### ISSUE TITLE
Show-UDToast -MessageSize parameter does not set unless -Title and -TitleSize are set

### ISSUE THREAD

**Issue by JLogan3o13** [ironmansoftware/powershell-universal#1000]
I was messing around with showing a Toast message today, trying to get the -MessageSize parameter to work. The docs just state it is a string parameter, with no indication of what that string should be. I tried "small", "large", "XL", "48px", etc. but no joy. Then, just for grins I added a Title to the toast message, and tried the -TitleSize parameter. That one worked when I use "large". See below:

if (!$boolAuth) {Show-UDToast -Duration 2000 -Title "Oops" -TitleSize "large" -Message "You must login first!"; Invoke-UDRedirect "/login"}

![image](https://user-images.githubusercontent.com/14804589/142708714-71c74a52-cad1-4d61-8f7d-47c0cbd439a1.png)

After setting this, I noticed that -MessageSize now works:

if (!$boolAuth) {Show-UDToast -Duration 2000 -Title "Oops" -TitleSize "large" -Message "You must login first!" -MessageSize "large"; Invoke-UDRedirect "/login"}

![image](https://user-images.githubusercontent.com/14804589/142708728-fcaaafb4-30e0-49d0-b6ee-e2429f3580b0.png)

- Universal: 2.5.4

**Comment by DataTraveler1** [comment]
Congrats on issue #1000 🎉

**Comment by JLogan3o13** [comment]
@adamdriscoll I know this is an old one, but I notice it is still an issue is 3.9.4. It seems textsize is somehow tied to having a title _and_ explicitly setting the title size. Once -Title and -TitleSize are set, I can set -MessageSize using either "small", "medium", or "large" or "12px", "48px", or "96px"

Edit: After submitting I noticed new behavior. Without specifying -Title or -TitleSize, -MessageSize using a standard size such as "large" still does not work. However, using "12" (px) works as long as the string is _only_ a string representation of the number and not "12px".

**Comment by mattselle** [comment]
We should now support large, small, ##px and just ##
