### ISSUE TITLE
receive and set history values/ make New-UdChart persistent ?

### ISSUE THREAD

**Issue by Just-Ch33s3** [ironmansoftware/powershell-universal#1002]
![1](https://user-images.githubusercontent.com/49145093/111914023-a9857c80-8a70-11eb-8449-47f52a611468.png)
Hi,
I've just got in touch with Powershell Universal Dashboard, so far its been a bliss ! Thanks for creating it!
My question would be if I can somehow make the the Charts persistent, even after a page refresh?
(I wouldnt mind receiving historic data first to fill the chart with some kind of a timestamp/value position if that should be possible)
My current configuration looks like this 
` New-UdColumn -Size 6 -Content {
New-UdMonitor -Title "CPU Load Percentage" -Type Line -DataPointHistory 200 -RefreshInterval 1 -ChartBackgroundColor '#80FF6B63' -ChartBorderColor '#FFFF6B63'  -Endpoint {
try {
(((Select-String -Path "C:\Users\_Scripts\logs\data.log" -Pattern "Ident:'/intelcpu/0/load/0' Value:'(\d+).*'").Matches.Groups[1])).Value | Out-UDMonitorData}
catch {
0 | Out-UDMonitorData
}
}
}`

Thanks for the help, have a good day! 
Christoph

**Comment by adamdriscoll** [comment]
I know this is really old but just poking through some older issues. You could do this with UDChartJS rather than a monitor. You would just set the $Data to whatever info you need and then update that data in a UDDynamic. 

```
    $Session:Iteration = 1
    New-UDDynamic -Content {
        $I = $Session:Iteration
        $Data = 1..$I | % { 
            [PSCustomObject]@{ Date = Get-Date; value = Get-Random }
        }
        New-UDChartJS -Type 'bar' -Data $Data -DataProperty Value -Id 'test' -LabelProperty Date -BackgroundColor Blue
        $I++
        $Session:Iteration = $I
    } -AutoRefresh -AutoRefreshInterval 1
```
