### ISSUE TITLE
Integration of the free TinyMCE Core WYSIWYG Editor as a new Component

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#1005]
### Summary of the new feature / enhancement

It would be great if PSU had a powerful WYSIWYG Editor like TinyMCE
https://github.com/tinymce/tinymce

### Proposed technical implementation details (optional)

Probably this one should be sort of a "copy paste" implementation 😊
https://github.com/tinymce/tinymce-react

**Comment by adamdriscoll** [comment]
This has been implemented as an external component: https://github.com/adamdriscoll/ud-tinymce
