### ISSUE TITLE
Disallow uploads of 2g or greater (New-UDUpload)

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1010]
### Summary of the new feature / enhancement

New-UDUpload should reject or otherwise inform the user that uploads of 2GB or higher will not actually be accepted. 

Note: This appears to be related to #685 from November 2021

### Proposed technical implementation details (optional)

Where technically feasible, check the length of the file that was selected to prevent files of 2GB or greater from being uploaded.

**Comment by DataTraveler1** [comment]
This also relates to forum post https://forums.ironmansoftware.com/t/new-udupload-is-not-working-for-zip-files/4715/39

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/new-udupload-is-not-working-for-zip-files/4715/44

**Comment by adamdriscoll** [comment]
Added this to the documentation: https://docs.powershelluniversal.com/userinterfaces/components/inputs/upload
