### ISSUE TITLE
Automatic formatting does not work

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1011]
# Steps to reproduce

1. Create a new PowerShell project in VS 2022
2. Add some unneeded spaces (whitespace) in front of a line of code
3. Initiate formatting by selecting it under 'Edit', 'Advanced', 'Format Document' (Ctrl+K, Ctrl+D)
4. Observe that the extra spaces are not removed
5. Perform the same steps with a different project type (e.g. C#) to compare

See animation in the Visuals section

# Expected Behavior
```
The extra spaces should be removed
```

# Actual Behavior
```
The extra spaces are not removed
```

# Environment
VS 2022 17.1.0
PowerShell Pro Tools 2022.2.1
PSScriptAnalyzer 1.20.0

# Visuals
![](https://user-images.githubusercontent.com/537287/155913275-b2466a37-96d4-41d1-beb0-ddbc6e844981.gif)

**Comment by adamdriscoll** [comment]
@DataTraveler1 - Can you please install this version and collect a log? 

https://www.dropbox.com/s/blueq0az5854dgq/PowerShellTools.2022.2022.3.0.vsix?dl=0

Logs are generated in %AppData%\PowerShell Tools for Visual Studio

**Comment by DataTraveler1** [comment]
@adamdriscoll - I have installed the extension (pictured) but somehow the log directory is empty (but present). Can you advise if there are any other settings needed to enable this log? I do remember seeing this in the past.

![image](https://user-images.githubusercontent.com/537287/156654460-a6f16799-7bdd-4944-99d1-0ef7b0e08ffc.png)

**Comment by adamdriscoll** [comment]
Whoops. I forgot you need to enable this. You might need to restart VS after enabling it. 

![image](https://user-images.githubusercontent.com/1256531/156790833-467678f3-ab9d-4cab-8c55-e13d1a209149.png)

**Comment by DataTraveler1** [comment]
@adamdriscoll - Thank you for the hint. Oddly, when I arrived to the settings, it was already enabled. I tried settings it to False, reopening VS2002, setting it to True and reopening VS2002. There is still no output in my %APPDATA%\PowerShell Tools for Visual Studio although the folder does exist.

I will try from a 2nd computer to see if I can replicate these results. Do you have any advice on how we can troubleshoot when the diagnostic log does not appear even though it is set to True and the application restarted?

**More**

On a 2nd computer also Windows 10 with a fresh install of VS2022, formatting worked like a champ as did the debug log. I am at a loss to find the difference.

**Comment by adamdriscoll** [comment]
@DataTraveler1 - Weird. I haven't seen that particular thing happen before. The only thing I would suggest would maybe be running a procmon trace on that machine to see if it's even trying to log. I guess I don't understand how that could be happening. Let me think about it.

**Comment by DataTraveler1** [comment]
> running a procmon trace on that machine

@adamdriscoll - On my 2nd machine where formatting does work, I am still unable to produce a diagnostic log even with the option enabled. In other words, I am not able to produce a log on either machine. I don't see any indicators that the expected folder is being written to in Procmon. Strangely, I do see past diagnostic logs there (i.e. log.devenv.exe.txt) so it is a mystery why I'm not able to get fresh logs now. 🤔

1. Can you advise is there more that needs to be done in order to enable diagnostic logging (besides setting the option from false to true and restarting VS2022)?

2. Can you confirm if diagnostic logging is working in the most current stable release?


Thank you!

**Comment by DataTraveler1** [comment]
@adamdriscoll - I finally have an update on this. I am able to work around this problem by removing the privateregistry.bin and then allowing VS2022 to recreate it. Basically, recreating my profile (user hive) registry key.

I did make backup copies of the before/after files but the not able to find any clues during comparison. I am not able to practically recreate the problem (yet). However, once the profile is reset then formatting (Ctrk+K, Ctrl+D) and diagnostic logging work as expected.

**Comment by DataTraveler1** [comment]
I'm assuming to close until the (apparent) issue with the user profile (privateregistry.bin) can be recreated and then at that point, open a new issue. The problem with formatting not working was worked around.
