### ISSUE TITLE
PSU 2.9.0 don't seem to refresh dashboard on pushing changes

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1015]
### Steps to Reproduce

Make a commit trough GIT then the dashboards that are affected are not refreshing

### Expected behavior

```console
Refresh dashboards
```

### Actual behavior

```console
Don't refreshing I need to restart the service
```

### Environment data

PSU 2.9.0 nightly build downloaded today 1/03/2022

**Comment by adamdriscoll** [comment]
Do you have auto deploy enabled for your dashboard? Also, can you let me know how your repo folder is setup? 

```
Repository \ 
    dashboard \ 
         dashboard.ps1
```

In my .universal\dashboard.ps1 file, I have this. 

```
New-PSUDashboard -Name "dashboard" -FilePath "dashboards\dashboard\dashboard.ps1" -BaseUrl "/dashboard" -Framework "UniversalDashboard:Latest" -SessionTimeout 0 -AutoDeploy -Credential "Default"
```

I tried this with the last 2.9 and it's working as expected with Git OneWay sync. I had to make sure to enable auto-deploy to ensure it would correctly restart. 

Also, are you still experiencing this issue with 2.9? 

https://github.com/ironmansoftware/issues/issues/993

**Comment by rwidmark** [comment]
> Do you have auto deploy enabled for your dashboard? Also, can you let me know how your repo folder is setup? 
> 
> 
> 
> ```
> 
> Repository \ 
> 
>     dashboard \ 
> 
>          dashboard.ps1
> 
> ```
> 
> 
> 
> In my .universal\dashboard.ps1 file, I have this. 
> 
> 
> 
> ```
> 
> New-PSUDashboard -Name "dashboard" -FilePath "dashboards\dashboard\dashboard.ps1" -BaseUrl "/dashboard" -Framework "UniversalDashboard:Latest" -SessionTimeout 0 -AutoDeploy -Credential "Default"
> 
> ```
> 
> 
> 
> I tried this with the last 2.9 and it's working as expected with Git OneWay sync. I had to make sure to enable auto-deploy to ensure it would correctly restart. 
> 
> 
> 
> Also, are you still experiencing this issue with 2.9? 
> 
> 
> 
> https://github.com/ironmansoftware/issues/issues/993

I'll check tomorrow I'm off work for now.

Good work with 2.9.0 you have fixed many of my issues and I have closed them :)
@adamdriscoll

**Comment by rwidmark** [comment]
@adamdriscoll I have it like this;


![image](https://user-images.githubusercontent.com/76907327/156316306-2423c3ca-eb5e-4383-a3f0-611a7bccc30f.png)

![image](https://user-images.githubusercontent.com/76907327/156316507-312e800f-2e42-47a3-b298-2a86da392f78.png)

And the structure I have it like this;
```
Repository \ 

    dashboards \ 

       NameOFDashboard \
                 dashboard.ps1
```
So to be more specific
I have folders under "C:\ProgramData\UniversalAutomation\Repository\Dashboards" that have the name of each dashboard and inside them I have the dashboard.ps1 file

I have it like that as I need to have many subfolders under dashboards as I need to have multiple dashboards.
So each subfolder under "dashboards" folder containes a dashboard.ps1 file.

And I also have the -AutoDeploy switch in the dashboards.ps1 file

**Comment by rwidmark** [comment]
@adamdriscoll any progress on this?

**Comment by adamdriscoll** [comment]
I will check again today and setup the structure like you have it. That's my only difference.

**Comment by rwidmark** [comment]
> I will check again today and setup the structure like you have it. That's my only difference. 

Ok, hope you can reproduce it as when I rewert back to 2.7.3 everything works fine.

**Comment by adamdriscoll** [comment]
Ah, ha! I got it. The problem was in casing. We were doing a case-sensitive comparison on the paths and it was preventing the dashboard from restarting.

**Comment by rwidmark** [comment]
> Ah, ha! I got it. The problem was in casing. We were doing a case-sensitive comparison on the paths and it was preventing the dashboard from restarting. 

Good work :)
