### ISSUE TITLE
Align -PaginationLocation with the Search when it's on the top

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1016]
### Summary of the new feature / enhancement

As you can see in the picture the alignment are not that good when your having the Pagination location on top.
It should align with the search box and be to the left side as it is today.

![image](https://user-images.githubusercontent.com/76907327/156131933-133c3f7b-d6d6-4186-a2e6-328665f29a46.png)

**Comment by rwidmark** [comment]
@adamdriscoll i love PSU and all of your work but this alignment is Apple Maps bad (when it was released) or maybe windows vista bad. •irony•

**Comment by adamdriscoll** [comment]
Including a title makes it look much better. 

![image](https://user-images.githubusercontent.com/1256531/157463612-83011d00-c7b2-4c00-b2d2-89f42be60da0.png)

**Comment by adamdriscoll** [comment]
Fixed version: 

![image](https://user-images.githubusercontent.com/1256531/157464435-adca8e13-c558-460e-951a-62a64b915aaa.png)

**Comment by rwidmark** [comment]
Love it :)
