### ISSUE TITLE
Docker ARM images have incorrect architecture

### ISSUE THREAD

**Issue by bradlane** [ironmansoftware/powershell-universal#1024]
### Steps to Reproduce

Docker hub shows the images with "arm" in their tag names as having "linux/amd64" as their architecture:
https://hub.docker.com/layers/ironmansoftware/universal/2.8.3-ubuntu-latest-arm64v8/images/sha256-94b067bd3f8c471b64d35796a6db06c553ef3cd05450d0a9a00c1597253e75bf

Testing on a Raspberry Pi:
pi@raspi:~ $ docker run -it --rm ironmansoftware/universal:2.8.3-ubuntu-latest-arm64v8
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
pi@raspi:~ $ uname -a
Linux raspi 5.10.63-v8+ #1496 SMP PREEMPT Wed Dec 1 15:59:46 GMT 2021 aarch64 GNU/Linux

### Expected behavior

```console
Expect container to start
```

### Actual behavior

```console
Container does not start
```

### Environment data

n/a

**Comment by aevans1987** [comment]
Bumping this as i just ran head first into this as well.

**Comment by abrahamYG** [comment]
Hi, I am still getting the same error on `ironmansoftware/universal:3.7.13-ubuntu-latest-arm64v8`

**Comment by bradlane** [comment]
the ARM build zip file on the downloads page works fine, so I've manually created my own Dockerfile and build an ARM container from that until this is addressed.  

I'm not the best at always keeping it current, but it's available for all here: 
 [https://hub.docker.com/r/lanehq/psuniversal/tags](https://hub.docker.com/r/lanehq/psuniversal/tags)
