### ISSUE TITLE
Add visual indicator on save for "Save Settings" button in script edit page

### ISSUE THREAD

**Issue by IdahoVandal** [ironmansoftware/powershell-universal#1032]
### Summary of the new feature / enhancement

When editing script settings, in the script editor dialog, there is no indicator the "Save Settings" button completed successfully. You just have to assume it worked and reload the page to confirm. It would be nice to see something similar to the Code Editor Save button where it displays a quick "Changes Saved" message.

![image](https://user-images.githubusercontent.com/78939229/157501951-1ccb3163-b808-4e74-934a-1d5868650513.png)

**Comment by adamdriscoll** [comment]
This is one of those things that I've hated for so long but haven't fixed. Thanks for the kick in the butt.
