### ISSUE TITLE
Unable to set $Cache: variables in API

### ISSUE THREAD

**Issue by waikinw** [ironmansoftware/powershell-universal#1038]
### Steps to Reproduce

Have APIs that use $Cache variable in 2.9.1 in conjunction with Get-ADObject. These are failing now.

### Expected behavior

```console
$Cache:CurrentDate = (Get-Date)
$Cache:CurrentDate

Returns date
```

### Actual behavior

```console
$Cache:CurrentDate = (Get-Date) #throws error on set.
```

### Environment data

PSU 2.9.1

**Comment by adamdriscoll** [comment]
This has been resolved in 2.9.2.
