### ISSUE TITLE
PSScriptPad for macOS Apple Silicon native

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1042]
Would be great if it's possible to port PSScriptPad to macOS Apple Silicon?

**Comment by rwidmark** [comment]
@adamdriscoll please :)

**Comment by rwidmark** [comment]
@adamdriscoll bump again.
Your wife if I remember correctly has a MacBook Air m1 so I guess she needs this also 😆

**Comment by adamdriscoll** [comment]
@rstolpe It's super unlikely this will actually happen with the current implementation of PSScriptPad. It is built on .NET Framework and would require a full rewrite to get it working cross platform and the 3rd library we bought to implement it also doesn't support cross platform. 

I'm curious what you're after with it. The main features: 

- Form Designer
- WPF Designer 
- Packager
- Script Editor
- Debugger

Anything specific that you want it for? A can be done with the VS Code extension that is similar to PSScriptPad.

**Comment by rwidmark** [comment]
@adamdriscoll I wanted it for wpf design.

But I guess that I can do it some other way.
