### ISSUE TITLE
Variables.ps1 -type is missing with strinf

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1047]
### Steps to Reproduce

Add a string variable in admin gui.

### Expected behavior

```console
Showing -type string in variables.ps1
```

### Actual behavior

```console
-type are not included for string in variables.ps1 but if you choose bool then it’s showing -type bool
```

### Environment data

PSU 2.9.2

**Comment by adamdriscoll** [comment]
String is just the default value so we don't show it. In the future, we won't include the -type parameter at all when generating this command and will just ignore it if it is there.
