### ISSUE TITLE
New-UDTextBox -Mask causes input issues

### ISSUE THREAD

**Issue by Entech-Ramon** [ironmansoftware/powershell-universal#105]
**Describe the bug**
Using New-UDTextbox with the Mask parameter and providing a input mask works, but when you type a single character and then it loses focus, you have to click in the box again and type another character, one character at a time.

**To Reproduce**
Command to use.
New-UDTextbox -Id ‘MACAddress’ -Placeholder “00:00:00:00:00:00” -Mask @(’/[0-9a-fA-F]/’, ‘/[0-9a-fA-F]/’, “:”, ‘/[0-9a-fA-F]/’, ‘/[0-9a-fA-F]/’, “:”, ‘/[0-9a-fA-F]/’, ‘/[0-9a-fA-F]/’, “:”, ‘/[0-9a-fA-F]/’, ‘/[0-9a-fA-F]/’, “:”, ‘/[0-9a-fA-F]/’, ‘/[0-9a-fA-F]/’, “:”, ‘/[0-9a-fA-F]/’, ‘/[0-9a-fA-F]/’)

**Expected behavior**
You should be able to keep typing and the textbox not loose focus.

**Version**

Version Number: 1.5.14
Dashboard Framework (if applicable): 3.3.3
Operating System: Ubuntu Docker

**Additional context**
https://forums.ironmansoftware.com/t/new-udtextbox-mask-for-mac-address/4502

**Comment by johnyoakum** [comment]
@adamdriscoll I just installed the nightly build, version 1.5.19, I have the dashboard frameworks for Latest, as well as 2.9.9, 3.3.5, and 3.3.6, and I am still experiencing this behavior. Am I missing something?
