### ISSUE TITLE
Pages: Hyperlink column for tables

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1064]
### Summary of the new feature / enhancement

https://forums.ironmansoftware.com/t/pages-feature-requests/6821

**Comment by ClarkRSD** [comment]
Just to add a little more to this, I think it would be great to be able to click hyperlinks via buttons as well.

So if I had a hyperlink, then give me the ability to just make a button for that particular area a clickable button that then goes to said hyperlink.
