### ISSUE TITLE
Combine New-UDAutocomplete and New-UDSelect

### ISSUE THREAD

**Issue by Entech-Ramon** [ironmansoftware/powershell-universal#108]
**Is your feature request related to a problem? Please describe.**
I really like the New-UDAutocomplete input component, however the options parameter only allows having an array of strings and not label:value pairs like the New-UDSelect allows for. I currently use the component created by PSDevUK New-UDSingleSelector, which is exactly what I'm looking for, however it does not work well with dashboard v3 dark theme in PSU.

**Describe the solution you'd like**
New-UDAutocomplete with the options to have a the listed items be in an arrary of label:value pairs. 

**Describe alternatives you've considered**
Used New-UDSingleSelector from psdevuk, but that component doesn't work well with the new dark theme of dashboard v3

**Additional context**
https://marketplace.universaldashboard.io/Dashboard/UniversalDashboard.UDSingleSelector
https://forums.ironmansoftware.com/t/new-multi-or-single-select-component-for-universaldashboard/1902/57

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/autocomplete-select-behavior/8222/2
