### ISSUE TITLE
Manual Filter Options for UDTable with Server Side Processing.

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1097]
### Summary of the new feature / enhancement

https://forums.ironmansoftware.com/t/manual-filter-options-for-udtablecolumn-in-a-udtable-with-loaddata/6262

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/manual-filter-options-for-udtablecolumn-in-a-udtable-with-loaddata/6262/5

**Comment by realslacker** [comment]
This would be handy, because you might want to filter results from a DB query based on a known set of values and by default the select is populated by the current list of results vs unique items in that particular column overall.

For instance I might want to populate this with a query like:

```sql
SELECT column_name FROM table_name GROUP BY column_name
```

**Comment by Omzig** [comment]
@adamdriscoll, bump?

New-UDTableColumn -FilterData "Open","OnHold" -ShowFilter -FilterType select

**Comment by JoriPS1** [comment]
Bumping this as well
