### ISSUE TITLE
Check and Install PS7 Versions

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1107]
### Summary of the new feature / enhancement

PowerShell Universal should check for the latest PS7 versions and have a feature to install them.

**Comment by Viajaz** [comment]
Keep in mind, PowerShell 7 Updates are now also available from the Microsoft Update Catalog
https://www.catalog.update.microsoft.com/Search.aspx?q=PowerShell%20v7

**Comment by adamdriscoll** [comment]
True. It would be good for non-Windows systems as well.
