### ISSUE TITLE
VS 2019 locked after PowerShell Pro Tools extension update

### ISSUE THREAD

**Issue by MalcolmEllis** [ironmansoftware/powershell-universal#1118]
**Describe the bug**
After updating the PowerShell Pro Tools extension today I closed VS. It's Patch Tuesday so there were some Windows updates pending, I completed those and rebooted. I had noticed the updates included .Net related patches so I checked VS Installer for VS updates, and updated VS 2019 to 16.11.12. Now when I try to open a solution in VS 2019 I get a large black PowerShell Tools dialog and two error dialogs. All of these are unresponsive, I can't click any buttons or close them at all, seem to be deadlocked or there's yet another dialog hidden away that I can't reach. VS is partially responsive but hasn't loaded the solution and is unusable. All these updates completed smoothly so they may have nothing to do with this issue but I figured it best to describe the sequence.

**Screenshots**

![2022-04-12_20-50-22](https://user-images.githubusercontent.com/5017590/163082552-09a2e64c-12d5-408d-be82-996e541947c3.png)

Operating System: Windows 10

**Logs**

section of the VS activitylog.xml:
 
  <entry>
    <record>1485</record>
    <time>2022/04/13 00:47:55.882</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [PowerShellToolsPackage]</description>
    <guid>{0429083F-FDBC-47A3-84FF-B3D50343B21E}</guid>
  </entry>
  <entry>
    <record>1486</record>
    <time>2022/04/13 00:47:56.770</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [PowerShellToolsPackage]Source: &apos;WindowsBase&apos; Description: Dispatcher processing has been suspended, but messages are still being processed.&#x000D;&#x000A;System.InvalidOperationException: Dispatcher processing has been suspended, but messages are still being processed.&#x000D;&#x000A;   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)&#x000D;&#x000A;   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)&#x000D;&#x000A;   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)&#x000D;&#x000A;   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)&#x000D;&#x000A;   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)&#x000D;&#x000A;   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)&#x000D;&#x000A;   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)&#x000D;&#x000A;   at MS.Win32.UnsafeNativeMethods.MessageBox(HandleRef hWnd, String text, String caption, Int32 type)&#x000D;&#x000A;   at System.Windows.MessageBox.ShowCore(IntPtr owner, String messageBoxText, String caption, MessageBoxButton button, MessageBoxImage icon, MessageBoxResult defaultResult, MessageBoxOptions options)&#x000D;&#x000A;   at System.Windows.MessageBox.Show(String messageBoxText, String caption, MessageBoxButton button, MessageBoxImage icon)&#x000D;&#x000A;   at PowerShellTools.PowerShellToolsPackage.&lt;InitializeAsync&gt;d__32.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass20_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.UIThreadReentrancyScope.WaitOnTaskCompleteInternal(Task task, CancellationToken cancel, Int32 ms)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.UIThreadReentrancyScope.WaitOnTaskComplete(Task task, CancellationToken cancel, Int32 ms)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.&lt;&gt;c__DisplayClass100_1.&lt;InternalGetResult&gt;b__1()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.IgnoreObjectDisposedException(Action action)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.&lt;&gt;c__DisplayClass100_0.&lt;InternalGetResult&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.&lt;&gt;c__DisplayClass108_0.&lt;InvokeWithWaitDialog&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InvokeWithWaitDialog[T](Func`1 function)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InvokeWithWaitDialog(Action action)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()</description>
    <guid>{0429083F-FDBC-47A3-84FF-B3D50343B21E}</guid>
    <hr>80131509</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>1487</record>
    <time>2022/04/13 00:47:56.787</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [PowerShellToolsPackage]</description>
    <guid>{0429083F-FDBC-47A3-84FF-B3D50343B21E}</guid>
    <hr>80131509</hr>
    <errorinfo></errorinfo>
  </entry>

Please upload a log. Logs are found in $Env:AppData\PowerShellProTools\ by default. 

No logs found.

**Comment by adamdriscoll** [comment]
We released an update to prevent this dialog from being shown at start up. Can you please upgrade to the latest version?

**Comment by adamdriscoll** [comment]
I haven't heard back so I'm closing this issue. If you are still experiencing this, please feel free to open it again.
