### ISSUE TITLE
New-UDTable -StickyHeader does not work

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1119]
### Steps to Reproduce

https://forums.ironmansoftware.com/t/new-udtable-sticky-header-parameter-doesnt-work/6951/2

### Expected behavior

```console
The table header is sticky.
```

### Actual behavior

```console
The table header is not sticky.
```

### Environment data

2.10

**Comment by adamdriscoll** [comment]
You will need to use `-MaxHeight` when using `-StickHeader` for it to work properly.

**Comment by Omzig** [comment]
#reopen

does not seem to work
```powershell
 New-UDTable -Data $data2 -Dense -MaxHeight 415 -StickyHeader -Columns @( 
```
