### ISSUE TITLE
Allow us to disable individual buttons that are added to the editor/title bar.

### ISSUE THREAD

**Issue by futuremotiondev** [ironmansoftware/powershell-universal#1132]
I don't use the "Run in new terminal", "Run selection", or "Quick Scripts" features, and I'd like to turn their respective icons off so I can save screen real-estate. 

**Describe the solution you'd like**
A setting in the extension settings to disable icons.

**Describe alternatives you've considered**
Short of editing the package.json, nothing.

**Additional context**

Here are the icons in question:

![Code_f06NW7RstX](https://user-images.githubusercontent.com/33441569/163663768-9cfb64ca-5572-41dd-9e30-087f23c28353.png)

Thanks.

**Comment by adamdriscoll** [comment]
This has been added to the next version. Note that Run Selection is provided by the PowerShell extension and not PowerShell Pro Tools so we won't be able to disable that one.

**Comment by futuremotiondev** [comment]
Great! Thank you so much, I appreciate the great support.
