### ISSUE TITLE
Dashboards: offer a way to work with dashboards that consist of pages in seperate files

### ISSUE THREAD

**Issue by HansenRene** [ironmansoftware/powershell-universal#1137]
### Summary of the new feature / enhancement

Currently, it seems that the only way to work with dashboards split into multiple files, is to log on the the actual server, or maybe share the folder with dashboard files.

It would be very nice to be able to access those files through the admin console - or maybe, since this would be an advanced feature, allow some way of doing it through the VS code extension.

### Proposed technical implementation details (optional)

one option could be to make "Dashboard with multiple files" a seperate thing. maybe check a box upon creating a new dashboard, and the dashboard would be created inside a folder in the dashboard repository, and everything inside that folder can be accessed in the admin console/extension.

**Comment by adamdriscoll** [comment]
This has been implemented in v3. We now have a repository editor that can access all the files of the repository (including all files in the for a dashboard). We'll be hooking that into the VS Code extension once v3 is released.

**Comment by adamdriscoll** [comment]
The VS Code extension has also been updated to accommodate this. It's not released yet but will be released alongside v3.
