### ISSUE TITLE
Invoke-PSUEndpoint 

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1143]
### Summary of the new feature / enhancement

Similar to Invoke-PSUScript, this would allow executing an API endpoint using -Integrated mode. 

https://forums.ironmansoftware.com/t/invoke-psuendpoint/6993/2

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/invoke-psuendpoint/6993/2

**Comment by SolidOceanTrust** [comment]
Hi @adamdriscoll this would be a very welcome addition as I have encountered a few use-cases where this would be helpful. An `-Internal` switch, inter-api specific apptoken, or similar functionality to `GrantPSUAppToken` would be awesome.

Happy to discuss further if you'd like.
Thanks!
