### ISSUE TITLE
Trigger "failed" or "error" to show in status for jobs

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1150]
### Summary of the new feature / enhancement

Today you can use write-warning "Warning" to set the status to warning in jobs.
![image](https://user-images.githubusercontent.com/76907327/165584068-e618715e-52af-4222-98f1-69d4e2807175.png)

It would be great if you also can flag it as "Failed" or "Error" with write-error "error"

**Comment by adamdriscoll** [comment]
This is possible if you set the Error Action Preference for the script to Stop

**Comment by rwidmark** [comment]
> This is possible if you set the Error Action Preference for the script to Stop 

Yes and no. If I don't want it to stop then?
I maybe only want to flag it as a error like with warning

**Comment by adamdriscoll** [comment]
Good point and this is actually a bug in my opinion. For example, if you set the job to error action Stop it doesn't actually stop. It continues. 

```
Write-Error "Test"

"Output"
```

![image](https://user-images.githubusercontent.com/1256531/167305444-89d80869-4d93-41ff-9cda-cf63a0e92b43.png)
