### ISSUE TITLE
New-UDAutocomplete , Icon and onEnter

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1157]
### Summary of the new feature / enhancement

Add so we can add icon in the beginning of the autocomplete as we can do for textbox.
-Icon (New-UDIcon -Icon 'user')

Also add OnEnter :)

**Comment by rwidmark** [comment]
Was this fixed with the icon @adamdriscoll ? Can't find anything in the documentation regarding it.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/new-udautocomplete-icon-support/7254/1
