### ISSUE TITLE
Git Sync - Too Many Redirects

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1160]
### Steps to Reproduce

https://forums.ironmansoftware.com/t/git-sync-failing-too-many-redirects-or-authentication-replays/7050/4

### Expected behavior

```console
Git sync succeeds
```

### Actual behavior

```console
Git sync fails with too many redirects
```

### Environment data

2.10.2

**Comment by kamilkosek** [comment]
Currently this issue is happening too at a customers site. They are using Azure Devops.
We tried both ways , with a password and with PAT´s - neither worked.
If you need additional information or even a remote session to investigate, feel free.

**Comment by adamdriscoll** [comment]
@kamilkosek - The error pretty much means "we didn't authenticate correctly and we are providing no information what so ever". The error is coming directly from the lib2git library and literally provides no additional context as to why it's happening. 

I've been messing around with avoiding the lib2git library authentication by providing the credentials in the git remote URL. 

Can you please try this format for your git remote URL? I was able to authentication with a different, invalid PAT listed in my GitPassword setting. It seems to ignore the GitUserName and GitPassword when using this GitRemote format. 

```
"GitRemote": "https://adamdriscoll:<MyPatGoesHere>@github.com/ironmansoftware/shiny-octo-waffle.git",
```

Note, that this will be displayed in the admin console so is only a diagnostic\debugging step. We'll be adding some masking to avoid displaying this at all.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/git-sync-failing-too-many-redirects-or-authentication-replays/7050/5

**Comment by TurnItOff-OnAgain** [comment]
Using Gitlab for my git host. I created a PAT and put it in the GitRemote field, it is showing with the updated URL in the admin console and I am still getting the error

![image](https://user-images.githubusercontent.com/26926284/169319891-c93f83ff-bea6-40b5-b4a1-9abb40caa829.png)

**Comment by adamdriscoll** [comment]
@TurnItOff-OnAgain Bummer. Thanks for giving that a shot. My next trick is to try to avoid lib2git all together and allowing some sort of integration with git.exe to see if we can achieve success in that way. Instead of calling the lib2git clone method, we could offer a way to call git commands at certain times. My hope is that will provide additional information if it fails and additionally provide us with a way to provide different command line options.

**Comment by mikebuckley** [comment]
Any update on this?   I seem to be experiencing similar issues.  Tried the work around, NoGo.

**Comment by kamilkosek** [comment]
Hi @adamdriscoll ,
do you have any update on this ? 
This currently gets really annoying, because there are many people working with Universal and the code repositry and we are getting conflicts on a regular basis.

**Comment by adamdriscoll** [comment]
Just an update on this issue. In v3.3, we have added support for using an external git client. Rather than using the libgit2 library within PSU, PSU will call git.exe and run commands just like other tools like VS Code. This means you have more configuration options and we avoid the libgit2 issues all together. 

You will also be able to use SSH rather than HTTPS so there shouldn't be any redirecting going on and you can install SSH keys on your PSU server to avoid having to pass credentials manually to PSU.
