### ISSUE TITLE
Add alternative labeling options for UDTable export button

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1161]
### Summary of the new feature / enhancement

Consider adding an alternative labeling option for the export button in a UDTable. See forum post [#7042](https://forums.ironmansoftware.com/t/export-button-label/7042) for background.

The only existing indicator of the export button is an icon which might not be preferred.

### Proposed technical implementation details (optional)

![image](https://user-images.githubusercontent.com/537287/166819068-349702ba-b216-49c3-80b0-f3b2773a6c96.png)
###### figure shows screenshot from the related forum post

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/export-button-label/7042/4

**Comment by adamdriscoll** [comment]
I added -Export to New-UDTableTextOption to adjust this text.
