### ISSUE TITLE
New-PSUEnvironment assumes non-Store pwsh location

### ISSUE THREAD

**Issue by potatoqualitee** [ironmansoftware/powershell-universal#1166]
### Steps to Reproduce

after installing the choco dashboard, i got some errors about pwsh not existing and it's bc it's looking for it in the wrong location, as I'm running pwsh from the Windows Store.

```
New-PSUEnvironment -Name 'PowerShell' -Path 'C:\Program Files\PowerShell\7\pwsh.exe' -Variables *
```

### Expected behavior

```console
Knows where pwsh is
```

### Actual behavior

```console
errors
```

### Environment data

Windows 11 with pwsh installed from the store

Seems it exists at $home\AppData\Local\Microsoft\WindowsApps\pwsh.exe

**Comment by potatoqualitee** [comment]
I found the above path using `get-command pwsh | select source`

**Comment by adamdriscoll** [comment]
Thanks for reporting this. This will be fixed in the next build.
