### ISSUE TITLE
Set secure value (variable) in OneWay gitsync

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1167]
### Summary of the new feature / enhancement

It should be possible to Set secure value if it's missing when GitSync is on OneWay.

Today you need to change the GitSync to TwoWay to just set secure value (That are done in valute and no real change in PSU config) and then change back to OneWay sync.

It should be perfect to set secure value on missing ones when GitSync is set to OneWay.
As I have one test server that I push code to and then when the code are validated I push it to prod that are OneWay and if I have added new secure variabels to the test server it's a hassel to just change it to two-way then back to oneway in prod etc.

I'm guessing you understand @ad

**Comment by adamdriscoll** [comment]
I thought we had already implemented this so I'll see if it needs fixing or something.

**Comment by adamdriscoll** [comment]
I just tried this and it works for me. I have a secret set in my variables PS1. 

```powershell
New-Variable -Name 'Secret' -Vault 'BuiltInLocalVault'
```

When I do the git one-way sync, I see this in the UI and then set the secret from the modal. 

![image](https://user-images.githubusercontent.com/1256531/168645685-c055a365-5f4e-4747-bc98-90a654c44807.png)

I then double checked that the value was set correctly. 

![image](https://user-images.githubusercontent.com/1256531/168645907-ad8fdcf5-9c41-496b-a2d9-a80d53e3e6ad.png)

**Comment by adamdriscoll** [comment]
@rstolpe - Can you verify that you were experiencing this on 2.11.1? I still cannot reproduce the problem.

**Comment by rwidmark** [comment]
> @rstolpe - Can you verify that you were experiencing this on 2.11.1? I still cannot reproduce the problem. 

I did try it now with 2.11.1 and it's working

**Comment by adamdriscoll** [comment]
Thanks!
