### ISSUE TITLE
Double dollar will break endpoints

### ISSUE THREAD

**Issue by mojoaar** [ironmansoftware/powershell-universal#1180]
### Steps to Reproduce

If you wrongly type double dollar in a new endpoint, it will break the endpoints page and display nothing. Code editor will display wrong format, but it will be saved successfully and afterwards the endpoints page will be blank.

Example:
`$var = $($$foo.bar)`

### Expected behavior

```console
Don't break endpoints page, throw an error about wrong format when the new endpoint is saved.
```

### Actual behavior

```console
Mark changes saved and endpoints page is blank until the wrongly code is removed from Configurations -> Endpoints.ps1
```

### Environment data

Version: 2.10.2

### Visuals

Code is fine:
![psu_no_bug](https://user-images.githubusercontent.com/21560785/168961261-d89040a9-96fd-4b71-b907-262b70aebc0b.png)

Double dollar:
![psu_double_dollar_bug](https://user-images.githubusercontent.com/21560785/168961292-ba16e211-5b5d-4d01-94d5-6405cdf70d51.png)

Endpoint page is blank:
![psu_double_dollar_bug_empty_endpoints](https://user-images.githubusercontent.com/21560785/168961323-8af7986f-315d-4ee8-a061-5d12e1e09256.png)

**Comment by Viajaz** [comment]
I think #599 would help mitigate syntax issues, in specific endpoints definitions, affecting other endpoints (in the future at least)

**Comment by adamdriscoll** [comment]
I'll do a syntax check before saving so we can at least isolate the bad endpoint.

**Comment by adamdriscoll** [comment]
This is what will happen in 2.11.2 and going forward. 

![image](https://user-images.githubusercontent.com/1256531/169072953-96cc997c-b745-4ab7-9c11-264aa787b8b9.png)

**Comment by DataTraveler1** [comment]
@adamdriscoll I came here to post about this and then I see that @mojoaar already did. However, the problem still persists in 2.11.2 (nightly build 2387822576).

Steps to recreate the issue I ran into which is very similar:

1. Go to Configuration and edit the Endpoints.ps1
2. Add some unneeded text at the bottom like pic below and save it

![image](https://user-images.githubusercontent.com/537287/170451018-44831f73-fab5-4d14-8624-06b0314dacbd.png)

100% of the endpoints are now unavailable but there is no warning. My suggestion is that if there are 0 endpoints showing in the UI even though endpoints.ps1 is populated, then the user should be warned to check their endpoints.ps1 for a problem.

![image](https://user-images.githubusercontent.com/537287/170451273-7d0d8a61-3af1-4b13-a30b-902baa57337d.png)

**Comment by adamdriscoll** [comment]
@DataTraveler1 - That's a good point. What I fixed is slightly different. If you go into an individual endpoint and enter some text that is of an invalid syntax, try saving it and you will see if responds by preventing the syntax error from being persisted. I think we should open a new issue for this case because this affects all PSU configuration files so we should have a more general fix. 

You'll have to edit the endpoint from the APIs \ Endpoint editor to see this behavior.

**Comment by DataTraveler1** [comment]
@adamdriscoll 

> you will see if responds by preventing the syntax error from being persisted

Indeed, it does work as described. I might suggest something additional (e.g. pop-up imagined below) to let the user know what happened as it might be a bit startling 😲 to the unsuspecting end-user.

![image](https://user-images.githubusercontent.com/537287/170538689-e3aa3453-e527-4094-a6ef-f1c8d1dbb65f.png)

> open a new issue for this case because this affects all PSU configuration files

#1203 has been raised. Thank you! ✔

Edit # 1: typo removed
