### ISSUE TITLE
Floating Action Button does not "float"

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#1181]
### Steps to Reproduce

- Take your example from the doc:
https://docs.powershelluniversal.com/userinterfaces/dashboards/components/inputs/floating-action-button

New-UDFloatingActionButton -Icon (New-UDIcon -Icon user) -OnClick {
    Show-UDToast -Message "Hello!"
}

- Put it anyware on a dashboard.
- Make sure you have a scrollable page (enough content on it)
- Scroll...

### Expected behavior

```console
It should float and stay on top of everything
```

### Actual behavior

```console
It does not and sticks just there where you've created it.
Also it is not at the usual place like bottom right.
Maybe it should also include a positional parameter for that...
```

### Environment data

Tested on 3.0 beta 2

**Comment by adamdriscoll** [comment]
Adding -Position to the next version. 

Position will default to Relative (current behavior) but you can also set BottomRight or BottomLeft to have it to pin to the bottom left or right.

**Comment by donlent** [comment]
Dear @adamdriscoll 

Sorry for reopening this issue.
Thanks for having added the Positional parameter which works really well.
However the floating issue is still present.
When you scroll a page the FAB will still stick at it's initial position. It should always be on top independently of the scroll behavior.

Could you re-check that please?

Thanks,
Don
