### ISSUE TITLE
Set Filter Values for UDTable AutoComplete filters

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1182]
### Summary of the new feature / enhancement

can i pre-set 2 valure from filter in New-UDTableColumn -Property status -Title Stato -IncludeInExport -IncludeInSearch -ShowFilter -FilterType AutoComplete

I can view “Open” and “Onhold” by default and not “Closed”

![image](https://user-images.githubusercontent.com/1256531/169053852-4dea4140-4d26-410f-8e8d-86c022ff6a31.png)

**Comment by Omzig** [comment]
@adamdriscoll, this would be super helpful when we use -DataLoad on a table so that we can select a distinct list of select values to provide the user, and then when they select it, it sends a where statement in. 

Can you bump this?

New-UDTableColumn -SelectData "Open","OnHold"

**Comment by MikeShepard** [comment]
Being able to set the filter dynamically would be super-helpful.

+1

**Comment by Omzig** [comment]
@adamdriscoll, is there documentation for this feature?
