### ISSUE TITLE
Restrict RunAs Credentials to roles

### ISSUE THREAD

**Issue by mwatts-seg** [ironmansoftware/powershell-universal#1183]
### Summary of the new feature / enhancement

It would be nice to be able to restrict access to credentials for Run As to specific roles. 
From an enterprise perspective, we want to be able to expand this product out further in our organization but restrict who can use what credentials. 

Even if restricting to one role, but the Administrator role should always have access to credentials. 

### Proposed technical implementation details (optional)

When adding a credential or editing, there should be a new drop down for 'Authorized Role'. Even if Administrator is not selected, it should be automatically added. Additionally, we could specify 'None' to only show for Administrator. 

The scripts Run As Credentials should only show authorized credentials for the user role. 

EDIT: Would also be nice to simply turn off the ability for specific scripts to use different credentials, such as the script is out of scope for using different credentials.

**Comment by gsterk** [comment]
I would agree with this, it would be a very nice addition to allow us to configure secrets to only be usable by certain users/roles, so we can support those that need to edit scripts, but not allow them to run with highly privileged accounts.
