### ISSUE TITLE
Incorrect Timezone in Docker Container

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1193]
### Steps to Reproduce

> My Docker container running PS Universal is running using "timezone=Europe/Oslo”:

```
docker run --name powershelluniversal -e "TZ=Europe/Oslo" -v "/volume1/docker/powershelluniversal:/home/data"  --rm -d  -p 5002:5000/tcp universal-persistent:latest
```
 
> From within the container, this looks good (CEST = Europe/Oslo):

```
date
Sun May 22 08:20:04 CEST 2022
```

> Also, if I run Get-Date within a script run via PS Universal – the correct time is returned.
> However, looking at the scheduled jobs, “Next execution” is off by 2 hours - so they are running in GMT:
> I then changed from “System Default” as the “Timezone” value within each schedule to “Europe/Oslo”:
> Then it looks better:

 

### Expected behavior

```console
System Default Timezone is correct
```

### Actual behavior

```console
System time zone is set to GMT
```

### Environment data

v2.11.2

**Comment by urskog84** [comment]
Same behaviour when using the msi file. expected to have samte TimeZone as local system

```
PS C:\ProgramData\UniversalAutomation\Repository> Get-TimeZone


Id                         : W. Europe Standard Time
DisplayName                : (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
StandardName               : W. Europe Standard Time
DaylightName               : W. Europe Daylight Time
BaseUtcOffset              : 01:00:00
SupportsDaylightSavingTime : True
```
