### ISSUE TITLE
The Logon auth page should check for an updated token cookie periodically and automatically redirect

### ISSUE THREAD

**Issue by x86Since8088** [ironmansoftware/powershell-universal#1194]
### Steps to Reproduce

Have multiple tabs open to a PowerShell Universal server.
Wait for authentication timeout or restore browser session.
Observer multiple tabs on the /login page.
Authenticate on one

The remining /Logon pages do not redirect automatically to their ReturnUrl= location even though there is now a good token.

### Expected behavior

```console
In most modern web applications, authentication pages will check for an existing good authentication token and automatically redirect.  This behavior is for when reauthentication happens on one browser tab and then the user selects a different tab containing that is also waiting for authentication.  The user shoudl not have to edit the url and remove "login?ReturnUrl=".
```

### Actual behavior

```console
The remining /Logon pages do not redirect automatically to their ReturnUrl= location even though there is now a good token.
```

### Environment data

{
    "Name":  "2368235129/PowerShellUniversal.3.0.0-beta7.msi",
    "Url":  "https://imsreleases.blob.core.windows.net/universal-nightly/2368235129/PowerShellUniversal.3.0.0-beta7.msi",
    "LastModified":  {
                         "value":  "\/Date(1653266725000)\/",
                         "DisplayHint":  2,
                         "DateTime":  "Sunday, May 22, 2022 7:45:25 PM"
                     }
}

**Comment by Omzig** [comment]
can we make the time the token is valid a setting?

**Comment by adamdriscoll** [comment]
The sessionTimeout setting in appsettings.json controls this.
