### ISSUE TITLE
Add-UDElement Doesn’t Update Code Editor Object

### ISSUE THREAD

**Issue by MoppyDev** [ironmansoftware/powershell-universal#12]
I can set-udelement by setting the code property = “text here”, but I can’t add on to that code with add-udelement as the documentation states I should be able to.

`New-UDCodeEditor -Id “test” `
` Add-UDElement -parentid “test” -content {“text here”}`

**Comment by adamdriscoll** [comment]
We won't be adding support for Add-UDElement but you can work around this by doing this. 

```
    New-UDCodeEditor -Id "test" -Height 300
    New-UDButton -Text 'Test' -OnClick {
        $Code = (Get-UDElement -Id 'test').Code
        Set-UDElement -Id "test" -Properties @{ code = $Code + "text here"}
    }
```
