### ISSUE TITLE
Errant data within endpoints.ps1 can prevent all endpoints from functioning

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1203]
### Steps to Reproduce

1. Go to Settings -> Configuration and edit the Endpoints.ps1
2. Add some unneeded text at the bottom and save it (_pictured immediately below_)
3. Select Endpoints under API and observe that the list is now empty (_pictured further below 🔽 in the Visuals section_). Also, previously working endpoints will now return error 404.

![image](https://user-images.githubusercontent.com/537287/170451018-44831f73-fab5-4d14-8624-06b0314dacbd.png)

### Expected behavior

```console
The list of Endpoints under the API menu should warn the end-user if something appears to be wrong with the endpoints. They should be encouraged to check the integrity of their endpoints.ps1 from Settings -> Configurations -> endpoints.ps1 (as whatever the issue is most likely immediately self-resolvable by the end-user)
```

### Actual behavior

```console
The list of Endpoints under the API menu will be empty
```

### Environment data

2.11.2 (nightly build May 26th)

### Visuals

![image](https://user-images.githubusercontent.com/537287/170451273-7d0d8a61-3af1-4b13-a30b-902baa57337d.png)

**Comment by DataTraveler1** [comment]
This topic was discussed with #1180

**Comment by adamdriscoll** [comment]
We are going to make this very obvious. You can get yourself in a lot of trouble if you make a mistake and then add a new endpoint. It will effectively erase all your endpoints. 

![image](https://user-images.githubusercontent.com/1256531/171292945-c27b3a51-dfb7-45c3-b8c8-09d599096c21.png)
