### ISSUE TITLE
Terminals crash if the 'exit' command issued

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1211]
### Steps to Reproduce

1. Start a new PSU Terminal
2. Enter the command 'exit' into the terminal
3. Check the status of the PSU service

### Expected behavior

```console
The Terminal instance should terminate gracefully or the exit command should not be honored
```

### Actual behavior

```console
The Terminal instance terminates and takes the entire service with it
```

### Environment data

PSU 2.11.1

With maximum logging, there is only 1 line

`2022-06-06 14:47:22.519 -04:00 [DBG] Received hub invocation: InvocationMessage { InvocationId: "2", Target: "invoke", Arguments: [ exit ], StreamIds: [  ] }.`

### Visuals

![image](https://user-images.githubusercontent.com/537287/172227388-a1d318c0-b314-495a-889c-f5d820fa05b5.png)
###### Figure shows how the Terminal looks afterwards

**Comment by DataTraveler1** [comment]
@adamdriscoll - I have found that `[environment]::Exit(0)` also creates the same symptom in PSU Terminals that `exit` once did. Would it be appropriate for me to raise a new issue on this or I could re-open this?

**Comment by adamdriscoll** [comment]
This works as well. 

```
exit(0) 
```
