### ISSUE TITLE
Add a stop button to PSU Desktop 🛑

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1215]
### Summary of the new feature / enhancement

As a user of PSU desktop, it would be ideal if there was a button to stop the service (or if the service could also be closed when the UI is closed). I am assuming the behavior is by design.

The context for this request is that after closing the UI, the underlying background process still runs. Implementing this request should align the application more closely within the expectations around a desktop application.

### Proposed technical implementation details (optional)

![image](https://user-images.githubusercontent.com/537287/172905272-d68fd5e0-c6c0-4a6f-9269-381e016a62e0.png)
###### figure shows what the feature could look like 💭

**Comment by adamdriscoll** [comment]
You can stop it by using the tray icon. You'll see the PSU icon and can right click on it to close it. This is similar to how Slack\Teams works by default. We can certainly add a setting to stop the app via the X button.

**Comment by DataTraveler1** [comment]
@adamdriscoll - I see! I didn't catch that somehow. Perhaps this request could be refashioned into a suggestion for a one-time pop-up (when closing the UI for the first time) that the functionality of the UI would still be available in the tray icon.
