### ISSUE TITLE
Open License File - not able to read license

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1222]
## Describe the bug
Any attempt to add a valid license to PowerShell Pro Tools through the 'Open License File' option will fail due to a bug

## To Reproduce

1. Possess a valid license.txt for PowerShell Pro Tools
2. Have PowerShell Pro Tools VS Code extension installed but unlicensed
3. In VS Code, select the 'Command Palette' under 'View' (Ctrl+Shift+P)
4. Use the command '_PowerShell Pro Tools: Open License File_' to import your valid license.txt
5. Receive below error dialog. License import process does not complete.

![image](https://user-images.githubusercontent.com/537287/173246819-1cf97513-7151-4b0e-9692-9c09f59a97bf.png)

⚠This issue may also be impacting the "Install License" button from the extension Welcome Page

## Workaround

1. Open license.txt in notepad and copy the entire contents into your clipboard (Ctrl+A, Ctrl+C)
2. Navigate to the PowerShell Pro Tools extension settings and manually enter the license data into the dialog (see screenshot below)

![image](https://user-images.githubusercontent.com/537287/173247486-0bbf35ef-961b-48f4-af64-7e24574af547.png)

## Expected behavior
The valid license file should be accepted and imported without error.

## Screenshots

![image](https://user-images.githubusercontent.com/537287/173246949-abf8607a-c0e6-4a69-84b9-8c14b3aa10c0.png)
## Version

VS Code 1.67.2
PowerShell Pro Tools for VS Code 2022.5.2

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/received-trial-license-but-i-cant-install-it-in-vs-code-on-win-10/4394/5

**Comment by DataTraveler1** [comment]
[Install-PoshProToolsLicense](https://docs.poshtools.com/powershell-pro-tools-documentation/powershell-module/install-poshprotoolslicense) can also be used to install the license, of course

⚠Be sure to note that the **-License** parameter requires the **content of the license file** and not a path to the license.txt file.

![image](https://user-images.githubusercontent.com/537287/173248566-e48dd171-5386-4bb9-8c2a-2fed6b3607f2.png)

**Comment by adamdriscoll** [comment]
@DataTraveler1 - Can you send me the license you are using via email or something? I can't reproduce this.

**Comment by DataTraveler1** [comment]
@adamdriscoll  - A sample license file has been sent along with an animated .gif to more clearly demonstrate the issue

**Comment by adamdriscoll** [comment]
@DataTraveler1 Thanks!

**Comment by adamdriscoll** [comment]
I've removed Open License File. Install License Key should be used instead.
