### ISSUE TITLE
New-UDAutocomplete don't show any options ( PSU 3.0 RTM)

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1223]
### Steps to Reproduce

This issue are only present in 3.0 RTM1 and not in 2.11.1 .
When you try to write something it don't show any "dropdown" with selections. And also after you have written something you can't delete everything that you have written. You can delete all the text with backspace beside the first letter.

https://user-images.githubusercontent.com/76907327/173331452-85dc07a6-ec11-4589-91ab-f51f15b46606.mov

As you can se in the video I can't delete the last T

**Code:**
```
                        New-UDAutocomplete -id "txtGroupNameStart" -OnLoadOptions {
                            If ($Body.length -ge 3) {
                                $Session:SelectedGroup = Get-ADObject -LDAPFilter "(&(objectCategory=group)(anr=$Body))" -SearchBase "OU=xxx,DC=xx,DC=xx" -Properties SamAccountName
                                $Session:SelectedGroup | Select-Object -ExpandProperty SamAccountName | ConvertTo-Json
                            }
                        } -OnChange {
                            $Session:SelectedGroup = $Body
                        }
```

### Expected behavior

```console
You should get a dropdown with options and also you should delete all the letters/signs with backspace
```

### Actual behavior

```console
Don't get dropdown with options and you can't delete the first letter/sign with backspace.
```

### Environment data

PowerShell Universal 3.0 RTM1

**Comment by adamdriscoll** [comment]
I can't reproduce the issue with it not providing options but I can reproduce the issue where it doesn't delete the first character.

Doing this:

```
    New-UDAutocomplete -OnLoadOptions { 
        @('Test', 'Test2', 'Test3', 'Test4') | Where-Object { $_ -like "*$Body*"} | ConvertTo-Json
    } 
``` 

![image](https://user-images.githubusercontent.com/1256531/173469476-902c2ee7-da6a-447f-a2cd-7475a704c612.png)

**Comment by adamdriscoll** [comment]
I updated MUI to the latest version and it resolved the issue with deleting the first character. This will be in tomorrow's GA build.

**Comment by rwidmark** [comment]
> I updated MUI to the latest version and it resolved the issue with deleting the first character. This will be in tomorrow's GA build.

Everything is fixed :)
