### ISSUE TITLE
New-UDSelect bad alignment for label (PSU 3.0 RTM)

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1224]
### Steps to Reproduce

Create a New-UDSelect and set a label

Correct alignment from PSU 2.11.1
![Screenshot 2022-06-13 at 12 30 18](https://user-images.githubusercontent.com/76907327/173335168-23ba6ed0-d6bd-4973-96e1-17a150813cdf.png)

Incorrect alignment that happens with the same code for PSU 3.0
![Screenshot 2022-06-13 at 12 29 52](https://user-images.githubusercontent.com/76907327/173335274-9bbb6fe8-8bb1-4279-9fb0-16e2bd6ebabd.png)

### Expected behavior

```console
Have the label properly align as in 2.11.1 (the picture is from 2.11.1)
```

### Actual behavior

```console
The label are not properly aligned with the box.
```

### Environment data

PSU 3.0 RTM

**Comment by rwidmark** [comment]
I'm at 3.0.2 nightly but this is not fixed so you should move the milestone I guess :)

**Comment by adamdriscoll** [comment]
I'll mark it completed once it fixed but yeah I haven't got to this one yet with all the other issues popping up.
