### ISSUE TITLE
Can't pass variable/parameter in nested modules/component (PSU 2.12 and PSU 3.0)

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1225]
### Steps to Reproduce

1. Call a module/component from the dashboard
2. From that module/component your calling for a other module/component
Then you will get return that the variable / parameter is null

Edit:
After some more checking it seem that it can't pass the value of the variable / parameter inside the Show-UDModal so this also effects if you just want to have one module/component and not only for nesting.

**For example**

From dashboard
`Show-NewThing -Name $UserName`

Then in module/component1:
```
function Show-NewThing {
    [CmdletBinding()]
    Param(
        [Parameter(Mandatory)][ValidateNotNullOrEmpty()][String]$Name
    )
# here it show the content from the $UserName in the UDToast
    Show-UDToast -Message "$($Name)" -MessageColor 'red' -Theme 'light' -TransitionIn 'bounceInUp' -CloseOnClick -Position center -Duration 4000

# It don't show any content for $Name in the module not in the -Header either
    Show-UDModal -Header { "Show things $Name" } -Content {
# And as above $Name is empty when I send it to Get-Data also
        $GetData = Get-Data -CompName $Name
        New-UDTypography -Text "$($GetData)"
    } -Footer {
        New-UDButton -Text "Stäng" -OnClick {
            Hide-UDModal
        }
    } -FullWidth -MaxWidth 'md' -Persistent
}
```
here is the error mes
![Screenshot 2022-06-13 at 14 35 30](https://user-images.githubusercontent.com/76907327/173355054-e9185ee0-e523-4bb6-b263-8ff61a44a963.png)
sage that I get from Get-Data

![Screenshot 2022-06-13 at 14 03 41](https://user-images.githubusercontent.com/76907327/173350101-f6ddfb72-3454-4633-90a9-38a8e99f1d90.png)

Module/Component2:
```
function Get-Data {
    [CmdletBinding()]
    Param(
        [Parameter(Mandatory)][String]$CompName
    )
}

```

### Expected behavior

```console
In 2.11.1 and earlier you can pass the variable/parameter trough multiple modules/components.
```

### Actual behavior

```console
You will get null as it can't take the variable / parameter to the third component / module.
```

### Environment data

PSU 2.12 and PSU 3.0 are affected
Running PowerShell 7.2.4

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/pu-3-0-0-released/7226/2

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/found-a-nasty-bug-in-psu-3-0-and-inside-2-12/7227/1
