### ISSUE TITLE
New-UDIconButton make it smaller then xs (xs are not really xs either as it set on icon and not New-UDIconButton)

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1234]
### Summary of the new feature / enhancement

Today when your using the New-UDIconButton and size the icon to xs the New-UDIconButton are not in "xs size" it's much bigger.

Don't know if it's because the size are set on the icon instead of the New-UDIconButton or not.

**Comment by adamdriscoll** [comment]
Looks like we need to implement the size parameter for icon button. Setting the icon size likely doesn't affect the button itself. 

https://mui.com/material-ui/api/icon-button/#props

**Comment by rwidmark** [comment]
> Looks like we need to implement the size parameter for icon button. Setting the icon size likely doesn't affect the button itself. 
> 
> 
> 
> https://mui.com/material-ui/api/icon-button/#props

Great!
