### ISSUE TITLE
Can't change fontsize for the New-UDtopography

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1241]
### Steps to Reproduce

Trying to do it inside the theme @ { } but I can change everything beside the default size of New-UDtopography it should also be effected of the changes.

### Expected behavior

```console
Change size of all the New-UDtopography at the dashboard @ theme
```

### Actual behavior

```console
Don't change the fontsize of the New-UDtopography
```

### Environment data

PSU 3.0

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/change-fontsize-at-typography/7234/13

**Comment by adamdriscoll** [comment]
There is some global style being injected that is overriding the styling. I'll try to figure it out. 

![Animation3](https://user-images.githubusercontent.com/1256531/173845769-9ebf0740-80de-4ac2-a0ff-f6f84e4c8471.gif)

**Comment by adamdriscoll** [comment]
I figured out what was causing this.
