### ISSUE TITLE
Documentation: Azure Managed Identity for SQL Server Connection

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1244]
### Summary of the new feature / enhancement

https://forums.ironmansoftware.com/t/psu-3-0-sql-support/7244/7?u=adam

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/psu-3-0-sql-support/7244/8

**Comment by mabster** [comment]
In case it helps with your testing, here's a blog post I found with simple steps for setting it up:

https://blog.novanet.no/passwordless-connectionstring-to-azure-sql-database-using-managed-identity/

I'm using a managed identity for an app service hosting a .NET 6 web app I wrote to talk to its database, and it works really well. I use `Authentication=Active Directory Default` but that's only so I can talk to the DB from within Visual Studio. If you're only ever talking to the DB from Azure, you can safely use `Authentication=Active Directory Managed Identity`, I think.

**Comment by adamdriscoll** [comment]
Ok. Cool. I wonder if this will just work then. We are using the default EF provider for SQL so it's leveraging Microsoft.Data.Sql already and PSU is just a .NET 6 web app.

**Comment by mabster** [comment]
As of 3.1.6 I'm still getting the "Invalid value for key 'authentication'" exception noted at the bottom of that blog post, so I think the update to Microsoft.Data.SqlClient 4.1 did not go as planned.

**Comment by adamdriscoll** [comment]
Finally got this working all the way through...
