### ISSUE TITLE
PSU 3.0.2 did break my hole news page (Error rendering component (ud-style))

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1245]
### Steps to Reproduce

After updating to PSU 3.0.2 I did loose my hole Newspage with UDCards, the error message below says everything I guess that you need @adamdriscoll to fix it.
If I revertback to PSU 3.0.1 it works again.

It just say Error rendering component (ud-style) on the hole page

### Expected behavior

```console
Error rendering component (ud-style)
```

### Actual behavior

```console
Show my udcards etc.
```

### Environment data

PSU 3.0.2

### Visuals

Here is the error message from the page: ( I have removed some rows)
```
Error rendering component (ud-style)
Error: The `emotion` package has been renamed to `@emotion/css`. Please import it like this `import { css } from '@emotion/css'`.

    at Lazy
```

![image](https://user-images.githubusercontent.com/76907327/173994756-07f48e6e-34dd-467c-8afa-a1a69dc922c8.png)

**Comment by adamdriscoll** [comment]
This has been resolved. It broke all our integration tests last night too...
