### ISSUE TITLE
PSU 3.0.2 New-UDIconButton can't open modules

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1247]
### Steps to Reproduce

Can't re-open case but here is the case with the first issue after @adamdriscoll did fix that in todays nightly now the New-UDIconButton don't show anything, nothing happens when I click it.
https://github.com/ironmansoftware/issues/issues/1235

### Expected behavior

```console
Open UDModal when clicked
```

### Actual behavior

```console
Nothing happens
```

### Environment data

PSU 3.0.2

**Comment by adamdriscoll** [comment]
This has been resolved. We now have integration tests covering New-UDIconButton.
