### ISSUE TITLE
New-UDSwitch icons for colorblind people, MUI has support

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1261]
### Summary of the new feature / enhancement

It would be great if you can have the Android12 example in this link;
https://mui.com/material-ui/react-switch/#customization

Some people are colorblind so it would be great to have the little check/unchecked icon inside the switch. It’s the example that’s called Android12 in the picture. If you want to see how it looks like unchecked you can use the link above to live switch it on and off to see.

![image](https://user-images.githubusercontent.com/76907327/174393175-6ea24007-148d-4c19-9143-1400e9cc0d02.jpeg)

![image](https://user-images.githubusercontent.com/76907327/174393206-972493d6-e83b-406d-862c-c671f294aa5b.jpeg)

### Proposed technical implementation details (optional)

some switch to get it activated for example;
New-UDSwitch -checklabel

Here is the MUI reference links for the function.

https://mui.com/material-ui/react-switch/#customization

https://mui-treasury.com/styles/switch/

https://mui.com/material-ui/customization/how-to-customize/

**Comment by rwidmark** [comment]
@adamdriscoll is this something that can be added?

**Comment by rwidmark** [comment]
@adamdriscoll is this something that can be added?

**Comment by rwidmark** [comment]
this one will be so great @adamdriscoll

**Comment by rwidmark** [comment]
@adamdriscoll @mattselle I can't see any documentation regarding this funktion in 3.5.0 did this go in to that version?

**Comment by donlent** [comment]
Dear @rstolpe 
You'll have to use the parameter  -CheckStyle and then it will work 🤗
![image](https://user-images.githubusercontent.com/11975745/201018141-0ed4560d-9785-46ef-a169-e585c38d2ed9.png)

It's not yet in the docs here https://docs.powershelluniversal.com/userinterfaces/dashboards/components/inputs/switch but I'm sure Adam will update it when he finds some spare time... Maintaining docs is always a pain... 😅

Kind regards,
Don
