### ISSUE TITLE
Make buildno on the nightly release/bulids

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1265]
### Summary of the new feature / enhancement

Today it seem that every build has the same version so upgrading with the .msi file are an issue as it flags as a new install on windows. So you get multi instans of the same version installed. So the solution today is to uninstall every nightly build and then reinstall the new one.

### Proposed technical implementation details (optional)

My suggestion here is that you @adamdriscoll are labeling the nightly builds with a build number like 3.1.0.xxx in that way we can just upgrade the installation as we can with the production release.

**Comment by adamdriscoll** [comment]
I will have to investigate. The last I checked, MSI will not honor the build number so even if we set it, it will think it's the same version. That said, it's been a long time since I tried to do it and maybe that has changed.

**Comment by Viajaz** [comment]
@adamdriscoll I don't believe Windows Installer honours the 'revision' in _major.minor.build.revision_.

https://www.firegiant.com/wix/tutorial/getting-started/the-software-package/
> For the Version attribute, use the standard major.minor.build format. Windows Installer will ignore an eventual fourth field, .revision as it provides other means to differentiate revisions.

**Comment by adamdriscoll** [comment]
Thanks for finding the info on that. I'm going to close this because it's not currently supported by Windows Installer.
