### ISSUE TITLE
MSI Installer not upgrading properly

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1269]
### Steps to Reproduce

https://forums.ironmansoftware.com/t/dashboards-are-failing-to-start-after-upgrading-to-psu-3-0-1/7248/16

### Expected behavior

```console
v2 is upgraded to v3
```

### Actual behavior

```console
v2 is left behind.
```

### Environment data

3.0.3

**Comment by adamdriscoll** [comment]
Documenting this for now. Upgrades from v3 - v3 work fine but v2 -> v3 do not. It could be something wrong with the v2 installer...

**Comment by Viajaz** [comment]
I think I was hit by this, it left old Modules behind from memory.
