### ISSUE TITLE
Open Core

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1284]
### Summary of the new feature / enhancement

This is something I've been considering for a long time. With so many features being available for free, it would make sense to have an open core. It would require some adjustment to how we package and build PSU. We would also need to accomplish #1214  to manage this. 

Many of the core aspects of PSU would really be cool as a free, extensible platform. 

Things to consider: 
- Development process needs to remain simple
- Packaging and distribution should remain simple

## Open Core Features

- APIs
- Scripts
- Scheduling
- Dashboards
- Configuration System
- Forms Authentication
- Role Based Access
- LiteDB Persistence

## Closed Features 
- Debugging
- Branding
- Rate Limits
- Terminals
- Triggers
- SQL Persistence
- Access Controls
- Git Sync
- Other Auth Methods

**Comment by Viajaz** [comment]
"Open" as in spinning it out from the product and putting it under an open-source license?

**Comment by adamdriscoll** [comment]
Right. The platform itself would be open source and then feature groups may be closed source.
