### ISSUE TITLE
Code Editor Path Autocomplete Causes Duplicates

### ISSUE THREAD

**Issue by x86Since8088** [ironmansoftware/powershell-universal#1285]
### Steps to Reproduce

Navigate to /admin then automation/scripts and create a new script.
When editing start typing a path.

### Expected behavior

```console
e:\E:\HttpListener_Apps\E:\HttpListener_Apps\PowerShellUniversal
```

### Actual behavior

```console
e:\E:\HttpListener_Apps\E:\HttpListener_Apps\PowerShellUniversal
```

### Environment data

3.0.3 GA

### Visuals

e:\E:\HttpListener_Apps\E:\HttpListener_Apps\PowerShellUniversal

**Comment by DataTraveler1** [comment]
@x86Since8088 - Thanks for reporting about this. Just in case it helps anyone, I've recorded a gif of it as well.

![Issue1285](https://user-images.githubusercontent.com/537287/175205376-c0166e02-670e-4baf-9519-0b40305bc5f9.gif)

**Comment by DataTraveler1** [comment]
@adamdriscoll - I believe this is still occurring in build 3.0.6

**Comment by adamdriscoll** [comment]
@DataTraveler1 - I should have reopened this. I rolled back this change at the last minute because it was causing other issues.

**Comment by adamdriscoll** [comment]
This as be resolved.

**Comment by DataTraveler1** [comment]
@x86Since8088 - I can confirm that this behavior no longer occurs in the latest 3.1.0 nightly build
