### ISSUE TITLE
Worker groups

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#1294]
### Summary of the new feature / enhancement

Just like we know it from Azure hybrid workers, it would be amazing to have worker groups in PSU.
Our Azure workers are divided into different environments (SQL, Azure, Data warehouse, etc) due to security regulations.

With PSU we are loosing that security regulations, since our workers needs to have access to both SQL, Azure, Data warehouse, etc from the same network.

The quick fix is to have different admin interfaces for each of the environments, but then we loose the functionality of having everything in an single pane of glass 🙂 

### Proposed technical implementation details (optional)

The same amazing experience we have with PSU today, but with worker groups

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/feature-request-worker-groups/7316/3
