### ISSUE TITLE
UDMap support for Non-geographical maps

### ISSUE THREAD

**Issue by HeuristicBishop** [ironmansoftware/powershell-universal#1296]
### Summary of the new feature / enhancement

Forum Post: https://forums.ironmansoftware.com/t/udmap-support-for-non-geographical-maps/7325

I would like to create non-geographical maps with UDMap. This means supporting maps that do not use a traditional latitude/longitude coordinate system. An example from leafletjs can be found here: https://leafletjs.com/examples/crs-simple/crs-simple.html

My use case is creating an interactive floorplan of my site with technology info overlayed and updated in ~realtime.
As this is a fairly simple/small floorplan I'd like to avoid dealing with tiled images as well.

Creating non-tiled maps could be considered it's own feature request but I think the exposed bits match up enough to roll it together. In fact this is also covered in the Non-geographical maps tutorial linked above.

Here is another decent example of using a static image and max bounds for a simple map:
https://kempe.net/blog/2014/06/14/leaflet-pan-zoom-image.html

### Proposed technical implementation details (optional)

Expose the following leaflet Map properties:
L.map.CRS
L.map.setmaxbounds
L.map.unproject
L.imageoverlay
L.LatLngBounds

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/udmap-support-for-non-geographical-maps/7325/4

**Comment by JREID96** [comment]
@adamdriscoll I came across this enhancement on the forum, and I am also looking to create a non-geographical map of my site using PowerShell Universal. Is this anywhere in the roadmap for the near future? Thanks

**Comment by adamdriscoll** [comment]
https://leafletjs.com/examples/crs-simple/crs-simple.html
