### ISSUE TITLE
PSU 3.1 The method or operation are not implemented (Bug)

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1298]
### Steps to Reproduce
After the dashboard has been running for some time (sometimes 24h) it starts to replay the following on some components/function, If I restart the Dashboard it works for some time again until it stops. The only thing that all of where I get the issue has in common are that it loading things from PSUCache, to clarify this also happens on other pages where I load stuff from PSUCache but it's not from the same PSUCache and it's not the same content. And when it happens it stops loading/showing the content from the PSUCache on the page everything else are working and I receive the error pop-up (se picture above)
The same code works perfectly fine before 3.1. I think I was running 3.0.2 before the 3.1 version.

When I restart the PowerShellUniversal service everything works fine for some time again until it stops working again.
![Screenshot 2022-06-30 at 09 54 37](https://user-images.githubusercontent.com/76907327/176624434-a55b1db4-bd41-49a3-a731-5485a1976e66.png)

(It's funny as I don't have a line 76 as you can se in the code below)

Here is the code from one of the pages that trough the issue.
```
$CacheFilesDashboardUploads = Get-PSUCache -Key "CacheFilesDashboardUploads"
#
New-UDGrid -Spacing '1' -Container -Children {
    New-UDGrid -Item -ExtraLargeSize 6 -LargeSize 6 -MediumSize 6 -SmallSize 6 -Children {
        New-UDStyle -Style ".ud-mu-cardbody { display: block !important; }" -Content {
            New-UDCard -Title "Release Notes" -Content {
                $NewReleaseNotes = $CacheFilesDashboardUploads | where-object FullName -like "D:\DFS\ReleaseNotes\New\*" | select-object -ExpandProperty name | Sort-Object -Descending
                $ArchiveReleaseNotes = $CacheFilesDashboardUploads | where-object FullName -like "D:\DFS\ReleaseNotes\Archive\*" | select-object -ExpandProperty name | Sort-Object -Descending
                New-UDList -Content {
                    foreach ($File in $NewReleaseNotes) {
                        New-UDListItem -Label "$($File)" -Icon (New-UDIcon -Icon file_download -Size lg) -OnClick {
                            Invoke-UDRedirect "https://$($TargetDomain)/ReleaseNotes/New/$($File)"
                        }
                    }
                    New-UDHtml -Markup "<br>"
                    New-UDTypography -Variant h6 -Text "Arkiv"
                    New-UDTransition -Id 'Archive' -Content {
                        New-UDHtml -Markup "<br>"
                        foreach ($File in $ArchiveReleaseNotes) {
                            New-UDListItem -Label "$($File)" -Icon (New-UDIcon -Icon file_download -Size lg) -OnClick {
                                Invoke-UDRedirect "https://$($TargetDomain)/ReleaseNotes/Archive/$($File)"
                            }
                        }
                    } -Collapse -CollapseHeight 100 -Timeout 1000
                    New-UDSwitch -OnChange {
                        Set-UDElement -Id 'Archive' -Properties @{
                            in = $EventData -eq 'true'
                        } 
                    }
                }
            }
        }
    }

    New-UDGrid -Item -ExtraLargeSize 6 -LargeSize 6 -MediumSize 6 -SmallSize 6 -Children {
        New-UDStyle -Style ".ud-mu-cardbody { display: block !important; }" -Content {
            New-UDCard -Title "Instruktioner och dokumentation" -Content {
                $RootChildFiles = $CacheFilesDashboardUploads | where-object FullName -like "D:\DFS\Instructions\*" | select-object -ExpandProperty name | Sort-Object -Property name
                New-UDList -Content {
                    foreach ($File in $RootChildFiles) {
                        New-UDListItem -Label "$File" -Icon (New-UDIcon -Icon file_download -Size lg) -OnClick {
                            Invoke-UDRedirect "https://$($TargetDomain)/Instructions/$($File)"
                        }
                    }
                }
            }
        }
    }
}
```

### Expected behavior

```console
That it should work all the time and not stop working after some time. The same code works with 3.0.2 and below
```

### Actual behavior

```console
After the dashboard has been running for some time (sometimes 24h) it starts to replay the following on some components/function, If I restart the Dashboard it works for some time again until it stops. The only thing that all of where I get the issue has in common are that it loading things from PSUCache, to clarify this also happens on other pages where I load stuff from PSUCache but it's not from the same PSUCache and it's not the same content. And when it happens it stops loading/showing the content from the PSUCache on the page everything else are working and I receive the error pop-up (se picture above)
The same code works perfectly fine before 3.1. I think I was running 3.0.2 before the 3.1 version.

When I restart the PowerShellUniversal service everything works fine for some time again until it stops working again.
```

### Environment data

PSU 3.1 Nightly (2022-06-28)
PowerShell 7.2.5
Windows Server 2022

**Comment by rwidmark** [comment]
@adamdriscoll can you reproduce this?
Do you want my script that catches the PSUCache that the page above are fetching?

**Comment by adamdriscoll** [comment]
I haven't reproduced this at all. Feel free to share whatever info you think would be helpful.

**Comment by rwidmark** [comment]
> I haven't reproduced this at all. Feel free to share whatever info you think would be helpful.

So make a page like the one that I did past above in the first post then you make a PSU Schedule job running this script every 30min and then just wait for about 24h or similar you should get the same error as I do get it on a brand new server.
Ofc fell free to change the path to the folder that it are caching.

```
$GetHost = [System.Net.Dns]::GetHostName()
Write-Host "--STARTING SCRIPT--`n"

Write-host "Starting to collect files and folders from D:\DFS from PSU Servers..."
try {
    $FilesToCache = Get-ChildItem -Path D:\DFS -File -Recurse -Force | Select-Object name, FullName
}
catch {
    Write-Warning "Something went wrong when trying to collect DFS files and folders..."
    Write-Warning "$($PSItem.Exception.Message)"
    Break
}

Write-Host "Trying to send file and folder information to Cache..."
if (-Not([string]::IsNullOrEmpty($FilesToCache))) {
    Set-PSUCache -Key "CacheFilesDashboardUploads" -Value $FilesToCache -AbsoluteExpirationFromNow ([TimeSpan]::FromHours(36))
    Write-Host "File and folder information was sent to cache!"
}
else {
    Write-Host "File and folder information is empty, didn't send it to cache..."
}

Write-Host "Completed!`n"
Write-Host "--END OF SCRIPT--"
```

**Comment by rwidmark** [comment]
@adamdriscoll downgraded a test server to 3.0.6 and it's working fine there.
So it's unseeded something with 3.1.0. But I have seen that you haven't updated the nightly for some time, you maybe haven't merge the new updates from 3.0.x to it.

Anyway you have the code above for the page and also the script that runs as a job in PSU for every 15min I think it is.

Just re-direct the path and make sure that you have some files in the directory etc.

**Comment by rwidmark** [comment]
@adamdriscoll I have tried it on 3.0.6 now and it's not an issue on 3.0.6 but on 3.1.0 so I'm guessing something is fixed in 3.0.6 that are not applied/merged in to 3.1.0 (2022-06-28) from 3.0.6 or if something else are changed in 3.1.0

**Comment by rwidmark** [comment]
@adamdriscoll this is still a issue in 3.1.0 it seem to only effect function when I'm retrieving information from PSU-Cache and it happens after some period of time.

First it works perfect for let say 18h then the issue appear.
Then I restart the PSU service and then it works flawless for 19h for example then the issue appears again.

The issue are in our Prod environment so I can't show it without a NDA.

But I'll wait until it provides a issue again and then collect information and email it to you.

After that if you want to enter the production environment and take a look I can ask HR to write a NDA for you.

**Comment by rwidmark** [comment]
@adamdriscoll this still happens.

Everywhere I'm reading in from PSUcache to the dashboard get the same error then I'm restarting PSU service and it works again for some time, it's happens random.

I have now tested to lower the PSUCache storage/save time to see if it helps. It was set to 36h until now.

Today it happens two times, after restarting it worked for about 3h on one of the nodes then the issue started again but not On the other one.

It seems like when I have many users at the same time on the dashboard it's when it happens after some time.

I'm guessing that you want logs so I'm wondering which logs and what log setting I should use in admin dashboard?

I'm on vaccation but I'll ask a colleague to clock it tomorrow if it happens again so we have a time point to go after.

It did work flawless before 3.0.6 i think it was.

Same issue on three nodes so it's not the nodes.

**Comment by rwidmark** [comment]
Closing this to open a new one that are more clear;
https://github.com/ironmansoftware/issues/issues/1421
