### ISSUE TITLE
Improved Exception Logging in Automation Jobs

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/powershell-universal#1299]
### Summary of the new feature / enhancement

Objects returned from Automation Scripts to the Pipeline are able to be viewed in the Pipeline pane but Uncaught Exceptions are viewed in the Errors pane with only a Timestamp and Message.

It would be useful to see the full Exception object (including StackTrace) for troubleshooting, rarely is just a timestamp and message sufficient for debugging PowerShell and .NET errors.

It would also be useful to have a Cmdlet to manually log caught exceptions to such a view (separately from the Pipeline view) to allow develops to optionally utilise the feature in their own `catch` blocks.

### Proposed technical implementation details (optional)

The UI tree component could be reused from the Pipeline pane for a theoretical additional 'Exceptions' Pane in order to view Exception objects.

**Comment by adamdriscoll** [comment]
Stack traces are now included with errors. You can also use Write-PSUError to log errors from exception handlers
