### ISSUE TITLE
Azure Key Vault Integration

### ISSUE THREAD

**Issue by Entech-Ramon** [ironmansoftware/powershell-universal#13]
Would it be possible to integrate PU with Azure Key Vault? Could maybe use the .net core sdk? Type of integration I'm thinking is you point it to a key vault and it can read the secrets and either store them in a variable or maybe make a cmdlet to retrieve the keys? Not sure how it would perform or work. Ideally these keys/variables/cmdlets could be available to API, Automation and Dashboards. Having the option to write to the Key Vault as well could be useful but personally I would like to see reading the key vault more.

**Comment by adamdriscoll** [comment]
We had to make some changes to the secret management module but you can now configure PSU to integrate with Az.keyVault module and store secrets in Az Key Vault with the PSU UI. This will be available in 2.7.

https://docs.powershelluniversal.com/platform/variables#az.keyvault
