### ISSUE TITLE
New-UDSelect doesn't return default value

### ISSUE THREAD

**Issue by ptmorris1** [ironmansoftware/powershell-universal#1307]
### Steps to Reproduce

When using new-udselect with a default value set, the default value does not return data into get-udelement until manually selected.

If you run below code and just click the 'Get Select' button it returns null value.  If you pick the drop down and manually select default value and then hit 'Get select' button it returns correct value.

```
$pages += New-UDPage -Name 'select' -Content {
    New-UDSelect -Option {
        New-UDSelectOption -Name 'One' -Value 1
        New-UDSelectOption -Name 'Two' -Value 2
        New-UDSelectOption -Name 'Three' -Value 3
    } -Id 'select' -DefaultValue 2
    New-UDButton -Text 'Get select' -OnClick {
        $value = $(Get-UDElement -Id 'select').value
        Show-UDToast -Message $value -Duration 6000
    }
}

New-UDDashboard -Title 'testing' -Pages $pages
```

### Expected behavior

```console
Default value should be set without manually selecting it first.
```

### Actual behavior

```console
Default value is not set until manually selected even when it is displayed\set by default in code.
```

### Environment data

3.0.6

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/select-onchange-update-card-contents/7341/9

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/new-udradiogroup/7626/1
