### ISSUE TITLE
PSU 3.1.0 GUI bug is back from 3.0.0

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1310]
### Steps to Reproduce

Install PSU 3.1.0 and the "bug" where the GUI was wrong is back, it's the same as it was in 3.0.0 and that you did fix in later 3.0.x version, as you can see the icons inside the buttons is slightly off etc. This was fixed was introduced in the nightly build of 3.1.0 that was released for maybe two days ago? It was not in the first nightly of 3.1.0 that's for sure anyway.

PSU 3.1.0

![](https://global.discourse-cdn.com/standard11/uploads/universaldashboard/original/2X/6/6e79d4e8761d4f720fbc0d5499720af7de06240a.png)

PSU 3.0.6
![image](https://user-images.githubusercontent.com/76907327/177256208-1c12e125-3671-4dc6-abea-3539d70ee19a.png)

### Expected behavior

```console
Same size etc. on the buttons.
```

### Actual behavior

```console
Button etc. get bigger even the icons get bigger.
```

### Environment data

3.1.0
win2022
PS 7.2.5

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/upgrade-test-server-to-3-1-0-and-the-icons-did-go-bananas-in-size-gui-bug-is-back-from-3-0-0/7349/1

**Comment by adamdriscoll** [comment]
This was introduced when we implemented the loading button but it's been resolved this morning.
