### ISSUE TITLE
Command line installation of the msi file

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1311]
### Summary of the new feature / enhancement

For example;
PSU.msi serviceuser=myuser servicepassword=mypassword port=443

**Comment by adamdriscoll** [comment]
Properties are documented here: https://docs.powershelluniversal.com/getting-started#msi-parameters

You can set them with the following syntax: 

```
msiexec /i "Othello.msi" TCPPORT="1000"
```
