### ISSUE TITLE
Job Log is truncated in the UI

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1315]
### Steps to Reproduce

https://forums.ironmansoftware.com/t/automation-job-logs-truncated/7328

### Expected behavior

```console
Entire job log is displayed
```

### Actual behavior

```console
Job log is sometimes truncated
```

### Environment data

3.0.6

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/automation-job-logs-truncated/7328/3

**Comment by adamdriscoll** [comment]
I'm seeing some truncation at the very end of the log file (last 3 lines or so) but I'm not seeing muhc more than that. I made a test script that just outputs a bunch of stuff in various streams. 

```
1..1000 | ForEach-Object {
    $R = 1..3 | Get-Random
    if ($R -eq 1)
    {
        Write-Host "This is a test $_ This is a test $_ This is a test $_ This is a test $_ This is a test $_ This is a test $_ This is a test $_ This is a test $_ This is a test $_"  
    }

    if ($R -eq 2)
    {
        Write-Error "This is a test $_ This is a test $_ This is a test $_ This is a test $_ This is a test $_ This is a test $_ This is a test $_ This is a test $_ This is a test $_"  
    }

    if ($R -eq 3)
    {
        Write-Warning "This is a test $_ This is a test $_ This is a test $_ This is a test $_ This is a test $_ This is a test $_ This is a test $_ This is a test $_ This is a test $_"  
    }
    
    
    Start-Sleep -Milliseconds 100
}
```

We've also added a link to the raw log file so in 3.1 we'll be able to verify whether this is a display issue or something else. 

![image](https://user-images.githubusercontent.com/1256531/177835963-09cad169-69ed-4f55-8d72-23ad388ebb89.png)

**Comment by Viajaz** [comment]
I'm not sure how to reproduce it but I often see a lot of the log missing

**Comment by Viajaz** [comment]
Another issue that keeps happening is if an error is raised (or more specifically, an exception) the job log will consist of nothing but the written Error output (Eg: from `Write-Error`) and nothing else, it's as if all the `$*Preference` are ignored. This has been particularly frustrating when trying to track down transient errors in Production scripts, I'm almost at the point of using an external logging solution for everything.

**Comment by Omzig** [comment]
@adamdriscoll, should this be closed?
