### ISSUE TITLE
PSU 3.1 GitHub sync is broken

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1319]
### Steps to Reproduce

I did update to 3.1.0 nightly (2022-07-06) from 3.0.6 and my GitHub sync stopped working.
(The first sync after updating was working perfectly fine)
Here is my config
```
  "Data": {
    "RepositoryPath": "%ProgramData%\\UniversalAutomation\\Repository",
    "ConnectionString": "filename=%ProgramData%\\UniversalAutomation\\database.db;upgrade=true",
    "GitRemote": "https://github.com/rstolpe/Franky_Dev.git",
    "GitUserName": "xxxx",
    "GitPassword": "xxxxx",
    "GitBranch": "main",
    "GitSyncBehavior": "TwoWay",
     "GitInitializationBehavior": "clone",
    "ConfigurationScript": ""
  },
```

I even tried to fill out the new "+ Git settings" but it don't seem to get saved.
Before I fill out the "+ Git settings" and if I push the "Synchroniz now" button it icon starts to "spinn"
But after I have filled out "+ Git settings" and if I push the "Synchroniz now" button nothing happens at all.

### Expected behavior

```console
Sync with GitHub
```

### Actual behavior

```console
Don't sync at all
```

### Environment data

GitHub
PSU 3.1.0
PS 7.2.5
Win2022

**Comment by rwidmark** [comment]
My guess is that this is kind of important to get working correctly before next weeks release @adamdriscoll 
Do you prefer that we(I) are reporting issues on nightly here or in any other place?

**Comment by adamdriscoll** [comment]
I can't reproduce this one. 

![image](https://user-images.githubusercontent.com/1256531/177571780-68ad3fea-83f6-4b06-af21-856c1d9b76a2.png)

I can reproduce the issue with sync now button not working and that will be fixed today. 

Can you upload a log?

**Comment by rwidmark** [comment]
> I can't reproduce this one. 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/1256531/177571780-68ad3fea-83f6-4b06-af21-856c1d9b76a2.png)
> 
> 
> 
> I can reproduce the issue with sync now button not working and that will be fixed today. 
> 
> 
> 
> Can you upload a log? 
> 
> 

I can try it out tomorrow and provide logs if it's not working

**Comment by rwidmark** [comment]
@adamdriscoll What file are this settings getting saved to?
![image](https://user-images.githubusercontent.com/76907327/177787908-e8372a14-3372-4a19-8e09-5e48099098d3.png)

It don't seem to sync with app settings.json as I have it set to clone inside there. I have downloaded the latest 3.1.0 nightly now.

**Comment by adamdriscoll** [comment]
@rstolpe - Those settings are stored in the database. 

The test I did above was using appsettings.json

**Comment by rwidmark** [comment]
@adamdriscoll then the issue are still there.
Give me around 2-3h then I can provide access to the server so you can try it out and see for your self

**Comment by rwidmark** [comment]
@adamdriscoll  I have sent you a email with all of the creds, just replay the IP your connecting from to the test environment so I can allow it trough the firewall.

It also seem like that it sync when you restart PSU service but not automatically, it's a testa envorumunte so feel free to try what ever you want :)

**Comment by adamdriscoll** [comment]
I certainly can see the issue in your environment. The sync now button seems to do nothing. I don't even see a log message about it. I also did run into an issue that was preventing the settings from being display. 

Finally, I can't RDP in with the account you sent so if you could see if I could, that'd be great!

**Comment by rwidmark** [comment]
@adamdriscoll I have sent you a email I have added your account to a missing group and I did even try to RDP with it in to the machine and it was working for me, please try again :)

**Comment by Viajaz** [comment]
This feature seems to fail a lot.

**Comment by rwidmark** [comment]
> This feature seems to fail a lot.

Yes, but this issue are solved. Maybe during install of PSU it can install git (official) and then from the PSU config GUI let users config git instead. It might be a better solution? Don't know if you can trigger git to sync or not. I have not looked in to it.
