### ISSUE TITLE
Add Power buttons to the main Dashboard list ⏺

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1325]
### Summary of the new feature / enhancement

Currently, the button for powering off a dashboard is only available in the UI by drilling down into each dashboard. It could be helpful if the Power buttons were also accessible from the main Dashboard list (visual below).

### Proposed technical implementation details (optional)

![image](https://user-images.githubusercontent.com/537287/178053420-5c65235f-1d5f-4628-aee3-8332ddd0cfbc.png)
###### figure shows the feature imagined (on the first Dashboard in the list)

**Comment by adamdriscoll** [comment]
@DataTraveler1 - If you click the Basic switch and toggle it to advanced those buttons will show up.

**Comment by DataTraveler1** [comment]
@adamdriscoll - Thank you! I did not catch that. I would consider this closed.
