### ISSUE TITLE
Able to audit environments.ps1 🔎

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1326]
## Feature Requested

It would be ideal if there was a button under **Settings** -> **Environments** which would check (audit) each entry in the Environments.ps1 for accuracy in the parameters, description and other properties where applicable. Even better, a pop-up with an offer to fix the discrepancies where it is reasonably possible 🔧. Example below would need to update the 'Version' and 'Name' properties of the PSU Environment from 7.2.4 to 7.2.5.

1. Install PowerShell 7.2.4 to the server (machine installer to Program Files)
2. Install PSU (environments.ps1 is created automatically and will detect/include the PS 7.2.4)
3. Upgrade the PowerShell to 7.2.5 and reboot the server (reboot not needed but for good measure)
4. Check under Settings -> Environments if the 7.2.4 was updated to 7.2.5

Another example could be checking for duplicated entries in the list of modules for each entry in the Environments.ps1

## Workarounds

- Edit the enviroments.ps1 manually whenever a new PowerShell core is installed on the PSU Server \Program Files\ directory
- Manually remove any entries that somehow became duplicated

### Proposed technical implementation details (optional)

![image](https://user-images.githubusercontent.com/537287/178082092-616c6b4d-9113-492e-a25b-76184309787a.png)
###### figure shows the feature imagined 💭

**Comment by adamdriscoll** [comment]
We added the PowerShell 7 environment to avoid having version specific names. The version value will still be updated when the service is started.
