### ISSUE TITLE
Able to clear terminated instances from Terminals 🧹

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1327]
### Summary of the new feature / enhancement

A button to immediately clear terminated instances of Terminals from the view. This is to reduce clutter.

### Proposed technical implementation details (optional)

![image](https://user-images.githubusercontent.com/537287/178083360-9e103560-434b-4a08-898b-9f13029fbf0e.png)
###### figure shows the feature imagined

**Comment by adamdriscoll** [comment]
@mattselle - Let's archive them like we are doing with jobs.
