### ISSUE TITLE
Importing ActiveDirectory module will break PowerShell 7 dashboards

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1328]
## Steps to Recreate

1. Have the latest 3.1.0 nightly build
2. Create a working dashboard using a PowerShell 7 environment (or the integrated environment)
3. Edit the dashboard and add the following to the top of the dashboard

`Import-Module -Name ActiveDirectory`

5. View the dashboard to see the breakage

_Exception calling "GetSteppablePipeline" with "1" argument(s): "The parameter is incorrect. "_

## Workaround (1)
Use the -SkipEditionCheck parameter

`Import-Module -Name ActiveDirectory -SkipEditionCheck`

## Workaround (2)
Use the Windows PowerShell 5.1 environment

### Expected behavior

```console
Importing the ActiveDirectory module should not break the dashboard
```

### Actual behavior

```console
Importing the ActiveDirectory module breaks the dashboard
```

### Environment data

ActiveDirectory module 1.0
PSU 3.10 nightly build (2639238314)

### Visuals

![image](https://user-images.githubusercontent.com/537287/178126497-90850706-2fac-4f2c-bacb-959517108bd4.png)

**Comment by DataTraveler1** [comment]
Please note that other modules which are installed as part of the OS (e.g. BitsTransfer) and therefore failing the PSEditionCheck do not exhibit the same behavior.

Reference: https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Core/About/about_PowerShell_Editions?view=powershell-7.2#edition-compatibility-for-modules-that-ship-as-part-of-windows

**Comment by adamdriscoll** [comment]
@DataTraveler1 - What version of the AD module do you have installed? I can't reproduce this one.

**Comment by DataTraveler1** [comment]
@adamdriscoll 

- ActiveDirectory module installed (as a feature from Server Manager) is 1.0.0.0
- Windows Server 2012 (up-to-date on patches, frequently rebooted), configured as a Domain Controller
- PowerShell 7.2.5 Core is installed as MSI machine-install in Program Files
- Windows Management Framework is 5.1

![image](https://user-images.githubusercontent.com/537287/178162760-db59ba29-1eaa-4f6a-b533-e0db9a2f2754.png)

Edit 1 
- PSU is running as a standard MSI (Kestrel) with default options (but under a service account)
- Every PSU begins with resetting the %PROGRAMDATA%\UniversalAutomation directory and is followed by a restart of the server

**Comment by adamdriscoll** [comment]
Ah, ok. That's likely the problem. The 1.0.0.0 version of the AD module loads using the Windows PowerShell Compat functionality. It doesn't actually load natively in PowerShell 7. It's problematic in PSU. It works by starting an external Windows PowerShell session and uses PowerShell remoting. Each runspace will open a WinPS process. 

To get native PS7 functionality with the AD module, you will need the 1.0.1.0 version. I honestly always find it really hard to figure out how to upgrade that...

![image](https://user-images.githubusercontent.com/1256531/178163167-00bdb851-d57c-49be-9e10-aad8c463855b.png)

**Comment by adamdriscoll** [comment]
Whoops. Didn't mean to do that. We should probably document this because others have run into it. I might even consider putting a warning in the product somehow.

**Comment by DataTraveler1** [comment]
@adamdriscoll - I am wondering this should be closed simply because there is nothing else that can be done from the PSU side? I have some suggested guidance below that we could close this out with.

## Windows Server 2019 and above
Update the ActiveDirectory module to version 1.0.1.0 which has PowerShell Core support

## Windows Server 2016 and below
Choose from 1 of 2 available workarounds:
- Include the ``-SkipEditionCheck`` parameter with **Import-Module** when importing the ActiveDirectory module
- Use the Windows PowerShell 5.1 environment instead of Integrated/PowerShell Core

### Further Reading
https://devblogs.microsoft.com/powershell/increased-windows-modules-coverage-with-powershell-core-6-1/

**Comment by adamdriscoll** [comment]
@DataTraveler1 - I'll find out somewhere to put this into our documentation.

**Comment by adamdriscoll** [comment]
@DataTraveler1  - Done: https://docs.powershelluniversal.com/platform/modules#activedirectory
