### ISSUE TITLE
Translations cannot be deleted and get somehow duplicated.. (3.1.0 Prod)

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#1332]
### Steps to Reproduce

- Create two translations
- Add a new string
- Go back to the view and you will see this:
 
![image](https://user-images.githubusercontent.com/11975745/178424685-4888d528-52bf-4659-a0a5-ce7df2e7a98a.png)

In addition these translations can't be deleted anymore. The delete function does nothing

### Expected behavior

```console
Translations should be manageable
```

### Actual behavior

```console
Translations are no manageable and duplicate themselves...
```

### Environment data

3.1.0 Release Version

**Comment by adamdriscoll** [comment]
Bummer. We saw this in testing but I thought it got fixed. I'll take a look ASAP.
