### ISSUE TITLE
Theming issues with Pages when using Default Dark Mode

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#1354]
### Steps to Reproduce

Really sorry Adam for filing so many theming issues...🙈
Hope you don't get mad on me 😅

![image](https://user-images.githubusercontent.com/11975745/178934524-ae9744f5-49ba-4fc4-a7f5-c4ff80fbc8bb.png)

That what happens when using default Dark Mode with Pages...

### Expected behavior

```console
Theming should work properly
```

### Actual behavior

```console
Theming is "broken" and doesn't display labels on some buttons. Light mode works fine...
```

### Environment data

3.1.1

**Comment by adamdriscoll** [comment]
@donlent - Keep reporting em! 🥳
