### ISSUE TITLE
macOS Apple Silicon native or universal

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1369]
### Summary of the new feature / enhancement

Today PowerShell Universal are only for x64 it should be a great time to update it to Universal or Apple Silicon native.

**Comment by adamdriscoll** [comment]
This will be available in tonight's nightly build.

**Comment by rwidmark** [comment]
@adamdriscoll  this was not been released don't show in the release notes for 3.2.0 and it's not showing up under download @ powershell universals webpage.

**Comment by adamdriscoll** [comment]
@rstolpe - This was implemented but we didn't deploy it for some reason. I'll make sure it gets on the website and into our nightly builds starting with 3.2.1

**Comment by adamdriscoll** [comment]
This was actually published but was not added to the download page. We're deploying a new version of the website to include it.
