### ISSUE TITLE
Automation: Merge jobs

### ISSUE THREAD

**Issue by arunrajann** [ironmansoftware/powershell-universal#1374]
### Summary of the new feature / enhancement

When a script is called / triggered from another script using 'Invoke-PSUScript', the PSU is creating a new / separate job for the child. I am sure there is a good reason why this design pattern is implemented. It becomes a little harder to analyze the log information created by the individual script as we have to jump back and forth between multiple jobs. It would `be great if we have an option to treat them as one integral job and log all the information in one job.

Invoke-PSUScript -Name DataExtract.ps1 -SourceSystemHostName $_SourceSystemHostName -SourceDatabaseName $_SourceDatabaseName 

### Proposed technical implementation details (optional)

Add a Parameter to 'Invoke-PSUScript' Cmdlet to treat them as one job / not to create a new job.

**Comment by adamdriscoll** [comment]
You could effectively do this by using -Wait. It would bring the errors, warnings and output from the other script into the calling script.

**Comment by arunrajann** [comment]
Appreciate looking into this request. Below are my current finding with sample script to simulate the issue

Based on my observation, messages are still written to the child job, in addition to that a error message 'Object reference not set to an instance of an object' is written to output when -Wait parameter is used but the system does wait until the child process is complete. I was hoping if there is a way to run just one job. At the least if the log-messages were written to parent job that would be great. No idea why we receive a object reference issue, am I missing something ?

Version : 3.1.0

**Parent script**
      
      Write-Host 'Begin Parent job...'       
      $output = Invoke-PSUScript -Name TestScript.ps1 -Wait      
      Write-Host 'Completed Parent job...' 

**Child Script** 

          param(
          )          
          write-host "Begin executing Child script..."          
          Start-Sleep -Seconds 20

Parent Job output
      
![image](https://user-images.githubusercontent.com/109398879/179425134-7adb422b-ac9f-4664-bed5-158d43ebb2a7.png)

Child job output
        
![image](https://user-images.githubusercontent.com/109398879/179425174-63b479c6-bcbc-4b83-906a-9cc2f7ae8090.png)

**Comment by adamdriscoll** [comment]
This shouldn't be happening. Let me try to reproduce this.

**Comment by adamdriscoll** [comment]
Can you try to use integrated mode? I just put together an integration test for this that works so this may be a workaround. 

```
Invoke-PSUScript  -Name TestScript.ps1 -Wait  -Integrated
```

**Comment by arunrajann** [comment]
No luck. Screenshot below for reference...

![image](https://user-images.githubusercontent.com/109398879/179426974-375dcd7a-5e18-429d-ab04-7b552166398e.png)

![image](https://user-images.githubusercontent.com/109398879/179427071-5b7b64ec-9a52-4ebe-8bf2-bfd05e759504.png)

![image](https://user-images.githubusercontent.com/109398879/179427016-0fa1b400-c813-4ccd-9bd1-a4482f79ce72.png)

![image](https://user-images.githubusercontent.com/109398879/179427036-fab24754-5496-4f5d-bef8-c25b9d4230ab.png)

**Comment by adamdriscoll** [comment]
@arunrajann - Can you let me know what version you are using?

**Comment by arunrajann** [comment]
Version : 3.1.0 (2653491244)

Downloaded from the main download page on 7/12/2022.

**Comment by arunrajann** [comment]
Below is reference from another Team member in the community who received an error when -Wait parameter is used. 

I could use ' | Wait-PSUJob ' to make the parent process to wait until the child process is complete... However, using it does not write the message / merge the child job with Parent which is what I was hoping to accomplish.

https://forums.ironmansoftware.com/t/invoke-psuscript-object-error/7296

**Comment by adamdriscoll** [comment]
I have reproduced this and it will be fixed in 3.1.4

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/regarding-invoke-psuscript/7419/1
