### ISSUE TITLE
Automation : Request to add Standard email notification

### ISSUE THREAD

**Issue by arunrajann** [ironmansoftware/powershell-universal#1378]
### Summary of the new feature / enhancement

While scheduling a given script, please add a default option to configure email notification for Success  and Error job status.
Each Schedule may potentially have different email notification group

**Comment by adamdriscoll** [comment]
You can achieve this with triggers right now: https://docs.powershelluniversal.com/automation/triggers

I realize this isn't totally built in but is possible.

**Comment by adamdriscoll** [comment]
We've added this to our solution library that will be included with v5. 

https://github.com/ironmansoftware/scripts/tree/0.0.3
