### ISSUE TITLE
Automation : Display Schedule status (Paused)

### ISSUE THREAD

**Issue by arunrajann** [ironmansoftware/powershell-universal#1379]
### Summary of the new feature / enhancement

When a Schedule is paused, it's status enabled / paused is not displayed in the screen. We will need to open individual schedules to identify if it is enabled or not

### Proposed technical implementation details (optional)

Include a column to indicate the current status of Schedule if it is Paused or now. Or may be color code it in RED / GREY which ever best fits application design / enhancement.

**Comment by adamdriscoll** [comment]
We display the text "Paused" for the next execution and I've made it so thta text is a different color now. 

![image](https://user-images.githubusercontent.com/1256531/179417436-9fd0def6-6242-45aa-90a2-0a4a31243116.png)

**Comment by arunrajann** [comment]
Thanks @adamdriscoll
