### ISSUE TITLE
Cannot set Schedule Environment in Web UI

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/powershell-universal#1382]
### Summary of the new feature / enhancement

One cannot set the Environment for a `PSUSchedule` in the Web UI at `/admin/automation/schedules`

### Proposed technical implementation details (optional)

Add 'Environment' field to Schedule Resource Properties modal.

**Comment by mrhector** [comment]
I came to post about the same thing. I think this is actually a GUI bug. The documentation shows a dropdown box to select the environment in the scheduling UI. @adamdriscoll can you confirm if this just a bug? 

Doc: https://docs.powershelluniversal.com/automation/schedules#cron

Current view in v3.1.3 when setting the schedule. 
![image](https://user-images.githubusercontent.com/1563177/179864068-c790d71d-47e7-4597-8485-0d24240fd12a.png)

**Comment by adamdriscoll** [comment]
@mrhector I'm not seeing this. Currently running 3.2. 

![image](https://user-images.githubusercontent.com/1256531/183943256-a7de50e0-49ae-4239-8c31-a0a0583e6503.png)

The environment will not be shown if it is selected on the script.

**Comment by adamdriscoll** [comment]
Closing this issue as stale. If you are still having this issue, let me know.
