### ISSUE TITLE
provide setting for number of script items to show per page

### ISSUE THREAD

**Issue by alexrgreenwood** [ironmansoftware/powershell-universal#1387]
### Summary of the new feature / enhancement

I have a large number of script in certain folders (and a large montor) , and would like to be able to set PSU to always show 30 items per page, right now if keeps defaulting to 10 / page

### Proposed technical implementation details (optional)

I'd like to have a setting in settings>general>automation where i can set serverwide how many items / page to show by default

**Comment by adamdriscoll** [comment]
Completed with commit [701cde4](https://github.com/ironmansoftware/universal/commit/701cde482e331a8f8a00ab27d9e574adf258575a)
