### ISSUE TITLE
New-PSUSchedule -Cron doesnt allow @reboot

### ISSUE THREAD

**Issue by mikedhanson** [ironmansoftware/powershell-universal#139]
**Describe the bug**
Trying to create a crontab to run script when PSU restarts. However getting the following error message when trying to create the schedule "Failed to format description: Error: Expression only has 1 parts. At least 5 part are required."

**To Reproduce**
1. Go to 'Automation / schedules'
2. Click on 'New schedule'
3. select script 
4. Under "Cron" fill out "@reboot"
5. ![image](https://user-images.githubusercontent.com/15201245/115578599-0e5c0e80-a28b-11eb-8331-b2fd867d772f.png)

**Expected behavior**
Schedule allows all crontab expressions

**Screenshots**
![image](https://user-images.githubusercontent.com/15201245/115578793-3481ae80-a28b-11eb-844e-992e53bf0847.png)

**Version**
Version Number: 1.5.14
Dashboard Framework (if applicable): 
Operating System: Server 2019

**Comment by adamdriscoll** [comment]
This isn't supported by hangfire. You can accomplished this with a Server Started trigger.
