### ISSUE TITLE
License warning in non-PowerShell project types

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1397]
## Describe the bug
In some situations, the "_Go to Definition_" (F12) feature of Visual Studio may be blocked when in a non-PowerShell project type (e.g. C#)

## To Reproduce
1. Have unlicensed PowerShell Pro Tools extension installed in Visual Studio
2. Create a new non-PowerShell project (e.g. C#)
3. Use the "_Go To Definition_" (F12) feature to trigger the error. See gif further below.

⚠ You may need to load a PowerShell project first, fire the license warning then go to C#

## Expected behavior
Any warnings or blockings within a non-PowerShell project type should not occur based on interference from PowerShell Pro Tools

## Screenshots
![Issue1395c](https://user-images.githubusercontent.com/537287/180116714-56a2333b-d12c-4907-b3f7-eb7ecae61353.gif)

## Version
PowerShell Pro Tools 7.0
Visual Studio 2022

**Comment by DataTraveler1** [comment]
Credit to the user on the Ironman Software Discord who reported this 👍

**Comment by adamdriscoll** [comment]
Cannot reproduce on latest.
