### ISSUE TITLE
Search scripts by Tag issue 

### ISSUE THREAD

**Issue by arunrajann** [ironmansoftware/powershell-universal#1398]
### Steps to Reproduce

When one or more script is not assigned with Tags. Below script is experiencing error

Get-PSUScript -Tag “Test” 

More info available in https://forums.ironmansoftware.com/t/potential-bug-when-search-by-tag/7433

No issue when all script are assigned with Tag

### Expected behavior

```console
Return script meeting the Tag criteria
```

### Actual behavior

```console
[error] Object reference not set to an instance of an object.
```

### Environment data

PSU 3.1.4

### Visuals

![image](https://user-images.githubusercontent.com/109398879/180120240-860ba6c1-1f0f-4f0a-a4f7-e25572a1f08e.png)

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/potential-bug-when-search-by-tag/7433/3
