### ISSUE TITLE
Refactoring large block of code with VS Code not working

### ISSUE THREAD

**Issue by rtonerii** [ironmansoftware/powershell-universal#14]
I am trying to refactor a block of code and nothing happens.

How can I get an error or anything to come up and tell me why it is not working?

I have tested that I can do a small block, just not the whole thing.

Here is the code I am trying to refactor, which does work when I run it.

`                #  Get field info
                $spField = $spListFields | Where-Object { $_.InternalName -eq $spToSqlField.SpField }
                if ($spField.TypeAsString -eq "DateTime") {
                    if ($destRecord[$spToSqlField.SpField].Date -ne $sourceValue[$spToSqlField.SqlField].Date) {
                        # Write-Host "$($destRecord[$spToSqlField.SpField].Date) <> $($sourceValue[$spToSqlField.SqlField].Date)"
                        $fieldValueList.Add( $spToSqlField.SpField, (Get-ValueFormat $spToSqlField $sourceValue) )
                    }
                }
                elseif ($spField.TypeAsString -eq "User") {
                    $destValueLookup = [Microsoft.SharePoint.Client.FieldUserValue]$destRecord[$spToSqlField.SpField]
                    if (![string]::IsNullOrEmpty($destValueLookup.Email ) -or ![string]::IsNullOrEmpty($sourceValue[$spToSqlField.SqlField])) {
                        $sourceValueLookup = Get-PnPUser -Identity "i:0#.f|membership|$($sourceValue[$spToSqlField.SqlField])" -ErrorAction SilentlyContinue
                        if ($destValueLookup.Email -ne $sourceValueLookup.Email) {
                            Write-Host "$($destValueLookup.Email) <> $($sourceValue[$spToSqlField.SqlField])"
                            $fieldValueList.Add( $spToSqlField.SpField, (Get-ValueFormat $spToSqlField $sourceValue) )
                        }
                    }
                }
                elseif ($spField.TypeAsString -eq "Choice") {
                    if ($destRecord[$spToSqlField.SpField] -ne $sourceValue[$spToSqlField.SqlField]) {
                        $destValueLookup = ($spListFields | Where-Object { $_.InternalName -eq $spToSqlField.SpField }).Choices | Where-Object{$_ -eq $sourceValue[$spToSqlField.SqlField]}
                        Write-Host "$($destRecord[$spToSqlField.SpField]) <> $($sourceValue[$spToSqlField.SqlField])"
                        $fieldValueList.Add( $spToSqlField.SpField, $destValueLookup)
                    }
                }
                elseif (![string]::IsNullOrEmpty($destRecord[$spToSqlField.SpField]) -or ![string]::IsNullOrEmpty($sourceValue[$spToSqlField.SqlField])) {
                    if ($destRecord[$spToSqlField.SpField] -ne $sourceValue[$spToSqlField.SqlField]) {
                        Write-Host "$($destRecord[$spToSqlField.SpField]) <> $($sourceValue[$spToSqlField.SqlField])"
                        $fieldValueList.Add( $spToSqlField.SpField, (Get-ValueFormat $spToSqlField $sourceValue) )
                    }
                }`

**Comment by adamdriscoll** [comment]
Fixed in 5.22.6
