### ISSUE TITLE
Installing modules , prerelease and local repository

### ISSUE THREAD

**Issue by alexrgreenwood** [ironmansoftware/powershell-universal#1403]
### Summary of the new feature / enhancement

id like to be able to install this module

https://www.powershellgallery.com/packages/ExchangeOnlineManagement/2.0.6-Preview6

but only 2.0.5 is returned from the PSGallery option but it doesnt seem to have Connect-ExchangeOnline cmdlet
(have worked around it by copying the module from another server)

also would like to be able to install from/search a local repo 

### Proposed technical implementation details (optional)

add -AllowPrerelease to the PSGallery search form

**Comment by adamdriscoll** [comment]
Any registered module repositories will show up in the drop down. We currently don't have a UI for it. As for prerelease, this work has been completed for 3.2.
