### ISSUE TITLE
Persist Page Size in Admin Console

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1406]
### Summary of the new feature / enhancement

https://forums.ironmansoftware.com/t/scripts-per-page-setting/7438

**Comment by alexrgreenwood** [comment]
+1 , kinda what i was getting at with this issue
https://github.com/ironmansoftware/issues/issues/1387

**Comment by adamdriscoll** [comment]
Completed with commit [701cde4](https://github.com/ironmansoftware/universal/commit/701cde482e331a8f8a00ab27d9e574adf258575a)
