### ISSUE TITLE
Dashboard Editing Tools

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1408]
### Summary of the new feature / enhancement

We should enhance the dashboard editing experience in PSU. I'm envisioning a central pane where the dashboard is displayed in an iframe. At the bottom we have a code editor that displays the dashboard code and can be edited. On the left hand side, we have tool windows that provide additional information. Think WPF Editor. 

You will be able to select controls within the dashboard to view the state of the control and it will populate a tool window on the left hand side. The dashboard will autoreload when changes are made. 

Tool windows will include: 
- Dashboard Log
- Selected Component Properties and date
- Session State
- Cache State
- Dashboard Console 
- Events (Clicking, Set-UDElement, Sync-UDElement, etc) 
- File Explorer for multi-file dashboards

**Comment by MikeShepard** [comment]
The advanced editor needs an Exit option.

**Comment by Omzig** [comment]
what does `Events (Clicking, Set-UDElement, Sync-UDElement, etc)` mean?
