### ISSUE TITLE
Remove New-UDTabContainer from UniversalDashboard module manifest

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1410]
### Steps to Reproduce

1. Open a PowerShell prompt in which UniversalDashboard is loaded
2. Type New-UDTab and then cycle through available commands with [TAB]
3. Note that New-UDTabContainer is available in the list but is not actually available (see Visuals below)

Root cause: 'New-UDTabContainer' is defined as a function on export on line 191 of UniversalDashboard.psd1

Thank you to contributors who reported this on the forums at https://forums.ironmansoftware.com/t/is-new-udtabcontainer-valid-in-powershell-universal/7452

### Expected behavior

```console
New-UDTabContainer should not be available in the list of functions to export
```

### Actual behavior

```console
New-UDTabContainer is available in the list of functions to export which leads to confusions
```

### Environment data

UniversalDashboard module 4.1.0

### Visuals

![Issue1410b](https://user-images.githubusercontent.com/537287/180667354-16211993-f870-4070-b28f-13dddd4f59b9.gif)

**Comment by DataTraveler1** [comment]
I meant to include a screenshot of the .psd1

![image](https://user-images.githubusercontent.com/537287/180667156-cd4c07cf-2bae-4f08-8e03-6a9d67cd7a21.png)

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/is-new-udtabcontainer-valid-in-powershell-universal/7452/4
