### ISSUE TITLE
Best Practices Documentation

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1411]
### Summary of the new feature / enhancement

We should include a best practices section in our documentation. This should include topics like: 

- Dashboard best practices
- Environment best practices
- Persistence best practices (grooming etc) 
- Common issues with modules 
- Credentials and secrets

**Comment by adamdriscoll** [comment]
I've added a document here: https://docs.powershelluniversal.com/config/best-practices

I'll continue to update this.

**Comment by potatoqualitee** [comment]
super useful! thank you 🙇🏼
