### ISSUE TITLE
New-UDMultiSelect Form Input

### ISSUE THREAD

**Issue by mwatts-seg** [ironmansoftware/powershell-universal#1415]
### Summary of the new feature / enhancement

There use to be a module that allowed multi-selection dropdown for form controls, but it looks like it is no longer supported. It would be nice if this was native. 

In the dashboard, I am trying to keep my form nice and compact, without having to throw a bunch of checkboxes in there. 

### Proposed technical implementation details (optional)

I believe it could be done via using MUI React component: 
https://mui.com/material-ui/react-select/#multiple-select

**Comment by adamdriscoll** [comment]
@mwatts-segops - In the meantime, you could try to use New-UDAutocomplete. It's similar and has a -Multiple parameter.

**Comment by mwatts-seg** [comment]
> @mwatts-segops - In the meantime, you could try to use New-UDAutocomplete. It's similar and has a -Multiple parameter.

Thank you! I will take a look at it.
