### ISSUE TITLE
Nightly 3.2 - MSI Fails to Start Service

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1416]
### Steps to Reproduce

Service is failing during startup. Not yet known why. 

### Expected behavior

```console
Starts just fine.
```

### Actual behavior

```console
Doesn't start.
```

### Environment data

3.2 Nightly

**Comment by alexrgreenwood** [comment]
error in application log was...

Exception Info: Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)

3.2.0 (2743347916) - also had same problem with 3.1.6
**got this to start by adding `Encrypt=False` to my sql server connection string**


could be related to 
https://stackoverflow.com/questions/17615260/the-certificate-chain-was-issued-by-an-authority-that-is-not-trusted-when-conn

**Comment by adamdriscoll** [comment]
@alexrgreenwood - Thanks. We may roll this change back due to this issue but it also seems like it would be good to upgrade to the latest SQL client. I'll let you know where we land.

**Comment by adamdriscoll** [comment]
We decided to keep this change and document the breaking change because it offers a better default security posture.
