### ISSUE TITLE
New-UDUpload fails when using SQL persistence

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1428]
### Steps to Reproduce

https://forums.ironmansoftware.com/t/system-invalidoperationexception-the-linq-expression-dbset-upload/7504

### Expected behavior

```console
Upload works as expected
```

### Actual behavior

```console
Upload fails with LINQ error
```

### Environment data

3.1.6

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/system-invalidoperationexception-the-linq-expression-dbset-upload/7504/2

**Comment by potatoqualitee** [comment]
AWW YEAHHH 🥳
