### ISSUE TITLE
The currently active route should have an "active" class

### ISSUE THREAD

**Issue by potatoqualitee** [ironmansoftware/powershell-universal#1431]
### Summary of the new feature / enhancement

Hello,
This is a follow up to: https://forums.ironmansoftware.com/t/setting-sidenavitem-background-colour-when-page-active/2345

I've hired a CSS dev to make my site pretty and she has the same issue. Here is what she said:

> I'm having problems styling the left navigation how I think should be done due to the fact that the currently active page (route) is not distinguishable from the rest of the links in the navigation. The functionality I'm hoping for is what is on http://localhost:5000/admin (and it would be styled differently of course). The below functionality is outlined generally but we can go into more details of it if you'd like! I could write some of this functionality with custom JS, but I feel like these changes would be better suited for PowerShell so that what I need is returned on load.

### Proposed technical implementation details (optional)

Here was her suggestion

* The currently active route should have an "active" class on the parent element (MuiButtonBase-root)
* If the currently active route is inside of a nested item, both the parent item and the active item will have a class. I would suggest the parent item have an attribute of `data-collapse="collapse"` or `data-collapse="collapsed"` based on the state. 
* If the currently active route is inside of a nested item, the nested items will be expanded on load.

**Comment by adamdriscoll** [comment]
This has been implemented by simplifying how custom navigation will work in v3.3. You can now use -Href instead of -OnClick to redirect to other pages. 

```
$Navigation = @(
    New-UDListItem -Label "Home" -Href "/Test"
    New-UDListItem -Label "Getting Started" -Children {
        New-UDListItem -Label "Installation" -href '/test2'
        New-UDListItem -Label "Usage" -Href'/usage'
        New-UDListItem -Label "FAQs" -Href '/faqs' 
        New-UDListItem -Label "System Requirements" -Href '/requirements' 
        New-UDListItem -Label "Purchasing" -Href '/purchasing'
    }
)
```

When this is configured this way, the ListItem will be aware of the current route and can apply the correct CSS style. You'll see a `Mui-selected` style on the list item for the current page.

**Comment by potatoqualitee** [comment]
Oh yeahhh! TY 🙇🏼
