### ISSUE TITLE
Support style customization of chart.js grid lines

### ISSUE THREAD

**Issue by st3phhays** [ironmansoftware/powershell-universal#1440]
### Summary of the new feature / enhancement

While trying to style a bar chart from chart.js, I am unable to style the grid lines themselves. I am following documentation from https://www.chartjs.org/docs/latest/axes/styling.html#grid-line-configuration and also looking at how stacked bar charts are implemented on PowerShell Universal for pointers. The following code does not have any effect on the color of the grid lines, although it should based on the docs. 

```
Options = @{
    scales = @{
        xAxes = @{
            grid = @{
                color = '#ff0000'
            }
        }
    }
}
```

### Proposed technical implementation details (optional)

```
Options = @{
    scales = @{
        xAxes = @{
            grid = @{
                color = '#ff0000'
            }
        }
    }
}
```

**Comment by adamdriscoll** [comment]
The problem was that UD was still using ChartJS v2. In the next release, we'll us v3.9.1.
