### ISSUE TITLE
Charts do not work with rgb or rgba colors

### ISSUE THREAD

**Issue by st3phhays** [ironmansoftware/powershell-universal#1441]
### Steps to Reproduce

Create a new chart. For example:

```
$Data = Get-Process | Sort-Object -Property CPU -Descending | Select-Object -First 10 
New-UDChartJS -Type 'horizontalBar' -Data $Data -DataProperty CPU -LabelProperty ProcessName -BackgroundColor 'rgb(255,0,0)'
```

Notice how the chart itself displays, but does not show any bars.

### Expected behavior

```console
Creating a chart using rgb or rgba colors should work the same as using a hex value. This will really come in handy when it comes to styling charts that look good on both dark/light modes.
```

### Actual behavior

```console
The chart does not display any data when using rgb or rgba colors.
```

### Environment data

Windows, Latest PSU

### Visuals

Chart while trying to use rgb colors or rgba colors:

![Screen Shot 2022-08-05 at 10 18 29 AM](https://user-images.githubusercontent.com/42750725/183108321-885dd727-7130-4fb4-b676-f64a45dd0fe9.png)

**Comment by st3phhays** [comment]
After a bit of digging, I read in the old PowerShell Dashboard docs that [ARGB colors are supported](https://docs.universaldashboard.io/look-and-feel/colors#rgb-colors), and that seems to work for this case perfect. However I am using ARGB Hex colors, to be honest, I don't know the difference. I am using this tool, and seems to work well with converting: https://hugabor.github.io/color-picker/.  Might be good to add this to the docs here? Seems like rgb/rgba colors work fine on most components, but charts it does not work on.

Note that ARGB Hex colors don't seem to work as expected on other components, only on charts, however Hex values with an alpha channel do. 🤔

**Comment by adamdriscoll** [comment]
We were effectively clearing out the color value if the rgb string was sent in. It's kinda funny because there is a process in the chart code to parse the hex strings, turn then Color object and then finally turn them into an rgb string. 😁rbg colors will work going forward.
