### ISSUE TITLE
Add an indicator on the <head> element of what theme is in use

### ISSUE THREAD

**Issue by st3phhays** [ironmansoftware/powershell-universal#1442]
### Summary of the new feature / enhancement

When styling components for both dark/light modes, it would be useful to have something in the html itself that can be referenced from css to indicate what theme is currently active (dark/light).

### Proposed technical implementation details (optional)

On load and on theme toggle, this is appended to the <head> element based on what theme is currently being used.

```
<head data-theme="dark">
```

or

```
<head data-theme="light>
```

This will allow styling from css to target what mode is currently active, especially for components that may be tricky to style inside of the theme.ps1. 

For example in the css, it could be used like this:

```
:root[data-theme="dark"] {
   --color-one: #000000;
}
:root[data-theme="light"] {
   --color-one: #ffffff;
}

.element {
    background-color: var(--color-one);
}
```

**Comment by adamdriscoll** [comment]
We are now adding `data-theme` to the `<html>` tag. 

I couldn't get the CSS variables to work for some reason but I did test it like this: 

```
:root[data-theme="dark"] #element {
    background-color: blue;
}

:root[data-theme="light"] #element {
    background-color: aqua;
}
```

My dashboard was like this. 

```
New-UDDashboard -Content {
 New-UDElement -Tag 'div' -Content {
            "Hello"
        } -Id 'element'
} -Stylesheets "http://localhost:5000/media/styles.css"
```

The HTML structure now looks like this. 

![image](https://user-images.githubusercontent.com/1256531/183931427-b0c5cb8c-f68e-4697-aeae-26dc923c4333.png)

**Comment by st3phhays** [comment]
This is a great addition, thank you!

**Comment by potatoqualitee** [comment]
tearin it up, thanks @st3phhays !
