### ISSUE TITLE
Ability to clear Jobs

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1445]
### Summary of the new feature / enhancement

It would be ideal if it was possible to conveniently clear away completed Jobs from the UI

### Proposed technical implementation details (optional)

A button which could add a property to the jobs which enables them to be filtered out in the UI

![image](https://user-images.githubusercontent.com/537287/183259080-874bbe42-6cc8-44a2-9dd1-e3d0499e2281.png)
###### figure above shows an example of the feature imagined

**Comment by adamdriscoll** [comment]
@mattselle - Let's not actually delete them but add an archived flag to them so we can just hide them for display purposes and then still view them for auditing purposes. We should also just an Archive Job button for an individual job.
