### ISSUE TITLE
The MSI Setup error prompt should include other possibilities for failure

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1448]
### Steps to Reproduce

1. Install the MSI version of PSU
2. During the setup, configure a service account but use intentionally incorrect credentials
3. Receive the below error message about insufficient privileges

`Service 'PowerShell Universal' (PowerShellUniversal) could not be installed.  Verify that you have sufficient privileges to install system services.`

### Expected behavior

```console
The possibility of bad credentials (or other failure reasons) should be included in the setup error prompt (pictured below)
```

### Actual behavior

```console
The possibility of bad credentials (or other failure reasons) is not included in the setup error prompt (pictured below)
```

### Environment data

PSU 3.1.6 (MSI Install)
Windows Server 2012 R2

### Visuals

![image](https://user-images.githubusercontent.com/537287/183311215-3e751d40-0827-4eab-8425-1d3b1e7ac872.png)

**Comment by mwatts-seg** [comment]
@DataTraveler1 @adamdriscoll I am seeing this trying to upgrade to 3.2.0 on two servers. 
I stopped both services prior to doing this. I use a service account for both services. I ensured the password is correct, but it will not continue past this.

**Comment by DataTraveler1** [comment]
@mwatts-segops - Can you confirm that you are using domain\username format for the username of the credential?

**Comment by adamdriscoll** [comment]
The MSI will now suggest looking in the log file (including the location of the file). We can't get a super clear message back from the installer framework in this case because the service just failed to start but the log file will have a very detailed log message.
