### ISSUE TITLE
Loading skeleton shows in the wrong section

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1457]
### Steps to Reproduce

Add menu and if the page are loading the skeleton are showing on the wrong place, se picture.
![Screenshot 2022-08-09 at 20 40 02](https://user-images.githubusercontent.com/76907327/183736604-06cb6a86-bc87-40ca-af61-ac319d1ea08c.png)

It was working in PSU 3.1.6

### Expected behavior

```console
Skeleton on loading should not be in the menu, and the page should be white during loading as now when it load you can open the side menu but it's nothing there as the dashboard are still loading.
The same behaviour as in PSU 3.1.6 should apply.

```

### Actual behavior

```console
Skeleton are showing in the menu when loading
```

### Environment data

PSU 3.2.0

**Comment by rwidmark** [comment]
@adamdriscoll GUI bug here in PSU 3.2.0 :(

**Comment by rwidmark** [comment]
@adamdriscoll if you need I can provide with more data and video of the issue but then you need to provide me with a link where I can upload it.

**Comment by rwidmark** [comment]
@adamdriscoll  updated the issue

**Comment by adamdriscoll** [comment]
I saw this on another customer's dashboard today. I know what's happening. We had to change the React structure of the dashboard pages do implement this #1426 and it's causing this problem.
