### ISSUE TITLE
Autoselect don't show icon and label are in the text

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1458]
### Steps to Reproduce

This was working in PSU 3.1.6 now the icon are gone for autoselect and the label are down once again where you write, se picture.
![Screenshot 2022-08-09 at 20 40 18](https://user-images.githubusercontent.com/76907327/183737005-da53fb57-9167-484e-a990-04ede0526698.png)

### Expected behavior

```console
Icon should show and the label text should not be in the textbox.
```

### Actual behavior

```console
Icon are not working and the label are in the textbox
```

### Environment data

PSU 3.2.0

**Comment by rwidmark** [comment]
@adamdriscoll  this bug are showing in many releases now. Icon are missing once again.

**Comment by rwidmark** [comment]
@adamdriscoll if you need I can provide with more data and video of the issue but then you need to provide me with a link where I can upload it.

**Comment by adamdriscoll** [comment]
The reason this happen edagain is that when the icon is displayed, it no longer displays the selected items, which made the component very hard to use for end users. This happens specifically when using dynamic autocompletes with the ability to select multiple items. I'll look at solving this icon issue. It happened when we upgraded to the new MUI version.

**Comment by adamdriscoll** [comment]
Ok. I figured out a way to do this. I can't use quite the same method but it will allow the icon to be shown.
