### ISSUE TITLE
[v3.2.1] Icon for Autocomplete are not aligned

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1462]
### Steps to Reproduce

The icon for the Autocomplete are not aligned / same size as the textfield.
![image](https://user-images.githubusercontent.com/76907327/183879786-a5f557e9-695d-44f6-8f64-fa50c3f93cc9.png)

![image](https://user-images.githubusercontent.com/76907327/183879847-013e0f69-ca4e-4141-8f56-9007df8b3644.png)

It should look something like this: (don't mind the text it's not where the issue are it's with the icon)
![image](https://user-images.githubusercontent.com/76907327/183880051-2af7926d-1958-4c6e-af4e-ee99ae60c0f7.png)

### Expected behavior

```console
That the icon are aligned / proper size with the textbox.
```

### Actual behavior

```console
The icon are not aligned / proper size.
```

### Environment data

PSU 3.2.1

**Comment by rwidmark** [comment]
@adamdriscoll  how do you prefer that I label the bug reports for the nightly betas? is it OK in the way that I do now with [v3.2.1] or similar?

**Comment by adamdriscoll** [comment]
This is great. The one thing that might be helpful to include is the build ID: 3.2.1 (**2829158964**)
