### ISSUE TITLE
Write-* Cmdlets stop working after dashboard restart

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1468]
### Steps to Reproduce

https://forums.ironmansoftware.com/t/consistent-dashboard-log/7580

### Expected behavior

```console
Write-* should work all the time
```

### Actual behavior

```console
Write-* stops working after dashboard restart.
```

### Environment data

3.2.0

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/consistent-dashboard-log/7580/2

**Comment by potatoqualitee** [comment]
Out of curiosity, what's a summary of what happened here/what fix it? 🙇🏼

**Comment by adamdriscoll** [comment]
When we refreshed the content of the dashboard via the auto-reload functionality, we were wiping out the dashboard ID so then the logging would stop working properly. Mostly just a logic error.
