### ISSUE TITLE
1.6 Beta - UX Light Theme does not show Username and Password 

### ISSUE THREAD

**Issue by az-kennedy** [ironmansoftware/powershell-universal#147]
**Describe the bug**
Minor bug - 

The logon splash page by default is in the light mode.  When I type in my username and password it does not show up in the html text boxes.

![image](https://user-images.githubusercontent.com/10156425/116285403-1371ff80-a75c-11eb-9311-718fb8147942.png)

Dark mode is fine

![image](https://user-images.githubusercontent.com/10156425/116285649-57650480-a75c-11eb-9bc2-b87825218a66.png)

**Comment by adamdriscoll** [comment]
Fixed in beta4
