### ISSUE TITLE
DataMigrator - SQL to LiteDB

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1472]
### Summary of the new feature / enhancement

Customer wants to move SQL data to LiteDB

**Comment by potatoqualitee** [comment]
Interesting! Can I ask what prompted the move back to LiteDB?

**Comment by adamdriscoll** [comment]
The user developed their instance on LiteDB and then moved to SQL. They had some issues with certain limitations of PSU (primarily the single job queue). Some of their solution depended on caching data on each node and since the job queues are not node specific, this caused a bunch of issues. Because their deployment window is coming up, they'd like to keep some of their SQL data, like app tokens, and move to LiteDB for the time being. 

We have this functionality in the backlog but it won't be done in time.

**Comment by potatoqualitee** [comment]
Awesome, thanks for the info!
