### ISSUE TITLE
New-UDTooltip missing from docs

### ISSUE THREAD

**Issue by JQ1983** [ironmansoftware/powershell-universal#1485]
### Steps to Reproduce

New-UDTooltip is nowhere to be found in https://docs.powershelluniversal.com/

### Expected behavior

```console
Searching https://docs.powershelluniversal.com/ for 'New-UDTooltip' gives documentation about this cmdlet
```

### Actual behavior

```console
Searching https://docs.powershelluniversal.com/ for 'New-UDTooltip' gives no result
```

### Environment data

3.2.1

**Comment by adamdriscoll** [comment]
https://docs.powershelluniversal.com/userinterfaces/dashboards/components/data-display/tooltip
