### ISSUE TITLE
Editing API Environment not possible in GUI

### ISSUE THREAD

**Issue by schubfre** [ironmansoftware/powershell-universal#1487]
### Steps to Reproduce

Using the GUI it's not possible anymore to change the environment (e.g. from Default to Integrated). No errors are posted and the edit box closes without issue, it just doesn't get saved properly. Changing the environment in the code is, of course, still possible.

### Expected behavior

```console
Changing the environment for an endpoint in the GUI gets applied.
```

### Actual behavior

```console
Changing the environment for an endpoint in the GUI doesn't get applied.
```

### Environment data

3.1.6

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/access-controls-buggy-in-gui/7603/1
