### ISSUE TITLE
Dashboard Slowness

### ISSUE THREAD

**Issue by mwatts-seg** [ironmansoftware/powershell-universal#1493]
### Steps to Reproduce

Experiencing extreme slowness on all dashboards, even simple ones. 

Here is a dashboard experiencing the issue, but all dashboards are experiencing slow downs:

```
$Pages = @()
$Pages += New-UDPage -Name "Test 1" -Url 'Test' -Content { 
        Switch ($roles) { 
            'User1' {
                New-UDcard -Title "Role $_" -Content {
                    "$($roles -contains $_)"
                }
            } 'User2' {
                New-UDcard -Title "Role $_" -Content {
                    "$($roles -contains $_)"
                }
            } 'Support' {
                New-UDcard -Title "Role $_" -Content {
                    "$($roles -contains $_)"
                }
            } 'PowerShellUniversal_Admins' {
                New-UDcard -Title "Role $_" -Content {
                    "$($roles -contains $_)"
                }
            } 'Administrator' {
                New-UDcard -Title "Role $_" -Content {
                    "$($roles -contains $_)"
                }
            }
        } 

        New-UDDynamic -Id 'card' -Content {
            New-UDCard -Text "You selected $Session:Selection"
        }

        New-UDForm -Content {
              
            New-UDTextbox -Label 'Employee ID:' -Mask "00000000" -id 'empID' -Autofocus
              
            New-UDselect -Id 'Selection' -Option {
                New-UDSelectOption -Name '1' -Value '1'
                New-UDSelectOption -Name '2' -Value '2'
                New-UDSelectOption -Name '3' -Value '3'
            }
        } -OnSubmit {
            $Session:Selection = $EventData.Selection
            Show-UDToast $Body
            Sync-UDElement -Id 'card'
        }
}

New-UDDashboard -Pages $Pages -Title 'Test' #-Theme $dbTheme
```

### Expected behavior

```console
Depending on the complexity of the dashboard, I know the times can vary. This one is very short and happens on every reload. I would expect it to take a few seconds at most.
```

### Actual behavior

```console
Taking 30+ seconds to load
```

### Environment data

Windows Server 2022
PSU 3.2.3

### Visuals

![image](https://user-images.githubusercontent.com/60755343/185205502-d6b48d14-a817-4938-9ef4-7f155988ad30.png)

**Comment by adamdriscoll** [comment]
@mwatts-segops - Yeah that's way too slow. One thing you can try to narrow it down is to use the profiler: https://docs.powershelluniversal.com/development/profiling

**Comment by mwatts-seg** [comment]
Hey @adamdriscoll 

I did this and restarted the services on both nodes. I accessed that profiler page first and then loaded a dashboard. 
I also spun up a test dashboard. Doing New-UDTextbox or something similar was very responsive. I wrapped it in a New-UDForm with two controls (Textbox & Button) and refreshed the page, took about 30-45 seconds to load. As long as I did not restart the dashboard, it was quick. Restarting the dashboard or loading a private tab results in slow loading times for even the sample dashboard. 

Here is the profiler page, I am not sure if the times are in milliseconds or seconds. 
![image](https://user-images.githubusercontent.com/60755343/185232901-eada17c5-5f92-41e3-b2c4-ba883dd27e55.png)

EDIT:

<html>
<body>

/notificationhub | 2022-08-17T20:04:24.6066229Z | 121974.8
-- | -- | -- | --
<br class="Apple-interchange-newline">
</body>
</html>

**Comment by adamdriscoll** [comment]
The timing is always in milliseconds. If you click on any one of those URLs you'll get a breakdown of the request. 

dashboardhub and notificationhub will always have long durations because they are long lived websocket connections so you can ignore those. 

Feel free to open a support ticket about this. I'm really surprised something in-between these releases is causing this so I'm super curious to get to the bottom of it.

**Comment by mwatts-seg** [comment]
Sounds good, I will definitely open a support ticket. 
Thank you!

**Comment by adamdriscoll** [comment]
This is related to this issue: 

https://github.com/PowerShell/PowerShell/issues/17119
https://github.com/PowerShell/PowerShell/issues/10983

The problem is that PowerShell is attempting to download the Certificate Revocation List from Microsoft and is timing out. 

This workaround reduces the timeout value to improve startup: 

https://github.com/PowerShell/PowerShell/issues/10983#issuecomment-779819256

This is the URL that is being accessed if it is possible to add the URL to an allow list. 

```
http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/disallowedcertstl.cab
```

**Comment by adamdriscoll** [comment]
This has been added to a KB article here: https://support.ironmansoftware.com/portal/en/kb/articles/kb0015-offline-psu-server-has-slow-dashboards
