### ISSUE TITLE
MSI Installer does not install to the specified path and instead installs to the last install path or default install location under ":\Program Files (x86)\Universal"

### ISSUE THREAD

**Issue by x86Since8088** [ironmansoftware/powershell-universal#1494]
### Steps to Reproduce

MSI Installer does not install to the specified path and instead installs to the last install path or default install location under ":\Program Files (x86)\Universal"

$InstallationTargetPath       = 'E:\Program Files (x86)\Universal'
...
            $PSWebSQL.Connection.ConnectionString
            [string[]]$ArgumentList= "/i ""$(split-path -leaf $MSIFile)"" "
                $ArgumentList+="INSTALLFOLDER=""$InstallationTargetPath"" "
                $ArgumentList+="DATABASETYPE=SQL "
                $ArgumentList+="CONNECTIONSTRING=""$ConnectionString"" "
                $ArgumentList+="STARTSERVICE=0 "
                $ArgumentList+="/norestart "
                $ArgumentList+="/qb "
                $ArgumentList+="/lv*! ""$InstallationLogPath"" "
            Start-Process -FilePath msiexec -ArgumentList $ArgumentList -PassThru

### Expected behavior

```console
Product should be installed to "E:\Program Files (x86)\Universal".
```

### Actual behavior

```console
Product is incorrectly installed to "C:\Program Files (x86)\Universal".
```

### Environment data

3.2.0 and prior

**Comment by adamdriscoll** [comment]
@x86Since8088 - Can you let me know if you have an $Env:UAPATH variable set?
