### ISSUE TITLE
PSScriptPad - Tool issues

### ISSUE THREAD

**Issue by ghost** [ironmansoftware/powershell-universal#15]
WPF designer.
Drag and drop components are a real challenge. 
They only drop center from, and cannot be moved. Unless the main form does not have a grid on it to start with.
This does not happen with the WinFrom designer.

Really disturbing.
The cursor does not stay in the console when entering commands. Constantly having to use the tab key to get back to anything.
**_The cursor is not visible because of a black cursor on a blue background._**

**Comment by adamdriscoll** [comment]
These issues have been resolved in the latest version.
