### ISSUE TITLE
VS2022 crashing when git diff window is closed.

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/powershell-universal#1506]
**Describe the bug**
I open a git diff windows by clicking the red arrow in the left margin.
When closing this window by click the "x", VS 2022 crashes - every time. And it also seems to happen in any powershell workspace.

I have noticed that VS2022 generally is crashing more often than earlier (fluffy statement, sorry).
Most of the time I see the problem when jumping to a function in the top drop-down menu. After selecting a function, I get the blue spinner and a crash. I have not been able to spot a way to reproduce.
Nor have I been able to spot any log files - do they exist?

**Screenshots**
The video attached shows the crash - sorry for the mouse cursor and spinner not visible.
But as soon as I click close - the blue spinner appears.

**Version**
2022.8.0

Microsoft Visual Studio Community 2022
Version 17.3.0
VisualStudio.17.Release/17.3.0+32804.467
Microsoft .NET Framework
Version 4.8.04084

https://user-images.githubusercontent.com/32414636/185951414-b68ef716-1518-4fa2-a166-3164461eb2c4.mp4

**Comment by adamdriscoll** [comment]
@pju55 - Crashes like this will usually be listed in event viewer as a .NET Application Exception or something and it should provide a stack trace of the exception.

**Comment by pju55** [comment]
Ok - thanks, good to know.
I have attached the 2 event dumps.

[NET Runtime 2022-08-22 16-53-14.txt](https://github.com/ironmansoftware/issues/files/9395796/NET.Runtime.2022-08-22.16-53-14.txt)
[Application Error 2022-08-22 16-53-15.txt](https://github.com/ironmansoftware/issues/files/9395797/Application.Error.2022-08-22.16-53-15.txt)

**Comment by adamdriscoll** [comment]
Thanks! Super helpful.
