### ISSUE TITLE
Unable to find package Microsoft.PowerShell.SDK

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1510]
## Describe the bug
Executables cannot be created with PowerShell 7.2.4 if the Microsoft.PowerShell.SDK is not also installed.

## To Reproduce
[✔] Have a Windows box with the prerequisites for PowerShell Pro Tools installed
[✔] Have PowerShell Pro Tools 8.0 installed
[✔] Do not have Microsoft.PowerShell.SDK installed (the nuget package)

Error messages:

```Unable to resolve ‘Microsoft.PowerShell.SDK (>= 7.2.4)’ for ‘net6.0’```

```error NU1101: Unable to find package Microsoft.PowerShell.SDK. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages```

## Expected behavior
Microsoft.PowerShell.SDK should not be required

## Screenshots
![image](https://user-images.githubusercontent.com/537287/186273383-ed504420-6e38-4d23-9162-7af51cbff87a.png)

## Version
PowerShell Pro Tools 8.0

## Additional context
![image](https://user-images.githubusercontent.com/537287/186273635-4cd5e670-ad0c-470a-bb78-d92c8691b504.png)

### Install the Microsoft.PowerShell.SDK per below

1. Download nuget.exe from Microsoft [here](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools)
2. Set the source with ```nuget sources Add -Name nuget.org.v3 -Source https://api.nuget.org/v3/index.json```
3. Install the package to a directory of your choice with ```nuget install Microsoft.PowerShell.SDK```

![image](https://user-images.githubusercontent.com/537287/186274051-ecb75979-afa6-47fa-80f4-61a44f47a791.png)

## Acknowledgements
Big thanks 🍻 to the forum member who was first to post the solution [here](https://forums.ironmansoftware.com/t/compiling-powershell-7-scripts-into-a-executable-in-vs-code/2855/23).

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/compiling-powershell-7-scripts-into-a-executable-in-vs-code/2855/27

**Comment by adamdriscoll** [comment]
We will now create a nuget.config file in the project directory to add the NuGet.org pacakge source.
