### ISSUE TITLE
Autocomplete crashes and buggy, can reproduce on multiple PSU servers.

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1512]
### Steps to Reproduce

Hi @adamdriscoll ,
I did find some buggs in Autocomplete

**Use this code:**
```
New-UDAutocomplete -id "txtName" -Icon (New-UDIcon -Icon 'User') -Label "Just some testing" -OnLoadOptions { 
    @('Test', 'Test2', 'Test3', 'Test4') | Where-Object { $_ -like "*$Body*" } | ConvertTo-Json
 }
```

**Bug1 - Crashes!**
I can't explain exactly how I make it crash but I type as you can see in the video Test and then I'm clicking on the "x" mark and clicking around on the background. Sometimes it crashes when I'm clicking "x" mark.

https://user-images.githubusercontent.com/76907327/186492886-376a4b63-a8f3-40cf-a7b2-2741a7dcb2fe.mov

**Bug 2 & 3 - GUI bug and you can't delete the text in the textbox with the "x" button on the right in the box.**
1. Write Test2
2. Select Test2 in the dropdown
3. Press the "x" at the right on the textbox
4. Klick anywhere in the form and you will end up with the picture below.
![Screenshot 2022-08-24 at 20 06 27](https://user-images.githubusercontent.com/76907327/186491931-13781b59-51ba-4f01-b583-c0601534256f.png)

**Bug 4**
The label in this case "Just some testing" is not above the textbox
![Screenshot 2022-08-24 at 20 06 03](https://user-images.githubusercontent.com/76907327/186491398-68ae0725-a9bb-45f7-9707-a4bed137d50e.png)

### Expected behavior

```console
No crashes, you can delete the text.
```

### Actual behavior

```console
Crashes, you can't delete the text from the box etc.
```

### Environment data

PSU 3.2.5

**Comment by rwidmark** [comment]
@adamdriscoll can you reproduce it?

**Comment by adamdriscoll** [comment]
I did. I noticed this yesterday in a dashboard I was creating.

**Comment by rwidmark** [comment]
@adamdriscoll make sure that you also take a look at #1519 and I did also today find out that if I press "x" mark it crashes also when the autocomplete textbox are empty. (don't know if its after you have written something and then erased it and then when it's empty press the "x" mark or if I did dit directly
