### ISSUE TITLE
Font Awesome icons are missing

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1513]
### Summary of the new feature / enhancement

Was looking in to Font Awesome 6.1.2 and it was my understanding that the free icons are bondled with PSU 3?
Many of the free icons are missing. please add them :)

**Comment by adamdriscoll** [comment]
Can you provide a couple examples of the missing ones?

**Comment by rwidmark** [comment]
> Can you provide a couple examples of the missing ones?

House, house-building, elevator.
I'm on the phone but that are ones that I do remember at the top of my head.

**Comment by rwidmark** [comment]
@adamdriscoll elevator is one that's missing for sure. I did just try it

**Comment by adamdriscoll** [comment]
Fixed! 

![image](https://user-images.githubusercontent.com/1256531/187048563-d7cdbfcd-6daa-4890-9e94-ae3a6e49ee14.png)

**Comment by rwidmark** [comment]
@adamdriscoll where can I search like you do in the pictures above? Is it in a new release?

**Comment by rwidmark** [comment]
@adamdriscoll  boxes-packing this are missing also can't find it anyway :)
