### ISSUE TITLE
How is the script output captured? PSFramework Logging line break annoyance (Technical detail info request/Fixing would be nice)

### ISSUE THREAD

**Issue by Callidus2000** [ironmansoftware/powershell-universal#1516]
Hi Adam,
I'm using PSFramework for many parts of my scripts and modules, especially the [logging framework](https://psframework.org/documentation/documents/psframework/logging.html). My only problem within Powershell Universal (3.2.5) is how the script output is parsed and presented within the admin console.

To demonstrate the problem I've created a litte demo script:
```Powershell
# It all starts with a single line of powershell code.
function Do-Nothing {
    [CmdletBinding()]
    param (
            $Message
        )
        Write-PSFMessage "This is verbose Message from function: $Message" -Level Verbose
        Write-PSFMessage "This is host Message from function: $Message" -Level Host


}
Write-PSFMessage "This is a verbose message" -Level Verbose
Write-PSFMessage "This is a host message" -Level Host
Do-Nothing -Message "NonVerbose Function Call"
Do-Nothing -Message "Verbose Function Call" -Verbose
$VerbosePreference="Continue"
Write-PSFMessage 'This is a verbose message after $VerbosePreference="Continue"' -Level Verbose
Write-PSFMessage 'This is a host message after $VerbosePreference="Continue"' -Level Host
```

If I execute it directly in the console (all PWSH (environment)) the logging looks fine like this:
```
[10:34:09][PSFLogging.ps1] This is a host message
[10:34:09][Do-Nothing] This is host Message from function: NonVerbose Function Call
VERBOSE: [10:34:09][Do-Nothing] This is verbose Message from function: Verbose Function Call
[10:34:09][Do-Nothing] This is host Message from function: Verbose Function Call
VERBOSE: [10:34:10][PSFLogging.ps1] This is a verbose message after $VerbosePreference="Continue"
[10:34:10][PSFLogging.ps1] This is a host message after $VerbosePreference="Continue"
```

Executing it from PSU results in multiple extra line breaks:
```
 [ 
 10:23:45 
 ][ 
 PSFLogging.ps1 
 ] This is a host message 
 
 
 [ 
 10:23:46 
 ][ 
 Do-Nothing 
 ] This is host Message from function: NonVerbose Function Call 
 
 
[verbose] [10:23:46][Do-Nothing] This is verbose Message from function: Verbose Function Call 
 [ 
 10:23:48 
 ][ 
 Do-Nothing 
 ] This is host Message from function: Verbose Function Call 
 
 
[verbose] [10:23:48][PSFLogging.ps1] This is a verbose message after $VerbosePreference="Continue" 
 [ 
 10:23:48 
 ][ 
 PSFLogging.ps1 
 ] This is a host message after $VerbosePreference="Continue" 
```

Curiously only the "-Level Host" messages have this problem, the `-Verbose` are logged fine.

I'd be very happy if you could fix this, but it would be also fine if you could give me some insight how PSU fetches this logging. With such info it would be possible to investigate a little bit further and maybe ask Fred for help (as it may be a configuration issue within his framework).

**Comment by adamdriscoll** [comment]
We have a custom PSHost that captures this output. For example:

```
        public override void Write(string value)
        {
            value = AnsiRegex.Replace(value, string.Empty);
            _protocol.Write(value);
        }
```

We might need to address extra new line characters being added but I'll have to futz around with it.

The other streams write out lines of text and I suspect that might be the difference.

```

        public override void WriteDebugLine(string message)
        {
            _protocol.WriteDebugLine(message);
        }

        public override void WriteErrorLine(string value)
        {
            _protocol.WriteErrorLine(value);
        }

        public override void WriteLine(string value)
        {
            value = AnsiRegex.Replace(value, string.Empty);
            _protocol.WriteLine(value);
        }

        public override void WriteProgress(long sourceId, ProgressRecord record)
        {
            _protocol.WriteProgress(sourceId, record);
        }

        public override void WriteVerboseLine(string message)
        {
            _protocol.WriteVerboseLine(message);
        }
```

**Comment by adamdriscoll** [comment]
Much better! 

![image](https://user-images.githubusercontent.com/1256531/189448163-7f7cf6aa-7e7d-4b26-ad6a-2aff8a0ec406.png)

**Comment by Callidus2000** [comment]
> Much better! 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/1256531/189448163-7f7cf6aa-7e7d-4b26-ad6a-2aff8a0ec406.png)
> 
> 

Wonderful, you're a genius!

Could you hint in which version the fix will be included?

Thx, Sascha aka callidud2000

**Comment by Callidus2000** [comment]
Ok, upgraded immediately to 3.3.0 after I've read about the release. Tried it myself, right, much better.
But not perfect ;-)

Could have seen it in your screenshot, damn little smartphone screens..

![image](https://user-images.githubusercontent.com/73584079/190126342-143bbc82-f1ff-47ab-82e7-0558d8970c67.png)

Irritating that the now missing line breaks appear in different sections in the screenshots...
