### ISSUE TITLE
Load components in to scripts

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1520]
### Summary of the new feature / enhancement

It would be great if it was possible in some easy way to load components in to a script so you can call for a function from the component.

Example:
In settings for each script you can choose what component that you want to load in to them.
In the scripts.ps1 you can have a -Components @("test1", "test2")

Or just a module that you can call for in the script file to load them would be perfect also :)

**Comment by adamdriscoll** [comment]
So, you'd like to specify a module to load into a particular script rather than configuring it for an environment?

**Comment by rwidmark** [comment]
> So, you'd like to specify a module to load into a particular script rather than configuring it for an environment? 

I'm talking about PSU components.
That are stored in the components folder

**Comment by rwidmark** [comment]
Any news to this?
It would be great if you could specify a component to be included  in the startup of a environment so you can use it in the dashboard but also for scripts etc.

I know that I can load modules in to the environment but this is more for psu adapted things

**Comment by rwidmark** [comment]
Closing this one as it's possible in psu 4
