### ISSUE TITLE
Custom Configuration Scripts

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1524]
### Summary of the new feature / enhancement

We keep adding more and more configuration scripts. For example: 

- Modules.ps1
- Vaults.ps1
- Repositories.ps1

We should consider adding some way to make this extensible. It would even be cool if we could add this to the UI and order the configuration scripts properly.

**Comment by rwidmark** [comment]
Nvm, missed that they was not released yet and that it's coming or is it already released?
