### ISSUE TITLE
New-UDTextBox ignores the MaxRows parameter

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1525]
### Steps to Reproduce

1. Create a multiline textbox with the MaxRows parameter set to 10
2. Confirm that more than 10 rows are allowed (see Visuals below for example)

```
New-UDDashboard -Title 'Issue #1525' -Content {
    New-UDTextbox -Id "txtTest" -Label "Maximum Rows 10" -Multiline -RowsMax 10 -Rows 15
}
```

Thanks to OP who reported this on the forum [here](https://forums.ironmansoftware.com/t/issue-with-udtextbox-multiline/7664)

### Expected behavior

```console
The UD textbox should be limited on the number of rows based on the MaxRows parameter
```

### Actual behavior

```console
The UD textbox is not limited on the number of rows based on the MaxRows parameter
```

### Environment data

PSU 3.2.5

###### below figure shows the example dashboard presented with 15 hand-typed rows of entered data
![image](https://user-images.githubusercontent.com/537287/187556004-cfa93204-651a-4bf1-8741-f0f549e1b629.png)

**Comment by DataTraveler1** [comment]
Extra note: The error still occurs without including a Rows parameter. The parameter was included to help the screenshot more clear.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/issue-with-udtextbox-multiline/7664/5
