### ISSUE TITLE
When running a Invoke-PSUScript command the target script has no calling parameters and errors.

### ISSUE THREAD

**Issue by Dods80** [ironmansoftware/powershell-universal#1528]
### Steps to Reproduce

Create a Test Script as follows:

param(
    [string] $Sites
)

switch ($sites) {
    "Hello" { "Hello" }
}

Then try to invoke the script from the Dashboard and you will see there is no Sites dialog field to pass the value.
I applied this a fix below as a workaround to the problem:

param(
    [string] $Sites
)
if ($true) {
    switch ($sites) {
        "Hello" { "Hello" }
    }
}

It dosn't seem to like the switch statement as a top level line of code with the parsed parameter variable. 

### Expected behavior

```console
Hello
```

### Actual behavior

```console
Errors with invalid parameter.
```

### Environment data

Powershell Universal 2.12.2

**Comment by adamdriscoll** [comment]
This is not reproducible on 3.7.6.
