### ISSUE TITLE
UDStepper, move buttons to module footer

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1533]
### Summary of the new feature / enhancement

Hi,
It's irritating when you have a udstepper that are larger and you need to scroll to the bottom to click on the buttons.
That's why it would be nice if you could move the buttons to the footer for a UDModal.
Or if that's not possible, make it possible to interact with the buttons from an other button.
For example, you have two buttons in the footer when you click on one of them it also "clicks" on one of the buttons for the UDStepper.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/udstepper-move-the-buttons-to-the-footer/7692/4

**Comment by rwidmark** [comment]
@adamdriscoll this is a old one, but it would be great if it was possible to either hide the standard buttons for the UDStepper and call the action from other buttons or just move the buttons to the footer of the UDModal.

Maybe do a modal of the hole UDStepper or something like that

**Comment by rwidmark** [comment]
@adamdriscoll  One other options is if it was possible to hide the standard buttons for UDStepper and then call the functions from that buttons with an other button that you have created by your self.
