### ISSUE TITLE
Set-PSULicense should support proxy options

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1537]
### Summary of the new feature / enhancement

In order to reach the activation server, Set-PSULicense may require a proxy

![image](https://user-images.githubusercontent.com/537287/188879697-f26d7afe-4258-4961-aa53-d66e4f740739.png)

* this issue was originally reported internally

### Proposed technical implementation details (optional)

The ideal implementation would mimic the current version of Invoke-WebRequest with these 4 parameters

```
-NoProxy
-Proxy
-ProxyCredential
-ProxyUseDefaultCredentials
```

**Comment by adamdriscoll** [comment]
@DataTraveler1 - I realize now that we have these settings in the Set-PSUSettings command. It would be a two step process for calling Set-PSUSettings -ProxyUri\-ProxyCredential and then calling Set-PSULicense
