### ISSUE TITLE
Support for PowerShell 7 Preview versions

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1540]
## Is your feature request related to a problem? Please describe.
There is no problem, there is just a desire to be able to use the latest PowerShell technology

## Describe the solution you'd like
The ability to utilize PowerShell 7 Preview versions with PowerShell Pro Tools

## Describe alternatives you've considered
None

## Additional context
```Preview builds remain in-place as pwsh-preview instead of pwsh under the 7-preview directory```

https://docs.microsoft.com/en-us/powershell/scripting/whats-new/What-s-New-in-PowerShell-70?view=powershell-7.3

**Comment by adamdriscoll** [comment]
I just checked and we already support the preview versions. 

Visual Studio

<img width="231" alt="image" src="https://user-images.githubusercontent.com/1256531/191049124-51eb2782-9050-411d-a910-5eca799e003d.png">

PSScriptPad

<img width="253" alt="image" src="https://user-images.githubusercontent.com/1256531/191049425-20fd66fb-8641-4e1c-90df-459c472288d4.png">

**Comment by DataTraveler1** [comment]
@adamdriscoll - This issue seems to have returned with the 7.4.x PowerShell Preview

**Comment by adamdriscoll** [comment]
I just checked and this appears to be working.
