### ISSUE TITLE
Integrate Custom Themes

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1541]
### Summary of the new feature / enhancement

https://github.com/potatoqualitee/psu-themes

**Comment by adamdriscoll** [comment]
@potatoqualitee I wanted to highlight some implementation details here since I made some tweaks to PSU to integrate your themes. 

## Themes now support CSS directly 

This was to remove the need to have a separate CSS file. You can now just supply a CSS string and it will be applied globally. I'm reading the theme.css from your repo when the module is loaded and just passing that along with the themes. 

## Get-UDTheme

Your themes are now directly part of Get-UDTheme. I tweaked a bunch of the functions that you have to read the JSON files and return them directly from Get-UDTheme. 

## Theme Endpoints 

There are now theme endpoints. Under the covers, this just calls Get-UDTheme but it also means we will be able to integrate that into the admin console. 

- /api/v1/dashboard/theme/{name} - Get a theme
- /api/v1/dashboard/theme - List all the themes

I will be adding PUT, POST, DELETE endpoints in 3.4 along with hopefully the first version of the GUI to modify themes.

**Question** Do you want me to merge any of these changes back into your themes repo? Your repo is totally still compatible with v3.3 so there really isn't an need to change it.

**Comment by potatoqualitee** [comment]
That sounds fantastic! No need to get it back into my repo. My repo was primarily intended to deliver the themes to you, however you wished to implement them 💕
