### ISSUE TITLE
Add support for Git SSH keys

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1542]
### Summary of the new feature / enhancement

Please add support for SSH keys with Git

Note: this was an internal request 🍮

### Proposed technical implementation details (optional)

Additional Information about SSH keys with Github

https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/git-hosted-services/git-auth-ssh-keys.md

**Comment by adamdriscoll** [comment]
Support for external git clients was added and this will now work. You can configure SSH keys and use the SSH URL when configuring external git support.
