### ISSUE TITLE
Built-In Variables With users current dashboard

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1544]
### Summary of the new feature / enhancement

It would be perfect if it was a Built-In Variables that has the current dashboard that the user are using as a value. It would be perfect for logging as the logs are getting more dynamic :)

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/built-in-variables-show-what-dashboard-you-have-accessed/7748/2
