### ISSUE TITLE
Universal.Server process memory usage balloons when a dashboard script tab is left open in VS Code using the PSU extension

### ISSUE THREAD

**Issue by shadowrun78** [ironmansoftware/powershell-universal#1551]
### Steps to Reproduce

I have the PSU extension in VS Code.  I open a dashboard script to work on a dashboard.  If I leave the tab open in VS Code, the Universal.Server process Memory usage will continue to increase and the service/process will become unresponsive. 

VS Code is running on my desktop and connected to the server via the PSU extension. 

### Expected behavior

```console
Universal.Server process to not balloon to 80/90% of memory usage.
```

### Actual behavior

```console
Universal.Server process memory usage increases overtime eventually reaching 80% to 90% memory usage and becomes either slow or unresponsive.
```

### Environment data

**PowerShell Universal:**
v3.2.8 (2943651430)
Default Environment: Integrated
API Environment: Powershell 7.2.6
Security Environment: Powershell 7.2.6

**Server OS:**
Windows Server 2019 Std
Version 1809

**Server VM Specs**
2 vCPU
8 GB RAM

**VS Code on Desktop:**
Version: 1.71.0 (user setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19043
Sandboxed: No
**settings.json for PSU Extension**
`{
    "workbench.colorTheme": "Default Dark+",
    "files.autoSave": "afterDelay",
    "powerShellUniversal.url": "",
    "powerShellUniversal.connections": [
        {
            "name": "Server",
            "url": "https://server",
            "appToken": "APITOKEN"
        }    
    ],
    "powerShellUniversal.samplesDirectory": "C:\\Users\\userID\\AppData\\Roaming",
    "powershell.helpCompletion": "LineComment",
    "powerShellUniversal.appToken": ""
}`

**Comment by adamdriscoll** [comment]
This was the result of file.autoSave = afterDelay saving the file in the background. The problem is that every time this happened, it would leak a runspace in PowerShell Universal. We've identified and fixed the leaked runspace so this won't happen any more.
