### ISSUE TITLE
PSU 3.3.0 slow when clicking buttons etc.

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1554]
### Steps to Reproduce

It's much slower to run the actions when you push the buttons then 3.2.8.
The buttons in the dashboard, when you click the button it takes 1-3 sekonds for it to react and that's kind of bad and the users are complaining.
@adamdriscoll  this issue was also in a release for some time ago.

### Expected behavior

```console
Same speed as 3.2.8 when clicking on buttons
```

### Actual behavior

```console
The time when you click on the button and the actions are starting is slow.
```

### Environment data

3.3.0 , win 2022, PowerShell 7.2.6

**Comment by rwidmark** [comment]
It seem that when you have started the dashboard and click a button it takes time the first time you click that button, after that it go fast for that user / session if you logout and then in again or access the dashboard with a other user it's the same again it's slow when clicking the button for the first time.

Same for -onenter for textboxes when they interact with buttons.

It's so slow so I need to revert back to psi 3.2.8 again.

@adamdriscoll

**Comment by rwidmark** [comment]
@adamdriscoll reverted back to 3.2.8 on our production machines and the same code works without any slowness there.

**Comment by adamdriscoll** [comment]
I may need some help reproducing this one. I'm not seeing it happening in my lab or on the demo site. 

https://demo.powershelluniversal.com/dashboard/Inputs

**Comment by rwidmark** [comment]
> I may need some help reproducing this one. I'm not seeing it happening in my lab or on the demo site.
> 
> https://demo.powershelluniversal.com/dashboard/Inputs

I'll try to isolate it a bit more if I can't do that I'll create a support case to you and attache the code etc.
Was in the middle of the night when I was working and it was not just me many of the other was complaining also but I sill have our testing env In 3.3.0 so I'll get back :)

**Comment by rwidmark** [comment]
@adamdriscoll 
When I exactly has started PSU and when I’m first clicking the button or hitting enter to activate -OnEnter it take a very long time for it to react.

This issue also appears if I restart the Dashboard inside PSU admin. It’s not exactly as slow as when I exactly has started the PSU Service but still it’s slow and the users are getting irritated about it.

Then after that it works great until something happens and it goes slow again. My guess is that it’s changing session or similar.

I don’t have the time to share my code as I need to censor it but the pseudocode is like this.
1. Enter the name of the ADComputer in textbox
2. When hitting enter or button it will check if the adcomputer exists then it will sync a UDElement that will reload some information and call some functions that I have in the components that will return some information etc.

The slowness is exactly when I’m hitting enter / button then it starts the UDelement don’t event start to reload it takes a long time for it to start loading.

Same code on 3.2.8 works perfect.

I can email you the code + movie to display it but I can’t remember how I open a case? can you provide me with a link or similar?

**Comment by rwidmark** [comment]
So... now I can't reproduce it. I could do that for like 5 times then when I was going to record I could not reproduce it strange.
I'll take a look at it tomorrow again as I'm sure it can't repair it self.

**Comment by rwidmark** [comment]
I'm still facing this issue from time to time but I can't reproduce it on purpose. I'll investigate it some more

**Comment by adamdriscoll** [comment]
Closing this issue as stale. If you are still having this problem with recent versions, please let me know and I will reopen it.

**Comment by rwidmark** [comment]
@adamdriscoll  sorry for the delay, I have been working with other things this past months sorry.
But the issue was not at PSU well it did change something that did not like my code :) But I can't blaim PSU for it as I did cheat in my code ;)
