### ISSUE TITLE
$Page: Variable Scope for Dashboards

### ISSUE THREAD

**Issue by JoriPS1** [ironmansoftware/powershell-universal#1555]
### Summary of the new feature / enhancement

https://forums.ironmansoftware.com/t/variables-new-uddynamic-and-environments/7744/3

Currently if a dashboard is running in a persistent environment and multiple instances of the same page open, variables set by New-UDDynamic can cause unpredictable behaviors in these pages due to variables not being containable to just the page.

A new variable scope which is limited to a page "instance" should solve this.   Possibly even cleareing when the page is closed.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/variables-state/8169/7

**Comment by Omzig** [comment]
@adamdriscoll, we kind of really need this one, how do we bump it to the top?

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/variables-new-uddynamic-and-environments/7744/5
