### ISSUE TITLE
API Testing Area

### ISSUE THREAD

**Issue by JoriPS1** [ironmansoftware/powershell-universal#1566]
### Summary of the new feature / enhancement

It would be cool to have an area in the Info tab to test an API.

I'm imagining a section that builds a form from any variables in the URL, or a paramblock. When submitted, Universal would build the URL and body.  It could even allow for different roles to be simulated.

**Comment by adamdriscoll** [comment]
I like this idea. Kinda like a built in postman.

**Comment by JoriPS1** [comment]
> I like this idea. Kinda like a built in postman.

Had to look Postman up, but yeah, very similar to it.

Something else I thought about that would be directly related would be some sort of feature to enable an 'API Debug'.

When enabled, the API would automatically save any passed variable sets, and any returned response.  These variable sets could then in turn be used with this feature.

A stretch goal for this would also be having some sort of built in Pester Test builder.

**Comment by Viajaz** [comment]
The ability to impersonate identities for said feature would be useful.

**Comment by Omzig** [comment]
right now we are using pester for this, but it is outside the framework and we forget to run it sometimes
