### ISSUE TITLE
PSScriptPad - Ability to define tab spaces

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1567]
## Is your feature request related to a problem? Please describe.
Yes, the inability to redefine the tab characteristics can reduce usability

## Describe the solution you'd like
The ability to redefine a tab as something different from 4 spaces

## Describe alternatives you've considered
Manually indent files to preference

## Additional context
https://stackoverflow.com/questions/1878974/redefine-tab-as-4-spaces

internally requested 🍮

**Comment by erpomik** [comment]
Two options might be relevant.
1. The ability to save files using TAB characters or not.
2. The ability to select TAB size or indent size, _if_ using TAB characters.
