### ISSUE TITLE
Outlined variant for New-UDSelect

### ISSUE THREAD

**Issue by ad-85** [ironmansoftware/powershell-universal#1568]
### Summary of the new feature / enhancement

Pretty much what it says in the title! It would be nice to have an `outlined` variant for New-UDSelect that would look similar to the one for New-UDTextbox.

**Comment by adamdriscoll** [comment]
It looks like this is already supported in 3.3. 

```
New-UDSelect -Label 'Select' -Id 'select' -Variant 'outlined' -Icon (New-UDIcon -Icon Users) -Option {
        New-UDSelectOption -Name "One" -Value 1 -Icon (New-UDIcon -Icon Home)
        New-UDSelectOption -Name "Two" -Value 2
        New-UDSelectOption -Name "Three" -Value 3 -Icon (New-UDIcon -Icon Book)
    }
```

![image](https://user-images.githubusercontent.com/1256531/194567076-9df63519-ed0c-4521-9c5e-a3903106e392.png)
