### ISSUE TITLE
Translation strings not applied when used for page names (New-UDPage -Name)

### ISSUE THREAD

**Issue by ad-85** [ironmansoftware/powershell-universal#1572]
### Steps to Reproduce

When calling a translation string to use as the page title, e.g. `New-UDPage -Name $T:Homepage_Title`, the page will always load with the en-US (default) language. Other strings will load with the string that respects the browser headers.

### Expected behavior

```console
Page title and navigation bar should retrieve the name based on the lang.ps1 files in the translations page.
```

### Actual behavior

```console
Page title and navigation bar always display in English.
```

### Environment data

Version: 3.3.1
_Note: This is in a dashboard that is calling external .ps1 files via dot-sourcing._

**Comment by adamdriscoll** [comment]
Based on how dashboards load the first time, the locale data is not available for New-UDPage at this level. To work around it, we've added a -LoadTitle parameter that allows you to load the title string dynamically. You can also use -LoadNavigation to load the navigation dynamically and provide translation strings. 

```
New-UDDashboard -Title 'PowerShell Universal' -Pages @(
   New-UDPage -Content {
      $t:String1
   } -HeaderContent {
      New-UDTypography $t:String1
   } -LoadTitle {
      $t:String1
   } -Name 'Name'
)
```
