### ISSUE TITLE
Manual Commit Mode for Git Sync

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1574]
### Summary of the new feature / enhancement

After working with git sync in my lab I find it weird that it just does all these commits in the background. I'd like to make it work more like gitbook. How their system works is that you click Edit and then can make changes in a bunch of places, and then you save it. Then it commits it. 

With the current system, you may need to make changes in multiple locations before you're actually done and it might be committing half complete changes. It also really makes the git history messy and hard to track because all the comments are the same. 

What I envision is that we have a new mode for git sync where it doesn't commit and push automatically. Instead, there is a button at the top of the admin console to start Editing. It will save all the changes but not actually do a commit. Once you're done editing, you can click Save Changes button, put in a comment, then we commit and push. 

While editing, git sync should be disabled because we will have uncommitted changes locally. We should probably disable all editing buttons when not in edit mode.

**Comment by mabster** [comment]
Hey Adam! What's the appsettings.json setting for manual mode? Gonna update to 3.4.1 and switch to manual mode to see if Git sync is the source of our memory leak.

**Comment by adamdriscoll** [comment]
@mabster - It looks like this wasn't actually added to appsettings.json. I will make sure that happens in 3.4.3
