### ISSUE TITLE
Invoke-DbaQuery not working

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1575]
### Steps to Reproduce

https://forums.ironmansoftware.com/t/psu-3-3-0-nightly-invoke-dbaquery-not-working-anymore/7730

### Expected behavior

```console
Invoke-DbaQuery works
```

### Actual behavior

```console
Invoke-DbaQuery throws an error
```

### Environment data

3.3.3

**Comment by adamdriscoll** [comment]
dbatools uses an older version of Microsoft.Data.SqlClient and will no longer load into the integrated environment. The work around is to use a non-integrated environment.

**Comment by potatoqualitee** [comment]
:O what version do we need to upgrade to?

**Comment by adamdriscoll** [comment]
@potatoqualitee - We are using version 5 - https://www.nuget.org/packages/Microsoft.Data.SqlClient/#versions-body-tab

**Comment by potatoqualitee** [comment]
thank you, ill try to get to this next week 👍🏼

**Comment by potatoqualitee** [comment]
@adamdriscoll -- man, I cannot get this to work. I'm not good at DLLs, can you offer any advice?

* To get to Microsoft.Data.SqlClient 5.0, I have to I have to find a version of SMO that supports it
* Sweet! The newest prerelease of SMO does. I ❤️ a prerelease if all of our tests pass.
* So I update to [SMO 170.7.0-preview](https://www.nuget.org/packages/Microsoft.SqlServer.SqlManagementObjects/170.7.0-preview) which depends on [Microsoft.Data.SqlClient 5.0](https://www.nuget.org/packages/Microsoft.Data.SqlClient) and works on .NET 6.0.
* Awesome, I can update the whole library to net6.0 on the Core side

I always start with 5.1 so I get that working (it was hell and [I had to do some crazy stuff I never had to do before](https://github.com/microsoft/sqlmanagementobjects/issues/114#issuecomment-1277205841)) and I move on to Core.

Everything compiles just fine but when I go to connect to SQL Server, I get Microsoft.Data.SqlClient platform not supported. What? So then I look at the nuget page and it says Microsoft.Data.SqlClient works on netcoreapp3.1 and doesn't list net6.0 as supported! How on earth can SMO depend on something that can't run on that version of .net? Is there hope?

**Comment by potatoqualitee** [comment]
Solved it 😮‍💨 

https://github.com/microsoft/sqlmanagementobjects/issues/114#issuecomment-1280832722

**Comment by adamdriscoll** [comment]
@potatoqualitee Wooooo! Glad you got it working. Sorry I didn't get to your comment this weekend!
