### ISSUE TITLE
Store license details and status in db

### ISSUE THREAD

**Issue by mojoaar** [ironmansoftware/powershell-universal#1576]
### Summary of the new feature / enhancement

At the moment you need to apply the PSU license to each "node" you deploy. So 6 nodes = 6 places to apply the license.

### Proposed technical implementation details (optional)

It would be beneficial if the license details and status was stored in the db and when you add new nodes they would pick it up from the db.

**Comment by potatoqualitee** [comment]
Yesssssssssss, I imagine this would also help an issue I have with having to re-register the license after upgrading.
