### ISSUE TITLE
Forms Field Disappearing Issue

### ISSUE THREAD

**Issue by clavrus** [ironmansoftware/powershell-universal#1583]
### Steps to Reproduce

I am having an issue when creating pages using the built-in page editor. As I make changes to certain areas in a table, other settings disappear.

- Create Page
- Select Toolbox
- Data Input
- +Form
- Add any # of fields you wish + required fields such as title/description/etc.
Change validation API script or Target and it will wipe out your fields.
Change fields and target will be cleared

Note: Happens majority of time, not all the time

### Expected behavior

```console
Change General/Validation API or Target/Type or Target/Script
Fields and other settings should remain
```

### Actual behavior

```console
Change General/Validation API or Target/Type or Target/Script
Fields disappear
```

### Environment data

Version: 2.12.5
IIS
Server 2022 Standard

### Visuals
Before
![image](https://user-images.githubusercontent.com/36702449/191616511-20c3e039-b565-481a-9891-c05f8ba01946.png)
Add target
![image](https://user-images.githubusercontent.com/36702449/191616677-117122ca-443c-4fef-9e1d-1d6bec2da880.png)
Fields wiped out
![image](https://user-images.githubusercontent.com/36702449/191616696-5776d3d5-c6a2-4406-ab76-61111bf64c89.png)
Add text field
![image](https://user-images.githubusercontent.com/36702449/191616766-82df8820-6e9f-4b9a-b8ba-46fc82776e4e.png)
Target wiped out
![image](https://user-images.githubusercontent.com/36702449/191616846-d30c9473-7838-4ced-b540-3ba3331e91b9.png)

**Comment by adamdriscoll** [comment]
We're replacing this functionality in v5 and will no longer be a problem.
