### ISSUE TITLE
Code Editor: Format Document does not work

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#1585]
### Steps to Reproduce

The Format Document command in the Code Editor does not work anymore. It used to work on one of the first releases where this was integrated (don't remember the version anymore though). 

### Expected behavior

```console
The document should nicely format
```

### Actual behavior

```console
The document doesn't format.
You have to use VSCode to workaround it.
```

### Environment data

3.3.0

### Visuals

![image](https://user-images.githubusercontent.com/11975745/191694406-0d357c8a-5afd-434a-9c11-135a268e022d.png)

**Comment by adamdriscoll** [comment]
Do you have PSScriptAnalyzer installed on the machine?

**Comment by donlent** [comment]
Hey Adam!

No I don't. Why is that a prerequisite?

Kind regards
Don

**Comment by adamdriscoll** [comment]
We use the Invoke-Formatter cmdlet to do the formatting. I'd be open to installing PSScriptAnalyzer along with PSU.

**Comment by donlent** [comment]
Ah ok didn't know that...
Ok will test it tomorrow and let you know if it will fix the issue. Yes, I think installing it during psu main installation could do the trick... 🤗 or allow to choose to do so as optional component?

**Comment by donlent** [comment]
Hey Adam
I can confirm that it works with PSScriptAnalyzer installed! 👍 
I'll therefore go ahead and close this one. Now it's up to you if you want to integrate it into the prereqs or not... ;-)
Thanks for your help!
Best regards,
Don
