### ISSUE TITLE
Custom Component: Add react-fullscreen support

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#1589]
### Summary of the new feature / enhancement

React support's the possibility to put media content like pictures, videos and other stuff  in full screen mode.

It would be great if we could leverage this function to create presentation dashboards that put content into full screen mode.

Example website that uses that:
https://megaman.pomle.com

=> Have fun while gaming Megaman 2!!  :-D

### Proposed technical implementation details (optional)

There's an opensource project for that which could be converted into a custom component pretty easy I think... :-)
https://github.com/snakesilk/react-fullscreen#readme

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/custom-component-add-react-fullscreen-support/7829/1

**Comment by psDevUK** [comment]
I got a working demo version, I will look at this more tomorrow, to add a CONTENT parameter script block, then hopefully this should all work

**Comment by psDevUK** [comment]
I have now got this component fully working so feel this could now be solved as this component is now published

**Comment by adamdriscoll** [comment]
@psDevUK You're a rockstar! Thanks for contributing this! I'll close this out and mark it as resolved!
