### ISSUE TITLE
Complete uninstall instructions (or app) for all versions of PSU for Windows

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1591]
### Summary of the new feature / enhancement

It would be ideal if there was a tool or detailed documentation which would completely remove all traces of PSU. This should include all versions of PSU for Windows (e.g. PSU Desktop). The PSU Removal app should be updated and tested with each release of PSU since the tool probably could not be forwards-compatible.

Implementation of this request could ease troubleshooting any installation/uninstallation issues as the MSI mechanism itself cannot always be relied on.

## Examples

1. Microsoft's Office Removal Tool at https://support.microsoft.com/en-us/office/about-the-microsoft-support-and-recovery-assistant-e90bb691-c2a7-4697-a94f-88836856c72f
2. Broadcom's CleanWipe at https://knowledge.broadcom.com/external/article/178870/download-the-cleanwipe-removal-tool-to-u.html

**Comment by adamdriscoll** [comment]
I'd be open to a document rather than having to produce a tool since there isn't much we install. I'll put one together and maybe we could additionally provide a PowerShell script to do so.

**Comment by adamdriscoll** [comment]
This can now be found here: https://docs.powershelluniversal.com/getting-started/uninstall
