### ISSUE TITLE
If a script cannot be found in .universal\scripts.ps1 PSU doesnt load correctly

### ISSUE THREAD

**Issue by i-windows** [ironmansoftware/powershell-universal#1597]
### Steps to Reproduce

if a script cannot be found on the disk which is listed in scripts.ps1 then PSU doesnt load correctly, schedules and jobs fail to load

### Expected behavior

```console
if a script is not found on disk then skip it in the config and move on.
```

### Actual behavior

```console
PSU borks and fails to load other components
```

### Environment data

3.3.4

**Comment by adamdriscoll** [comment]
This will actually improve all configuration scripts. Non-terminating errors, like the issue with scripts, won't cause the entire configuration script to fail.
