### ISSUE TITLE
JiraPS - Not loading correctly

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#1602]
### Steps to Reproduce

When trying to import the JiraPS module in PSU, it fails with an exception.
If executed manually as the service account user on the PSU server, it imports just fine - so the issue is narrowed down to PSU.

`Get-module JiraPS -ListAvailable`
`Import-Module JiraPS -ErrorAction Stop`

Sep 30, 2022 9:19 AM      Directory: C:\Program Files\PowerShell\Modules 
Sep 30, 2022 9:19 AM  ModuleType Version    PreRelease Name                                PSEdition 
Sep 30, 2022 9:19 AM  ---------- -------    ---------- ----                                --------- 
Sep 30, 2022 9:19 AM  Script     2.14.6                JiraPS                              Desk      
Sep 30, 2022 9:19 AM [error] The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Uri".

### Expected behavior

```console
I expected JiraPS to be imported, since its installed on the server.
```

### Actual behavior

```console
Sep 30, 2022 9:19 AM      Directory: C:\Program Files\PowerShell\Modules 
Sep 30, 2022 9:19 AM  ModuleType Version    PreRelease Name                                PSEdition 
Sep 30, 2022 9:19 AM  ---------- -------    ---------- ----                                --------- 
Sep 30, 2022 9:19 AM  Script     2.14.6                JiraPS                              Desk      
Sep 30, 2022 9:19 AM [error] The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot convert the "System.Object[]" value of type "System.Object[]" to type "System.Uri".
```

### Environment data

PSU: 2.12.2
OS: Windows Server 2019 - 17763.3406

**Comment by adamdriscoll** [comment]
This looks to be resolved in PSU v4.2 and JiraPS 2.14.7
