### ISSUE TITLE
License activation failure should not disable all authentication features

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1604]
### Summary of the new feature / enhancement

We should consider locking down PSU completely when a license fails to activate rather than disabling security features when a license fails to activate.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/upgrading-broke-the-installed-online-license-key/7880/2

**Comment by Viajaz** [comment]
As it stands, it could be said that any method to induce a license failure can lead to a CWE-862, or maybe CWE-306, vulnerability.
