### ISSUE TITLE
Change documentation page "Pages"

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1610]
### Summary of the new feature / enhancement

In this link in the documentation it saying that the user should use +=
https://docs.powershelluniversal.com/userinterfaces/dashboards/components/pages

I don't agree as you know += will rewrite the hole array and then in the end add the new page.
Instead you should change it to;

```
New-UDDashboard -Title 'Pages' -Pages @(
New-UDPage -Name 'Dashboard One' -Content {
    New-UDTypography -Text 'Dashboard Two'
}
New-UDPage -Name 'Dashboard Two' -Content {
    New-UDTypography -Text 'Dashboard Two'
}
)
​
```

It seem that the documentation might be old. But still it should be changed so the new users will get a proper experience I don't know how much faster it is but well you know :)

**Comment by augiaugi** [comment]
Just saw this issue and was thinking about the main problem. I am just aware of performance using `+=`, but this should not be a problem in this example.
Can you please explain me the reason for this issue in depth? Kr :)

**Comment by JoriPS1** [comment]
I think this comes down to readability vs performance.

On my most complex dashboard, using += results in 1.7 second worth of loading, vs 33ms when using measure-command.  I think both are worth mentioning, but in the end I think "$pages +=" makes it a bit more readable and understandable.  It's all really dependent on the reader's comfort level with arrays.

**Comment by augiaugi** [comment]
@JoriPS1 totally agree 👍

**Comment by rwidmark** [comment]
Can't shake this of, I still think it's wrong.
Check this out.

https://theposhwolf.com/howtos/PS-Plus-Equals-Dangers/?fbclid=IwAR1cALbzce5mZBH1I5N8Y8hrDUSs8hWuhTbMaf90bP-s5i_0F5KZMfpuYLY

**Comment by augiaugi** [comment]
@rstolpe whats wrong?

it is a performance decrease writing code with += but its always a matter of awareness. If +50ms has no impact on you project and anything is working, go for it. Because maybe it has other benefits like readability, simplification, ...

**Comment by adamdriscoll** [comment]
This is a very, very minor performance impact. Not going to worry about it.
