### ISSUE TITLE
UDCard: Ability to specify an Icon next to the Title

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#1616]
### Summary of the new feature / enhancement

It would be cool if it was possible to specify an Icon next to the Title of the UDCard.
I think it would be an additional neat touch :-)

### Proposed technical implementation details (optional)

New-UDCard -Title "Active Directory" -Icon { New-UDIcon -Icon user -Size lg -Style @{ color = '#66ccff' } } -IconPosition BeforeTitle | AfterTitle

**Comment by adamdriscoll** [comment]
We've added -Avatar to New-UDCard and New-UDCardHeader to be able to specify an icon for the card. This the nomenclature that MUI uses.
