### ISSUE TITLE
Git Sync not working since 3.3.7 (Proxy)

### ISSUE THREAD

**Issue by eizedev** [ironmansoftware/powershell-universal#1621]
### Steps to Reproduce

Hi adam,

since 3.3.7 we can no longer use git sync while the http proxy is set in the configuration. 

reproduce: configure an http proxy in the Universal config and do not allow to access the git server through this proxy.

Since since 3.3.7 git requests now also use the in universal configured proxy, this no longer works for us. Since our Gitlab server is internal and not accessible via proxy. Can we include a NO_PROXY configuration that then similar to the NO_PROXY environment variable ([NO_PROXY HttpClient](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.defaultproxy?view=net-6.0)) for certain names in the list does not use the proxy?
Perhaps the integrated git library could also support this?

### Expected behavior

```console
It should be possible to maintain an exception list for systems that should not be accessed via the proxy.
```

### Actual behavior

```console
If git server cannot be contacted through the configured proxy server, git sync is not posssible anymore
```

### Environment data

Universal 3.3.7 (Windows)

**Comment by eizedev** [comment]
LibGit2 in general supports NO_PROXY - https://github.com/libgit2/libgit2/pull/5796

**Comment by adamdriscoll** [comment]
@eizedev What would be your preferred method for configuring this? 

- NO_PROXY environment variable support
- PowerShell Universal setting - Something like -NoGitProxy 
- Something else?

**Comment by eizedev** [comment]
> @eizedev What would be your preferred method for configuring this?
> 
> * NO_PROXY environment variable support
> * PowerShell Universal setting - Something like -NoGitProxy
> * Something else?

Hi @adamdriscoll 
For us, adjusting the NO_PROXY setting would be more appropriate as a Universal Setting.

**Comment by eizedev** [comment]
@adamdriscoll 
Either the use of the NO_PROXY environment variable or a custom NO_PROXY (list of hosts where the proxy will not be used) configuration within Universal. The `-NoGitProxy` configuration sounds good but we like to be flexible

**Comment by adamdriscoll** [comment]
We are going to switch the libgit2 proxy mode to auto rather than none by default. This will allow you to specify the NO_PROXY, http_proxy and https_proxy environment variables.

**Comment by eizedev** [comment]
thanks @adamdriscoll, i will test it in the new release
