### ISSUE TITLE
Connect-ExchangeOnline

### ISSUE THREAD

**Issue by alexsmid** [ironmansoftware/powershell-universal#1623]
### Steps to Reproduce

Running Connect-ExchangeOnline will give the error
`Cannot bind argument to parameter 'Path' because it is null.`
4 times, 2 before the connect, and 2 after.

After these errors all other commands work.

### Expected behavior

```console
Connect-ExchangeOnline
No errors
```

### Actual behavior

```console
Connect-ExchangeOnline
Cannot bind argument to parameter 'Path' because it is null.
```

### Environment data

Product: PowerShell Universal - Kestrel
Version: 3.3.6
Powershell Version: 7.2.6
ExchangeOnlineManagement Version: 3.0.0

**Comment by alexsmid** [comment]
https://forums.ironmansoftware.com/t/connect-exchangeonline/7919/5

**Comment by adamdriscoll** [comment]
Is this still an issue? You can disable error toasts via the admin console if it works but just shows an error message.

**Comment by alexsmid** [comment]
It still gives errors:
![image](https://user-images.githubusercontent.com/37578975/214084370-b20d9622-a14f-4c5a-b446-95e9bc0a48c2.png)
![image](https://user-images.githubusercontent.com/37578975/214084541-b825c7c0-77af-4f47-8039-71a31d683fc3.png)

Wouldn't this also hide all other error toasts?
