### ISSUE TITLE
MSI installer does not "keep" already configured port

### ISSUE THREAD

**Issue by mojoaar** [ironmansoftware/powershell-universal#1628]
### Summary of the new feature / enhancement

When you want to deploy/update a new msi version, the installer defaults to using port 5000 instead of using the already configured port (80/443).
![psu_port](https://user-images.githubusercontent.com/21560785/195257636-5c3476b6-1b78-48ae-9875-581fd443f1de.png)

### Proposed technical implementation details (optional)

Installer looks at already configured port and drop it in the msi installer (if possible?).

**Comment by mojoaar** [comment]
...same goes for sql connection details.

**Comment by adamdriscoll** [comment]
@mojoaar Are you doing an uninstall\install or is this an upgrade?

**Comment by mojoaar** [comment]
@adamdriscoll This was an upgrade from 3.3.5 to 3.4.0 - tested on 2 nodes, same experience.

My colleague tried the same and he got the current values (maybe because he installed it?). Are the settings stored in a user and not system context or something?

**Comment by adamdriscoll** [comment]
They are stored in the C:\ProgramData\PowerShellUniversal folder. I do wonder if the permissions on the file are incorrect since we use a custom action to write it.

**Comment by mojoaar** [comment]
@adamdriscoll I did try to add my own admin account (full access) to the appsettings file since I saw my colleague having full access - still the same issue. Any ideas to what else to try?
