### ISSUE TITLE
-TimeZone for New-UDDatePicker and New-UDTimePicker

### ISSUE THREAD

**Issue by ptmorris1** [ironmansoftware/powershell-universal#1629]
### Steps to Reproduce

Using New-UDTimePicker the value returns a date in the past and not the time chosen.

### Expected behavior

```console
Return selected time.
```

### Actual behavior

```console
Returns date 2 days in the past and wrong time.
```

### Environment data

3.3.7

**Comment by adamdriscoll** [comment]
Can you let me know what time zone you are in and if you are using a different locale? 

What I'm seeing is that it's returning the current date but in UTC time.

**Comment by ptmorris1** [comment]
So looks like my dashboard is giving me different results.  Below is my
code, screenshot of the form on submit and $eventdata from debugger for
each one.  The client I am running this from is CST but the server running
PSU is PST time zone.  Let me know if you need more information.

Thanks.


![image](https://user-images.githubusercontent.com/31410292/195826914-49ec5ebc-9a22-4a5e-b076-12577c4d8aa5.png)

![image](https://user-images.githubusercontent.com/31410292/195826964-bae680ab-9cae-43a6-9a3c-98e835a1f68f.png)

![image](https://user-images.githubusercontent.com/31410292/195826997-17799222-9b79-40bd-984c-e298023f2f3d.png)

![image](https://user-images.githubusercontent.com/31410292/195827047-bb20f8e7-f1e4-4656-a72e-39905234fe5d.png)


$pages += New-UDPage -Name "BlackoutWindow[testing]" /blkwndw -Content {

    $layout =
'{"lg":[{"w":4,"h":8,"x":0,"y":0,"i":"grid-element-CADRform","moved":false,"static":false}]}'

    New-UDGridLayout -Content {

        New-UDForm -Id 'CADRform' -Children {

            New-UDPaper -Elevation 3 -Children {

                New-UDGrid -Container -Spacing 2 -Children {

                    New-udgrid -Item -ExtraSmallSize 12 -Content {

                        New-UDTypography -Id 'CADRtext' -Text "Canada DR
Testing"

                    }

                    New-UDGrid -Item -ExtraSmallSize 6 -Content {

                        New-UDDatePicker -Id 'CAstartDate' -Label 'Start
Date'

                    }

                    New-UDGrid -Item -ExtraSmallSize 6 -Content {

                        New-UDDatePicker -Id 'CAendDate' -Label 'End Date'

                    }

                    New-UDGrid -Item -ExtraSmallSize 6 -Content {

                        New-UDTimePicker -id 'CAstartTime' -Label 'Start
Time'

                    }

                    New-UDGrid -Item -ExtraSmallSize 6 -Content {

                        New-UDTimePicker -Id 'CAendTime' -Label 'End Time'

                    }

                    New-UDGrid -Id 'selection' -Item -ExtraSmallSize
12 -Content
{

                        New-UDCheckBox -id 'Sun' -Label 'Sun' -LabelPlacement
bottom

                        New-UDCheckBox -id 'Mon' -Label 'Mon' -LabelPlacement
bottom

                        New-UDCheckBox -id 'Tue' -Label 'Tue' -LabelPlacement
bottom

                        New-UDCheckBox -id 'Wed' -Label 'Wed' -LabelPlacement
bottom

                        New-UDCheckBox -id 'Thur' -Label 'Thur' -LabelPlacement
bottom

                        New-UDCheckBox -id 'Fri' -Label 'Fri' -LabelPlacement
bottom

                        New-UDCheckBox -id 'Sat' -Label 'Sat' -LabelPlacement
bottom

                    }

                }

            }

        } -OnSubmit {

            Show-UDModal -Content {"Waiting debugger"}

            Wait-Debugger

            # if $eventdata -eq 'true'

            # $eventdata

            # get-date -Date "1/1/1970 7:30:00" -UFormat %s

        }

    } -Design -Layout $layout

}

**Comment by ptmorris1** [comment]
So the time picker should return a date as well?  I would prefer time only as you have a date picker as well.

The correct time is being picked now but it converts the time to local server time.  So if I pick 7am from the dashboard running on a PC using CST time it converts to PST time and chooses 5am.  I want to be able to use the time picked and not convert.  Is this possible?  Also would love to see the date removed from the time picker and time removed from the date picker.

Thanks.

**Comment by adamdriscoll** [comment]
Date and Time in .NET are represented by the DateTime object so there really isn't any separating them. You could use DateTime.TimeOfDay to get a time span from the date object and you could use DateTime.Date to get a date with the time set to midnight. 

As for date and time conversions, it seems to me that 7 AM CST would be the same time as 5 AM PST. Are you expecting to select 7 AM CST and then have the date returned as 7 AM PST on the server?

**Comment by ptmorris1** [comment]
Thanks.

I am just needing the exact time picked.  If the user picks 7am, then I will  use that value to set a black out window.  This doesn't work when the user picks 7am but the dashboard wants to use 5am.  When the time is picked on the dashboard it is assumed to be in PST time.  Hope that makes sense.

**Comment by adamdriscoll** [comment]
One thing we could do is add a -TimeZone parameter to both components. This would ensure that the date\time provided to the server was in the correct time zone. The user would then select the 7 AM and it would be 7 AM PST and not 7 AM local time for the client. I would also consider adding some sort of label to ensure that it's obvious this is what is happening. 

```
New-UDDatePicker  -TimeZone 'Pacific Standard Time' 
```

I think the current behavior should be the default since it's what most people would expect from the date\time pickers.

**Comment by ptmorris1** [comment]
That would work for me.  My goal is to avoid having the user have to try and convert times.  Thanks!
