### ISSUE TITLE
-Logo does not work when using theme in UD

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1630]
### Steps to Reproduce

When using one of the new themes, the -Logo is hidden behind the navbar. 

### Expected behavior

```console
Navbar goes under header
```

### Actual behavior

```console
Navbar goes over header.
```

### Environment data

3.3.7

**Comment by potatoqualitee** [comment]
@st3phhays had a solution for this that i may have included in the repo?
