### ISSUE TITLE
Cannot make Poshtools logging work in Visual Studio 2022

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/powershell-universal#1634]
This issue is opened from #1577 and additional conversation can be found there.
(Sorry it took me a while - away on holiday).
And problem is that I cannot make Poshtools in Visual Studio 2022 log to file.

When I open View(not Tools)->Powershell->Settings->Diagnostic, "Enable logging" is unchecked.
I can then check it, restart VS2022 - and the flag is unchecked again - apparently not saved.
"View logs" points to the expected folder.
And the logging is enabled under tools-->options...

The problem has been there for a while. So it it is not related to a version.

Version
Microsoft Visual Studio Community 2022
Version 17.3.4
VisualStudio.17.Release/17.3.4
Microsoft .NET Framework
Version 4.8.04084
Installed Version: Community
PowerShell Pro Tools for Visual Studio 2022.09.0

Operating System:
Edition Windows 10 Pro for Workstations
Version 21H2
OS build 19044.2006

![image](https://user-images.githubusercontent.com/32414636/195814658-9a0631cd-7df0-4c1b-8356-10ec47b9f2e9.png)
![image](https://user-images.githubusercontent.com/32414636/195814728-481ef85e-f662-45ba-a074-de81f0efa51f.png)

**Comment by adamdriscoll** [comment]
@pju55 - Can you let me know what other extensions you have installed? I wonder if one of them is also using Log4Net and causing an issue with the logging configuration.

**Comment by pju55** [comment]
Here you go,
I can disable/remove them if you think that'll help ?

<img width="339" alt="image" src="https://user-images.githubusercontent.com/32414636/196510541-d7c6f489-d04f-4ece-af39-64d1320060ba.png">

**Comment by adamdriscoll** [comment]
Thanks. I installed all of these extensions and logging still works for me. Looking at other options...

**Comment by adamdriscoll** [comment]
Can you do me a favor and try this version? I changed logging frameworks. It should always be enabled and show up in the same place. 

https://www.dropbox.com/s/lhld13b9gbwtth8/PowerShellTools.2022.2022.11.0.vsix?dl=0

**Comment by pju55** [comment]
You did it - again:-)
Logging is working, thanks!
[log-20221021.txt](https://github.com/ironmansoftware/issues/files/9839035/log-20221021.txt)

**Comment by adamdriscoll** [comment]
Good news!
