### ISSUE TITLE
Dashboards in 3.4.0 do not display color code (web ui)

### ISSUE THREAD

**Issue by mojoaar** [ironmansoftware/powershell-universal#1635]
### Steps to Reproduce

Create a dashboard and assign a tag

### Expected behavior

```console
Tag displays in web ui with color
```

### Actual behavior

```console
Tag displays, but without color
```

### Environment data

3.4.0

### Visuals

Endpoints (works):
![endpoint](https://user-images.githubusercontent.com/21560785/195827777-960cd482-a87e-4313-b74e-dd117a11d35a.png)

Dashboards (does not work):
![dashboards](https://user-images.githubusercontent.com/21560785/195827866-c315bc6e-3016-4d5f-9133-d7a050941412.png)

**Comment by adamdriscoll** [comment]
I can't reproduce this one on 3.4.1. 

<img width="1614" alt="image" src="https://user-images.githubusercontent.com/1256531/196214677-ffcc18ff-6911-46e3-8997-90e4a2aa6759.png">

**Comment by mojoaar** [comment]
Think this was a bad endpoint - created a new one and colors now displays.
