### ISSUE TITLE
PSScriptPad should incidate or warn if the Execution Policy is set to Restricted

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1636]
## Is your feature request related to a problem? Please describe.
No, it's just a minor improvement.

## Describe the solution you'd like
Some kind of indicator or warning from PSScriptPad if the applicable execution policy is set to restricted.

## Describe alternatives you've considered
none

## Additional context
This is most applicable for a freshly installed workstation

**Comment by adamdriscoll** [comment]
We will display this in the top right corner. 

<img width="555" alt="image" src="https://user-images.githubusercontent.com/1256531/196380245-5cc9fa81-afb6-415f-8135-146766b5fa11.png">
