### ISSUE TITLE
api endpoint does not work after adding a parameter

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1641]
## Step 1
create api called /users
```powershell
"Hello Name"
```

## Step 2
edit /users endpoint and add a parameter /users/:name
```powershell
"Hello $name"
```

## Step 3
test the endpoint
GET /users/Omzig

### Expected behavior

```console
"Hello Omzig"
```

### Actual behavior

```console
variables does not show up in the edited api in the "Info" tab. you have to recreate the API correctly with the :nameOfTheVariable in order for the api to work correctly.
```

### Environment data

Windows Server 2019

### Visuals

Before existing api is edited and a parm is added to it:
![image](https://user-images.githubusercontent.com/1987296/197296797-6c7a22b8-9dbd-4a77-a70f-05f012b086eb.png)

After existing api is update with a parm:
![image](https://user-images.githubusercontent.com/1987296/197296936-d3194fb8-fde7-4982-bebb-2eb3a9ac5fc6.png)

Trying to invoke it gives a 404
![image](https://user-images.githubusercontent.com/1987296/197297231-c613ed0b-30bd-49ee-90e9-72356af720f3.png)

# Workaround
- Restart 'PowerShell Universal' Service

# Failed Workaround
- Click the 'Restart API's' Button on the /admin/apis/endpoints page

**Comment by adamdriscoll** [comment]
I can reproduce this.
