### ISSUE TITLE
Scripts time out instantly if time out minutes is defined

### ISSUE THREAD

**Issue by molson98** [ironmansoftware/powershell-universal#1658]
### Steps to Reproduce

I created an automation script that just wrote out hello. Defined a time out of 10 minutes and run it. 

### Expected behavior

```console
Script should run up to the defined time out
```

### Actual behavior

```console
The Job will fail with a timeout.  If the script takes longer then a few second to run it will also cancel the script.
```

### Environment data

Universal: 3.4.4
Windows Server: 2016
Run as a service with a windows domain user.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/automation-pipeline-has-been-stopped/8035/3
