### ISSUE TITLE
UDTable: Cannot read properties of undefined (reading '__version')

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#1659]
### Steps to Reproduce

Don't know unfortunately. :-(
No log or anything in the Admin console that gives some hints about the issue..

It started to appear all over sudden...

Seems a rendering problem with the UDTable component

![image](https://user-images.githubusercontent.com/11975745/198953537-d70d60d9-9b22-40a7-9148-f03f7379f17f.png)

### Expected behavior

```console
The UDTable shoud render as usual
```

### Actual behavior

```console
The UDTable stops rendering with this strange expection
```

### Environment data

3.4.4

**Comment by donlent** [comment]
@mattselle @adamdriscoll 
I may have found some hints for you... It seems related to a multiple use of the same UDTable ID.

Let me quickly explain what I'm doing...

In order to optimize the responsiveness I'm doing this. 

```
New-UDHidden -Only 'xs' -Content {
        New-UDTable -Id 'QueryResultsADTable -LoadData {
        [...]
        }

New-UDHidden -Only @('sm', 'md', 'lg', 'xl') -Content {
        New-UDTable -Id 'QueryResultsADTable -LoadData {
        [...]
        }
```

Like that I'm able to show the table with an optimized UDTable with specific width and relevant columns, based on the screen size.

Normally this used to work. Also it used to work until last week... Then... Yesterday I realized this issue...
If I change the Table IDs it "seems" to work ("seems" cause I haven't done extensive tests). However this complicates the code a little bit because when I trigger table refreshes I'd have to do it for each and every table based on the screensize. 
And since I think they can "co-exist" since they get loaded only when they're shown (at least I suppose it is like that?) this makes the code a bit more slick. 

Or am I totally wrong with that?

Thanks a lot for your much appreciated help guys!

Kind regards,
Don

**Comment by adamdriscoll** [comment]
Hmm that's a neat way to do this. I'm having a bit of a hard time reproducing this one. Here's my test. 

```
New-UDDashboard -Title 'PowerShell Universal' -Content {
    New-UDHidden -Only 'xs' -Content {
        $Columns = @(
            New-UDTableColumn -Property Name -Title "Name" -ShowFilter
            New-UDTableColumn -Property Value -Title "Value" -ShowFilter
        )

        $Data = 1..1000 | ForEach-Object {
            @{
                Name  = "Record-$_"
                Value = $_ 
            }
        }

        New-UDTable -Id 'table' -Columns $Columns -LoadData {
            foreach ($Filter in $EventData.Filters) {
                $Data = $Data | Where-Object -Property $Filter.Id -Match -Value $Filter.Value
            }

            $TotalCount = $Data.Count 

            if (-not [string]::IsNullOrEmpty($EventData.OrderBy)) {
                $Descending = $EventData.OrderDirection -ne 'asc'
                $Data = $Data | Sort-Object -Property $EventData.orderBy -Descending:$Descending
            }
    
            $Data = $Data | Select-Object -First $EventData.PageSize -Skip ($EventData.Page * $EventData.PageSize)

            $Data | Out-UDTableData -Page $EventData.Page -TotalCount $TotalCount -Properties $EventData.Properties 
        } -ShowFilter -ShowSort -ShowPagination
    }

    New-UDHidden -Only @('sm', 'md', 'lg', 'xl') -Content {
        $Columns = @(
            New-UDTableColumn -Property Name -Title "Name" -ShowFilter
            New-UDTableColumn -Property Value -Title "Value" -ShowFilter
        )

        $Data = 1..1000 | ForEach-Object {
            @{
                Name  = "Record-$_"
                Value = $_ 
            }
        }

        New-UDTable -Id 'table' -Columns $Columns -LoadData {
            foreach ($Filter in $EventData.Filters) {
                $Data = $Data | Where-Object -Property $Filter.Id -Match -Value $Filter.Value
            }

            $TotalCount = $Data.Count 

            if (-not [string]::IsNullOrEmpty($EventData.OrderBy)) {
                $Descending = $EventData.OrderDirection -ne 'asc'
                $Data = $Data | Sort-Object -Property $EventData.orderBy -Descending:$Descending
            }
    
            $Data = $Data | Select-Object -First $EventData.PageSize -Skip ($EventData.Page * $EventData.PageSize)

            $Data | Out-UDTableData -Page $EventData.Page -TotalCount $TotalCount -Properties $EventData.Properties 
        } -ShowFilter -ShowSort -ShowPagination
    }

    New-UDButton -Text 'sync' -OnClick {
        Sync-UDElement -Id 'table'
    }
}
```

I can resize and sync the tables without issue and everything seems to respond properly. Can you send all the errors from the browser console?

**Comment by donlent** [comment]
Dear @adamdriscoll 
Thanks a lot for your analysis trying to figure out what's going on here.
Sure I will try my best to send you all the needed information tomorrow morning. Will also try to figure out more details about the issue. Interesting enough this issue happens only on the full table and not on the XS (for small screens). that one seems to render without problems even if the first one breaks (going from big to small screen). so strange... So it seems that something is causing a critical exception in this react component when trying to populate all TableColums maybe...
Anyway I'll keep you posted!
Thanks again,
Don

**Comment by donlent** [comment]
Hey @adamdriscoll 
EUREKA!! 🥳 I was able to find the bug!!

It is related to the -Render Argument!

To reproduce it do this:
Just add a -Render { } to any of the UDTableColumns situated under the very first UDHidden Section. 

Example:
```
New-UDHidden -Only 'xs' -Content {
        $Columns = @(
            New-UDTableColumn -Property Name -Title "Name" -ShowFilter -Render { }
            New-UDTableColumn -Property Value -Title "Value" -ShowFilter
        )
```
Reload the Dashboard and "boom"! 😅

Now remove it from that part of the code and add it to this section here:
```
    New-UDHidden -Only @('sm', 'md', 'lg', 'xl') -Content {
        $Columns = @(
            New-UDTableColumn -Property Name -Title "Name" -ShowFilter -Render { }
            New-UDTableColumn -Property Value -Title "Value" -ShowFilter
        )
```
It will work! 😅
So it seems that it is somehow related to the combo of New-UDHidden -Only 'xs' while trying to render TableColumns...

Hope that helps for now to solve the issue on your end! 😃
If not just let me know what else I can do for you, ok?

Looking forward to hearing from you.

Kind regards,
Don

**Comment by donlent** [comment]
...just another thought... I'm wondering if this bug will in the end lead to this one as well...?
https://github.com/ironmansoftware/issues/issues/1561

So maybe once this one gets solved it will resolve also issue 1561? Really hope so! 🙏

**Comment by adamdriscoll** [comment]
It looks like what was changed to fix #1561 has also fixed this!

**Comment by donlent** [comment]
YESSSSS!!! 🎉🥳😀
Thanks a lot mate!! Can't wait to test 3.5.0 GA tomorrow! 🎉🎉🎉
All the best to you and thanks again for your tremendous support! Really much appreciated!! 🤗

**Comment by donlent** [comment]
Dear @adamdriscoll 
Unfortunately I have to tell you that this issue still persists... Here's the code to reproduce it:

```
New-UDDashboard -Title 'PowerShell Universal' -Content {
    New-UDHidden -Only 'xs' -Content {
        $Columns = @(
            New-UDTableColumn -Property Name -Title "Name" -ShowFilter -Render { }
            New-UDTableColumn -Property Value -Title "Value" -ShowFilter 
        )

        $Data = 1..1000 | ForEach-Object {
            @{
                Name  = "Record-$_"
                Value = $_ 
            }
        }

        New-UDTable -Id 'table' -Columns $Columns -LoadData {
            foreach ($Filter in $EventData.Filters) {
                $Data = $Data | Where-Object -Property $Filter.Id -Match -Value $Filter.Value
            }

            $TotalCount = $Data.Count 

            if (-not [string]::IsNullOrEmpty($EventData.OrderBy)) {
                $Descending = $EventData.OrderDirection -ne 'asc'
                $Data = $Data | Sort-Object -Property $EventData.orderBy -Descending:$Descending
            }
    
            $Data = $Data | Select-Object -First $EventData.PageSize -Skip ($EventData.Page * $EventData.PageSize)

            $Data | Out-UDTableData -Page $EventData.Page -TotalCount $TotalCount -Properties $EventData.Properties 
        } -ShowFilter -ShowSort -ShowPagination
    }

    New-UDHidden -Only @('sm', 'md', 'lg', 'xl') -Content {
        $Columns = @(
            New-UDTableColumn -Property Name -Title "Name" -ShowFilter
            New-UDTableColumn -Property Value -Title "Value" -ShowFilter
        )

        $Data = 1..1000 | ForEach-Object {
            @{
                Name  = "Record-$_"
                Value = $_ 
            }
        }

        New-UDTable -Id 'table' -Columns $Columns -LoadData {
            foreach ($Filter in $EventData.Filters) {
                $Data = $Data | Where-Object -Property $Filter.Id -Match -Value $Filter.Value
            }

            $TotalCount = $Data.Count 

            if (-not [string]::IsNullOrEmpty($EventData.OrderBy)) {
                $Descending = $EventData.OrderDirection -ne 'asc'
                $Data = $Data | Sort-Object -Property $EventData.orderBy -Descending:$Descending
            }
    
            $Data = $Data | Select-Object -First $EventData.PageSize -Skip ($EventData.Page * $EventData.PageSize)

            $Data | Out-UDTableData -Page $EventData.Page -TotalCount $TotalCount -Properties $EventData.Properties 
        } -ShowFilter -ShowSort -ShowPagination
    }

    New-UDButton -Text 'sync' -OnClick {
        Sync-UDElement -Id 'table'
    }
}
```

Pay attention to this line in particular:
`New-UDTableColumn -Property Name -Title "Name" -ShowFilter -Render { }`

As soon as you add `-Render {} ` it will raise this error.

Would be really cool if you can have a closer look at this because I'm sure this causes other implicit issues...
Thanks a lot for all your efforts, Don
