### ISSUE TITLE
Automation Scripts: Stream Output in one line

### ISSUE THREAD

**Issue by claudiospizzi** [ironmansoftware/powershell-universal#1660]
### Steps to Reproduce

function Log-Verbose ($Message)
{
    $VerbosePreference = 'Continue'
    Write-Verbose -Message $Message
}

function Log-Warning ($Message)
{
    # $VerbosePreference = 'Continue'
    Write-Warning -Message $Message
}

Log-Verbose -Message 'Message 1'

$var = 2 + 2

Log-Verbose -Message 'Message 2'

$var = $var * $var

Log-Warning -Message 'Warning!'

$var = $var / 2

Log-Verbose -Message 'Message 3'

### Expected behavior

```console
Message 1
Message 2
Warning!
Message 3
```

### Actual behavior

```console
Message 1Message 2Warning!Message 3
```

### Environment data

Windows Server, Installed with Default Options, PowerShell Universal 3.4.4

### Visuals

Check the Output pane:
![827712459aca0fcaa076af865763788d724d4161_2_690x211](https://user-images.githubusercontent.com/1934246/199005318-894af6d4-3533-4df1-a6d4-e0d1e1e7dade.png)

**Comment by claudiospizzi** [comment]
Forum entry: [https://forums.ironmansoftware.com/t/streams-are-in-one-output/8003](https://forums.ironmansoftware.com/t/streams-are-in-one-output/8003)

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/streams-are-in-one-output/8003/4

**Comment by claudiospizzi** [comment]
@adamdriscoll 
I've opened the forum post. As there was no feedback and I think it's a platform bug, I've opened this issue too.

**Comment by adamdriscoll** [comment]
@claudiospizzi - I can reproduce this. Currently working on a fix. We'll put out a 3.4.5 build when this is resolved.
