### ISSUE TITLE
Links Not working when using nested IIS application configuration

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1661]
### Steps to Reproduce

I am experiencing an issue with the /psuSandbox application not being applied to all the links inside the admin site. In this instance of the problem, the dashboard stop and restart and start is not working.

### Expected behavior

```console
All links/buttons/actions should use the base href instead of sending you back to the root path of /.
Dashboard Stop/Start/Restart to include the application name in the api call. 
```

### Actual behavior

```console
error 500 because its going to the wrong endpoint
```

Environment data

PsU: 3.4.4 server
IIS: nested application
Windows Server: 2019

### Visuals

![image](https://user-images.githubusercontent.com/1987296/199054906-0f2b3a8a-6be6-48ba-b0dc-2af14ae94e0f.png)

### Forum Link
- https://forums.ironmansoftware.com/t/pu-single-iis-site-with-multiple-nested-applications/8015/19

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/pu-single-iis-site-with-multiple-nested-applications/8015/19

**Comment by Omzig** [comment]
> This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:
> 
> https://forums.ironmansoftware.com/t/pu-single-iis-site-with-multiple-nested-applications/8015/19


I found another issue, thought i would log it correctly ;)

I know that you said that notifications would be fixed in 3.5, but this needs to be added to that issue

**Comment by Omzig** [comment]
@adamdriscoll, it also seems that the api config is not working on the dashbord api's:
![image](https://user-images.githubusercontent.com/1987296/199062186-9e14bf6c-efb9-46ae-aa0b-e3a1cd7c54ea.png)

```json
{
	"Kestrel": {
		"Endpoints": {
			"HTTP": {
				"Url": "http://*:5000"
			}
		},
		"RedirectToHttps": "false",
		"UseHttpSys": "false",
		"BasePath": "/psuSandbox"
	},
	"ApplicationInsights": {
		"InstrumentationKey": ""
	},
	"Logging": {
		"Path": "E:\\src\\psu\\psuSandbox_data\\PowerShellUniversal\\log.txt",
		"RetainedFileCountLimit": 31,
		"LogLevel": {
			"Default": "Information",
			"Microsoft": "Warning",
			"Microsoft.Hosting.Lifetime": "Information",
			"Grpc": "Information"
		}
	},
	"AllowedHosts": "*",
	"CorsHosts": "",
	"Plugins": [
		"UniversalAutomation.LiteDBv5"
	],
	"Data": {
		"RepositoryPath": "E:\\src\\psu\\psuSandbox_data\\UniversalAutomation\\Repository",
		"ConnectionString": "filename=E:\\src\\psu\\psuSandbox_data\\UniversalAutomation\\database.db;upgrade=true",
		"RunMigrations": true,
		"GitRemote": "",
		"GitUserName": "",
		"GitPassword": "",
		"GitBranch": "",
		"GitSyncBehavior": "TwoWay",
		"GitInitializeBehavior": "",
		"GitSyncInterval": "1",
		"ConfigurationScript": ""
	},
	"Api": {
		"Url": "/psuSandbox",
		"GrpcPort": 0
	},
	"Authentication": {
		"Windows": {
			"Enabled": "false"
		},
		"WSFed": {
			"Enabled": "false",
			"MetadataAddress": "",
			"Wtrealm": "",
			"CallbackPath": "/auth/signin-wsfed",
			"Wreply": "",
			"UseTokenLifetime": true,
			"CorrelationCookieSameSite": ""
		},
		"OIDC": {
			"Enabled": "false",
			"CallbackPath": "/auth/signin-oidc",
			"ClientID": "",
			"ClientSecret": "",
			"Resource": "",
			"Authority": "",
			"ResponseType": "",
			"SaveTokens": "false",
			"CorrelationCookieSameSite": "",
			"UseTokenLifetime": true,
			"Scope": "openid profile groups",
			"GetUserInfo": false
		},
		"ClientCertificate": {
			"Enabled": "false"
		},
		"SessionTimeout": "500"
	},
	"Jwt": {
		"SigningKey": "PleaseUseYourOwnSigningKeyHere",
		"Issuer": "IronmanSoftware",
		"Audience": "PowerShellUniversal"
	},
	"UniversalAutomation": {
		"JobHandshakeTimeout": 5,
		"JobDebugging": false,
		"ContinueJobOnServerStop": false
	},
	"UniversalDashboard": {
		"AssetsFolder": "E:\\src\\psu\\psuSandbox_data\\PowerShellUniversal\\Dashboard",
		"DashboardStartupTimeout": 10
	},
	"Secrets": {
		"SecretStore": {
			"Password": "PSUSecretStore"
		}
	},
	"ShowDevTools": false,
	"HideAdminConsole": false,
	"Profiling": false
}
```

**Comment by Omzig** [comment]
@adamdriscoll,  I found another missing /applicationName/api 
![image](https://user-images.githubusercontent.com/1987296/199077564-02e0fdf3-e93c-4a0d-af6a-7495dbc3aee7.png)

**Comment by Omzig** [comment]
I found another missing /applicationName/ when importing templates:

![image](https://user-images.githubusercontent.com/1987296/199236186-3a4f31b2-bfcc-4362-92c1-34c735960ee2.png)
