### ISSUE TITLE
API Endpoint - Excel Upload Getting Corrupted

### ISSUE THREAD

**Issue by memphisraynz** [ironmansoftware/powershell-universal#1667]
### Steps to Reproduce

Using the example on the documentation page, using Invoke-Restmethod -InFile and then saving the file with [IO.File]::WriteAllBytes("C:\Temp\V1.xlsx", $Data) results in a corrupt file.

### Expected behavior

```console
Allow opening.
```

### Actual behavior

```console
Opening file in Excel says it is corrupt.
Only difference I can see is Excel files on my machine are ANSI econded and the files saved by PUS are UTF-8 encoded
```

### Environment data

API running under PS5.1
PSU Version 3.4.4

**Comment by adamdriscoll** [comment]
This was actually resolved a few days ago in our 3.5 branch.
