### ISSUE TITLE
Missing Documentation for New-UDImage

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1668]
### Summary of the new feature / enhancement

As a developer, I want to see New-UDImage as a component in the dashboard help to remind me what components are available.
https://docs.powershelluniversal.com/userinterfaces/dashboards/components

The best i could find was by searching google and found this:
https://github.com/adamdriscoll/universal-dashboard-documentation/blob/master/api/1.6.0/New-UDImage.md

**Comment by adamdriscoll** [comment]
The most recent docs are here: https://github.com/ironmansoftware/universal-docs/blob/master/cmdlets/New-UDImage.txt

We should add this to the docs page though...

**Comment by adamdriscoll** [comment]
This has been completed here: https://docs.powershelluniversal.com/userinterfaces/dashboards/components/data-visualization/image
