### ISSUE TITLE
Add more robust swagger documentation for endpoints

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1680]
### Summary of the new feature / enhancement

As a developer, I want to be able to create better swagger documentation so that people know how to consume my api's. 

### Proposed technical implementation details

1) create a new definition for /endpionts, called user defined endpoints or something
![image](https://user-images.githubusercontent.com/1987296/199983077-2a10792e-ba5a-4828-8f65-1a729523479f.png)
2) add something to the endpoint like -swagger $swaggerStuff 
3) add another edit button on the endpoint just for swagger stuff in the admin site
4) Pode is a good pattern of how they did the swagger doc
5) maybe use comment based help to change the documentation on each field exposed to swagger? or maybe surface the existing tags feature to swagger?

### Current
It currently puts path and query fields in the swagger api, but you cannot do much with them.

**Comment by schubfre** [comment]
#542

**Comment by adamdriscoll** [comment]
<img width="398" alt="image" src="https://user-images.githubusercontent.com/1256531/202731967-9cb6996b-3ca9-4ab5-9cfb-9f017add9416.png">

<img width="306" alt="image" src="https://user-images.githubusercontent.com/1256531/202731997-ad7f39ac-3da0-47a5-a95a-68c6c1fe1281.png">

<img width="179" alt="image" src="https://user-images.githubusercontent.com/1256531/202732049-03af58c1-d4ea-4ae6-9938-c0c99170172c.png">

We'll be exposing schemas using PS classes. 

```
[Documentation()]
class MyReturnType {
    [string]$Value
}
```

Then, comment based help can be used to tie schema to return values and inputs. 

```
<# 
    .SYNOPSIS
    This is an endpoint
      
    .DESCRIPTION
    This is a description
    
    .PARAMETER Id
    This is an ID.
    
    .PARAMETER AnotherOne
    This is AnotherOne

    .OUTPUTS
        200:
            Description: This is a very great return value.
            Content:
                application/json: MyReturnType

        400:
            Description: bad
        
    #>
```

**Comment by Omzig** [comment]
> <img alt="image" width="398" src="https://user-images.githubusercontent.com/1256531/202731967-9cb6996b-3ca9-4ab5-9cfb-9f017add9416.png">
> 
> <img alt="image" width="306" src="https://user-images.githubusercontent.com/1256531/202731997-ad7f39ac-3da0-47a5-a95a-68c6c1fe1281.png">
> 
> <img alt="image" width="179" src="https://user-images.githubusercontent.com/1256531/202732049-03af58c1-d4ea-4ae6-9938-c0c99170172c.png">
> 
> We'll be exposing schemas using PS classes.
> 
> ```
> [Documentation()]
> class MyReturnType {
>     [string]$Value
> }
> ```
> 
> Then, comment based help can be used to tie schema to return values and inputs.
> 
> ```
> <# 
>     .SYNOPSIS
>     This is an endpoint
>       
>     .DESCRIPTION
>     This is a description
>     
>     .PARAMETER Id
>     This is an ID.
>     
>     .PARAMETER AnotherOne
>     This is AnotherOne
> 
>     .OUTPUTS
>         200:
>             Description: This is a very great return value.
>             Content:
>                 application/json: MyReturnType
> 
>         400:
>             Description: bad
>         
>     #>
> ```

/drool, this is amazing!!!!!!!!!!!!!!!!

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/swagger-autodoc-document-body-instead-of-query/7516/3

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/is-there-a-way-to-change-the-swagger-api-tag-in-the-endpoints-documentation/8326/1

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/swagger-autodoc/8387/1
