### ISSUE TITLE
Add "Run As" to /endpoints

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1683]
### Summary of the new feature / enhancement

As a developer, I want to use 'run as' on endpoints the same way as i can use 'run as' on a dashboard so that i can use different account to get access to different systems to get the data from it.
- sql databases
- environments

I do not want to create a 'god' account that has access to everything in dev and production. 

### Proposed technical implementation details (optional)

- use the same pattern for 'run as' in the dashboards and apply it to endpoints. FYI pages doesn't have a run as feature either. 
- maybe even put the run as down at the environment level
![image](https://user-images.githubusercontent.com/1987296/200587475-fed80d34-50c2-465f-b4f2-cafc12ab212d.png)

### Workaround 
- Setup a script to run on a schedule and extract the SQL data into a csv file and keep the table/csv up to date
- use the /api/myTableData {import-csv -path  c:\temp\myDownloadedTableData.csv}

**Comment by Omzig** [comment]
@adamdriscoll, this has not made it to help yet ;)

**Comment by Omzig** [comment]
Beta5 does not have this yet, so maybe it is stuck in a branch somewhere?

**Comment by adamdriscoll** [comment]
We have this in 4.0 via environments. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/d21ab2c1-4a88-4db1-8871-f882ed2f5877)

![image](https://github.com/ironmansoftware/issues/assets/1256531/f89743e7-f291-44f8-a833-be8c1e0b3092)
