### ISSUE TITLE
Role authorization on pages does not work on 3.5.0

### ISSUE THREAD

**Issue by gitbute** [ironmansoftware/powershell-universal#1692]
### Steps to Reproduce

Pages with a role set (New-UDPage -Role 'xyz') does not work for us anymore, after upgrading from 3.4.1 to 3.5.0
We use integrated windows authentication with kestrel as host.
Outputting the $Roles variable in a Page actually shows the right SID's and computed Policy-Roles, and the admin-Dashboard also works fine.

### Expected behavior

```console
On pages with -Role switch, the Users in the correct role has access
```

### Actual behavior

```console
The user with the correct Role has 'Page not found' error - the page definitely gets loaded though.

The log from universal shows several of the following errors, maybe it has to do with it:
System.InvalidOperationException: No authentication handler is registered for the scheme 'Negotiate'. The registered schemes are: Identity.External, Cookies, Bearer. 
```

### Environment data

Version Number: 3.5.0, Kestrel hosted, Authentication trough integrated Windows Authentication

**Comment by adamdriscoll** [comment]
We have some [routing issues](https://forums.ironmansoftware.com/t/psu-3-5-0-dashboard-blank/8102/5) that we are looking at that may be causing this as well. 

I can't reproduce your issue with our current 3.5.1 with the fix implemented. I'll try installing 3.5.0 and see if the issue is present. 

All that said, it looks like we may have this fixed.

**Comment by gitbute** [comment]
Wow, quick reply 😃
I also found out that the username does not get displayed in the header on the dashboard anymore - works fine in admin console.
In the meantime i rolled back to 3.4.1 - waiting for the fix.

Thanks very much

**Comment by adamdriscoll** [comment]
After messing around with this a big, I'm not seeing this issue. Can you let me know how you configured Windows auth? Authentication.ps1?

**Comment by gitbute** [comment]
No, per appsettings.json and roles.json
![image](https://user-images.githubusercontent.com/32512939/200866237-c0e8b8ea-e1ad-40be-af2a-de0d99317630.png)

**Comment by adamdriscoll** [comment]
Ah, interesting. I only ask because I've seen some issues where Windows auth won't get enabled properly when clicking that enabled switch in the admin console. 

This error is referring to the Windows (Negotiate) auth not being enabled properly. 

```
System.InvalidOperationException: No authentication handler is registered for the scheme 'Negotiate'. The registered schemes are: Identity.External, Cookies, Bearer. 
```

I'll continue to try to track this one and let you know if I need more info.

**Comment by gitbute** [comment]
I tried it today with 3.5.4, but sadly it did not fix the issue.
Any idea what i can try to fix it?

**Comment by gitbute** [comment]
@adamdriscoll 

Can we try anything else to solve this for our environment? Is my screenshot how the setup should be done, or can i try anything else? I'd rather not start from scratch completely..

Thanks very much.

**Comment by gitbute** [comment]
@adamdriscoll

How should i proceed in this? Do i have to setup the instance completely new?

Thanks

**Comment by gitbute** [comment]
@adamdriscoll 

Ok so i think i found the bug after much testing and a complete reinstallation.
As soon as i configure a -Logo on New-UDDashboard, i have the bug. Without the Logo everything works fine.
The Logo comes from a published folder. It doesnt matter if i make the published folder authenticated or not, i have the bug.
Maybe something you can check out.
For the meantime we just ditch our logo from the dashboard.

Thanks
