### ISSUE TITLE
Enable 'One Time' schedule while in 'One-Way' git sync mode

### ISSUE THREAD

**Issue by schubfre** [ironmansoftware/powershell-universal#1702]
### Summary of the new feature / enhancement

In One Way git mode it's currently not possible to make One Time schedules. It's not feasable to PR into the main branch just for a one time schedule. So I would like to have the option to schedule a one-off script run while PSU runs in 'Read Only' mode.

### Proposed technical implementation details (optional)

Save 'One Time' schedules in database as opposed to schedules.ps1
Saving a one time schedule in the database would make it possible to use it when in 'One-Way' git sync mode.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/managing-jobs-with-one-way-sync/8742/2

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/one-time-schedules-are-not-triggered-on-psu-4/10070/2
