### ISSUE TITLE
When loadin pages get “-1% Reading web respons”  pop-up

### ISSUE THREAD

**Issue by robinstolpe** [ironmansoftware/powershell-universal#1711]
### Steps to Reproduce

Load dashboard or page

### Expected behavior

```console
Don’t show pop-up that says “-1% Reading web respons”
```

### Actual behavior

```console
Pop-up shows with “-1% Reading web respons”
```

### Environment data

Psu 3.5.2
PowerShell 7.3

### Visuals

![3FE10080-1B43-4D3C-9511-AA321DF18035](https://user-images.githubusercontent.com/106820660/201598140-6c952e29-5bf0-49ae-ae5c-42dd319f25a4.jpeg)

**Comment by adamdriscoll** [comment]
I've updated the documentation with info on how to prevent this from happening: https://docs.powershelluniversal.com/userinterfaces/dashboards/interaction#write-progress
