### ISSUE TITLE
Hide property doesn't seem to work on Data Grid columns

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1713]
### Steps to Reproduce

When the _Hide_ property is specified for a column in a Data Grid, it doesn't seem to be honored. It seems that _Hide_ is acting like _Hideable_.

This issue was internally reported 🍮

The below code will demonstrate the issue.

```
New-UDDashboard -Title 'Issue1713' -Content {
    New-UDDataGrid -id 'datagrid_id' -LoadRows {
        $Data = @(
            @{ Name = 'Larry'; Number = 1; Widget = 'A'}
            @{ Name = 'Moe'; Number = 2; Widget = 'B'}
            @{ Name = 'Jack'; Number = 3; Widget = 'C'}
        )
        @{
            rows = $Data 
            rowCount = $Data.Length
        } 
    } -Columns @(
        @{ field = "name"}
        @{ field = "number"}
        @{ field = "widget"; hide = $true}
    ) -AutoHeight
}
```

### Expected behavior

```console
A column with the Hide property specified as true should be hidden
```

### Actual behavior

```console
A column with the Hide property specified as true can be hidden with 1 click
```

### Environment data

PSU 3.5.2

###### below figure shows that the Hide property seems to function as Hideable
![Issue1713](https://user-images.githubusercontent.com/537287/201650132-5b7d009d-a98b-401e-b03f-90bf321c1fc6.gif)

**Comment by adamdriscoll** [comment]
Looks like that property is deprecated so we should implement the new way of doing it. 

https://mui.com/x/react-data-grid/column-visibility/#column-hide-property-deprecated

This is the new way to do it. 

https://mui.com/x/react-data-grid/column-visibility/#controlled-visible-columns
