### ISSUE TITLE
Add functionality to Get-PSUVariable to get a secret

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1723]
### Summary of the new feature / enhancement

As a developer, I want to get the value from a secret using Get-PSUVariable so that i can use parametrized names. 
- https://github.com/ironmansoftware/universal-docs/blob/master/cmdlets/Get-PSUVariable.txt
- the -ValueOnly returns "" if it is a secret

### Proposed technical implementation details (optional)

Add -Scope Secret to the existing cmdlet or -Secret. 

### Workaround
```powershell
function Get-MyPSUSecret{
    param(
        $Name
    )

    ([scriptblock]::Create("`${secret:$Name}")).Invoke() #Risk of command injection
}

$cred = Get-MyPSUSecret -Name $body.ServerName
```

**Comment by adamdriscoll** [comment]
You can use Get-ChildItem to do this because the secret scope is really just a custom provider. 

```
# PSCredential
(Get-ChildItem "Secret:MyNewSecret").UserName
(Get-ChildItem "Secret:MyNewSecret").Password

# String
(Get-ChildItem "Secret:DashboardSecret")
```

**Comment by Omzig** [comment]
> (Get-ChildItem "Secret:MyNewSecret")

Ok, well, that makes me feel dumb. I didn't even know you could DO THAT!

Would you mind to add it to your documentation on secrets here, maybe at the bottom in the alternative ways to get to the secrets?
- https://docs.powershelluniversal.com/platform/variables


This can be closed, but man, i am keeping it for memory.

I was able to do `(Get-ChildItem "Secret:$myServerName").UserName` !!!!

**Comment by adamdriscoll** [comment]
Done! Updated.
