### ISSUE TITLE
New-UDIcon add -Solid Parameter 

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1730]
### Summary of the new feature / enhancement

https://github.com/ironmansoftware/universal-dashboard-documentation/blob/master/api/New-UDIcon.md

can we add a -solid parm to the cmdlet so we can bring in the solid versions of the icons?

i am unable to get to the solid address book:
https://fontawesome.com/search?q=addressbook&o=r&m=free

**Comment by JQ1983** [comment]
see also https://forums.ironmansoftware.com/t/icon-solid-version/8029/2

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/icon-solid-version/8029/5

**Comment by adamdriscoll** [comment]
Added -Solid to New-UDIcon
