### ISSUE TITLE
Parameter default values in Automation Scripts aren't passed along to the GUI input

### ISSUE THREAD

**Issue by schubfre** [ironmansoftware/powershell-universal#1734]
### Steps to Reproduce

```
    [parameter(Mandatory = $false)]
    [ValidateSet('win', 'unx')]
    [string]
    $OSType = 'win'
```

### Expected behavior

```console
When you click on the "Invoke Script" button and the "Run ScriptX.ps1" GUI opens, the default values should be populated in the respective fields
```

### Actual behavior

```console
The "Run ScriptX.ps1" GUI doesn't show any default values
```

### Environment data

PSU 3.5.4

In PSU 2.5.5 it seems to have worked somewhat as per issue #746

EDIT: I'm pretty sure now it has worked as far as 3.3.x

### Visuals

![image](https://user-images.githubusercontent.com/28289080/202678467-008a7db0-1666-46db-acbc-927128747120.png)

**Comment by memphisraynz** [comment]
I am facing the same issue. For me the issue starting on the 3.5 releases.
For me I have noticed this issue on switches and booleans, they are all defaulting to off/false.
