### ISSUE TITLE
Textbox Labels misbehave when the Value of the TextBox is zero length

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1739]
### Steps to Reproduce

When the length of the Value of the New-UDTextBox is 0 (e.g. an _empty string or null_) then the label text will be shown in place of the value and there will effectively be no label. The below code will demonstrate the issue. 

```
New-UDDashboard -Title 'Issue #1739' -Content {
    $test1_value = 'Value 1'
    $test2_value = 'Value 2'
    $test3_value = ''
    #If( $test3_value.Length -eq 0){$test3_value = 'N/A'}
    New-UDTextBox -Id 'udtextbox_1' -Label 'Label 1' -Value $test1_value
    New-UDTextBox -Id 'udtextbox_2' -Label 'Label 2' -Value $test2_value
    New-UDTextBox -Id 'udtextbox_3' -Label 'Label 3' -Value $test3_value
}
```

## Steps to workaround

Uncommenting the 5th line will force the value of the textbox to be non-zero in length.

### Expected behavior

```console
A textbox with a value length of zero and a label should not be displayed in a malformed way.
```

### Actual behavior

```console
A textbox with a value length of zero and a label is displayed in a malformed way.
```

### Environment data

PSU 3.5.5

Note that this issue was reported internally 🍮

### Visuals

![image](https://user-images.githubusercontent.com/537287/202966152-4c107cc8-758d-400b-bd9b-4980e88db5ec.png)
![image](https://user-images.githubusercontent.com/537287/202966173-b0950fd5-a5d7-4e89-a68b-5c4506b2522d.png)

**Comment by adamdriscoll** [comment]
This is the default behavior for text boxes using the MUI framework: https://mui.com/material-ui/react-text-field/#basic-textfield

It is possible to change the shrink state: https://mui.com/material-ui/react-text-field/#shrink

We could add a new parameter called Shrink to force it into this state.
