### ISSUE TITLE
Ability to disable dashboards 🟡

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1741]
### Summary of the new feature / enhancement

From within the UI, I would occasionally like to have a dashboard stay powered off after restarting PSU. Presently, this does not seem possible from within the UI.

### Proposed technical implementation details (optional)

Disabled dashboards could have a yellow indicator 🟡 whereas running dashboards have green 🟢 and powered off dashboards have red 🔴.

![image](https://user-images.githubusercontent.com/537287/203056130-9f5f5fb5-875a-4e24-89f9-5a4dc8e5be04.png)

![image](https://user-images.githubusercontent.com/537287/203057106-9f823f78-ffeb-49d2-9392-5a42d1f75c35.png)

**Comment by adamdriscoll** [comment]
@DataTraveler1 - If you got to the properties for a dashboard, you can disable Auto Start to prevent the dashboard from starting on restarts of the server.
