### ISSUE TITLE
vsCode extension don't work in macOS 13 (m1)

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1742]
I have reported this bug with a ticket also but I just want to highlight it here also if people getting the same issue.

So, when I install vsCode extension of PowerShell Pro Tools it won't start and just loops.

In the  Log (Extension Host) I can see the following error:
```
2022-11-21 12:22:07.575 [error] Error: ENOENT: no such file or directory, chmod '/Users/xxx/PowerShellProTools/2022.11.2/osx-arm64/PowerShellProTools.Host'
    at Object.chmodSync (node:fs:1830:3)
    at PowerShellService.<anonymous> (/Users/xxx/.vscode/extensions/ironmansoftware.powershellprotools-2022.11.2/out/services/powershellservice.js:264:24)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/xxx/.vscode/extensions/ironmansoftware.powershellprotools-2022.11.2/out/services/powershellservice.js:5:58)
```

When I go to the path ```/Users/xxx/PowerShellProTools/2022.11.2``` it don't contain the folder **osx-arm64** instead it contains the folder **osx**

So if I rename the folder to **osx-arm64** and restart vsCode I get the following error under Log (Extension Host):
```
2022-11-21 12:30:38.685 [error] Error: spawn /Users/xxx/PowerShellProTools/2022.11.2/osx-arm64/PowerShellProTools.Host EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

So @adamdriscoll did ask me to download the osx-arm64 version and manually import it to the path ```/Users/xxx/PowerShellProTools/2022.11.2/osx-arm64``` but that did not help either, when I did that I do get the following error in  Log (Extension Host)
```
2022-11-21 14:28:53.465 [error] Error: spawn /Users/xxxx/PowerShellProTools/2022.11.2/osx-arm64/PowerShellProTools.Host EACCES
    at ChildProcess._handle.onexit (node:internal/child_process:283:19)
    at onErrorNT (node:internal/child_process:478:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

But now I can see the following under the  OutPut and Powershell Pro Tools:
```
Starting PowerShell Pro Tools host from: /Users/xxxx/PowerShellProTools/2022.11.2/osx-arm64/PowerShellProTools.Host
Process started
```

Before I could not see anything in the  OutPut and Powershell Pro Tools tab.

@adamdriscoll  do you have some kind of nightly beta or similar of the PowerShell Pro Tools? I badly want it to work on my Mac :)

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/cant-install-powershell-pro-tools-for-vscode-on-mac/8149/4

**Comment by rwidmark** [comment]
@adamdriscoll any news for this?

**Comment by adamdriscoll** [comment]
@rstolpe - I'm working with Apple to help resolve an issue with our code signing. The latest version is correctly downloading and launching the proper architecture but the signing isn't valid and it's causing the application to stop as soon as it's started.

**Comment by rwidmark** [comment]
@adamdriscoll ok, I understand.

**Comment by rwidmark** [comment]
@adamdriscoll any luck?

**Comment by rwidmark** [comment]
Any news on this @adamdriscoll

**Comment by derFrane** [comment]
I have also the same Problem

**Comment by rwidmark** [comment]
@adamdriscoll any news?

**Comment by rwidmark** [comment]
@adamdriscoll  this one are hunting me as it don't work at Mac and I think that others also have the same issue. Any news on this one?

**Comment by rwidmark** [comment]
@adamdriscoll any news?

**Comment by WillPowerCat** [comment]
Same issue here, Including arm64 linux container.

Device
>   Model Name:	MacBook Pro
>   Model Number:	MPHK3X/A
>   Chip:	Apple M2 Max
>   Total Number of Cores:	12 (8 performance and 4 efficiency)
>   Memory:	32 GB


Just pure curiosity, is the code signing issue related to cross platform Authenticode support?

if you need a guinea pig - id be happy to help out.

**Comment by rwidmark** [comment]
> Same issue here, Including arm64 linux container.
> 
> 
> 
> Device
> 
> >   Model Name:	MacBook Pro
> 
> >   Model Number:	MPHK3X/A
> 
> >   Chip:	Apple M2 Max
> 
> >   Total Number of Cores:	12 (8 performance and 4 efficiency)
> 
> >   Memory:	32 GB
> 
> 
> 
> 
> 
> Just pure curiosity, is the code signing issue related to cross platform Authenticode support?
> 
> 
> 
> if you need a guinea pig - id be happy to help out.
> 
> 
> 
> 
> 
> 

I don't know but I'm still waiting for this @adamdriscoll

**Comment by adamdriscoll** [comment]
This will be supported in our next version. We actually changed how the extension works to avoid having to build hosts per OS.

**Comment by rwidmark** [comment]
> This will be supported in our next version. We actually changed how the extension works to avoid having to build hosts per OS. 

Do you have any release date for next version?

**Comment by adamdriscoll** [comment]
November 14

**Comment by rwidmark** [comment]
> November 14

Is it delayed?
