### ISSUE TITLE
Icon Documentation is not working

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1744]
### Summary of the documentation enhancement

this documentation does not work, it needs to be updated:
https://docs.powershelluniversal.com/userinterfaces/dashboards/components/data-display/icon#visually-search-for-icons

Error:
![image](https://user-images.githubusercontent.com/1987296/203132564-cda2609b-b0c5-4da9-be7a-235d6822aa9c.png)

### Proposed technical implementation details (optional)

```powershell
New-UDTextbox -Id 'txtIconSearch' -Label 'Search' 
    New-UDButton -Text 'Search' -OnClick {
        Sync-UDElement -Id 'icons'
    }

    New-UDElement -tag 'p' -Content {}

    New-UDDynamic -Id 'icons' -Content {
            $Icons = [Enum]::GetNames([UniversalDashboard.Models.FontAwesomeIcons]) | Where-Object {$_ -ne "None"}
            $IconSearch = (Get-UDElement -Id 'txtIconSearch').value
            if ($null -ne $IconSearch -and $IconSearch -ne '')
            {
            $Icons = $Icons.where({ $_ -match $IconSearch})
        }

        foreach($icon in $icons) {
            try{
                New-UDChip -Label $icon -Icon (New-UDIcon -Icon $icon)
            }
            catch{
                New-UDChip -Label "$icon Unknown" 
            }
        }
    }
```

However, it seems like there are a bunch of missing icons, or some that are named incorrectly:
![image](https://user-images.githubusercontent.com/1987296/203133022-5d600d35-040f-4197-b2c0-45bc0a675793.png)

**Comment by adamdriscoll** [comment]
This has been resolved: https://docs.powershelluniversal.com/userinterfaces/dashboards/components/data-display/icon#visually-search-for-icons
