### ISSUE TITLE
Error/Verbose messages no longer display colour when "time" is hidden

### ISSUE THREAD

**Issue by memphisraynz** [ironmansoftware/powershell-universal#1745]
### Steps to Reproduce

wirting a verbose or error message will only show the foreground colour when the Show Time toggle is enabled.

### Expected behavior

```console
Foreground colours are shown for both Show Time and Hide Time
```

### Actual behavior

```console
All text output is black
```

### Environment data

Version 3.5.5
Environment: Powershell 5.1 & Powershell 7.2

### Visuals

![image](https://user-images.githubusercontent.com/9811720/203164788-02847eae-8e7b-4372-a41d-dfa03864d252.png)

**Comment by schubfre** [comment]
Now in 3.6.2 the debug colour gets 'reset' to white when there are linebreaks

![image](https://user-images.githubusercontent.com/28289080/208707299-569ad224-7de3-4e9a-bc00-e74ac306fc1d.png)
