### ISSUE TITLE
Secrets not written to Database

### ISSUE THREAD

**Issue by Daniel0023** [ironmansoftware/powershell-universal#1754]
### Steps to Reproduce

Secrets created in the BuildInVault are not written to the Database. Which means when you have a cluster you must creat the secret on all nodes manually

### Expected behavior

```console
Secret written to Database and available on all nodes
```

### Actual behavior

```console
Not present in Database and on available the node where it was created
```

### Environment data

3.3.5

**Comment by adamdriscoll** [comment]
This is expected behavior. The BuiltInVault is using Credential Manager. That said, in version 3.6, we have implemented a new vault for storing secrets in the database.

**Comment by realslacker** [comment]
@adamdriscoll right after I spent the last few days setting up KeyVault
