### ISSUE TITLE
Generate UUID/GUID as Job IDs instead of incrementing a number

### ISSUE THREAD

**Issue by schubfre** [ironmansoftware/powershell-universal#1771]
### Summary of the new feature / enhancement

As a User I want Jobs to have UUIDs instead of incrementing numbers because UUIDs are so much harder to guess.

I have a Job Query API endpoint with which you can query an asynchronous API Call (POST request to endpoint, endpoints starts PSU Script). Currently I create a 0-byte file with the UUID of the HTTP request ($SessionId) as filename and Job ID (e.g. 52) as content.
Previously I used the PSU cache, but the cache gets cleared when the Service or Server is rebooted. I have also looked at a few cache tools for Windows (like Redis <- discontinued on Windows) but none were satisfactory. I will not build a Linux Server solely for the purpose of being cache. I need a non-filebased solution, because when we go from single instance to cluster the filesystem solution won't work anymore without a lot of effort.

I don't want anyone who doesn't know the Job ID requesting info about a job they shouldn't know about. I am aware that this is security by obscurity, but I don't have a better solution and we use other tools the same way (e.g. vRealize Orchestrator Execution IDs, Jenkins Build IDs, etc. all of which are UUIDs)

**Comment by rwidmark** [comment]
@adamdriscoll

**Comment by adamdriscoll** [comment]
This will be behind a feature flag to begin with because it changes quite a bit of how jobs work.

**Comment by Viajaz** [comment]
@adamdriscoll If we wanted to utilise this feature, would we be able to migrate to it on an existing instance?

**Comment by adamdriscoll** [comment]
@Viajaz - Yep. When you enable the feature flag, it will allocate GUIDs for all existing jobs and then turn off all the long ID based endpoints. We'll enforce this in 4.0 as the default.

**Comment by Viajaz** [comment]
> it will allocate GUIDs for all existing jobs

@adamdriscoll We've made assumptions that Job IDs are immutable, we'll need to change some code in some places, which release will this be in?
