### ISSUE TITLE
New-UDNivoChart not passing -Groupmode parameter

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#1772]
### Steps to Reproduce

I can't get a grouped (nivo) bar chart to render.  It's always stacked.

(this code is slightly modified from @cl's theme demo dashboard)

````powershell
        # NIVO CHART - BAR CHART
        $Data = 1..10 | ForEach-Object { 
            $item = Get-Random -Max 1000 
            [PSCustomObject]@{
                Name  = "Test$item"
                Value = $item
                Value2= $item*2
            }
        }
        New-UDNivoChart -Id 'autoRefreshingNivoBar' -bar -GroupMode Grouped -Keys "value","value2" -IndexBy 'name' -Data $Data -Height 500 -Width 1000
````

### Expected behavior

```console
The chart should be grouped.
```

### Actual behavior

```console
The chart is stacked
```

### Environment data

PowerShell Universal 3.5.5

### Visuals

What I'm getting
![image](https://user-images.githubusercontent.com/5541154/204903968-f686b439-813b-43be-ac64-b5e7a8150e3f.png)

What kind of chart I want:
![image](https://user-images.githubusercontent.com/5541154/204904174-c111f441-bfa9-4f3c-be04-948257fa392d.png)

**Comment by mattselle** [comment]
The problem is with the cmdlet call itself you need to change the Grouped to be "grouped" and you will see the bar chart draw correctly New-UDNivoChart -Id 'autoRefreshingNivoBar' -bar -GroupMode "grouped" -Keys "value","value2" -IndexBy 'name' -Data $Data -Height 500 -Width 1000

**Comment by MikeShepard** [comment]
That works.  The issue, then, is that there is parameter validation which allows Grouped instead of grouped (because the validation is case-insensitive.  Would be great if the code did a .ToLower() on the value so that validated parameter values worked.

I can continue without that change, though.  Thanks!

**Comment by mattselle** [comment]
Yes, that needs to be tolower for sure. I just put in a PR for that.

**Comment by MikeShepard** [comment]
I appreciate your help.  The responsiveness to issues in this project is extremely good and is definitely noticed.
