### ISSUE TITLE
Start-UDDownload adds a leading space to content

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#1775]
### Steps to Reproduce

Start-UDDownload -stringdata "hello"

resulting file is
(space)hello

### Expected behavior

```console
Start-UDDownload -stringdata "hello"

Downloaded file should contain hello (just 5 characters)
```

### Actual behavior

```console
Start-UDDownload -stringdata "hello"

Downloaded file contains " hello" (6 characters)
```

### Environment data

PSU 3.5.5

### Visuals

![image](https://user-images.githubusercontent.com/5541154/205139843-863a5331-da69-4921-b9a9-32024018eff5.png)

**Comment by Omzig** [comment]
@adamdriscoll, bump?

**Comment by Omzig** [comment]
Related: https://github.com/ironmansoftware/issues/issues/1876
