### ISSUE TITLE
Template - Windows System Information

### ISSUE THREAD

**Issue by PCAssistSoftware** [ironmansoftware/powershell-universal#1780]
### Steps to Reproduce

Get errors on Service, Processes and Event Log as per below screenshot

![image](https://user-images.githubusercontent.com/10872799/205492489-09eb8b5f-aa07-41ef-9f29-74cbf28c56b1.png)

### Expected behavior

```console
no error
```

### Actual behavior

```console
error
```

### Environment data

3.5.5

**Comment by rwidmark** [comment]
Don't see how this is a issue with PSU?
Your trying to send null.

The forum is a better place for this kind of Q

**Comment by PCAssistSoftware** [comment]
Because I am reporting a problem about one of the templates that come with PowerShell Universal.....???    All I have done is Imported it and tried to use it, and it didn't work - hence reporting a problem with it on the page linked from Support > Issue Tracker, which seemed the obvious / logical place to report it.

> Your trying to send null.

"I" am not trying to send null - I am just trying to use a template supplied and reporting it doesn't work..

![image](https://user-images.githubusercontent.com/10872799/207172745-4fed3900-5f4b-4181-95c5-0187a35d7d52.png)

**Comment by adamdriscoll** [comment]
Templates are no longer supported. This will be resolved in the PSU Windows System Information module.
