### ISSUE TITLE
Sort Tags Column does not sort in /admin/apis/endpoints

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1783]
### Steps to Reproduce

i am experience a problem with sorting the tags column

### Expected behavior

```console
click tags column to sort
the list sorts
```

### Actual behavior

```console
click sort on tags column
nothing happens
```

### Environment data

PSU: 3.5.5
Nested IIS

**Comment by adamdriscoll** [comment]
- v4 - Removed the ability to sort this column
- v5 - Same but added the ability to filter by tag.
