### ISSUE TITLE
Document -ArgumentList for New-UDDynamic

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#1792]
### Summary of the new feature / enhancement

In the API section of "Dynamic Regions" it mentions that New-UDDynamic has a parameter called ArgumentList which can be used to pass values to the region.

There aren't any examples to show how to do this (and there's no matching parameter in Sync-UDElement).

### Proposed technical implementation details (optional)

I'd like to see an example of using -ArgumentList with a dynamic region, especially if you can pass arguments when calling Sync-UDElement.

**Comment by DataTraveler1** [comment]
@MikeShepard - Below is an example which demonstrates how to use the ArgumentList parameter with New-UDDynamic. This parameter does not appear to be updated when **Sync-UDElement** is invoked. I will proceed to closure on this but please comment if you have further concerns. I have also submitted this change to @adamdriscoll for the online documentation so we should see this there in the future.

```
$Page1 = New-UDPage -Name 'Page1' -Content {
        New-UDDynamic -Id 'dynamic_01' -ArgumentList @('example of', 'arguments list') -Content {
        New-UDTypography -Text "This is an $($ArgumentList[0]) an $($ArgumentList[1]) in a UDDynamic"
    }
}

$Page2 = New-UDPage -Name 'Page2' -Content {
        New-UDDynamic -Id 'dynamic_02' -ArgumentList @((Get-Random -Minimum 1 -Maximum 6),(Get-Random -Minimum 6 -Maximum 11)) -Content {
        New-UDTypography -Text "Drew random numbers $($ArgumentList[0]) an $($ArgumentList[1]) at $(Get-Date)"
        New-UDButton -Text 'Reload Date' -OnClick { Sync-UDElement -Id 'dynamic_02' }
    }
}
    
New-UDDashboard -Title 'Issue #1792' -Pages (
        $Page1,
        $Page2
)
```

Page1 is the simple direct example which I included in my documentation change request. However, Page2 is here to demonstrate more clearly that the Sync-UDElement command does not update the argument list. It is static.

![image](https://user-images.githubusercontent.com/537287/206482831-85b4247e-8ef3-4ac0-ae4a-f774daf1a3c7.png)

###### figure shows Page1 from the example code

Note for anyone else seeing this, it is possible to submit your own documentation change requests at https://github.com/ironmansoftware/universal-docs

**Comment by MikeShepard** [comment]
The documentation of the feature (as-is) makes sense, but it seems like adding an -ArgumentList parameter to sync-udelement would be a huge win and tie in with the new-uddynamic really well.  
Currently, I'm putting data in a session variable, syncing the dynamic and in the dynamic I read the session variable.

Adding an -ArgumentList removes a lot of that flow and makes it super-easy.
