### ISSUE TITLE
Single server is not subscribed to the "all" Hangfire queue

### ISSUE THREAD

**Issue by realslacker** [ironmansoftware/powershell-universal#1800]
### Steps to Reproduce

I have a single PSU server configured with the intention to create a cluster of servers. Currently there is only one server running jobs. I noticed that when scheduling a job and setting Computer to "All Computers" that the jobs is added to the "all" queue in Hangfire, however my server is not subscribed to the "all" queue.

I am not able to test this functionality with multiple servers.

### Expected behavior

```console
When job targets "All Computers" job should run on all computers even if there is only one computer.
```

### Actual behavior

```console
Job gets stuck in the "all" queue in Hangfire and never executes.
```

### Environment data

PSU 3.5.5

### Visuals

![image](https://user-images.githubusercontent.com/552756/206569667-c7a5d2d8-0365-4e87-b437-41539dda25cc.png)
![image](https://user-images.githubusercontent.com/552756/206569701-4d85e2c8-9c52-4653-bf3e-a7a42d251976.png)
![image](https://user-images.githubusercontent.com/552756/206569781-ef5dbb52-794a-41f3-b79f-ec00fe2d2bd4.png)
![image](https://user-images.githubusercontent.com/552756/206569891-920eb760-771d-4c2a-b83d-f8096d589779.png)

**Comment by adamdriscoll** [comment]
This has been resolved in 3.6.0 already. 🥳
