### ISSUE TITLE
Support for PostgreSQL / other database technologies

### ISSUE THREAD

**Issue by ydhondt** [ironmansoftware/powershell-universal#1801]
### Summary of the new feature / enhancement

Add support for other database technologies next to MSSQL, for example PostgreSQL.

### Proposed technical implementation details (optional)

For Hangfire, there is already support for other database technologies. See the storage section at https://www.hangfire.io/extensions.html . So the implementation would be limited to the PowershellUniversal functionality only.

It looks like most db specific functionality is stored in PowerShellUniversal.SQL.dll . Provide an interface / template / ... so this could be a community effort.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/extra-persistent-database-support/9164/4

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/powershell-universal-v4-0-vision-and-roadmap/8858/16

**Comment by adamdriscoll** [comment]
#2936
