### ISSUE TITLE
PSU Desktop for macOS

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1803]
### Summary of the new feature / enhancement

I can see that the desktop feature are very good and have big potential for the feature.

But it would be great if it also was available for macOS.

For just face it, macOS is something that many people within the IT business are using :)

**Comment by rwidmark** [comment]
@adam maybe for Christmas?

**Comment by rwidmark** [comment]
@adamdriscoll is this possible?

**Comment by adamdriscoll** [comment]
This is possible but would be lumped in with: #2756
