### ISSUE TITLE
UDTableColumn -DefaultSortColumn not working 

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#181]
In latest 1.6b4 nightly build not working (again). It was sometimes fixed, now it just ignores this parameter.
https://forums.ironmansoftware.com/t/bug-udtablecolumn-defaultsortcolumn-not-working/4840/2

**Comment by adamdriscoll** [comment]
Here is the work around: https://forums.ironmansoftware.com/t/bug-udtablecolumn-defaultsortcolumn-not-working/4840/7?u=adam
