### ISSUE TITLE
Add ArgumentList parameter to Sync-UDElement

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1815]
## Feature Request

It would be ideal if we could update/refresh the ArgumentList that was provided to New-UDDynamic when using Sync-UDElement to update an element within the dynamic region of the page. This would require adding the ArgumentList parameter to Sync-UDElement.

## Background

See https://github.com/ironmansoftware/issues/issues/1792

## Acknowledgements

originally suggested by [@MikeShepard](https://github.com/MikeShepard)

**Comment by MikeShepard** [comment]
This would be a huge benefit.

Without this, the pattern is...save a bunch of data in page: variables, sync-udElement, read page: variables.

With this, I can just pass the items to the dynamic region.
