### ISSUE TITLE
Some Cron shcedules throwing Object reference error

### ISSUE THREAD

**Issue by memphisraynz** [ironmansoftware/powershell-universal#1816]
### Steps to Reproduce

Create a Cron schedule using the expression '0 23 * L *' causes a Object reference error.
After updating to the latest version the schedules were removed.

### Expected behavior

```console
Using this as a reference (https://github.com/bradymholt/cron-expression-descriptor) expecting the schedule to be obeyed
```

### Actual behavior

```console
expressions causing a Object reference error.
```

### Environment data

Windows Server 2019
PSU 3.6.1

### Visuals

![firefox_eiGIuDEUJI](https://user-images.githubusercontent.com/9811720/207445387-850ef6da-f85b-4577-ba22-7456093b2479.png)

**Comment by adamdriscoll** [comment]
We use Chronos (part of hangfire) for scheduling. You can accomplish this schedule like this: `0 23 L  * *`

<img width="507" alt="image" src="https://user-images.githubusercontent.com/1256531/213372360-d55cc95d-af8c-42a5-963f-762b15b90bfd.png">

https://github.com/HangfireIO/Cronos
