### ISSUE TITLE
UDTableColumn Sort is reset on third click

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#182]
Apparently there is a disableSortRemove function that may need to be implemented to avoid this.

Basically it should always be like this:

Click 1 => A-Z
Click 2 => Z-A
Any other click starts the sequence from "click1" again.

Additional info:
https://forums.ironmansoftware.com/t/bug-udtablecolumn-defaultsortcolumn-not-working/4840

**Comment by adamdriscoll** [comment]
We need to expose the disableSortRemove property for the table library we are using. This is currently by design: https://react-table.tanstack.com/docs/api/useSortBy

**Comment by adamdriscoll** [comment]
I've added a -DisableSortRemove parameter to New-UDTable.

**Comment by donlent** [comment]
So great! Thanks lot!! :-D
