### ISSUE TITLE
Archive Completed Jobs button stopped working in 3.6.?

### ISSUE THREAD

**Issue by realslacker** [ironmansoftware/powershell-universal#1835]
### Steps to Reproduce

After one of the recent updates the "archive Completed Jobs" button appears to have stopped working. It definitely worked in 3.5.x. Archiving a single job still works, but with over 700 jobs I would rather press a single button.

### Expected behavior

```console
Press "Archive Completed Jobs" and all jobs are archived
```

### Actual behavior

```console
Press "Archive Completed Jobs" and nothing happens
```

### Environment data

PowerShell Universal 3.6.2

**Comment by adamdriscoll** [comment]
Can you share a log file? I'm not seeing this in my lab but I suspect there is a SQL exception being thrown.

**Comment by realslacker** [comment]
It turns out to have been something with my browser, using another browser works.
