### ISSUE TITLE
Sub-menus stuck when left nav is collapsed

### ISSUE THREAD

**Issue by cheilamanJHA** [ironmansoftware/powershell-universal#1838]
### Steps to Reproduce

When in the Powershell Universal Admin page:
1. Collapse left navigation menu using the arrow button at the left-bottom of the screen
2. Hover over any navigation menu option (like "User Interfaces", "Platform", "Settings", etc) to produce the fly-out sub-menus. 
3.  Take any action such as clicking a sub-menu item or clicking in negative space on the page.  Sub-Menu does not disappear. 
4. Hover over any other left menu item and a new sub-menu will appear over the existing one that is already stuck.  This new sub-menu will also be stuck (now there are two sub-menus stuck on the screen).  
![image](https://user-images.githubusercontent.com/101599145/208186556-b303d0b8-059b-469b-8fc7-d2a699bac34d.png)

5. Expand the left navigation menu using the button at the bottom-left of the page.  Now the full menu is visible, but the sub-menus are still stuck on the screen. Only a refresh of the page seems to remove them. 

![image](https://user-images.githubusercontent.com/101599145/208186705-fb070dd6-4f77-4d4c-b127-80ce7d38a277.png)

### Expected behavior

```console
I would expect that the Sub-Menus would be able to be cleared by clicking on one of the items, or clicking in a negative space to remove focus.  Would not expect multiples to remain on screen, especially when main left-menu is expanded.
```

### Actual behavior

```console
Sub-Menus easily expand if the mouse is accidentally (or intentionally) placed over the left-menu area and then they are stuck, blocking your view of the screen.  This is especially frustrating when using the built-in editor.
```

### Environment data

Browsers: 
Chrome and Edge 

PSU version: 
3.6.2
Also occurred on a local installation of 3.5.5

**Comment by adamdriscoll** [comment]
Replaces: #1488
