### ISSUE TITLE
Integrate the React "Hidden" Component to enhance the responsiveness

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#184]
https://forums.ironmansoftware.com/t/responsive-layout-for-udtables-columns-rows-to-show/4853

**Comment by adamdriscoll** [comment]
This has been implemented in 1.5.19 - https://docs.powershelluniversal.com/dashboard/components/layout/hidden

**Comment by donlent** [comment]
@adamdriscoll GENIUS! :-D Thanks, didn't realize that!
It works perfectly and it's sooo much nicer now! 
Thanks a lot for your tremendous support!!
