### ISSUE TITLE
Remove the frame around new-UDTable

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1840]
### Summary of the new feature / enhancement

The frame around the New-UDTable is nice sometimes and sometimes you don't want it to show, I have highlighted it in red in the picture below. I think that the table is wrapped with a UDCard as default?

So some switch with -Hideboard or similar would be perfect :)

![image](https://user-images.githubusercontent.com/76907327/208284143-2c714c2c-7c95-425b-9974-630019555301.png)

Just to be clear it's not the line in the table it's the lines that are around the hole table.

**Comment by rwidmark** [comment]
@adamdriscoll  can't find documentation how to do this. How can I do this? :)

**Comment by rwidmark** [comment]
@adamdriscoll ?

**Comment by adamdriscoll** [comment]
You can use -RemoveCard on New-UDTable
