### ISSUE TITLE
Unable to resolve link from License page

### ISSUE THREAD

**Issue by potatoqualitee** [ironmansoftware/powershell-universal#1847]
https://docs.powershelluniversal.com/licensing leads to https://store.ironmansoftware.com/pricing/powershell-universal which can't be resolved in DNS. If this is just my setup, my apologies!

**Comment by adamdriscoll** [comment]
Whoops. That's an old link. Thanks for the heads up. Should be https://ironmansoftware.com/pricing/powershell-universal
