### ISSUE TITLE
VS Code doesn't launch .xaml files

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#1857]
## Describe the bug
The 'Show Form Designer' button does not work if a file of type .xaml is currently loaded and in focus on VS Code

## To Reproduce

1. Create a .xaml file in your workspace

2. Select the .xaml file in VS Code

3. You should see the button selection showing only '_Show Form Designer_' per below
![image](https://user-images.githubusercontent.com/537287/209451279-8cef3a03-2a85-4e31-9f55-b78f5bbf96a9.png)

4. The .xaml should have the xml file type (orange) icon as shown below
  ![image](https://user-images.githubusercontent.com/537287/209451374-d3df4e65-3fcf-408d-bda2-55e19dacf1ce.png)

5. Select the '_Show Form Designer_' button. PSScriptPad does not launch

## Expected behavior
PSScriptPad should launch when a .xaml file is selected in a workspace and '_Show Form Designer_' is invoked.

## Version
2022.12.1
Windows 10

**Comment by jcalvarezj** [comment]
I'm presenting this problem as well. After installing both the PowerShell and PowerShell Pro Tools extensions and activating with provided license, I am prompted with the `command 'powershell.showWinFormDesigner' not found` error message when trying to open Form Designer with either the button or the Command Palette
