### ISSUE TITLE
Custom API endpoints don't show in Swagger anymore

### ISSUE THREAD

**Issue by schubfre** [ironmansoftware/powershell-universal#1858]
### Steps to Reproduce

Go to https://url.example/swagger and see that there are no more custom endpoints listed. The whole "APIs" header is missing. The first header is now AccessControl, as if there were no custom endpoints at all.

### Expected behavior

```console
Swagger shows custom endpoints under APIs
(see https://docs.powershelluniversal.com/api/endpoints#documenting-apis)
```

### Actual behavior

```console
Swagger doesn't show custom endpoints anymore
```

### Environment data

PSU: 3.6.3 OS: Windows Server 2022

In 3.5.x it was fine

**Comment by adamdriscoll** [comment]
We need to update the documentation. This was changed in 3.6. Endpoints are now in their own definition. 

<img width="346" alt="image" src="https://user-images.githubusercontent.com/1256531/209821946-56d74615-29c4-4bd5-a9c3-f2b190b9872b.png">
