### ISSUE TITLE
TinyMCE - Dark Mode

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#1859]
### Summary of the new feature / enhancement

TinyMCE supports Dark Mode.
![image](https://user-images.githubusercontent.com/11975745/209764590-9ec9e6ed-d428-49d7-a3f7-28718ded0b18.png)

It would be really cool if you could include / allow the usage of the following additionalTinyMCEOptions:
```
$TinyMCEOptions = @{
                    skin = 'oxide-dark'
                    content_css = 'dark'
}
```
Thanks a lot in advance!

### Proposed technical implementation details (optional)

https://www.tiny.cloud/blog/dark-mode-tinymce-rich-text-editor/

**Comment by donlent** [comment]
Dear @adamdriscoll and @mattselle 
Sorry for bothering on that but is that something that could be achieved similar to how you implemented it here?

From your 3.8 release notes:
"- Added -LightTheme\-DarkTheme to New-UDCodeEditor"
https://github.com/ironmansoftware/issues/issues/2016

And if you could in the meantime also implement the following options, that would be awesome!! 😊
![image](https://user-images.githubusercontent.com/11975745/218652512-b0bdec4e-f8bb-4ec7-94fb-d6d66b786ea5.png)
-------------
If it's not planned, could you write a blog post or something on how we can modify existing components?
I know you have some examples here and there:
https://docs.powershelluniversal.com/userinterfaces/dashboards/components/custom-components/building-custom-components
https://blog.ironmansoftware.com/universal-dashboard-custom-components/

But as a non-developer I really do not understand how to adapt these techniques to already existing components in PSU. Is that even possible? Or would I really have to implement a New-UDTinyMCE2 by myself starting from scratch?

Thanks for your clarification on this one as well!

Kind regards,
Don

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/using-tinymce-with-a-stepper-component-in-universal-dashboard/7614/3

**Comment by donlent** [comment]
Hey all!
Sorry just stumbled again over this topic and wanted to share an additional thought with you:
Maybe the implementation should be as transparent like with this issue here:
https://github.com/ironmansoftware/issues/issues/2016

Probably this one makes more sense... if the theme is light => use light mode, if dark => dark...

Would really be cool if this enhancement could make it into an upcoming release... 🤗
Thanks a lot for your efforts!

Best regards,
Don

**Comment by Omzig** [comment]
> Maybe the implementation should be as transparent like with this issue here:

@mattselle; Yes, please tie it to the theme, just like the work i had done on the CodeEditor, the UDCodeEditor works perfectly.

**Comment by adamdriscoll** [comment]
This component has been moved to our modules repo. https://github.com/ironmansoftware/universal-modules/tree/main/Components/TinyMCE

It now supports dark mode and checks the current theme setting to load the proper style. You can install this module with: 

```
Install-Module Universal.Components.TinyMCE
```

**Comment by donlent** [comment]
Thanks a lot @adamdriscoll! Can't wait to implement it in the upcoming PSU Version!
