### ISSUE TITLE
Automation: Disabling processing of trigger scripts on a per-job basis

### ISSUE THREAD

**Issue by tholabrk** [ironmansoftware/powershell-universal#1861]
### Summary of the new feature / enhancement

As a user I want to disable trigger scripts for a single job so that I can run jobs during development without triggering scripts that may send emails, cause actions in external systems, and so forth.

### Proposed technical implementation details (optional)

I'm thinking an option could be set on either the trigger as an exclusion filter or if there was a property on scripts/jobs that cause them to be ignored by trigger scripts.

**Comment by adamdriscoll** [comment]
This might be related to #1941
