### ISSUE TITLE
Update PowerShell Version in Container

### ISSUE THREAD

**Issue by potatoqualitee** [ironmansoftware/powershell-universal#1867]
### Summary of the new feature / enhancement

Hello,
I would like to integrate PSU testing into our CI/CD process to ensure that dbatools continues to work with each change. The new version coming soon, 2.0, requires PowerShell 7.2+ but as far as I can tell, the PSU container is still at 7.1. Any chance that can be upgraded? ref: https://github.com/dataplat/dbatools/issues/8699

:bow

### Proposed technical implementation details (optional)

update to anything above 7.2

**Comment by adamdriscoll** [comment]
universal:latest will be Ubuntu 20.04 and PowerShell 7.3 in version 3.7
