### ISSUE TITLE
not able to acces packaged resources

### ISSUE THREAD

**Issue by ArthurHuyghe** [ironmansoftware/powershell-universal#1870]
If i try to use the get-resource function that is in the documentation it just puts out an none and this causes my program to error out. This is when my script is packaged.
I use VScode and powershell 7.3 on windows 11

my package.psd1:
@{
    Root = 'C:\Users\Arthu\Documents\GitHub\PhotoOrganizer\PhotoOrganizer_v2.ps1'
    OutputPath = 'C:\Users\Arthu\Documents\GitHub\PhotoOrganizer'
    Package = @{
        Enabled = $true
        Obfuscate = $false
        HideConsoleWindow = $false
        DotNetVersion = 'net6.0'
        FileVersion = '2.0.1'
        FileDescription = 'program to sort images based on date taken'
        ProductName = 'PhotoOrganizer'
        ProductVersion = 'v2'
        Copyright = 'Arthur Huyghe'
        RequireElevation = $false
        ApplicationIconPath = 'PhotoOrganizer_v2(gekleurd).ico'
        PackageType = 'Console'
        HighDPISupport = $true
        PowerShellVersion = '7.2.6'
        Resources = [string[]]@("PhotoOrganizer_v2(gekleurd).ico", "sortWindow.xaml", "ProgressWindow.xaml")
    }
    Bundle = @{
        Enabled = $true
        Modules = $true
        # IgnoredModules = @()
    }
}

the get-resource function in my script:
function Get-Resource {
    param($Name)
    
    $ProcessName = (Get-Process -Id $PID).Name
    $Stream = [System.Reflection.Assembly]::GetEntryAssembly().GetManifestResourceStream("$ProcessName.g.resources")
    $KV = [System.Resources.ResourceReader]::new($Stream) | Where-Object Key -EQ $Name
    [System.IO.StreamReader]::new($KV.Value).ReadToEnd()
}

and the call for the function:
$xamlFile = Get-Resource -Name 'sortWindow.xaml'
$xamlFile = $xamlFile.Name
$inputXAML = Get-Content -Path $xamlFile -Raw

**Expected behavior**
it should import the path to sortWindow.xaml and store it in my variable and then get the content of the file

**Screenshots**
![Schermafbeelding 2022-12-30 220116](https://user-images.githubusercontent.com/117371534/210111361-eae352fd-a7df-4fc3-b723-ba50996ea4b7.png)

**Additional context**
im trying to make an app to sort photo's based on date taken

an otheŕ issue i have is that im not able to package for powershell 7.3 but isn't that big of a deal for the moment

**Comment by adamdriscoll** [comment]
@ArthurHuyghe - A file name isn't returned. The actual contents of the file are. Can you try this instead? 

```
$xamlXAML = Get-Resource -Name 'sortWindow.xaml'
```

**Comment by ArthurHuyghe** [comment]
thanks for the quick responds, this indeed fixed it. However it now errors out while trying to load the icon for my gui. I try to acces it as in the documentation:
$bitmap = New-Object System.Windows.Media.Imaging.BitmapImage
    $bitmap.BeginInit()
    $bitmap.StreamSource = Get-Resource -Name "PhotoOrganizer_v2(gekleurd).ico"
    $bitmap.EndInit()
    $bitmap.Freeze()
    $psform.icon = $bitmap
but then i get these errors:
![Schermafbeelding 2022-12-31 101738](https://user-images.githubusercontent.com/117371534/210131704-6cb9e90f-75f0-471c-bbc5-c2b8ae356f70.png)
![Schermafbeelding 2022-12-31 101838](https://user-images.githubusercontent.com/117371534/210131703-92eee908-dad1-40b2-9c62-e735b5cd77d3.png)

I also noticed that the code for the get recourse function is given two times but it isn't the same cod thats given.
the first time the documentations gives this as the code for the function:
function Get-Resource {
     param($Name)
     
     $ProcessName = (Get-Process -Id $PID).Name
     $Stream = [System.Reflection.Assembly]::GetEntryAssembly().GetManifestResourceStream("$ProcessName.g.resources")
     $KV = [System.Resources.ResourceReader]::new($Stream) | Where-Object Key -EQ $Name
     [System.IO.StreamReader]::new($KV.Value).ReadToEnd()
}
and the second time this is the code:
function Get-Resource {
     param($Name)
     
     $ProcessName = (Get-Process -Id $PID).Name
     try 
     {
        $Stream = [System.Reflection.Assembly]::GetEntryAssembly().GetManifestResourceStream("$ProcessName.g.resources")
        $KV = [System.Resources.ResourceReader]::new($Stream) | Where-Object Key -EQ $Name
        $Stream = $KV.Value
     } catch {}

    if (-not $Stream)
    {
        $Stream = [IO.File]::OpenRead("$PSScriptRoot\favicon.ico")
    }

    $Stream
}

the second time this line: [System.IO.StreamReader]::new($KV.Value).ReadToEnd() isn't used. can this be a possible cause for the error?

**Comment by ArthurHuyghe** [comment]
if i use the second code snippet as the get resource function i get these error:
 
![Schermafbeelding 2022-12-31 143356](https://user-images.githubusercontent.com/117371534/210138575-6d874032-5b62-4e91-826a-f71709f30799.png)

this is my code to load the xaml file:
$inputXAML = Get-Resource -Name 'sortWindow.xaml'
    $inputXAML = $inputXAML -replace 'mc:Ignorable="d"', '' -replace 'x:N', 'N' -replace '^<Win.*', '<Window'
    [XML]$XAML = $inputXAML

    $reader = New-Object -TypeName System.Xml.XmlNodeReader -ArgumentList $XAML
    try {
        $psform = [Windows.Markup.XamlReader]::Load($reader)
    }
    catch {
        Write-Verbose -Message $_.Exception
        throw
    }

    $xaml.SelectNodes('//*[@Name]') | ForEach-Object {
        try {
            Set-Variable -Name ('var_{0}' -f $_.Name) -Value $psform.FindName($_.Name) -ErrorAction Stop
        }
        catch {
            throw
        }
    }

**Comment by adamdriscoll** [comment]
They really should be two different functions. I updated the docs to indicate this: https://docs.poshtools.com/powershell-pro-tools-documentation/packaging/package.psd1#bundle-resources-in-a-wpf-application

**Comment by ArthurHuyghe** [comment]
thanks! this fixed the problem, my program works now.
