### ISSUE TITLE
UDStepper: Add -ShowLoading Parameter to buttons

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#1871]
### Summary of the new feature / enhancement

Sometimes there are some tasks that just take some time to complete.
In my case I've built a mail form using Send-MailMessage. Everything works great but when you click on "Finish" it will just take some time until the user lands on the "OnFinish" Step. 

That means that the user could potentially click multiple time on the button which is not a good idea... :-) 

Additionally it just seams that "nothing is happening"...  And since there is no (apparent?) way to access the stepper buttons themselves using Get-UDElement in order to disable them I'm very limited in how I can workaround this issue...

### Proposed technical implementation details (optional)

Please add the -ShowLoading ability at least for the Finish Button of the stepper like for a normal UDButton:
https://docs.powershelluniversal.com/userinterfaces/dashboards/components/inputs/button#loading-button

Thanks a lot!

**Comment by rwidmark** [comment]
Look if you can disable the button until it has been finished.

This is happen as you don't run your code Async.
It's some ways to do that in powershell 7.3 what you then can do is run your code Async and then when they click on the finish button on the stepper you have await there.

So basically what it does is that it run multiple tasks in different threads and then in after clicking finish button you can wait with await for them to finish or not it's up to you.

https://learn.microsoft.com/en-us/dotnet/api/system.management.automation.powershell.invokeasync?view=powershellsdk-7.0.0

You also have
https://learn.microsoft.com/en-us/powershell/module/threadjob/start-threadjob?view=powershell-7.3

**Comment by donlent** [comment]
Hi @rstolpe 
Thank you so much for your inputs. Indeed this is certainly a workaoround. However I don't think that right now you can also disable the buttons because you don't have Id's and therefore you cannot refer to them I think.

Or did you already achieve this somehow? If yes, would you mind to share with me how to do it with the stepper buttons?

Thanks,
Don

**Comment by rwidmark** [comment]
@donlent are you sure you can't just put Id on it?

I'm not on the computer right now, but take a look at MUi I'm guessing the stepper is 
https://mui.com/material-ui/react-stepper/

You can adjust that if you like.
PSU have docs how to do it

**Comment by donlent** [comment]
Sorry for my delayed answer. 🙈
Unfortunately it's not possible somehow. I also tried with the async task but it doesn't really work, at least I wasn't able to achieve success... 

I'm still of the opinion that at least "disabling" the button once clicked should be implemented...

**Comment by donlent** [comment]
Closing this one since I was able to resolve it in a more elegant way:
Instead of executing the code directly in the -OnFinish Session of the Stepper (which indeed is when you press "Finish") I decided to add use a Show-UDModal to present the users a confirmation box. There I can leverage the normal UDButton -ShowLoading function and like that all problems are resolved. 👌

Thanks,
Don
