### ISSUE TITLE
Extension for vs2022 arm64

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#1873]
Visual studio 2022 has offices support for windows 11 arm64 now.
Would be great if your extension also did shave it

**Comment by rwidmark** [comment]
@adamdriscoll  is this possible? :) If the extension is based on .net core 6 or later it should be easy to compile it for ARM :) Also vs2022 latest version has WPF support in ARM ;)

PS 7.3.1 do exist for win11 arm also, installation from MS store but it still exist :)

**Comment by rwidmark** [comment]
@adamdriscoll  got any eta on this? I checked the milestone and it's due.

**Comment by adamdriscoll** [comment]
We have the changes complete for this and are just waiting on hardware to do verification.
