### ISSUE TITLE
Secrets Database Requirement Clarification

### ISSUE THREAD

**Issue by GeoffOrlebeck** [ironmansoftware/powershell-universal#1874]
### Summary of the new feature / enhancement

While trying to use a custom secrets database encryption key I kept getting this error in the UI

![image](https://user-images.githubusercontent.com/82668592/210275082-195723ba-b6ca-43b6-9223-40852565fac6.png)

I don't see any specific guidance in the [Secrets documentation](https://docs.powershelluniversal.com/platform/variables#database). I did finally get it to work by using a leading "=" sign and matching the exact character length of the default encryption password (e.g. 32-characters total). Is this required? If so, I think this should be documented in the Secrets/Variables documentation.

### Proposed technical implementation details (optional)

Document any requirements for Secrets database encryption key in https://docs.powershelluniversal.com/platform/variables#database

**Comment by adamdriscoll** [comment]
I've added an example here: https://docs.powershelluniversal.com/config/settings#generating-an-encryption-key
