### ISSUE TITLE
Swagger tags are not sorted randomly

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1885]
### Steps to Reproduce

when i look at endpoints that i created in swagger they are not alphabetical 

### Expected behavior

```console
alphabetical sort of tags
```

### Actual behavior

```console
random
```

### Environment data

PSU: 3.4.6

**Comment by Omzig** [comment]
@adamdriscoll still not fixed
#reopen

**Comment by adamdriscoll** [comment]
I cannot reproduce this on 3.7.1. Steps to verify: 

endpoints.ps1

```
1..100 | % { 
    $Tag = 65..90 | % { 
        [String][char]$_ 
    } | Get-Random

    New-PSUEndpoint -Url "/$_" -Method @('GET') -Endpoint {
    # Enter your script to process requests.
    } -Tag @($Tag)

}
```

Tags 

```
65..90 | % { 
    $Name = [char]$_ 
    New-PSUTag -Name $Name
}
```

Result

<img width="587" alt="image" src="https://user-images.githubusercontent.com/1256531/211868803-21d568e6-1ab6-421b-8450-9b5738561657.png">

<img width="523" alt="image" src="https://user-images.githubusercontent.com/1256531/211868639-6d13678a-0a10-4d46-9a98-71c3ba97759b.png">

Please let me know if there is something else I can try.
