### ISSUE TITLE
PowerShell Pro Tools not starting

### ISSUE THREAD

**Issue by ArthurHuyghe** [ironmansoftware/powershell-universal#1889]
**Describe the bug**
when i start VScode PowerShell Pro Tools tries to load but it errors out and gives a message:
Failed to workaround VS Code bug. Please see PowerShell Pro Tools output for more information. 
In the logs are a whole bunch of errors. Even reverting back to previous versions but they wont start either.

**Expected behavior**
I want it to properly load and work on start up like it normally did.

**Version**

VS Code version: 1.74.2
Operating System: Windows 11
PowerShell Pro Tools: v2022.12.3

**Logs** 

Please upload a log. Logs are found in $Env:AppData\PowerShellProTools\ by default.
no logs found, only a license. this is the output in VScode:
[bug.txt](https://github.com/ironmansoftware/issues/files/10369431/bug.txt)

**Comment by adamdriscoll** [comment]
I've fixed the issue you are seeing in the log and it will be included in tomorrow's release. If you still see this issue after that, please reopen this issue and we can do some additional debugging.
