### ISSUE TITLE
Endpoint error when receiving invalid JSON

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1894]
### Steps to Reproduce

For an Endpoint that receives JSON data and if that data has a single ' character, then Endpoint returns an error as below.
"The string is missing the terminator: '."

Error is received prior to executing the code in the Endpoint.

### Expected behavior

```console
Invalid JSON could be passed to the script and processed as desired.
```

### Actual behavior

```console
Endpoint is not executed
```

### Environment data

Issue is tested with version 3.2.8 on IIS installation.

**Comment by adamdriscoll** [comment]
This is expected behavior.

**Comment by DataTraveler1** [comment]
@adamdriscoll - In the case where we are using the URL parameter (i.e. :5000/endpoint?string="abc") would it be possible (under the hood) to workaround this scenario by URLing the string (e.g. the single apostrophe is converted to %27)?
