### ISSUE TITLE
Updating to 3.7.0 fails

### ISSUE THREAD

**Issue by schubfre** [ironmansoftware/powershell-universal#1899]
### Steps to Reproduce

Have 3.6.3 installed and try to install 3.7.0. There is also no logfile as indicated in the failed message.

I have also tried a "clean install" where I removed the "C:\ProgramData\PowerShellUniversal" folder with the appsettings.json in it. This also didn't work.

What I haven't tried yet is a "blank install" where I first uninstall the old version.

### Expected behavior

```console
Installation succeeds
```

### Actual behavior

```console
MSI wizard doesn't even start and instantly shows a failed message
```

### Environment data

PSU 3.6.3 -> PSU 3.7.0
Windows Server 2022

### Visuals

![image](https://user-images.githubusercontent.com/28289080/211574008-1169216b-075a-45af-a67f-6c72cc0e497a.png)

**Comment by adamdriscoll** [comment]
@schubfre - There is any issue with the MSI. We have it patched and it's in the release pipeline.
