### ISSUE TITLE
Scripts with parameter ValidateSet causes script to hang

### ISSUE THREAD

**Issue by mwatts-seg** [ironmansoftware/powershell-universal#190]
Create a new script or edit one and add the following at the top: 

```
param(
    [Parameter()]
    [ValidateSet('foo','bar','baz')]
    [string[]]
    $Item
)
```
Trying to run the script, will prompt the user for the entries, but clicking 'Okay/Run' will not close, but the script will be queued with two entries. One waiting for user feedback and the other is queued. Both hang. 

queued | run manualy by wattsm | NaNh NaNm NaNs

**Comment by adamdriscoll** [comment]
Can you let me know what version you are using?

**Comment by mwatts-seg** [comment]
I am using 1.6.0 Beta 4.

**Comment by adamdriscoll** [comment]
This is due to the use of a string[]. If you change this to string, it will work. That said, I'm fixing the issue. 

```
param(
    [Parameter()]
    [ValidateSet('foo','bar','baz')]
    [string]
    $Item
)
```
