### ISSUE TITLE
Upgrade causes account lockout

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1904]
### Steps to Reproduce

- Install 3.6.4
- Login so the admin account is created
- Don't configure anything 
- Upgrade to 3.7.1
- Attempt to login

The problem is that we don't upgrade the admin account to a local account on upgrade. If no authentication was configured, then the login will not work. 

### Work around

- Remove the admin account from the database (LiteDB or SQL) in the identities table
- Downgrade to 3.6.4

### Expected behavior

```console
Login successfully
```

### Actual behavior

```console
Login fails
```

### Environment data

3.7.1

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/upgrading-to-3-7-1-locked-me-out/8415/2

**Comment by jonny190** [comment]
Same issue, but unable to open the DB to edit so essentially locked out of the platform
