### ISSUE TITLE
Improve Ant Design Theme

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#1910]
### Steps to Reproduce

The Ant Design theme makes it hard to read disabled controls. 

### Expected behavior

```console
Easy to see controls.
```

### Actual behavior

```console
hard to see labels.
```

### Environment data

3.7.1

**Comment by donlent** [comment]
I can confirm... :-)
![image](https://user-images.githubusercontent.com/11975745/211815802-f9f1f4e0-ff73-42bf-b664-0e9d66f026f0.png)

Also I have the impression that the font size (no matter if you also specify a header size like h2, h3) is smaller than it was before... Am I wrong?

And as always: Thanks Adam! :-D

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/powershell-universal-3-7-1/8410/7

**Comment by Omzig** [comment]
If i understand this correctly, we are trying to replicate the dashboards theme?

Things i have noticed that are not the same, there are some interesting lines:

Admin Example:
![image](https://user-images.githubusercontent.com/1987296/211838299-47b34610-075b-486a-946e-fc48f55f9604.png)

After:
![image](https://user-images.githubusercontent.com/1987296/211838330-90fd7e54-8fd9-4487-bf60-71f685fc210a.png)

# Colors:
We lost primary/secondary button colors

Admin:
![image](https://user-images.githubusercontent.com/1987296/211838868-ec5913d1-e0bb-4bb6-8739-50a5d9bd6207.png)

After:
![image](https://user-images.githubusercontent.com/1987296/211839236-f897513f-5152-4d9d-82e4-6a79d4562f8a.png)

**Comment by Omzig** [comment]
cannot see toggle in light mode:
![image](https://user-images.githubusercontent.com/1987296/211841116-7f68f68b-b1af-4632-bb6a-99ae36c92e8d.png)

Admin site:
![image](https://user-images.githubusercontent.com/1987296/211841258-59d27e27-b51f-43ee-a8fe-ad33c599b623.png)

**Comment by adamdriscoll** [comment]
@Omzig -That toggle one is weird. This is what my toggle looks like. 

<img width="88" alt="image" src="https://user-images.githubusercontent.com/1256531/211841985-729735d3-2430-47ec-9c5a-cb0e620b45a6.png">

You are just specifying a dashboard without the -Theme switch?

**Comment by Omzig** [comment]
Super minor problem with the scroll bars, they are not themed anymore, but they work ;)

**Comment by Omzig** [comment]
> @Omzig -That toggle one is weird. This is what my toggle looks like.
> 
> <img alt="image" width="88" src="https://user-images.githubusercontent.com/1256531/211841985-729735d3-2430-47ec-9c5a-cb0e620b45a6.png">
> 
> You are just specifying a dashboard without the -Theme switch?

Yes ;)

**Comment by adamdriscoll** [comment]
Something weird is going on. This is how my scrollbars look when using Ant Design. 

<img width="168" alt="image" src="https://user-images.githubusercontent.com/1256531/211845873-373750ef-8166-4952-b80c-ca33bd8e14a5.png">

**Comment by Omzig** [comment]
> 

It is the one on the right when you have 100 items to scroll through in a table:
![image](https://user-images.githubusercontent.com/1987296/211849279-5c9d40d7-65fa-4818-8dc7-6d7e1adb98ba.png)

**Comment by Omzig** [comment]
Something is wrong with the scroll bar now on default theme:

It is hidden and you cannot seem to find the tag/pill/dragger:

![image](https://user-images.githubusercontent.com/1987296/212090778-f414748e-7fa6-422e-b9fe-957fdb22f30b.png)

Hover:
![image](https://user-images.githubusercontent.com/1987296/212090875-cff4258f-c09c-4e95-8d84-1a4faddc321a.png)

**Comment by adamdriscoll** [comment]
Closing. Will open issues for individual problems.
