### ISSUE TITLE
Show-UDToast: Icon does not show

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#1913]
### Steps to Reproduce

When you specify -Icon for a Toast it shows an empty region but not the actual icon...

`Show-UDToast -Message "This toast schould show an Icon but does not... :-)" -Icon (New-UDIcon -Icon 'FileUpload') -Duration 3000 -BackgroundColor "#80ff80" -MessageSize 20`

![image](https://user-images.githubusercontent.com/11975745/211814998-e475f967-9511-4b51-8cff-97aaba8e3058.png)

### Expected behavior

```console
Show-UDToast should show the specified Icon
```

### Actual behavior

```console
Show-UDToast does not show any Icon but only a "space" in front of the message text.
```

### Environment data

3.7.1

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/new-udicon-solid-new-udtextbox-onvalidate-new-udalert-as-toast-and-more/8510/1

**Comment by donlent** [comment]
@adamdriscoll @mattselle 
Hey guys, I think I discovered an important fact for you.
It seems that Show-UDToast expects just a String for the Icon parameter and not an Icon Object itself.

So for example this won't work

`Show-UDToast -Message "This toast schould show an Icon but does not... :-)" -Icon (New-UDIcon -Icon 'Warning') -Duration 3000 -BackgroundColor "#80ff80" -MessageSize 20`

but this will

`Show-UDToast -Message "This toast schould show an Icon but does not... :-)" -Icon "Warning" -Duration 3000 -BackgroundColor "#80ff80" -MessageSize 20`

So the issue is resolved? Unfortunately not yet. :-)
There must be some other problems with the available Icons that you can use here.
Because in my original example I wanted to use the "FileUpload" Icon and indeed, this will again result into a blank placeholder, even if you use the String as argument.

Hope that helps fixing the issue and thanks again for all your efforts!

**Comment by mattselle** [comment]
Hi @donlent 
I am currently working on making the -Icon take in both a string like it currently does and a UDIcon. If you do a complete fontawesome string for the FileUpload it should work (-Icon 'fa fa-file-upload'). I will look into why its not parsing that correctly as well.

Show-UDToast -Message "This toast schould show an Icon but does not... :-)" -Icon 'fa fa-file-upload' -Duration 3000 -BackgroundColor "#80ff80" -MessageSize 20

**Comment by donlent** [comment]
Hi @mattselle 
Ah that's so cool to know! :-D Thanks a lot! I mean that means that it already works if you know how... ;-)

Sorry for the question though but since you're re-designing this, would it be possible to also use the other variants of the icons? Right now only "fa-solid" works... but there is "fa-light", "fa-thin" etc...

Obviously it would be great if in the end it would be consistent throughout the product. Right now I think that most of the time you have to specify the UDIcon as object...

THANK YOU!

**Comment by Viajaz** [comment]
@mattselle @adamdriscoll 
This problem occurs in 4.0.7, it doesn't work:
```powershell
Show-UDToast -Message 'Test Toast 1' -Icon 'exclamation' -Duration 5000
Show-UDToast -Message 'Test Toast 2' -Icon (New-UDIcon -Icon 'exclamation') -Duration 5000
Show-UDToast -Message 'Test Toast 4' -Icon 'fa-exclamation' -Duration 5000
Show-UDToast -Message 'Test Toast 5' -Icon 'fa fa-exclamation' -Duration 5000
Show-UDToast -Message 'Test Toast 5' -Icon 'fas fa-exclamation' -Duration 5000
```

**Comment by adamdriscoll** [comment]
I see it too.

**Comment by mattselle** [comment]
Sorry about that, It looks like when we reverted the fontawesome pro changes it affected the toast as well. I just put in a PR that will fix this
