### ISSUE TITLE
Navigating to a Get-UDPage you lose navigation

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1938]
### Steps to Reproduce

i am experiencing a problem with the nav menu loading when only using Get-UDPage link

### Expected behavior

```console
show navigation items when only using get-udpage
```

### Actual behavior

```console
blank nav menu
```

### Environment data

PSU: 3.7.3

### Visuals

Actual:
![image](https://user-images.githubusercontent.com/1987296/212129274-5bff05e4-4435-42b0-8551-b4d1b82a5ad2.png)

Expected:
![image](https://user-images.githubusercontent.com/1987296/212129233-6053c391-e408-4041-b59f-f2b34b842475.png)

Code:
Add a new-UDPage first, then add Get-UDPage's
```powershell
    New-UDPage -Name 'Home' -Content{"TEST"} # Shows navigation items when you are on this page
    Get-UDPage -Name 'Products' ## Navigating to this link will cause the menu navigation to go blank
```

**Comment by Omzig** [comment]
```powershell
$Navigation = @(
    New-UDListItem -Label 'Home' -Icon (New-UDIcon -Icon Home) -OnClick {
        Invoke-UDRedirect -Url '/home'
    }
    New-UDListItem -Label 'Products' -Icon (New-UDIcon -Icon Home) -OnClick {
        Invoke-UDRedirect -Url '/products'
    }
)

New-UDDashboard -Title 'PowerShell Universal' -Navigation $Navigation -Theme (Get-UDTheme -Name 'MaterialDesign')  -Pages @(
    New-UDPage -Name 'Home' -Content{"TEST"} #nav works when viewing this page
    Get-UDPage -Name 'Products' #nav does not work when viewing this page
    Get-UDPage -Name 'tool'
)
```

**Comment by adamdriscoll** [comment]
You're the second person to report this but I can't reproduce it. 

```
$Navigation = @(
    New-UDListItem -Label 'Home' -Icon (New-UDIcon -Icon Home) -OnClick {
        Invoke-UDRedirect -Url '/home'
    }
    New-UDListItem -Label 'Products' -Icon (New-UDIcon -Icon Home) -OnClick {
        Invoke-UDRedirect -Url '/products'
    }
)

New-UDDashboard -Title 'PowerShell Universal' -Navigation $Navigation  -Pages @(
    Get-UDPage -Name 'Products' #nav does not work when viewing this page
    Get-UDPage -Name 'tool'
)
```

<img width="251" alt="image" src="https://user-images.githubusercontent.com/1256531/212192797-9c1d6cd0-daa3-4f68-a4f4-a0a01dac575e.png">

**Comment by adamdriscoll** [comment]
It looks like blank -LoadNavigation parameters are being added some how to the page. If you go to Settings \ Configurations \ Dashboards \ <dashboard> \ pages \ <page>.ps1, you should be able to remove it in the meantime.
