### ISSUE TITLE
Rate limits fails "Object not set"

### ISSUE THREAD

**Issue by tkmoeller** [ironmansoftware/powershell-universal#1946]
### Steps to Reproduce

In 3.7.2 I reported an issue with rate limits that should have been solved in 3.7.4, but I have just installed 3.7.5 and tried creating a limit. Unfortunately that still isn't possible.

### Expected behavior

```console
Not available.
```

### Actual behavior

```console
Not available.
```

### Environment data

PSU 3.7.5

### Visuals

![Screenshot 2023-01-16 at 14 06 56](https://user-images.githubusercontent.com/26480631/212686098-ce3d0b3a-283e-42ca-a8be-c1a3dd58172a.png)
![Screenshot 2023-01-16 at 14 06 49](https://user-images.githubusercontent.com/26480631/212686112-88bd9892-eef1-44c7-bef0-7e43ce338a6f.png)

**Comment by adamdriscoll** [comment]
@tkmoeller - Can you please share a log file? There should be a stack trace error message that will provide the location of the exception.

**Comment by tkmoeller** [comment]
@adamdriscoll yes, here you go.

[log20230117.txt](https://github.com/ironmansoftware/issues/files/10431312/log20230117.txt)
