### ISSUE TITLE
Add a property to customize the 'Select a definition' dropdown

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1951]
### Summary of the new feature / enhancement

all custom endpoints show up in the 'endpoints' definition. Is it possible to add a field to the settings that allows us to customize this value in the dropdown?

"CRM Data Warehouse" would be one that i would like to use instead of the default 'endpoints'

### Proposed technical implementation details (optional)

Input:
![image](https://user-images.githubusercontent.com/1987296/213208708-e73a46bf-a043-486c-b72b-8f9afd4ac3a6.png)

Output:
![image](https://user-images.githubusercontent.com/1987296/213208063-ae4fc524-7794-4eb2-bd57-16bbfa2d4003.png)

**Comment by adamdriscoll** [comment]
@Omzig The configuration will be a bit different (appsettings.json) because we need to configure the swagger docs during app startup but you will be able to set the name, description and URL.

**Comment by adamdriscoll** [comment]
Now that I think about it though, it would be cool to be able to specify multiple custom docs. Let me see if we can configure this at runtime rather than at startup.

**Comment by Omzig** [comment]
> Let me see if we can configure this at runtime rather than at startup.

you're da best, ty, you have no idea how much this would help organize our different api's
this will keep us from having to spin up more than one instance of PSU when we get overrrun with api's

**Comment by adamdriscoll** [comment]
Workaround here:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1093#issuecomment-964622538

I'll give it a go.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/swagger-categories-for-api-endpoints/8632/2

**Comment by adamdriscoll** [comment]
You'll be able to assign APIs to docs and define object types directly in the PSU console. 


<img width="265" alt="image" src="https://user-images.githubusercontent.com/1256531/217939854-6b278f66-d3a5-45e4-9134-e21394b1b5f2.png">


<img width="297" alt="image" src="https://user-images.githubusercontent.com/1256531/217939794-8fe93c75-252e-493e-bb88-11cbf071c3a1.png">

<img width="819" alt="image" src="https://user-images.githubusercontent.com/1256531/217940058-053b5acf-c4a1-4176-9673-cb143353abf7.png">

You'll also have control over roles and authentication for these endpoints.
