### ISSUE TITLE
Enhance Table Performance with alot of rows 100+

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1952]
### Summary of the new feature / enhancement

https://www.reddit.com/r/reactjs/comments/td6wq5/react_mui_extremely_slow_performance/

i found where they were talking about how the table renders and things that can be done to make it faster when doing filters and such.

currently when i try to use a filter, it rerenders very slow

**Comment by Omzig** [comment]
Server side paging i think is the answer to this if it was working 100%

**Comment by adamdriscoll** [comment]
Server-side is the answer. UDDataGrid also implements virtualization so it should render faster than a table.
