### ISSUE TITLE
New-UDIcon are solid by default

### ISSUE THREAD

**Issue by alexsmid** [ironmansoftware/powershell-universal#1962]
### Steps to Reproduce

When creating a new icon user New-UDIcon, they are created as "solid" by default.
Using the "-Solid" parameter does nothing.
This was discussed here:
https://forums.ironmansoftware.com/t/icon-solid-version/8029
And here:
https://github.com/ironmansoftware/issues/issues/1730#issuecomment-1319833119

### Expected behavior

```console
To get "Regular" version of the icon
```

### Actual behavior

```console
Always getting the "Solid" version of the icons, and never able to get the "Regular" version
```

### Environment data

3.7.7

**Comment by Omzig** [comment]
some of the icons are PRO on regular, many of the solids are free:

![image](https://user-images.githubusercontent.com/1987296/213814723-8468eed1-3349-4083-ad1a-e70e4613125d.png)

![image](https://user-images.githubusercontent.com/1987296/213814832-ad05cc49-f54e-445e-8c0d-d5d2c1ccd4e0.png)

**Comment by Omzig** [comment]
There are some that are missing:

![image](https://user-images.githubusercontent.com/1987296/213815170-b779f240-a86c-4f8d-abef-67baafa35bed.png)

![image](https://user-images.githubusercontent.com/1987296/213815198-04356105-e371-4797-a6f4-244c5762b163.png)
