### ISSUE TITLE
Add system log viewer

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1963]
### Summary of the new feature / enhancement

As a user, I want visit the logs in the site so that i do not have to go to the hard drive and find them. 
- some users do not have access to the HD

### Proposed technical implementation details (optional)

Add a system logs section
https://dev.psu.jhacorp.com/SiteName/admin/settings

Log file location that i am interested in:
- E:\src\psu\NestedSiteFolder_data\PowerShellUniversal\\[currentLog].txt

**Comment by adamdriscoll** [comment]
If you go to the diagnostics tab under general settings you can download the logs. There is also a live log viewer.
