### ISSUE TITLE
Re-Open: UDStepper: Add -StepIcon option

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#1967]
### Steps to Reproduce

Sorry guys I have to re-open this one.

All details here:
https://github.com/ironmansoftware/issues/issues/1881

Apparently it has been added to 3.7 but it's not. At least the parameter isn't there yet. :-)

### Expected behavior

```console
-StepIcon (or whatever you've called it) should be available
```

### Actual behavior

```console
-StepIcon is not available
```

### Environment data

3.7.7

**Comment by adamdriscoll** [comment]
@donlent  Matt just let me know this didn't make it into 3.7 but it is finished for 3.8.

**Comment by donlent** [comment]
Dear @adamdriscoll @mattselle 
Sorry for asking again but are you sure that this was added to 3.8?
I just read the nightly build release notes and there's nowhere a reference to this...
Maybe it's there but it's just the info that is missing in the release notes?
Thanks, Don

**Comment by mattselle** [comment]
Hi,

It looks like we had a bad merge and the release note got merged over. I will add that back in but I just double checked and New-UDStep has -Icon on it. I will get the release note put back in.

**Comment by donlent** [comment]
Hi @mattselle 
Ah super, thank you very much for that!
Wish you a very good day. 
Take care, Don
