### ISSUE TITLE
Dashboard Pages is not working correctly 

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1982]
### Steps to Reproduce

- saving sometimes overwrites code in another page.ps1
- adding a page, adds it to the bottom of the list, but when selecting it, it does not select the correct page
- the page menu works if you keep it to just a few pages

### Expected behavior

```console
a working page editor
```

### Actual behavior

```console
saves do not work
get content from other pages saved in the wrong page
selecting page does not show the expected page
```

### Environment data

PSU: 3.7.7

**Comment by Omzig** [comment]
@adamdriscoll, bump

**Comment by Omzig** [comment]
ugg, we have reverted to editing pages in https://dev.psu.domain.com/siteName/admin/settings/configurations.

Lost more code, reverting to old github branch copy.

**Comment by adamdriscoll** [comment]
I reproduced this once but haven't found a root cause. Still investigating. Can you let me know how many pages you have?

**Comment by Omzig** [comment]
we just had a save over a page in /configurations, so this issue is not exclusive to the pages tab
https://github.com/ironmansoftware/issues/issues/1992

**Comment by adamdriscoll** [comment]
@Omzig - I'm running a nightly build with a "fix" for this. I have certainly reproduced this issue a few times but it's definitely not consistent. It certainly feels like some sort of timing issue that results in the wrong ID updated. 

The change adjusts how we load data and mount the editor in both the configuration page and the dashboard pages editors. 

The problem with both of these components is that they allow you to quickly change between editors and it appears that state is not being updated properly in the mounted editors when that happens. I don't see this behavior in scripts or APIs where it's harder to quickly change between editors. The change effectively causes the admin console to full query the data from the server and render the editor when changing between files.  After this change, I haven't seen the issue again. I'll continue to test but if you have time to test a nightly, I will let you know when it's done.

**Comment by Omzig** [comment]
@adamdriscoll  this version? 3.7.8 (4001621254)

the reason i ask, is because i don't see it in the change log on this ver

**Comment by adamdriscoll** [comment]
Grab this one: 4008592854

https://imsreleases.blob.core.windows.net/universal-nightly/4008592854/PowerShellUniversal.3.7.8.msi

**Comment by Omzig** [comment]
> Grab this one: 4008592854
> 
> https://imsreleases.blob.core.windows.net/universal-nightly/4008592854/PowerShellUniversal.3.7.8.msi

testing

**Comment by Omzig** [comment]
> Grab this one: 4008592854
> 
> https://imsreleases.blob.core.windows.net/universal-nightly/4008592854/PowerShellUniversal.3.7.8.msi

It happened again :( 
We had steps.ps1 get saved over step.ps1
new version = fail

**Comment by adamdriscoll** [comment]
Bummer. Ok. I will continue to try to reproduce this.

**Comment by Omzig** [comment]
> Bummer. Ok. I will continue to try to reproduce this.

If it helps any, we are up to 12 pages in this 1 dashboard

- manual workflow
  - in editor save
  - navigate to dashboard to look at logs
  - navigate back to /configurations and edit file
  - click on button to make something happen
  - fix the something in the editor
  - navigate back to dashboards and restart dashboard
  - repeat over and over (somewhere in here things start to get confused)

**Comment by Omzig** [comment]
> Bummer. Ok. I will continue to try to reproduce this.


@adamdriscoll !!!!!

NEW DEVELOPMENT:
+ Save Changes commit button is also causing the issue at the top of the screen
  - the new lines in Steps.ps1 made the entire file to be saved in Step.ps1

**Comment by adamdriscoll** [comment]
As a stop gap, I changed the pages editor to behave like other editors in the console with its own page. 

![image](https://user-images.githubusercontent.com/1256531/214795600-2ea376b0-b44c-4223-9472-b4d38c9b10b6.png)

Although this isn't the UX I desire, I hope it gets us around the current saving-over-other-files issue because that seems way worse of a problem. 

It's in nightly build 4011105001

**Comment by Omzig** [comment]
testing

**Comment by Omzig** [comment]
@adamdriscoll, FYI this editor does it also, yesterday we had the page incorrectly save while using this editor and not the pages editor:
![image](https://user-images.githubusercontent.com/1987296/214852379-cb7a1fe3-859f-48e6-b380-dd454ce8e221.png)

**Comment by adamdriscoll** [comment]
@Omzig Yep. I'll update that one next if this works for you.

**Comment by Omzig** [comment]
> @Omzig Yep. I'll update that one next if this works for you.

Testing

**Comment by Omzig** [comment]
@adamdriscoll, seems to be some success...

1. Edited all the pages, using 2 different tabs, one to copy from and one to edit and save
2. commit 
3. PR
4. Merge
5. edit all the pages again
6. commit
7. PR
8. Merge

no wonky saves

So far, i would say this is closed..... for now ;)

**Comment by adamdriscoll** [comment]
@Omzig - Awesome. Thank you so much for all the help with this. I'll look at the configuration page for a similar solution. We have 1 outstanding issue I'd like to resolve (aside from the editing issues) in 3.7.8. Once we have a handle on that, we'll be releasing it. Let me know if anything crops up on your end.

**Comment by Omzig** [comment]
@adamdriscoll, installed 3.7.8, we saved a script from admin/dashboards/x/pages/xx and it did not save anything at all, when we went back in it was blank. we are 99% sure we hit save.

#reopen

**Comment by adamdriscoll** [comment]
😖

**Comment by Omzig** [comment]
@adamdriscoll, did you make any changes on this in 3.7.9 that we need to watch for?

**Comment by Omzig** [comment]
@adamdriscoll, 3.7.9 lost the pages menu items:
![image](https://user-images.githubusercontent.com/1987296/215516747-eb7be4e9-331b-457a-a5f9-23a0389bff68.png)

**Comment by adamdriscoll** [comment]
@Omzig - We didn't make any changes to this in 3.7.9. Still looking into the issue. Very strange that your pages menu is missing....

**Comment by Omzig** [comment]
I have not noticed this in 3.8.x, closing issue.
