### ISSUE TITLE
in code editor allow "Format Document" to work

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1983]
### Summary of the new feature / enhancement

it would be nice if format doc would work in the editor in the admin site, 4 spaces would be nice for a tab

### Proposed technical implementation details (optional)

![image](https://user-images.githubusercontent.com/1987296/214392634-81c67e9d-7779-4eb2-86ce-36b26d00bf8a.png)

**Comment by adamdriscoll** [comment]
If you have PSScriptAnalyzer installed on the PSU server, this will work.

**Comment by Omzig** [comment]
OH MY GOODNESS, you are da BEST! confirmed
