### ISSUE TITLE
file change on HD does not show up in admin site 

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1984]
### Steps to Reproduce

when i change a file on the hard drive the pages\page.ps1 file does not reflect in the admin site till after an app pool recycle #sometimes

### Expected behavior

```console
show file on HD that was changed manually
```

### Actual behavior

```console
displays cached version of the file
```

### Environment data

PSU: 3.7.7 - 3.8.12
IIS: Nested

### Workaround
Recycle App Pool

**Comment by adamdriscoll** [comment]
I'm actually seeing this sometimes as well. For example: I install a license.ps1 file and the license it not picked up.

**Comment by Omzig** [comment]
> I'm actually seeing this sometimes as well. For example: I install a license.ps1 file and the license it not picked up.

Sometimes my format is super bad, so i will open it up on the HD in vscode and do a format document to get the lines to look nice, and then i have to restart the app pool to get it to show up in the website

**Comment by Omzig** [comment]
this will keep me off the HD: https://docs.powershelluniversal.com/development/editor#formatting

**Comment by Omzig** [comment]
I had to revert a file change and then i had to recycle the app pool to see my change undo

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/dashboard-pages-not-showing-changes-in-ui/9083/2

**Comment by Omzig** [comment]
I just changed 10 files with http:// to https:// in the dashboard on the HD directly on the server using vscode find and replace, the psu does not know that the files changed, i am in edit mode for git

**Comment by adamdriscoll** [comment]
We need to grab some logs from your environment on debug. This find\replace scenario was the exact one I tested when checking on this fix.

**Comment by Omzig** [comment]
1. Edit something on the HD, boom, it refreshes in the PSU editor.
2. Edit something in the editor, hit save, the file on the HD gets updated, vscode sees the change.
3. Edit something in vscode on the HD, save
4. PSU stops watching the file for changes

Emailing you the logs

**Comment by adamdriscoll** [comment]
Interesting. So if you edit it with something besides VS Code it reloads it?

**Comment by Omzig** [comment]
> Interesting. So if you edit it with something besides VS Code it reloads it?

if you edit something on the HD with notepad, then it reloads... then, go into the PSU editor, and edit the same file, then edit the file on the HD, psu will stop watching the files to reload

if you want a quick call and watch me, you can send me an invite ;)

**Comment by Omzig** [comment]
vscode = a text editor on the server

**Comment by adamdriscoll** [comment]
Retry has been implemented.
