### ISSUE TITLE
Settings | Configurations | Edit ps1 file not saving sometimes

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1992]
### Steps to Reproduce

randomly the save button does NOT save the file even when it says it did

unknown trigger that cause the file to not save...
restarting the dashboard might have something to do with it?
- edit dashboard .ps1 file in configurations
- go to dashboard, click the power and restart it
- edit dashboard .ps1 file in configurations
- go to dashboard, click the power and restart it
- edit dashboard .ps1 file in configurations
- go to dashboard, click the power and restart it
- edit dashboard .ps1 file in configurations
- go to dashboard, click the power and restart it

somewhere in this pattern it stops saving

### Expected behavior

```console
a saved file
```

### Actual behavior

```console
nothing saved
```

### Environment data

PSU: 3.7.7

**Comment by Omzig** [comment]
@adamdriscoll, bump

**Comment by Omzig** [comment]
these are related https://github.com/ironmansoftware/issues/issues/1982

**Comment by Omzig** [comment]
@adamdriscoll, reworking our lost pages is getting annoying. We have had to restore lost pages and lost changes more than 5 times today.

**Comment by adamdriscoll** [comment]
I understand. I am actively working getting to the bottom of it.

**Comment by Viajaz** [comment]
I think I've seen issues like this before as well, it's one of the reasons we modify PSU files out-of-band using VS Code etc.

**Comment by Omzig** [comment]
> I think I've seen issues like this before as well, it's one of the reasons we modify PSU files out-of-band using VS Code etc.

I have seen this also with the vscode plugin, i just have not reported it, because we have been working on other things
