### ISSUE TITLE
Tab Completion of scoped variables doubles the scope

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#1998]
### Steps to Reproduce

I am experiencing a problem with tab completion when i use things like $env:User[tab], i think it should not double my $env:

### Expected behavior

```console
$env:thing
```

### Actual behavior

```console
$env:$env:thing
```

### Environment data

PSU: 3.7.7

### Visuals

![2023-01-25_14-53-30](https://user-images.githubusercontent.com/1987296/214688961-b9782b1f-279e-40e1-a2b6-154be628d469.gif)

**Comment by MikeShepard** [comment]
Same thing with $page:, $Session:, and $Cache:
