### ISSUE TITLE
Edit mode pauses Git Sync

### ISSUE THREAD

**Issue by timosemmler** [ironmansoftware/powershell-universal#2007]
### Summary of the new feature / enhancement

As described in my [post](https://forums.ironmansoftware.com/t/git-synchronization-failed-cannot-access-the-file/8459/9), the editor mode caused the git sync to stop running.

I would like to have more information about when the edit mode is activated and what effects this has on other processes.

### Proposed technical implementation details (optional)

This "error" should be avoided in my opinion with one or more options:

I can currently think of the following possibilities, but maybe you have more/better ones?

- If git is used and you are in edit mode, then a clear warning (yellow exclamation mark with info text when the mouse hovers over it?) should be displayed to indicate that the synchronization is paused until saved or cancelled
- Add a setting (global) that allows the edit mode to exit automatically after X hours/minutes and discard changes. In my case I only noticed after one night that the mode was still active
  - We will probably have several people working with PowerShell Universal, this is the only way to make sure that no one forgets to exit the mode
- Adding the information in the documentation in the configuration section git sync (or did I just miss that?)

**Comment by adamdriscoll** [comment]
Good feedback. This is by design, but I agree that this needs to be clearer.

**Comment by timosemmler** [comment]
Thanks for including this directly as part of a milestone, I think it's awesome!

Over the weekend, I thought about how to implement the whole thing for the HA setup as well. 

With a **LoadBalancer** for the **HA configuration** it would mean that e.g. 4 users are distributed on say 2 systems.

2 on ServerA
2 on ServerB

If now a user on ServerB activates the edit mode, the users on ServerA can not see this. So it should also be possible somehow that a potentially built in warning message checks not only the local system, but all systems in the cluster and issues the status based on that. Do you agree so far or is that rather not what you would do?

_Furthermore, it would also make sense that if a user activates edit mode on any system, no one else can make changes, simply to avoid merge conflicts._

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/git-synchronization-failed-cannot-access-the-file/8459/10

**Comment by adamdriscoll** [comment]
We are working towards a much better experience here. While not all requirements of this issue will be completed for 3.8, we have made some significant improvements. 

## Notification 

There will now be a notification about the pausing of pulls while editing. 

![image](https://user-images.githubusercontent.com/1256531/224099565-e07b896f-aa15-4e6d-a796-e0801eabafda.png)

## Better Save Changes Dialog

The save changes now shows each change and a diff viewer. 

![image](https://user-images.githubusercontent.com/1256531/224099778-016d0dad-d89c-42ae-be18-81a1bebb4b21.png)

## Merge Conflict Support

PSU will support merge conflict resolution directly in the browser. 

![image](https://user-images.githubusercontent.com/1256531/224098862-46d8a9d0-ba2c-4bfc-8d63-b88085b5cd1a.png)

## Repository History

Full repository history is now browsable within PSU. 

![image](https://user-images.githubusercontent.com/1256531/224100053-a868ad23-4b1b-4e9e-94ed-10279a58f29e.png)

## Sync Status 

Sync status has been improved to include only the currently status for all nodes. 

![image](https://user-images.githubusercontent.com/1256531/224100251-b080165d-220f-4984-b1bb-35879dfceffa.png)
