### ISSUE TITLE
Add Server up time if available to dashboard

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2021]
### Summary of the new feature / enhancement

As a psu admin, I want to know when my server was last rebooted so that i can compare the service up time. 

### Proposed technical implementation details (optional)

![image](https://user-images.githubusercontent.com/1987296/215508340-178f5c95-01af-433b-ba6b-82429105667e.png)

```powershell
Function Get-ServerUptime {
    Param (
        [Parameter(Mandatory=$true)]
        [string]$ComputerName
    )
    $Uptime = (Get-CimInstance -ClassName Win32_OperatingSystem -ComputerName $ComputerName).LastBootUpTime
    $Uptime = (Get-Date) - $Uptime
    $Uptime
}

Get-ServerUptime -ComputerName localhost
```

**Comment by adamdriscoll** [comment]
Will be available once #1021 is done. We won't bake this in.
