### ISSUE TITLE
Scheduler Parameters are empty during edit

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2023]
### Steps to Reproduce

https://forums.ironmansoftware.com/t/error-in-scheduler-parameters/8560/2

### Expected behavior

```console
Parameters have values
```

### Actual behavior

```console
Parameters are empty
```

### Environment data

3.7.9

**Comment by aayala-arsys** [comment]
And, as aditional info, if you click Save button all values set to null on ".universal/schedules.ps1" file.

Example work schedule:
`New-PSUSchedule -Script "Scripts\test.ps1" -TimeZone "Europe/Madrid" -OneTime '2023-03-01T07:37:00.0000000Z' -param1 'test1' -param2 'test2' -param3 $true -Name "Test Param purposes" -Paused`

Same schedule after edit and save button:
`New-PSUSchedule -Script "Scripts\test.ps1" -TimeZone "Europe/Madrid" -OneTime '2023-01-31T07:50:00.0000000Z' -param1 '' -param2 '' -param3 $False -Name "Test Param purposes" -Paused`

note: param1 and param2 are a [string]  variables without default value, param3 is a [bool] variable with $false as default.

**Comment by adamdriscoll** [comment]
Moving to 3.8 because I want some more time with this one. It's a bit of a core problem with how the PSU admin console works.

**Comment by adamdriscoll** [comment]
Another note from another user about this issue: 

>Running 3.7.14. If a script is created that has param() block, a new scheduled job will show those as part of creating the scheduled job.

>How to reproduce the bug...If you create a scheduled job for a script that is missing a param() block and then add it after the schedule has been created, when editing it the param fields do not show up.

**Comment by aayala-arsys** [comment]
Hello, aparently not resolved in 3.8.1 neither 3.8.2
