### ISSUE TITLE
Executables created with PowerShell Pro Tools are detected as virus

### ISSUE THREAD

**Issue by hasufell** [ironmansoftware/powershell-universal#203]
**Describe the bug**

https://downloads.haskell.org/~ghcup/tmp/bootstrap-haskell-8.exe

was built from https://gitlab.haskell.org/haskell/ghcup-hs/-/blob/windows-support/bootstrap-haskell.ps1

![photo_2021-06-02_22-44-58](https://user-images.githubusercontent.com/1241845/120549704-37c49a00-c3f4-11eb-8bb1-ca09883a2809.jpg)

config was: https://gist.github.com/hasufell/ca840ea56fdd2515959fe13cccf4194a

**To Reproduce**
1. Build above powershell script
2. run it

**Expected behavior**

Is not detected as virus.

**Screenshots**

See above.

**Version**

VS Code: 1.56.2
PowerShell Pro Tools: 5.28.4
Operating System: Windows 10

**Additional context**

**Logs** 

> Please upload a log. Logs are found in $Env:AppData\PowerShellProTools\ by default.

Above directory doesn't exit.

**Comment by adamdriscoll** [comment]
I've submitted this file for Microsoft for review. It's actually not flagging in my environment but I've certainly seen AV flag these executables before. I'm trying to get a bit more information on how we can avoid this in the future.

**Comment by adamdriscoll** [comment]
The difference may be with Cloud vs Client detection. 

![image](https://user-images.githubusercontent.com/1256531/120556694-16df5300-c3ba-11eb-8858-d665fd1e1c0d.png)

I also ran it through VirusTotal with mixed results: https://www.virustotal.com/gui/file/433576c0f5b758fe84428901c6478efe9d18df61a2976870fada964d289da0dc/detection

**Comment by adamdriscoll** [comment]
Microsoft responded with this:

We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

Thank you for contacting Microsoft.

If this ever happens again, you can submit files here: https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by hasufell** [comment]
Great progress... I've built more of said binaries (with slight source code changes) and they're not detected as malware anymore.

I wonder... would code signing alleviate this problem too?

**Comment by adamdriscoll** [comment]
Code signing may help with the issue. Microsoft didn't give me a reason as to why they flagged this binary but I would imagine a code signed binary would be more legitimate in their eyes.

**Comment by hasufell** [comment]
https://www.reddit.com/r/haskell/comments/ntmmkq/ann_ghcup_0115rc2_windows_prerelease/h16khbf?utm_source=share&utm_medium=web2x&context=3

> 5 security vendors flagged bootstrap-haskell-1.0.1.exe as malicious

**Comment by adamdriscoll** [comment]
Here's some detailed information about this issue. https://docs.poshtools.com/powershell-pro-tools-documentation/packaging/anti-virus

There isn't much we can do on a technical level about this besides provide some guidance.
