### ISSUE TITLE
Static appsettings.json values

### ISSUE THREAD

**Issue by carterduplessis** [ironmansoftware/powershell-universal#2033]
### Summary of the new feature / enhancement

Every time I upgrade to a new version of Powershell Universal, I have to change the global session timeout back to what I had it set to because the installer resets C:\Program Files (x86)\Universal\appsettings.json which overwrites the values I have set inside. For me, it is the sessiontimeout value.

I was thinking that it would be good if that didn't get overwritten when I uninstall/reinstall different versions.

Carter

### Proposed technical implementation details (optional)

I was thinking that it would be good if C:\Program Files (x86)\Universal\appsettings.json didn't get overwritten when the app is uninstalled/reinstalled.

**Comment by schubfre** [comment]
You need to change your custom settings in the appsettings.json in C:\ProgramData\PowerShellUniversal\appsettings.json (needs to be created)

See https://docs.powershelluniversal.com/config/settings

> Although you can edit this file directly, it's recommended that you use one of the following methods to persist settings as the appsettings.json file in the installation directory will be overridden on upgrades.

**Comment by adamdriscoll** [comment]
Closing as the suggested solution is the way to accomplish this.
