### ISSUE TITLE
dbatools - api issues

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#2034]
### Steps to Reproduce

Im experiencing issues with importing dbatools, into my API endpoints.
PSU is set to use individual pwsh processes, to serve the enpoints.

It only fails for the first attempt, after the server or API have been restarted - all subsequent requests are handled fine.
![image](https://user-images.githubusercontent.com/53445047/216132163-03b71170-73f1-4e2d-b74c-06a410e22d40.png)

`
$Modules = @("dbatools")
foreach ($Module in $Modules) {
    if (!(Get-Module -name $Module)) {
        try {
            Import-Module -name $module -Force -ErrorAction stop    
        }
        catch {
            throw "Failed to import the module $Module - $($_.Exception.Message)"
        }
    }
}
`

### Expected behavior

```console
That dbatools is actually imported. It works if i use Pwsh manually.
```

### Actual behavior

```console
It fails. Run it again, and it works until next restart.
```

### Environment data

PSU Version: 3.7.9
OS: Windows Server 2022

**Comment by adamdriscoll** [comment]
This is related to this issue: https://github.com/dataplat/dbatools/issues/8688

**Comment by ksl28** [comment]
> This is related to this issue: [dataplat/dbatools#8688](https://github.com/dataplat/dbatools/issues/8688)

Awesome - looks like the dbatools team, is already working on a fix :)
