### ISSUE TITLE
add dashboard built in variable

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2035]
### Summary of the new feature / enhancement

As a developer, I want to build a link to click on to get to another dashboard so that i don't have to build my urls from scratch. 

This would be used when trying to get to a different dashboard url.

### Proposed technical implementation details (optional)

add

```powershell
$psuRootUrl

Write-Host $psuRootUrl
```

would echo "https://servername.com/mySubName/"

**Comment by Omzig** [comment]
@adamdriscoll, how hard is this?

**Comment by MikeShepard** [comment]
@adamdriscoll - you mention here: https://github.com/ironmansoftware/issues/issues/2622#issuecomment-1718113132
that we can combine the base URL with the relative path for the download folder.

Can't really find a "base URL" in any of the automatic variables.

**Comment by Omzig** [comment]
Make sure you add the nested IIS site path into that base url path ;)

right now we do some messy business with $Env:PSUBaseURLinstanceName to get around it, but it should be built in

As a developer, I want to know all the things about my instance so that i can craft urls accurately and quickly without spaghetti code.

**Comment by MattHarrisUltima** [comment]
I had the same problem, but was able to find the base URL in a hashtable.

`$headers["Host"]` gave me the base URL. From that, I was able to construct the full URL for a published folder.

**Comment by MikeShepard** [comment]
@MattHarrisUltima - that's cool, but it would be awesome if we didn't have to do that digging.

**Comment by Omzig** [comment]
duplicate

**Comment by Omzig** [comment]
IT WORKS!
