### ISSUE TITLE
Login Page: Image property is broken

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#2036]
### Steps to Reproduce

You can define an image and save it, and it will initially work.
But as soon as you logoff and reopen the browser the logo gets "lost"
![image](https://user-images.githubusercontent.com/11975745/216244039-8a8ce592-e1da-4514-ba7e-cdec25d0d40e.png)

### Expected behavior

```console
The logo should stay once configured
```

### Actual behavior

```console
It stays only after hitting save and at next page reload its gone
```

### Environment data

3.7.9

**Comment by adamdriscoll** [comment]
I can't reproduce this one. What's the URL look like for this image and how are you hosting it?

**Comment by donlent** [comment]
Not on my computer right now but I'm using a published folder pointing to C:\PSU\Repository\assets pointing to /assets

In the config I'm then referring directly to /assets/myImage.png

Hope that helps...

**Comment by adamdriscoll** [comment]
I don't see this with published folders either. I can reproduce it if I enable authentication for the published folder. Then it fails to load the image with a 401. 

<img width="562" alt="image" src="https://user-images.githubusercontent.com/1256531/216371115-02deb6a9-b80c-432d-b5c7-66578fa8dd19.png">

**Comment by donlent** [comment]
Ah there we go! I can't tell you right now if auth is enabled or not but will report back as soon as I get home an verify this 😊
In the meantime thanks a lot!

**Comment by donlent** [comment]
OK Adam you're right! Sorry for that! I had auth enabled which is the default setting so I completely ignored that in such a case even the "internal" Login Page will not have access to it.
I'll go ahead an close the issue now but just for curiosity: Is there a way to just internally point to a resource without having to publish anything? Because using the published folder approach seemed to me the most simple and evident solution...
Thanks, Don

**Comment by adamdriscoll** [comment]
This is currently the only way to host files. We don't have a way to publish just a single file.

**Comment by donlent** [comment]
OK Adam thanks! Just wanted to know if there was another, even simpler way to do it. But I can absolutely live with the current solution! 👌🤗
