### ISSUE TITLE
Allow Custom Favicon's for separate dashboards on start

### ISSUE THREAD

**Issue by MattHarrisUltima** [ironmansoftware/powershell-universal#2038]
### Summary of the new feature / enhancement

Currently, we can see that the favicon is loaded from the /home directory from inside PowerShell Universal Containers.

Would it be possible to add functionality to specify a custom favicon (stored inside the dashboard folder) per dashboard to load on start up of a dashboard?

If implemented, we would like to be able to use different favicons for multiple dashboards specified in the dashboard properties.

**Comment by DougNeely** [comment]
I'll mention that the way I do this is using UDHelmet.  Here is sample code:
New-UDHelmet -Content {
		New-UDHtmlTag -Tag 'title' -Content { "$Cache:SiteName" }
		New-UDHtmlTag -Tag 'link' -Attributes @{
			rel  = 'icon'
			href = 'https://siteurlhere/files/Gfavicon.ico'
		}
	}

Yes, I do have to have this on every page, but I use the title to then put a unique title on each page, as well.

**Comment by MattHarrisUltima** [comment]
Hi @DougNeely,

I currently do exactly the same however, when the page loads the Icon remains on the default item for a good few seconds before this bit of code kicks in. 

It's those few seconds on load I'm looking to swap the Icon on.

I'm hoping something along the lines of a parameter can be added to New-PSUDashboard to load these on dashboard start for this and [https://github.com/ironmansoftware/issues/issues/2040](url)

Unfortunately, the underlining settings are outside the /root folder on containers, so there is no workaround I can put in place.

**Comment by MattHarrisUltima** [comment]
Good morning,

I was wondering if you have had a chance to review this enhancement request?

Since removing JS modules after [this forum post](https://forums.ironmansoftware.com/t/intermittent-invalid-configuration-dashboards-ps1-error/8629), I have seen a massive reduction in hanging and load times, however the delay is still sizeable. By removing the UDHelmet module, I hope to get this down some more if this enhancement request is accepted.
