### ISSUE TITLE
Allow custom browser tab titles for dashboards on start of dashboard

### ISSUE THREAD

**Issue by MattHarrisUltima** [ironmansoftware/powershell-universal#2040]
### Summary of the new feature / enhancement

Currently, we are using New-UDHelmet to modify the <Title> tag of our dashboard's.

Dome of our dashboards are loading quite a bit of data and on load it takes a few seconds for this bit of code to apply, leaving "PowerShell Universal Dashboard" displayed whenever dashboard pages load.

Would it be possible to add a Dashboard parameter for <Title> so dashboards on load pull in this string instead of "PowerShell Universal Dashboard" so this is applied before the dashboard page loads?

**Comment by MattHarrisUltima** [comment]
Good morning,

I was wondering if you have had a chance to review this enhancement request?

Since removing JS modules after [this forum post](https://forums.ironmansoftware.com/t/intermittent-invalid-configuration-dashboards-ps1-error/8629), I have seen a massive reduction in hanging and load times, however the delay is still sizeable. By removing the UDHelmet module, I hope to get this down some more if this enhancement request is accepted.

**Comment by adamdriscoll** [comment]
I believe this was actually resolved in 3.8 - https://docs.powershelluniversal.com/changelog#3.8.0-3-14-2023 Closed issue: #2095

**Comment by MattHarrisUltima** [comment]
Hi @adamdriscoll,

I have tested this in 3.8.3 can can confirm that when I use the -title parameter in New-UDPage this is changing the tab title.

The last hurdle I have is that this seems to place a block of text on my header:
![image](https://user-images.githubusercontent.com/106333485/227457913-229c1949-5f26-443a-9e0f-167252605f7d.png)

Is there a parameter I can use to stop this from displaying?

**Comment by adamdriscoll** [comment]
@MattHarrisUltima - This is expected behavior. I'm assuming you used Website title as the -Title value? If you want to override the appbar behavior, you will need to using -Blank on New-UDPage and then use New-UDAppBar within the page. 

```
New-UDPage -Blank -Title 'Website title' -Content {
   New-UDAppBar -Children {}
}
```

**Comment by MattHarrisUltima** [comment]
Thanks, @adamdriscoll 

I will Implement this.
