### ISSUE TITLE
UDAutoComplete does not recognize a one-item array

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2050]
### Steps to Reproduce

1. Create a working example of New-UDAutoComplete with multiple items to choose from
2. Reduce the number of items to choose from down to 1 (i.e. the -Options parameter of New-UDAutoComplete)
3. Observe that the UDAutoComplete dialog is no longer drawn

### Expected behavior

```console
If only one item is available to the UDAutoComplete, it should be displayed and selected automatically.
```

### Actual behavior

```console
If only one item is available to the UDAutoComplete, the dialog is not drawn.
```

### Environment data

PSU 3.7.10

**Comment by DataTraveler1** [comment]
Workaround - Adding a label parameter to the New-UDAutoComplete will enable a 1-item array to render

**Comment by adamdriscoll** [comment]
Cannot reproduce on latest.
