### ISSUE TITLE
No runas in schedule UI

### ISSUE THREAD

**Issue by i-windows** [ironmansoftware/powershell-universal#2055]
### Steps to Reproduce

there is no runas option displayed when editing a scheduled job in the UI

![Uploading image.png…]()

### Expected behavior

```console
should be able to set runas credential in the UI
```

### Actual behavior

```console
non runas ui displayedn
```

### Environment data

3.7.10

**Comment by adamdriscoll** [comment]
I can't reproduce this: 
<img width="422" alt="image" src="https://user-images.githubusercontent.com/1256531/217835936-bf8a8f2a-9aea-4ee9-be53-be0716ac2c74.png">

Do note, that if a script has a credential specified directly on it, then this option won't be available in the schedule UI.
