### ISSUE TITLE
Scheduled Jobs which return an error are displayed as sucessful

### ISSUE THREAD

**Issue by i-windows** [ironmansoftware/powershell-universal#2056]
### Steps to Reproduce

a scheduled job which generates an error is displayed as sucessful in the GUI

EG. the following is error is generated
[error] Cannot bind argument to parameter 'InputObject' because it is null. 
[error] Cannot bind argument to parameter 'InputObject' because it is null. 

but the job returns success
![image](https://user-images.githubusercontent.com/6116167/217478924-a8060a16-24cb-4826-9fc7-8680a43623ae.png)

### Expected behavior

```console
job returns with an error
```

### Actual behavior

```console
job returns with sucess
```

### Environment data

3.7.10

**Comment by schubfre** [comment]
Is the Erroraction of the Script set to 'Stop'? If it's set to 'SilentlyContinue' the script will always run as successful

**Comment by i-windows** [comment]
it set to continue, which should output the trapped errors.
Warning messages are displayed correctly, however errors are not.
