### ISSUE TITLE
swagger documentation went poof

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2064]
### Steps to Reproduce

when i go to /swagger all the comment base swagger help is not shown anymore

### Expected behavior

```console
doc
```

### Actual behavior

```console
no doc
```

### Environment data

PSU: 3.7.10

**Comment by adamdriscoll** [comment]
Trying to reproduce this with a super simple example. 

```

<# 
.SYNOPSIS
This is an endpoint

.DESCRIPTION
This is a description

.PARAMETER ID
This is an ID.

#>
param($ID)
    
$Id

```

<img width="295" alt="image" src="https://user-images.githubusercontent.com/1256531/218812920-310575c4-6157-465c-b5e1-13a28d3a00cf.png">


Can you check the logs for any errors after viewing the swagger page?

**Comment by Omzig** [comment]
@adamdriscoll, i am closing this, since it went out in 3.7.11
