### ISSUE TITLE
Similar Parameters between New-UDDataGrid and New-UDTable should be named the same

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/powershell-universal#2072]
### Summary of the new feature / enhancement

I think having consistent parameter naming conventions between similar components would be helpful.

Current similarities but with different naming 
| New-UDTable | New-UDDataGrid |
| --- | --- |
| LoadData | LoadRows |
| ShowPagination | Pagination |
| PageSize | RowsPerPageOptions |
| Locale | Language |

I think such an approach should for all components.

### Proposed technical implementation details (optional)

Any changes should ensure that aliases should be provided by the current parameters in order to not break existing code.

**Comment by adamdriscoll** [comment]
@mattselle - I'm up for renaming all of these to match. I think, I like the UDDataGrid nomenclature better, but we should make sure to include aliases for backwards compat.

**Comment by Viajaz** [comment]
@adamdriscoll Keep in mind that `ShowPagination` matches the convention of other `Show*` parameters for `New-UDTable`.
I think a full review of all parameters of both is probably in order.
