### ISSUE TITLE
Renaming script names should trigger an update of related entries in Schedule.ps1

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2075]
### Steps to Reproduce

Renaming script names directly in .Universal\Scripts.ps1 does not trigger an update of related entries in Schedule.ps1

### Suggestions

1. Allow the Schedules.ps1 New-PSUSchedule modules Name parameter to match a registered scripts name, relative path (in repository or scripts) or full path name

2. Update New-PSUSchedule dynamic parameters with more resiliency. For example: If there is a failure pulling "$URL/api/v1/script/$($ScriptName) ", maybe try a few other options before gently exiting.

### Expected behavior

```console
Renaming script names directly in .Universal\Scripts.ps1 should an update of related entries in Schedule.ps1
```

### Actual behavior

```console
Renaming script names directly in .Universal\Scripts.ps1 does not trigger an update of related entries in Schedule.ps1
```

### Environment data

PSU 3.7.10

### Visuals

Thanks to the person who reported this internally 👍

**Comment by insomniacc** [comment]
I'd also suggest updating script names in triggers.ps1 should be bundled in with this too
