### ISSUE TITLE
Editing files in Configurations resulting in Error 500

### ISSUE THREAD

**Issue by memphisraynz** [ironmansoftware/powershell-universal#2076]
### Steps to Reproduce

On 3.7.10 and now getting "Request failed with status code 500" when editing files in Configurations

### Expected behavior

```console
Save edits
```

### Actual behavior

```console
Request failed with status code 500
```

### Environment data

Powershell universal 3.7.10 on Windows server

**Comment by adamdriscoll** [comment]
Can you please provide a log? The 500 error should include more information. I'm not able to reproduce this.

**Comment by memphisraynz** [comment]
I have gone through and reviewed permissions and the service account has full control along with the other requirements for running as a service.

I have attached a log
[log20230213.txt](https://github.com/ironmansoftware/issues/files/10717381/log20230213.txt)

*edit* - I have gone back and reviewed all my logs files. This first started after the 3.7.8 upgrade. Prior to this I can't find this error.

Thanks

**Comment by memphisraynz** [comment]
I think I have found the issue.
I have a couple of folders hidden to keep required files in GIT but not showing up in the Scripts section.
The files themselves had the hidden flag. I have tried a few times, removing and re-adding. 
Each time the hidden flag is remove I can save, re-adding the hidden flag reproduces the error.

**Comment by adamdriscoll** [comment]
We've made a change to allow for writing to hidden files.
