### ISSUE TITLE
Please add the remaining 19 nivo react components (charts)

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2077]
### Summary of the new feature / enhancement

Currently, New-UDNivoChart supports 8 of 27 charts. It would be ideal if the remaining 19 chart types could be added. This feature request was raised internally 🍮 specifically around the choropleth chart 🗺
 
|Name|Supported|
| :------------ |:---------------:|
|AreaBump|❌|
|Bar|✔|
|Bullet|❌|
|Bump|❌|
|Calendar|✔|
|Chord|❌|
|Choropleth|❌|
|CirclePacking<SUP>[1]</SUP>|✔|
|Funnel|❌|
|GeoMap|❌|
|HeatMap|✔|
|Line|✔|
|Marimekko|❌|
|Network|❌|
|ParallelCoordinates|❌|
|Pie|✔|
|Radar|❌|
|RadialBar|❌|
|Sankey|❌|
|ScatterPlot|❌|
|Stream|✔|
|Sunburst|❌|
|SwarmPlot|❌|
|TimeRange|❌|
|TreeMap|✔|
|Voronoi|❌|
|Waffle|❌|

<SUP>[1]</SUP> Circle-Packing exists under the legacy name 'Bubble'. There is a pull request to update it to its current name.

**Comment by adamdriscoll** [comment]
Not enough demand from customers.
