### ISSUE TITLE
Sessions do not persist in the $Cache when using integrated mode with jobs

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#209]
https://forums.ironmansoftware.com/t/cache-mechanism/4672/26

**Comment by LxLeChat** [comment]
Hello @adamdriscoll , any update on this issue ???
Thanks !

**Comment by adamdriscoll** [comment]
This is going to require quite a bit of reachitecting and I don't want to rush it into 2.7. I will be pushing this into 3.0 since it will require some significant work.

**Comment by LxLeChat** [comment]
Hi adam, any update on this issue ? maybe you need me to do some tests on my side with the latetest realases ?

**Comment by adamdriscoll** [comment]
After trying to accomplish this a few times, I actually had to roll this back since we have a bunch of issues with how environments in jobs are used that make it super difficult to actually accomplish this. We may approach this in a different manner with a new feature specifically for this type of thing. 

That said, what I would recommend as a work around would be to create an API endpoint that has the functionality that you wish to encompass in the job. Then, when you run the schedule or jobs you could execute the API rather than running the code in the job itself. This would ensure that the runspaces and sessions are persisted because it's running them within the API runspace rather than the job runspaces themselves.

**Comment by LxLeChat** [comment]
thank you adam! we will try the workaround :) as always bravo for you work !
