### ISSUE TITLE
ChartJS Stacked chart actually is grouped

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#2091]
### Steps to Reproduce

The example here: https://docs.powershelluniversal.com/userinterfaces/dashboards/components/data-visualization/charts#stacked-bar

Should build a stacked bar chart.  The graphic is stacked.  Unfortunately, the output is grouped (side-by-side rather than stacked).

Passing 'grouped=$false' gets us closer, but then the bars are on top of each other (overlaying rather than stacking)

### Expected behavior

```console
Should be a stacked bar chart
```

### Actual behavior

```console
Is a grouped bar chart
```

### Environment data

PSU 3.7.10

**Comment by mattselle** [comment]
We will need to update that example.

To do stack this should work
$GraphPrep = @(
            @{ RAM = "Server1"; AvailableRam = 128; UsedRAM = 10 }
            @{ RAM = "Server2"; AvailableRam = 64; UsedRAM = 63 }
            @{ RAM = "Server3"; AvailableRam = 48; UsedRAM = 40 }
            @{ RAM = "Server4"; AvailableRam = 64;; UsedRAM = 26 }
            @{ RAM = "Server5"; AvailableRam = 128; UsedRAM = 120 }
        )
    
        $AvailableRamDataSet = New-UDChartJSDataset -DataProperty AvailableRAM -Label 'Available' -BackgroundColor blue
        $UsedRamDataset = New-UDChartJSDataset -DataProperty UsedRAM -Label 'Used' -BackgroundColor red
        $Options = @{
            Type          = 'bar'
            Data          = $GraphPrep
            Dataset       = @($AvailableRamDataSet, $UsedRamDataset)
            LabelProperty = "RAM"
            Options = @{
                scales = @{
                    xAxes = 
                    @{
                        stacked = $true
                    }
                
                    yAxes =                 
                    @{
                        stacked = $true
                    }
                
                }
            }
        } 
    
        New-UDChartJS @Options

**Comment by mattselle** [comment]
Docs have been updated
