### ISSUE TITLE
Sorting tags does not work in the admin console.

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#210]
Tag a script and attempt to sort by tag. 

Version: 2.0.0

**Comment by mabster** [comment]
Kinda related - if you filter the list of scripts using tags, it's possible to get yourself into a knot:

1. Click on "Tag A" to filter scripts for that tag
2. Click on "Tag B" to add a second filter, so now you see everything with both Tag A and Tag B
3. Remove "Tag A" from the filter

Now you only see scripts with Tag B, but both tags get removed from the filter so you have no way to clear the filter. Refreshing the page gets you back, thankfully.

**Comment by penser-jata** [comment]
Could we get this fixed, please?
Bug still present in 2.8.2.
It is a useful feature, and there is absolutely no indication that it shouldn't work.
On the contrary, the asc / desc indicator toggles as if it were sorting.

**Comment by MikeShepard** [comment]
Still present in 3.8.12

**Comment by adamdriscoll** [comment]
#2975 - Implement for new admin console
