### ISSUE TITLE
Editing Dashboard Page URL does not work

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2102]
### Steps to Reproduce

Create a dashboard page 
Try to edit the dashboard page URL 
Dashboard page URL is not updated

### Expected behavior

```console
Dashboard URL is updated.
```

### Actual behavior

```console
Dashboard page uRL is not updated.
```

### Environment data

3.7.11

**Comment by adamdriscoll** [comment]
Cannot reproduce on 3.7.11

**Comment by Omzig** [comment]
> Cannot reproduce on 3.7.11

Welp, now i cannot duplicate it. Description is still messed up. so this is still valid: https://github.com/ironmansoftware/issues/issues/2111

**Comment by Omzig** [comment]
ok, so, i was able to cause the Get-UDPage to not work after you rename the url, because if you create page2, then rename the url to page3, you cannot do Get-UDPage page2 or page3, the -Name and -URL has to match ;) but the file name does not.

this scenario does work
```powershell
page2.ps1
New-UDPage -Url "/page3" -Name "page3" -Content {
# Use Get-UDPage -Name 'page2' to use this page in your dashboard
New-UDTypography -Text page2
}
```

```powershell
dashboardTest.ps1
New-UDDashboard -Title 'PowerShell Universal' -Pages @(
    # Create a page using the menu to the right ->   
    # Reference the page here with Get-UDPage
    New-UDPage -Name 'Home' -Content {}
    Get-UDPage -Name page3
)
```
