### ISSUE TITLE
Configuration Editor should remember selected file and expanded folders

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2103]
### Summary of the new feature / enhancement

Go to the configuration editor page
Navigate to a folder and file
Edit the file 
Navigate back after editing the file
Navigation is all collapsed.

**Comment by Omzig** [comment]
#reopen

@adamdriscoll, something is wrong with how it reloads the folders, this example is in the modules folder:
![image](https://user-images.githubusercontent.com/1987296/220402279-67b09836-de4c-403b-b7ab-eef208c93562.png)

I lost the ability to expand the folders after saving.

**Comment by adamdriscoll** [comment]
I cleaned this up today. It will be in tonight's build. I was having the same problem
