### ISSUE TITLE
Git Commit Staging

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2106]
### Summary of the new feature / enhancement

This may help users looking for #1974. 

When going to commit a change, we should display a page that includes all currently changed files. The user then could select the files they wish to stage and only commit and push those files rather than all files. This would at least allow two users to work at once and only commit the files they have changed. We should also include a diff view.

**Comment by Omzig** [comment]
@adamdriscoll, this would be super helpful in our multi user dev environment. We currently have to RDP into the server and commit just the files that i am working on.

**Comment by adamdriscoll** [comment]
We got this done for 4.2 ;)
