### ISSUE TITLE
Consistent Logging

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2110]
### Summary of the new feature / enhancement

We should provide consistent logging across PSU. There are several different places logs are stored: 

- Server log (file system and in-memory)
- API logs (database and in-memory)
- Job logs (database) 
- Dashboard logs (database) 

Instead of all these different places, we should use a single system that stores logs consistently. The reason for doing this would be that we could: 

- View all logs across tools in the system at once
- Filter logs in a single place based on metadata in the log system 
- Download filtered logs without having to go to the file system 
- Easily trace interaction across the platform 

We should also consider enriching logs with info about the current action: 

- Username 
- Http session ID 
- Event IDs from dashboards 

Considerations: 

- Performance
- Log storage, growth, and pruning
- Log shipping

**Comment by Viajaz** [comment]
I was actually going to make a ticket similar to this too.

I'm also looking for the following for scripts, API endpoints and, especially, dashboards:
- Timestamps
- Thread IDs
- Runspace/Endpoint IDs

**Comment by JoriPS1** [comment]
I think is a great enhancement @adamdriscoll.  Bonus points if the logging includes a function that we can use to log custom functions/include custom data in the log.  Would love to replace my custom logging functions (technical debt) with something made with care.

I think in an ideal world for me, the logs would be stored "locally", but also be forwarded to a Azure Log Analytics Workspace.

**Comment by Omzig** [comment]
these are related:
- https://github.com/ironmansoftware/issues/issues/1963
- https://github.com/ironmansoftware/issues/issues/2271

**Comment by adamdriscoll** [comment]
Just an update on this issue. We will be releasing a more comprehensive version in beta2. It will include the following: 

- Additional logging methods: Database (LiteDB, SQL), HTTP, UDP and TCP
- Write-PSULog now has a -Properties parameter where you can specify a hashtable of properties to include with your log messages
- Log viewer implementation is complete and filters messages from the database logger. It is used where logs can be viewed. 

I'll close this issue and open some other smaller ones that I still want to implement. I will link them here. 

- Grooming settings : #2317 
- Log Exporting: #2318
