### ISSUE TITLE
New-UDTable "NoData" parameter

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#2112]
### Summary of the new feature / enhancement

As a user, I want to display a label if there's no data loaded in the table (rather than showing an error toast)

New-UDTable -data $data -NoDataLabel "No data found for this query" ...

### Proposed technical implementation details (optional)

New-UDTable -data $data -NoDataLabel "No data found for this query" ...

**Comment by rwidmark** [comment]
You can do this by your self.
Just set if ($null -ne $tableData) { show error } else { show data table }

**Comment by MikeShepard** [comment]
> You can do this by your self. Just set if ($null -ne $tableData) { show error } else { show data table }

That is the workaround for the enhancement I'm asking for.
