### ISSUE TITLE
PowerShell Universal Code Analyzer

### ISSUE THREAD

**Issue by JoriPS1** [ironmansoftware/powershell-universal#2113]
### Summary of the new feature / enhancement

This is still a rough draft in my brain, but I think it would be informative and helpful if PSU had some built-in functionality to analyze code.

Things that could be analyzed and reported could include..

Repeated code blocks that could be made into functions
How many times a function is used
How many times a Secret/Variable is used

The idea is that it would aggregate these across scripts, dashboards, APIs and hopefully provide information that makes it easier to write consistent code across the platform.  Perhaps even provide a way to change code across all of these.

**Comment by Viajaz** [comment]
If such a thing were to be made, some indicator of when a ScriptBlock might run in a different runspace/endpoint would be very useful.

**Comment by adamdriscoll** [comment]
We will have PSScriptAnalyzer support in v3.8 so we could create custom analyzers for PSU. I'd likely ship it as an external, open-source module that we package during the build for PSU and release it alongside the Universal module. 

![image](https://user-images.githubusercontent.com/1256531/224380678-9024e408-0a41-4779-a8a3-8b64394a7895.png)

**Comment by MikeShepard** [comment]
@adamdriscoll  - can this be closed?

**Comment by adamdriscoll** [comment]
We won't be implementing this as part of PSU but could be a community project.
