### ISSUE TITLE
Export as PDF: Columns / Rows are cutoff

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#2114]
### Steps to Reproduce

The issue is well documented here...
https://forums.ironmansoftware.com/t/table-exporting-as-pdf-formatting-concerns/6616

### Expected behavior

```console
The rows should be readable throughout the row and column but are cutoff

In addition it would be good to have the ability to specify the page orientation. For larger table just having a portrait export is not ideal.
```

### Actual behavior

```console
The rows are cutoff and are unreadable
```

### Environment data

3.7.9

**Comment by Omzig** [comment]
oh wow, i just removed pdf because i had like 25 columns that needed to be exported.

It almost needs to be something like Column -ExcludePDFExport

the pdf version should be a limited set compared to the csv json and excel file formats

**Comment by adamdriscoll** [comment]
We're going to enable horizontal page breaks for the PDF generation and that should resolve this.
