### ISSUE TITLE
Page Auto Reload is blank sometimes on Save

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2115]
### Steps to Reproduce

when i save code and it auto refreshes sometimes (Most of the time) the page is blank and doesn't reload all the way, the header and the navigation is there, but the contents is just blank.

### Expected behavior

```console
auto refresh reloads the page all the way
```

### Actual behavior

```console
navigation and header is only loaded
```

### Environment data

PSU: 3.7.12 (4228049157)
IIS: Nested

### Workaround
- F5 on the dashboard
- OR, hit it save again on your code

**Comment by adamdriscoll** [comment]
I've also seen this.

**Comment by Omzig** [comment]
@adamdriscoll, can we reopen this, this is still a random problem, sometimes it will auto reload sometimes it wont. Sometimes it will even go white.

#Reopen
