### ISSUE TITLE
New-PSUVariable accepts invalid data Type

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2116]
### Steps to Reproduce

New-PSUVariable will accept any value for the 'Type' ~property~ parameter. This is inconsistent with the UI which only presents 4 or 2 choices for Type (depending on if the variable is _Simple_ or _Secret_)

1. String
2. Boolean
3. Integer
4. Array

or

1. String
2. PSCredential

Ideally, these values would be in the form of a ValidateSet attribute in the cmdlet.

### Expected behavior

```console
New-PSUVariable should not accept any value for the Type parameter
```

### Actual behavior

```console
New-PSUVariable accepts any value for the Type parameter (see Visuals 👀)
```

### Environment data

PSU 3.7.11
PSU PowerShell Module version 3.7.11

### Visuals

![image](https://user-images.githubusercontent.com/537287/220416029-bf75b0f5-a262-49fe-afca-5e277786051d.png)

Edit 1 clarified a detail

**Comment by DataTraveler1** [comment]
Extra pic I forgot to include showing how the variable was created

![image](https://user-images.githubusercontent.com/537287/220417283-500363db-46e7-42ea-b7b5-13f8a0af43fa.png)

**Comment by DataTraveler1** [comment]
I believe that the intention with the present design was to funnel any Type besides a known type to a string. Perhaps this bug report should have been a feature request. The idea here is to provide the user with the possible and valid Types when cycling with Tab at the command line.

**Comment by adamdriscoll** [comment]
We are going to effectively ignore the -Type parameter in v5. We will just look up the type automatically.
