### ISSUE TITLE
HTML Link in Script Description

### ISSUE THREAD

**Issue by memphisraynz** [ironmansoftware/powershell-universal#2128]
### Summary of the new feature / enhancement

Ability to add a html link in the script Description field to take users to a documentation page.

Some of the script I implement require some further explanation. Being either what he code does or what format to enter in the required information.

It would be great to have the ability to enter in HTML code to create a clickable link that will take the user to the docuemntation page.

This could either be the standard <a href="url">link text</a> or even a custom format.

**Comment by adamdriscoll** [comment]
@memphisraynz I'm leaning a little towards markdown for this. How's that sound?

**Comment by memphisraynz** [comment]
Perfect!
Haven't learnt Markdown, but a good excuse to learn.

**Comment by memphisraynz** [comment]
Is there any example of the correct syntax? I can't get this to work on 4.0.1
