### ISSUE TITLE
Set-UDTheme does not persist like Dark/Light Mode

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2133]
### Steps to Reproduce

i am unable to get the selected theme to persist on refresh

### Expected behavior

```console
set theme
F5, same theme is selected
```

### Actual behavior

```console
set theme
F5, reverts to original theme
```

### Environment data

PSU: 3.7.12
IIS: Nested

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/persistent-theme/8743/4

**Comment by Omzig** [comment]
@adamdriscoll, you made my day, this is EPIC
