### ISSUE TITLE
Endpoint doesn't look through all URL links

### ISSUE THREAD

**Issue by jhadvan** [ironmansoftware/powershell-universal#2136]
### Steps to Reproduce

The two API have similar naming convention, but I expected it to be different since the first one has a unique id, while the second API is just url path.
![image](https://user-images.githubusercontent.com/116764491/221688926-14efbdbe-3c32-4542-97ae-e2e458c26817.png)

![image](https://user-images.githubusercontent.com/116764491/221688992-fa91285f-abe4-4199-bb2d-3a7257aeffec.png)

### Expected behavior

```console
I expect the URL to go to /api/custom/product/searchtag when calling it.

Instead it goes through to 
Invoke-RestMethod URL/api/custom/product/:id -Method GET
```

### Actual behavior

```console
When calling the API of URL/api/custom/product/searchtag it actually points to the link below and think "searchtag" is a query parameter of URL/api/custom/product/:id. It seems like PSU Endpoint does not look at all of the URL path available?
```

### Environment data

3.7.12

**Comment by adamdriscoll** [comment]
@jhadvan - You might be able to move the definitions within the endpoints.ps1 file so that the searchtag one comes before the :id  one. Might be worth a shot.
