### ISSUE TITLE
Dense Text Boxes for Tables

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2144]
### Summary of the new feature / enhancement

I have a problem with check boxes being too large in a table with -Dense.... I like the size of the checkbox icons, i just don't like all the extra space it takes up.

![image](https://user-images.githubusercontent.com/1987296/222183921-60eb5df8-8350-4722-872b-fe6cca7f71ec.png)

### Proposed technical implementation details (optional)

not sure what the solution is here, when we -Render a text box in a -Dense table, should it just be aware that -Dense is on or do we need to add -Dense to the New-UDTextBox itself?

**Comment by Omzig** [comment]
@mattselle, is this an easy one?

**Comment by adamdriscoll** [comment]
You can use the -Style parameter to remove the padding. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/4a9bf95a-cf35-4d15-a328-36e39fc752c6)


```powershell
New-UDApp -Content {
   New-UDCheckbox -Size "small" -Style @{
     padding = 0
   }
   New-UDCheckbox -Style @{
     padding = 0
   }
}
```

**Comment by Omzig** [comment]
i cannot get that to work in a table....

```
   New-UDTableColumn -Property ReadOnly -Title 'Read Only?' -Render {
                                    Write-Host $eventData.ReadOnly
                                    New-UDCheckBox -Checked ($eventData.ReadOnly -eq 'true') -Disabled -Style @{
                                        padding = 0
                                    }
                                }
```

**Comment by Omzig** [comment]
So, it is because -disabled does something funny to the style. it is like an override that wipes any -style being applied and i cannot do !important to get it to fix the padding...

```
    New-UDCheckBox -Disabled -Size "small" -Style @{
        padding = 0
    }
    New-UDCheckBox -Disabled -Style @{
        padding = 0
    }
```

**Comment by adamdriscoll** [comment]
We needed to make a tweak to the React component to support the disabled switch and the style
