### ISSUE TITLE
New-UDTextbox -RowsMax does not work

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2155]
### Steps to Reproduce

when i use  this, it does not limit my max rows to 10: New-UDTextbox -Multiline -Rows 4 -RowsMax 10

### Expected behavior

```console
10 rows max
```

### Actual behavior

```console
unlimited
```

### Environment data

PSU: 3.7.14
IIS: Nested

### Visuals

![image](https://user-images.githubusercontent.com/1987296/222751809-084d4aa4-01cd-43f6-8056-9a0ff32dbe9e.png)

**Comment by adamdriscoll** [comment]
Rows max is the number of rows to display before showing a scrollbar and not a limit on the number of rows allowed in the textbox.

**Comment by Omzig** [comment]
> Rows max is the number of rows to display before showing a scrollbar and not a limit on the number of rows allowed in the textbox.

oh /facepalm
