### ISSUE TITLE
Add split button to UDButton (Button Group)

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#2163]
### Summary of the new feature / enhancement

Mui have something called split button in the button group. It would be great to have that in PSU as well.

![image](https://user-images.githubusercontent.com/76907327/222962300-6b982271-f23f-4c09-8667-571d85fb3e7e.png)

https://user-images.githubusercontent.com/76907327/222950565-5c513aee-563f-453b-b4f2-a9b10dcdbf13.mov

https://mui.com/material-ui/react-button-group/

### Proposed technical implementation details (optional)

https://mui.com/material-ui/react-button-group/

**Comment by rwidmark** [comment]
@adamdriscoll this is also something that's needed 😀 

For example, you have multiple power options, then you don't need to create a button for each one of them.

**Comment by Viajaz** [comment]
Absolutely, was in desperate need for this for my last PSU dashboard project, in the end I just used a modal.

**Comment by rwidmark** [comment]
@adamdriscoll is this something that you can add to 3.8.0?

This is badly missing :)

**Comment by adamdriscoll** [comment]
@rstolpe We'll see if we can get it in.

**Comment by rwidmark** [comment]
> @rstolpe We'll see if we can get it in. 

@adamdriscoll  Any eta on 3.8?

**Comment by adamdriscoll** [comment]
@rstolpe March 14th. We always have our release dates assigned on our milestones page: https://github.com/ironmansoftware/issues/milestones

**Comment by rwidmark** [comment]
@adamdriscoll dident know that, perfect :)

**Comment by rwidmark** [comment]
Guessing the milestone on this is 3.8.3? :)

**Comment by rwidmark** [comment]
@adamdriscoll any news on this one?

**Comment by rwidmark** [comment]
@adamdriscoll @mattselle any eta?

**Comment by Omzig** [comment]
Here is the doc on it: https://mui.com/material-ui/react-button-group/#split-button

**Comment by mattselle** [comment]
I should have this done by early next week
