### ISSUE TITLE
UDAutocomplete OnEnter cannot access value

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2165]
### Steps to Reproduce

https://forums.ironmansoftware.com/t/get-udelement-with-new-udautocomplete-element-not-working/8788/2

### Expected behavior

```console
OnEnter can access the value (we should just pass it in)
```

### Actual behavior

```console
OnEnter cannot access the value
```

### Environment data

3.7.14

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/autocomplete-add-new-item/8791/3

**Comment by Omzig** [comment]
@adamdriscoll, can we get this in 3.8?

**Comment by adamdriscoll** [comment]
Yep. This one should be an easy fix.

**Comment by Omzig** [comment]
#related  
- https://github.com/ironmansoftware/issues/issues/2154

**Comment by Omzig** [comment]
#reopen

@adamdriscoll, this is not working for new values that need to be added into the autocomplete list.
