### ISSUE TITLE
Run-Away Memory Usage in Dashboards

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2171]
### Steps to Reproduce

It's possible to cause a run-away memory condition in a dashboard. If many, many error records are generated, it can cause the dashboard process to use more and more memory. After some time, the memory will be reclaimed but if maximum server memory is used before then, it can get into a state where it never recovers. 

To reproduce: 

```
New-UDDashboard -Title 'PowerShell Universal' -Content {
    1..1000000 | % {
        Write-Error $_
    }
} 
```

With that example, I was able to use about 2.5 GB of memory in 1 minute after refreshing the dashboard page a few times. 

A work around is to set the ErrorActionPreference to SilentlyContinue. 

```
New-UDDashboard -Title 'PowerShell Universal' -Content {
    $ErrorActionPreference = 'SilentlyContinue'
    1..1000000 | % {
        Write-Error $_
    }
} 
```

PSU should not allow dashboards to get into this condition. 

### Expected behavior

```console
No run-away memory usage
```

### Actual behavior

```console
Run-away memory usage
```

### Environment data

3.7.14

**Comment by adamdriscoll** [comment]
This is just a problem of too many errors. I think if the dashboard is doing this it's in an invalid state and there isn't much we can do. The PowerShell engine is just collecting all the errors as the pipeline is executing ...

**Comment by Viajaz** [comment]
Could you put in an option to enable a condition that if there are X number of ErrorRecords created in Y minutes, it forces a restart of the dashboard?
@adamdriscoll
