### ISSUE TITLE
Loadbalancing / failover

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#218]
**Describe the solution you'd like**
- AppToken need to bee floated over multi PSU sites.
- API somehow floaten or understand what site there are on.
- Load balancing check, maybe a small picture?
- Replication trough PSU sites with one master-site. Manually trigger and automatic schedual maybe every 60 or 120 minutes?
- In PSU GUI/admin user should only slide a button to activate this function and ofc fill out necessary information.

**Additional context**

Many of us that are building a big environment with PSU do have multiple datacenters. And with that we do have multiple PSU sites that we want to work side by side.

For example if you are using Netscaler the setup can bee something like this;

PSU.com -> IP (Netscaler, stickiness connection) -> load balancing and failover trough multiple PSU sites.

And if one PSU site goes down it don't matter as you have redundancy. The Netscaler for example are checking if a picture or similar can bee access on every PSU site and if it's not then it's flagged as offline and are taking out of service.

**How to get this to work?**

I have a function for the AppToken already that I can upload if someone are interested not the best solution but it works.

Im also working on a function to sync the content between sites. I know that gitsync work like this but sometimes you don't want to share / upload your stuff to GitHub or maybe you only want the git to sync with a test site and not with the production like we do.

The API I'm stuck I did have an ide but it did not work.

@adamdriscoll maybe some kind of open source git section for side projects that then later on maybe if you approves them migrates in to the project?
Like VMware flings?

**Comment by adamdriscoll** [comment]
I'm really open to feedback here because it's something I'm looking into. High availability\failover was the original target but I can understand why load balancing is important too. 

The idea was to introduce SQL support for persistence. This would allow a centralized storage location for configuration and other state. We use a scheduling library called HangFire that takes care of issuing jobs to agents and we could store configuration data from PS1s in the database rather than memory. 

Obviously, this is a big lift and will require some work but now that we have 2.0, it is the next major thing to work on aside from bug fixing. 

That said, I'm super curious about VMware Flings and that concept. Hadn't heard of that before and will take a look at the program.

**Comment by rwidmark** [comment]
> I'm really open to feedback here because it's something I'm looking into. High availability\failover was the original target but I can understand why load balancing is important too. 
> 
> 
> 
> The idea was to introduce SQL support for persistence. This would allow a centralized storage location for configuration and other state. We use a scheduling library called HangFire that takes care of issuing jobs to agents and we could store configuration data from PS1s in the database rather than memory. 
> 
> 
> 
> Obviously, this is a big lift and will require some work but now that we have 2.0, it is the next major thing to work on aside from bug fixing. 
> 
> 
> 
> That said, I'm super curious about VMware Flings and that concept. Hadn't heard of that before and will take a look at the program. 


I'm on vacation now but I can provide with notes and a map over how we have thought regarding the solution. (Ofc sql db should be best but as I did write we are working with what we have now :))

Yeh, VMware flings is a good approach.
Don't know what you should name it but it's a great thing.

One git with opensource solution VMware don't have that as flings are currently build from employees at VMware. But in this case if you want to get out to the big mass of people the. Opensource would bee the best option.

Then people can work with a new function for powershell universal and if you think it's good then you migrate it in to powershell universal.

**Comment by rwidmark** [comment]
I have not forgotten this, I'm still on vacation ending within a week. I did pull 10 week vacation this year :)

**Comment by rwidmark** [comment]
Here is the AppToken solution I have done.
https://github.com/rstolpe/PSU-Random/tree/main/AppToken

I guess you can do it better but it do work.

**Comment by muravsky** [comment]
Move to DB already addressed most of the concerns. But in order to use PSU behind a load balancer without a second thought - cache replication is missing. For now, in order to use $Cache variables - they need to be independently populated on each node.

**Comment by adamdriscoll** [comment]
We now have cache persistence in the database in v5 so they can go across nodes.
