### ISSUE TITLE
New-UDTreeView marking is still there after selecting other

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#2180]
### Steps to Reproduce

Just select on option in the three then select and other, as you can see it still has some kind of "marking" left.
![image](https://user-images.githubusercontent.com/76907327/224666566-28395eaa-e017-491c-b28b-ed8d402dd7dc.png)

In the example above I did first select W7 and then I did select XP.

### Expected behavior

```console
Old markings should not jut be lighter it should not be anything that indicate that it has been marked
```

### Actual behavior

```console
Show light color after changing marking option
```

### Environment data

Newest

**Comment by donlent** [comment]
Hi everybody!
Any news on that? Since you're fixing a lot of things in the TreeView it would be really cool if you also could take care of this one since it's really annoying...

Thanks a lot,
Don

**Comment by rwidmark** [comment]
@donlent issue is still there

**Comment by adamdriscoll** [comment]
I can't reproduce this. Just using this as an example: 

```
New-UDApp -Content { 
    New-UDTreeView -Node {
    New-UDTreeNode -Name 'Level 1' -Children {
        New-UDTreeNode -Name 'Level 2 - Item 1' 
        New-UDTreeNode -Name 'Level 2 - Item 2'
        New-UDTreeNode -Name 'Level 2 - Item 3' -Children {
            New-UDTreeNode -Name 'Level 3'
        }
    }
    New-UDTreeNode -Name '2Level 1' -Children {
        New-UDTreeNode -Name '2Level 2 - Item 1' 
        New-UDTreeNode -Name '2Level 2 - Item 2'
        New-UDTreeNode -Name '2Level 2 - Item 3' -Children {
            New-UDTreeNode -Name '2Level 3'
        }
    }
}
 } -Theme (Get-UDTheme -Name 1984)
```

![image](https://github.com/user-attachments/assets/6d6f9472-638e-48eb-a498-57a3a0c3056c)

I tried a few different themes and never saw this.

**Comment by rwidmark** [comment]
@adamdriscoll it seems that it's gone and working now. I know other people also notice this issue before but it works now :)
