### ISSUE TITLE
3.8.0 - Critital Problems with the License

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#2183]
### Steps to Reproduce

There is a critical issue with the license.
I think because of that an existing database cannot be read. The Service starts but Kestrel does not respond to http://localhost:5000 

Then, when you reset the DB it works but once you try to re-import the license this is the error message:
![image](https://user-images.githubusercontent.com/11975745/224892169-c1b3beae-10ae-42e1-838d-03de3f864e17.png)

### Expected behavior

```console
The current customer license should continue to work
```

### Actual behavior

```console
The customer license does not work anymore and breaks PSU
```

### Environment data

3.8.0

**Comment by donlent** [comment]
UPDATE:
Re-downloading the License from the website fixes the issue apparently. Anyway I'm of the opinion that this shouldn't happen or at least it should be clearly visible on the website that starting from this version it is needed to re-download the license from the ironman account...

**Comment by MattHarrisUltima** [comment]
Attaching debug logs from licenced container
[log20230314.txt](https://github.com/ironmansoftware/issues/files/10967113/log20230314.txt)
