### ISSUE TITLE
Show-UDToast is broken in 1.15.20

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#219]
**Describe the bug**
Try to push a button to show Show-UDToast don't work.

**Expected behavior**
You should get a pop-up

**Version**

It did work on 1.15.19 and was broken in 1.15.20 

**Additional context**
I did role back to 1.15.19 and then it started to work again.

Don't know if this effect 2.0.1 or 2.0.2 maybe a good thing if you check it out @adamdriscoll

**Comment by adamdriscoll** [comment]
This was fixed in 2.0.2. I'll get this merged into 1.5 and get it released this week.
