### ISSUE TITLE
New-UDIcon missing style parameters, only -Solid exists

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#2191]
### Steps to Reproduce

Now from 3.8 as you have Pro icons it would be nice if you also added the other parameters for the style of the icons.
Today only -Solid are existing.

Other parameters are:
-regular
-light
-thin
-duotone

### Expected behavior

```console
Select other parameters for the style of the icon
```

### Actual behavior

```console
Only -Solid exists
```

### Environment data

3.8.2

**Comment by rwidmark** [comment]
ETA on this? @mattselle

**Comment by adamdriscoll** [comment]
We need to remove the pro icons for PSU. After some discussion with FontAwesome, it looks like we cannot use them in a product  of this nature.

**Comment by rwidmark** [comment]
That was not good @adamdriscoll can the user somehow buy the licens for the icons and use them in psu?
Add the icon to a library or similar?
And then use new-udicon (searchpath)

More or less make a image file to a icon or use a .ico file ?
