### ISSUE TITLE
View Log (for dashboard) in VS Code returns error

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#2192]
### Steps to Reproduce

Clicking the "View Log" option in the popup menu on a dashboard in the VS Code PowerShell Universal extension gives an error.

![image](https://user-images.githubusercontent.com/5541154/225359579-a224d2f5-089d-4ec4-994c-df6803f004c3.png)

### Expected behavior

```console
Expect to see the log contents :-)
```

### Actual behavior

```console
Get an error toast instead.
```

### Environment data

PSU 3.8.1
VS Code 1.76.1
PowerShell Universal Extension 3.1.0
Universal module 3.7.11

**Comment by adamdriscoll** [comment]
This has been resolved in v4 versions.
