### ISSUE TITLE
Takes a long time to save a page

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2199]
### Steps to Reproduce

if i wait a really long time, it will finish

### Expected behavior

```console
save in a timely manner
```

### Actual behavior

```console
takes forever
```

### Environment data

PSU: 3.8.2
IIS: Nested

### Visuals

![image](https://user-images.githubusercontent.com/1987296/225446008-c03e4e24-91fb-49c6-b1e7-9e7a09e24745.png)

### Workaround
edit the file directly and then recycle the app pool :(

**Comment by Omzig** [comment]
I am also noticing this problem at the dashboard editor level:
![image](https://user-images.githubusercontent.com/1987296/225688882-15f323f2-e49e-41cd-a37d-a7850a154208.png)

**Comment by adamdriscoll** [comment]
Can you send some logs? It might be helpful to set them to debug level. I'm not seeing this locally with a service install or a nested IIS install.

**Comment by Omzig** [comment]
> Can you send some logs? It might be helpful to set them to debug level. I'm not seeing this locally with a service install or a nested IIS install.

I just upgraded to 3.8.4 (4463445595) and the problem went away. i will have to wait till 3.8.4 gets released and retest.

🐛 went under the 🪨 and is hiding from me right now, dumb roach.

**Comment by Omzig** [comment]
I am going to close this for now. 3.8.5+ seems to be working better.
