### ISSUE TITLE
Shell Occludes Tools and Modal Dialog

### ISSUE THREAD

**Issue by aluitink** [ironmansoftware/powershell-universal#22]
I noticed this when reducing the size of the pad window.

![image](https://user-images.githubusercontent.com/3255752/87700435-ed92e580-c75b-11ea-85a5-11cd6c64fabc.png)

![image](https://user-images.githubusercontent.com/3255752/87700759-79a50d00-c75c-11ea-91b7-8f5b80bd6227.png)

**Comment by adamdriscoll** [comment]
We no longer use this console so it's no longer an issue.
