### ISSUE TITLE
new page with a list of the dashboards

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2203]
### Summary of the new feature / enhancement

As a user/developer, I want a place that looks like the home page with all my dashboards on it in tile form or something so that i can quickly visit the dashboard that i want to work with. 

### Proposed technical implementation details (optional)

in the same way that admin/home works, it would be nice to click on a tile with said dashboard and view it. Maybe even give it a filter at the top to find said dashboard.

using the admin/dashboards view and trying to find the little [view] world icon and click on it, is troublesome when there are like 30 dashboards.

**Comment by JoriPS1** [comment]
Have you had a look at this?

https://ironmansoftware.com/powershell-universal/templates/template/PowerShell%20Universal%20Landing%20Page/1.0.2

I haven't personally tried it, but you should be able to add "all" the buttons and functionality you would normally see in the Admin page.

**Comment by Omzig** [comment]
> Have you had a look at this?
> 
> https://ironmansoftware.com/powershell-universal/templates/template/PowerShell%20Universal%20Landing%20Page/1.0.2
> 
> I haven't personally tried it, but you should be able to add "all" the buttons and functionality you would normally see in the Admin page.

that is cool, but i was more thinking about the developer side, not the user side ;)
