### ISSUE TITLE
BUG: Fix sticky headers in New-UDTable

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#2223]
It was pointed out to me that -StickyHeader exists, but doesn't work...

### Summary of the new feature / enhancement

As a user, I want the ability for headers to remain fixed while the table scrolls

### Proposed technical implementation details (optional)

The react table component has a stickyheader option...

https://mui.com/material-ui/react-table/#sticky-header

**Comment by Omzig** [comment]
oh my goodness! this would help me out SOOOOOOOOOOOO much

**Comment by donlent** [comment]
Have you seen that? It has already been reported but I think it cannot be done "better"... but maybe I'm wrong...
https://github.com/ironmansoftware/issues/issues/1119#issue-1203871179

**Comment by Omzig** [comment]
> Have you seen that? It has already been reported but I think it cannot be done "better"... but maybe I'm wrong... [#1119 (comment)](https://github.com/ironmansoftware/issues/issues/1119#issue-1203871179)

Seems to be a bug.

#AddBugTag

does not work :(
```powershell
 New-UDTable -Data $data2 -Dense -MaxHeight 415 -StickyHeader -Columns @(
```

**Comment by Omzig** [comment]
Once this is working, it would be nice to have a little blurb in the doc with how that works and the requirements to get it to work ;)
