### ISSUE TITLE
Job Handshake Timeout value

### ISSUE THREAD

**Issue by sulinm** [ironmansoftware/powershell-universal#2226]
When upgrading to the latest version the Job Handshake Timeout value reset to 5. Is there a way to have this value carry over when upgrading?

**Comment by schubfre** [comment]
If you are using the $PSUInstallfolder\appsettings.json please see https://github.com/ironmansoftware/issues/issues/2033#issuecomment-1412378224 for the correct way to persistently change custom settings.

**Comment by sulinm** [comment]
Thank You. I will make the change.


Mike C. Sulin
Senior IT Systems Administrator
115 N. Neil St.
Champaign, IL  61820
P: 314.579.5162
C: 314.412.4029

**Comment by adamdriscoll** [comment]
Thanks, @schubfre . This is expected behavior and that's the correct way to workaround it.
