### ISSUE TITLE
Platform Check

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2230]
### Summary of the new feature / enhancement

As a dev/support person, I want a new page that allows me to check the system so that when i am missing a feature or someone or something uninstalls something on me it will give me [x] feature installed. 

### Proposed technical implementation details (optional)

example, websockets should be installed, but wasn't, it would be nice to know from all my servers if said requirement is met

**Comment by adamdriscoll** [comment]
Compiling a list: 

- [x] Web Socket Support
- [x] Privileges for Service Account
- [x] Privileges for Run As Accounts
- [x] CPU \ Memory Recommendations

**Comment by Omzig** [comment]
Add this to the list! https://github.com/ironmansoftware/issues/issues/2251

**Comment by Omzig** [comment]
> Compiling a list:
> 
> * [ ]  Web Socket Support
> * [ ]  Privileges for Service Account
> * [ ]  Privileges for Run As Accounts
> * [ ]  CPU \ Memory Recommendations

Add this one to the list:
* [x] PSScriptAnalyzer - https://github.com/ironmansoftware/issues/issues/2251
