### ISSUE TITLE
New-UDIconButton are not aligned with the rest

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#2233]
### Steps to Reproduce

New-UDIconButton are not properly aligned with the rest of the GUI. The part in the circle are New-UDButtons
![Screenshot 2023-03-25 at 06 58 39](https://user-images.githubusercontent.com/76907327/227699681-2c8fb474-16a5-468e-a097-45565c61fd3e.png)

### Expected behavior

```console
That the New-UDButton should be aligned with the rest
```

### Actual behavior

```console
Are note aligned
```

### Environment data

3.8.3

**Comment by rwidmark** [comment]
@adamdriscoll guessing you did add the wrong milestone?

**Comment by rwidmark** [comment]
@adamdriscoll @mattselle any plans to fix this?

**Comment by adamdriscoll** [comment]
Can you please provide a code example for this?

**Comment by rwidmark** [comment]
This is solved as -Justified are existing now :)
