### ISSUE TITLE
UDForm - Input text slowness

### ISSUE THREAD

**Issue by DanielSjogren** [ironmansoftware/powershell-universal#2234]
When using New-UDForm and you have a lot of content, text input will be slow in the form, but not outside of the form.

Using an older framework in the Dashboard will make it faster.
Tried multiple browsers (Edge, Chrome and Firefox).

Version: 3.8.4
PS: 7.3.3
Framework: Latest

Code to test:
`New-UDForm -Content {
    $i = 1
    Do {
        New-UDTextbox -Id "txtTest$i" -Label "Testing $i - Inside of form" 
        $i+=1
    } Until ($i -eq 20)
    
} -OnSubmit { }
New-UDCard -Content { New-UDTextbox -Id 'txtTest' -Label "Testing - Outside of Form" -FullWidth }`

![Slowness in PSU forms](https://user-images.githubusercontent.com/40316868/227877142-4b9659c4-0203-4d21-b152-7063b119e9c7.gif)

**Comment by adamdriscoll** [comment]
@DanielSjogren - Thanks for the repo. I can reproduce this in Firefox. I'll keep you posted on what I find.
