### ISSUE TITLE
Checks for new version no longer occur

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2237]
### Steps to Reproduce

Rolling back to 3.8.3 (which is one version below current) does not produce a 'new version available' indicator in the PSU UI. 

### Expected behavior

```console
Recent versions of PSU should indicate if a newer version is available
```

### Actual behavior

```console
Recent versions of PSU do not indicate if a newer version is available
```

### Environment data

PSU 3.8.3 (one version below current)

Note that I confirmed this behavior on two different servers. One with MSI install and the other with ZIP.

**Comment by schubfre** [comment]
I have actually never seen this indicator on our installs. For me this hasn't worked at all in v3. I don't think it's a network problem on my end, because all three URLs Adam mentioned at https://forums.ironmansoftware.com/t/url-whitelisting/7430 are whitelisted. I can activate my online license, browse templates etc. and I never saw the new version indicator

**Comment by adamdriscoll** [comment]
Just tried this myself. It didn't work right away. 

I went into the hangfire dashboard and triggered the update check. 

<img width="261" alt="image" src="https://user-images.githubusercontent.com/1256531/228001654-196fee6e-50cd-4b9b-bd7d-a50d1bb28481.png">

Then it worked. 

![image](https://user-images.githubusercontent.com/1256531/228001536-190d4733-6087-4e19-9102-63a3e3e4adf7.png)

I was missing a URL in that list. Our blob storage has the this file: https://imsreleases.blob.core.windows.net/universal/production/v3-version.txt

**Comment by DataTraveler1** [comment]
Just wanted to follow up on this and mention that the checks are working as expected in 3.8.8

![image](https://user-images.githubusercontent.com/537287/229458446-8a4e4c5f-cb94-4fdf-9579-275ed7c8493d.png)
