### ISSUE TITLE
Telemetry could be repurposed for specific troubleshooting cases

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2238]
### Summary of the new feature / enhancement

As a current subscriber of PowerShell Universal, it would be great if the (currently disabled) Telemetry feature could be enhanced into an opt-only diagnostic/log-uploader to assist the staff with support cases. 

![image](https://user-images.githubusercontent.com/537287/227931053-c8c35c9a-65a0-4d69-9b69-a86e7fc4bf2e.png)

Bonus: The user could be presented with a consent form that explains how to see what log data was sent and to where.

### Proposed technical implementation details (optional)

The data would be sent in the same way that previous telemetry data was sent. Strict controls should be in place to prevent troubleshooting log data from being sent after it isn't needed (e.g. a Case number would have to be associated to telemetry data)

**Comment by adamdriscoll** [comment]
Going to close this in favor of the issue for uploading logs to support since that will be more useful.
