### ISSUE TITLE
New-UDIconButton missing ExtraSmall and ExtraLarge

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#2241]
### Steps to Reproduce

New-UDIconButton seem to be missing ExtraSmall and ExtraLarge

### Expected behavior

```console
That it should have ExtraSmall size and ExtraLarge Size
```

### Actual behavior

```console
Don't have ExtraSmall and ExtraLarge
```

### Environment data

PSU 3.8.4

**Comment by adamdriscoll** [comment]
IconButton does not define ExtraSmall or ExtraLarge: https://mui.com/material-ui/api/icon-button/#props
