### ISSUE TITLE
Random file went blank

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2242]
### Steps to Reproduce

i had an api that i had to restore from github main branch because it went blank at some point.

I have an endpoint setup to go to a path of endpoints/datawarehouse/filter-companie.ps1 and it went poof at some point, and i was not working on this api that i know of.

### Expected behavior

```console
not wipe out existing code
```

### Actual behavior

```console
cleared my ps1 file
```

### Environment data

PSU: 3.8.4

### Visuals

![image](https://user-images.githubusercontent.com/1987296/228249233-3ff791d2-9d86-4e0f-ba05-7deace0b56a5.png)

**Comment by adamdriscoll** [comment]
This is old  and I'm not sure this has ever happened again. If you are experiencing this issue still, we can reopen and try to track it down.
