### ISSUE TITLE
TreeView Fixes

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2246]
### Steps to Reproduce

- [x] If onNodeClicked is defined, -Expanded does not work.
- [x] OnNodeClicked isn't fired when the item is a leaf
- [x] Nodes do not have an ID and cannot be updated via *-UDElement

### Expected behavior

```console
More robust tree view
```

### Actual behavior

```console
Tree view isn't very robust
```

### Environment data

3.8.6

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/issues-with-treeviews/8916/2

**Comment by abbottbd** [comment]
If you're re-working treeview control then some other requests that would make it more useful for me (and probably others)...
1. Be able to set the tree view so that it isn't collapsable (or fully override the 'on click' event so that it doesn't cause the tree to collapse)
2. Be able to set the text/style/background of individual nodes (highlight specific node(s), even if it isn't the selected node)

**Comment by adamdriscoll** [comment]
@abbottbd - Some of these requests may make it into the 4.x or 3.9 releases if they aren't totally "bugs" but I'll slice and dice this issue into a new one if we need to.

**Comment by adamdriscoll** [comment]
In 3.8.7, you'll be able to use the following type of script to update nodes and set which as expanded. 

```
    New-UDTreeView -Id 'treeView' -Node {
        New-UDTreeNode -Name 'Level 1' -Children {
            New-UDTreeNode -Name 'Level 2 - Item 1' 
            New-UDTreeNode -Name 'Level 2 - Item 2'
            New-UDTreeNode -Name 'Level 2 - Item 3' -Children {
                New-UDTreeNode -Name 'Level 3' 
            }
        } -Id 'Root'
    }

    New-UDButton -Text 'Expand' -OnClick {
        Set-UDElement -Id 'treeView' -Properties @{
            expanded = @("Root")
        }
    }

    New-UDButton -Text 'Set Node' -OnClick {
        Set-UDElement -Id 'Root' -Properties @{
            label = "Update"
        }
    }
```

**Comment by adamdriscoll** [comment]
I've opened an issue to prevent collapse:
https://github.com/ironmansoftware/issues/issues/2252

You can change the style of specific nodes like this: 

```

    New-UDButton -Text 'Set Node' -OnClick {
        Set-UDElement -Id 'Root' -Properties @{
            label = "Update"
            style = @{
                background = "red"
            }
        }
    }
```
