### ISSUE TITLE
Format Document

### ISSUE THREAD

**Issue by carterduplessis** [ironmansoftware/powershell-universal#2251]
### Summary of the new feature / enhancement

It would be nice to be able to use the 'Format Document' feature. I usually do Shift + Alt + F to format my document in VS Code. In the embedded code box of the browser I can access the 'Format Document' feature by hitting F1 and finding it in the drop down menu. The only problem is that it doesn't seem to do anything.

![image](https://user-images.githubusercontent.com/91789171/228529891-d313c444-b99d-4165-b0f4-7c1aabfb1691.png)

I don't know how much of a challenge this would be. It's just a "Nice to have" kind of thing instead of having to copy and paste my code to VS Code to format it and moving it back into the browser. I could just use the VS Code PSU extension for editing but I have had a few issues with that and I haven't had the time to figure it out.

Carter

**Comment by adamdriscoll** [comment]
If you install PSScriptAnalyzer on the server, this will work. 

https://docs.powershelluniversal.com/development/editor#formatting

**Comment by Omzig** [comment]
> ### Summary of the new feature / enhancement
> It would be nice to be able to use the 'Format Document' feature. I usually do Shift + Alt + F to format my document in VS Code. In the embedded code box of the browser I can access the 'Format Document' feature by hitting F1 and finding it in the drop down menu. The only problem is that it doesn't seem to do anything.
> 
> ![image](https://user-images.githubusercontent.com/91789171/228529891-d313c444-b99d-4165-b0f4-7c1aabfb1691.png)
> 
> I don't know how much of a challenge this would be. It's just a "Nice to have" kind of thing instead of having to copy and paste my code to VS Code to format it and moving it back into the browser. I could just use the VS Code PSU extension for editing but I have had a few issues with that and I haven't had the time to figure it out.
> 
> Carter
> 
> ### Proposed technical implementation details (optional)
> _No response_

F8 is really nice

**Comment by carterduplessis** [comment]
Hi Adam,

I installed PSScriptAnalyzer under the -Scope AllUsers and it works great! Thanks so much!
