### ISSUE TITLE
Diagnostics Logs are empty

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2253]
### Steps to Reproduce

logs are empty, but there are some on the hard drive.

### Expected behavior

```console
show logs
```

### Actual behavior

```console
blank
```

### Environment data

PSU: 3.8.6
IIS: Nested

### Visuals

![image](https://user-images.githubusercontent.com/1987296/228652558-9f0c6eec-ccf6-4994-9301-d7e3fd5e7c7a.png)

**Comment by adamdriscoll** [comment]
Only log messages that are written while that window is open will be shown. It just has a websocket connection to the server and will receive new log messages. 

Improving this is part of the broader "centralized logging" story in v4.

**Comment by Omzig** [comment]
sweet, bring it on! i cannot wait to upgrade to v4, even though i am loving 3.8.x
