### ISSUE TITLE
Move Actions column to the far left instead of far right.

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2261]
### Summary of the new feature / enhancement

As an admin, I want the actions (edit/delete/etc) column moved to the first column so that when the other data on the screen pushes it off to the right, i do not have to scroll to find the said action button. 

### Proposed technical implementation details (optional)

reorder columns to make better use of the space in the api and dashboard editors

**Comment by Omzig** [comment]
@adamdriscoll, is there room to get this in 4.0?

**Comment by adamdriscoll** [comment]
This is actually partially complete. The actions are moved over but after some review, it looks like we need to work on some of the formatting on some pages. The action column is taking up too much space in places.

**Comment by Omzig** [comment]
> This is actually partially complete. The actions are moved over but after some review, it looks like we need to work on some of the formatting on some pages. The action column is taking up too much space in places.

thank you soooooooooooooooooo much for working on this for 4.0!!!!
