### ISSUE TITLE
Windows Auth - User Session is listed an anonymous

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2262]
### Steps to Reproduce

Not sure exactly the root cause of this one but it seems like in certain circumstances, the user sessions window displays Anonymous instead of the user accessing the dashboard when using Windows Auth. 

### Expected behavior

```console
User name is displayed
```

### Actual behavior

```console
Anonymous is displayed
```

### Environment data

3.8.7

**Comment by schubfre** [comment]
I got the same behaviour in 3.8.12 with LiteDB and Windows Auth. And it is not in certain circumstances but seems to be always to be the case when accessing dashboards.

![image](https://user-images.githubusercontent.com/28289080/236137345-b6a96dfc-98d9-4826-b01c-b2db097b34a7.png)
