### ISSUE TITLE
New-UDPage should substitute additional characters in the Name parameter

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2263]
### Steps to Reproduce

1. Use New-UDPage to create a new Universal Dashboard page
2. Include the # character (i.e. U+0023) in the Name parameter (this forms the eventual URL)·
3. Observe the error 404 that will result when viewing the dashboard page

Note that space characters are replaced with a hyphen, thus this bug report is more of a feature request to add more substitutions.

· or use the percentage sign (i.e. U+0025)

### Expected behavior

```console
New-UDPage should substitute the pound/percent characters with an underscore or a similarly compliant substitute
```

### Actual behavior

```console
New-UDPage does not substitute the pound/percent characters with an underscore or a similarly compliant substitute
```

### Environment data

PSU 3.8.7

**Comment by DataTraveler1** [comment]
@adamdriscoll - Please see PR 1079

**Comment by Omzig** [comment]
This is almost the same problem as creating a new dashboard with the name of "My dashboard's are cool" this is an invalid file name :(
