### ISSUE TITLE
Output missing in rendered column

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#2267]
### Steps to Reproduce

When I render a value which is numeric but is a string, it doesn't show up in the table (unless I wrap it in New-UDTypograhpy)

```powershell
    $data = Get-Service | Select-Object -First 5
    New-UDTable -Data $data -Columns @(
        New-UDTableColumn -Property Name -Width 350
        New-UDTableColumn -Property Value -Render { "30" }
        New-UDTableColumn -Property Value2 -Render { New-UDTypography -text "30" }
        New-UDTableColumn -Property Value3 -Render { "A30" }

    )
```

### Expected behavior

```console
Should see 5 rows in a table with a Value column of 30
```

### Actual behavior

```console
See 5 rows with blank Value column.  Typography and non-numeric data works fine.
```

### Environment data

PSU 3.8.7

### Visuals

![image](https://user-images.githubusercontent.com/5541154/229234576-f120be08-61c0-4270-9612-a548d67549d6.png)

**Comment by Omzig** [comment]
#roach, we killed it like 10 different ways before we figured out what the problem was.
