### ISSUE TITLE
TreeView -expanded doesn't work as described

### ISSUE THREAD

**Issue by abbottbd** [ironmansoftware/powershell-universal#2272]
### Steps to Reproduce

1. Create a tree view using the example code: 
New-UDTreeView -Node {
    New-UDTreeNode -Name 'Level 1' -Children {
        New-UDTreeNode -Name 'Level 2 - Item 1' 
        New-UDTreeNode -Name 'Level 2 - Item 2'
        New-UDTreeNode -Name 'Level 2 - Item 3' -Children {
            New-UDTreeNode -Name 'Level 3'
        }
    }
}

Result: Everything works as expected

Add the -expanded property on the TreeView
New-UDTreeView -Node {
    New-UDTreeNode -Name 'Level 1' -Children {
        New-UDTreeNode -Name 'Level 2 - Item 1' 
        New-UDTreeNode -Name 'Level 2 - Item 2'
        New-UDTreeNode -Name 'Level 2 - Item 3' -Children {
            New-UDTreeNode -Name 'Level 3'
        }
    }
} -Expanded:$true

Result: The tree view is collapsed by default and can not be expanded by clicking on the nodes.

### Expected behavior

```console
when using -expanded:$true the tree view should load in the 'fully expanded' format.
-expanded:$true probably shouldn't have any impact on the ability to click on a node and have it expand or collapse as a result of the click.
```

### Actual behavior

```console
when using -expanded:$true the tree view is displayed in a collapsed state
When using -expanded:$true clicking on a node doesn't cause it to expand or collapse
```

### Environment data

3.8.8 on windows server 2022, installed using MSI installer.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/issues-with-treeviews/8916/4
