### ISSUE TITLE
New-UDTextbox -OnEnter {} does not work

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2273]
### Steps to Reproduce

using this doc, the component does not fire, i tried putting write-host in the onEnter and nothing writes to the logs on enter:
https://docs.powershelluniversal.com/userinterfaces/dashboards/components/inputs/textbox#onenter

### Expected behavior

```console
onEnter to fire
```

### Actual behavior

```console
nothing happens
```

### Environment data

PSU: 3.8.8
IIS: Nested

**Comment by adamdriscoll** [comment]
This was a problem with the example. After fixing it, the OnEnter fires. It was actually a problem with Invoke-UDEndpoint.
