### ISSUE TITLE
An error occurred: Unable to find type [certvalidation].

### ISSUE THREAD

**Issue by gitbute** [ironmansoftware/powershell-universal#228]
**Describe the bug**
An error occurred: Unable to find type [certvalidation].
Same issue as: https://github.com/ironmansoftware/powershell-universal/issues/37

**To Reproduce**
See other issue

**Expected behavior**
See other issue

**Version**

Version Number: 2.0.3 nightly 923438082
Dashboard Framework (if applicable): 3.4.2
Operating System: Windows Server 2016

**Comment by adamdriscoll** [comment]
@gitbute - I wonder if this is a dependency issue of some kind. I still don't have this issue on Windows 10 it might be how I'm hosting it or if I have something else installed on there. 

Can you let me know how you are hosting it? MSI?

**Comment by gitbute** [comment]
@adamdriscoll  - I host it in IIS. Not sure where the problem could be..

**Comment by adamdriscoll** [comment]
We have seen a similar issue using New-WebServiceProxy which also attempts to compile C# code in IIS. More discussion here: https://forums.ironmansoftware.com/t/unable-to-call-new-webserviceproxy-in-a-script/4867/12

One potential work around would be to use the `-OutputAssembly` of `Add-Type` to create a DLL outside of PSU. Then, within your script use `Import-Module` to load the DLL. This would avoid calling the C# compiler and would avoid the issue.

**Comment by gitbute** [comment]
This does indeed work, and i can live with that as a workaround / permanent solution ;-)

Best thanks for all your work!
