### ISSUE TITLE
Add helper text to New-UDTextbox

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2285]
### Summary of the new feature / enhancement

As a developer, I want to be able to set -HelperText on the UDTextbox so that i can provide some details to the end user about what to put in the box. 
- https://mui.com/material-ui/react-text-field/#components

### Proposed technical implementation details (optional)

![image](https://user-images.githubusercontent.com/1987296/230177584-2f0fe136-caca-4345-b67b-459b2c6afbae.png)

**Comment by rwidmark** [comment]
That would spare me some code. Now I'm doing it with UDStack and then font size 12 for the typography
