### ISSUE TITLE
TreeView $evendata returns the wrong id

### ISSUE THREAD

**Issue by abbottbd** [ironmansoftware/powershell-universal#2289]
### Steps to Reproduce

When clicking on any node in a tree view that is not specified as a leaf node, the returned $eventdata ID value is alternatly either the node that was clicked, or its parent node, dependong on if the node was expanded or colapsed by the click. 

I would expect that the returned EventData.ID should be the ID of the node that was clicked, regardless of if it was expanded by the click, or colapsed by the click.

Consider the following example code:
                New-UDTreeView -Id 'treeView' -Node {
                    New-UDTreeNode -Name 'Level 1' -id "1-1" -Children {
                        New-UDTreeNode -Name 'Level 2 - Item 1' -id "2-1" -leaf:$true
                        New-UDTreeNode -Name 'Level 2 - Item 2' -id "2-2"
                        New-UDTreeNode -Name 'Level 2 - Item 3' -id "2-3" -Children {
                            New-UDTreeNode -Name 'Level 3' -id "3-1"
                        }
                    }  
                }-OnNodeClicked{ Show-UDToast -Message ($EventData | ConvertTo-Json) -Duration 10000}

Expand node 'level 1'
The first time you click on 'Level 2 - Item 2' the $eventData.ID will be '2-2'.
The Second time you click on 'Level 2 - Item 2' the $eventdata.id will be '1-1'
now consider 'Level 2 - Item 1', each time you click on it the $evendata.id will be '2-1'
now expand all levels fully
When you colapse the root node 'Level 1' the $evendata.id will be '3-1'
When you expand the roo node 'level 1' again the $Eventdata.id will be '1-1'

### Expected behavior

```console
Anytime a node is clicked the $eventdata should indicate the ID of the node that was clicked upon.
```

### Actual behavior

```console
Eventdata doesn't always contain the ID of the node that was clicked.
```

### Environment data

3.8.8 on windows server 2020 installed by MSI package.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/issues-with-treeviews/8916/4
