### ISSUE TITLE
Dark Theme setting not global

### ISSUE THREAD

**Issue by wdomon** [ironmansoftware/powershell-universal#2292]
### Steps to Reproduce

In Powershell Universal:
Settings > General > Admin Console > Dark Theme toggle

1. Signed in via AzureAD OIDC using a private browser
2. Set the toggle to "Yes"
3. Close the private browser
4. Sign in via AzureAD OIDC using a new private browser window
5. Toggle has changed back to "No"

### Expected behavior

```console
Setting looks to be intended to be global, so all new and existing users that sign in after this has been changed to "Yes" should see a Dark Theme by default. However, this gets reset to "No" for every user individually on every session.
```

### Actual behavior

```console
This toggle should be persistent and be changing the global default - allowing individual admin users to change their own preference after they sign in (using the toggle at the top of the admin console).
```

### Environment data

PSU 3.7.14
Windows Server 2022

**Comment by timosemmler** [comment]
When using two servers in the cluster, the user must also set the setting twice, depending on which server you come out on. I therefore see a global user setting as more than necessary here.

Thanks @adamdriscoll  that you have included this as a goal!
