### ISSUE TITLE
Hide Run As \ Environment Globally

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2294]
### Summary of the new feature / enhancement

We should add a setting to globally hide run as and environment.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/globally-hide-run-on-and-environment-on-parameter-dialog-when-running-scripts/8986/2

**Comment by wdomon** [comment]
In addition, the "Run On" should have a setting to globally hide in the same way as "Run As" and "Environment"
