### ISSUE TITLE
Links not following theme

### ISSUE THREAD

**Issue by jhadvan** [ironmansoftware/powershell-universal#2296]
### Steps to Reproduce

I am experiencing that the hyper link URL is staying at a static color not following the theme

Issue made on the forum
https://forums.ironmansoftware.com/t/markdown-hyperlink-not-following-theme/8987/3

### Expected behavior

```console
Link to follow theme
```

### Actual behavior

```console
Hyperlink URL color is staying a static color
```

### Environment data

 3.8.8

### Visuals

![image](https://user-images.githubusercontent.com/116764491/230658491-4564f636-da60-4ec1-9595-4aba7ba962b6.png)

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/markdown-hyperlink-not-following-theme/8987/4

**Comment by Omzig** [comment]
@adamdriscoll, can we add this to 4.1 or 4.0.9?

**Comment by adamdriscoll** [comment]
This is way more involved than I would have imagined so I am moving this to 4.1.

**Comment by Omzig** [comment]
thank you for trying to get this into 4.1, @adamdriscoll

**Comment by Omzig** [comment]
![image](https://github.com/ironmansoftware/issues/assets/1987296/123cb193-2406-4505-8f21-57563dbc53a3)
Did this get merged into 4.1? This change does not seem to be in 4.1 :(

**Comment by adamdriscoll** [comment]
I'm not experiencing this.

```
New-UDApp -Content {
    New-UDMarkdown -Children "[Google.com](http://www.google.com)"
    New-UDLink -Text 'Google.com' -url http://www.google.com
}
```

![image](https://github.com/ironmansoftware/issues/assets/1256531/433a82ab-32e0-4661-b1ce-93bb9e92064e)

![image](https://github.com/ironmansoftware/issues/assets/1256531/bb8c79db-b95e-4ee3-ad30-026b11f0d08a)

**Comment by adamdriscoll** [comment]
With MaterialUI theme. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/d2a55367-47a5-4575-a410-c16e3b227403)

![image](https://github.com/ironmansoftware/issues/assets/1256531/f700c955-26eb-4ca1-a800-e7f1e19b1958)

**Comment by Omzig** [comment]
OHHHHHHHHHH, we converted it to html and used this:
```
New-UDHtml -Markup '<a href="www.google.com">Google.com</a>'
```
new enhancement then :(
