### ISSUE TITLE
How to enable/disable analysis rules.

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/powershell-universal#23]
Most likely my fault, but cannot figure out how to enable/disable rules in Options->Powershell Rules->Analysis.
No matter what I click - left or right -  I can't see any effect in the "Enabled" column.
All rules seems to be Enabled.

[HowToEnableOrDisableRules - Desktop 2020.06.02 - 16.25.04.03.zip](https://github.com/ironmansoftware/poshtools-issues/files/4717905/HowToEnableOrDisableRules.-.Desktop.2020.06.02.-.16.25.04.03.zip)

**Comment by adamdriscoll** [comment]
We've completely rebuilt this UI so it no longer uses the WinForm version and uses WPF. As a result, this issue will be resolved in the next version.
