### ISSUE TITLE
Include the 'End of Support' date value 📆 as a read-only property within each PSU build

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2301]
### Summary of the new feature / enhancement

Consider including the 'End of Support' date value 📆 as a read-only property (for each build) within the PSU Settings. In this way, the date could be derived by way of Get-PSUSetting.

### Proposed technical implementation details (optional)

![image](https://user-images.githubusercontent.com/537287/230734556-91c48169-eac4-4d1d-8b9e-c63ca401872f.png)
###### figure shows the feature imagined 💭

**Comment by adamdriscoll** [comment]
I don't want to actually bake this into the product in-case we change our mind later on for whatever reason.
