### ISSUE TITLE
$EventData / $Body missing updated data

### ISSUE THREAD

**Issue by DanielSjogren** [ironmansoftware/powershell-universal#2304]
### Steps to Reproduce

$Body doesn't pick up updated data. If you have a Set-UDElement that updates a field, that value is not present in the event data.

Example. Write something in the first field and click on the button to insert the value into field 2. The $Body will still contain the value "Test" unless you modify the value manually.

New-UDForm -Content {
    New-UDTextbox -Id 'txtField1'
    New-UDTextbox -Id 'txtField2' -value "Test" -disabled
    New-UDButton -Text "Update field2 with field1 data" -OnClick {             
        $txtField1Value = (Get-UDElement -Id 'txtField1').value
        Set-UDElement -id 'txtField2' -Properties @{ Value = $txtField1Value }
    }
}-OnSubmit {
            New-UDElement -Tag 'div' -Id 'result' -Content {$Body}
}

### Expected behavior

```console
txtField2 should be the value shown in the text field after clicking the button
```

### Actual behavior

```console
txtField2 will be "Test"
```

### Environment data

PSU: 3.8.9
PS 7.3.3
Windows Server 2022

### Visuals

{"$type":"System.Collections.Hashtable, System.Private.CoreLib","txtField2":"Test","txtField1":"Correct tex"}

**Comment by Omzig** [comment]
confirmed

**Comment by Omzig** [comment]
Support Ticket #5203
