### ISSUE TITLE
Live Doc is kranky

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2315]
### Steps to Reproduce

live doc is missing lots of icons and menu items

### Expected behavior

```console
content visible
```

### Actual behavior

```console
missing content
```

### Environment data

PSU: 4.0.0-beta2 (4694969633)
IIS: Nested

### Visuals

![image](https://user-images.githubusercontent.com/1987296/232074876-d4f6b4a3-2035-4bc6-9927-4a25cc9acb01.png)

**Comment by adamdriscoll** [comment]
@Omzig - I made a change to icons and it's causing this. It was originally to implement all the pro icons, but since we can't do that, I'll likely just roll this back and get it this fixed.
