### ISSUE TITLE
Identities are duplicated

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2322]
### Version

3.8.9

### Severity

Low

### Steps to Reproduce

Identities duplicate sometimes. Seems to happen with windows auth and SQL. 

### Expected behavior

```console
No duplicates
```

### Actual behavior

```console
Duplicates
```

### Environment data

Windows Auth
SQL

**Comment by Omzig** [comment]
also happens without SQL
