### ISSUE TITLE
UploadButton Color

### ISSUE THREAD

**Issue by jhadvan** [ironmansoftware/powershell-universal#2326]
### Version

3.8.9

### Severity

Visual

### Steps to Reproduce

```
New-UDUpload -Text "Upload"  -OnUpload {
 }
```

### Expected behavior

```console
I would have expected the NewUpload Button to follow the same theming ad UDButton using the primary as a defaulted color.
```

### Actual behavior

```console
UDUpload button has a different color theme than the rest of the button
```

### Environment data

3.8.9

### Visuals

Dark Mode:
![image](https://user-images.githubusercontent.com/116764491/232921607-4d9e4c10-040b-4606-af67-e9fb172a4cfd.png)

Light Mode:
![image](https://user-images.githubusercontent.com/116764491/232921644-48664c3e-7aa6-43cf-8a26-8118e3c51814.png)

**Comment by Omzig** [comment]
# workaround
```powershell
New-UDUpload -Text "Upload" -color "primary"
```
