### ISSUE TITLE
Desktop Mode does not start

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2328]
### Version

3.8.9

### Severity

Critical

### Steps to Reproduce

Desktop mode shows the loading indicator forever. The server is starting in the background properly but for some reason the desktop app never connects to it. 

### Expected behavior

```console
Desktop starts.
```

### Actual behavior

```console
Desktop doesn't start.
```

### Environment data

This works on 3.8.9 so it was introduced in 3.8.10.

**Comment by Omzig** [comment]
I have noticed this on my home computer, but does not happen on my corp laptop.

My home computer is a hex core, it is massive, and can process a dvd for the apple tv in like 5-10min.

**Comment by adamdriscoll** [comment]
We have a mismatched assembly version due to a bad merge. I'm a bit surprised this works with the server version too but here we are....
