### ISSUE TITLE
Values from a secret variable in Pages are exposed in script parameters

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2329]
### Version

3.8.9

### Severity

Low

### Steps to Reproduce

Create a script that accepts a string parameter
Create a form page with a password field
Run the form
Notice the value from the password field is displayed in the parameters for the job

### Expected behavior

```console
Parameter is masked
```

### Actual behavior

```console
Parameter is displayed
```

### Environment data

3.8.9

**Comment by sulinm** [comment]
I was wondering why you are not planning on making this change? We have two requirements for pages that require user name and passwords.
