### ISSUE TITLE
PSU 4.0 Beta: Please make Docker containers available as well

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#2334]
### Summary of the new feature / enhancement

I like the flexibility of Docker, K8S, etc. a lot because it allows to create a test container in a matter of seconds.
As of now you don't provide docker images for the 4.0 beta release. It would be cool if you could publish these as well.

### Proposed technical implementation details (optional)

Publish Docker Images on Docker Hub for 4.x beta / rc releases as well

**Comment by adamdriscoll** [comment]
Beta2 will publish a preview tag and a 4.0.0-beta2 tag.

**Comment by donlent** [comment]
Thank you so much 👍🏻😊
