### ISSUE TITLE
Components do not load

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2336]
### Version

3.8.10

### Severity

Low

### Steps to Reproduce

when i use the marketplace to install a component, it doesn't load any in the /components folders
- Components in the asset folder do not load
- Components moved into the repo does not work

### Expected behavior

```console
module loads
```

### Actual behavior

```console
module does not load
```

### Additional Environment data

IIS: Nested

### Workaround
```powershell
Install-Module UniversalDashboard.TinyMCE
```

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/components-load-issue/9055/3

**Comment by rwidmark** [comment]
@adamdriscoll and @Omzig I think this is related to a bug that I did find yesterday.
If you create a component with only one option in the FunctionsToExport in the .psd1 file it will not load or work.
But if you add some dummy function in it also then it will work.

Conclusion is that if FunctionsToExport only contains one function then it will not work but if it contain more then one then ti will start to work.

Example:
Will not work:
FunctionsToExport = "Get-ProIcon"

This will work:
FunctionsToExport = "Get-ProIcon", "Get-DummyFunction"
