### ISSUE TITLE
[3.8.11] No replacement for Pro icons

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#2338]
### Version

3.8.9

### Severity

Visual

### Steps to Reproduce

@adamdriscoll  as you know you have in the release notes for 3.8.11 removed the Pro icons.
I understand why you do it but you should include the new solution that's in v4 in 3.8.11 as you have removed the pro icons here.

Now if you remove the Pro icons without any other solution for us we are kind of stuck with 3.8.10.

So please add the New-UDHelmet thing in 3.8.11

### Expected behavior

```console
Option so add own icons or similar, the solution that you have for v4 should be added here in 3.8.11
```

### Actual behavior

```console
No solution offered.
```

**Comment by adamdriscoll** [comment]
We will be adding this in 3.9.
