### ISSUE TITLE
Replace FontAwesome Pro icons with Material Design Icons

### ISSUE THREAD

**Issue by serialscriptr** [ironmansoftware/powershell-universal#2343]
### Summary of the new feature / enhancement

With the recent removal of the FontAwesome Pro icons I think a suitable replacement would be to implement the MDI (material design icon) library for use within powershell universal. Its a much bigger library and completely free and open source. Projects like Home Assistant already use it for their icon libraries. 

Here is one of many websites where these icons can be viewed and searched: https://pictogrammers.com/library/mdi/

**Comment by donlent** [comment]
Hey @serialscriptr 

There are multiple issues opened on the tracker realted to (custom) icons. Have you seen these for example?
https://github.com/ironmansoftware/issues/issues/640
https://github.com/ironmansoftware/issues/issues/2338

So I'm not sure if adam & team can "easily" implement your wish because this would be a major breaking change for everybody...

In any case you'll be able to specify your custom icon library soon... no matter from where they come. :-) I'm personally very happy about this upcoming change.. :-)

Take care,
Don

**Comment by Omzig** [comment]
@adamdriscoll, this icon set is massive, maybe to keep breaking changes from happening we create a new cmdlet like `New-UDMaterialIcon`
- they have different things we can manipulate https://fonts.google.com/icons?icon.set=Material+Symbols

**Comment by donlent** [comment]
Good suggestion @Omzig  :-)
This would certainly avoid a breaking change. However I think that it could be solved a little bit more "elegant", also w/o breaking anything.

The New-UDIcon cmdlet should be expaned with additional parameters, something like that:

**Default (taking "FontAwesome", like today):**
`New-UDIcon -Icon 'xyz'`
=> won't break anything for existing environments

**Additionally for any pre-defined free / opensource icon set it could be solved like that:**

**_New Icon Set: Material_**
`New-UDIcon -Material 'xyz'`

**_New Icon Set: Bootstrap_**
`New-UDIcon -Bootstrap 'xyz'`

Any other local or custom / non-predefined icon set it would then be solved by the UD-Helmet solution proposed on #640

Of course this in only a suggestion based on my thoughts.. But I'm sure adam and team will come up with the most efficient and long lasting solution. :-)

**Comment by Omzig** [comment]
> Good suggestion @Omzig :-) This would certainly avoid a breaking change. However I think that it could be solved a little bit more "elegant", also w/o breaking anything.
> 
> The New-UDIcon cmdlet should be expaned with additional parameters, something like that:
> 
> **Default (taking "FontAwesome", like today):** `New-UDIcon -Icon 'xyz'` => won't break anything for existing environments
> 
> **Additionally for any pre-defined free / opensource icon set it could be solved like that:**
> 
> **_New Icon Set: Material_** `New-UDIcon -Material 'xyz'`
> 
> **_New Icon Set: Bootstrap_** `New-UDIcon -Bootstrap 'xyz'`
> 
> Any other local or custom / non-predefined icon set it would then be solved by the UD-Helmet solution proposed on #640
> 
> Of course this in only a suggestion based on my thoughts.. But I'm sure adam and team will come up with the most efficient and long lasting solution. :-)

ya, this would be cool, we would need a completely different cmdlet set for each because -Material has different parameters that can be set like
- -Grade
- -Fill
- -Weight
- -Size
- -disabled (https://developers.google.com/fonts/docs/material_icons)
- can be dark and light theme targeted

**Comment by adamdriscoll** [comment]
I'd really rather not include a ton of icon sets directly in PSU. It really complicates New-UDIcon and bloats the PSU client library. For example, the Material Icon font is 2.7 MB. 

<img width="691" alt="image" src="https://user-images.githubusercontent.com/1256531/234338495-11f12f73-473c-4ee1-89e1-44e33967beeb.png">

What'd I'd rather do is create modules for each icon set that can be installed on demand. These modules would be open source.

```
New-UDMaterialIcon # material specific props here
```

Then rather than trying to reuse the New-UDIcon cmdlet for everything, you can just use those icon packs directly on other parameters that accept icons. 

```
Import-Module Universal.MaterialIcon
New-UDAlert -Icon (New-UDMaterialIcon) 
```

**Comment by Omzig** [comment]
> I'd really rather not include a ton of icon sets directly in PSU. It really complicates New-UDIcon and bloats the PSU client library. For example, the Material Icon font is 2.7 MB.
> 
> <img alt="image" width="691" src="https://user-images.githubusercontent.com/1256531/234338495-11f12f73-473c-4ee1-89e1-44e33967beeb.png">
> 
> What'd I'd rather do is create modules for each icon set that can be installed on demand. These modules would be open source.
> 
> ```
> New-UDMaterialIcon # material specific props here
> ```
> 
> Then rather than trying to reuse the New-UDIcon cmdlet for everything, you can just use those icon packs directly on other parameters that accept icons.
> 
> ```
> Import-Module Universal.MaterialIcon
> New-UDAlert -Icon (New-UDMaterialIcon) 
> ```

then you could drop the New-UDIcon to a module like Universal.Fontawesome?

**Comment by donlent** [comment]
Hey @adamdriscoll 
This is exactly what I meant with my sentence: "I'm sure adam and team will come up with the most efficient and long lasting solution. :-)"

So thanks a lot!  Sounds great to me! :-) 👍

**Comment by adamdriscoll** [comment]
FYI - https://github.com/ironmansoftware/universal-icons
https://www.powershellgallery.com/packages/Universal.Icons.MaterialDesign/0.0.1

**Comment by rwidmark** [comment]
This issue are already resolved in 4.0 and also according to the milestone it will be resolved in 3.9

**Comment by rwidmark** [comment]
> FYI - https://github.com/ironmansoftware/universal-icons
> 
> https://www.powershellgallery.com/packages/Universal.Icons.MaterialDesign/0.0.1

Wow, your fast.
I'll try it out later today.

**Comment by rwidmark** [comment]
@adamdriscoll  Works like a charm, I did install all of the different modules. But some of them are missing for example:
* Circum Icons
* Github Octicons icons

Can I somehow re-write the function to collect them?

**Comment by rwidmark** [comment]
@adamdriscoll 
It seem that it's not possible to include it with for example Autocomplete.

Code example
```
New-UDAutocomplete -id "autocompleteUserName" -Icon (New-UDFeatherIcon -Icon "FaUser") -Label "Användare" -OnLoadOptions {
```

![image](https://user-images.githubusercontent.com/76907327/234527172-e924f2d5-59e2-4e82-b7fc-04174af50cb8.png)

**Comment by adamdriscoll** [comment]
For the missing icon sets, you'd need to replicate what is happening in each of those folders. I only did a subset of the icons. 

For example, this implements the bootstrap icons. 

https://github.com/ironmansoftware/universal-icons/tree/main/Bootstrap

As for the error you are seeing, you won't be able to use these icons in v3 yet. We need to update the components to accept the icons. This will work in recent builds of v4.

**Comment by rwidmark** [comment]
@adamdriscoll the icons works fine with v3 only thing is when your going to use it with -Icons () inside an other component.

I can't really understand how I can modify it to work with all of the icons at the react icon page.
Or create a function for each one of the sets of icons.

**Comment by adamdriscoll** [comment]
@rstolpe 

> the icons works fine with v3 only thing is when your going to use it with -Icons () inside an other component.

This will require 3.9 to work. We needed to make a change to those commands to support different icons. 

> I can't really understand how I can modify it to work with all of the icons at the react icon page.
Or create a function for each one of the sets of icons.

Is there a particular icon set you are looking for? We just need to create a module like this: https://github.com/ironmansoftware/universal-modules/tree/main/Components/Icons.Bootstrap

The only reason you wouldn't want to create a single module will all the icon sets is that it will be 10s of megabytes to load in the browser.

**Comment by rwidmark** [comment]
@adamdriscoll 
https://react-icons.github.io/react-icons/icons?name=di
https://react-icons.github.io/react-icons/icons?name=gr
https://react-icons.github.io/react-icons/icons?name=gr
https://react-icons.github.io/react-icons/icons?name=si
https://react-icons.github.io/react-icons/icons?name=go

Basically it seems that I just need to change the end "=name" but I can't figure it out in your module.

**Comment by rwidmark** [comment]
> @rstolpe 
> 
> 
> 
> > the icons works fine with v3 only thing is when your going to use it with -Icons () inside an other component.
> 
> 
> 
> This will require 3.9 to work. We needed to make a change to those commands to support different icons. 
> 
> 
> 
> > I can't really understand how I can modify it to work with all of the icons at the react icon page.
> 
> Or create a function for each one of the sets of icons.
> 
> 
> 
> Is there a particular icon set you are looking for? We just need to create a module like this: https://github.com/ironmansoftware/universal-modules/tree/main/Components/Icons.Bootstrap
> 
> 
> 
> The only reason you wouldn't want to create a single module will all the icon sets is that it will be 10s of megabytes to load in the browser. 

Regarding the single module so it loads all icons at once? I thought it did fetch each icon when it was called for.
Then I see the issue with a single module :)
