### ISSUE TITLE
git setup on existing system fails

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2344]
### Version

3.8.11

### Severity

Low

### Steps to Reproduce

i am experiencing a problem with having an existing repo in psu populated and then trying to turn on git sync.

### Expected behavior

```console
save changes would commit to branch all the changes
```

### Actual behavior

```console
save changes does not know that everything is new in the github repo
it did not create a .git folder in the repo folder
```

### Additional Environment data

IIS: Nested

### Workaround
- Clone repo to temp folder
- move the .git folder that was create into the /repository folder 
- recycle app pool
- click `save changes`, give commit a comment and `commit changes`
- in a cli on the server, `git push` from the repo folder to get it up to the git repo

**Comment by donlent** [comment]
Hi @Omzig 
Is this maybe related to my issue?
...at least it sounds like that... :-)
https://forums.ironmansoftware.com/t/git-bug-initial-configuration-does-not-succeed/9064

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/git-bug-initial-configuration-does-not-succeed/9064/3

**Comment by adamdriscoll** [comment]
@donlent - This was definitely the issue.
