### ISSUE TITLE
Git: Set differing push / pull branches

### ISSUE THREAD

**Issue by KylerStr** [ironmansoftware/powershell-universal#2348]
### Summary of the new feature / enhancement

Implementing the ability to select a branch for PSUniversal to push to, and a differing branch to pull from, would be a fantastic feature. 

Currently, if someone edits a script through the GUI for PSUniversal, it pushes directly to the main branch. This circumvents forced approval processes through things such as gitlab, or github. This also occurs if using the Visual Studio plugin.

Allowing a separate push branch to be specified would allow all changes to go to a separate branch, and need to be merged back into main, which would then allow it to pull back down to all nodes.

This could cause confusion about making changes, and them not being available within PSU after commiting these changes. But it would also allow people to easily create scripts, fill in the relevant data, set up schedules, etc. from the GUI, while still forcing approvals through a GIT manager. This fixes a current security loophole of being able to write directly to main, circumventing any git manager security settings.

### Proposed technical implementation details (optional)

Having GIT pushing occur to a seperate branch, that is specified from the settings of PSU.

GIT pulls would occur from a branch also specified, allowing two branches to be used.

This would discard changes, but push them to the remote in a branch capable of being reviewed. This could either create new branches per push, or push to a perpetual branch that is just merged into main as needed.

**Comment by Omzig** [comment]
we have our dev server hooked up to the dev branch and the prod server hooked up to main. We commit on dev and then PR it into main/prod.

**Comment by adamdriscoll** [comment]
I'm going to agree with Omzig on this. This really isn't a great git flow and overcomplicates the core value add of PSU.

**Comment by MikeShepard** [comment]
From my perspective, the comment from @Omzig encapsulates the beauty of PSU's git integration.  Simple to configure in the admin console, use PR's in GitHub to do the approval side.

CI/CD without the pain.

**Comment by Omzig** [comment]
why is main even setup to allow for a commit in the first place?
