### ISSUE TITLE
Export Button in New-UDDataGrid doesn't follow theme properly

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2357]
### Version

3.8.11

### Severity

Visual

### Steps to Reproduce

Apply the galaxy theme to the dashboard and view the export button. It will disappear when hovered. 

### Expected behavior

```console
Export follows the theme
```

### Actual behavior

```console
Export does not follow the theme
```

**Comment by Omzig** [comment]
this is the same problem with the New-UDIconButton not following the theme
- https://github.com/ironmansoftware/issues/issues/2149
