### ISSUE TITLE
4.0.0-beta2 - Bug with Docker Image Deployment

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#2359]
### Version

4.0.0-beta2

### Severity

High

### Steps to Reproduce

Try to deploy a docker image.
It will fail with the following error and crashloop:

`Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'name') 2023-04-28T16:56:43.921419629+02:00 at System.ArgumentNullException.Throw(String paramName) 2023-04-28T16:56:43.921434917+02:00 at System.Environment.ExpandEnvironmentVariables(String name) 2023-04-28T16:56:43.921455106+02:00 at Universal.Server.Program.CreateHostBuilder(String[] args, Options options) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Program.cs:line 228 2023-04-28T16:56:43.921465062+02:00 at Universal.Server.Program.<>c__DisplayClass3_0.<Main>b__0(Options o) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Program.cs:line 63 2023-04-28T16:56:43.921471428+02:00 at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action) 2023-04-28T16:56:43.921477794+02:00 at Universal.Server.Program.Main(String[] args) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Program.cs:line 52`

### Expected behavior

```console
Docker Image should deploy like 3.8.x
```

### Actual behavior

```console
Docker Image 4.0.x does not deploy
```

### Additional Environment data

K8S / Rancher

**Comment by adamdriscoll** [comment]
You can work around this by setting the SystemLogPath environment variable. 

docker run -p 5000:5000  -e SystemLogPath=%home%/.PowerShellUniversal/systemLog.txt ironmansoftware/universal:preview

**Comment by donlent** [comment]
Hey @adamdriscoll 
Thanks a lot for your answer and for having fixed it already for the GA release.
I do confirm though that with your workaround the deployment succeeds. :-)
