### ISSUE TITLE
Database Log Target and Log Viewer - Export Feature

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2365]
### Summary of the new feature / enhancement

As an admin, I want to export a filtered list of logs so that it is easy to share them with people like Adam. 

### Proposed technical implementation details (optional)

![image](https://user-images.githubusercontent.com/1987296/235476037-9d00ed62-5b00-435d-b3f5-7b39ed1063fd.png)

**Comment by adamdriscoll** [comment]
This is a duplicate of this: https://github.com/ironmansoftware/issues/issues/2318

**Comment by Omzig** [comment]
Duplicate /facepalm
