### ISSUE TITLE
New Page in apps causes "Value cannot be null. (Parameter 'path2')"

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2366]
### Version

4.0.0-beta2

### Severity

Critical

### Steps to Reproduce

cannot add new pages

### Expected behavior

```console
add new page
```

### Actual behavior

```console
400 
Value cannot be null. (Parameter 'path2')
```

### Additional Environment data

IIS: Nested

**Comment by adamdriscoll** [comment]
Can you send me a screen shot of how your file system looks in regards to the dashboards folder? 

<img width="346" alt="image" src="https://user-images.githubusercontent.com/1256531/236220937-b5a9ac6f-b4ad-4364-8742-b9dfd1f85537.png">

I'm also curious of the contents of dashboards.ps1

**Comment by Omzig** [comment]
Unable to recreate in beta5 (5183140655)
