### ISSUE TITLE
UDExpansionPanelGroup -id and -classname does not apply

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2370]
### Version

3.8.12

### Severity

Visual

### Steps to Reproduce

```powershell
New-UDElement -Id 'panelGroup' -Tag div -Content {
                    New-UDExpansionPanelGroup -Id 'UDExpansionPanelGroup' -ClassName 'UDExpansionPanelGroupV2' -Children {
                        New-UDExpansionPanel -id 'UDExpansionPanel' -Title "Tags" -Active -Children {
                            Show-Tag -Id "16"
                        }
                    }
                }
```

### Expected behavior

```console
apply UDExpansionPanelGroup id
```

### Actual behavior

```console
applies UDExpansionPanel id instead
```

### Additional Environment data

IIS: Nested

### Visuals

I am not sure exactly where the `UDExpansionPanelGroup`  is supposed to be applied

![image](https://user-images.githubusercontent.com/1987296/235706027-cbdcc872-755e-4f27-8284-d78f13115bd7.png)

**Comment by helperBob** [comment]
The "ID" class can only be assigned to one element.

**Comment by helperBob** [comment]
The attribute "ID" can only be assigned once with a given value.
