### ISSUE TITLE
Add -ClassName to New-UDElement

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2371]
### Summary of the new feature / enhancement

As a developer, I want to be able to add a class name to my div so that i can target it with a css selector.

**Comment by adamdriscoll** [comment]
For the time being, you should be able to do this with the attributes. 
```
New-UDElement -Tag div -Attributes @{
   className = "MySuperDuperClass"
}
```

**Comment by Omzig** [comment]
ty, this makes live so much smoother, i really do appreciate all your work.
