### ISSUE TITLE
ExpansionPanelGroup behavior is the same with -PopOut, -Type Accordion

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#2373]
### Version

3.8.12

### Severity

Visual

### Steps to Reproduce

I don't see any difference between the behavior of new-UDExpansionPanelGroup with these settings

New-UDExpansionPanelGroup
New-UDExpansionPanelGroup -PopOut
New-UDExpansionPanelGroup -Type Accordion

the livedocs also seem to show identical behavior

### Expected behavior

```console
Accordion should only allow one panel to be open at a time

Not sure from MUI docs what PopOut means
```

### Actual behavior

```console
All look identical
```

**Comment by adamdriscoll** [comment]
-Popout has been removed as MUI no longer supports this. 
Fixed the issue with -Type Accordion.
