### ISSUE TITLE
Dialog from mui

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#2384]
### Summary of the new feature / enhancement

It would be perfect if you could add Dialog from mui.
https://mui.com/material-ui/react-dialog/

All of them looks perfect, so it would be perfect if you could add all of them :)
[Basic: (With this you can change option in a nice way)](https://mui.com/material-ui/react-dialog/#basic-dialog)

[Alert (With this you can confirm if something for example before user delete something)](https://mui.com/material-ui/react-dialog/#basic-dialog)

[Form Dialogs (With this user can write something in a textbox)](https://mui.com/material-ui/react-dialog/#form-dialogs)

Then you have the different options like size and also the scrollable etc.

### Proposed technical implementation details (optional)

https://mui.com/material-ui/react-dialog/

**Comment by rwidmark** [comment]
@adamdriscoll something for v4?

**Comment by adamdriscoll** [comment]
Moving into 4.1 for the time being. Time is running out for 4.0 and I don't want to add to much more to that milestone.

**Comment by adamdriscoll** [comment]
Show-UDModal is actually using the dialog so we should probably enhance what is there already.
