### ISSUE TITLE
Automate publishing of cmdlet help to GitHub

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#239]
The cmdlet help stored on github is woefully out of date. We need to ensure that cmdlet help is published every time a new release is released.

**Comment by Viajaz** [comment]
This is important if one has to onboard multiple developers onto the PSU platform, it's the first thing they ask for.

**Comment by MikeShepard** [comment]
100% agree...trying to use maps, but none of the map cmdlets are in the help.

**Comment by adamdriscoll** [comment]
Done: https://github.com/ironmansoftware/universal-docs/pull/78

We now have a workflow that creates a PR with the new help when we release a new version.
