### ISSUE TITLE
New-PSUEvent - Add parameter for "Within"

### ISSUE THREAD

**Issue by JoriPS1** [ironmansoftware/powershell-universal#2390]
### Summary of the new feature / enhancement

Currently creating many system events, or complex system events can cause quota violations/exceptions.  This is likely due to the frequency of querying WMI (1 second).  Adding this as a parameter can take some of the load off of WMI by decreasing the frequency of checks.

**Comment by adamdriscoll** [comment]
We use Register-ObjectEvent for system events and it doesn't offer this functionality.
