### ISSUE TITLE
Check for module updates

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2396]
### Summary of the new feature / enhancement

We should have a good way to see which modules are out of date. This will be handy in v4 since there will be a push for more module adoption.

**Comment by rwidmark** [comment]
I have done a script for this in c# for a other project.

A tip from me, also include a function that can delete old modules.
And how old module version you want to keep.

For example if you want to only keep the previous one.
Maybe it should have a int where the user can select how many module version they want to keep :)

Also, have some kind of auto-update feature that can be triggered by time.
