### ISSUE TITLE
New-UDBootstrapIcon missing size etc.

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#2397]
### Summary of the new feature / enhancement

The new way to add icons with for example New-UDBootstrapIcon are missing size.
I have tried -Style @{ size = 5x } and also -Style @{ size = 5rem } and the same but with font-size instead of size

**Comment by adamdriscoll** [comment]
-Size has been added. Example here: https://github.com/ironmansoftware/universal-modules/tree/main/Components/Icons.Bootstrap
