### ISSUE TITLE
Opening settings on an app or trying to create new app shows "TypeError: r.find is not a function"

### ISSUE THREAD

**Issue by kp-bit** [ironmansoftware/powershell-universal#2400]
### Version

4.0.0-beta2

### Severity

Critical

### Steps to Reproduce

Production environment (to be) upgraded from 3.9.2 - everything works fine except when opening settings on an existing app (Dashboard) or trying to create a new app, the following is shown:

![image](https://github.com/ironmansoftware/issues/assets/61055573/0c8397ee-69c3-40e0-aa7a-d8b22fc11298)

When opening the Templates page, same happens, except it says "TypeError: t.find is not a function"

Test environment does not show these problems.

### Expected behavior

```console
Settings page shown
```

### Actual behavior

```console
TypeError: r.find is not a function (see screen shot)
```

### Additional Environment data

PSU 4.0.0-beta4 on Windows Server 2019

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/61055573/37fb7408-b889-40dd-81df-41f1665a4b94)

**Comment by adamdriscoll** [comment]
@kp-bit - Can you do me a favor and try pressing F12 in the browser and look for this error within the console tab? It should provide some better line numbers for the stack trace.

**Comment by kp-bit** [comment]
@adamdriscoll, here you go - thanks!

From Apps page:
![image](https://github.com/ironmansoftware/issues/assets/61055573/2e3d741d-b053-456d-b6d0-0d8a206fc013)

From Templates page:
![image](https://github.com/ironmansoftware/issues/assets/61055573/7c16ea45-98c5-4394-b4f0-6282fb27b41f)
