### ISSUE TITLE
Output log in GUI is empty when JobRunId flag is enabled

### ISSUE THREAD

**Issue by schubfre** [ironmansoftware/powershell-universal#2403]
### Version

3.9.2

### Severity

Low

### Steps to Reproduce

Enable `ExperimentalFeature = ([PowerShellUniversal.ExperimentalFeatures]::JobRunId)` and start a job. See that the Output log in the GUI is empty.

The log is still saved though, because if you click on the 'Log File' button in the GUI a new window opens with the relevant filled log

### Expected behavior

```console
Output log should show Debug/Verbose/Info output
```

### Actual behavior

```console
Output log doesn't show Debug/Verbose/Info output
```

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/28289080/373d4080-2b41-4085-b739-a385b1477e3f)

![image](https://github.com/ironmansoftware/issues/assets/28289080/9802a239-a380-4039-bb82-5c988046018f)

**Comment by adamdriscoll** [comment]
I can't reproduce this at the moment. Can you please press F12 in your browser and let me know if you have any failed HTTP requests on this page? They will be under the network tab.

**Comment by schubfre** [comment]
I can't reproduce it either anymore, it seems to have been a temporary problem.

Thing is, I didn't restart the service since then. I entered edit mode, enabled the flag, tested a bit, then reverted all changes made in edit mode and now did the same as yesterday. Maybe a service restart would have fixed the problem right then anyway.

Well, I think we can close this one.

**Comment by adamdriscoll** [comment]
Ok. Feel free to reopen if you run into it again.
