### ISSUE TITLE
Add Git startup progress bar or something

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2404]
### Summary of the new feature / enhancement

As a user, I want the git sync to show me something as it is working because in azure dev the containers run really slow so that i know that it is doing something, and so that i don't restart the container in the middle of a process that i think is hung. 

I have a git pull that takes 10-20min to finish in the container because azure is soooooooooooooooooo slow in dev.

### Proposed technical implementation details (optional)

Add progress bar here?

![image](https://github.com/ironmansoftware/issues/assets/1987296/5da02fbf-6215-4310-87bb-d1c811f2b0ee)

**Comment by adamdriscoll** [comment]
I've often thought about this with the configuration files as well...
