### ISSUE TITLE
PSScriptPad shows the name property twice

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2405]
## Describe the bug
The name property is shown twice

## To Reproduce
1. Install the current version of PSScriptPad 2023.3.0
2. Create a new Windows Form
3. Select the main form itself (which is a control) or add a new control onto the canvas and select that form
4. Review the properties of the selected control including the name property

## Screenshots
![image](https://github.com/ironmansoftware/issues/assets/537287/f8621235-a4a0-4486-9702-ff449557ec13)

## Version
2023.3.0

**Comment by adamdriscoll** [comment]
We are using the built in prop dialog and this is just how it works.
