### ISSUE TITLE
Add a Calendar component

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2406]
### Summary of the new feature / enhancement

It would be ideal if there was a ready-to-use calendar component (beyond the DateTimePicker) for PowerShell Universal 3.x/4.x.

### Proposed technical implementation details (optional)

Links

**1st party UD Calendar module (incomplete?)**
https://www.powershellgallery.com/packages/UniversalDashboard.Calendar/1.0.0

**3rd party UD Calendar module**
https://www.powershellgallery.com/packages/universaldashboard.ud-calendar/1.0.0 (by https://github.com/BoSen29)

**Forum post**
https://forums.ironmansoftware.com/t/fancy-new-control-udcalendar/1579

**Comment by adamdriscoll** [comment]
I made this recently. I'm going to keep it as a separate module but it's the "official" one now: https://github.com/ironmansoftware/universal-modules/tree/main/Components/Calendar
