### ISSUE TITLE
Kiosk mode

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#2407]
### Summary of the new feature / enhancement

As a developer I would like to run an instance which has no "admin" interface - only dashboards and apis that I have written should be available.  A docker deployment would be an example.

### Proposed technical implementation details (optional)

instance-level switch that turns off as much admin as possible

**Comment by MikeShepard** [comment]
Apparently there's a HideAdminConsole setting, but I haven't been able to get it to work in a local install or in docker.

**Comment by adamdriscoll** [comment]
I can reproduce the issue with HideAdminConsole. If that setting worked, would that meet your requirements?

**Comment by MikeShepard** [comment]
I think so.

**Comment by adamdriscoll** [comment]
Cool. Well, this will be fixed in 3.9.4. I'll close this but feel free to reopen if you find hiding the admin console doesn't meet your needs.
