### ISSUE TITLE
Add volume for repository folder (or higher folder) to Docker image

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#2410]
### Summary of the new feature / enhancement

The repository folder is empty by default.  By adding a volume definition to the official image, you will save everyone working with it having to rebuild and upload to a repository.  I imagine by far the most common use cases of PSU in a container would involve having persisted data.

### Proposed technical implementation details (optional)

Add this to the Dockerfile:
VOLUME ["/home/data/Repository"]

**Comment by adamdriscoll** [comment]
I guess I'm not really sure how folks are using docker in this regard. It's possible to mount a volume without having to rebuild or upload to a repository by using the `-v` command for docker to map the container path to a host path. By putting the VOLUME into the metainformation, it creates an anonymous volume and doesn't let you decide where that volume lives on the host. I'm pretty sure you can't override that volume with `-v` but I could be wrong. That said, we could easily change the data directory within the container via ENV VARs and redirect to a volume mounted via `-v` so it shouldn't prevent us from using the VOLUME command. 

In my configuration, I don't persist state in the docker container itself but use a SQL DB to read git settings that are then pulled and loaded when the container starts up. I realize that the volume being defined within the image would simplify this as there wouldn't need to have external services. This would also allow for using LiteDB with docker without having to run external commands. 

All-in-all, I agree that this would be a good change and just want to make sure we follow best practices without breaking existing docker users. 

We should most definitely loop in Matt Harris as he is a big PSU docker user: https://forums.ironmansoftware.com/u/matt.harris/summary

**Comment by MikeShepard** [comment]
My use-case is to start an azure container instance with a volume mapped to a github repo.  Not sure if I'm going down the wrong path.  My docker skills are somewhat limited :-).

**Comment by adamdriscoll** [comment]
Cool. I'll pinged Matt to get his thoughts. Also note, that we open-sourced our docker files and will be using this repo v4+

https://github.com/ironmansoftware/universal-docker

**Comment by MikeShepard** [comment]
Turns out I don't need a volume to do what I want.

**Comment by MattHarrisUltima** [comment]
Hi @MikeShepard,

What are you looking to do?

Currently, I mount /root and everything runs from there.

I am happy to throw some thoughts you way :-)
