### ISSUE TITLE
Missing Icon: New-UDIcon -Icon 'Hive' -Solid

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2417]
### Version

3.9.2

### Severity

Visual

### Steps to Reproduce

hive is not found

it says hive is free: https://fontawesome.com/icons/hive?f=brands&s=solid

```
New-UDIconButton -Icon (New-UDIcon -Icon 'Hive' -Solid)
```

### Expected behavior

```console
show free hive icon
```

### Actual behavior

```console
? icon
```

### Additional Environment data

IIS: Nested

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/1987296/870d5e6c-58a7-4838-a286-d08b32249fa8)

**Comment by adamdriscoll** [comment]
This seems to work: New-UDIconButton -Icon (New-UDIcon -Icon 'HiveBlockchainNetwork' -Solid) 

But, yeah. Hive should work...

**Comment by Omzig** [comment]
> This seems to work: New-UDIconButton -Icon (New-UDIcon -Icon 'HiveBlockchainNetwork' -Solid)
> 
> But, yeah. Hive should work...

dude, that is bonkers, HiveBlockchainNetwork is not even in the website's search

**Comment by adamdriscoll** [comment]
The problem is how we search within New-UDIcon. We are looking at the label and the aliases for icons. 

```
  "hive": {
    "changes": [
      "5.15.0"
    ],
    "ligatures": [],
    "search": {
      "terms": []
    },
    "styles": [
      "brands"
    ],
    "unicode": "e07f",
    "label": "Hive Blockchain Network",
    "voted": false,
```

We should add the fa class name as well...
