### ISSUE TITLE
Unable to disable app authentication (4.0.0-beta4)

### ISSUE THREAD

**Issue by insomniacc** [ironmansoftware/powershell-universal#2446]
### Version

4.0.0-beta4

### Severity

High

### Steps to Reproduce

I've just installed as an azure web app via docker image 'ironmansoftware/universal:4.0.0-beta4-ubuntu-20.04'
I've followed the docs to enable a fileshare mount for 'Data__ConnectionString' & 'Data__RepositoryPath'.
Mostly everything appears to work fine, and config is retained after reboots.

However, when creating a new app/dashboard, and attempting to disable authentication I get error "Object reference not set to an instance of an object"

### Expected behavior

```console
Able to successfully disable authentication and make the dashboard/app public.
```

### Actual behavior

```console
Error thrown: Object reference not set to an instance of an object
```

### Additional Environment data

App Service Plan: F1: 1
Operating System: Linux

### Visuals

![DisableAuthError](https://github.com/ironmansoftware/issues/assets/10046621/bb9bd5bd-60df-43a6-b5ba-ac91631ae70d)

**Comment by adamdriscoll** [comment]
Can you upload a log snippet? A stack trace of that error would be good.

**Comment by insomniacc** [comment]
About that... 😵‍💫 
I actually posted on the forum about logging, since I'm having a few issues with that too but wasn't sure if it was just my own misunderstanding: https://forums.ironmansoftware.com/t/psu-in-azure-webapp-logging-help/9239/2

**Comment by adamdriscoll** [comment]
You might need to configure the SystemLogPath environment variable. 

```
"SystemLogPath": "%ProgramData%\\PowerShellUniversal\\systemLog.txt",
```

There aren't level controls for the built in file-based logging so you just need to change the path.

**Comment by insomniacc** [comment]
Thanks for that, I just added the variable + restarted and can now see it's outputting a log file on my storage account (altho its still giving me the below error in the UI notifications, and the logging page in the admin console is empty)
```
Invalid configuration: logging.ps1 
Could not find a part of the path '/usr/share/PowerShellUniversal/log.db'.
```

I went to go test the authentication issue and I cant seem to replicate it now! 
Not sure if that's because I've updated to beta5 or if it's something to do with the restart.

**Comment by adamdriscoll** [comment]
I can reproduce that issue with the logging.ps1. That will be fixed in tonight's nightly. 

Let me know if the authentication issue crops up again!

**Comment by insomniacc** [comment]
Awesome! Thank you as always!

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/psu-in-azure-webapp-logging-help/9239/4

**Comment by adamdriscoll** [comment]
I'll close this issue as it seems to have resolved itself, but feel free to comment on it if it happens again and I can reopen.
