### ISSUE TITLE
Dashboard  - IFRAME bug

### ISSUE THREAD

**Issue by Bartozorus** [ironmansoftware/powershell-universal#2451]
### Version

3.9.4

### Severity

Content

### Steps to Reproduce

When displaying any dashboard rom iframe whe have a Javascript error

```
One or more errors occurred
Value cannot be null. (Parameter ‘source’)
```

Issue can be reproduced with any PSU dashboard --> just add this code on any file and open it with a navigator :

```
<html>
  <header>
  </header>
  <body>
    <iframe src="https://demo.powershelluniversal.com/" style="width: 100%; height:100%;"></iframe>
  </body>
</html>
```

Note : It was working on PowershellUniversal 3.7.14. For the use → several dashboards from different sources including a PowerShellUniversal dashboard are displayed on a giant screen. To operate a rotation of the differents dashboards we use a raspberrypi with reveal.js which encapsulates all the dashboards in IFRAME

### Expected behavior

```console
the dashboard needs to be displayed without error
```

### Actual behavior

```console
One or more errors occurred
Value cannot be null. (Parameter ‘source’)
```

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/dashboard-display-in-iframe-one-or-more-errors-occurred-value-cannot-be-null-parameter-source/9048/5

**Comment by pookkii** [comment]
The problem seems to occur again in versions 3.9.8 and 4.0.2, it was working in version 3.9.6.
