### ISSUE TITLE
'Running Dashboards' link on the homepage is broken

### ISSUE THREAD

**Issue by insomniacc** [ironmansoftware/powershell-universal#2453]
### Version

4.0.0-beta5

### Severity

Low

### Steps to Reproduce

Minor detail but on the home page of the admin back end, click on 'Running Dashboards', it redirects to a broken link /admin/dashboards.
Appears to be a left over since the terminology was changed from dashboards to apps, both the link and display value need updating.

### Expected behavior

```console
This should direct to 'https://host/admin/apps'
```

### Actual behavior

```console
It directs to 'https://host/admin/dashboards
```

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/10046621/8c9b856d-9297-4705-a4c9-05c0fc707065)

**Comment by insomniacc** [comment]
Curiously, I'm also not sure why it's showing 3, I've only got 1 app running:
![image](https://github.com/ironmansoftware/issues/assets/10046621/52c78c30-1eaa-4826-bde7-766e5f149bfc)

**Comment by adamdriscoll** [comment]
Hmmm mine shows 2 and one of the is the docs dashboard. I wonder what your 3rd one is.....

I'll make sure we remove the docs dashboard from this stat.
