### ISSUE TITLE
[PSU 4.0]Can't start Dashboards / apps

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#2458]
### Version

4.0.0-beta5

### Severity

High

### Steps to Reproduce

Dashboard that did work to start without any issues in 3.9.6 won't start in 4.0
```
Cannot bind parameter 'Component'. Cannot convert the "CustomGUI:1.0" value of type "System.String" to type "PowerShellUniversal.DashboardComponent".
```

I have not done any changes to anything when I was going over to 4.0, I have my components (modules) in the component folder is that the wrong approach in 4.0?
I also see that components are missing in the menu in Admin view. So I'm guessing that you have moved this? If so, where? and how can I get them to sync with git?

### Expected behavior

```console
that the dashboard will start
```

### Actual behavior

```console
Dashboard will not start.
```

**Comment by adamdriscoll** [comment]
At the moment, you would need to move your components into the Modules folder in the repository to have them load. You would need to remove the -Components parameter from New-PSUDashboard in dashboards.ps1. 

That said, we should seamlessly upgrade here so we will fix this.

**Comment by rwidmark** [comment]
@adamdriscoll ill try that tomorrow. I'm kind of confused is 4.0 live now or still in beta?

**Comment by adamdriscoll** [comment]
4 was released from beta yesterday so it is now live.
