### ISSUE TITLE
Configuration files do not show up properly in the VS Code extension

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2467]
### Version

4.0.0

### Severity

Low

### Steps to Reproduce

https://forums.ironmansoftware.com/t/powershell-universal-4-0-0/9258/13

### Expected behavior

```console
Configuration files can be edited properly
```

### Actual behavior

```console
Configurations are not showing properly.
```

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/powershell-universal-4-0-0/9258/14

**Comment by TurnItOff-OnAgain** [comment]
Just a note that the configuration tab works correctly on Universal 3.8.12.
