### ISSUE TITLE
Get-Acl not working correctly in PowerShell 7 enviroments

### ISSUE THREAD

**Issue by hansVader11** [ironmansoftware/powershell-universal#2482]
### Version

4.0.1

### Severity

Low

### Steps to Reproduce

When using Get-Acl in a Script or App running on PowerShell 7, the CodeProperties Access, Group, Owner, Path and Sddl aren't there. When i switch the enviroment to PowerShell 5.1 it works. Doesn't work in the Enviroments Integrated, Agent and 7.3.4.

Same thing happens when using .Net directly:
[System.IO.FileSystemAclExtensions]::GetAccessControl( [System.IO.DirectoryInfo]::new( "c:\windows"))

Running the Command in a PowerShell 7 window on the Server works without any problems.

### Expected behavior

```console
Get-Acl | Select Path, Owner, Access
<Populated Objects>
```

### Actual behavior

```console
Get-Acl | Select Path, Owner, Access
<Empty Objects>
```

### Additional Environment data

PowerShell Version: 7.3.4, also tested with 7.3.1
Windows Server 2022, also tested with Windows Server 2019

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/get-acl-only-creates-an-empty-directorysecurity-object/9892/1
