### ISSUE TITLE
Roles dropdown empty

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#2483]
### Version

4.0.1

### Severity

Low

### Steps to Reproduce

Normally when you created a new identity / changed an existing one, you could select what roles the identity should be part of. _For the free version, you could select the built-in ones._

The dropdown menu is blank, and the search does not find any roles when searching.

### Expected behavior

```console
That the list of built-in roles, would be present.
```

### Actual behavior

```console
No roles is presented.
```

**Comment by ksl28** [comment]
Its seems that its also an issue when creating new variables (Secret variables) then the role drop-down is empty = we cant assign the secret

**Comment by Viajaz** [comment]
I too have experienced this throughout the software in v4, it happens about 60% of the time to me.
