### ISSUE TITLE
Job handshake value not working

### ISSUE THREAD

**Issue by TurnItOff-OnAgain** [ironmansoftware/powershell-universal#2484]
### Version

4.0.0

### Severity

Low

### Steps to Reproduce

Set Job Handshake timeout to something other than 5 seconds in both the admin UI and in appsettings.json, save and restart the service

### Expected behavior

```console
Job should wait more than 5 seconds before timing out
```

### Actual behavior

```console
Job fails with this error

Error executing job: PowerShell did not respond in a timely fashion. PowerShell Universal is currently waiting 5 seconds for PowerShell to start running the script.
You can increase the timeout by setting the 'Job Handshake Timeout' setting in the Settings \ General \ Automation page.
If you are still experiencing issues, you may need to consider increasing the resources available on your system or take advantage of the Random Delay parameter for schedules to stagger jobs.
```

### Additional Environment data

Seems to be related to the AV installed on the server (bitdefender). If I disable Advanced Threat Control it works fine. Looks like a new setting in ATC is grabbing the powershell session and scanning it before it allows it to run, causing the job to time out. Increasing the time out doesn't work though.

**Comment by TurnItOff-OnAgain** [comment]
Here is a screenshot of my appsettings.json

![image](https://github.com/ironmansoftware/issues/assets/26926284/781ad92c-c8cf-43b7-a670-1c134ab1ef7f)

Here is a video of the admin UI not keeping the setting

![ezgif-4-ff5e845cbe](https://github.com/ironmansoftware/issues/assets/26926284/dfcebf15-c76b-4653-ba16-4651f1c8da62)

And a screenshot on a job I manually ran after setting the handshake to 30 seconds

![image](https://github.com/ironmansoftware/issues/assets/26926284/cedbe964-3e13-49d7-b070-311fa301550b)

I will be working with my AV vendor to see why this suddenly started happening last night, but figured a bug report should be submitted.

**Comment by adamdriscoll** [comment]
@TurnItOff-OnAgain - I found that if I change it to any except 30 seconds, it will change. That said, I can reproduce what you are seeing and will release a fix for this.
