### ISSUE TITLE
`-Children` Parameter of `New-UDLink` is ignored in favour of `-Text`

### ISSUE THREAD

**Issue by liamjpeters** [ironmansoftware/powershell-universal#2490]
### Version

4.0.1

### Severity

High

### Steps to Reproduce

Create a new link element and pass it a `-Url` and a `-Content` (or `-Children`) argument. Such as in the example below from the Live Docs:

```powershell
New-UDLink -Url "https://www.google.com" -Content {
    New-UDImage -Url "https://www.ironmansoftware.com/img/ps-logo.png" -Height 20 -Width 20 
} -Id 'link7'
```
![Screenshot 2023-06-23 073528](https://github.com/ironmansoftware/issues/assets/6566675/085b5afd-c959-4366-8c34-7d7e26f657ba)

### Expected behavior

```console
The content is rendered and the default value of the `-Text` parameter (`"Ironman Software"`) is ignored.
```

### Actual behavior

```console
The content is ignored in favour of rendering the default `-Text` parameter
```

### Additional Environment data

IIS hosted Zip version

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/new-udlink-not-using-the-children-content-parameters/9331/1
