### ISSUE TITLE
Administrator role should default to $False

### ISSUE THREAD

**Issue by insomniacc** [ironmansoftware/powershell-universal#2492]
### Summary of the new feature / enhancement

I feel like the administrator role should not default to $true.

Web app docker (linux) user here.
The main thought process behind this is that I've had the occasional issue with git, the most recent example, I upscaled my web app from B1 to B2, after it rebooted and came back online, I noticed that the git sync had completely broken and I was in a clean instance of PSU without any dashboards, all the default roles etc. (even after several web app reboots) The fix was to reset/remove and re-configure git settings.

Now the potential problem with this, lets say something like this occurred over night due to a restart or similar while I was not aware and my instance was reset, all the permissions on my managed identity remain so it could be a potential security issue that anyone could login through the admin role and write scripts to interact with my tenant via the Az cmdlets or similar.

The local admin account is safe since it's stored in the DB and doesn't reset to default, but the roles do.

### Proposed technical implementation details (optional)

Change $True to $False in the default Administrator role.

**Comment by adamdriscoll** [comment]
I agree. This made sense before we had local accounts but I'll make sure we make this change in 4.1.
