### ISSUE TITLE
Roles cannot be edited on Endpoints that were created with New-PSUEndpoint

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2493]
### Version

3.9.7

### Severity

Low

### Steps to Reproduce

1. Using the PSU UI, create a new Endpoint and assign a Role to it.
2. View the details of the Endpoint and confirm that the role was assigned.
3. Using New-PSUEndpoint, create a new Endpoint and do not assign a Role to it.
4. Using the PSU UI, try to modify the Roles of the Endpoint that you created in Step 3.

## Workaround
The roles of an endpoint can be modified outside of the UI using the built-in PSU API

### Expected behavior

```console
The textbox for modifying the roles of an endpoint (created with New-PSUEndpoint) should always be available.
```

### Actual behavior

```console
The textbox for modifying the roles of an endpoint (created with New-PSUEndpoint) are not always available.
```

### Additional Environment data

PSU 3.9.7

**Comment by DataTraveler1** [comment]
See PR 1167

**Comment by adamdriscoll** [comment]
@DataTraveler1 This is because Authentication is disabled. Did you enable authenticaiton for this endpoint? 

EDIT: I created an integration test to prove it works. 

```
        It "should create an API with roles" {
            $Random = Get-Random
            New-PSUEndpoint -Url "/$Random" -Endpoint {
                "Hello"
            } -Role "Administrator" -Authentication | Should -Not -Be $null
            Get-PSUEndpoint -Url "/$Random" | Should -Not -Be $null
        }
```

<img width="617" alt="image" src="https://github.com/ironmansoftware/issues/assets/1256531/a1c00d63-33e1-4f45-9c9b-744048217756">

**Comment by DataTraveler1** [comment]
@adamdriscoll - Yes, that is correct. I did not have authentication enabled on those endpoints. I see your point, it's all clear now. Thank you! 🍺
