### ISSUE TITLE
Secret Handling in Endpoints

### ISSUE THREAD

**Issue by SignalR-Dev** [ironmansoftware/powershell-universal#2513]
### Version

4.0.3

### Severity

High

### Steps to Reproduce

Create a Secret Variable name "test" as PScredential (Buildin or Database , makes no diffrence)

Create an API Endpoint with following code

(Get-ChildItem "Secret:test").Password
or
(Get-Secret test).Password

The Resulting Object is not a secure String or String , just a Propertie Length 
[{"Length":3}
Where 3 is the length of the password

What is correct Usage of Passwords in Enpoints? 
(Behaves similar in 3.9 !)

### Expected behavior

```console
Secure String (as it is in Script execution)
```

### Actual behavior

```console
Object of Length
```

**Comment by adamdriscoll** [comment]
@SignalR-Dev You will want to use the secret scope. 

```
# For strings: 
$Secret:Test

# Credentials are PSCredential objects. Use this to return the plaintext password. 
$Secret:Text.GetNetworkCredential().Password

**Comment by aauerswald** [comment]
Hello I tried also,

$Secret:Test gave me no repsonse via api endpint, only via script directly.
Only (Get-Secret Test) or (Get-ChildItem "Secret:test") will gave me a response, but only the length of the password and not the password itself.

$Secret:Text.GetNetworkCredential().Password will not work and also not in combination with Get-Secret or Get-ChildItem. (in API)

**Comment by aauerswald** [comment]
Result via API
![api](https://github.com/ironmansoftware/issues/assets/7852951/9123b1c3-672f-49f8-9549-6405813a40bb)

Result via Script (Same code)

![script](https://github.com/ironmansoftware/issues/assets/7852951/d23723cf-6b77-4cd7-bf12-9bf8c9bf33c2)

I need the same PSCredential object back in API.

**Comment by adamdriscoll** [comment]
Trying to recreate this. I have created a secret variable in the database to store a credential. This is what I'm doing in my endpoint. 

<img width="650" alt="image" src="https://github.com/ironmansoftware/issues/assets/1256531/f04cadcf-6b91-4067-9a52-db314511119f">

This is what my variable looks like.

<img width="835" alt="image" src="https://github.com/ironmansoftware/issues/assets/1256531/d3284b92-9e7d-4796-95ef-82ab844e546c">

**Comment by aauerswald** [comment]
Worked. Thanks! (But $Secret:Cred is no Credential-Object like i got from Scripts)

**Comment by SignalR-Dev** [comment]
I agree with @aauerswald 

While this could be used as a workaround , it is not the expected behavior.

I assume the Runtime or AST is differently created in Endpoints than in Scripts , as it´s not working in a Startup Script of Environment   as well.

Still consider it as a Bug

**Comment by adamdriscoll** [comment]
I guess I'm missing the issue. They are accessed the same way in both scripts and endpoints. 

My script gets the username and password and displays the type. 

<img width="237" alt="image" src="https://github.com/ironmansoftware/issues/assets/1256531/36344c42-d299-498a-b6b2-0d274f1e8db5">

This is the result when running the script. 

<img width="174" alt="image" src="https://github.com/ironmansoftware/issues/assets/1256531/659f511c-1fb5-4973-9180-6c282706055c">

I use the exact same code in an endpoint and it returns the same values. 

<img width="656" alt="image" src="https://github.com/ironmansoftware/issues/assets/1256531/95d40a74-25cf-40ad-8b30-6e714d49704c">

**Comment by SignalR-Dev** [comment]
Never mind.
Totally my fault. 
Another Module Loaded Splatted over the Variables used in PSU.
I close this down
