### ISSUE TITLE
Reduce Initial load time

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2518]
### Summary of the new feature / enhancement

As an end user, I want the initial load time to be faster so that i do not have to wait 40 seconds for the website to work while on VPN. Sometimes it will just fail to load and you have to hit refresh.

if i load the fav icon by itself it is like 100ms load time

### Proposed technical implementation details (optional)

![image](https://github.com/ironmansoftware/issues/assets/1987296/db358fe2-663c-4914-a501-550a73300855)

**Comment by adamdriscoll** [comment]
Can you click on one of those long running requests and then click the timing tab? 

<img width="449" alt="image" src="https://github.com/ironmansoftware/issues/assets/1256531/8e5cdd0f-cae9-41a4-a24b-0c3203c6a714">

**Comment by Omzig** [comment]
![image](https://github.com/ironmansoftware/issues/assets/1987296/cbae6bec-24e0-47f0-ad76-8922f94bff18)
this was the one that was slow, today it was 2.2 sec instead of 40sec.

i upgraded to 3.9.10 and 4.0.4, that might have helped or maybe they did something to VPN that i don't know about.


at the time, even the fav icon was loading slow unless i hit the link directly

**Comment by Omzig** [comment]
oops, found out that they had some kind of encryption thing they turned off on vpn, IT help desk said it was an encryption issue.
