### ISSUE TITLE
Allow -Selected to be used on New-UDSelectOption

### ISSUE THREAD

**Issue by MattHarrisUltima** [ironmansoftware/powershell-universal#2519]
Previously in UD2.0 we were able to pass the `-Selected` parameter to `New-UDSelectOption`.

The `-Selected` Parameter appears to have been removed in PSU3.0.

Is it possible to put a parameter into the `New-UDSelectOption` Element to allow us to pre-select options in a list?

**Comment by mattselle** [comment]
You can accomplish a multi-select selected by still using the -DefaultValue
Example: 
        New-UDSelect -Label 'Select' -Id 'select2' -Option {
            New-UDSelectOption -Name "One" -Value 1
            New-UDSelectOption -Name "Two" -Value 2
            New-UDSelectOption -Name "Three" -Value 3
            } -Multiple -DefaultValue 2, 3

**Comment by MattHarrisUltima** [comment]
Hi @mattselle ,

Thank you for the code snippet :)

I will review our UD code and see if we can modify what we have to specify the selected Parameter at the New-USelect level and not the New-UDSelectOption level.
