### ISSUE TITLE
Health Checks Missing

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2527]
### Version

4.0.5

### Severity

Low

### Steps to Reproduce

i no longer see the health checks
- can go to /admin/health manually

### Expected behavior

```console
menu for health check
tile for a health check
```

### Actual behavior

```console
missing menus and tiles for health checks
```

**Comment by Omzig** [comment]
@adamdriscoll, apparently after restarting the app pool the tile for health health checks popped up in 4.0.5. i do not understand what was making it not show up on the main dashboard in the first place.

**Comment by adamdriscoll** [comment]
Health checks are only visible to administrators. Is it possible the role wasn't assigned properly at first?

**Comment by Omzig** [comment]
I will reopen if need be, maybe the auth didn't happen right... who knows.
