### ISSUE TITLE
Roles dropdown empty - Secrets

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#2545]
### Version

4.0.6

### Severity

Low

### Steps to Reproduce

Normally when you created a secret, you could select what roles the identity should be part of. For the free version, you could select the built-in ones. 

The dropdown menu is blank, and the search does not find any roles when searching. 
Might be related to this one https://github.com/ironmansoftware/issues/issues/2483

### Expected behavior

```console
That the list of built-in roles, would be present.
```

### Actual behavior

```console
No roles is presented.
```

**Comment by Viajaz** [comment]
I too have experienced this elsewhere within the software in v4, it happens about 60% of the time to me.

**Comment by adamdriscoll** [comment]
Seeing it too. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/b70f02e2-905f-4fd0-b89f-6ba7552b48cb)
