### ISSUE TITLE
New-UDApp - Logo is not working

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#2547]
### Version

4.0.6

### Severity

High

### Steps to Reproduce

It seems that the -Logo parameter is not working for New-UDApp, since the image is never loaded.

If i use this code (pre v4) the logo is present:
`New-UDDashboard -Title 'Image test' -HeaderColor 'white' -HeaderBackgroundColor "#143c8a" -Logo "/Images/logo_110_wo.png" -Content {
}`

But if i do the same with New-UDApp, i icon is shown, indicating that it cant find the file:
`New-UDApp -Title 'Image test' -HeaderColor 'white' -HeaderBackgroundColor "#143c8a" -Logo "/Images/logo_110_wo.png" -Content {}`

Its the exact same server that i just upgraded = i know the file is present, and that the service account have access to it.

### Expected behavior

```console
That the logo would be shown
```

### Actual behavior

```console
The logo is not shown
```

**Comment by adamdriscoll** [comment]
I can't reproduce this issue. 

Here is my configuration: 

```
New-UDApp -Title 'PowerShell Universal' -Content {
} -Logo "/Images/ims-logo.png" -HeaderColor 'white' -HeaderBackgroundColor "#143c8a"
```

Yields: 

![image](https://github.com/ironmansoftware/issues/assets/1256531/a01e807d-6925-431f-9289-f4798a148f18)

This is how my published folder is setup. 

New-PSUPublishedFolder -RequestPath "/Images" -Path "C:\src\" -DefaultDocument @() -Name "Pub"

I have the file located at C:\src\ims-logo.png

**Comment by ksl28** [comment]
Turned out to be a configuration error at my end - the image had somehow been blocked, so had to Unblock it (https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/unblock-file?view=powershell-7.3) to get it working.

Thanks for the help :)
