### ISSUE TITLE
Unable to add OpenID Auth

### ISSUE THREAD

**Issue by v2kiran** [ironmansoftware/powershell-universal#2556]
### Version

4.0.0

### Severity

Low

### Steps to Reproduce

go to security and try to add the openid auth method after configuring the clientid,secret etc

<img width="1315" alt="image" src="https://github.com/ironmansoftware/issues/assets/7691373/70d2fd8f-a961-4f6c-ab24-a48d82e722bd">

the errors comes up after clicking ok on the openid settings.

### error message

![image](https://github.com/ironmansoftware/issues/assets/7691373/fc7ad0c8-31e0-425e-8c50-85e1c08040a2)

### Expected behavior

```console
openid is configured
```

### Actual behavior

```console
see the error in steps to reproduce
```

### Additional Environment data

docker image: ironmansoftware/universal:4.0.0-ubunutu-20.04-ps-7.3.0
docker running on OS: windows 11

**Comment by v2kiran** [comment]
restarted docker and tried to login - couldnt so went to the following page : 
localhost:5008/login but it redirected me to this:

http://localhost:5008/api/v1/auth/redirect?returnUrl=/admin

and then i see this error on page:

```
No authentication handler is registered for the scheme 'OpenIdConnect'. 
The registered schemes are: Identity.External, Cookies, Bearer.
 Did you forget to call AddAuthentication().Add[SomeAuthHandler]("OpenIdConnect",...)?
```

**Comment by insomniacc** [comment]
I think we'd probably need to see the content of your authentication.ps1 (obviously with any sensitive information masked) just to see what is and isnt being defined, and how it's being defined. Also I would recommend updating and testing this on 4.0.8. v4 had a few issues when it was first released and the patches since have cleared a lot of those up.

**Comment by v2kiran** [comment]
@insomniacc  - thanks for replying. This is resolved now - I deleted the database.db and probably the repository as well i think - started fresh. This time instead of auth/signin-oidc i used /auth/signin-oidc so it was the  trailing slash that locked me out :)

thing is when such misconfiguration happens it seems even the backup login method of forms auth wont work.
anyway my license is only valid for v4.0 ... seems like i need to upgrade :)
