### ISSUE TITLE
scrollbuttons not working for New-UDTabs

### ISSUE THREAD

**Issue by insomniacc** [ironmansoftware/powershell-universal#2557]
### Version

4.0.7

### Severity

Low

### Steps to Reproduce

Use the following code example to create a New-UDTabs container with tabs with scrollbuttons turned on

```powershell
New-UDTabs -Tabs {
    New-UDTab -Text 'Test1' -Icon (New-UDIcon -Icon house) -Content {
    }
    New-UDTab -Text 'Test2' -Icon (New-UDIcon -Icon house) -Content {
    }
    New-UDTab -Text 'Test3' -Icon (New-UDIcon -Icon house) -Content {
    }
    New-UDTab -Text 'Test4' -Icon (New-UDIcon -Icon house) -Content {
    }
    New-UDTab -Text 'Test5' -Icon (New-UDIcon -Icon house) -Content {
    }
    New-UDTab -Text 'Test6' -Content {
    }
} -ScrollButtons on
```

### Expected behavior

```console
Scroll buttons show on either side of the tab container
```

### Actual behavior

```console
No scroll buttons show regardless of parameter value or screen size, this leads to tabs being cut off and inaccessible in certain cases.
```

### Additional Environment data

4.0.7 Azure web app / docker

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/10046621/0a085e3f-968b-4ad2-adf5-a9a642f111eb)
missing tab 6 when minimised, no scroll buttons showing.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/no-scroll-buttons-on-new-udtabs-v4-0-7/9459/2

**Comment by insomniacc** [comment]
Just tested this on 4.0.8 - it seems that ```-scrollbuttons auto``` doesnt work, ```-scrollbuttons on``` does now function, but it seems to break ```-centered``` when in use as everything is left aligned. @adamdriscoll
