### ISSUE TITLE
$Roles unavailable to New-UDApp Navigation

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/powershell-universal#2565]
### Version

4.0.7

### Severity

Low

### Steps to Reproduce

Attempt to utilise `$Roles` in elements within `Navigation` of `New-UDApp`

### Expected behavior

```console
To be able to utilise `$Roles' in elements within `Navigation` of `New-UDApp` so menu items can change depending on what roles a user holds. Should `Navigation` be a ScriptBlock?
```

### Actual behavior

```console
`$Roles` is `$null`
```

**Comment by adamdriscoll** [comment]
-Navigation is static. You will want to use the -LoadNavigation parameter and pass a script block. Then you can use $roles. 

https://docs.powershelluniversal.com/userinterfaces/components/pages#dynamic-navigation
