### ISSUE TITLE
New-UDAutocomplete DefaultValue Support

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/powershell-universal#2566]
### Summary of the new feature / enhancement

It would be useful if `New-UDAutocomplete` could support `DefaultValue` in the same way that `New-UDSelect` does.

### Proposed technical implementation details (optional)

```powershell
New-UDAutocomplete -DefaultValue '2' -Options @(
    New-UDAutoCompleteOption -Name 'Adam D' -Value '1'
    New-UDAutoCompleteOption -Name 'Sarah F' -Value '2'
    New-UDAutoCompleteOption -Name 'Tom S' -Value '3'
)
```

**Comment by Viajaz** [comment]
I believe `-Value` serves this purpose? Are there any limitations?

**Comment by adamdriscoll** [comment]
-Value does server this purpose.  The only current limitation is using New-UDAutoCompleteOption and -LoadOptions where it will display the value rather than the name. We have an open issue for this.

**Comment by adamdriscoll** [comment]
@mattselle - I'm pretty sure this is the same issue as #2583
