### ISSUE TITLE
Access based enumeration - Pages

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#2569]
### Summary of the new feature / enhancement

We use the App/Dashboards with the -pages paremeter, to built a menu for the user to click through:
![image](https://github.com/ironmansoftware/issues/assets/53445047/40187b6c-58ab-44d4-8c0e-409bd814535b)

When a user goes to a page that they dont have permission to view, they are met with a generic "Page not found", leaving them to believe there is an error in the site - but in fact they are missing out on permissions.

I believe its possible to build that menu dynamically based on a mix of Get-PSURole / Get-UDPage, and then built the site.

It would be very beneficial, if the New-UDApp had a parameter to autohide pages, that the user does not have access to like with Access based enumeration

**Comment by insomniacc** [comment]
One way which you can do this, is to load all your pages into an array and pass that into the -pages param.
After loading all the pages, you can also define your navigation which you'll pass into -LoadNavigation.
Within your Navigation script, you can use something like a foreach to iterate over your $pages and check for the roles, vs what the user has in $Roles, and only show what is relevant to their access.
At least this is how I'm currently building mine. 

I  did think that this happened automatically though if you don't define the navigation (although I haven't tested that any time recently), but I wanted a bit more granular control over how and what was displayed, like certain exclusions that are never listed in the menu, what order, nesting etc.

**Comment by Viajaz** [comment]
I've recently done what @insomniacc just mentioned as a result of #2565

**Comment by ksl28** [comment]
> One way which you can do this, is to load all your pages into an array and pass that into the -pages param. After loading all the pages, you can also define your navigation which you'll pass into -LoadNavigation. Within your Navigation script, you can use something like a foreach to iterate over your $pages and check for the roles, vs what the user has in $Roles, and only show what is relevant to their access. At least this is how I'm currently building mine.
> 
> I did think that this happened automatically though if you don't define the navigation (although I haven't tested that any time recently), but I wanted a bit more granular control over how and what was displayed, like certain exclusions that are never listed in the menu, what order, nesting etc.

I agree that it would be an option, but since we have a lot of different Dashboards running on different environments, i believe it would be beneficial if PSU had a feature to do this automatically.
