### ISSUE TITLE
F8 format in editor

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2572]
### Version

4.0.8

### Severity

Low

### Steps to Reproduce

when using the format feature now, it adds and extra tab at the root level

### Expected behavior

```console
it used to format and move everything to the start of the the first tab, pos 0
```

### Actual behavior

```console
now it indents the entire script and adds a useless tab
```

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/1987296/38473b5b-c785-49ac-ab1a-d823f447c18d)

**Comment by adamdriscoll** [comment]
@Omzig - I can't reproduce this. Is this happening in a specific type of resource?
