### ISSUE TITLE
PSScriptPad (under PowerShell Preview) does not render the first button correctly

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2581]
### Prerequisites
1. It's the first time you're running PSScriptPad under that profile. In other words, the **HKCU\SOFTWARE\Ironman Software\** key does not exist yet.
2. PowerShell Preview 7.4 (preview 4) is installed
3. You've started a new WinForm project but you have not used the toolbox yet to create forms on the canvas.

## To Reproduce
1. Ensure that PowerShell Preview 7 is selected as the environment in PSScriptPad
2. Use the toolbox to create a button on the canvas

## Expected behavior
The button should be 75x23 in size

![image](https://github.com/ironmansoftware/issues/assets/537287/676d4c7e-3bd6-4a76-a187-88be67af3c14)

## Actual behavior
The button is 8x8 in size

![image](https://github.com/ironmansoftware/issues/assets/537287/f0a69b7f-3aba-4254-828f-70610b13d7b7)

## Version
PSScriptPad 2023.7.1
Windows 10 22H2

## Additional context
This problem goes away after the 2nd button is dropped. Only the first button is impacted and only under PowerShell Preview so it's very low impact.

**Comment by adamdriscoll** [comment]
I can't reproduce this. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/60b1562a-e818-4d90-93d4-7feb9b4a9fae)

The form designer doesn't actually use the PS process to create the button in the designer.
