### ISSUE TITLE
Ability to set HTTP Response Headers in PSU/UD Apps/Dashboards

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/powershell-universal#2582]
### Summary of the new feature / enhancement

Unfortunately, I have a use-case where I need to set the `Referrer-Policy` HTTP Header in page responses.
It would be useful to set arbitrary HTTP headers for Pages.

### Proposed technical implementation details (optional)

Perhaps a `HTTPHeaders` ScriptBlock Parameter for `New-UDPage`?

**Comment by adamdriscoll** [comment]
Would middleware suffice for this? 

https://docs.powershelluniversal.com/platform/middleware

**Comment by Viajaz** [comment]
A bit clunky, given it's global to the whole server, but it would work.
