### ISSUE TITLE
 New-UDAutocomplete does not let you select the item when using New-UDAutocompleteOption

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2583]
### Version

4.0.9

### Severity

High

### Steps to Reproduce

i am experiencing a problem when trying to set the -value of the auto complete

if i load in options with a 'name' and 'value' defined in the UDautocompleteOption, i cannot get the value to be set correctly

```
    $defaultValue = @{}
    $options = @(
        New-UDAutocompleteOption -Name "Bob" -Value 1
        New-UDAutocompleteOption -Name "Sue" -Value 2
        New-UDAutocompleteOption -Name "Matt" -Value 3
        New-UDAutocompleteOption -Name "Dave" -Value 4
    )
    # $defaultValue = @{Value = 'Matt' } #setting the default value to Matt yelds the value to be Matt and the display to be Matt
    $defaultValue = @{Value = 2 } #setting the default value to 2 yelds the value to be 2 and the display to be 2

    New-UDAutocomplete -Label 'Select Item' -Id 'FieldID' @defaultValue -Options $options -FullWidth

    New-UDButton -Text debug -OnClick {
        Show-UDToast -Message (Get-UDElement -Id 'FieldID' | ConvertTo-Json)
    }
```

`$defaultValue = @{Value = New-UDAutocompleteOption -Name "Matt" -Value 3 }` does not work either.

### Expected behavior

```console
.value to be set to the value and the name displayed instead of the value
```

### Actual behavior

```console
.value is set and the display shows the value instead of the name
```

### Additional Environment data

IIS: Nested

**Comment by MattHarrisUltima** [comment]
This may be simular to https://github.com/ironmansoftware/issues/issues/2585

**Comment by Omzig** [comment]
i have one tool that uses this heavily, and it is a bottle neck on one of our projects, i hope that it is an easy fix for the next minor release ;)

**Comment by Omzig** [comment]
So funny thing New-UDSelect can select the value correctly when the 'options' in the control look the same

These are the options from an autocomplete control:
![image](https://github.com/ironmansoftware/issues/assets/1987296/8b60f54b-3910-4728-9473-f1c6d05c0650)


These are the options from a select control:
![image](https://github.com/ironmansoftware/issues/assets/1987296/8e80a823-dc37-4a34-9856-e147c4181557)


the .value can be restored correctly to a new-udselect using -defaultValue, however new-udautocomplete cannot have its -value set to the default value; it doesn't seem compatible with the pattern. LOL, now i am just talking in circles.

**Comment by MattHarrisUltima** [comment]
Interesting.

This has put a blocker in my current workload. I'm hoping it can be fixed soon.

**Comment by Omzig** [comment]
> Interesting.
> 
> This has put a blocker in my current workload. I'm hoping it can be fixed soon.

i had to drop down to a UDSelect, as a work around, but it is hard to use when there are 1000 items in the drop down

**Comment by Omzig** [comment]
@mattselle. let me know if you need anything from me ;)
