### ISSUE TITLE
New-UDSelect options missing with inside an element

### ISSUE THREAD

**Issue by MattHarrisUltima** [ironmansoftware/powershell-universal#2585]
### Version

4.0.8

### Severity

Content

### Steps to Reproduce

We believe we have found a bug relating to New-UDSelectOption entries for New-UDSelect Elements Inside of a New-UDElement element.

This has working in PSU3.0 (untested in PSU 4.0-4.0.7).

We have 2 New-UDSelect elements. The 2nd New-UDSelect element is wraped inside a New-UDElement so we can change the select options depending on the selection in the first select menu.

Code:
```
New-UDStack -id "SelectStack" -Direction column -content {
        New-UDSelect -Id "TestSelect1" -Label "Select 1" -DefaultValue '' -Option {
            New-UDSelectOption -Name "Option 1" -value "opt1"
            New-UDSelectOption -Name "Option 2" -value "opt2"
        } -OnChange {
            $Session:TestSelectArray=@(10..100) | Get-Random -Count 3
            Show-UDToast -Message "OnChange - TestSelectArray is set to $($Session:TestSelectArray)" -Duration 10000
            Sync-UDElement -Id "TestElement1"
        }
        New-UDElement -Id "TestElement1" -Tag div -Endpoint {
            New-UDSelect -Id "TestSelect2" -Label "Select 2" -DefaultValue '' -Option {
                Show-UDToast -Message "Inside the select - TestSelectArray is set to $($Session:TestSelectArray)" -Duration 10000
                foreach ($Value in $Session:TestSelectArray) {
                    Show-UDToast -Message "Inside foreach loop - Value: $Value" -Duration 10000
                    New-UDSelectOption -Name $Value -Value $Value
                }
            }
        }
    }
```

This only seems to happen when setting Session variables ( $Session:TestSelectArray in the OnChange script block).

When we check the variables the data is there, however when we attempt to place the data in a New-UDSelectOption cmdlet the data does not appear.

![2023-08-02 14_54_28-Tom O'Brien _ Microsoft Teams](https://github.com/ironmansoftware/issues/assets/106333485/159297fa-08ab-4f0c-a0e9-bbb739ebc64b)

![2023-08-02 14_54_42-Tom O'Brien _ Microsoft Teams](https://github.com/ironmansoftware/issues/assets/106333485/e7fe1cd9-0e02-40be-818b-132d2a0961b4)

It would be handy if we could Sync-UDSelect

### Expected behavior

```console
Data is meant to be selectable in the drop down menu
```

### Actual behavior

```console
Data is not selectable.
```

### Additional Environment data

PSU 4.0.8 Linux Docker container.

**Comment by mattselle** [comment]
Hi, This is a UI id issue that is sort of out of our hands. But can easily be fixed by just removing the id on your Select 2
Example:
New-UDStack -id "SelectStack" -Direction column -content {
            New-UDSelect -Id "TestSelect1" -Label "Select 1" -DefaultValue '' -Option {
                New-UDSelectOption -Name "Option 1" -value "opt1"
                New-UDSelectOption -Name "Option 2" -value "opt2"
            } -OnChange {
                $Session:TestSelectArray=@(10..100) | Get-Random -Count 3
                Show-UDToast -Message "OnChange - TestSelectArray is set to $($Session:TestSelectArray)" -Duration 10000
                Sync-UDElement -Id "TestElement1"
            }
            New-UDElement -Id "TestElement1" -Tag div -Endpoint {
                New-UDSelect -Label "Select 2" -DefaultValue '' -Option {
                    Show-UDToast -Message "Inside the select - TestSelectArray is set to $($Session:TestSelectArray)" -Duration 10000
                    foreach ($Value in $Session:TestSelectArray) {
                        Show-UDToast -Message "Inside foreach loop - Value: $Value" -Duration 10000
                        New-UDSelectOption -Name $Value -Value $Value
                    }
                }
            }
        }

**Comment by mattselle** [comment]
Also another way to fix this is to switch to a New-UDDynamic
New-UDStack -id "SelectStack" -Direction column -content {
            New-UDSelect -Id "TestSelect1" -Label "Select 1" -DefaultValue '' -Option {
                New-UDSelectOption -Name "Option 1" -value "opt1"
                New-UDSelectOption -Name "Option 2" -value "opt2"
            } -OnChange {
                $Session:TestSelectArray=@(10..100) | Get-Random -Count 3
                Show-UDToast -Message "OnChange - TestSelectArray is set to $($Session:TestSelectArray)" -Duration 10000
                Sync-UDElement -Id "TestElement1"
            }
            New-UDDynamic -Id "TestElement1" -Content {
                New-UDSelect -Id "TestSelect2" -Label "Select 2" -DefaultValue '' -Option {
                    Show-UDToast -Message "Inside the select - TestSelectArray is set to $($Session:TestSelectArray)" -Duration 10000
                    foreach ($Value in $Session:TestSelectArray) {
                        Show-UDToast -Message "Inside foreach loop - Value: $Value" -Duration 10000
                        New-UDSelectOption -Name $Value -Value $Value
                    }
                }
            }
        }
