### ISSUE TITLE
PSScriptPad external communications should be off by default

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2597]
## Is your feature request related to a problem? Please describe.
Yes, the problem is that PSScriptPad (when opened) engages in some external communications (by default) which can be considered hazardous by some security vendors<sup>[1]</sup>.

<sup>[1] https://www.virustotal.com/gui/file/c94ec29923b8cb0d648530732a0df18448d0e1c7e4be5a6d33ed4904ada6d959/behavior</sup> 

## Describe the solution you'd like
By default, PSScriptPad could be silent on the network. The options which create network calls could be opted in by the user if desired (e.g. to check if a newer version is available).

I believe that implementation of this request is likely to reduce the number of vendors who are currently flagging the current version of PSScriptPad 7.0 as a threat. 

## Describe alternatives you've considered
Some security vendors can be individually petitioned to investigate a specific executable for inclusion to their allow list (i.e. submit a file to investigate a false positive).

## Additional context
See forum post [9562](https://forums.ironmansoftware.com/t/psscriptpad-flagged-as-malicious/9562)

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/psscriptpad-flagged-as-malicious/9562/2
