### ISSUE TITLE
API Endpoint: existing script override by new endpoint in same folder

### ISSUE THREAD

**Issue by ricoroodenburg** [ironmansoftware/powershell-universal#2603]
### Version

4.1.0

### Severity

Low

### Steps to Reproduce

1. Create a new API endpoint, for example /active-directory/users/:SamAccountName
2. Write code
3. Save script
4. Create another API endpoint in the same folder, for example: /active-directory/users/:UserPrincipalName
5. Write code
6. Save script
7. Open the first created endpoint, you're script is replaced by the second endpoint.

### Expected behavior

```console
No changes to existing endpoints.
```

### Actual behavior

```console
Changes to existing endpoints.
```

### Visuals

![PSUNI](https://github.com/ironmansoftware/issues/assets/79546116/ca281f0b-bce3-4314-aa94-bec8b6983402)

**Comment by adamdriscoll** [comment]
This is happening because those URLs are effectively the same. We should likely have validation here but you won't be able to create two URLs with the same path and the only difference in the replacement section.

**Comment by ricoroodenburg** [comment]
Hmm that's weird.
Each API works with a same URL, with only a different variable.

For example the MS Graph API:
Get a user: /users/id
List users: /users


Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ricoroodenburg** [comment]
Also: is it possible to create collections in the Swagger UI? For example: Groups, Users, Devices

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by adamdriscoll** [comment]
The problem isn't having two APIs with paths that are static. The examples you provided would work in PSU. The problem with the ones you have are they are same path with the same replacement portion. 

So for example, calling the API would be like:

Invoke-RestMethod http://localhost:5000/active-directory/users/MyUserName 

But we wouldn't be able to tell which one of the URL endpoints to call. 

Some work arounds to this include:

Defining a more specific URL to dictate which property you want to filter on:

/active-directory/users/sam/:samAccountName
/active-directory/users/principal/:userPrincipalName

Or by using something like query string parameters to pass filter criteria. 

/active-directory/users

Invoke-RestMethod http://localhost:5000/active-directory/users?samAccountName=MyUserName 

And the in the endpoint you could use the $SamAccountName variable. 

In terms of swagger collections, you can use tags to group endpoints together. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/e9a26c6f-ad5a-44d0-908b-7ee963ac6bb9)


![image](https://github.com/ironmansoftware/issues/assets/1256531/b9080492-351d-4ddd-80f8-beac4485ea0c)

**Comment by ricoroodenburg** [comment]
Hi,

I have create the following new endpoints:

  *   /active-directory/users (List all users)
  *   /active-directory/users/SamAccountName (Get a user based on SAM)

This is the same model as the Graph API I mentioned earlier. Same issue.

Maybe I don't understand it. Excuse me!

Rico



Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by adamdriscoll** [comment]
I wasn't understanding the issue completely. This is actually the same problem as this: #2552

The problem is having the same path. The path is intended for storing a single endpoint in a different file than endpoints.ps1. At the moment, the admin console allows setting the same path for multiple endpoints which results in the last one written to overwrite whatever was in the file before. 

The solution at the moment is to have two unique paths for your endpoints. 

/active-directory/users.ps1
/active-directory/users/samAccountName.ps1

**Comment by ricoroodenburg** [comment]
Hi,

Unfortunately for my bad English, haha.
I think it is clear for me: for each endpoint define a unique path.

I’m trying to change the path, but it won’t save this setting. Maybe you can create the Path field read only. I’ll create the endpoints again from scratch!

Rico

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
