### ISSUE TITLE
Broken translation file status could be more apparent

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2606]
## Summary of the new feature / enhancement

Currently, if a translation .ps1 file* is broken or malformed then the only way to know this is to check the notifications in PSU (which is readily available in the upper-right corner of the console). However, it could be more immediately apparent 👀 for the 
 end-user if the translation page itself would also indicate that there was an error detected within one of the .ps1 files within the translations directory.

<sup>* for example C:\ProgramData\UniversalAutomation\Repository\translations\en-us.ps1 has an error</sup>

## Proposed technical implementation details (optional)

A direct warning message on the Translations page in the event that the count of *.ps1 files within the translations directory (or database) does not equal the number of displayed available translations.

![image](https://github.com/ironmansoftware/issues/assets/537287/50c1b2fa-2343-47bd-8d1c-740b0032bdb7)

<sup>edited for clarification</sup>

**Comment by adamdriscoll** [comment]
#2975
