### ISSUE TITLE
There is a 5-minute lag ⏱ between service stoppage and all log files being released

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2615]
### Version

4.0.10

### Severity

Low

### Steps to Reproduce

After stopping the PowerShell Universal service on a Windows Server, there is a 5-minute lag between when the service is stopped versus when the last logs are released.

### Expected behavior

```console
systemLog_date.txt is released immediately following service stoppage
systemLog_date_001.txt is released immediately following service stoppage
systemLog_date_002.txt is released immediately following service stoppage
```

### Actual behavior

```console
systemLog_date.txt is released immediately following service stoppage
systemLog_date_001.txt is not released for exactly 5 minutes following service stoppage
systemLog_date_002.txt is not released for exactly 5 minutes following service stoppage
```

### Additional Environment data

PowerShell Universal nightly build 4.0.10 (5873064426)
Windows Server 2016

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/537287/c3bd7055-0268-4c93-9159-d2aed690c67e)

**Comment by DataTraveler1** [comment]
I forgot to include that the last line of from the systemLog_date.txt log file is:

``2023-08-16 11:12:33.568 -04:00 [DBG] Hosting stopped``

The last write time of the _001 and _002 corresponding are exactly 5 minutes later which suggests a timeout threshold

**Comment by DataTraveler1** [comment]
**Update**

I forgot to include a screenshot showing the open handles related to PowerShell Universal during the 5-minute threshold period

![image](https://github.com/ironmansoftware/issues/assets/537287/35942e7d-8830-4d11-9833-1517ae95ef5d)

**Comment by DataTraveler1** [comment]
This seems to still be an issue in PowerShell Universal 5.x current branch. I have made available privately a binary dump of the universal.server process when the log files are held for 300 seconds after stopping the service on a Kestrel installation on Windows Server 2016.

**Comment by adamdriscoll** [comment]
The change for app insights has been made and I did also find an issue with logging that could also cause this delay.
