### ISSUE TITLE
Get-PSUPublishedFolder cmdlet

### ISSUE THREAD

**Issue by MattHarrisUltima** [ironmansoftware/powershell-universal#2622]
### Summary of the new feature / enhancement

Would it be possible to get a Get-PSUPublishedFolder cmdlet to allow us to pull all data about created published folders as an object in our dashboards?

Currently, I have 5 environments. I need to be able to reference the URL's for each environment.

When setting up the environment I run a New-PSUPublishedFolder and the name of my published folder is identical across all environments. I would like to be able to run a 'Get-PSUPublishedFolder -name "MyPublishedFolder"' to be able to pull back the generated URL.
![2023-08-17 14_44_18-PowerShell Universal — Mozilla Firefox](https://github.com/ironmansoftware/issues/assets/106333485/78c0481b-a2c9-4027-9bc9-507aaaa9eef9)

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/how-to-pull-info-about-a-published-folder-get-psupublishedfolder/9597/4

**Comment by MattHarrisUltima** [comment]
Hi @adamdriscoll ,

I have pulled a 4.1.0 environment into a container to have a look at this new cmdlet.

How do I get the URL you can copy to clipboard from the 3rd button on the GUI? I can't seam to see this when I run the Get-PSUPublishedFolder cmdlet.

**Comment by adamdriscoll** [comment]
@MattHarrisUltima The RequestPath parameter of the objects returned will be the relative path for the published folder. 

For example, it would be /images and then to get the URL like the one in the admin console, you would need to combine it with your server URL.

**Comment by MattHarrisUltima** [comment]
Thanks @adamdriscoll.  That gives me everything I need.
