### ISSUE TITLE
New-UDAvatar -Variant rounded not working on 4.0.10

### ISSUE THREAD

**Issue by insomniacc** [ironmansoftware/powershell-universal#2633]
### Version

4.0.10

### Severity

Low

### Steps to Reproduce

New-UDAvatar -Image $session:AvatarPicture -Variant rounded

### Expected behavior

```console
Rounded avatar
```

### Actual behavior

```console
Square avatar
```

### Additional Environment data

Docker 4.0.10 ubuntu 20.4

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/10046621/3ac6c4e8-a7a4-44d9-9ebb-accaa4002101)

**Comment by mattselle** [comment]
So issue was we actually only supported rounded and square and not MUIs default circle. Rounded is just square rounded the circle is the default MUI but we didn't allow it. Now we will

**Comment by insomniacc** [comment]
I have a New-UDAvatar on my dashboard with the -variant "rounded" parameter.
It seems after updating to 4.1 the avatar was still square. 
If I remove the -variant parameter all together then it does infact default to rounded, but -variant "rounded" doesn't work as expected.
It's a minor issue with an easy workaround but figured i'd flag it incase others don't realise

@mattselle

**Comment by mattselle** [comment]
Hi @insomniacc
I got confused by this too. We use MUI for most of our UI components. There default is the circle you are looking for which we now support. The -variant rounded is actually meant for square with rounded corners per MUI. https://mui.com/material-ui/react-avatar/#variants

**Comment by insomniacc** [comment]
> Hi @insomniacc
> I got confused by this too. We use MUI for most of our UI components. There default is the circle you are looking for which we now support. The -variant rounded is actually meant for square with rounded corners per MUI. https://mui.com/material-ui/react-avatar/#variants

Ohh I get you! Thanks for explaining. It might be worth adding an option to -variant for either 'default' or 'circle' to make it more explicit and list all available options.
