### ISSUE TITLE
Public API for download info

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#2638]
### Summary of the new feature / enhancement

To automate the update of our Windows PSU servers, it would be beneficial to have the download info available.
Today we have to manually download the version, enter the meta data in a SQL table, and then our scripts can automatically update the PSU servers with the required version.

We would therefor like an public exposed API maintained by ironman software, that contains the version and URL of each version & type - so that we can download it automatically.

It could be like this:
```
{
  "Versions": {
    "4.0.11": {
      "WindowsServerURL": "https://imsreleases.blob.core.windows.net/universal/production/4.0.11/PowerShellUniversal.4.0.11.msi",
      "LinuxServerURL": "https://imsreleases.blob.core.windows.net/universal/production/4.0.11/Universal.linux-x64.4.0.11.zip",
      "WindowsDesktopURL": "https://imsreleases.blob.core.windows.net/universal/production/4.0.11/PowerShellUniversal.Desktop.4.0.11.exe"
    },
    "4.0.10": {
      "WindowsServerURL": "https://imsreleases.blob.core.windows.net/universal/production/4.0.11/PowerShellUniversal.4.0.11.msi",
      "LinuxServerURL": "https://imsreleases.blob.core.windows.net/universal/production/4.0.11/Universal.linux-x64.4.0.11.zip",
      "WindowsDesktopURL": "https://imsreleases.blob.core.windows.net/universal/production/4.0.11/PowerShellUniversal.Desktop.4.0.11.exe"
    }
  }
}
```

**Comment by Omzig** [comment]
they are supposed to be adding auto update support

**Comment by ksl28** [comment]
> they are supposed to be adding auto update support

That is also a really awesome feature to get! But i can still see the usecase, for having the public API info.
_We stage our PSU updates on test servers for a few days, before rolling them into production - so an auto update, would prob just update all of them at the same time_

**Comment by adamdriscoll** [comment]
We actually do this internally for the previous versions page so I just exposed that as a JSON API. 

https://ironmansoftware.com/api/downloads/powershell-universal

**Comment by ksl28** [comment]
@adamdriscoll - Nice! :)
It would be handy in the future, to have a static value to search for (WindowsServerURL, LinuxServerURL, etc).
Right now we are filtering if the filename is *.msi 

```
$APIArray = Invoke-RestMethod -Uri "https://ironmansoftware.com/api/downloads/powershell-universal" -Method Get -ContentType "application/json"
$URL = $APIArray[0].files | Where-Object {$_.Url -like "*.msi"}
Invoke-WebRequest -Uri $URL.url -OutFile "C:\Temp\$($URL.Name)"
```
