### ISSUE TITLE
Error in documentation - admin password is admin

### ISSUE THREAD

**Issue by ssg47** [ironmansoftware/powershell-universal#2649]
### Version

4.1.0

### Severity

Content

### Steps to Reproduce

Install the product for the first time.
Navigate to [http://localhost:5000/](http://localhost:5000/)
Attempt to login with username **admin** and any password.

The [documentation](https://docs.powershelluniversal.com/getting-started) says 'You will be able to navigate to http://localhost:5000 and login with admin and any password' whereas the password required is **admin**.

### Expected behavior

```console
You get logged in.
```

### Actual behavior

```console
You get the error message:
Bad username or password
```

### Additional Environment data

4.0.12

**Comment by DataTraveler1** [comment]
@ssg47 - Thank you for reporting this. Although there is a separate repository for the PSU documentation at [https://github.com/ironmansoftware/universal-docs/issues](https://github.com/ironmansoftware/universal-docs/issues), I have raised this internally and am estimating that the documentation will be updated on this point soon.

**Comment by DataTraveler1** [comment]
@ssg47 - Just a follow up to confirm that the PowerShell Universal documentation (for supported versions 3.x and 4.x) has been updated 👍
