### ISSUE TITLE
New-UDForm with Schema does not emit $EventData anymore

### ISSUE THREAD

**Issue by gitbute** [ironmansoftware/powershell-universal#2650]
### Version

4.0.9

### Severity

High

### Steps to Reproduce

Hi

Just use the first example on
https://docs.powershelluniversal.com/userinterfaces/components/inputs/form#schema-forms
It does not produce a $EventData variable

### Expected behavior

```console
$EventData gets emitted
```

### Actual behavior

```console
no $EventData gets emitted
```

**Comment by adamdriscoll** [comment]
The documentation was incorrect. It should be $EventData.name rather than $EventData.formData.Name. I've corrected the documentation.
