### ISSUE TITLE
Improve UDButtonGroup behavior

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2651]
### Summary of the new feature / enhancement

I don't think the first button should be included in the drop down. I also think the items in the drop down should invoke their onClick when pressed rather than selecting them.

**Comment by rwidmark** [comment]
@adamdriscoll it would also be great if it was possible to have a icon as the first so you see the icon in the dashboard and when clicking on it , it will list the rest of the buttons.
