### ISSUE TITLE
Error at login - Cannot Communicate with the security service

### ISSUE THREAD

**Issue by TurnItOff-OnAgain** [ironmansoftware/powershell-universal#2652]
### Version

4.0.10

### Severity

Low

### Steps to Reproduce

Forms based login. Every so often I will get an error at the login page saying it could not communicate with the security service. I get this error even when using the built in admin account. Restarting the Universal service doesn't fix it, but rebooting the server does. I have a dump of the process, but it's quite large (1.12GB). Is there somewhere I can send that? I can share from my onedrive if needed

### Expected behavior

```console
Login works
```

### Actual behavior

```console
Error message
```

### Additional Environment data

Universal 4.0.10
Windows Server 2019
Built in Kestrel web server

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/26926284/be6292c6-233c-4dcc-a399-76e81a562fd6)

**Comment by adamdriscoll** [comment]
You can send an email to support[at]ironmansoftware.com with a OneDrive link. Any logs would be helpful too.

**Comment by TurnItOff-OnAgain** [comment]
Link sent. Thanks

**Comment by adamdriscoll** [comment]
Closing this for now. Feel free to reopen if anything pops up.
