### ISSUE TITLE
Suppress PSScriptAnalyzer warnings for Write-Host

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#2658]
### Summary of the new feature / enhancement

Since write-host is how you log in PSU, it shouldn't show as a PSScriptAnalyzer warning

### Proposed technical implementation details (optional)

PSScriptAnalyzer supports "ExcludeRules", so it should be possible to suppress these warnings.

**Comment by Omzig** [comment]
please, and thank you, or at least give us a way to add the exceptions in ;)

**Comment by adamdriscoll** [comment]
You'll be able to define a PSScriptAnalyzerSettings.psd1 file in the repository and it will be auto-loaded by PSU.

https://learn.microsoft.com/en-us/powershell/utility-modules/psscriptanalyzer/using-scriptanalyzer?view=ps-modules#explicit

**Comment by MikeShepard** [comment]
Maybe this should be a documentation issue?  Adding that file makes the PSScriptAnalyzer integration a lot more useful.
