### ISSUE TITLE
Dynamic regions are not updating properly in v4

### ISSUE THREAD

**Issue by insomniacc** [ironmansoftware/powershell-universal#2661]
### Version

4.0.10

### Severity

High

### Steps to Reproduce

Use the example code from [auto refreshing charts in the documentation](https://docs.powershelluniversal.com/userinterfaces/components/data-visualization/charts#auto-refreshing-charts)

```powershell
New-UDDynamic -Content {
    $Data = 1..10 | % { 
        [PSCustomObject]@{ Name = $_; value = get-random }
    }
    New-UDChartJS -Type 'bar' -Data $Data -DataProperty Value -Id 'test' -LabelProperty Name -BackgroundColor Blue
} -AutoRefresh -AutoRefreshInterval 1
```

### Expected behavior

```console
Graph refreshes every 1 second
```

### Actual behavior

```console
Component renders once and does not auto refresh.
```

### Additional Environment data

Tested in ubuntu docker, and also local desktop on a windows 10 machine using the MSI install.
Tested on 4.0.11 - Issue present#
Tested on 4.0.2 - Issue present
Tested on 3.9.17 - Is is **not** present.

I have noticed multiple problems with dynamic data over the last two weeks while on v4 and havent thought too much about it as I've managed to implement workarounds but I think there's a fundamental bug with dynamic regions in v4.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/cant-get-udtable-to-update/9670/6

**Comment by adamdriscoll** [comment]
There is something wrong with the client-side react updates. If you remove the -ID, you will see it update (not smoothly due to it re-rendering the entire control).

**Comment by insomniacc** [comment]
Thanks, that helps in the short term, see what you mean about it not being smooth, seems to just hang after 10 seconds and pause until the thing has reloaded and it goes again for another 10 seconds

**Comment by adamdriscoll** [comment]
I've spotted the issue with the chart and it's actually related to the chart and not the dynamic. It also looks like 4.1 will fix the issue with the table not updating in a dynamic. 

Do you have any other components that you were having this problem with? I've spotted the pattern that is causing this but, unfortunately, it looks like it's per component. I'll poke around to see if I can find other instances of it.

**Comment by adamdriscoll** [comment]
I reviewed all the components for the offending pattern and found several others that likely had this issue as well:

- DatePicker
- TimePicker
- AutoComplete

As mentioned, this fix will also resolve the issue with charts and tables.

**Comment by insomniacc** [comment]
Awesome as always, thanks for being so quick on this one!
