### ISSUE TITLE
Date picker displays wrong time format

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#2665]
### Version

4.1.0

### Severity

Visual

### Steps to Reproduce

If you set date format as yyyy-MM-dd then the date picker display it in a strange way.

### Expected behavior

```console
Display it in the right format
```

### Actual behavior

```console
It don't show in the right format
```

### Visuals

![Screenshot 2023-09-10 at 19 33 49](https://github.com/ironmansoftware/issues/assets/76907327/d7f472d3-7f4f-41aa-9264-75adf2a8db91)

**Comment by insomniacc** [comment]
I'm not sure what the underlying react component is so maybe this is just the difference between the typical powershell format vs whatever the underlying component uses, but you can get the date you want with uppercase YYYY, and assuming you want numerical day as well, use uppercase for that:

New-UDDatePicker -Format "YYYY-MM-DD"

**Comment by rwidmark** [comment]
Before 4.0 you could write yyyy-MM-dd or yyyy-MM-DD but now you need to write it as YYYY-MM-DD as @insomniacc stated.
So this is not a issue just a change
