### ISSUE TITLE
New-UDDynamic with table inside of it won't update unless you have -loadingcomponent

### ISSUE THREAD

**Issue by TurnItOff-OnAgain** [ironmansoftware/powershell-universal#2670]
### Version

4.0.10

### Severity

Low

### Steps to Reproduce

https://forums.ironmansoftware.com/t/table-in-dymanic-region-not-updating/9697

I confirmed this is the case. Code is in the link.

I also did a basic page with this and it worked as expected, both typography's updated. Seems to be complex dynamics?

````
New-UDDynamic -id "test1" -Content {
        New-UDTypography -Text "$(get-date)"
    }

    new-udhtml -Markup "</br>"
    new-udhtml -Markup "</br>"
    
    New-UDDynamic -id "test2" -Content {
        New-UDTypography -Text "$(get-date)"
    } -LoadingComponent {
        New-UDProgress -Circular
    }

    new-udbutton -text "click" -OnClick {
        Sync-UDElement -Id "test1"
        Sync-UDElement -id "test2"
    }
````

### Expected behavior

```console
table updates without loading component needed
```

### Actual behavior

```console
table won't update unless you have loading component
```

**Comment by adamdriscoll** [comment]
We just fixed this for 4.1. Here's some more info: https://github.com/ironmansoftware/issues/issues/2661
