### ISSUE TITLE
-Dense is missing from New-UDListItem

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#2677]
### Version

4.1.0

### Severity

Visual

### Steps to Reproduce

In 4.1.0 you did add -Dense to New-UDList and that works fine and looks super good, the issue now is that you don't have -Dense for New-UDListItem.
If you have a List with and then use -Children for New-UDListItem then it will look to big as the "main" list is -Dense

### Expected behavior

```console
That New-UDListItem -Children { can have -Dense
```

### Actual behavior

```console
New-UDListItem -Children { are missing -dense and then everything looks kind of goofy. As you can see with "Sök information"
```

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/76907327/211c0009-a8fe-40d9-b038-5c07dbf1cf1f)

**Comment by mattselle** [comment]
Could I get some example code for this? I currently can't repro this
$Drawer = New-UDDrawer -Id 'drawer' -Children {
            New-UDList -Dense -Content {
                New-UDListItem -Label 'Inbox' -Icon (New-UDIcon -Icon envelope)
                New-UDListItem -Label 'Drafts' -Icon (New-UDIcon -Icon edit)
                New-UDListItem -Label 'Trash' -Icon (New-UDIcon -Icon trash)
                New-UDListItem -Label 'Spam' -Icon (New-UDIcon -Icon bug) -Children {
                    New-UDListItem -Label 'Drafts' -Icon (New-UDIcon -Icon edit)
                    New-UDListItem -Label 'Trash' -Icon (New-UDIcon -Icon trash)
                }
            } -Id 'list1'

        }
        New-UDElement -Tag 'main' -Content {
            New-UDAppBar -Children { New-UDTypography -Text 'Test' } -Drawer $Drawer
        }

![image](https://github.com/ironmansoftware/issues/assets/17792677/cbdf84f8-52e0-4d94-b3da-f6aca41c5c9c)

**Comment by rwidmark** [comment]
@mattselle you need to use the -nested switch on the children.

I'll post code when I'm at my computer again but as far as I can see your missing -nested on the children so my guess is that's not  working together

**Comment by rwidmark** [comment]
@mattselle  here's a code example:

```
New-UDList -Dense -Content {
            New-UDListItem -Label 'Program' -Icon (New-UDIcon -Icon BoxesPacking -Size lg) -Children {
                New-UDListItem -Nested -Label "$tl:Search" -Icon (New-UDIcon -Icon MagnifyingGlass -Size lg) -OnClick { Invoke-UDRedirect '/program' }
            }
}
```

**Comment by rwidmark** [comment]
@mattselle  do you have an email so I can send you my code? I don't want to publish it here.

**Comment by mattselle** [comment]
@rstolpe thank you so much. I was able to repro this and should have it fixed today or tomorrow

**Comment by mattselle** [comment]
Adam and I talked about this one and if the New-UDList -Dense we are going to make all children dense as well. PR is in for this
