### ISSUE TITLE
"Entry point was not found" when using KeyVault modules

### ISSUE THREAD

**Issue by MattHarrisUltima** [ironmansoftware/powershell-universal#2681]
### Version

4.1.0

### Severity

High

### Steps to Reproduce

Following testing of a new environment and upgrade of a container image on an existing environment, Azure connectivity does not appear to be working as expected.

The container image in question is: `ironmansoftware/universal:4.1.0-modules`

In a new environment, PowerShell Universal appears to be unable to connect to an Azure Tenant via Service Principal. claiming it can not find an application ID in the given tenant.
```
[warning] The provided service principal secret or certifcate password will be included in the 'keystore.cache' file found in the user profile ( /root/.Azure ). Please ensure that this directory has appropriate protections. 
[error] Entry point was not found.
Could not find tenant id for provided tenant domain 'xxxxxxxx-aae9-44fe-bdc4-53f76xxxxxd0'. Please ensure that the provided service principal 'xxxxxxx-4d45-4a37-be96-dfea4xxxxx71' is found in the provided tenant domain. 

```

In an upgraded environment, `Get-AZContext` returns the current subscription in a tenant however `Disconnect-AZAccount` returns the following error:
```
[ERROR] Method not found: 'Microsoft.Identity.Client.PublicClientApplicationBuilder Microsoft.Identity.Client.Broker.BrokerExtension.WithBrokerPreview(Microsoft.Identity.Client.PublicClientApplicationBuilder, Boolean)'.
```

A `Get-AZKeyvault` returns the following error:
```
[ERROR] Your Azure credentials have not been set up or have expired, please run Connect-AzAccount to set up your Azure credentials.
Entry point was not found.
```

I can see there have been some version changes in the modules provided this may be the problem
![2023-09-15 13_54_24-PowerShell Universal — Mozilla Firefox](https://github.com/ironmansoftware/issues/assets/106333485/1697defa-59c4-41a7-994a-3b330c489ec9)
:

### Expected behavior

```console
Commands like `Connect-AZAccount`, `Disconnect-AZAccount`, and `Get-AZKeyvault` work as expected.
```

### Actual behavior

```console
`Disconnect-AZAccount` returns the following error:

[ERROR] Method not found: 'Microsoft.Identity.Client.PublicClientApplicationBuilder Microsoft.Identity.Client.Broker.BrokerExtension.WithBrokerPreview(Microsoft.Identity.Client.PublicClientApplicationBuilder, Boolean)'.
```

A `Get-AZKeyvault` returns the following error:
```
[ERROR] Your Azure credentials have not been set up or have expired, please run Connect-AzAccount to set up your Azure credentials.
Entry point was not found.
```

Reverting to 4.0.12-modules and re-running my keyvault setup commands appears to return functionality.
```


### Additional Environment data

_No response_

### Visuals

_No response_

**Comment by MattHarrisUltima** [comment]
Hi @adamdriscoll,

Thank you for making the change to static versions, however it appears the versions have been frozen on the faulty versions.

Are you able to modify this on the next release?

**Comment by adamdriscoll** [comment]
Hmmm. Let me double check this. I thought we pinned to the older versions. 

UPDATE: It looks like both versions got in some how...

![image](https://github.com/ironmansoftware/issues/assets/1256531/cd9c97fc-0e12-419f-9996-89ddb4616192)

**Comment by adamdriscoll** [comment]
I found the root cause. This will be in tonight's module-preview container and next week's 4.1.2 release.

**Comment by MattHarrisUltima** [comment]
Thanks Adam,

Ill run the preview container in the morning and let you know how it goes.

Kind Regards,

MATT​​​​

HARRIS
 |
Cloud Automation Developer
 |
www.ultima.com<http://www.ultima.com/>
 |

**Comment by MattHarrisUltima** [comment]
Hi @adamdriscoll,

It looks like we are still getting some errors.

After testing the preview image, `ironmansoftware/universal:4.1.2-preview-modules` I am still receiving the same error In 4.1.x using the same versions. 

I transferred the 

Connecting to Azure appears to be the problem.

I have pulled `4.1.1-ubuntu-20.04` without the modules and moved Az.Accounts into the /root modules' folder, and I am receiving exactly the same error:

```
[warning] The provided service principal secret or certifcate password will be included in the 'keystore.cache' file found in the user profile ( /root/.Azure ). Please ensure that this directory has appropriate protections. 
[error] Entry point was not found.
Could not find tenant id for provided tenant domain '########-####-####-####-############'. Please ensure that the provided service principal '########-####-####-####-############' is found in the provided tenant domain. 
```


I pulled a copy of Az.Accounts version 2.10.14 from a backup and it appears to work. Im wondering if the Az.Accounts module bundled in the home directory has been corrupted?

**Comment by adamdriscoll** [comment]
Very weird. We are using Save-Module to download that module before building the container so I don't know why it would be corrupt.

**Comment by MattHarrisUltima** [comment]
I agree, this is very weird. 

Had anything else been added in 4.1.x which could disrupt module loading? I saw PowerShell 7.3.7 was included, I was wondering if anything else relating to code execution within an environment could have changed?

**Comment by MattHarrisUltima** [comment]
Hi @adamdriscoll,

I have been thinking this over. Is there a command I can use to rescan the /home/Universal/Modules/ manually?

This would allow me to monitor logs and potentially do some testing.

**Comment by MattHarrisUltima** [comment]
Hi @adamdriscoll 

Please advise if there is anything you need from me on this issue. 

Additionally, after today I am on annual leave until the 9th October and will be unable to reply until my return.

**Comment by adamdriscoll** [comment]
@MattHarrisUltima  - I will be reviewing this tomorrow and will let you know if I need anything else. Hopefully this is resolved when you return. :)

**Comment by adamdriscoll** [comment]
Success! 

![image](https://github.com/ironmansoftware/issues/assets/1256531/7953b9b7-7d27-4340-b79d-476a035ad98a)


After much code spelunking, I was able to determine the root cause was actually the upgrade Microsoft.Data.SqlClient. It included a reference to Azure.Identity 1.7.0. The Az cmdlets actually use a newer version of that package. Once I upgraded that, it works great.

**Comment by adamdriscoll** [comment]
While this fixed Azure Accounts integration, it broke a lot of other things. I need to push this to 4.2. We are rolling this back and releasing 4.14.

**Comment by MattHarrisUltima** [comment]
Hi @adamdriscoll,

Thanks for the update. I will wait for 4.2.

**Comment by adamdriscoll** [comment]
@MattHarrisUltima - This change will be included in tonight's nightly build and preview containers.

**Comment by MattHarrisUltima** [comment]
Thanks for the preview image @adamdriscoll 

That loads up without error on my end.

Please feel free to reach out if you would like any images tested.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/can-no-longer-connect-to-azure-with-connect-azaccount/9908/3
