### ISSUE TITLE
Prerelease module for nightly builds

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2683]
## Request
If a minor build version of PowerShell Universal exists only in Nightly Build form then a corresponding version of Universal PowerShell module could be published as a PreRelease type of module. This would allow the nightly build to have a matching module.

## Context
Currently, version 4.2.x is only available as a nightly build. When the current 4.1.x PowerShell Universal VS Code extension connects to a 4.2.x instance, it seeks (via `Install-UniversalModule -Version '4.2.0'`) a corresponding version of Universal module from the PS Gallery which is not available.

## Alternatives

- If the PowerShell Universal VS Code extension detects that it is connecting to a nightly build instance of PowerShell Universal, don't attempt to update the Universal module
- The PowerShell Universal VS Code extension could attempt to confirm (via `Find-Module`) that the version it is seeking exists on the PS Gallery

## Miscellaneous
![image](https://github.com/ironmansoftware/issues/assets/537287/1059b70f-2544-4aa5-b6a5-64e36ac70ba0)

**Comment by adamdriscoll** [comment]
@DataTraveler1 - We used to do this with the universaldashboard module but the PS team didn't want us publishing nightly builds to the gallery. We should consider setting up our own pre-release repository.

**Comment by adamdriscoll** [comment]
We include this with the ZIP.
