### ISSUE TITLE
New-UDMenu drop mandatory -Text if -Icon is provided

### ISSUE THREAD

**Issue by insomniacc** [ironmansoftware/powershell-universal#2685]
### Summary of the new feature / enhancement

I'd love to be able to use the following code to make a elipsis button with a drop down menu:

```powershell
New-UDMenu -Icon $(New-UDIcon -Icon ellipsis) -Content {
                New-UDMenuItem -Text 'Export'
                New-UDMenuItem -Text 'Delete'
}
```

The only issue with the above is that -Text is mandatory, so this will not work if it's not provided.
If you provide an empty string it will throw an error.
If you provide " " it will cause the icon to look off centre.

### Proposed technical implementation details (optional)

Drop the mandatory flag on -Text, and instead put validation to check if text/icon is provided so it can be one, or the other, or both and only complain if neither are provided.

**Comment by rwidmark** [comment]
Did struggle with this my self today.
It would be perfect if text was not mandatory
