### ISSUE TITLE
Ability to submit logs directly to support ⬆

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2686]
## Request
Add the ability to submit logs directly to Ironman Software through the PowerShell Universal console

## Context
Some users of PowerShell Universal may not be able to submit logs for support by way of support ticket due to limitation of mail attachment size 📩

## Benefits
Increased convenience and possibly reduction in time to resolve for support tickets

## Remarks
There should probably be strict limits on how many files and the total size of the submission (e.g. only the first 100MB of logs according to filedate)

###### below figure shows the feature imagined as a '_Submit logs to support_' button under Platform -> Logging
![image](https://github.com/ironmansoftware/issues/assets/537287/ab19d73a-38f9-4593-b6ac-f362614c794f)

**Comment by kevinblumenfeld** [comment]
This is a fantastic idea. Additionally, I’d appreciate a button that enables the appropriate logging required by the support team and then allows us to revert back to the original settings.
