### ISSUE TITLE
Dark theme - New-UDButton -ShowLoading not working

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#2691]
### Version

4.1.0

### Severity

Low

### Steps to Reproduce

If you have a New-UDButton with the -ShowLoading parameter, you can see the circle spinning when the App is in White mode.
But if you switch to dark mode, there is no circle - the button just disappears  instead.

### Expected behavior

```console
The the circle is presented in both dark and white mode.
```

### Actual behavior

```console
The circle is not presented in the dark mode.
```

**Comment by schubfre** [comment]
I just encountered this on friday on 3.9.17. Can you fix it in 3.9.18 too please
