### ISSUE TITLE
New-UDDatePicker -Variant dialog/inline

### ISSUE THREAD

**Issue by insomniacc** [ironmansoftware/powershell-universal#2696]
### Version

4.1.0

### Severity

Low

### Steps to Reproduce

New-UDDatePicker -OnChange {
    Show-UDToast -Message $body
} -Variant dialog

New-UDDatePicker -OnChange {
    Show-UDToast -Message $body
} -Variant inline

### Expected behavior

```console
According to:
https://docs.powershelluniversal.com/userinterfaces/components/inputs/date-picker

inline should pop up the picker inline, while dialog should show in the middle of the screen.
```

### Actual behavior

```console
Both dialog and inline behave the same.
```

**Comment by adamdriscoll** [comment]
Apparently, it is printing a warning: 

```
    if ($Variant -eq 'dialog') {
        Write-Warning "Variant dialog is deprecated. Inline will be used."
    }
```

I will just remove the dialog option and update the docs.

**Comment by insomniacc** [comment]
> Apparently, it is printing a warning: 
> 
> ```
>     if ($Variant -eq 'dialog') {
>         Write-Warning "Variant dialog is deprecated. Inline will be used."
>     }
> ```
> 
> I will just remove the dialog option and update the docs. 

Thanks!
Ah, I guess I didn't see that one. 
I've worked around it using UDModal + Static which is fine too 👍
