### ISSUE TITLE
Version 4.1.2 - New-UDApp -LoadNavigation failed

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#2709]
### Version

4.1.0

### Severity

Visual

### Steps to Reproduce

If we use the New-UDApp with the parameter "-LoadNavigation" it will fail with the following error:
```
Error with dashboard script
Missing an argument for parameter 'LoadNavigation'. Specify a parameter of type 'UniversalDashboard.Models.Endpoint' and try again.
at <ScriptBlock>, C:\ProgramData\UniversalAutomation\Repository\dashboards\uitest\uitest.ps1: line 68
at <ScriptBlock>, <No file>: line 1
System.Management.Automation.ParameterBindingException: Missing an argument for parameter 'LoadNavigation'. Specify a parameter of type 'UniversalDashboard.Models.Endpoint' and try again.
```

If we then use the "-HideNavigation" its working as expected, and actually hides the navigation.

There is no documentation on the "-LoadNavigation" parameter, so either its a bug, or im actually missing an argument - but im unsure what argument that should then be.

Steps to reproduce:
```
$Navigation = @(
    New-UDListItem -Label 'Start' -Icon (New-UDIcon -Icon 'Toolbox') -OnClick {
        Invoke-UDRedirect -Url '/app/home/start' -Native
    }    
    New-UDListItem -Label "Test group 1" -Children {
        New-UDListItem -Label "Test sub page1" -Icon (New-UDIcon -Icon building-user) -Href "/page/test/subpage1" -Nested
    }
)
New-UDApp -Title 'PowerShell Universal' -Pages $Pages -Navigation $Navigation -NavigationLayout Permanent -LoadNavigation
```

### Expected behavior

```console
That -LoadNavigation would automatically expand the Navigation Menu
```

### Actual behavior

```console
It breaks the entire site
```

**Comment by adamdriscoll** [comment]
Here is how to use -LoadNavigation: https://docs.powershelluniversal.com/userinterfaces/components/pages#dynamic-navigation

**Comment by ksl28** [comment]
> Here is how to use -LoadNavigation: https://docs.powershelluniversal.com/userinterfaces/components/pages#dynamic-navigation


Ohh! I was under the impression, that it would automatically expand the New-UDListItem, so that all the childrens below would be visible. 
I will create a feature request for that then :)
