### ISSUE TITLE
$Cache Scope is not shared between API and Apps

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#2721]
### Version

4.1.4

### Severity

Critical

### Steps to Reproduce

Create a Cache Variable in an API Endpoint and try to use it in an App (and vice-versa). It won't be available!

### Expected behavior

```console
The $Cache Scope should be available everywhere in PSU. Apps, API, Modules, etc.
```

### Actual behavior

```console
The $Cache Scope is specific to each function in PSU. Can't imagine that this is by design...? Hope not!
```

### Additional Environment data

Server W2K22

**Comment by adamdriscoll** [comment]
If the apps and APIs are running in different processes, they will not share the same $Cache. You will need to use the server-level cache scope instead: https://docs.powershelluniversal.com/platform/cache#server-level-cache

**Comment by donlent** [comment]
Aha... As easy as that... As always... If you know how the system works... 😉 
Thanks a lot adam! That obviously clears everything... 😉 
Best regards, Don
