### ISSUE TITLE
UDModal, fullheight

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#2722]
### Summary of the new feature / enhancement

Today you have fullwidth and it works perfectly with the different sizes.

but, you don't have fullheight. It's kind of ugly when the modal colaps when you reload something in a udelement or similar.
For example table

**Comment by adamdriscoll** [comment]
Would -FullScreen make sense here or do you want the width to be narrow and it to be full height?

**Comment by rwidmark** [comment]
@adamdriscoll  Sure, -fullscreen works but I was more thinking of that in some cases you might want to have the window smaller then -fullscreen and still have it it in the same size when it's loading and / or not loading.

**Comment by rwidmark** [comment]
@adamdriscoll maybe I dident explain correctly.

For example if you want a modal to be md in size and everything works fine and looks great until you refresh the element where the table or something else is inside then the hole modal get compact (smaller in size) until the data from the element shows then the modal is md again.

It's on the height

**Comment by rwidmark** [comment]
@adamdriscoll  I have tried with -fullwidth etc. and it will still collapse when your reloading the content instead of have it the same size all the time.
-Persistent switch should also keep the window the same size all the time :)

Just to be clear I want height of the modul to be persistent all the time.

**Comment by adamdriscoll** [comment]
Can you provide a code sample? I kinda think I understand but a sample would be great.

**Comment by rwidmark** [comment]
> Can you provide a code sample? I kinda think I understand but a sample would be great.

I'll post it tonight

**Comment by rwidmark** [comment]
@adamdriscoll  I did send a support ticket for this ticket ID 6836
