### ISSUE TITLE
New-UDDatePicker will not clear

### ISSUE THREAD

**Issue by dkkazak** [ironmansoftware/powershell-universal#2734]
### Version

4.1.2

### Severity

Low

### Steps to Reproduce

In a UDForm, I have a New-UDDatePicker.  If I clear out the date on it, it will still pass through today's date when -OnSubmit .  I have had this happen in much older versions and it was fixed, but looks like it is an issue again. 

Here is some sample:
New-UDForm -Id "PMUpdateDateInput$ProjectManagementPKID" -ButtonVariant contained -Content {
	If ($PMInfo.PMProposedDate) {
		New-UDDatePicker -Id "PMProposedDateInput" -Label "Proposed Date" -Value $PMInfo.PMProposedDate
	} Else {
		New-UDDatePicker -Id "PMProposedDateInput" -Label "Proposed Date"
	}
	If ($PMInfo.PMReceivedProposalDate) {
		New-UDDatePicker -Id "PMReceivedProposalDateInput" -Label "Received Proposal Date" -Value $PMInfo.PMReceivedProposalDate
	} Else {
		New-UDDatePicker -Id "PMReceivedProposalDateInput" -Label "Received Proposal Date" 
	}
} -OnSubmit {
	$PMProposedDateInput = $EventData.PMProposedDateInput
	$PMReceivedProposalDateInput = $EventData.PMReceivedProposalDateInput
	#Remaining work here
}

### Expected behavior

```console
When I clear the field in the form, that no date/time gets sent through.
```

### Actual behavior

```console
Receive the following:

[32;1mPMProposedDateInput           : [0m9/20/2023 7:47:10 PM
[32;1mPMReceivedProposalDateInput   : [0m10/2/2023 7:47:10 PM
```

### Additional Environment data

This is a dashboard running in a PowerShell 7.2 environment.

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/16762695/60b54c9f-8f52-4761-954f-6e884537d2dc)

**Comment by DougNeely** [comment]
I have installed both 1.4.6 and 1.4.7 and am still having this problem.
