### ISSUE TITLE
Built in monitoring URL

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#2736]
### Summary of the new feature / enhancement

We have a few Apps running that are using authentication - each of these Apps have 10-20 pages under them have different roles as well.

We want to monitor that each of these URLs are available using our monitoring system, but dont want to specify a credential for each of these pages.

Would it be possible to have a dedicated monitor page for each Apps / Page, that we can monitor the HTTP status code for?

**Comment by adamdriscoll** [comment]
You could easily implement this with a custom API. I don't think we'll get this specific on monitoring URLs for apps.
