### ISSUE TITLE
Windows Auth shows anonymous in User Sessions

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2738]
### Version

4.1.4

### Severity

Low

### Steps to Reproduce

When using windows auth, the user sessions page shows anonymous for the connection., 

### Expected behavior

```console
Shows the user name
```

### Actual behavior

```console
Shows anonymous
```

**Comment by ghost** [comment]
I think we might be seeing this again in 5.5.5, but not really sure why. Some sessions for the same user show the correct user name, while occasionally some show Anonymous.
