### ISSUE TITLE
Changing git settings removes credentials

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2742]
### Version

4.1.5

### Severity

Low

### Steps to Reproduce

Configure git in the admin console
Edit git settings (for example, adjust interval)
Git not longer works because git credentials are gone

### Expected behavior

```console
Git credentials are retained
```

### Actual behavior

```console
Git credentials are cleared out
```

**Comment by schubfre** [comment]
As with #2691 could you fix this in 3.9.x too please.

I always thought this was wanted behaviour and therefore didn't report it. The current workaround is, you have to paste the user and password again.
