### ISSUE TITLE
Make $Query dictionary keys case insensitive

### ISSUE THREAD

**Issue by realslacker** [ironmansoftware/powershell-universal#2752]
### Summary of the new feature / enhancement

In cases where I don't have 100% control over the input for query parameters I find it difficult to manage lookups in the $Query dictionary.

Right now I have to do something like:

```powershell
$Query.Keys | Where-Object { $_ -eq 'MyKey' } | ForEach-Object { $Query.Item($_) }
```

### Proposed technical implementation details (optional)

Ideally I feel like a hashtable suits this use case better than a dictionary. Hardly any server side scripting languages treat request keys as case sensitive.

Other possible solutions are implementing a dictionary with a case insensitive comparer or converting all of the keys to upper or lower case so lookups are easier.

**Comment by adamdriscoll** [comment]
Made it a hashtable for simplicity.

**Comment by realslacker** [comment]
@adamdriscoll thanks!

**Comment by realslacker** [comment]
@adamdriscoll I'm not sure what is going on, but the keys still seem to be case sensitive on that hashtable...

## Test Dashboard
```powershell
New-UDApp -Title 'PowerShell Universal' -Pages @(
    $Parameters = @{
        Url       = "/home"
        Name      = "Home"
        Content   = {
            New-UDElement -Tag pre -Content { @'
$Query Type: {0}
$Query['Test']: {1}
$Query['test']: {2}
$Query.Test: {3}
$Query.test: {4}
'@ -f $Query.GetType().FullName, $Query['Test'], $Query['test'], $Query.Test, $Query.test }
        }
    }
    New-UDPage @Parameters
)
```

## Query String
/test/home?test=1

## Result
```
$Query Type: System.Collections.Hashtable
$Query['Test']: 
$Query['test']: 1
$Query.Test: 1
$Query.test: 1
```

It looks to me like the key is still case sensitive, however using it like a property works since properties are not case sensitive ever.

**Comment by realslacker** [comment]
@adamdriscoll this seems to be related to [this change](https://github.com/PowerShell/PowerShell/issues/19928) in PowerShell v7.3
