### ISSUE TITLE
Get-PSUVariable - Returned attributes are incorrect or inaccurate

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#2778]
### Version

4.1.6

### Severity

High

### Steps to Reproduce

`Get-PSUVariable -Integrated`

Output could be for example this:
```
Id                  : 13
Name                : MySecret
Value               : 
UserName            : 
Password            : 
Secret              : False
Vault               : Database
Type                : System.String
CreatedTime         : 01.01.0001 00:00:00
UpdatedTime         : 01.01.0001 00:00:00
Description         : my description
MissingSecret       : False
DisableRunAsSupport : False
DeleteSecret        : False
ReadOnly            : False
Database            : False
Role                : 
Force               : False
DisplayValue        : 
```

Some of the attributes that are always wrong:
"Secret" is always "False"
"CreatedTime" always "01.01.0001 00:00:00"
"UpdatedTime" always "01.01.0001 00:00:00"
"MissingSecret is always "False"
"Database" is always "False" even if the Vault correctly says "Database"

Please fix this behavior because it makes it really difficult to programmatically work / add / change PSU Variables. :-(

Thanks a lot!

### Expected behavior

```console
Get-PSUVariable should return reliable data
```

### Actual behavior

```console
Get-PSUVariable is messed-up
```

**Comment by adamdriscoll** [comment]
We have removed CreatedTime and UpdatedTime as they weren't being used. 

Secret property is fixed. This was only set the when the secret was created. After restarting the service, it would be false. 

MissingSecret is true when the secret is defined but it not actually in the vault. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/7fccb9ae-a85d-4fd8-a97f-5eef85efa551)

Database is true when the non-secret variable value is stored in the database, not that the vault is the Database. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/dced3ec3-7640-4fec-b25d-e4b66e26409c)
