### ISSUE TITLE
Allow New-UDTable to support an initial state for form fields

### ISSUE THREAD

**Issue by realslacker** [ironmansoftware/powershell-universal#2779]
### Summary of the new feature / enhancement

I think it would be useful for New-UDTable to have a parameter that sets an initial state to set options that would normally come from $Body. Basically set the value of any search box, filters, the page number if paginated, etc...

### Proposed technical implementation details (optional)

Add a parameter to New-UDTable called -InitialState that would take either a hashtable that matches the format of $Body, or a json $Body as a string, which ever makes more sense.

Example:
```powershell
$InitialState = @{
    filters = @(
        @{ id = "status"; value="failed" }
        @{ id = "name"; value = "test" }
    )
    search = "example search"
    page = 4
    orderBy = @{ field = "name" }
    orderDirection = "asc"
}

New-UDTable -InitialState $InitialState
```

Since this is specified in the same place we can specify the columns and page size I would suggest ignoring redundant parameters (ex: pageSize and properties).

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/new-udtable-initial-state/9872/3
