### ISSUE TITLE
Constant CPU Usage from PowerShellProTools.Host in VS Code

### ISSUE THREAD

**Issue by brisexton** [ironmansoftware/powershell-universal#278]
**To Reproduce**
1. Have the PowerShell Pro Tools Extension installed in VS Code
2. Start VS Code
3. Click on the PowerShell Pro Tools icon in the vertical side bar
4. Wait until values propagate or don't. From this point on, the process has CPU Utilization until VS Code is exited.

**Expected behavior**
I DIDN'T have the expectation that this process would have between 10% and 16.1% CPU utilization for as long as I'm running VS Code.

**Screenshots**
![image](https://user-images.githubusercontent.com/37346284/124206913-52049d00-dab2-11eb-9786-71961b4392e2.png)

**Version**

Tool (Visual Studio, VS Code, PSScriptPad, PS Module):  VS Code Extension
Version Number: Extension 5.28.7 / EXE 1.0.0.0
Operating System: Windows 10 21H1 Build 19043.1052

**Logs** 

$Env:AppData\PowerShellProTools\ doesn't exist on my machine.

$Env:AppData\PowerShell Pro Tools\ only has the license and activation files.

**Comment by adamdriscoll** [comment]
@brisexton - Can you do me a favor and take a couple of memory dumps for me? I don't see this locally so I'd like to see what's happening in your environment. Just right click on the process in task manager under details and select Create Memory Dump. If you open a support ticket, we can find a way to send those over. Just email support@ironmansoftware.com

**Comment by brisexton** [comment]
Will do @adamdriscoll . I send them over to the support address.

**Comment by adamdriscoll** [comment]
This has been resolved.
