### ISSUE TITLE
PowerShell ProTools Profile has no output

### ISSUE THREAD

**Issue by mighty-services** [ironmansoftware/powershell-universal#2783]
**Describe the bug**
I am using PowerShell ProTools in my VScode on my Windows 11 machine and Tried to run the 'Profile Script performance' Option. It is running, as I can see on the little Notification at the bottom right corner, but there´s no output in the script.

I followed the instructions in the official Youtube-Video:
https://www.youtube.com/watch?v=9DkxJ78C5ks

**Version**
Tool (Visual Studio, VS Code, PSScriptPad, PS Module): Powershell Pro Tools v2023.9.0
Operating System: Windows 11 22h2 Build 22621.2428 with VSCode v1.83.1

**Logs** 
I cant find Log-Inormation in the Appdata\Roaming\PowershelProTools Folder. There´s only the license File.

**Comment by mighty-services** [comment]
Thanks Adam, for looking into it.
Can you quickly share, how to obtain this new version? When I click on "Visual Studio Code" Download on [your Website](https://ironmansoftware.com/powershell-pro-tools). It redirects me to the [VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=ironmansoftware.powershellprotools), where there is still the old version 2023.9.0 available

**Comment by adamdriscoll** [comment]
This will be released next Tuesday.
