### ISSUE TITLE
Add filter tags to /endpoints for back button and quick filtering

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2784]
### Summary of the new feature / enhancement

add tag filter to query parameters so that i can hit the back button and go back to my set of api's that i am working with instead of starting over at the full list

Before:
https://servername.com/psuLAND/admin/apis/endpoints

After: 
https://servername.com/psuLAND/admin/apis/endpoints?tags=Accounts,Whatever

**Comment by adamdriscoll** [comment]
#2975

**Comment by Omzig** [comment]
Maybe add the search and some other filters to the back button, or some kind of 'remember state, but i like the url parms so i can share my view
