### ISSUE TITLE
Schedules not saving (sometimes) and not showing up in admin console

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#2797]
### Version

4.1.6

### Severity

Low?

### Steps to Reproduce

Adding schedules (simple), they don't show up in the admin screen if script parameters 'conflict' with New-PSUSchedule parameters.

They don't always show up in the schedules.ps1 either.

Might be some failed validation, but there's no indication in the browser that there's an issue, just nothing shows up.

Create a script with a parameter called "Name" and you'll be able to reproduce this.

### Expected behavior

```console
Creating a schedule saves it to file, shows up in browser.
```

### Actual behavior

```console
Nothing in browser, some results in file.
```

### Additional Environment data

4.1.7

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/5541154/25f5ae6c-4807-461c-975d-bf4a90e26315)

**Comment by MikeShepard** [comment]
Got it to write to the schedules.ps1 again, but it overwrote the entry that was there.

**Comment by adamdriscoll** [comment]
This is a known issue at the moment. I thought we had another issue open for it but I'm not seeing it. PowerShell does not like having duplicate parameters like this. We would need to do something like: 

```powershell
New-PSUSchedule -Script 'MyScript' -Name 'MySchedule' -Parameters @{
    Name = "MyScheduleParameterName" 
}
```
