### ISSUE TITLE
Promote JobRunId to feature 

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2799]
### Summary of the new feature / enhancement

Add a new setting for JobRunId and promote to feature.

**Comment by schubfre** [comment]
Wasn't this planned for v4 ?
> New defaults for some features (e.g. random jobs ID)
[https://blog.ironmansoftware.com/powershell-universal-v4-roadmap/](https://blog.ironmansoftware.com/powershell-universal-v4-roadmap/)

So, when we upgrade to v4 we still need the experimental flag right?

**Comment by adamdriscoll** [comment]
@schubfre - This should have been completed in v4 but for some reason, it was not. You will continue to have to do this in v4 for the time being.
