### ISSUE TITLE
New-UDTextBox Doesn't Allow a Single Character "Value" to be Deleted

### ISSUE THREAD

**Issue by sean-sauve** [ironmansoftware/powershell-universal#2800]
### Version

4.1.4

### Severity

High

### Steps to Reproduce

```
New-UDTextbox -Value 'A'
```

### Expected behavior

```console
Users can press backspace to remove the A
```

### Actual behavior

```console
The A cannot be removed until something else is also entered.
```

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/new-udtextbox-doesnt-allow-a-single-character-value-to-be-deleted/9912/1

**Comment by adamdriscoll** [comment]
Weird...I can totally reproduce this. 

We'll get this fixed.
