### ISSUE TITLE
Display Link in Table

### ISSUE THREAD

**Issue by urskog84** [ironmansoftware/powershell-universal#2804]
### Summary of the new feature / enhancement

Hi Adam!

Thanks for bringing a grate product to the powershell comunity.

I try to build some pages with PowerShell Universal. Displaying some data from our windows dhcp server.
i have get some insperation from your video from the Powershell DevOps summit 2022
[```](https://www.youtube.com/watch?v=NFOLe-MEoPE)

in this viedo you are dsiplaying a table after filing in a form... and using but I want go direct  to a page and displaying a table after loading data from en API endpoint
```powershell
# Endpoint
New-PSUEndpoint -Url "/dhcp-scoops" -Method @('GET') -Endpoint {
$CimSession = New-CimSession -ComputerName "dhcp1.int.myorg.biz" -Credential $Secret:dhcpadmin
$DhcpScope = Get-DhcpServerv4Scope -CimSession $CimSession
$DhcpScope | ForEach-Object {
    @{
        Name = $_.Name
        State = $_.State
        ScopeId = $_.ScopeId.IPAddressToString
        Description = $_.Description
        Link = @{ 
            type = 'link'
            url = "/scope/$($_.ScopeId.IPAddressToString)"
            text = "id"
                    }
    }
}
}
```
after fetching the data and displaying the table i cant get the Link to appear in the table

![image](https://github.com/ironmansoftware/issues/assets/18033678/9a7124ae-9643-49fc-9ec0-8769e82603ee)

i only get the text [object Object] instaed of the hyper link a expected.
i have allsow tray with a `New-UDLink` object

**Comment by TurnItOff-OnAgain** [comment]
Not sure how you have your table set up, but you need to render the column you want 

https://docs.powershelluniversal.com/userinterfaces/components/data-display/table#table-with-custom-column-rendering

You can so something like this

```
$columns - @(
     New-UDTableColumn -property link -Title "Link" -Render {
        new-udlink -text $evendata.link.text -URL $evendata.link.url
     }
    ## Fill in the rest of your columns here
)
```
$eventdata will be the object that is passed into that row for that column, so you may need to play around with it to get the object displayed how you want it based on how your object is formatted.

**Comment by adamdriscoll** [comment]
#2975
