### ISSUE TITLE
Re-Open: New-UDTextbox -Mask doesn't work with RegEx patterns

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#2808]
### Version

4.1.6

### Severity

Quality-of-life

### Steps to Reproduce

See original post and related forums thread:
https://github.com/ironmansoftware/issues/issues/1578

Not being able to validate input text using RegEx is really a pain sometimes...

Here is a regex example for email address validation:

`-mask '/^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$/'`

### Expected behavior

```console
RegEx should work
```

### Actual behavior

```console
RegEx doesn't work.
```

**Comment by adamdriscoll** [comment]
We will be removing the -Mask parameter in favor of -OnValidate. Masking has never really worked correctly and the -OnValidate will work a lot better. 

-OnValidate {
  $Validate = $EventData -match "<regex>"
  New-UDValidationResult -ValidationError '...'
}

**Comment by donlent** [comment]
Hi @adamdriscoll 

Thanks for your feedback on this.

OK I understand that you're not going to "fix" or maybe better expressed "enhance" the functionality of -mask.
But please don't remove it completely! We're actively using it with the simpler pattern mask which works well:
![image](https://github.com/ironmansoftware/issues/assets/11975745/6881524f-b327-4e5d-8752-1e26e5d69fa4)

The thing I like about -mask is that it automatically limits and formats the textbox according to the need. in our case "000-000".
So using the OnValidate parameter would not honor this anymore but just do the validation check.

Really hope you'll leave it.

Thanks in advance for your much appreciated efforts!!
