### ISSUE TITLE
demo.powershelluniversal.com - failed to get runspace

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#2809]
### Version

4.1.7

### Severity

Low

### Steps to Reproduce

demo.powershelluniversal.com is having issues displaying a lot of the things in there.
![image](https://github.com/ironmansoftware/issues/assets/53445047/082eeba3-d2d8-4beb-a372-e69182c7a155)

### Expected behavior

```console
That it would work and show the awesome examples.
```

### Actual behavior

```console
Its not working
```

**Comment by adamdriscoll** [comment]
This is fixed for the meantime, but I don't know what caused it. If it happens again, please reopen.
