### ISSUE TITLE
Desktop Takes a long time to load.

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2829]
### Version

4.1.8

### Severity

Low

### Steps to Reproduce

I am experiencing a problem with the desktop version. When it auto loads it takes a very long time to load.

### Expected behavior

```console
load
```

### Actual behavior

```console
long time to load 3min+, i need to sit down and put a stop watch to it
```

### Additional Environment data

	Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz

	Base speed:	3.20 GHz
	Sockets:	1
	Cores:	6
	Logical processors:	12
	Virtualization:	Enabled
	L1 cache:	384 KB
	L2 cache:	1.5 MB
	L3 cache:	12.0 MB

	Utilization	5%
	Speed	1.18 GHz
	Up time	1:00:33:36
	Processes	247
	Threads	4017
	Handles	114890

Windows 10 Pro

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/1987296/ce7b91b4-9784-4324-866c-95ab80141849)

**Comment by Omzig** [comment]
# Logs
[systemLog20231106_002.txt](https://github.com/ironmansoftware/issues/files/13274608/systemLog20231106_002.txt)
[systemLog20231106_003.txt](https://github.com/ironmansoftware/issues/files/13274609/systemLog20231106_003.txt)
[log20231106.txt](https://github.com/ironmansoftware/issues/files/13274610/log20231106.txt)
[systemLog20231106_001.txt](https://github.com/ironmansoftware/issues/files/13274611/systemLog20231106_001.txt)
[systemLog20231106.txt](https://github.com/ironmansoftware/issues/files/13274612/systemLog20231106.txt)

**Comment by adamdriscoll** [comment]
Can you grab a desktop log from %AppData%\PowerShellUniversal?
