### ISSUE TITLE
Swagger Docs - Schemas Defined in Other Documentations Are Shown

### ISSUE THREAD

**Issue by sean-sauve** [ironmansoftware/powershell-universal#2830]
### Version

4.1.8

### Severity

Visual

### Steps to Reproduce

When defining multiple documentation groups with New-PSUEndpointDocumentation, all schemas from all documentations are shown on the swagger page for each individual documentation group.

Steps to reproduce:

1. Define 2 roles; Administrator and ContosoVendorAPI.
2. Define 2 documentations (user and group) with New-PSUEndpointDocumentation and define a different class using “[Documentation()]; class …” for each. Restrict the “user” documentation so only “Administrator” can see and use it.
3. Define 2 endpoints, user and group. Use the .OUTPUTS to specify the documentation classes for each. Restrict the “user” endpoint so only the first role can see and use it. Specify the tag and documentation for each.
4. Restart the PowerShell Unversal service. This may not be strictly required, but I tend to do this when modifying files those are used by Swagger to ensure they are updated.
5. Under a user with only the ContosoVendorAPI role visit the Swagger page for the “group” documentation; https://myserver.com/swagger/index.html?urls.primaryName=Group
6. Check under “Schemas” on this page. The documentation class (schema) for the “user” endpoint will be shown.

I’ve posted the source code for reproducing this here: [sean-sauve/PUDSwaggerDemo (github.com)](https://github.com/sean-sauve/PUDSwaggerDemo)

### Expected behavior

```console
We should be able to show only the schemas defined in the documentation that we are currently showing.  This becomes more critical as the number of APIs we have grows, both for useability and security.
```

### Actual behavior

```console
All schemas are shown on all Swagger doc pages.
```

### Additional Environment data

Windows.
The github link I posted includes all of the details that I thought might be relevant, such as the PowerShell environments I use.

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/64482571/db3530a6-b323-425d-8740-1149a7789e3c)

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/swagger-docs-schema-not-defined-in-other-documentations-are-shown/9953/2

**Comment by ScheeleRxNL** [comment]
I experience the same issue now on version 5.6.11.

Maybe because of this issue? -> https://github.com/ironmansoftware/powershell-universal/issues/5316
