### ISSUE TITLE
4.2 git sync issues

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#2831]
### Version

4.1.8

### Severity

Low

### Steps to Reproduce

Just upgraded and I do get the following error message

`cannot push because a reference that you are trying to update on the remote contains commits that are not present locally.`

Don't have it when reverting back to 4.1.8

### Expected behavior

```console
Don't get any error message for git
```

### Actual behavior

```console
get error message
```

**Comment by adamdriscoll** [comment]
Good catch. Thanks!

**Comment by rwidmark** [comment]
> Good catch. Thanks!

Is it solved in nightly? Was thinking to try it again tomorrow

**Comment by adamdriscoll** [comment]
This will be in tonight's build.

**Comment by rwidmark** [comment]
> This will be in tonight's build.

Ok, when is that released? Living in Sweden so it's a little bit after you I think.
