### ISSUE TITLE
Z-Index of UDAutocomplete is incorrect. 

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2832]
### Version

4.1.8

### Severity

Low

### Steps to Reproduce

https://forums.ironmansoftware.com/t/autocomplete-z-index-not-the-same-as-udselect/9854

### Expected behavior

```console
Modal should not hide autocomplete.
```

### Actual behavior

```console
Modal hides auto complete.
```

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/autocomplete-z-index-not-the-same-as-udselect/9854/6

**Comment by adamdriscoll** [comment]
This can be accomplished with the new -PaperStyle and -Style props. 

```
        Show-UDModal -Content {
            New-UDSelect -Option {
            1..1000 | % { New-UDSelectOption -Name $_ -Value $_ }
            }
        }  -ContentStyle @{ overflowY = "visible" } -PaperStyle @{ overflowY = "visible" }
```

**Comment by dbytes** [comment]
> This can be accomplished with the new -PaperStyle and -Style props.
> 
> ```
>         Show-UDModal -Content {
>             New-UDSelect -Option {
>             1..1000 | % { New-UDSelectOption -Name $_ -Value $_ }
>             }
>         }  -ContentStyle @{ overflowY = "visible" } -PaperStyle @{ overflowY = "visible" }
> ```

I don't see PaperStyle as a parameter for Show-UDModal.

**Comment by adamdriscoll** [comment]
This will be released in the next version. 4.2.13


*Adam Driscoll*
Owner of Ironman Software  <https://ironmansoftware.com/>
Microsoft MVP
<https://mvp.microsoft.com/en-us/PublicProfile/4040089?fullName=Adam%20%20Driscoll>
| Twitter <https://twitter.com/adamdriscoll> | LinkedIn
<https://www.linkedin.com/in/adamrdriscoll/>

**Comment by dbytes** [comment]
I tried this with a nightly build and it does not work with New-UDAutoComplete but does with New-UDSelect. Maybe I need to be patient.  ;)
