### ISSUE TITLE
4.2 git sync issue

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#2841]
### Version

Other Please Specify

### Severity

Low

### Steps to Reproduce

Every time I try to sync with git I get error message with 4.2.0 (2023-11-12 nightly) if I revert back to 4.1.8 everything works perfect.

```
Git Synchronization 
too many redirects or authentication replays
```

### Expected behavior

```console
No error message
```

### Actual behavior

```console
Get error message
```

### Visuals

<img width="770" alt="Screenshot 2023-11-12 at 12 21 57" src="https://github.com/ironmansoftware/issues/assets/76907327/8e382a96-577b-4b6f-9870-fe3cbd5eacf5">

**Comment by rwidmark** [comment]
@adamdriscoll this is something that needs to be fixed before release.

**Comment by adamdriscoll** [comment]
I'll look at it today. My git sync was previously working on 4.2 so hopefully I can reproduce it. Will let you know if I have questions.

**Comment by rwidmark** [comment]
@adamdriscoll was it released in this nightly? or will the fix be released tonight?
