### ISSUE TITLE
Customize AspNetCore Session Cookie ID

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2846]
### Summary of the new feature / enhancement

Right now, the cookie ID is a combination of the BaseUrl property in appsettings and the default name of the cookie. The problem is that the service could be run on the same host but on different ports. This would cause the cookie to be shared across the instances.

**Comment by Omzig** [comment]
has this been documented yet, @adamdriscoll

**Comment by Omzig** [comment]
@adamdriscoll or @DataTraveler1, 

does RequestVerificationToken need to be prefixed?

![image](https://github.com/ironmansoftware/issues/assets/1987296/156d5c56-0016-4ae1-a7ba-884b8f7bf1fd)

**Comment by Omzig** [comment]
![image](https://github.com/ironmansoftware/issues/assets/1987296/38319ae5-1022-4279-8213-f3fdb7437c9c)

**Comment by Omzig** [comment]
So, in my testing, i am unable to change the cookie prefix:

```json
"Kestrel": {
		"Endpoints": {
			"HTTP": {
				"Url": "http://*:5000"
			}
		},
		"RedirectToHttps": "false",
		"UseHttpSys": "false",
		"BasePath": "/Beta",
		"CookiePrefix": "Beta2",
		"Hsts": {
			"MaxAgeDays": 365
		}
	},
```

![image](https://github.com/ironmansoftware/issues/assets/1987296/bf5ba86a-a465-40e7-bd49-e47f31127a20)

**Comment by adamdriscoll** [comment]
It wasn't setting all the cookies properly. That said, I was able to change it just fine. I had to make sure to close the dashboard before it would show up in the dev tools. 

<img width="253" alt="image" src="https://github.com/ironmansoftware/issues/assets/1256531/e6050379-cca1-4fda-ad2a-b709484bd6c0">

**Comment by Omzig** [comment]
@adamdriscoll, does the requestverificationtoken need to be prefixed?
