### ISSUE TITLE
Conflicting messages in Health checks

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#2850]
### Version

4.2.0

### Severity

Low

### Steps to Reproduce

Clean bill of health in terms of conflicting modules, followed by detection of a conflicting module 3 seconds later.
![image](https://github.com/ironmansoftware/issues/assets/5541154/3fe415a4-86b7-4d35-8758-78b13bb3f6c1)

### Expected behavior

```console
One or the other.  If it's clean, it should be clean.
```

### Actual behavior

```console
Said it was good, then said it wasn't.

Didn't install a module in the intervening 3 seconds.
```

**Comment by Omzig** [comment]
So, the MSI installs a 
![image](https://github.com/ironmansoftware/issues/assets/1987296/f0872853-07bd-4894-b2b7-19b75062c826)

@adamdriscoll, remember when we removed all the references for IIS when it used to add things to the module path? Maybe the MSI missed that change.

The result is that we get a health check now in IIS that is kranky with that module being there.


Found it:
![image](https://github.com/ironmansoftware/issues/assets/1987296/b59d021f-6b92-401c-89e5-5a75f1a8c3a0)
