### ISSUE TITLE
PowerShell 7.4 support

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#2860]
### Summary of the new feature / enhancement

I haven't tested yet if it works but still want official support for PowerShell 7.4 :) it's GA now.

**Comment by axisfx24** [comment]
Nothing official, but I upgraded to PS 7.4 when I upgraded my PSU instance to 4.2.1. Everything is good so far.

**Comment by adamdriscoll** [comment]
Same here. We will get official support mentioned after our next release and we can run through verification.
