### ISSUE TITLE
OpenID Group Claims to Role Mapping

### ISSUE THREAD

**Issue by tonesto7** [ironmansoftware/powershell-universal#2862]
### Version

4.2.1

### Severity

High

### Steps to Reproduce

I recently enabled OpenID + Azure AD authentication so I could assign roles using AAD groups.  
I can see the groups listed under the Roles > View Claim Information.
When a user logs in the Identity is created but none of the Roles get assigned (or the UI doesn't update to show the assigned roles)

### Expected behavior

```console
Group should be assigned based on the claims groups id
```

### Actual behavior

```console
I've been trying to find ways to debug this... 
I can see all of the claims at this endpoint /api/v1/identity/claims and the required groups id is there.
```

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/1835933/4608079f-2e36-4e63-8cca-68a37ae5841f)

**Comment by tonesto7** [comment]
I also notice these errors while trying to view the logs section for the Roles policy editor
![image](https://github.com/ironmansoftware/issues/assets/1835933/b020db8f-ead8-4d07-98b7-f431ff24e393)

**Comment by kp-bit** [comment]
Two things to bear in mind:
- Claim Value is the Azure group object id
- Use: "groupMembershipClaims": "ApplicationGroup" and assign the groups you want to use to the Enterprise App

**Comment by tonesto7** [comment]
@kp-bit I am using the group object id... I also see the ID as an available option in the claim value input.
I currently have 3 AAD groups:
* PSU-Admins
* PSU-Techs
* PSU-Auditors

I just want to use those groups to define those 3 different roles in PSU

**Comment by kp-bit** [comment]
For users with many groups this doesn't always work as intended (in my experience). Adding the groups to the enterprise app and setting "groupMembershipClaims": "ApplicationGroup" in the manifest of the App Registration fixes that.

**Comment by tonesto7** [comment]
@kp-bit I may be slightly confused. So, by restricting the AAD enterprise app to those 3 groups I mentioned above and setting the groupMembershipClaims to the value you suggested.  
Can I still see the user groups in their login claims?  Will it just reduce the number of groups that are returned?

**Comment by kp-bit** [comment]
Yes, but you will only see the users' membership of any of those 3 groups

**Comment by tobrienultima** [comment]
This is affecting our dev environment since trying 4.2.1 as well. Previously using the object ID of the Azure AD group worked (without having to specify anything in the app registration manifest) but it doesn't seem to be recognising Azure AD group memberships in 4.2.1. I rolled back to 4.0.12 without making any changes and it works again.

@kp-bit I believe you need a minimum of Azure AD P1 plan to be able to specify groups in the enterprise app so this might be limiting to some people.

**Comment by kp-bit** [comment]
> @kp-bit I believe you need a minimum of Azure AD P1 plan to be able to specify groups in the enterprise app so this might be limiting to some people.

You might be right, we're on P2 - works fine in 4.2.1 though...

**Comment by tonesto7** [comment]
I made the recommended changes, and it's still not working, but the groups returned via the claims are so much cleaner.

Here is the group shown in the View Claims Info page:
![image](https://github.com/ironmansoftware/issues/assets/1835933/107b3c07-5d54-443c-9199-d25db4b2b075)

Here is the specific role I need to be assigned:
![image](https://github.com/ironmansoftware/issues/assets/1835933/1e79f2b5-3056-4aa1-817e-b7b70d0d90bd)

Here is my user identity:
![image](https://github.com/ironmansoftware/issues/assets/1835933/ff5223d0-29b5-4157-a6d1-ed7e06ee25ea)
As you can see there is no "Administrators" role listed, but I seem to have admin privileges in PSU using my AAD account.

Maybe this is a bug in the UI related to custom roles?

How can I debug my assigned roles?

**Comment by kp-bit** [comment]
Roles will be empty when you're using claims. Under Security\Identities you will see your account with the role "Policy Defined". If you're admin, it looks like your claims are doing what they should. You can use $Roles -join ', ' on a page to show what roles you've been assigned.

**Comment by adamdriscoll** [comment]
We've added a My Identity page in v5 that includes all of the current user's roles and permissions. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/b613b79d-ac2d-49bb-8b9e-aeb14fb83fbc)
