### ISSUE TITLE
Auto Reload broken after update

### ISSUE THREAD

**Issue by kp-bit** [ironmansoftware/powershell-universal#2863]
### Version

4.2.1

### Severity

Critical

### Steps to Reproduce

After upgrading to v4.2.1 this morning, PSU no longer auto reloads when editing/creating files. Workaround is to restart the dashboard/app.

Disable Auto Reload is set to No.

### Expected behavior

```console
PSU auto reloads dashboard after edits
```

### Actual behavior

```console
Nothing happens
```

**Comment by eizedev** [comment]
Same problem for us after updating to 4.2.0 and 4.2.1 (on both versions)

**Comment by adamdriscoll** [comment]
I can't reproduce this. Can you provide some logs and\or some info on number of apps\dashboards, if you are using pages, etc.

**Comment by kp-bit** [comment]
So we have a folder structure under \dashboards

\dashboards\Main\ which contains main.ps1 with the dashboard definition and loading of pages. When editing this file, reload is triggered.

Pages are residing under Main - e.g.: \dashboards\Main\Accounts\page.ps1

When .ps1 files are edited in the subfolders, reload is not triggered (it was earlier)

We have about 70 .ps1 page files in total, and growing.

**Comment by kp-bit** [comment]
Works perfectly now, thank you!
