### ISSUE TITLE
Applying license to Docker image produces "sequence contains no elements" error

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#2864]
### Version

4.1.9

### Severity

Low

### Steps to Reproduce

1. Follow the directions in the documentation to setup PowerShell Universal on docker on a clean Linux machine*
2. Logon to the instance and ensure PSU is displaying/functioning as expected in an unlicensed state.
3. Install (Upload) your current license file using the UI
4. Observe error "sequence contains no elements" (shown below)

![image](https://github.com/ironmansoftware/issues/assets/537287/222e8eee-a9c8-4379-a11d-00f7822504f1)

5. The license appears to be installed immediately afterwards

### Expected behavior

```console
There should not be any error displays when installing a valid license
```

### Actual behavior

```console
There is an error displayed when installing a valid license
```

### Additional Environment data

```
└─$ sudo docker version
Client:
 Version:           20.10.25+dfsg1
 API version:       1.41
 Go version:        go1.21.3
 Git commit:        b82b9f3
 Built:             Wed Oct 18 17:36:27 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

**Comment by adamdriscoll** [comment]
Cannot reproduce on latest.
