### ISSUE TITLE
When using configuration file splatting schedules.ps1 is saved in an invalid format

### ISSUE THREAD

**Issue by realslacker** [ironmansoftware/powershell-universal#2866]
### Version

4.2.1

### Severity

High

### Steps to Reproduce

Since at least 4.2.1 when the schedules.ps1 is saved using configuration file splatting the output of the file is invalid.

The Name parameter gets put on the same line as the Parameters hashtable, causing the file to be unreadable. I have also noticed that only the schedule that I edit in the GUI is saved into schedules.ps1. For example, if I have 10 scheduled scripts, and edit one via the GUI only the one I was editing will appear in the schedules.ps1, all of the other schedules will be gone and the schedules.ps1 will be unreadable due to the first bug.

### Expected behavior

```console
$Parameters = @{
    Cron       = "*/5 * * * *"
    Script     = "Import-ADObjects.ps1"
    TimeZone   = "America/Chicago"
    Parameters = @{
        Forest     = '*'
        Domain     = '*'
        MaxRetries = '5'
        ChunkSize  = '500000'
    }
    Name = "Import AD objects in to the database"
    Paused = $true
    Timeout = 30
    RandomDelay = $true
}
New-PSUSchedule @Parameters
```

### Actual behavior

```console
$Parameters = @{
    Cron       = "*/5 * * * *"
    Script     = "Import-ADObjects.ps1"
    TimeZone   = "America/Chicago"
    Parameters = @{
        Forest     = '*'
        Domain     = '*'
        MaxRetries = '5'
        ChunkSize  = '500000'
    }	Name = "Import AD objects in to the database"
    Paused = $true
    Timeout = 30
    RandomDelay = $true
}
New-PSUSchedule @Parameters
```

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/4-2-3-schedules-are-not-executed-formatting-issue-in-schedules-ps-when-using-splatting/10062/2
