### ISSUE TITLE
Dashboard Maintanance Mode

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#287]
> I would like to set my Dashboard to “Maintanance Mode” so that “Users” see a Custom Page “Dashboard is in Maintanance” and “admins” can reach The Page and Admin-Dashboard

PSU 2.1.1

**Comment by rwidmark** [comment]
Has this been added in 2.1.1? I can't find it.

**Comment by adamdriscoll** [comment]
This wasn't released in 2.1.1. That's just the version it was first reported.

**Comment by rwidmark** [comment]
I see my bad, I did misunderstand
