### ISSUE TITLE
Schedules.ps1 Splatting broken since 4.2.1

### ISSUE THREAD

**Issue by HansenRene** [ironmansoftware/powershell-universal#2873]
### Version

4.2.3

### Severity

Low

### Steps to Reproduce

When creating a schedule on a script with parameters, formatting will be broken in the schedule Splat, and no schedule will execute.
https://forums.ironmansoftware.com/t/4-2-3-schedules-are-not-executed-formatting-issue-in-schedules-ps-when-using-splatting/10062

### Expected behavior

```console
to work
```

### Actual behavior

```console
breaks
```

**Comment by schubfre** [comment]
This should be fixed in 4.2.4
See #2866
