### ISSUE TITLE
Git Commit not working

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2877]
### Version

4.2.4

### Severity

Low

### Steps to Reproduce

I am unable to commit

### Expected behavior

```console
Commit -> Changes Accepted
```

### Actual behavior

```console
Commit -> No Changes Selected
```

### Additional Environment data

IIS: Nested

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/1987296/bd046734-0e3c-4d5f-99a5-1a367565d04e)

**Comment by andrewwood-wbg** [comment]
This seems to be a bug with the select all checkbox for the column.  If you select each change individually it works.

**Comment by Omzig** [comment]
> This seems to be a bug with the select all checkbox for the column. If you select each change individually it works.

hehe, i currently have 2 pages of commits.

Also, if i just commit 1 file, it doesn't push.

**Comment by OwainEsau** [comment]
> > This seems to be a bug with the select all checkbox for the column. If you select each change individually it works.
> 
> hehe, i currently have 2 pages of commits.
> 
> Also, if i just commit 1 file, it doesn't push.

Not ideal but you can run this in chrome console and it should tick each one:

````
// Get all the checkboxes within the specific <td> elements
const checkboxes = document.querySelectorAll('td.ant-table-cell input[type="checkbox"]');

// Loop through each checkbox and check it, excluding the one with the "Select all" aria-label
checkboxes.forEach((checkbox) => {
  if (checkbox.getAttribute('aria-label') !== 'Select all') {
    checkbox.click();
  }
});
```

**Comment by Omzig** [comment]
> > > This seems to be a bug with the select all checkbox for the column. If you select each change individually it works.
> > 
> > 
> > hehe, i currently have 2 pages of commits.
> > Also, if i just commit 1 file, it doesn't push.
> 
> Not ideal but you can run this in chrome console and it should tick each one:
> 
> ```
> // Get all the checkboxes within the specific <td> elements
> const checkboxes = document.querySelectorAll('td.ant-table-cell input[type="checkbox"]');
> 
> // Loop through each checkbox and check it, excluding the one with the "Select all" aria-label
> checkboxes.forEach((checkbox) => {
>   if (checkbox.getAttribute('aria-label') !== 'Select all') {
>     checkbox.click();
>   }
> });
> ```
> ```

@adamdriscoll, hehe, we got some people that know how to Hack the Gibson!
