### ISSUE TITLE
Schedules does not execute.

### ISSUE THREAD

**Issue by HansenRene** [ironmansoftware/powershell-universal#2879]
### Version

4.2.4

### Severity

Low

### Steps to Reproduce

(Windows Auth)
Schedules does not execute.

Schedules.ps1 are no longer malformed, but jobs does still not execute

I wonder if this is relevant:
`2023-11-27 08:51:40.873 +01:00 [INF] CORS policy execution failed.
2023-11-27 08:51:40.873 +01:00 [INF] Request origin https://[server].org does not have permission to access the resource.
2023-11-27 08:51:40.876 +01:00 [INF] Request finished HTTP/1.1 POST https://[server].org/hangfire/stats application/x-www-form-urlencoded;+charset=UTF-8 167 - 200 - application/json 5.2062ms
2023-11-27 08:51:44.792 +01:00 [INF] Request starting HTTP/1.1 POST https://[server].org/hangfire/stats application/x-www-form-urlencoded;+charset=UTF-8 167

Hangfire shows that the jobs runs, but nothing actually happens in PSU, no jobs are generated.

![image](https://github.com/ironmansoftware/issues/assets/20628942/b51eedbc-fea8-40f8-a445-9bd609d9c9fa)

### Expected behavior

```console
that it works
```

### Actual behavior

```console
it does not
```

**Comment by adamdriscoll** [comment]
Do you have the Scheduled option checked? This was added in 4.2 to be able to hide scheduled jobs. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/c4751b34-1dd2-4f25-8c29-099d2c5811d6)

**Comment by HansenRene** [comment]
oh balls

**Comment by HansenRene** [comment]
Wait no, almost

Yes, enabling that options now correctly show the scheduled jobs in the jobs list.

But opening a script and going to its "jobs" tab, also only shows manual jobs, with no (apparent) option to show scheduled jobs.
So I missed the changelog on the added "show scheduled" option, but missing job on the scripts page didn't exactly aid the troubleshooting :D 

Ideally, I visit Script.ps1 -> Jobs, to see all jobs of that script, not just the manual ones.

**Comment by adamdriscoll** [comment]
We've got the Scripts -> Jobs page fixed in 4.2.5.
