### ISSUE TITLE
Extended random delay in schedules

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#2886]
### Summary of the new feature / enhancement

The current Random delay feature is nice, but its predefined to 0-60 seconds.
I have a server that starts 25-30 scripts every 15 minutes, and with 4 CPU cores and the Random delay, it still manages to kill itself.
![image](https://github.com/ironmansoftware/issues/assets/53445047/9cdf1ea1-867b-4c63-a0e2-bd4a90deb344)

For this server its not important that the script starts at XX:00, XX:15, XX:30, XX:45 - its just important that it runs fairly often.

A extended random delay that we could specify ourself would be nice - then i can spread the jobs over a 5 minute delay or so.

**Comment by rwidmark** [comment]
Was thinking about this today also actually
