### ISSUE TITLE
UDMarkdown, can't change fontaine

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#2887]
### Version

4.2.4

### Severity

Low

### Steps to Reproduce

I can't change fontsize etc. in the UDMarkdown when I open developer tools in my browser it says:
User Agent Style Sheet is locked and I'm guessing it's because of that I have issues.
![image](https://github.com/ironmansoftware/issues/assets/76907327/e18405df-bd9b-4e38-8512-bf7d36bb6af9)

### Expected behavior

```console
Somehow change default font-size
```

### Actual behavior

```console
I can't override the default font-size.
If I do remember correctly according to developer view in the browser it's flagged as "agent locked" or similar.
```

**Comment by rwidmark** [comment]
@adamdriscoll  any work-a-round on this one?

**Comment by adamdriscoll** [comment]
Agent locked is usually the browser. Do you have any extensions installed that could cause this?

**Comment by rwidmark** [comment]
> Agent locked is usually the browser. Do you have any extensions installed that could cause this? 

Hmm not what I know of, I'll take look.

**Comment by rwidmark** [comment]
@adamdriscoll i have been trying but can't figure out how to change it. Do you have any suggestions?
