### ISSUE TITLE
Endpoint Doc Issues

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2890]
### Version

4.2.4

### Severity

Low

### Steps to Reproduce

- Arrays are not handled properly 
- Mandatory parameters are not marked as such

### Expected behavior

```console
Arrays and mandatory parameters handled properly.
```

### Actual behavior

```console
Not so.
```

**Comment by rwidmark** [comment]
@adamdriscoll regarding the array parameter, it's the same for int also.
