### ISSUE TITLE
New-UDDatePicker doesn't clear when using tab + delete

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2892]
### Version

4.2.4

### Severity

Low

### Steps to Reproduce

Create a date picker with a default value
Use tab to select the picker and delete the value with the delete key
submit a form and see the default value is still present

### Expected behavior

```console
Default value is not sent
```

### Actual behavior

```console
Default value is still sent.
```

**Comment by sgaglione** [comment]
@adamdriscoll i believe i'm experiencing this behavior in `5.5.3`. should i open a case?

in the meantime i've worked around it by using the following technique:

```powershell
$PowerOn = if ($EventData.PowerOn -eq 'Invalid Date' -or $EventData.PowerOn -eq $null) {$null} else {$EventData.PowerOn.ToString('HH:mm')}
```

the above work around works if half the time is "deleted" or each hour and then minute sections deleted but using the exact steps noted at the top of this issue description still persists the original value thus original behavior of this issue.  

---

here's a working example of this in `5.5.3`:

```powershell
New-UDForm -Content {
    if ($EventData.PowerOn) {New-UDTimePicker -Id 'PowerOn' -Label 'Power On Time' -DisableAmPm -Value $EventData.PowerOn} else {New-UDTimePicker -Id 'PowerOn' -Label 'Power On Time' -DisableAmPm}
} -OnSubmit {
     $PowerOn = if ($EventData.PowerOn -eq 'Invalid Date' -or $EventData.PowerOn -eq $null) {$null} else {$EventData.PowerOn.ToString('HH:mm')}
    Show-UDSnackbar -Message $PowerOn -Persist
}
```
