### ISSUE TITLE
Status filter overlapping with sort

### ISSUE THREAD

**Issue by TurnItOff-OnAgain** [ironmansoftware/powershell-universal#2893]
### Version

4.2.4

### Severity

Low

### Steps to Reproduce

The Status filter in jobs is overlapping with the sort button, makes it hard to click.

![image](https://github.com/ironmansoftware/issues/assets/26926284/7aba63f1-0452-49bc-b204-4e8d0fb905ea)

### Expected behavior

```console
Should be a gap between them
```

### Actual behavior

```console
no gap
```

**Comment by TurnItOff-OnAgain** [comment]
Also, would be nice to be able to select multiple status' rather than just one. Being able to select Warning and Error to view them both at the same time would be nice.

**Comment by adamdriscoll** [comment]
@TurnItOff-OnAgain - Can you let me know what browser and resolution you are using? Mine looks like this. 

<img width="132" alt="image" src="https://github.com/ironmansoftware/issues/assets/1256531/824165cd-9e50-4122-8d23-478f451f1053">

And I agree selecting multiple would be nice.

**Comment by TurnItOff-OnAgain** [comment]
Windows 11
I see it in Firefox, Edge and Chrome
Resolution is 1920x1080 on a 27" Dell monitor

Here is the full top bar, looks the same in each browser.

![image](https://github.com/ironmansoftware/issues/assets/26926284/432dd71e-055a-415a-a249-5f5ba12f5aa5)


What about the ability to resize the columns as well?

**Comment by adamdriscoll** [comment]
I'll look into resizing columns. I don't see a simple option to turn on for AntD but I've resolved this issue with some CSS.
