### ISSUE TITLE
admin site loses its mind and will not load, loads white page

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2900]
### Version

4.2.4

### Severity

Low

### Steps to Reproduce

when i am in the admin site, and i am in a page, then i hit back, it stops loading. 

## Workaround
Go back to /admin and click through till you find the section you were looking at in the first place

### Expected behavior

```console
200
```

### Actual behavior

```console
404
```

### Additional Environment data

IIS: Nested

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/1987296/4034df78-6a98-4cab-bb7f-8828e5ad2fee)

**Comment by adamdriscoll** [comment]
I believe this was resolved. Please reopen if not.
