### ISSUE TITLE
Improve job history functionality / restore some functionality from 3.x days

### ISSUE THREAD

**Issue by realslacker** [ironmansoftware/powershell-universal#2903]
### Summary of the new feature / enhancement

In PSU v4 the job history tab for an individual script only shows the history for manually invoked jobs. Previously the tab would show all history for that script. This provided a convenient place to see at a glance all of the job history for a script. Right now you have to page through the main Job history page until you find your script, and you cannot see at a glance if it ran successfully the last three times but failed the time before that.

I would find it very useful to bring back a complete job history to the individual script job tab and/or implement some sort of filters on that tab.

Additionally, this could be somewhat resolved if we could filter on the main job history page by the script name.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/job-history-functionality-decreased/10074/3

**Comment by adamdriscoll** [comment]
@realslacker - We're fixing the issue with the job history in 4.2.5 but I like the idea of filtering for particular scripts on the main job page.
