### ISSUE TITLE
Wait-PSUJob should be able to wait for an array of jobs

### ISSUE THREAD

**Issue by RockoTheeHut** [ironmansoftware/powershell-universal#2904]
### Summary of the new feature / enhancement

I would like to execute multiple scripts at once and wait for them to all complete like wait-rsjob does with runspaces. Right now it will only accept a single job. As of right now we have to write our own function to monitor when all jobs complete. 

### Proposed technical implementation details (optional)

Wait-PSUJob -JobID <int64[]>

**Comment by adamdriscoll** [comment]
Can you use the pipeline for this? 

$Jobs = Invoke-PSUScript 
$Jobs | Wait-PSUJob

**Comment by RockoTheeHut** [comment]
@adamdriscoll  I was about to reply that I had tried that but then thought I had better test again to be sure.. Piping an array of jobs to wait-psujob did in fact work. I thought that was part of my tests.. sorry about that! I'll close this issue..
