### ISSUE TITLE
Add enableArcLinkLabels parameter to New-UDNivoChart

### ISSUE THREAD

**Issue by MattHarrisUltima** [ironmansoftware/powershell-universal#2907]
### Summary of the new feature / enhancement

Currently, when you create a pie chart using New-UDNivoChart the label lines appear and there is no way to remove them in PSU.

In the Nivo documentation for Pie charts (https://nivo.rocks/pie/) there is a parameter called enableArcLinkLabels  which removes these lines.

It would be good to be able to use this parameter to remove the lines.

Alternatively, if it is not too much work it would be good to be able to pass an object to the cmdlet to allow us to apply any Nivo support parameter.

### Proposed technical implementation details (optional)

Ability to set enableArcLinkLabels for Nivo pie charts or, abilty to pass an object of Nivo supported parmeters to the  New-UDNivoChart cmdlet.

Please see screenshots for examples
![2023-12-01 12_33_49-Pie chart _ nivo — Mozilla Firefox](https://github.com/ironmansoftware/issues/assets/106333485/2dcc43e0-6303-4687-a20b-1bd0d38332a7)
![2023-12-01 10_42_21-Pie chart _ nivo — Mozilla Firefox](https://github.com/ironmansoftware/issues/assets/106333485/80e2eb9a-c61b-4ea6-955e-c3d561f4c396)

Test code replicating problem:
```
New-UDApp -Title 'PowerShell Universal Test App' -Content {
    $Data =
    $([PSCustomObject]@{
        #ID = 'Compliant Resources'
        #Label = 'Compliant Resources'
        value = "50"
        color = '#89A63E'
    }
    [PSCustomObject]@{
        #ID = 'Non-Compliant Resources'
        #Label = 'Non-Compliant Resources'
        value = "50"
        color = '#A6364A'
    }
    )

New-UDNivoChart -Pie -Data ($Data | Where-Object { $_.Value -ne 0 }) -InnerRadius 0.7 -CornerRadius 5 -PadAngle 1 -Colors @{datum = 'data.color' } -Height 280 -Width 346 -MarginTop 0 -MarginBottom 0 -MarginLeft 0 -MarginRight 0 -DisableInteractive
}
```
![2023-12-01 12_39_11-Mail](https://github.com/ironmansoftware/issues/assets/106333485/48194a7b-7e56-4f53-b803-6311612bcf1f)

**Comment by tobrienultima** [comment]
While adding this parameter, would it be possible to also add "enableArcLabels" - this shows/removes the values from showing in the slices themselves which would be useful too.

**Comment by MattHarrisUltima** [comment]
Hi @adamdriscoll  and @mattselle .

We are looking at using Nivo charts more. Do you know if you will be able to support the other attributes Nivo offers in an upcoming version?

Using Nivo and its additional attributes would be very advantageous to us.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/ability-to-customize-labels-in-nivo-charts/4395/3

**Comment by MattHarrisUltima** [comment]
Hi @adamdriscoll ,

Can you confirm how to apply this? I can't see any update in the git docs and it looks like the release notes on the forum are no longer pubishing.

**Comment by adamdriscoll** [comment]
Hey @MattHarrisUltima ,

These were both added in 4.2.8 -> https://docs.powershelluniversal.com/changelogs/changelog#id-4.2.8-1-3-2023
