### ISSUE TITLE
Refresh on a sub admin page results in a white page

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2910]
### Version

4.2.4

### Severity

Low

### Steps to Reproduce

when i navigate to any page other than /admin, and press F5, the refresh loads a white page, back no longer works also

Funny thing, it removes the nested IIS app name from the url when you F4
https://servername.com/admin/manifest.json

### Expected behavior

```console
200
```

### Actual behavior

```console
404
```

### Additional Environment data

IIS: Nested

**Comment by adamdriscoll** [comment]
This has to do with enabling PSU as a progressive web app. We're disabling all that for now since it is caching a bunch of junk.

**Comment by Omzig** [comment]
still broke:
![image](https://github.com/ironmansoftware/issues/assets/1987296/3dd15017-c57f-4b36-8582-43e51a1cb659)

**Comment by adamdriscoll** [comment]
@Omzig Can you try to clear your browser cache? The manifest is just commented out in the index.html file now. 

<img width="349" alt="image" src="https://github.com/ironmansoftware/issues/assets/1256531/291793f0-79c3-47a0-baba-925ea27ae886">

**Comment by Omzig** [comment]
@adamdriscoll, lol, now it doesn't even load the manifest:
![image](https://github.com/ironmansoftware/issues/assets/1987296/b19b4dc9-bed3-491e-8dad-49ed0b0a07d9)

**Comment by Omzig** [comment]
i would be happy to get on a call with you, @adamdriscoll, if that would help ;)

**Comment by adamdriscoll** [comment]
Probably will need to schedule that. I can't reproduce this in a nested site in IIS. Can you email me? I might not be able to sneak something in until tomorrow. 

<img width="332" alt="image" src="https://github.com/ironmansoftware/issues/assets/1256531/c5ee6301-3f5c-4490-aef6-1117b745c562">

**Comment by adamdriscoll** [comment]
@Omzig Migrated to #2925
