### ISSUE TITLE
Add a Role to an API endpoint does not show on the form

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2920]
### Version

4.2.x

### Severity

Low

### Steps to Reproduce

When i go to an api, add a role, click save settings, then go somewhere else in the admin site, when i revisit the api and look at the settings the role is blank

### Expected behavior

```console
saved settings on api should be shown
```

### Actual behavior

```console
role is blank
```

### Additional Environment data

IIS: Nested

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/1987296/a72d177e-ea39-451a-9c8e-a51fd93b84d5)

**Comment by RockoTheeHut** [comment]
We see the same thing
