### ISSUE TITLE
Issue with element OnClick when using Invoke-UDJavascript

### ISSUE THREAD

**Issue by tobrienultima** [ironmansoftware/powershell-universal#2922]
### Version

4.2.4

### Severity

Quality-of-life

### Steps to Reproduce

When using Invoke-UDJavascript inside an element's OnClick event, the action gets stuck running the JavaScript. Any actions after the JavaScript does not run and the element then becomes unresponsive until the page is refreshed. This behaviour seems specific to UDElements.

Additional information, a code example and screenshots can be found here:

https://forums.ironmansoftware.com/t/issue-with-invoke-udjavascript/10115

### Expected behavior

```console
If using Invoke-UDJavascript in an element's onclick should run successfully and should not hang. The element should be clickable after the code has run once.
```

### Actual behavior

```console
Elements become unresponsive after clicking them once. Other elements on the page which also have an onclick also become unresponsive.
```

**Comment by adamdriscoll** [comment]
@tobrienultima Is there an error in the dev tools console in the browser?

**Comment by tobrienultima** [comment]
Hi Adam, I don't see any new errors appear when clicking on the element. I've also removed all elements from the page and there aren't any differences in the console with/without the elements too.
I added some example code to reproduce the error in the link to my forum post above if that helps. I've tried it on 2 different PSU instances and get the same behaviour.

**Comment by adamdriscoll** [comment]
I can reproduce this. We added the ability to return data from Invoke-UDJavaScript and it seems to cause some sort of deadlock in PSU. We'll get this resolved.

**Comment by adamdriscoll** [comment]
It looks like when we added the ability to return data from JS, that causes a hang for some reason in UDElement. I've added a -IgnoreResult parameter to Invoke-UDJavaScript to avoid that. 

```
New-UDElement -Id "testingelement" -Tag div -Attributes @{
                'className'="accordionheader"
                onClick={
                    Show-UDToast -Message "Pre-Toggle" -Duration 5000
                    Invoke-UDJavaScript -JavaScript 'document.getElementById("testingelement").classList.toggle("active");' -IgnoreResult
                    Show-UDToast -Message "Post-Toggle" -Duration 5000
                }
            } -Content {
                New-UDStack -Direction row -AlignItems center -Children {
                    New-UDIcon -Icon chevron_right -ClassName "accordionicon"
                    New-UDParagraph -Text "Test"
                }
            }
            New-UDSwitch -UncheckedLabel "Inactive" -CheckedLabel "Active" -Checked $false -OnChange {
                Show-UDToast -Message "Pre-Toggle" -Duration 5000
                Invoke-UDJavaScript -JavaScript 'document.getElementById("testingelement").classList.toggle("active");'
                Show-UDToast -Message "Post-Toggle" -Duration 5000
            }
```

This prevents it from even trying to deserialize the data returned by the JS statement.
