### ISSUE TITLE
Rich Text (WYSIWYG) Input Field Dashboard Component

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/powershell-universal#293]
**Is your feature request related to a problem? Please describe.**
There are times where a workflow or process requires rich-text input from end-users for use with PowerShell Universal Dashboards but there doesn't appear to be an existing component ('WYSIWYG editor') to allow the entry of formatted text.
https://forums.ironmansoftware.com/t/rich-text-wysiwyg-input-field-component/5181

**Describe the solution you'd like**
An existing solution can be adapted into a component for use with PowerShell Universal Dashboards. Licensing issues aside, here are some examples:
- https://github.com/codex-team/editor.js
- https://github.com/ckeditor/ckeditor5

**Describe alternatives you've considered**
End-users could be asked to use normal multi-line text input boxes and use Markup/Markdown style of notation to format their text but this introduces a skill hurdle and impacts the UX for PowerShell Universal Dashboards aimed at less technical users.

**Additional context**
N/A

**Comment by adamdriscoll** [comment]
New-UDEditor has been added and implements Editor.JS. It includes all standard plugins and can return the JSON block format as well as HTML.
