### ISSUE TITLE
Deleting a schedule in the admin console does not refresh the page

### ISSUE THREAD

**Issue by RockoTheeHut** [ironmansoftware/powershell-universal#2939]
### Version

4.2.5

### Severity

Low

### Steps to Reproduce

I have to manually refresh the page for the new changes. 

Env: Three servers with SQL backend 

### Expected behavior

```console
When you delete a schedule the data refreshes
```

### Actual behavior

```console
It does not refresh
```

**Comment by adamdriscoll** [comment]
I cannot reproduce this in 4.2.10.
