### ISSUE TITLE
Rerun job - DateTime type are not working

### ISSUE THREAD

**Issue by mikedhanson** [ironmansoftware/powershell-universal#2944]
### Version

3.10.2

### Severity

Low

### Steps to Reproduce

When you have a [datetime] type as a param in a script everything works fine until you click rerun job and params with datetime do not come over.

```
[CmdletBinding()]
param (
    [Parameter()]
    [datetime]
    $BeforeDate,

    [Parameter()]
    [datetime]
    $AfterDate
)
```

### Expected behavior

```console
datetime params should come over when clicking rerun job
```

### Actual behavior

```console
value is null
```

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/15201245/df64baae-96e0-4e4e-ba15-98beb13840a4)

![image](https://github.com/ironmansoftware/issues/assets/15201245/e9bcaf51-b03d-43b4-a2f2-9c425d76dbc6)

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/rerun-job-datetime-type-are-not-working/10122/2
