### ISSUE TITLE
api documentation type renders weird 

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2948]
### Version

4.2.5

### Severity

Low

### Steps to Reproduce

i am experiencing a problem with how the types render in the swagger doc

```
[Documentation()]
class MyReturnType {
    [string]$Value
}
```

### Expected behavior

```console
{
  "Value": "string"
}
```

### Actual behavior

```console
{
  "Value": null
}
```

### Additional Environment data

IIS: Nested

**Comment by Omzig** [comment]
I am also unable to tell it that the output is an array, not sure how what to put to tell it that the output is an array type

**Comment by rwidmark** [comment]
For [string] use it like this:
[String]$Data = "my data"

It will output

Data: my data

For array use [String[]]$Data = "data1", "data2"

That should output 
Data: [
Data1,
data2
]


Sorry for formatting I'm on my phone.

**Comment by Omzig** [comment]
@adamdriscoll, shouldn't it auto generate the type example like it does in C# for you? Or do you really have to go through and decorate it?

**Comment by rwidmark** [comment]
Found some more issues, the documentation for the APIs needs to have some work done.

Will post an issue here when I have the time to do so.

**Comment by Omzig** [comment]
@adamdriscoll, 4.2.14? /hint /hint

**Comment by rwidmark** [comment]
@adamdriscoll if you write [bool]$test then you will get test: null

If you write = $false or true after it will output like string.

Would be great if it was outputted as json formatted bool
