### ISSUE TITLE
Scheduled jobs not showing up

### ISSUE THREAD

**Issue by TurnItOff-OnAgain** [ironmansoftware/powershell-universal#2955]
### Version

4.2.5

### Severity

Low

### Steps to Reproduce

Some scheduled jobs are not showing up in any of the jobs lists. I have 4 scripts I know that are correctly running, but are not showing up in the main job log or under the script unless I manually run them. 

This one is currently running in Hangfire, but not in the console

![image](https://github.com/ironmansoftware/issues/assets/26926284/0da3a45d-7f7f-4f8c-be92-77624f5a8689)

![image](https://github.com/ironmansoftware/issues/assets/26926284/35162963-3b7e-4f17-aaad-5ae2b2bb4ccf)

This one is scheduled to run every day at 7:30AM, and it does run, but the scheduled jobs do not show up in Jobs, only the manually run ones. (The jobs with errors listed are expected)

![image](https://github.com/ironmansoftware/issues/assets/26926284/57b25e7a-d915-47bf-9ca9-7b5e2b227057)

![image](https://github.com/ironmansoftware/issues/assets/26926284/f247f30d-02b0-4bac-b98c-b50f5b7bac17)

Not browser specific. I've checked in Firefox, Edge, and Chrome.

### Expected behavior

```console
jobs show up in the log
```

### Actual behavior

```console
jobs not showing up
```

### Additional Environment data

https://forums.ironmansoftware.com/t/two-scheduled-jobs-issues/10126

**Comment by alexrgreenwood** [comment]
i thought the same until i realised there is a new "scheduled" filter button that is off by default - clicking that to blue (on) should make them appear

**Comment by TurnItOff-OnAgain** [comment]
Ahh I see that now. Strange that only some of the scheduled jobs are not showing up.

The difference seems to be the schedules that have the Name field populated do not show up, but schedules without the Name field do show up. @adamdriscoll bug in the schedule filter?

Here it is with the scheduled pill enabled, showing all jobs

![image](https://github.com/ironmansoftware/issues/assets/26926284/ce22ce6f-0981-408f-aec9-f42f5f282b73)


and with the pill disabled only showing some jobs

![image](https://github.com/ironmansoftware/issues/assets/26926284/27321fcf-f141-4a81-b4a7-8eea8eb21a55)

**Comment by adamdriscoll** [comment]
Ah. I see the issue. I didn't realize you could create schedules without names any longer but it works fine from the schedules.ps1 file. We can get this fixed.

**Comment by TurnItOff-OnAgain** [comment]
Thanks for fixing it! The schedules that don't have a name were created in the early 3.x days.
