### ISSUE TITLE
Git Synchronization Failed: The current branch is configured to merge with the reference 'refs/heads/main'

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2958]
### Version

4.2.6

### Severity

Low

### Steps to Reproduce

git it still kranky

### Expected behavior

```console
git pull
```

### Actual behavior

```console
The current branch is configured to merge with the reference 'refs/heads/main' from the remote, but this reference was not fetched.
```

### Additional Environment data

IIS: Nested

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/1987296/4dd35135-d1de-4c1c-acc5-52a069a1bf38)

**Comment by adamdriscoll** [comment]
If you run a `git fetch` in the repo directory does this go away? Does it come back if you click sync now?

**Comment by Omzig** [comment]
git fetch with git.exe does not fix the problem, tried, even tried to checkout dev, delete main, checkout main, still mad, at this point do we shut down and delete the .git folder?

**Comment by adamdriscoll** [comment]
I'm not sure yet. Still trying to reproduce this. I've found some SO posts about this but it's not clear yet what the root cause is. 

https://stackoverflow.com/questions/36984371/your-configuration-specifies-to-merge-with-the-branch-name-from-the-remote-bu

**Comment by Omzig** [comment]
> I'm not sure yet. Still trying to reproduce this. I've found some SO posts about this but it's not clear yet what the root cause is.
> 
> https://stackoverflow.com/questions/36984371/your-configuration-specifies-to-merge-with-the-branch-name-from-the-remote-bu

what logging would you like turned on so we can see what is going on? i can email it to you if u like

**Comment by Omzig** [comment]
# Solution
So, I was able to fix my repo by moving the old repository folder to the c:\temp folder and then letting PSU redownload the repo anew. Now I have no more errors. I still have the bad .git folder if it is needed. Not sure what to do now with this issue now.

## Better Use of Time
Instead of trying to figure out why 1 version of PSU to another messed up my .git folder, can we do this instead? 
- https://github.com/ironmansoftware/issues/issues/2957

**Comment by adamdriscoll** [comment]
@Omzig - I would compare the config file in the .git folder between the working one and the broken one to see if there is any difference. I'll close this issue for now and can look at that other issue.

**Comment by Omzig** [comment]
@adamdriscoll,
- the main thing i can figure out is that the FETCH_HEAD is blank in the bad folder
- HEAD is the same
