### ISSUE TITLE
Need to clear notifications (1000+)

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2959]
### Summary of the new feature / enhancement

because notifications has so much, how do we clear them out?

### Proposed technical implementation details (optional)

![image](https://github.com/ironmansoftware/issues/assets/1987296/2c66dc18-eb7b-4a2f-beb4-1494b7641f77)

**Comment by TurnItOff-OnAgain** [comment]
I ran into this a while back and was able to use the built in API to fix this with the /api/v1/notification endpoint
