### ISSUE TITLE
Wallboard support

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#296]
Customer would like to use PowerShell Universal Dashboard on a wallboard. They are having a hard time configuring sessions timeouts etc so that the dashboard doesn't time out after some time. Since the wallboard will not be interactive, it needs to not time out.

**Comment by Viajaz** [comment]
I have this same digital signage requirement as well.

**Comment by mwatts-seg** [comment]
Hmm, I wonder how my environment is setup differently. 
Maybe because I use endpoints to refresh the content, but my overhead monitors for our data center does not time out. I use at least four to five dashboards for this.
