### ISSUE TITLE
Logging stopped working

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#2972]
### Version

4.2.6

### Severity

Low

### Steps to Reproduce

i upgraded to 4.2.6 and then my logging stopped showing up in the admin site

### Expected behavior

```console
show logs
```

### Actual behavior

```console
no logs shown
```

### Additional Environment data

IIS: Nested

# Workaround Solution

my log.db file was 220mb
- deleted logs in /PowerShellUniversal
- deleted logs.db

**Comment by Omzig** [comment]
@adamdriscoll, 
![image](https://github.com/ironmansoftware/issues/assets/1987296/ff996500-7fad-406f-b1e0-1c726f5b4503)

**Comment by MikeShepard** [comment]
@adamdriscoll  - It seems like since 4.0 the logging has gone way downhill.  I often go to the admin console to see logs and there's nothing.

**Comment by adamdriscoll** [comment]
When it fails to load, is the browser returning an error at all? Is it a size issue with the logging database?

**Comment by MikeShepard** [comment]
Looks like there's a 500 error happening.

![image](https://github.com/ironmansoftware/issues/assets/5541154/14a5f885-3860-4180-90f4-af7f068e0bb9)

**Comment by adamdriscoll** [comment]
The system logs should have a clear error message in them. You can either look through them over email them to me and I can take a look. That should give me something to go on.

**Comment by MikeShepard** [comment]
Just emailed you the system logs for today.

**Comment by adamdriscoll** [comment]
Thanks. It looks like something is going awry with the log config because it thinks the connection string is null. This means it isn't grooming or able to display the log messages. 

Is it still writing logs?
What does your logging.ps1 look like?

**Comment by MikeShepard** [comment]
```
New-PSULoggingTarget -Type "File" -Properties @{
    RetentionPeriod = '30'
    Path            = 'C:\ProgramData\PowerShellUniversal\log.txt'
}
```

and yes, it's still writing to the log.

**Comment by adamdriscoll** [comment]
Ah. I gotcha. I can reproduce this. The reason you can't view logs is that it's not writing any logs to the database.  I've added some better error handling around this so that it will show the following when no DB logging is enabled. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/8d13992e-4375-4d68-bac0-e9240fda56d8)

You will need to add something like this to see logs in the admin console. 

```powershell
New-PSULoggingTarget -Type "Database" -Level Information -Scope 'User'
```

**Comment by MikeShepard** [comment]
should this have been added automatically when the new PSU logging was implemented (upgrading from 3.xx to 4.xx)?

**Comment by adamdriscoll** [comment]
It shouldn't have had a logging.ps1 at all and used the defaults. The defaults are the log.txt file (which you have) and the database logging. 

If you edited the logging targets it would generate this file. You can also just delete the file to go back to defaults. Based on Matt's screenshot it looks like DB logging was running for some time.

**Comment by MikeShepard** [comment]
Matt's screenshots and mine are almost certainly different instances.  We've had logging issues consistently since 4.0

**Comment by adamdriscoll** [comment]
Understood. Based on the size of Matt's log I thought it was some sort of performance issue. Let me know if enabling the DB logging lets you see logs and we can continue to diagnosis the logging system. 

The v3 version didn't persist anything and wasn't using Serilog. We could create an [In Memory target](https://github.com/serilog-contrib/SerilogSinksInMemory) that effectively does the same thing to avoid having to worry about configuring any DB logging if that isn't desired.

**Comment by MikeShepard** [comment]
For instance, here's what's in the latest log.txt (log20240110.txt):
[09:41:30 INF][Security][roles.ps1] Default admin logged in, setting admin to true.
[09:41:30 INF][Security][roles.ps1] Default admin logged in, setting admin to true.
[09:41:34 INF][App][CPM] Scope- None
[09:41:34 INF][App][CPM] Fitering IDs based on None - None
[09:41:34 INF][App][CPM] Filtered for None, 854 rows
[09:41:34 INF][App][CPM] Reloading CPM table
[11:38:34 INF][App][jhCx] Waiting for dashboard information...
[11:38:35 INF][App][jhCx] Dashboard information received. Starting dashboard.
[11:38:35 INF][App][jhCx] Creating services.
[11:38:36 INF][App][jhCx] Starting scheduler.
[11:38:37 INF][App][jhCx] Dashboard configuration complete.
[11:38:37 INF][App][CRMManagement] Creating services.
[11:38:37 INF][App][CRMManagement] Starting scheduler.
[11:38:37 INF][App][CRMManagement] Dashboard configuration complete.
[11:38:37 INF][App][CPM] Creating services.

Here's what shows in the log for the CPM app:
![image](https://github.com/ironmansoftware/issues/assets/5541154/37140892-8335-4dd3-a35e-40a3d17a6e6b)

**Comment by adamdriscoll** [comment]
Are this Write-Host outputs or something? 

```
[09:41:34 INF][App][CPM] Scope- None
[09:41:34 INF][App][CPM] Fitering IDs based on None - None
[09:41:34 INF][App][CPM] Filtered for None, 854 rows
[09:41:34 INF][App][CPM] Reloading CPM table
```

**Comment by MikeShepard** [comment]
those are, yes.

**Comment by adamdriscoll** [comment]
Weird. I just tried the same thing. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/60628a69-8cba-41bb-88cf-4bf7e26f7720)

![image](https://github.com/ironmansoftware/issues/assets/1256531/0a6f5e05-fa42-435a-b917-76eb262c1e37)

I'm using the default logging config. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/9483482b-611f-42d4-8550-e3981768ae5d)

Now that the logs are showing up again, can you send me another system log?

**Comment by MikeShepard** [comment]
this is all working now.

**Comment by adamdriscoll** [comment]
Thanks. I'll remove this from the milestone for now and we can double check with Matt to make sure it's working for him as well.

**Comment by adamdriscoll** [comment]
Haven't heard back about this so assuming all is working.

**Comment by Omzig** [comment]
ya, will reopen if we get more issues on this in the current version, it takes a while to build up a 700mb log db file
