### ISSUE TITLE
Connect-PSUEventHub fails to run

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#2987]
### Version

4.2.6

### Severity

Low

### Steps to Reproduce

```
PS C:\Users\Administrator> import-module universal
PS C:\Users\Administrator> connect-psueventhub -ComputerName http://localhost:5000 -Hub eventhub
connect-psueventhub: The type initializer for 'PowerShellUniversal.ConnectEventHubCommand' threw an exception.
PS C:\Users\Administrator> $error[0].Exception

TypeName       : PowerShellUniversal.ConnectEventHubCommand
TargetSite     : Void .ctor()
Message        : The type initializer for 'PowerShellUniversal.ConnectEventHubCommand' threw an exception.
Data           : {}
InnerException : System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces,
                 Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific
                 file. (0x80131621)
                 File name: 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral,
                 PublicKeyToken=cc7b13ffcd2ddd51'
                  ---> System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces,
                 Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
                    at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
                    at System.Reflection.Assembly.LoadFrom(String assemblyFile)
                    at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
                    at System.Runtime.Loader.AssemblyLoadContext.InvokeResolveEvent(ResolveEventHandler eventHandler,
                 RuntimeAssembly assembly, String name)
                    at PowerShellUniversal.ConnectEventHubCommand..cctor()
HelpLink       :
Source         : Universal.Cmdlets
HResult        : -2146233036
StackTrace     :    at PowerShellUniversal.ConnectEventHubCommand..ctor()
                    at lambda_method85(Closure)
                    at System.Management.Automation.CommandProcessor.Init(CmdletInfo cmdletInformation)

```

### Expected behavior

```console
Runs
```

### Actual behavior

```console
Assembly issue
```

**Comment by adamdriscoll** [comment]
This is related to this: #2548 I cannot for the life of me get this to work in PS7 directly (how did this ever work kinda thing...). We likely need to implement the module assembly initializer but it's a big PIA and requires lots of code churn making it dangerous. 

I'm trying to brain storm how to attack this. The root of the issue is that PS7 packages an older version of the BCL assembly directly with the shell so we don't have time to load the newer one required by SignalR. This may have worked when we targeted .NET 6. 

The event hub client installer seems like an easier ask at the moment: #3003

**Comment by oNdsen** [comment]
@adamdriscoll any News regarding this Problem? PS7 above 7.3.8 breaks the EventHub Function.
Please note this critical Issue: https://www.anoopcnair.com/2-critical-vulnerabilities-powershell-cve-nov/
Can you please fix this Problem ASAP?

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/exception-with-connect-psueventhub-microsoft-bcl-asyncinterfaces/10414/2

**Comment by adamdriscoll** [comment]
We're removing this cmdlet and shipping the client directly in the install package. There are too many dependency issues with PowerShell to ship this as a cmdlet.
