### ISSUE TITLE
$EventData for New-UDDatePicker provides output in multiple formats (re-open)

### ISSUE THREAD

**Issue by MattHarrisUltima** [ironmansoftware/powershell-universal#2992]
### Version

4.2.6

### Severity

Low

### Steps to Reproduce

This is a re-open of #2835 I am experiencing the same problem in 4.2.6

### Version

4.0.12

### Severity

High

### Steps to Reproduce

I have tested this in 2 code bocks (with and without the -Format parameter):

```
New-UDDatePicker -Id 'managecompanysecretexpirydate' -Format 'dd/MM/yyyy' -OnChange {
        $session:ChangedDate = $Eventdata
    Sync-UDElement -id dynamicbox
}

New-UDDynamic -id dynamicbox -Content {
    New-UDParagraph -Text $session:ChangedDate
}
```

```
New-UDDatePicker -Id 'managecompanysecretexpirydate' -OnChange {
        $session:ChangedDate = $Eventdata
    Sync-UDElement -id dynamicbox
}

New-UDDynamic -id dynamicbox -Content {
    New-UDParagraph -Text $session:ChangedDate
}
```

### Expected behavior

```console
### Expected behavior


$EventData should present data in the same format
```

### Actual behaviour

```
The output passed to $EventData is presented in at least 1 of 2 formats.

E.g.

11/10/2023 14:47:11
"2023-11-10T14:47:11+00:00"
```

### Visuals

![2023-11-09 14_45_19-IA-Cloud — Mozilla Firefox](https://github.com/ironmansoftware/issues/assets/106333485/453d08c3-bda9-4f36-a6f4-4cfcee6d0657)
![2023-11-09 14_45_09-IA-Cloud — Mozilla Firefox](https://github.com/ironmansoftware/issues/assets/106333485/d9ef2d69-0f82-4f28-b0e6-172d0ee8ba2c)
![2023-11-09 14_44_36-IA-Cloud — Mozilla Firefox](https://github.com/ironmansoftware/issues/assets/106333485/5383a723-8732-463c-8b1f-6e709a784f93)
![2023-11-09 14_47_29-IA-Cloud — Mozilla Firefox](https://github.com/ironmansoftware/issues/assets/106333485/60de4cfd-b28f-479e-ae46-01eecf4f8c59)
![2023-11-09 14_47_22-IA-Cloud — Mozilla Firefox](https://github.com/ironmansoftware/issues/assets/106333485/03def459-221f-488d-8238-11f0bd85a2fb)

**Comment by adamdriscoll** [comment]
I cannot reproduce this on 4.2.8. Additionally, I'm not seeing the times in the dates. Something has changed. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/583fb05c-8c48-4172-8560-6078fcb41484)

We did make a change around the -Locale parameter but I'm not sure if that has an effect on this. I'll remove this from the milestone for now but will leave this open until we can verify across more systems.

**Comment by MattHarrisUltima** [comment]
Hi Adam,

I am on 4.2.6 at the moment. Once 4.2.8 is out I will test again to see if the problem is in this version.

Kind Regards,

MATT​​​​

HARRIS
 |
Cloud Automation Developer
 |
www.ultima.com<http://www.ultima.com/>
 |

**Comment by MattHarrisUltima** [comment]
Hi @adamdriscoll 

I can still replicate this in 4.2.8.

Please reach out if you would like a call to take a look at this.

**Comment by adamdriscoll** [comment]
Can you email me at adam[at]ironmansoftware.com and we can get something scheduled?

**Comment by MattHarrisUltima** [comment]
Hi @adamdriscoll 

I have pulled 4.2.10 and the problem looks to be fixed.

Many thanks for your help with this.
