### ISSUE TITLE
Event Hub Client Installer

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#3003]
### Summary of the new feature / enhancement

Right now you need to have almost the whole PSU Installation running on a Client in order to being able to connect to a PSU Event Hub. 
(You state that it's part of the Universal Module but I wasn't able to import only the Module (and all its contents) on a Client w/o PSU... I didn't yet play around trying to figure out all dependencies though... I'm sure it will somehow work)

### Proposed technical implementation details (optional)

Create a little Client Installer (MSI) with only the Hub Related stuff. No need for the whole PSU Webserver, etc. :-)

**Comment by adamdriscoll** [comment]
Related: #2987

**Comment by donlent** [comment]
Super, thank you so much @adamdriscoll!
Really appreciate that you're taking care of this within the next release cause we'll probably have a new customer solution built on top of the Event Hub functionality... And it's just so much professional to have a little installer for this purpose.
Really looking forward to it!

**Comment by Omzig** [comment]
LOL, i am blind, i cannot find the Event Hub Client Installer.

However after failing to find it, Mike helped me find it. It is so not easy to find.

Process: 
- go here https://ironmansoftware.com/release/powershell-universal
- click the download button
- there you will find the hub msi
