### ISSUE TITLE
AppFullUrl is wrong

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3013]
### Version

4.2.8

### Severity

Low

### Steps to Reproduce

when AppFullUrl returns a value, it does not represent the correct url in a nested IIS environment
- visit the live docs page and then go to /variables

### Expected behavior

```console
https://dev.servername.com/NESTEDIISNAME/apps/docs
```

### Actual behavior

```console
https://dev.servername.com:80/apps/docs
```

### Additional Environment data

IIS: Nested

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/1987296/7f8f9b41-b2d0-4485-9a44-bb8c26c50158)

**Comment by Omzig** [comment]
@adamdriscoll, why does AppFullUrl have :80 on an https connection?

in order to use it, i am having to do this:
```
$global:myAppUrl = $AppFullUrl.replace(':80',"")
```

**Comment by adamdriscoll** [comment]
Let me re-check this.
