### ISSUE TITLE
Memory Limits for Scripts 

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3019]
### Summary of the new feature / enhancement

A customer would like to see memory limits for scripts (xGB) that causes PSU to terminate the script. We already collect memory so putting this in place should be easy. This would prevent the PSU server from running out of memory due to issues with script development.

**Comment by feichinger** [comment]
Hey Adam - I'm not seeing this in the release notes or in the options in the GUI. Has this really made it into version 4.2.9?

Thanks,
Felix

**Comment by adamdriscoll** [comment]
This is in the general settings. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/058f7cc4-3193-45c6-90b7-cc88dcf256d6)

**Comment by feichinger** [comment]
thank you

I just set that to 7000 and it kills all my scripts. Here's an example from one of them:

[error] Job exceeded the maximum memory allowed. The maximum memory allowed is 7000 MBs. The job used 159 MBs.

**Comment by adamdriscoll** [comment]
It looks like we are wrapping around on a int. If you set the value to about 2000, it should work and won't wrap. That said, we'll get this resolved in the next version.
