### ISSUE TITLE
🚨 The window terminated unexpected (reason: 'oom', code: '7012')

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#3030]
## Describe the bug
PowerShell Pro Tools for VS. Code can become stuck in a loop which drains resources leading to `The window terminated unexpected (reason: 'oom', code: '7012')`. I am able to recreate this on Windows 10 machines consistently.

## To Reproduce

1. On a freshly Windows 10 22H image, install the latest VS. Code followed by the PowerShell extension.
2. Restart VS. Code
3. Install the current PowerShell Pro Tools extension (2023.12)
4. Restart VS. Code
5. Ensure that the PowerShell Pro Tools loads correctly and is functioning correctly (see below)

![image](https://github.com/ironmansoftware/issues/assets/537287/8571965c-d67e-49c6-9647-202efdd904b1)
###### above figure shows PowerShell Pro Tools is in Connected mode

7. Create a new sample PowerShell script and execute it once (e.g. "hello world")
8. Restart VS. Code
9. VS. Code will not be able to connect to its own internal daemon. In other words, it will stay in "_Connecting..._" 🟡 mode perpetually instead of moving to "_Connected_" 🟢 mode (see below)

![image](https://github.com/ironmansoftware/issues/assets/537287/0f36e791-3c7f-40c8-b29c-c53275c23c49)
###### above figure shows PowerShell Pro Tools is stuck in Connecting mode

10. VS. Code will become unresponsive with the below prompt
![image](https://github.com/ironmansoftware/issues/assets/537287/943358fb-b820-41c9-bca4-c62ee7ad9a7b)

## Expected behavior
PowerShell Pro Tools should not try to reconnect to its own daemon infinitely

## Actual behavior
PowerShell Pro Tools tries to reconnect to its own daemon infinitely

## Version
VS. Code extension 2023.12 with Microsoft PowerShell extension 

## Logs
The exthost.log will be filled with the below error until the out of memory error occurs
 ``2024-01-09 11:52:08.701 [error] Error: connect ENOENT \\.\pipe\usxhynjektcs_log
	at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)``

**Comment by DataTraveler1** [comment]
The immediate crashing issue was remediated with the release of 2023.12.1. However, the underlying root cause was not known until now. This issue is limited to Windows operating system only.

The root cause is a reference to a non-existent "backupPath" in the windowState section of the VS Code user settings.

![image](https://github.com/ironmansoftware/issues/assets/537287/fafdb700-e981-404c-8b53-e1fbe025ff60)

The file is typically located at %APPDATA\Code\User\globalStorage\storage.json by default

![image](https://github.com/ironmansoftware/issues/assets/537287/33518f52-152c-401d-b328-06f67a8112cc)

Removing the reference to the windowState (when VS Code is closed) is the least impactful workaround (demonstrated below).

![Issue3030-Workaround-org](https://github.com/ironmansoftware/issues/assets/537287/b108d60d-38b9-4d37-9329-4ef23f550290)

**Comment by adamdriscoll** [comment]
This should be resolved in the latest.
