### ISSUE TITLE
Variables' list its properties and methods are partially sorted

### ISSUE THREAD

**Issue by That-Annoying-Guy** [ironmansoftware/powershell-universal#3031]
**Describe the bug**
**In some situations,** the list of properties and methods listed after you type a period is partially sorted.
My example below consistently fail to sort the list of properties and methods .

**To Reproduce**

1. Install IntuneWin32App module... [You will be prompted to approve]
`Install-Module -Name IntuneWin32App #you can only install modules once per session (need elevation to install module)
`
2. Connect to a tenant
` Connect-MSIntuneGraph -TenantID "<tenant_name>.onmicrosoft.com" -verbose
`
3. This creates the `$AuthenticationHeader` variable

4. Now type  `$AuthenticationHeader.` (with the period at the end)

5. The list of properties and methods is shown but it not sorted properly.

**Expected behavior**
The list of properties and methods should be sorted properly. not a jumbled mess.

**Screenshots**
![image](https://github.com/ironmansoftware/issues/assets/12900014/48166900-1ee3-49be-b36b-b75ddecf6486)
**Version**

Tool (Visual Studio, VS Code, PSScriptPad, PS Module): 
PowerShell Pro Tools 
Version Number: v2023.12.0 

Operating System:  win10 22h2

**Additional context**
VS code v1.84.2

**Logs** 
No Logs found in $($Env:AppData\PowerShell Pro Tools)

**Comment by adamdriscoll** [comment]
@That-Annoying-Guy Are you using RapidSense or just the standard IntelliSense? If it's the standard IntelliSense, then that is provided by the PowerShell extension itself -> https://github.com/PowerShell/vscode-powershell

**Comment by That-Annoying-Guy** [comment]
I tried RapidSense and it's the same thing.

![image](https://github.com/ironmansoftware/issues/assets/12900014/8c72499a-ec53-4d01-8b77-0c46fe131ff8)

Q1: Which is best **RapidSense** or **IntelliSense**?

Q2: Is this issue related to how PS Functions' parameters not sorted either?
![image](https://github.com/ironmansoftware/issues/assets/12900014/5be267db-2b25-4094-a0a0-a4027dbf6a2a)

**Comment by adamdriscoll** [comment]
Q1 - We introduced Rapidsense when they first released the PS extension and the IntelliSense was much slower. I would suggest just using the built in IntelliSense at this point as they've made a ton of improvements. 
Q2 - Yep. Both of these functions use PowerShell built-in command completion engine. I have no idea why they would be out of order.

**Comment by That-Annoying-Guy** [comment]
If this is a Bug in VS Code and not PS Pro Tools, how come listing properties and methods listing didn't even happen until I installed PS Pro Tools?

**Comment by adamdriscoll** [comment]
Not sure. I just tried without PowerShell Pro Tools installed and it's out of order for me too. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/3cd76612-2d55-4efd-a9f5-1c4b1403fa25)

What I'm noticing is that it's putting the variables that are in the current scope at the top. For example, $NoDashboard is defined as a parameter for the function I'm in.
