### ISSUE TITLE
Login page logo only works with local path now

### ISSUE THREAD

**Issue by TurnItOff-OnAgain** [ironmansoftware/powershell-universal#3037]
### Version

4.2.8

### Severity

Low

### Steps to Reproduce

After upgrading to 4.2.9 the login page logo only displays when using the local path to it. Serving the logo through http no longer works. Assuming this is related to #2705

### Expected behavior

```console
logo displays
```

### Actual behavior

```console
No logo
```

### Additional Environment data

Universal 4.2.9
Built in web server
Server 2019

### Visuals

login page with the logo served via http

![image](https://github.com/ironmansoftware/issues/assets/26926284/6c9a62d4-b8ed-4132-b26e-e6e9dbddb8cf)

Displays correctly when serving via local path.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/login-page-logo-is-not-loading-after-updating-to-psu-4-2-9/10218/2

**Comment by adamdriscoll** [comment]
@TurnItOff-OnAgain - How is your URL configured? I tried relative and

**Comment by TurnItOff-OnAgain** [comment]
I created a published folder in the admin console and used that url. I can browse the URL fine in a browser and get the image. Relative works fine, it's the https url that doesn't.

**Comment by adamdriscoll** [comment]
@TurnItOff-OnAgain Thanks. I realized that caching was throwing me off. Got it resolved.
