### ISSUE TITLE
No code syntax check

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/powershell-universal#3044]
**Describe the bug**
I have been forced into re-installing Visual Studio 22 Community and now syntax errors in my code no longer is shown.
Neither in the "Error List" window nor visually in the code.

**To Reproduce**
1. Type an extra curly brace

**Expected behavior**
Error List window showing the error and a red underscore at the extra brace.

**Screenshots**

**Version**
PowerShell Tools Version: 2023.8.0
Visual Studio Version: 17.8.4
Windows Version: Microsoft 10 22H2

**Additional context**
The re-install has forced me to newer versions of both VS2022 and poshtools, so I don't know if it would have worked before.
Everything else seems to work, I can debug, use the left margin bulb, complete commands and so on.

**Logs** 
[log-20240114.txt](https://github.com/ironmansoftware/issues/files/13931919/log-20240114.txt)

**Comment by pju55** [comment]
Any chance to get a little help?
Pretty annoying having no syntax check.

**Comment by adamdriscoll** [comment]
@pju55 Do you have PSScriptAnalyzer installed? Also, make sure you have this setting enabled. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/13365c07-9278-43f5-a9e8-274f21dcd733)

**Comment by pju55** [comment]
@adamdriscoll  Embarassing !
But, thanks a lot for taking your time to tell me ...
It'll go into my notes !

**Comment by pju55** [comment]
@adamdriscoll 
Hmm, could you give me a hint on how to make it persistent...
I enable, click Save and closes VS.
But next time I open VS, the setting is disabled again. Guess this has been the problem from the beginning.

**Comment by pju55** [comment]
Have dug a bit deeper.
PSScriptAnalyzerSettings.psd1 is being updated correctly.
AnalysisSettings.json is not. 
The 3 top flags is not written at all.
I can't quite figure when/how "EnabledLevels" are written - somehow seems to be some lag.
Example: 
I disable "Information", click "Save" - no changes to file (it's written, but no change).
Then disable "Warning", too, and click "Save". Now "Information" is removed from "EnableLevels", but "Warning" is still there.

A copy of my json file:
[AnalysisSettings.json](https://github.com/ironmansoftware/issues/files/14115547/AnalysisSettings.json)

**Comment by pju55** [comment]
Solved - but not sure how.
But enabling/disabling the 3 analysis choices in varrious combinations suddenly made it work persistent ;-)
