### ISSUE TITLE
New-UDApp Logo - not working on HTTP

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#3053]
### Version

4.2.6

### Severity

Visual

### Steps to Reproduce

We plan on using a central repo for our logos / images used in Powershell universal dashboards, but it seems that its not working if we access the .png file over HTTP - if we do it over HTTPS, then its working just fine.

We can access the file from our client using HTTP, and a Invoke-Webrequest from the PSU servers are also able to pull the .png file down.

**Works:**
```
New-UDApp -Title "Home" -Pages $pages -Navigation $Navigation -HeaderColor 'white' -HeaderBackgroundColor "#143c8a" -Logo "https://repo.domain.com/logo-110.png" -NavigationLayout Permanent -HeaderContent {
    New-UDAlert -Severity warning -Text "Version 0.0.1" -Dense
} 
```

**Not working:**
```
New-UDApp -Title "Home" -Pages $pages -Navigation $Navigation -HeaderColor 'white' -HeaderBackgroundColor "#143c8a" -Logo "http://repo.domain.com/logo-110.png" -NavigationLayout Permanent -HeaderContent {
    New-UDAlert -Severity warning -Text "Version 0.0.1" -Dense
} 
```

### Expected behavior

```console
That PSU is able to use the image over HTTP
```

### Actual behavior

```console
Its not able to use it over HTTP
```

**Comment by adamdriscoll** [comment]
@ksl28 Are you hosting PSU on HTTPS? If so, that's why the HTTP resource doesn't work. You'll need to host it on HTTPS as the browser is blocking the unsafe resource.
