### ISSUE TITLE
API: Documentation removed after syntax error in Defintion

### ISSUE THREAD

**Issue by ricoroodenburg** [ironmansoftware/powershell-universal#3056]
### Version

4.2.9

### Severity

High

### Steps to Reproduce

1. Create a new API Documentation.
2. Link some API endpoints to it.
3. Test if it is working.
4. Add the following classes to the documentation definitions.
```
    class SID
    {
        [int]$BinaryLength
        [string]$Value
        [string]$Value
    }
```
5. Save the definition. You'll get a success message "Changes saved!".
6. In the background the documentation is removed. Simply click on the Documentation menu item and you don't see the documentation anymore.

In the notifications area you'll see the following error:
At C:\ProgramData\UniversalAutomation\Repository\.universal\endpointDocumentation.ps1:6 char:9 + [string]$Value + ~~~~~~~~~~~~~~ The member 'Value' is already defined.

### Expected behavior

```console
While the error is valid, the behavior not.
The user should not be allowed to save the definition, a syntax error should be shown.
```

### Actual behavior

```console
* Success message (toast)
* Documentation is removed
* Error in the notifications area
```

**Comment by ricoooww** [comment]
Problem still exists after upgrading tot 4.2.12.
