### ISSUE TITLE
API: Endpoint script gone after linking to a Documentation

### ISSUE THREAD

**Issue by ricoroodenburg** [ironmansoftware/powershell-universal#3057]
### Version

4.2.9

### Severity

Critical

### Steps to Reproduce

When linking a documentation to an existing endpoint, the code / script is be removed.
This is not acceptable.

### Expected behavior

```console
No changed to the code / script.
```

### Actual behavior

```console
The whole content of the code / script is removed.
```

**Comment by adamdriscoll** [comment]
@ricoroodenburg - Cannot reproduce this and may need some more info. 

Do you see anything in the notification drop down regarding errors? Can you send some logs?

**Comment by adamdriscoll** [comment]
I can't reproduce this and haven't heard back so I'm closing. Feel free to update with any more info and I can reopen.
