### ISSUE TITLE
PSU fails to load after update to 4.2.10

### ISSUE THREAD

**Issue by schubfre** [ironmansoftware/powershell-universal#3065]
### Version

4.2.10

### Severity

Critical

### Steps to Reproduce

Update to 4.2.10 on the below mentioned environment
**Downgrading to 4.2.9 works fine as before**

I will send the logfiles via mail

### Expected behavior

```console
Everything works fine
```

### Actual behavior

```console
PowerShell Universal Failed to Load
Failed to load PowerShell Universal. Ask your administrator to refer to the log file for more information
```

### Additional Environment data

Windows Server 2022
SQLite DB
gMSA as service account
https cert from a official CA with a functioning cert path
Update from 4.2.9 to 4.2.10

### Visuals

![error_4 2 10](https://github.com/ironmansoftware/issues/assets/28289080/cc0637c7-95cd-4e20-89cc-b12783acce73)

### Outdated info

Premise:
Error entry in the system log of the server
>Could not retrieve an OCSP response.
>
>   The Failure Reason is: REASON_OCSP_RESPONSE_RETRIEVAL_ERROR
>    The OCSP Url is: http://status.rapidssl.com
>   The previous OCSP response contained the following times:
>      ThisUpdate: ‎1601‎-‎01‎-‎01T00:00:00.000000000Z
>      NextUpdate: ‎1601‎-‎01‎-‎01T00:00:00.000000000Z
>
>The attached data contains the certificate.

When removing the cert config from the appsettings, the problem persists in 4.2.10
I don't know if this system log entry is even relevant to the problem. I get it on my 3.10.2 servers as well and everything works fine there.

Conclusion:
_After speaking with my Active Directory guy, he explained this happens because the server(s) can't access the CRL. This happens, because the server has no internet.
So this error is not relevant at all, because we don't authenticate via certificate, so there is no need for the application to check the CRL. Except something changed how PSU behaves from version 4.2.9 to 4.2.10?_

**Comment by adamdriscoll** [comment]
This is resolved in 4.2.11.
