### ISSUE TITLE
General: Be ISO 27001 compliant

### ISSUE THREAD

**Issue by ricoroodenburg** [ironmansoftware/powershell-universal#3067]
### Summary of the new feature / enhancement

**What is ISO/IEC 27001?**
ISO/IEC 27001 is the world's best-known standard for information security management systems (ISMS). It defines requirements an ISMS must meet.

The ISO/IEC 27001 standard provides companies of any size and from all sectors of activity with guidance for establishing, implementing, maintaining and continually improving an information security management system.

Conformity with ISO/IEC 27001 means that an organization or business has put in place a system to manage risks related to the security of data owned or handled by the company, and that this system respects all the best practices and principles enshrined in this International Standard.

**Why is ISO/IEC 27001 important?**
With cyber-crime on the rise and new threats constantly emerging, it can seem difficult or even impossible to manage cyber-risks. ISO/IEC 27001 helps organizations become risk-aware and proactively identify and address weaknesses.

ISO/IEC 27001 promotes a holistic approach to information security: vetting people, policies and technology. An information security management system implemented according to this standard is a tool for risk management, cyber-resilience and operational excellence.

**Comment by Viajaz** [comment]
Are you suggesting the company gets ISO 27001 certified or that PowerShell Universal becomes more amenable to the ISO 27001 annex A? If it's the later, I think you'd be better off submitting each change you need (to comply with annex) as separate issues.

Eg: #2096 for ISO 27001:2022 A.5.12, A.5.13

**Comment by ricoroodenburg** [comment]
I'm suggesting the company gets ISO 27001 certified :)!

**Comment by Viajaz** [comment]
I think that is a big ask for a company of this size, given the amount of overhead of the time to write the policies and to implement controls as well as the costs involves for the auditing and maintaining governance/risk register tracking, but such a certification would certainly make Ironman Software appear much better in our Supplier Assessments as an ISO 27001 organization ourselves. I would support this if they decided to do this but it's not for the faint of heart. I would actually prefer that they focus on features that let's us implement ISO 27001 controls better.

**Comment by Omzig** [comment]
I vote, NO, to keep costs down.

**Comment by adamdriscoll** [comment]
This is not something that we will be pursuing at this time. We typically use this track for technical issues so discussions of the company structure would be better suited via email.
