### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by TurnItOff-OnAgain** [ironmansoftware/powershell-universal#3073]
### Version

4.2.9

### Severity

Low

### Steps to Reproduce

Admin Console > User Interfaces > Pages > Documentation button (top right) points to this URL

https://docs.powershelluniversal.com/userinterfaces/pages

Which doesn't exist

### Expected behavior

```console
Goes to doc page
```

### Actual behavior

```console
Doc page doesn't exist
```

**Comment by ricoroodenburg** [comment]
I can cofirm this with version 4.2.11 same issue.
