### ISSUE TITLE
When moving a script location, update any references in schedules

### ISSUE THREAD

**Issue by RockoTheeHut** [ironmansoftware/powershell-universal#3076]
### Summary of the new feature / enhancement

When you update a script location any schedule that utilizes it fails. I suppose this would be the same issue for triggers. I would like any references in schedules \ triggers \ etc to be updated when the script location is updated at least through the admin console. I understand that there may be some circumstances where this will be difficult. 

### Proposed technical implementation details (optional)

References to the script are updated. Perhaps something like in set-psuscript that you can set a flag to update references, or a global setting. Not sure how a manual update to the ps1 file could work if you are changing a lot of scripts at once.. there might not be a way to reliably cross referenced. But for a script change through the admin console or using the API / cmdlet this might work.

**Comment by adamdriscoll** [comment]
This should be complete in v5 but I'll double check.
