### ISSUE TITLE
"PowerShell.Language.CSharp" plugin not creating C# environment as documentation states

### ISSUE THREAD

**Issue by RockoTheeHut** [ironmansoftware/powershell-universal#3084]
### Version

4.2.11

### Severity

Low

### Steps to Reproduce

A developer asked about using these.. doesn't look like we can get it to work.

Add "PowerShell.Language.CSharp" to plugins, restart PSU, there is no C# environment per the documentation: "This plugin creates a C#-based environment that can be used to create API endpoints with C# code".

There are no options in the route definition either int he admin console. 

### Expected behavior

```console
Ability to run C# endpoints in a C# environment
```

### Actual behavior

```console
No C# environment
```

### Additional Environment data

4.2.12
Server 2022
SQL 2022
OIDC

**Comment by adamdriscoll** [comment]
This is partially a documentation issue. It should be "PowerShellUniversal.Language.CSharp". That said, while testing this we are resolving the path incorrectly in the C# plugin. It seems that a full path is currently required to get it to work. The path resolve will be fixed in the next version.

**Comment by RockoTheeHut** [comment]
@adamdriscoll That fixed the issue. Glad you mentioned the path, that would have driven me mad lol. Specifying a whole path is simple and at least lets us move forward. Thanks!
