### ISSUE TITLE
Triggers are duplicated when using PSUHeader

### ISSUE THREAD

**Issue by schubfre** [ironmansoftware/powershell-universal#3090]
### Version

4.2.12

### Severity

High

### Steps to Reproduce

On a MSSQL backed application two-node "cluster":
Create one or two git sync trigger(s) in the PSUHeader region; commit and push in your repository and git sync in PSU.
Change something in the header region - for example change the Computer parameter from All to $ENV:COMPUTERNAME - commit, push and git sync.

The duplicated triggers are dangerous, because they are real triggers and not some display bug.
Restarting the service on all application nodes fixes the problem and removes all duplicates.

Related to #3082 ?

EDIT: The behaviour is the same on a two node MSSQL backed environment or a single node SQLite backed environment

### Expected behavior

```console
Only the respective parameters change; the count of triggers stays the same and nothing gets duplicated
```

### Actual behavior

```console
The triggers get duplicated - one set of triggers with the old parameters and one set of triggers with the new parameters
```

### Additional Environment data

Windows Server 2022
MSI install
MSSQL AAG DB
Two application nodes
Azure DevOps git

**Comment by adamdriscoll** [comment]
This was the same issue as 3082.
