### ISSUE TITLE
{scriptPath} Not Working (Python as Environment)

### ISSUE THREAD

**Issue by bscharff** [ironmansoftware/powershell-universal#3091]
### Version

4.2.12

### Severity

Low

### Steps to Reproduce

PSU seems to not be dynamically replacing {scriptPath} when running a script with a Python environment (set up per https://blog.ironmansoftware.com/powershell-universal-python/ )
Another user is reporting the same issue here:  https://forums.ironmansoftware.com/t/python-in-psu-general-questions/9986/7

Screenshots of setup are below.  For reference, I also tried omitting the full path to python.exe

Contents of script test.py:
print("Goodbye, World!")

### Expected behavior

```console
Goodbye, World!
```

### Actual behavior

```console
[information] C:\Program Files\Python\python.exe: can't open file 'C:\\ProgramData\\UniversalAutomation\\Repository\\{scriptPath}': [Errno 2] No such file or directory
```

### Additional Environment data

Windows Server 2022 with latest Python as of Feb 2nd, 2024

### Visuals

<img width="776" alt="image" src="https://github.com/ironmansoftware/issues/assets/1313397/33d70754-676a-41d9-9c03-e148e691ac40">
<img width="731" alt="image" src="https://github.com/ironmansoftware/issues/assets/1313397/95973ed9-7f98-4ebe-b5e6-61ba7493b0a6">
<img width="219" alt="image" src="https://github.com/ironmansoftware/issues/assets/1313397/2699e53e-d4c8-48e4-b098-008128da4d90">

**Comment by adamdriscoll** [comment]
@bscharff You need to enable Minimal Job Environment

**Comment by adamdriscoll** [comment]
I have verified this is working when minimal environment is checked.

**Comment by bscharff** [comment]
LOL yup, you're right.
You might want to add a little note on that blog page "Don't forget to check the Minimal Job Environment option!"
