### ISSUE TITLE
Expiring/complex passwords for local users

### ISSUE THREAD

**Issue by schubfre** [ironmansoftware/powershell-universal#3098]
### Summary of the new feature / enhancement

As a user I want to be able to configure a global password expiration policy for local users. It would also help if there were complexity settings regarding the password.

**Comment by bscharff** [comment]
It's probably better to use external authentication instead.  SAML, OAUTH, AD, etc.

**Comment by schubfre** [comment]
There are use-cases, where it isn't possible to use other providers. 
For example if you don't want any chance of lateral movement and want your local accounts managed by cyberark where every step is recorded in accord to a zero-trust policy.

Anyway, it should be common security practice to not have users where a password with the value 'aaa123' is possible and where a password expires after a set amount of time.
