### ISSUE TITLE
Filter out scheduled jobs under /admin/automation/jobs

### ISSUE THREAD

**Issue by mikedhanson** [ironmansoftware/powershell-universal#3106]
### Summary of the new feature / enhancement

https://forums.ironmansoftware.com/t/filter-out-scheduled-jobs/9036

I think it would be very helpful to be able to have more advanced filtering on the jobs page. This could include filtering out the scheduled jobs, by tags, users, environments, etc.

### Proposed technical implementation details (optional)

Create more advanced filtering for jobs.

**Comment by adamdriscoll** [comment]
You can filter out scheduled jobs in v4. We have an issue open for this for v5 to improve it further: #618
