### ISSUE TITLE
The given key 'PowerShellUniversal.GitBundle' was not present in the dictionary.

### ISSUE THREAD

**Issue by bscharff** [ironmansoftware/powershell-universal#3108]
### Version

4.2.12

### Severity

Low

### Steps to Reproduce

Trying to enable basic Git functionality.
Go to Settings > Git >  + Git Settings
Only check "Bundle Git Repository in Database"
Click OK

### Expected behavior

```console
Success
```

### Actual behavior

```console
Error message:
Git Synchronization Failed
The given key 'PowerShellUniversal.GitBundle' was not present in the dictionary.
```

### Additional Environment data

Running PSU v4.2.12 on Windows Server 2022
Installed Git v2.43.0 using 64-bit Git for Windows Setup using all defaults (from https://git-scm.com/download/win)
Confirmed git is in PATH, git is executable from cmd, powershell, pwsh when directly RDP'ing to the server.
Rebooted Windows just in case :)

I Google'd "PowerShellUniversal.GitBundle" and got absolutely no results :(

### Visuals

<img width="454" alt="2024-02-07 12_04_53-PowerShell Universal" src="https://github.com/ironmansoftware/issues/assets/1313397/7ee6adb3-b628-4d10-b9e7-e8594c4f0c4a">
<img width="712" alt="2024-02-07 12_05_16-PowerShell Universal" src="https://github.com/ironmansoftware/issues/assets/1313397/6be0bfaa-d38e-484d-a4fd-05309374c64a">

**Comment by adamdriscoll** [comment]
Are you using something besides SQL? If so, I'm curious for your use case for this. Typically, git is useful for sharing scripts across nodes but neither LiteDB nor SQLite databases are usually shared in PSU setups.

**Comment by bscharff** [comment]
Hi there!  I'm using SQLite.  My only goal is change tracking.  I know I could set it up with a Github repo but really don't need that level of tracking, ya know?

**Comment by adamdriscoll** [comment]
That makes sense. We should be able to get this fixed up for that case.
