### ISSUE TITLE
Add a site base url

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3110]
### Summary of the new feature / enhancement

we need the url for the psu instance

eg
$RootUrl = "https://something.com/siteName"

**Comment by MikeShepard** [comment]
this would be perfect...
then, I can say  invoke-restmethod -uri $rootURL/api/SomeRoute 

And it will work when I migrate the code between instances.

**Comment by Omzig** [comment]
@adamdriscoll, can we add this to .14?

**Comment by adamdriscoll** [comment]
The variable is $RootUrl

**Comment by Omzig** [comment]
Duplicate: 
- https://github.com/ironmansoftware/issues/issues/2035
