### ISSUE TITLE
Schedules - Computer property should allow more than a single computer name 

### ISSUE THREAD

**Issue by mikedhanson** [ironmansoftware/powershell-universal#3112]
### Summary of the new feature / enhancement

![image](https://github.com/ironmansoftware/issues/assets/15201245/9cbde60b-ed01-4d81-9cb9-70cb4f525cda)

It would be very cool to be able to define computer groups in variables and have that to pass into the computer param. 

### Proposed technical implementation details (optional)

Example:

```powershell
$Parameters = @{
	Cron = "0 0 1 * *"
	Script = "script.ps1"
	TimeZone = "America/Chicago"
	SNInstance = 'Dev'
	Name = "Checks to make sure DHCP addresses match addresses in location table in SN"
	Computer = "Computer1", "Computer2, 
}
New-PSUSchedule @Parameters
```

**Comment by adamdriscoll** [comment]
This can be achieved with computer groups: https://docs.powershelluniversal.com/platform/computers#computer-groups
