### ISSUE TITLE
Issues with App Pages (Duplicate\Fail to Delete)(

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3120]
### Version

4.2.12

### Severity

Low

### Steps to Reproduce

Multiple default pages issue/bug:
1) Deploy clean docker (4.2.12)
2) UI > App > New App > 
      Name: app
      Desc: app
      URL: /app
      Template: multiple pages
3) View the pages of the app
4) UI > App > New App
5) Delete app
6) UI > App > New App > (Same details)
      Name: app
      Desc: app
      URL: /app
      Template: multiple pages
7) View the pages of the app 
8) You should now have 2 copies of groups/home/users

Cant delete default pages issue/bug:
1) Deploy clean docker (4.2.12)
2) UI > App > New App > 
      Name: app
      Desc: app
      URL: /app
      Template: multiple pages
3) UI > App > Name > Pages
4) Try to delete any of the defaults with the red delete button

### Expected behavior

```console
No duplicate pages and delete pages.
```

### Actual behavior

```console
Duplicate pages and cannot delete some pages.
```

**Comment by pbknl** [comment]
Hi Adam,

Thanks for the commit.
I just wanted to let you know the multiple-pages part of this issue is fixed.
But the unable to delete default (Home/Groups/Users) pages is still not working for me.

Cheers,
Peter

**Comment by pbknl** [comment]
@adamdriscoll
