### ISSUE TITLE
Force event attributes to be passed down as strings

### ISSUE THREAD

**Issue by ClarkRSD** [ironmansoftware/powershell-universal#3121]
### Summary of the new feature / enhancement

It would be nice if there was the ability to "force" the passing of a string down into an attribute for specific events. For example, if I want to pass down `onclick` as an attribute rather than a script block that runs server-side, I should not be restricted in that ability.

### Proposed technical implementation details (optional)

When making events with `New-UDElement` and passing an `Attributes` hashtable it would be nice if we could have `onInput`, `onClick`, `onKeyPress`, etc. have the ability to be passed down as raw JavaScript if we so choose that can be ran client-side.

Current behavior:
```pwsh
New-UDApp -Title 'PowerShell Universal' -Pages @(
    New-UDPage -Blank -Url "home" -Title "Home" -Content {
        New-UDElement -Tag input -Id "Textbox" -Content {} -Attributes @{
            type = 'text'
            onInput = "alert('Hello World!')"
        }
    }
)
```
![image](https://github.com/ironmansoftware/issues/assets/98977894/90f1fe05-094d-45fc-9123-4418088f4594)

Expected behavior:
```pwsh
New-UDApp -Title 'PowerShell Universal' -Pages @(
    New-UDPage -Blank -Url "home" -Title "Home" -Content {
        New-UDElement -Tag input -Id "Textbox" -Content {} -Attributes @{
            type = 'text'
            onInput = "alert('Hello World!')"
        }
    }
)
```
![image](https://github.com/ironmansoftware/issues/assets/98977894/6537602a-acd1-4eb1-9f3a-a78d201394e2)

I know the expected way of doing it is to do a script block and pass it down as `Invoke-UDJavaScript`, but the whole reason I want the proposed feature is to force client-side input.
```pwsh
New-UDApp -Title 'PowerShell Universal' -Pages @(
    New-UDPage -Blank -Url "home" -Title "Home" -Content {
        New-UDElement -Tag input -Id "Textbox" -Content {} -Attributes @{
            type = 'text'
            onInput = {
                Invoke-UDJavaScript "alert('Hello World!')"
            }
        }
    }
)
```

Sometimes when using `onInput` and `onKeyPress`, if the user types fast enough, the events get behind and take a few seconds to catch up, which can be jarring for some users. Forcing it to be passed down as a string can allow the processing to be done client-side and these are no longer issues.

There is also a workaround in that I can just use `New-UDHTML` to pass it down as a string, but this then forces me to then use `Invoke-UDJavaScript` if I want to interact at all with that particular element:

```pwsh
New-UDApp -Title 'PowerShell Universal' -Pages @(
    New-UDPage -Blank -Url "home" -Title "Home" -Content {
        New-UDHtml -Markup '<input type="text" oninput="alert(''Hello World!'')" id="Textbox">' -Id "Textbox"

        New-UDElement -Tag button -Id "Button" -Content {"Click me!"} -Attributes @{
            onClick = {
                $Output = Get-UDElement -Id "Textbox" # returns $null

                Show-UDToast " $($Output | ConvertTo-Json)"
            }
        }
    }
)
```
Note: the `-Id "Textbox"` argument with `New-UDHTML` doesn't work at all in my experience. I'm not sure if I'm using it incorrectly (My apologies if there's already a bug report on this) but I was unable to register anything doing it this way. The enclosed HTML content gets enclosed inside of a parent div as well, which I'm not sure if this is expected behavior or not.
![image](https://github.com/ironmansoftware/issues/assets/98977894/248e4085-08b6-4281-8b44-0c20e1d5894d)

I'm not sure if my proposed solution would work, but this suggestion was proposed as the most straight-forward solution that I could think of. If it's preferred that there are separate defined attributes inside of the hashtable that can then be converted down that way, I'm sure that would work too, but I figured it would be fairly straight forward to parse the key's value as either a string or a script block with the `-is` and `-isnot` operators.

**Comment by adamdriscoll** [comment]
You'll be able to do this with New-UDEndpoint.

```powershell
        New-UDElement -Tag input -Id "Textbox" -Content {} -Attributes @{
            type = 'text'
            onInput = New-UDEndpoint -JavaScript "alert(e.data)"
        }
```
