### ISSUE TITLE
site without / does not work

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3134]
### Version

4.2.12

### Severity

Medium

### Steps to Reproduce

when i visit the websites main page, like a normal website it says page can't be found

Visit:
- https://myserver.com

### Expected behavior

```console
view site
```

### Actual behavior

```console
this myserver.com page can't be found
```

### Additional Environment data

IIS: Nested

### Workaround
Visit:
- https://myserver.com/

### Suggestion
Create a way to tell the server what the default page is like / is the default if you don't tell it anything?

**Comment by Omzig** [comment]
@adamdriscoll, maybe if the dashboard had a -Default then / wouldn't matter in the path?

**Comment by adamdriscoll** [comment]
I can't reproduce this in a normal kestrel site. Is this in IIS and do you have some sort of default route set (dashboard, role-based)?

**Comment by Omzig** [comment]
> Is this in IIS and do you hav

yes this is IIS......... :(

**Comment by adamdriscoll** [comment]
I can't reproduce this in IIS either. 

```
 adamr    ~   0ms⠀ invoke-webrequest http://localhost

StatusCode        : 200
StatusDescription : OK
Content           : <!doctype html><html lang="en"><head><base href="/"><meta charset="utf-8"/><meta name="viewport"
                    content="width=device-width,initial-scale=1"/><meta http-equiv="Pragma" content="no-cache"/><meta
                    http-…
RawContent        : HTTP/1.1 200 OK
                    Transfer-Encoding: chunked
                    Vary: Accept-Encoding
                    Server: Microsoft-IIS/10.0
                    Date: Thu, 07 Mar 2024 11:25:52 GMT
                    Content-Type: text/html

                    <!doctype html><html lang="en"><head><ba…
Headers           : {[Transfer-Encoding, System.String[]], [Vary, System.String[]], [Server, System.String[]], [Date,
                    System.String[]]…}
Images            : {}
InputFields       : {}
Links             : {}
RawContentLength  : 936
RelationLink      : {}
```

Visiting http://localhost serves my website.

**Comment by Omzig** [comment]
> I can't reproduce this in IIS either.
> 
> ```
>  adamr    ~   0ms⠀ invoke-webrequest http://localhost
> 
> StatusCode        : 200
> StatusDescription : OK
> Content           : <!doctype html><html lang="en"><head><base href="/"><meta charset="utf-8"/><meta name="viewport"
>                     content="width=device-width,initial-scale=1"/><meta http-equiv="Pragma" content="no-cache"/><meta
>                     http-…
> RawContent        : HTTP/1.1 200 OK
>                     Transfer-Encoding: chunked
>                     Vary: Accept-Encoding
>                     Server: Microsoft-IIS/10.0
>                     Date: Thu, 07 Mar 2024 11:25:52 GMT
>                     Content-Type: text/html
> 
>                     <!doctype html><html lang="en"><head><ba…
> Headers           : {[Transfer-Encoding, System.String[]], [Vary, System.String[]], [Server, System.String[]], [Date,
>                     System.String[]]…}
> Images            : {}
> InputFields       : {}
> Links             : {}
> RawContentLength  : 936
> RelationLink      : {}
> ```
> 
> Visiting http://localhost serves my website.

# Bad:
![image](https://github.com/ironmansoftware/issues/assets/1987296/63f7d67d-fb3f-4db2-afe0-e62ba65ca59a)

# Good:
![image](https://github.com/ironmansoftware/issues/assets/1987296/4a7e5570-811b-4618-bdea-3f8d26e38b25)

## I cannot remove the / for the dashboard:
![image](https://github.com/ironmansoftware/issues/assets/1987296/f50a06f6-f589-4660-a5db-c7a1fad7634d)

Ugg, maybe this is a support case since i don't know what i am doing, but i have never been quite able to get non / dashboards to work. @adamdriscoll, quick call?

**Comment by adamdriscoll** [comment]
Let try with a nested IIS site. 

EDIT: I can reproduce this when I set a / in a dashboard URL

**Comment by adamdriscoll** [comment]
Got it!

**Comment by Omzig** [comment]
IT WORKS!
