### ISSUE TITLE
Surface Event Hub Client Installer to main download page

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3152]
### Summary of the new feature / enhancement

as a user, i am unable to quickly find the event hub msi

### Proposed technical implementation details (optional)

surface a link to https://ironmansoftware.com/powershell-universal/downloads

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/powershell-universal-4-2-9/10216/2

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/event-hub-client-installer-link-download/10407/2

**Comment by Omzig** [comment]
I CAN FIND IT! happy days!!!!!!!!! ty @adamdriscoll 

![image](https://github.com/ironmansoftware/issues/assets/1987296/7af7a299-ed92-4922-b95b-ec14d4b319b9)
