### ISSUE TITLE
Event Hub Client Installer does not 100% install

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3153]
### Version

4.2.12

### Severity

Low

### Steps to Reproduce

when installing the client hub, the folders and files under %ProgramData%\PowerShellUniversal are not created.
https://docs.powershelluniversal.com/api/event-hubs#event-hub-client-installer

### Expected behavior

```console
create folders and files under %ProgramData%\PowerShellUniversal
```

### Actual behavior

```console
%ProgramData% does not have any folders that are normally there during a regular MSI install
```

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/1987296/d9eb6a4e-d968-4876-948e-cb4288131179)

**Comment by adamdriscoll** [comment]
This is by design. We could update the installer to ask for this stuff but it's just a manual process at this time. I've updated the docs to indicate this.
