### ISSUE TITLE
stepper Validation does not work in live doc

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3155]
### Version

4.2.12

### Severity

Low

### Steps to Reproduce

when i use the **live** documentation to see how the Validation works, it doesn't validate

### Expected behavior

```console
validation
```

### Actual behavior

```console
no validation
```

### Additional Environment data

IIS: Nested

**Comment by adamdriscoll** [comment]
I can't reproduce this either. I took the example right from the docs. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/455bcd5f-faf1-4266-929f-76c7dffb2a1e)


```
New-UDStepper -Steps {
    New-UDStep -OnLoad {
        New-UDElement -tag 'div' -Content { "Step 1" }
        New-UDTextbox -Id 'txtStep1' -Value $EventData.Context.txtStep1
    } -Label "Step 1"
    New-UDStep -OnLoad {
        New-UDElement -tag 'div' -Content { "Step 2" }
        New-UDElement -tag 'div' -Content { "Previous data: $Body" }
        New-UDTextbox -Id 'txtStep2' -Value $EventData.Context.txtStep2
    } -Label "Step 2"
    New-UDStep -OnLoad {
        New-UDElement -tag 'div' -Content { "Step 3" }
        New-UDElement -tag 'div' -Content { "Previous data: $Body" }
        New-UDTextbox -Id 'txtStep3' -Value $EventData.Context.txtStep3
    } -Label "Step 3"
} -OnFinish {
    New-UDTypography -Text 'Nice! You did it!' -Variant h3
    New-UDElement -Tag 'div' -Id 'result' -Content {$Body}
} -OnValidateStep {
    $Context = $EventData
    if ($Context.CurrentStep -eq 0 -and $Context.Context.txtStep1 -eq 'bad')
    {
        New-UDValidationResult 
    }
    else
    {
        New-UDValidationResult -Valid 
    }
}
```

**Comment by Omzig** [comment]
from the /doc
![image](https://github.com/ironmansoftware/issues/assets/1987296/d7912398-6389-40ba-892a-366ab6cd2f27)

![image](https://github.com/ironmansoftware/issues/assets/1987296/1a1367ff-1489-403a-a4ca-b102f2e7cbdd)

**Comment by Omzig** [comment]
> I can't reproduce this either. I took the example right from the docs.
> 
> ![image](https://private-user-images.githubusercontent.com/1256531/310561112-455bcd5f-faf1-4266-929f-76c7dffb2a1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDAzODcsIm5iZiI6MTcwOTc0MDA4NywicGF0aCI6Ii8xMjU2NTMxLzMxMDU2MTExMi00NTViY2Q1Zi1mYWYxLTQyNjYtOTI5Zi03NmM3ZGZmYjJhMWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMTU0ODA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjA3M2Y1ZTkzNzEzMGIwZDZmOWFjZDZiZWFkYjllNDQ1ZGVkOWM2MDFiOTcxOGVmOTllOWZmNzUzMzkzNDU0ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D_62hTNmCFduXHBy9lmTuVhAXBVAJpgpHAwh8eKRJTo)
> 
> ```
> New-UDStepper -Steps {
>     New-UDStep -OnLoad {
>         New-UDElement -tag 'div' -Content { "Step 1" }
>         New-UDTextbox -Id 'txtStep1' -Value $EventData.Context.txtStep1
>     } -Label "Step 1"
>     New-UDStep -OnLoad {
>         New-UDElement -tag 'div' -Content { "Step 2" }
>         New-UDElement -tag 'div' -Content { "Previous data: $Body" }
>         New-UDTextbox -Id 'txtStep2' -Value $EventData.Context.txtStep2
>     } -Label "Step 2"
>     New-UDStep -OnLoad {
>         New-UDElement -tag 'div' -Content { "Step 3" }
>         New-UDElement -tag 'div' -Content { "Previous data: $Body" }
>         New-UDTextbox -Id 'txtStep3' -Value $EventData.Context.txtStep3
>     } -Label "Step 3"
> } -OnFinish {
>     New-UDTypography -Text 'Nice! You did it!' -Variant h3
>     New-UDElement -Tag 'div' -Id 'result' -Content {$Body}
> } -OnValidateStep {
>     $Context = $EventData
>     if ($Context.CurrentStep -eq 0 -and $Context.Context.txtStep1 -eq 'bad')
>     {
>         New-UDValidationResult 
>     }
>     else
>     {
>         New-UDValidationResult -Valid 
>     }
> }
> ```

the documentation site does not match the live doc ;)

**Comment by adamdriscoll** [comment]
Will take a look at the live docs. 😵‍💫

**Comment by Omzig** [comment]
> Will take a look at the live docs. 😵‍💫

LOL, live doc uses $eventdata.step instead of .currentstep and it uses 1 instead of 0, should stepper match the steps or be array based?
