### ISSUE TITLE
Setup Cmdlets

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#316]
We need to revisit the "getting started" experience. We should have cmdlets that can download the proper ZIP or MSI, unblock the files if necessary, install into IIS if desired, etc. It's a PowerShell environment and should be easily installed from PowerShell. 

We also have too many ways to install right now. It should always be a single command. 

# Requirements

## Install-PSUServer should install and start PSU in a single command. 

This should work on any platform and get the system installed and persistent with a single command. Windows should install as a service. Linux and Mac should install so they start up with the system. 

```
Install-PSUServer 
```

## Set PSModulePath correctly

Lot's of people have issues with IntelliSense. When you install the PSU server via the cmdlet, it should update PS module path so the latest framework and the Universal cmdlets are available. 

## IIS Configuration

There should be a parameter set of setting up an IIS site. It doesn't necessarily need to get it completely configured, but it should do the following. 

- Accept -IISWebsiteName as a single, mandatory parameter 
- Check of admin privileges
- install the .NET Core hosting package if it doesn't exist
- Copy files for Universal and unblock them
- Create a website based on the specified name
- Website should be up and running after this is done

## Upgrade-PSUServer

We need to add a new module to do upgrades. We can check for certain things on the environment for how to do the upgrade. We should have a parameter set that can upgrade an IIS Website. 

## Save-PSUServer

In offline environments, we should provide commands to download the proper server files so they can be used offline. Install-PSUServer should accept an installation package path. 

```
Save-PSUServer -Path .\myFiles
Install-PSUServer -ServerPackagePath .\myFiles
```

**Comment by Viajaz** [comment]
I think having information on the benefits and disadvantages of the different methods would be useful too, perhaps recommendations depending on the environment?
