### ISSUE TITLE
New cmdlet - New-UDConfirm

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#3160]
### Summary of the new feature / enhancement

As a user, I want to be able to prompt the user for an ok/cancel kind of decision without having to write my own modal code

### Proposed technical implementation details (optional)

Here's a prototype, which doesn't include any styling and is a bit hacky because I'm outside of the black box:

```
function Get-UDConfirm {
    [CmdletBinding()]
    Param($Title, $Message)
    $page:output=$false
    $page:ModalShowing=$true
    Show-UDModal -Header { $Title } -Content {
        New-UDTypography $Message
    } -Footer {
        New-UDButton -Text "Yes" -Color error -OnClick {   $page:ModalShowing=$false;$page:Output=$true;Hide-UDModal; }
        New-UDButton -Text No -OnClick {
            Hide-UDModal
            $page:ModalShowing=$false;$page:Output=$false;
        }
    } -Persistent
    while($page:modalshowing){
        start-sleep -Milliseconds 100
    }
    return $page:output
}
```

**Comment by MikeShepard** [comment]
usage would be like this:

```
if(Get-UDConfirm -title "Delete?" -message "do you want to delete record # $recordNumber"){
  remove-databaserecord -id $recordNumber
}
```

**Comment by Omzig** [comment]
woooooohooooooo, it brings back memory's of winforms!

i love out of the box functionality that pairs up with other tech ;)

```
string message = "Simple MessageBox";
MessageBox.Show(message);
```

i vote for New-UDMessageBox :P

**Comment by adamdriscoll** [comment]
Should it be Show-UDMessageBox?

**Comment by MikeShepard** [comment]
That would be fine....just having it built in and less "gross" than what I wrote :-)

**Comment by Viajaz** [comment]
Make sure to include in the docs the situations where it's blocking nature would be inappropriate.
@adamdriscoll

**Comment by MikeShepard** [comment]
The blocking nature of my code wasn't an essential feature, just necessary due to how I implemented it.

**Comment by Omzig** [comment]
we should add a flag or something that says -Required

**Comment by adamdriscoll** [comment]
I think we could just integrate with the existing prompt for choice UI. 

```
$title = 'Confirm'
$question = 'Do you want to continue?'
$choices = 'Yes', 'No'

$decision = $Host.UI.PromptForChoice($title, $question, $choices, 1)
if ($decision -eq 0) {
    Write-Host 'Your choice is Yes.'
}
else {
    Write-Host 'Your choice is No.'
}
```

**Comment by MikeShepard** [comment]
That looks promising...an official cmdlet would be awesome.
