### ISSUE TITLE
Nested modal implementation

### ISSUE THREAD

**Issue by kodifan** [ironmansoftware/powershell-universal#3163]
### Summary of the new feature / enhancement

Since nested modals  are available in react material ui - it would be handy if this feature will be implemented. 
Modals are widely used but sometimes it necessary to display some additional information and here modals is the best solution if this information is little more complicated than a simple phrase. 
But since you cannot display modal over modal - its hard to be done it another way.

### Proposed technical implementation details (optional)

i guess the same as react implementation.

**Comment by DJS91** [comment]
+1 for this

**Comment by kodifan** [comment]
@adamdriscoll any updates on this idea ? really miss that function in some circumstances

**Comment by kodifan** [comment]
Ive just installed 5.1.0 and tested this implementation.
And its working, its fine but as usual there is always some things to make it better.
Now this new modal closes previous, and when new is closed, previous is restored.
In mui react modal is displayed over modal with yet another level of fading.
I like better mui approach, some might like current way.
It will be nice if we can decide how;)

**Comment by kodifan** [comment]
Hello @adamdriscoll  
Have you consider changing default behavior of how the next modal is showing ? (from closing old one and showing new one, to dimming screen with old modal and showing new one). Or maybe this can be configurable ? 😄 
Technically it should be possible because read-host command produces its own new window (which is modal as far as i can see) over already displayed modal.
