### ISSUE TITLE
Make the $Query hashtable case insensitive

### ISSUE THREAD

**Issue by liamjpeters** [ironmansoftware/powershell-universal#3169]
### Summary of the new feature / enhancement

We utilise the feature of Powershell Universal whereby URL query parameters are automatically mapped to the `$Query` `[hashtable]` when loading a page. 

We lookup to see if a particular key is present in the `[hashtable]` – if it is, we may take some action based on the value.

We’ve recently noticed that this `$Query` `[hashtable]` is case sensitive. 

We’d like you to consider **making the `$Query` `[hashtable]` case insensitive**.

Urls and the web are not typically case sensitive. 

Windows, and Powershell itself, are not case sensitive (in most instances). 

This change would only impact the keys and key-lookup - it would not impact the casing of the value - which we appreciate could be important.

### Proposed technical implementation details (optional)

I’m unclear on the wider ramifications but should hopefully be something as simple as passing in a `StringComparer` when making the Query `hashtable` on the C# side.

```c#
var Query = new Hashtable(StringComparer.InvariantCultureIgnoreCase);
```

**Comment by MikeShepard** [comment]
According to this, the schema should be case-insensitive:
https://stackoverflow.com/questions/24699643/are-query-string-keys-case-sensitive
