### ISSUE TITLE
Editing any App page reloads all Apps

### ISSUE THREAD

**Issue by HansenRene** [ironmansoftware/powershell-universal#3172]
### Version

4.2.13

### Severity

Low

### Steps to Reproduce

have 2 apps with auto reload - edit anything in App 1 or 2 - and both apps will reload their content

### Expected behavior

```console
Ideally only apps with changes should reload, as the current behavior can cause quite the disturbance on larger sites.
```

### Actual behavior

```console
any app will reload all content.
```

**Comment by adamdriscoll** [comment]
Same as https://github.com/ironmansoftware/issues/issues/3174
