### ISSUE TITLE
App Pages: Navigation Icons are too near to the Page Title

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#3173]
### Version

4.2.13

### Severity

Low

### Steps to Reproduce

```
New-UDApp -Title 'My Super App' -Pages @(
    Get-UDPage -Name 'Page1'
    Get-UDPage -Name 'Page2'
    Get-UDPage -Name 'Page3'
)

```
Then, using the Page Properties function, specify an icon.

The result, as always: "A picture tells more than a 1000 words :-)"

![image](https://github.com/ironmansoftware/issues/assets/11975745/9a4550af-774d-4acf-877a-6a2e0022ff99)

Thanks a lot for fixing this visual thing if possible :-)

### Expected behavior

```console
There should be some space between the icon and the page text
```

### Actual behavior

```console
There's no space at all between the icon and the page text.
```

**Comment by adamdriscoll** [comment]
Same as #3174

**Comment by adamdriscoll** [comment]
Wrong one... sorry

**Comment by donlent** [comment]
Apparently related to this one but not overridable using the method mentioned on the forum:
https://forums.ironmansoftware.com/t/new-udlist-spacing/9656/9

**Comment by donlent** [comment]
Another Update which may be helpful.
The only current way to workaround the issue a little bit is by directly modifying the Pages ps1 files and doing something like this as an example:

```
New-UDPage -Url "/Home" -Name "Home" -Content {
    # Use Get-UDPage -Name 'Home' to use this page in your dashboard

} -Title "`tHome" -Icon @{
    name = 'home'
    size = "lg"
    style = @{"min-width" = "30px"}
}
```

The problem?
Whenever you modify the code using the PSU internal Code Editor this section will be overwritten. So either you perform these modifications as your very last change (at the end of every code update) or maybe it will be fixed by the team, so that we can specify all wanted details directly in the properties pages in a future update... :-)
