### ISSUE TITLE
Invalid configuration: endpoints.psi

### ISSUE THREAD

**Issue by SVBWMarkus** [ironmansoftware/powershell-universal#3177]
### Version

Other Please Specify

### Severity

High

### Steps to Reproduce

i have updated the system to a newer verison (actual on 4.2.14 (8273398923)) and since then my endpoints.ps1 produces the folowing error:

Object reference not set to an instance of an object.

### Expected behavior

```console
api calls working

New-PSUEndpoint -Url "/hardewareausgabe" -Method @('POST') -Endpoint {
$script = Get-PSUScript -Name "Hardwareausgabe.ps1"
$scriptrespones = Invoke-PSUScript -Id $script.Id -Personalnr $personalnr
} -Environment "Windows PowerShell 5.1" -PersistentLog 
New-PSUEndpoint -Url "/sachkontensalden" -Method @('POST') -Endpoint {
$script = Get-PSUScript -Name "Sachkontensalden.ps1"
$scriptrespones = Invoke-PSUScript -Id $script.Id -periode $periode
} -Environment "Windows PowerShell 5.1" -PersistentLog
```

### Actual behavior

```console
api calls not working
```

### Additional Environment data

4.2.14 (8273398923)

### Visuals

![PowershellServerFehler 1](https://github.com/ironmansoftware/issues/assets/163397311/9bf36a66-ae1b-4e34-bde5-2ed37e89a628)

**Comment by adamdriscoll** [comment]
Can you please check in the system log for this error? It will provide more context.

**Comment by SVBWMarkus** [comment]
Sorry, i can not fetch any more information for you.

I tried the following:
- create a new endpoint -> same error
- removed powershelluniversal from the server an installed it again -> create new endpoint from the scratch -> same error

**Comment by SVBWMarkus** [comment]
on the webpage i got the folloging error:

This is an error with the configuration script for this page. You will need to correct the issue manually before continuing.
Object reference not set to an instande of an object.

**Comment by adamdriscoll** [comment]
If you click Platform \ Logging do you see these errors listed there?

**Comment by adamdriscoll** [comment]
I have another user experiencing a similar problem. If you change the environment for these endpoints to PowerShell 7 do they work? I cannot reproduce this myself.

**Comment by adamdriscoll** [comment]
I still can't reproduce this on the latest 4.2.14. Going to remove from this milestone for now.

**Comment by adamdriscoll** [comment]
Closing as I haven't been able to reproduce or heard back. Please comment if you are still experiencing this.
