### ISSUE TITLE
No Output on UI Page

### ISSUE THREAD

**Issue by Marvin-Becker** [ironmansoftware/powershell-universal#3192]
### Version

4.2.13

### Severity

High

### Steps to Reproduce

I have created a UI Page (not App/Dashboard) for my colleagues to use my scripts outside the admin console. The page uses authentication and the scripts are linked with tags through access control. The “Show Output” is checked and result type is text.
FYI: I am using PowerShell 7 environment as default.
I can trigger the scripts perfectly and they are running as desired.

My Problem is: there is no reaction on the Page for the user (also not for Admins). We cannot see anything happen when we click on the run button. Even not the texts that I prepared like “Success Title” or “Failure Title” are shown. Simply nothing…

Does anybody has an idea what I am doing wrong?

Thanks in advance!
Marvin

### Expected behavior

```console
Showing output of the script.
Show if run was successful or failed.
```

### Actual behavior

```console
Script runs properly as I can see in logs.
But nothing happens on the page for the user, no reaction at all.
```

**Comment by adamdriscoll** [comment]
I can't reproduce this. 

Here is my form setup. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/82a8730f-1153-4b17-819a-2e78d771218b)

![image](https://github.com/ironmansoftware/issues/assets/1256531/35466f13-5c01-46d0-9e31-7d6e6c185c84)

My script just returns a hello world object. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/bd49b057-8d28-49e9-a37b-20315f33e262)

Here's the XML that was created for this page. Maybe if you share yours we can see the difference. 

```
<?xml version="1.0" encoding="utf-8"?>
<Page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" Id="1" Name="Page" Authenticated="true" ShowInNavigation="true" ShowNavigation="true" HideHeader="false" HideTitle="false" Url="/url21">
  <Components>
    <Form Id="a6133dfd-d4e0-440a-9297-323b68d48071" Title="Form" Description="Test" SuccessTitle="Test" ShowOutput="false" ShowProgress="false" ResultType="Text" CanReset="false">
      <Target Name="Test.ps1" Type="script" />
    </Form>
  </Components>
  <Layout>
    <Lg>
      <LayoutItem Id="a6133dfd-d4e0-440a-9297-323b68d48071" X="0" Y="0" W="10" H="10" />
    </Lg>
  </Layout>
  <AccessControls>None</AccessControls>
</Page>
```

**Comment by adamdriscoll** [comment]
Please let me know if this is still and issue and I can reopen this.
