### ISSUE TITLE
Scheduled job never runs

### ISSUE THREAD

**Issue by brettfire** [ironmansoftware/powershell-universal#320]
**Describe the bug**
Next execution of scheduled script shows as Jan 1, 1901 at 12:00 AM.
Schedules.ps1 looks like this: 
```
New-PSUSchedule -Cron "*/30 * * * *" -Script "[Scheduled] Gather Inventory" -TimeZone "America/New_York" -Name "Gather Inventory"
```
I used the UI to schedule an existing script at 30 min intervals. The job never runs.

**To Reproduce**
1. Have existing script.
2. Go to Schedules -> Create New Schedule. Under the "Simple" tab, select existing script and set "Time" to "Every 30 Minutes"
3. Schedule shows in listing but never runs. Next execution of scheduled script shows as Jan 1, 1901 at 12:00 AM.
 
I also tested the "continuous" scheduling option, which did not work either.

**Expected behavior**
Script should run every 30 minutes.

**Version**

Version Number: 2.1.2
Dashboard Framework (if applicable): 
Operating System: Server 2019

**Additional context**
Using kestrel to run PSU

**Comment by adamdriscoll** [comment]
Can you send a log (%ProgramData%\PowerShellUniversal)? Since it's displaying an incorrect next execution time, it seems like the scheduling library (HangFire) failed to actually schedule the job. There may be an error in the log around when the schedules.ps1 file was read. I tried your CRON locally and it works fine for me.

**Comment by brettfire** [comment]
Here is my schedules.ps1:
```
New-PSUSchedule -Script "[Scheduled] Gather Inventory" -TimeZone "America/New_York" -Continuous -Delay ([System.TimeSpan]::FromSeconds(240)) -Name "Gather Inventory"
```

Log:
```
2021-07-26T15:03:22.5304858-04:00  [ERR] Failed to read configuration file. schedules.ps1 (0045c5f0)
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at PowerShellUniversal.MemoryTable`1.First() in D:\a\universal\universal\src\PowerShellUniversal\MemoryTable.cs:line 40
   at UniversalAutomation.Services.SchedulesConfigurationScript.OnReadAfterAddAsync(Schedule schedule) in D:\a\universal\universal\src\UniversalAutomation\Services\Configuration\Schedules.cs:line 36
   at UniversalAutomation.Services.ConfigurationScript`1.ReadAsync(Boolean initialSync) in D:\a\universal\universal\src\UniversalAutomation\Services\Configuration\ConfigurationScript.cs:line 189
```

And file permissions for schedules.ps1 (service is running as PSUniversalMSA managed service account):
![image](https://user-images.githubusercontent.com/5559465/127044682-9b438bd5-0907-4eca-a25b-3e60a4d706f5.png)

**Comment by brettfire** [comment]
@adamdriscoll any idea about this one?

**Comment by adamdriscoll** [comment]
@icanhazpython It looks like it's failing to find the script. Can you verify that you have a `[Scheduled] Gather Inventory` script? You may also need to use `[Scheduled] Gather Inventory.ps1` within schedules.ps1

**Comment by brettfire** [comment]
@adamdriscoll I changed things around:

- Renamed the file to `Gather Inventory.ps1`
- scripts.ps1 now has: `New-PSUScript -Name "Gather Inventory.ps1" -Description "Gather AD inventory." -TimeOut "30" -Path "Gather Inventory.ps1" -InformationAction "Continue" -MaxHistory 10`
- schedules.ps1 now has (created from gui): `New-PSUSchedule -Script "Gather Inventory.ps1" -TimeZone "America/New_York" -Continuous -Delay ([System.TimeSpan]::FromSeconds(300)) -Credential "Default" -Name "Gather Inventory"`

Result: still showing scheduled as "Jan 1, 1901 12:00 AM", and no jobs are running.

**Comment by adamdriscoll** [comment]
@icanhazpython Can you do me a favor and try the same thing on 2.2.0? I've heard some reports of strange scheduling issues on 2.1.2.  I just want to make sure we don't have a resolution for this already. That said, it seems like a bug for sure.
