### ISSUE TITLE
Automation scripts with certain characters in file name cannot be edited via UI

### ISSUE THREAD

**Issue by brettfire** [ironmansoftware/powershell-universal#321]
**Describe the bug**
When attempting to edit script files from the automation UI for scripts that have characters such as "[]" in their file name, the UI returns an error: "Request failed with status code 405".

**To Reproduce**
1. Create file on filesystem with brackets ([]) in the name. 
2. Add the script to the scripts.ps1 config file as such: `New-PSUScript -Name "[Scheduled] Provision" -Description "Provision new servers." -TimeOut "210" -Path "[Scheduled] Provision.ps1" -ErrorAction "Stop" -InformationAction "Continue" -MaxHistory 10`
3. Within PSU, Go to Automation -> Scripts. Click the "Details" button next to the script.
4. Attempt to edit the code and save.
5. A 405 error will appear

**Expected behavior**
Changes should be saved

**Version**

Version Number: 2.1.2
Dashboard Framework (if applicable): 
Operating System: Server 2019

**Additional context**
Using kestrel to run PSU

**Comment by RamikySPK** [comment]
Same problem with umlaut letters (ä, ö, å)
