### ISSUE TITLE
Add -DefaultSortDirection (or equivalent) to New-UDTableColumn

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#3216]
### Summary of the new feature / enhancement

As a user, I want to be able to sort a table in reverse (newest rows at the top, for instance), but -DefaultSortColumn only sorts ascending.

### Proposed technical implementation details (optional)

Add a -DefaultSortDirection which defaults to Ascending, but allows Descending 
Alternatively, add -SortInReverse or some other switch to do the same.

**Comment by MikeShepard** [comment]
Just found -DefaultSortDirection on New-UDTable....I'm guessing that does this. 

Guessing this is really a documentation issue.

**Comment by adamdriscoll** [comment]
I've added an example to the live docs for this. The parameters are: 

-DefaultSortColumn on New-UDTable
-DefaultSortDirection on New-UDTableColumn
