### ISSUE TITLE
Admin Console vs Management API - Memory Reporting

### ISSUE THREAD

**Issue by liamjpeters** [ironmansoftware/powershell-universal#3217]
### Version

4.2.13

### Severity

Low

### Steps to Reproduce

When I get the memory usage of all processes (Universal Server, API, Dashboards/Apps), the Sum is always smaller than that memory usage shown in the `https://Server/admin/apps` page.

For instance, Total Memory Usage shows in the Apps page as 5.3GB currently.

Running:

```powershell
$Server = 'MyServerURL'
$Mem = Invoke-RestMethod "https://$Server/api/v1/diagnostics/processes" -UseDefaultCredentials
$Mem | measure-object -Sum 'memory' | Select -expand 'sum' | ForEach-Object {"{0:N2}GB" -f ($_/1GB)}
```

Returns `3.63GB`, which is basically the usage listed in `https://Server/admin/platform/diagnostics/processes`

What's the discrepancy?

### Expected behavior

```console
Total memory usage of all PSU processes is greater than the memory usage listed on the Apps page (which I understood to be a summation of the memory used by just the apps - e.g. not including API and the Universal Server process)
```

### Actual behavior

```console
Total memory usage of all PSU processes is less than the memory usage listed on the Apps page
```

### Additional Environment data

PSU Version `4.2.13`. Running in on-prem IIS under Windows Server 2019

**Comment by adamdriscoll** [comment]
I wonder if we're counting the integrated environment more than once on the apps page. Do you have apps running in the integrated environment?

**Comment by liamjpeters** [comment]
Not that I know of. Only process that comes back as using the integrated environment is the `PowerShell Universal Server` process.

```powershell
$Server = 'MyServerURL'
$Mem = Invoke-RestMethod "https://$Server/api/v1/diagnostics/processes" -UseDefaultCredentials

$Mem | Select-Object 'ProcessId','Description', @{n='PSVersion';e={$_.environment.version}}, 'Memory', @{n='Memory(GB)';e={"{0:N2}" -f ($_.Memory/1GB)}} | FT

$Mem | measure-object -Sum 'memory' | Select -expand 'sum' | ForEach-Object {"{0:N2}GB" -f ($_/1GB)}
```

```shell
processId description                 PSVersion         memory Memory(GB)
--------- -----------                 ---------         ------ ----------
     9536 Dashboard                   7.3.9          157675520 0.15
    15684 Dashboard                   7.3.9          135794688 0.13
    23656 Dashboard                   7.3.9          244842496 0.23
     8644 Dashboard                   7.3.9          135925760 0.13
     7604 Dashboard                   7.3.9          135602176 0.13
    17080 Dashboard                   7.3.9          144355328 0.13
     4856 Dashboard                   7.3.9          163606528 0.15
     7644 Dashboard                   7.3.9          157212672 0.15
    17148 API                         5.1.14393.6343  79118336 0.07
    19388 Dashboard                   7.3.9          128245760 0.12
    17736 Dashboard                   7.3.9          142286848 0.13
    20536 Dashboard                   7.3.9          134938624 0.13
    15528 Dashboard                   7.3.9          514641920 0.48
     1056 Dashboard                   7.3.9          463159296 0.43
     5532 PowerShell Universal Server                840650752 0.78
```

```shell
3.33GB
```

![image](https://github.com/ironmansoftware/issues/assets/6566675/5be1732d-2cb5-4b0a-933f-0411a5be4e8b)

Though the PowerShell Universal Server process listed above seems to match the process ID of the built-in docs app - if that has any potential bearing.

![image](https://github.com/ironmansoftware/issues/assets/6566675/9b3b0ee2-f18d-467d-a27f-4e26001b62a6)

**Comment by adamdriscoll** [comment]
We were using two different memory stats. I've lined them up to both use private bytes.
