### ISSUE TITLE
API Variables Persist Across Endpoints and Executions

### ISSUE THREAD

**Issue by loganhawker** [ironmansoftware/powershell-universal#3219]
Just tested this in 4.2.14 and the issue is still present

_Originally posted by @loganhawker in https://github.com/ironmansoftware/issues/issues/3181#issuecomment-2016551616_

**Comment by adamdriscoll** [comment]
We actually have a test case for this and it's passing. We did have to make changes to fix the original issue. Here's the test case we are using. Is there something I'm missing with my test case? 

```
New-PSUEndpoint -Url /testEndpoint13/:name -ScriptBlock {
   param($Name) 
   $Name
}

New-PSUEndpoint -Url /testEndpoint13/anEndpoint -ScriptBlock {
   'Hello'
}
```

Invoking /testEndpoint13/anEndpoint returns Hello
Invoking /testEndpoint13/123 returns 123

**Comment by loganhawker** [comment]
Try this
```
New-PSUEndpoint -Url /testEndpoint14/:name -ScriptBlock {
   $name
}

New-PSUEndpoint -Url /testEndpoint14-ScriptBlock {
   $name
}
```
Invoking /testEndpoint14/logan returns "logan"
Invoking /testEndpoint14 returns "logan"

It looks like if you don't catch it as a param it becomes a global variable in the environment. Is that intended?

**Comment by adamdriscoll** [comment]
If there is no parameter, it does set a variable. That said, after every execution the runspace state is reset so this variable should not exist on the second execution. That is, unless you have persistent runspaces enabled for the environment. This prevents the variables from being cleared. 

I tried your test above and don't see that behavior without persistent runspaces.

**Comment by loganhawker** [comment]
I do have persistent runspaces. I'll go through and add parameters to the endpoints. Interesting because this issue only came up after updating to 4.2.13.

**Comment by adamdriscoll** [comment]
Unsure why that would have changed for you but glad we got to the bottom of it.
