### ISSUE TITLE
Variables overview visable bug vault

### ISSUE THREAD

**Issue by timoline** [ironmansoftware/powershell-universal#3220]
### Version

4.2.14

### Severity

Low

### Steps to Reproduce

Hi Adam,
there is a small visable bug in the variables overview.
When you add a string variable and store it in the database vault, its not shown in the overview.

### Expected behavior

```console
Show it in the overview
```

### Actual behavior

```console
it is not shown in the overview
```

### Visuals

<img width="622" alt="image" src="https://github.com/ironmansoftware/issues/assets/680252/ab299a41-49a9-491b-8c3d-eb517795a1a7">

**Comment by adamdriscoll** [comment]
This is actually by design. The database secret vault and the regular variable are stored in two different ways so when you select Store in Database, it doesn't actually use the vault. In v5, we have a better display for this.
