### ISSUE TITLE
Feeedback v5.0.0-Beta1

### ISSUE THREAD

**Issue by mikesimmons80** [ironmansoftware/powershell-universal#3221]
### Summary of the feedback

1 - Unable to create a PSCredential secret variable. The modal crashes and won't allow any input fields to be selected - possibly an issue with the port to Blazor.
2 - Tags missing from Apps. Might be by design, but I use these as parent headings when building multi-level navigation menu in v4 so would be mildly irritating.
3 - There is a condition that causes apps in dashboards.ps1 to be duplicated. I haven't figured out what it is yet.

**Comment by alexrgreenwood** [comment]
I've added some feedback at this forum post
https://forums.ironmansoftware.com/t/first-testing-of-psu-5-0-0-beta-1/10476/3?u=alexrgreenwood
