### ISSUE TITLE
Failed to sync.  System.ArgumentNullException: Value cannot be null. (Parameter 's')

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3222]
### Version

4.2.14

### Severity

High

### Steps to Reproduce

i upgraded to .14, psu git sync broke.

### Expected behavior

```console
200
```

### Actual behavior

```console
PowerShell Universal Failed to Load Failed to load PowerShell Universal. Ask your administrator to refer to the log file for more information
```

### Additional Environment data

IIS: Nested

## Problem
secrets.database.encryptionkey was missing from settings.json
## Solution
add 
```
		"Database": {
			"EncryptionKey": "some nonsense"
		}
```
to the settings file, this might be missing due to having been upgraded so many times

# Enhancement Request
create a better error message that helps us figure out what the real problem is.

**Comment by Omzig** [comment]
support: https://support.ironmansoftware.com/portal/en/ticket/548223000031405011

**Comment by adamdriscoll** [comment]
I added a better error message about this in 4.2.15.
