### ISSUE TITLE
Warning if persistent sessions are enabled in VS Code

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#3223]
## Is your feature request related to a problem? Please describe.
This feature request is related to a known bug in PowerShell Pro Tools 'command not found' and PowerShell Pro Tools host is not connecting. The workarounds are described in [KB3009](https://support.ironmansoftware.com/portal/en/kb/articles/kb3009-powershell-pro-tools-for-vs-code-failed-to-connect).

## Describe the solution you'd like
To avoid impact PowerShell Pro Tools for VS Code should throw a pop-up or other prominent warning if the _Enable Persistent Sessions_ setting is enabled in VS Code.

> terminal.integrated.enablePersistentSessions = true

## Additional context
![image](https://github.com/ironmansoftware/issues/assets/537287/7c227aa9-13f6-4ebb-8d83-efffcd29b995)
###### above figure shows the setting in VS Code which PowerShell Pro Tools should alert on if it is enabled

![image](https://github.com/ironmansoftware/issues/assets/537287/d6a77c5b-505e-4475-bf7e-49c04240941e)

**Comment by adamdriscoll** [comment]
I think I actually found the cause for why this isn't working. I will publish a build today.
