### ISSUE TITLE
Git push not happening after commit

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3224]
### Version

4.2.14

### Severity

Low

### Steps to Reproduce

i have to manually git push now

### Expected behavior

```console
auto git push
```

### Actual behavior

```console
git commit only
```

### Additional Environment data

IIS: Nested

**Comment by timoline** [comment]
we had the same, 
We solved it by changing some git policies which where active

**Comment by Omzig** [comment]
> we had the same, We solved it by changing some git policies which where active

what policy would you be talking about? i use github, but sometimes things are not obvious to me when github adds a new feature or they apply some policy to my org

**Comment by adamdriscoll** [comment]
Is there any error in the log? If you enable debug system logs you should get a pretty good error message from the git client.

**Comment by Omzig** [comment]
so funny thing, i am now on .15, and the problem has gone away............... i have not had to go do a push yesterday and today. i would be willing to close this..................
