### ISSUE TITLE
Problem with wait in invoke-PSUScript

### ISSUE THREAD

**Issue by septprip** [ironmansoftware/powershell-universal#3226]
### Version

4.2.14

### Severity

High

### Steps to Reproduce

If I run this command:
Invoke-PSUScript -Name USBX\GetUSBX.ps1 -ComputerID 'Computer' -Domain 'domain.com' -Wait
 I get this error:
[error] Value cannot be null. (Parameter 'value') 

At a closer look it seems '-wait' is the problem. If I remove '-wait' it works! Also if I look at the failed request, the nested job worked and produced the desired outcome.

### Expected behavior

```console
Invoke-PSUScript -Name USBX\GetUSBX.ps1 -ComputerID 'Computer' -Domain 'domain.com' -Wait

Returns
a string in line with CODE;22334455;20240101;20240202;11d;ABC
```

### Actual behavior

```console
Invoke-PSUScript -Name USBX\GetUSBX.ps1 -ComputerID 'Computer' -Domain 'domain.com' -Wait

Returns:
[error] Value cannot be null. (Parameter 'value')
```

**Comment by Viajaz** [comment]
I have the same issue with `Wait-PSUJob`:
```
At line:1 char:1
+ Wait-PSUJob -JobId 12345
+ ~~~~~~~~~~~~~~~~~~~~~~~~~

System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at UniversalAutomation.WaitJobCommand.ProcessRecord() in C:\actions-runner\_work\universal\universal\src\Cmdlets\Automation\WaitJobCommand.cs:line 73
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

**Comment by adamdriscoll** [comment]
We are looking into this one and will be issuing a patch later today. Others have reported this on the support queue as well.
