### ISSUE TITLE
PSU synced automatically when it was set to manual.

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#3232]
### Summary of the new feature / enhancement

I just merged a pull request and when I went to the main PSU instance to sync, it was already present.

The git settings in main are "one-way, manual".

4.2.15, in nested IIS.

**Comment by MikeShepard** [comment]
Just did it again....kept hitting refresh in the git page in PSU Admin and it showed the new PR and the sync status showed success.

**Comment by MikeShepard** [comment]
Watched several times now, without refreshing the git page.  Just wait ~15 seconds from merging to main, a loaded psu page reloads with the newly merged code.

**Comment by adamdriscoll** [comment]
This is actually by design at the moment. Auto vs manual is auto push vs manual push. It will also pull automatically if the manual edit mode is not currently editing.

**Comment by MikeShepard** [comment]
Ok...well at least that makes sense.

On the other hand, manual on the DEV end (pushing to github) isn't super important.  There's almost no risk in pushing code to a branch.

On the PRD side (pulling from github), it seems like this is where a gate would be helpful.  I might have several PRs merged as different features mature in DEV.  Don't necessarily want them to get pulled into production at the same time.  Similar to how you bunch up PRs in a PSU release, I like to bunch up PRs in a release of a PSU App.

Does that make sense, @adamdriscoll ?  Am I using the github ci/cd differently than you expect?

**Comment by Omzig** [comment]
As a user, I want to set the sync interval to 0 minutes to disable auto pull so that i can manually click the `synchronize now` button. 
- This would allow for me to pile up 5 PRS before i want to deploy to production.
- Manual Pull's would let me control deployment to production.
