### ISSUE TITLE
JobsRunToday - Goes down

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#3235]
### Version

4.2.15

### Severity

Visual

### Environment

msi

### Steps to Reproduce

We have one PSU server that runs approx. 900-1000 jobs every day.
When looking at the Jobs run today, the number tends to go up AND down.

Either this is a bug or the counter is based on current datetime minus 24 hours - meaning the counter goes down, when the jobs older than 24 hours is archived.

### Expected behavior

```console
I would expect the counter to reset everyday at midnight, and then start from 0.
```

### Actual behavior

```console
Either its a bug, or it calculates the Jobs run today based on current datetime minus 24 hours.
```

### Visuals

![image](https://github.com/ironmansoftware/issues/assets/53445047/9b1841d0-d450-417e-9e26-20aa5bfca8bc)

**Comment by adamdriscoll** [comment]
It's just calculating based on the past 24 hours. We really should just have a stats table in the database rather than calculating this from the jobs table since jobs can be removed.

**Comment by ksl28** [comment]
> It's just calculating based on the past 24 hours. We really should just have a stats table in the database rather than calculating this from the jobs table since jobs can be removed.

And either change the description to "Jobs over past 24 hours" or reset the counter at midnight (preferred) :)

**Comment by adamdriscoll** [comment]
v4 - this has been renamed to Last 24 hours 
v5 - this has been updated to jobs run today
