### ISSUE TITLE
Tooltip from Comment Based Help on Automation Scripts Parameters

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3237]
### Summary of the new feature / enhancement

As a user, I want to put a comment on my parameter in a script so that it will surface to the end user when he clicks the run button on a script. 

Script Comments:
![image](https://github.com/ironmansoftware/issues/assets/1987296/17789c35-63ee-429f-bd47-4129cbde72b1)

Before:
![image](https://github.com/ironmansoftware/issues/assets/1987296/36907f9c-93fb-43b5-a2bf-08ae58695a26)

After:
![image](https://github.com/ironmansoftware/issues/assets/1987296/da7279ba-b7c7-4d46-986e-d7047a32c58b)

### Proposed technical implementation details (optional)

Something like this?
(get-help whatever-script.ps1).parameters.parameter | select Name,description

**Comment by adamdriscoll** [comment]
You can do this with the parameter attribute: https://docs.powershelluniversal.com/automation/scripts/parameters#help-messages

**Comment by Omzig** [comment]
YOU WIN.
