### ISSUE TITLE
Get-PSUJobOutput - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mikedhanson** [ironmansoftware/powershell-universal#3249]
### Version

4.2.16

### Severity

High

### Environment

msi

### Steps to Reproduce

https://forums.ironmansoftware.com/t/powershell-universal-4-2-16/10566/3?u=mikedhanson 

![image](https://github.com/ironmansoftware/issues/assets/15201245/6d26b01d-dd3a-4cae-a500-c2e093f48588)

### Expected behavior

```console
No error
```

### Actual behavior

```console
Error
```

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/powershell-universal-4-2-16/10566/4
