### ISSUE TITLE
Get-PsuVariable

### ISSUE THREAD

**Issue by Bartozorus** [ironmansoftware/powershell-universal#3250]
### Version

4.2.8

### Severity

High

### Environment

IIS

### Steps to Reproduce

**BUG Reproduction :**

1.  "Create New Variable" with enabled "Store in Database", type "integer", value : 0
![image](https://github.com/ironmansoftware/issues/assets/96522499/742331e7-fd1d-4dd3-83ac-f3846448e491)

At this state all is OK variable "var_test"=0
Configuration file "variables.ps1" should contain something like this : `New-PSUVariable -Name "var_test" -Type "System.Int32" -Database`

Get-PSUVariable -Name var_test  --> Value = 0 --> OK

2. Edit variable configuration then disable "Store in Database" and change value : 999
![image](https://github.com/ironmansoftware/issues/assets/96522499/62c2dc7d-1cb4-4e3f-b1b7-fe47150c25bc)

configuration file "variables.ps1" should now contain something like this : `New-PSUVariable -Name "var_test" -Value 999 -Type "System.Int32"`

Get-PSUVariable -Name var_test  --> Value = 0 --> NOK --> **Should be Value =999**

**CAUSE :**
Database contain row value created on step1. Function Get-PSUVariable always get value from database even config file variables.ps1 contain something else

![image](https://github.com/ironmansoftware/issues/assets/96522499/113026d6-f0d1-418a-b7c3-5349901d2b17)

### Expected behavior

```console
Get-PSUVariable : function should return value from variables.ps1 configuration file rather than that indicated in the database
```

### Actual behavior

```console
Get-PSUVariable : function always returns the value from the database regardless of the configuration of variables.ps1
```

### Additional Environment data

using PowershellUniversal local LiteDB integrated database

**Comment by timoline** [comment]
I also have this bug,, but a little different...

The bug is when editing the value and forget to set the database switch  again
(switch is not correct when editing)
