### ISSUE TITLE
Endpoints: Cant sort tags

### ISSUE THREAD

**Issue by mikedhanson** [ironmansoftware/powershell-universal#3258]
### Version

4.2.17

### Severity

Low

### Environment

msi

### Steps to Reproduce

https://github.com/ironmansoftware/issues/assets/15201245/a17c0390-6a68-4ba2-acae-1b5656c50606

### Expected behavior

```console
sort tags
```

### Actual behavior

```console
doesnt sort
```

**Comment by adamdriscoll** [comment]
Duplicate of https://github.com/ironmansoftware/issues/issues/1783
