### ISSUE TITLE
logging in general sometimes stops working

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3261]
### Version

4.2.16

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

i am having a problem 'sometimes' where the logs just wont write out to the logging window

### Expected behavior

```console
populate logs
```

### Actual behavior

```console
no logs at all shown in the admin site
```

### Workaround
restart the app pool

**Comment by RockoTheeHut** [comment]
Our logs will randomly stop working like this but it impacts all logs. Have to restart the service and then we can view them in the gui again. Endpoints, jobs, etc..

Not using IIS though, have a SQL backend

**Comment by Omzig** [comment]
so it seems to work for a good day, then when we come in the next few days or whatever, that is when it seems like it gives up.

**Comment by adamdriscoll** [comment]
We were improperly configuring Serilog and stomping on the logging configuration. This was also causing the issue with multiple logs being generated for a single process.

**Comment by Omzig** [comment]
@adamdriscoll, Are you going to apply this fix to 5.x?

**Comment by adamdriscoll** [comment]
@adamdriscoll - Yep. It's been merged into both versions. 

EDIT: lol....talking to myself @Omzig
