### ISSUE TITLE
Extra options for Swagger Documentation

### ISSUE THREAD

**Issue by ScheeleRxNL** [ironmansoftware/powershell-universal#3263]
### Summary of the new feature / enhancement

As a user i want to have some extra options to add for swagger documentation. See forum post with screenshots etc.
[Endpoint Documentation add some Swagger Options](https://forums.ironmansoftware.com/t/endpoint-documentation-add-some-swagger-options/10591/2)

**Comment by adamdriscoll** [comment]
We have improved this for v5, but do note that you can take advantage of much of this in v4. 

The description parameter for New-PSUEndpointDocumentation (or within the admin console) supports markdown. You can add any links or text you like. 

We have also added the authorize button in v4.2.18.
