### ISSUE TITLE
/variables not reading the -database option on the variable

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3266]
### Version

4.2.17

### Severity

Medium/High

### Environment

Nested IIS

### Steps to Reproduce

you can set the variable to a string, it turns into a public one, the config sets the var to -database
but when you edit it again, the toggle says the db is not enabled

It also does not have a button like the secret, it should have a button that says "Set Secret Value" in production (or oneway git)

### Expected behavior

```console
toggle should say 'in database'
Same behavior as the secret.
```

### Actual behavior

```console
toggle is always disabled on edit (clicking cog)
```

### Screenshots/Animations

![image](https://github.com/ironmansoftware/issues/assets/1987296/72e3b2d0-3a55-4586-82e6-f3177905ad5b)
![image](https://github.com/ironmansoftware/issues/assets/1987296/6be2761e-bab6-4085-ba07-814042604a79)

**Comment by Omzig** [comment]
oh my goodness, thank you so much

**Comment by adamdriscoll** [comment]
It was actually already done :) Had someone else report it.
