### ISSUE TITLE
$Query hashtable is not scoped into New-UDForm -OnValidate scriptblock

### ISSUE THREAD

**Issue by ad-85** [ironmansoftware/powershell-universal#3267]
### Version

4.2.17

### Severity

Low

### Environment

msi

### Steps to Reproduce

Using a variable form a URI query used to create a variable of the same name before this behaviour was changed in 3.9.16 to address the inherent injection vulnerability of the old functionality. 

However, the new `$Query` hashtable does not appear to have the same global scope the previous funcitonality offered. For example, an `-OnValidate` scriptblock of `New-UDForm` returns `null` if the hashtable is referenced. This may also be true for other scriptblocks (I haven't tested it to completion).

This code can demonstrate the issue - even if you use the `?Test=valid` in the URI, validation fails as the variable evaluates to `$null`.
```
New-UDApp -Title 'PSUTest' -Pages @(
    New-UDPage -Name 'home' -Content {
        New-UDForm -Id 'TestForm' -OnValidate {
            if ($Query.Test -eq 'Valid') {
                New-UDValidationResult -Valid
            }
            else {
                New-UDValidationResult -ValidationError "`"$($Query.Test)`" is not valid."
            }
        } -OnSubmit {
            Show-UDToast -Message "Success!"
        } -Children {
            New-UDCheckBox -Label "This is a test form"
        }
    }
)
```

### Expected behavior

```console
In the above example, the form should pass validation.
```

### Actual behavior

```console
The form fails validation as $Query -eq $null within the OnValidate scriptblock.
```

### Additional Environment data

(With URI of /home?Test=Valid)

New-UDApp -Title 'PSUTest' -Pages @(
    New-UDPage -Name 'home' -Content {
        New-UDForm -Id 'TestForm' -OnValidate {
            if ($Query.Test -ne 'Valid') {
                New-UDValidationResult -ValidationError "`"$($Query.Test)`" is not valid."
            }
        } -OnSubmit {
            Show-UDToast -Message "Success!"
        } -Children {
            New-UDCheckBox -Label "This is a test form"
        }
    }
)

**Comment by adamdriscoll** [comment]
This seems related. 

https://forums.ironmansoftware.com/t/query-dictionary-and-invoke-udendpoint-onclick-behavior/10397

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/query-not-updating-when-switching-pages-from-navigation/10808/1
