### ISSUE TITLE
$Cache value is empty 

### ISSUE THREAD

**Issue by wsl2001** [ironmansoftware/powershell-universal#3273]
### Version

4.2.18

### Severity

Critical

### Environment

IIS

### Steps to Reproduce

New-UDEndpoint -Endpoint {

       $Cache:computers = "pc1","pc2","pc3"                                         

 } -Schedule (New-UDEndpointSchedule -Every 1 -Day)

New-UDPage -Name "Test"  -Content { 

New-UDButton -Icon (New-UDIcon -Icon 'rotate') -Style @{ BackgroundColor = "#26a69a"; Width = "125px" } -ShowLoading -Text "Test" -OnClick {

Show-UDToast -Message "$Cache:computers" -MessageColor Green -Title "Test" -Position topCenter -Duration 2500

}

}
        

### Expected behavior

```console
$Cache:computers should return cached value.
```

### Actual behavior

```console
Empty String.
```

### Screenshots/Animations

![image](https://github.com/ironmansoftware/issues/assets/47834749/b01a8d40-f8de-4beb-a3d2-a5316b328673)

**Comment by adamdriscoll** [comment]
I can reproduce this. Scheduled endpoints aren't running properly. This has been resolved in our main branch and will be in 4.2.19.
