### ISSUE TITLE
Ability to filter by any column on the Automation/Jobs page

### ISSUE THREAD

**Issue by JessePeden** [ironmansoftware/powershell-universal#3274]
### Summary of the new feature / enhancement

Currently, the only column you can filter by is the Status column.  It would be very helpful to be able to filter any column, as well as any combination of the columns.

**Comment by adamdriscoll** [comment]
This has been implemented in v5.

**Comment by JessePeden** [comment]
> This has been implemented in v5. 

Oh. Great. I guess I'll be looking forward to v5's non-beta release.
