### ISSUE TITLE
Remove-PSUVariable cmdlet throws "Specified method is not supported" error

### ISSUE THREAD

**Issue by RubenT91** [ironmansoftware/powershell-universal#3281]
### Version

4.2.12

### Severity

Low

### Environment

msi

### Steps to Reproduce

Create a PowerShell Universal variable using New-PSUVariable with a PSCredential type and store it in the BuiltInLocalVault.
In a PowerShell script, use the following code to try to remove the variable:

`param (
    [Parameter(Mandatory)]
    [String]
    $username
)

Remove-PSUVariable -name $username -RemoveSecret -Verbose`

### Expected behavior

```console
The Remove-PSUVariable cmdlet should successfully remove the specified variable from the BuiltInLocalVault.
```

### Actual behavior

```console
When running the script, the following error is thrown:
[error] Specified method is not supported
```

### Additional Environment data

PowerShell Universal version: 4.2.12
The variable was created using New-PSUVariable and stored in the BuiltInLocalVault with a PSCredential type.
User is able to use the variable in other scripts, but they are unable to remove it using the Remove-PSUVariable cmdlet.
The documentation for the Remove-PSUVariable cmdlet is out-of-date and refers to the incorrect cmdlet name (Get-UAVariable).

**Comment by adamdriscoll** [comment]
@RubenT91 - I can reproduce this. This will be resolved in v4.2.19.
