### ISSUE TITLE
[bughancement] ~500mb log files

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3282]
### Version

4.2.18

### Severity

High

### Environment

Nested IIS

### Steps to Reproduce

my logs are are filling up my hard drive and there is [VRB] and [DBG] stuff in them. LogLevel in settings is set to 'error' by default. However when i go to logging targets, there is no default log settings....

### Expected behavior

```console
Default Logging added as row 1?
```

### Actual behavior

```console
logging set to full and we get everything in the logs by default
```

**Comment by Omzig** [comment]
So i found this:

https://docs.powershelluniversal.com/development/logging#targets

> The first is the system log. This contains log details about the PowerShell Universal server and is set to verbose by default.


If it is verbose by default, it would be nice to have that in the targets already by 'default'....

**Comment by Omzig** [comment]
OHHHHHHHHHHH! the settings file now has a default that i didn't know about, because it doesn't exist in v3.x when i first created my settings.json file!

`"SystemLogLevel": "Information",`

**Comment by adamdriscoll** [comment]
This is causing the issue you saw. I'll get it fixed so it doesn't default to verbose if it isn't set to that. 

```
var systemLogLevel = configuration["SystemLogLevel"] ?? "Verbose";
```
