### ISSUE TITLE
New-UDChip editable label

### ISSUE THREAD

**Issue by kodifan** [ironmansoftware/powershell-universal#3284]
### Summary of the new feature / enhancement

I use in some of my dashboard udchips to display some kind of elements from array (i.e. users in particular  group or computers etc)
I use it because its has on delete script block where i can easily remove this elemental form array. 
But when it comes to adding or changing those element you have to use other commands (udtexbox or read-host) 
It will be handy if udchip has onedit (or function in onclick ) script block to update its "label" or even create new form empty ud chip"
There is onclick block but still you have to use another command to input those values

**Comment by Omzig** [comment]
I do not see that feature in the MUI controls: https://mui.com/material-ui/react-chip/#basic-chip

**Comment by kodifan** [comment]
> I do not see that feature in the MUI controls: https://mui.com/material-ui/react-chip/#basic-chip

But it has to be ? It could not be added on the PU code itself ?  (to be at least able to set value of udlement by label attribute ?

**Comment by adamdriscoll** [comment]
You can use Set-UDElement to update a chip label. 

```powershell
    New-UDChip -Label "Hello" -Id 'MyChip' -OnClick {
        Set-UDElement -Id "MyChip" -Properties @{
            Label = "Goodbye"
        }
    }
```

**Comment by Omzig** [comment]
> You can use Set-UDElement to update a chip label.
> 
> ```powershell
>     New-UDChip -Label "Hello" -Id 'MyChip' -OnClick {
>         Set-UDElement -Id "MyChip" -Properties @{
>             Label = "Goodbye"
>         }
>     }
> ```

@adamdriscoll,
/drool, this would be good in the live doc

**Comment by kodifan** [comment]
Yes that is working but still you have use other elements (like modal) to allow user to enter new label name
Since I use a modals a lot and PU dont have nested modals yet, next modal will destroy this one with udchip :)
Yes i can use read-host, some java applets etc. but its all not that easy to use like ability to edit chip label "on the chip itself" (like ud textbox or so)
Maybe I want to much :) but it would be great if someday that functionality will be included in PU
