### ISSUE TITLE
Ability to connect multiple repositories to a single PU server

### ISSUE THREAD

**Issue by RubenT91** [ironmansoftware/powershell-universal#3288]
### Summary of the new feature / enhancement

Allow a single PU server to connect to multiple repositories simultaneously, with different access rights (read/write or read-only) for each repository. This would enable users to have separate DEV and PROD repositories connected, eliminating the need to switch between servers.

### Proposed technical implementation details (optional)

Configure multiple repository connections with access credentials.
Define access rights (read/write or read-only) for each connected repository.
Synchronize changes from DEV to PROD repository while preventing accidental modifications.
Support for multiple network connections and VPN configurations.
UI enhancements to manage and switch between connected repositories.
Access control and permissions based on user roles.
Logging and auditing of changes to each repository.

**Comment by adamdriscoll** [comment]
This is beyond the scope of what I'd like to implement in PSU.
