### ISSUE TITLE
 Wait-PSUJob: Value cannot be null. (Parameter 'source')

### ISSUE THREAD

**Issue by mikedhanson** [ironmansoftware/powershell-universal#3290]
### Version

4.2.19

### Severity

High

### Environment

msi

### Steps to Reproduce

 $ScriptParams = [ordered]@{
            Name         = 'ActiveDirectory\Edit-Groups.ps1' 
            UserAccounts = @("$ADTestUser")
            Groups       = $TestGroups
            RequestType  = "add"
            ComputerName = $HostName
            AppToken     = $AppToken
        }

$CurrentJob = Invoke-PSUScript @ScriptParams | Wait-PSUJob

Wait-PSUJob: Value cannot be null. (Parameter 'source')

### Expected behavior

```console
No error
```

### Actual behavior

```console
error
```

### Screenshots/Animations

![image](https://github.com/ironmansoftware/issues/assets/15201245/b4d68d37-59d0-4c3a-9119-e2d0546996c6)

**Comment by mikedhanson** [comment]
https://docs.powershelluniversal.com/automation/jobs#waiting-for-a-script-to-finished

**Comment by JessePeden** [comment]
In my own instance of PSU 4.2.19, which is also an MSI-based setup, I ran a similar command without any errors.

```
param(
        [Parameter(Mandatory)]
        [String]$HuduDeviceID,
        [Parameter(Mandatory)]
        [String]$HuduCompanyID,
        [Parameter(Mandatory)]
        [String]$HuduCredentialID,
        [Parameter(Mandatory)]
        [String]$PaloAltoDeviceIP,
        [Parameter(Mandatory)]
        [String]$Comment
    )



    Invoke-PSUScript -Script "Hudu\DownloadPaloAltoConfig.ps1" -HuduDeviceID $HuduDeviceID -HuduCompanyID $HuduCompanyID -PaloAltoDeviceIP $PaloAltoDeviceIP -HuduCredentialID $HuduCredentialID | Wait-PSUJob
```

I got no errors and the script completed as expected.  Can you provide any more details that might help?

**Comment by mikedhanson** [comment]
I'm not sure what else to provide other than that error message. 

I tried the same steps as I outlined in version 4.2.15, and it works.

**Comment by JessePeden** [comment]
That's interesting.  I wonder what it is that's causing it to work in one version but not in the other, assuming all variables are being filled with the same data and the same script file is being used in both cases.  And why using Wait-PSUJob works in my test.  Are you able to use Wait-PSUJob in 4.2.19 with any other scripts (meaning, is it only failing for that one case you detailed above, or failing for any case you try it in)?

**Comment by mikedhanson** [comment]
![image](https://github.com/ironmansoftware/issues/assets/15201245/43cdca85-155a-47af-aba9-9c373e6120c0)

Yeah its all scripts. Not sure what is going on. @adamdriscoll would you like a support ticket on this? Ive been running into issues that your documentation says should work.

**Comment by mikedhanson** [comment]
![image](https://github.com/ironmansoftware/issues/assets/15201245/c51a3a6a-21b5-4574-93af-2f7e457046c5)

**Comment by mikedhanson** [comment]
Rolled back to v4.2.15 and this works 

 Invoke-PSUScript "Examples/HelloWorld.ps1" -UseDefaultCredentials | Wait-PSUJob -UseDefaultCredentials

![image](https://github.com/ironmansoftware/issues/assets/15201245/486c2bc8-d6fb-4441-91dc-7ad4b7584f9e)

**Comment by mikedhanson** [comment]
In order to wait for a job to finish and grab the output you have to use the following 

```powershell
$CurrentJob = Invoke-PSUScript @ScriptParams
$null = Wait-PSUJob -Job $CurrentJob 
```

This way you can wait for the job to finish and have the psu job object to work with.

**Comment by adamdriscoll** [comment]
@mikedhanson - I can't reproduce the Value cannot be null. Can you please get more details from the exception? 

```
$error[0].Exception.StackTrace 
```

![image](https://github.com/ironmansoftware/issues/assets/1256531/2349cbaf-48a3-4d6d-9613-dc56610ab2a4)

I can reproduce this. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/cf82f991-ed65-4983-b15e-856ddaa83200)

The problem is that Invoke-PSUScript is calling Wait-PSUJob when you use -Wait and it isn't passing the -UseDefaultCredential down to that cmdlet. This will be fixed in 4.2.20.

**Comment by mikedhanson** [comment]
Here is the error: @adamdriscoll 


```powershell 
 Invoke-PSUScript "Examples/HelloWorld.ps1" -UseDefaultCredentials -ComputerName "http://localhost:5000" | Wait-PSUJob -UseDefaultCredentials
Wait-PSUJob: Specify a computer name or use the Connect-PSUServer command.
 connect-psuserver -ComputerName localhost:5000 -UseDefaultCredentials

Mode           : Server
Username       : 
OneWayGitSync  : False
ManualGitMode  : False
Roles          : {Administrator}
BuiltInRole    : True
AccessControls : PowerShellUniversal.UserAccessControls

 Invoke-PSUScript "Examples/HelloWorld.ps1" -UseDefaultCredentials -ComputerName "http://localhost:5000" | Wait-PSUJob -UseDefaultCredentials
Wait-PSUJob: Value cannot be null. (Parameter 'source')
 $error[0].Exception.StackTrace
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at UniversalAutomation.WaitJobCommand.ProcessRecord() in C:\actions-runner\_work\universal\universal\src\Cmdlets\Automation\WaitJobCommand.cs:line 75
   at System.Management.Automation.CommandProcessor.ProcessRecord()
```

**Comment by mikedhanson** [comment]
I think im onto something.. Not sure what is causing the issue though. 

![image](https://github.com/ironmansoftware/issues/assets/15201245/d6e2377a-cdda-4712-8068-90d67fc1b2cd)


![image](https://github.com/ironmansoftware/issues/assets/15201245/69fcb4f2-a537-4ac8-b401-dae8282e816a)

**Comment by JessePeden** [comment]
So, it's something limited to PowerShell 7.x or 7.4.x?  Hmm.

**Comment by adamdriscoll** [comment]
I tried in both versions (5.1\7.4.2\7.5) and it works. Is it possible you have 2 versions of the Universal module on this machine and PS7 is finding it at one path and 5.1 finding it at another?

**Comment by mikedhanson** [comment]
OMG! You are correct. I was pulling my hair out on this one. Running `Get-module -ListAvailable -Name Universal` returned some older versions. Deleted those older versions and reinstalled 4.2.19 and re-tested. Looks to be working.
