### ISSUE TITLE
/swagger/index.html requires login, make optional?

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3294]
### Version

4.2.19

### Severity

Medium

### Environment

Container

### Steps to Reproduce

when i visit the swagger doc, it requires login

### Expected behavior

```console
200, to /swagger/index.html
```

### Actual behavior

```console
302, to /login
```

### Screenshots/Animations

![image](https://github.com/ironmansoftware/issues/assets/1987296/5c0d4d51-07d5-4aee-b5ef-f80e51a73b82)

**Comment by adamdriscoll** [comment]
This behaves the same for me in previous versions. It was be design to limit to authenticated users so I'm not sure what changed. 

We did adjust this a bit because it wasn't enforcing it properly for custom endpoint docs that had auth on.

**Comment by Omzig** [comment]
@adamdriscoll, can we make it something we can toggle on and off in the settings.json?

**Comment by adamdriscoll** [comment]
Sure. That's easy enough

**Comment by Omzig** [comment]
@adamdriscoll, errr, What/Where is the setting? Maybe it is in the doc somewhere, but i couldn't find it.
