### ISSUE TITLE
Server fails to start if the Git repo is not accessible

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#3300]
### Version

4.2.19

### Severity

High

### Environment

msi

### Steps to Reproduce

I configured an incorrect Git repo and then had to restart the PSU server, and realized that the server then cant start.
Its stuck on an image like this: 
![image](https://github.com/ironmansoftware/issues/assets/53445047/067a7827-81be-4fa5-8ba5-a0ffdb3f490f)

I had to delete the Git settings from the SQL database, to make the server startup again:
`DELETE FROM GitSettings WHERE (Id = 'xyz')`

I initially tried to set the mode to 0 in the SQL database, but that did not fix the issue.

### Expected behavior

```console
That the PSU server UI could start up, without a connection to the Git repository.
```

### Actual behavior

```console
It cant start without a connection to the Git repository
```

**Comment by adamdriscoll** [comment]
We have a 60 minute timeout on the initial sync in case it takes awhile for this to happen (large repo, slow network etc). You can adjust this by setting Data: { GitSyncTimeout: <minutes> } in appsettings.json.

**Comment by ksl28** [comment]
> GitSyncTimeout

That is good to know, and it makes sense.
I tried searching for the GitSyncTimeout setting, but i cant seem to find any documentation for it - could you add it to https://docs.powershelluniversal.com/config/git ? 🙂

**Comment by adamdriscoll** [comment]
Yep! Will do.
