### ISSUE TITLE
Prevent changing the "top" of the .ps1 files in .Universal

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#3301]
### Summary of the new feature / enhancement

Hi,
It would be great if PSU did not delete the hole .ps1 file inside .universal folder when it updates/renew from the GUI.
For example loginPage.ps1 if you change something for that one in the GUI it will delete the hole .ps1 file and rewrite it it seems like.

Why you might ask? I have some code running some conditions at the top of the page, so if it was possible for example that PSU will not delete anything that's at the top of the .ps1 page and inside this
```
# ---- #
My own code
# ---- #
```

**Comment by adamdriscoll** [comment]
Have you tried using read only regions? 

https://docs.powershelluniversal.com/config/repository#read-only-configuration-sections

**Comment by rwidmark** [comment]
> Have you tried using read only regions? 
> 
> 
> 
> https://docs.powershelluniversal.com/config/repository#read-only-configuration-sections

Ooo, I completely missed that sorry.
