### ISSUE TITLE
Support for tags on jobs produced by Invoke-PSUScript

### ISSUE THREAD

**Issue by JessePeden** [ironmansoftware/powershell-universal#3302]
### Summary of the new feature / enhancement

It would be very nice to have the ability to tag the jobs produced by an `Invoke-PSUScript` command, for organizational/searching purposes.  For example, one of our APIs receives parameters and then adds those parameters into an `Invoke-PSUScript` command to pass along to the script it executes.  The problem is that the parameters are different depending on which client called the API, so without a tag, the only way to see which client called the API at any particular time/date is to hit the `View Job` button to see what the parameters were that it ran with.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/invoke-psuscript-add-tag-to-job/10682/5
