### ISSUE TITLE
CookiePrefix gets added to BasePath

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3307]
### Version

4.2.20

### Severity

Critical

### Environment

Container

### Steps to Reproduce

PSU concatenates the CookiePrefix to the basepath when it creates a cookie. the / is a bad char in the cookie, so even if we were to keep the concatenation we need to replace `/` with `.`.
```
{
	"Kestrel": {
		"Endpoints": {
			"HTTP": {
				"Url": "http://*:5000"
			}
		},
		"RedirectToHttps": "false",
		"UseHttpSys": "false",
		"BasePath": "/department/psuBlank",
		"Hsts": {
			"MaxAgeDays": 365
		},
		"CookiePolicy": "",
		"CookiePrefix": "dd-cookie-monster"

```

### Expected behavior

```console
200

cookie name: dd-cookie-monster.AspNetCore.Identity.Application
```
OR
```console
200

cookie name: dd-cookie-monster.department.psuBlank.AspNetCore.Identity.Application
```

### Actual behavior

```console
Request URL:
https://svcs.dev.myDomain.com/department/psuBlank/api/v1/signin?returnUrl=/department/psuBlank/admin
Request Method:
POST
Status Code:
500 Internal Server Error

RESPONSE:
Invalid cookie name: dd-cookie-monsterdepartment/psuBlank.AspNetCore.Identity.Application (Parameter 'value')
```

### Additional Environment data

we are trying to deploy in to k8s, and it has a double nested path. if it would turn the / into . that might also help.

**Comment by adamdriscoll** [comment]
There's not much you can do aside from making the base path 1 segment. We trim off the starting\ending / but don't replace all the slashes in the string. That said, this is a super easy fix on our end. I can get it in a nightly tonight and will be available in next monday's build.

**Comment by Omzig** [comment]
> There's not much you can do aside from making the base path 1 segment. We trim off the starting\ending / but don't replace all the slashes in the string. That said, this is a super easy fix on our end. I can get it in a nightly tonight and will be available in next monday's build.

ya, my hands are tied on the base path being 2 segments :(, or do we need something like CookieOverrride?

**Comment by Omzig** [comment]
@adamdriscoll, you have no idea how much this means to me. Thank you so much man.

**Comment by Omzig** [comment]
@adamdriscoll, THANK YOU SO MUCH!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by Omzig** [comment]
@adamdriscoll, does it matter that the cookie now starts with a `.`?
