### ISSUE TITLE
New-UDTable - error when data only contains one object [2.1.3]

### ISSUE THREAD

**Issue by psott** [ironmansoftware/powershell-universal#331]
```
$Data = @(
        @{Dessert = 'Frozen yoghurt'; Calories = 159; Fat = 6.0; Carbs = 24; Protein = 4.0}
 ) 

New-UDTable -Data $Data
```

![image](https://user-images.githubusercontent.com/22870453/127274665-e11f2c46-ebc7-43c6-9151-4ec452541c73.png)

Workaround is to add an empty object if $data-count -eq 1

Version Number: 2.1.3
Dashboard Framework (if applicable): 3.5.1

**Comment by adamdriscoll** [comment]
Releasing a new build because of this. 2.1.4 should be available shortly.
