### ISSUE TITLE
DataGrid OnEdit giving duplicate keys in newRow

### ISSUE THREAD

**Issue by RockoTheeHut** [ironmansoftware/powershell-universal#3316]
### Version

4.2.20

### Severity

Low

### Environment

msi

### Steps to Reproduce

I create a data grid with columns that are editable. Source of data is a sql query datarow[] converted to a selected data rows array inside of -LoadRows.  I edit a column, the test popup shows, and the value I just edited to reverts back to the original value. The example below is updating the myid column. 

I output $EventData to a file to review, and the field I changed, MYID, has duplicates in the newRow object. When I convert from json I have to output as -ashashtable because of the duplicate keys.

The other question I have is that both $Body and $EventData are json strings. Is the newRow and oldRow data available as an object instead of a json string? 

-LoadRows :

[hashtable]$P_Query = @{
    ServerInstance = 'myinstance'
    Query          = "select ....."
}
[system.data.datarow[]]$Results = Invoke-SQLQuery @P_Query
[String[]]$Names = ($Results[0] | Get-Member -MemberType Property).Name
[array]$Data = $Results | Select-Object -Property $Names

$Data | Out-UDDataGridData -Context $EventData -TotalRows $Data.Length

-Columns : 

New-UDDataGridColumn -Field Server -MinWidth 400
New-UDDataGridColumn -Field Platform
New-UDDataGridColumn -Field myid -Editable $true
New-UDDataGridColumn -Field DisbursementCode -Editable $true  -MinWidth 100 -HeaderName DisbCode

### Expected behavior

```console
No duplicates and that the value of the column / cell I changed is updated
{
    "newRow": {
        "myid": "12346",
        "disbursementCode": "123456",
        "id": 1612612,
        "platform": "myplatform",
        "server": "myserver"
    },
    "oldRow": {
        "mYID": "1234",
        "disbursementCode": "123456",
        "id": 1612612,
        "platform": "myplatform",
        "server": "myserver"
    }
}
```

### Actual behavior

```console
{
    "newRow": {
        "myid": "12346",
        "mYID": "1234",
        "disbursementCode": "123456",
        "id": 1612612,
        "platform": "myplatform",
        "server": "myserver"
    },
    "oldRow": {
        "myid": "1234",
        "disbursementCode": "123456",
        "id": 1612612,
        "platform": "myplatform",
        "server": "myserver"
    }
}
```

### Additional Environment data

4.2.21
Windows 2022
SQL Server 2022

**Comment by RockoTheeHut** [comment]
Interesting, I changed it to query before the datagrid and only pass the variable $Data in. Same thing. I then looped through the data rows and created both a hashtable array and then a pscustomobject array and same thing. 

When I changed MYID to lower case and ran it, the field then stayed as is, but $Eventdata was then an object instead of a json string like $Body is. $Body is a json string no matter.

With that, it looks like me having an all upper case column name causes the issue. Changing it to all lower case fixes it. Further, I tried a bunch of different combinations, and if I have more than one capital letter in the column name then it fails. More specifically, The only capital letter that does not cause the bug is the first letter. If I have  capital in the name anywhere but the first letter, it fails.

Myid = works
myid = works
mYid = bug
MYID = bug
myiD = bug
mYId = bug

**Comment by adamdriscoll** [comment]
Thanks for all the research. We've got a patch for this. $Body will also be a string. $EventData should be an object but it uses ConvertTo-Json in the backend and it was failing so that's why it ended up being a string in the error cases.
