### ISSUE TITLE
Windows auth: $Roles and $ClaimsPrincipal are null on dashboards

### ISSUE THREAD

**Issue by mikedhanson** [ironmansoftware/powershell-universal#3324]
### Version

4.2.20

### Severity

Low

### Environment

msi

### Steps to Reproduce

https://docs.powershelluniversal.com/platform/variables#apps

I am trying to get the user roles to make some items on the dashboard/app a bit more dynamic, such as navigation. I am using Windows auth and running the latest version as a service. 

```powershell
# Store pages in an empty array
$Pages = @()

$Params = @{

    Url     = "/printer"
    Name    = "printer"
    Role = $CustomRole
    Content = { . .\dashboards\Printer.ps1 }
    Title   = "Printer GPO Request"
    Icon    = (New-UDIcon -Icon "print")
}
$Pages += New-UDPage @Params


$Dashboard = @{
    Title            = 'ATG'
    Pages            = $Pages
    LoadNavigation   = $Navigation
    NavigationLayout = 'Permanent'
}

New-UDApp @Dashboard

```

https://docs.powershelluniversal.com/platform/variables#apps

Looking over the following docs I should be able to use $Roles and $ClaimsPrincipal to view information about the user. I am able to use the $User to get the users SAM. 

### Expected behavior

```console
Roles should contain the roles for the user and or claims
```

### Actual behavior

```console
Nothing
```

**Comment by mikedhanson** [comment]
Update if you do something like this inside a page you can see the values

 New-UDCard -Title "Roles" -Content {
        $ClaimsPrincipal.Claims | Out-String
    }

**Comment by mikedhanson** [comment]
Looks like $Roles and $ClaimsPrincipal are not accessible from the root dashboard script but they are accessible from the apps pages. Is this by design?

**Comment by adamdriscoll** [comment]
@mikedhanson - That's by design. The root dashboard script is run when the dashboard starts and not when a user logs in.

**Comment by mikedhanson** [comment]
Makes sense. I was attempting to make navigation a bit dynamic depending who was viewing the dashboard. Also being able to change the titles and other New-UDApp values

**Comment by adamdriscoll** [comment]
You should be able to use LoadNavigation because it has access to $Roles. Same with the -LoadTitle parameter of New-UDPage.

**Comment by mikedhanson** [comment]
Do you have an example?

This is what I was using

$Dashboard = @{
    Title            = 'Service Delivery'
    Pages            = $Pages
    LoadNavigation   = $Navigation
    NavigationLayout = 'Permanent'
}

New-UDApp @Dashboard

**Comment by adamdriscoll** [comment]
Add the role to both the navigation and to the page. 

```
$Navigation = {
    New-UDListItem -Label "Test" -Href '/test'
    Protect-UDSection -Role @("Admin") -Content {
        New-UDListItem -Label "Test" -Href '/test2' 
    }

}

$Pages = @()
$Pages += New-UDPage -Name 'Test' -Content {
 New-UDTypography -Text "Test"
} -NavigationLayout permanent -LoadNavigation $Navigation 

$Pages += New-UDPage -Name 'Test2' -Content {
    New-UDTypography -Text "Test2"
} -NavigationLayout permanent -LoadNavigation $Navigation -Role @("Admin")


New-UDApp -Title "Hello, World!" -Pages $Pages
```
