### ISSUE TITLE
buttongroup dropdown in datagrid is hidden behind footer

### ISSUE THREAD

**Issue by timoline** [ironmansoftware/powershell-universal#3327]
### Version

4.2.20

### Severity

Low

### Environment

msi

### Steps to Reproduce

buttongroup dropdown in datagrid is hidden behind footer

### Expected behavior

```console
show the dropdown over the footer of datagrid
```

### Actual behavior

```console
dropdown is hidden behind footer of datagrid
```

### Screenshots/Animations
correct
![image](https://github.com/ironmansoftware/issues/assets/680252/9b8663ee-20ad-4670-9bfe-23a8b19b2648)

wrong
![image](https://github.com/ironmansoftware/issues/assets/680252/233cc118-4bb5-4dd6-b8ac-06742b7d2ab5)
![image](https://github.com/ironmansoftware/issues/assets/680252/e981aacf-596c-4b6f-ae3d-0f469749289a)

**Comment by ScheeleRxNL** [comment]
Yes, I have the same problem here, it is quite annoying.
