### ISSUE TITLE
Documentation: Linux\Mac Windows Authentication

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3336]
### Summary of the new feature / enhancement

We are not entirely sure if this is possible but want to do some research into it. The issue is that on Linux\Mac machines, windows auth does not prompt for credentials and simply returns a blank page with a 401 error. The server is domain joined and running windows. The clients are not domain joined.

**Comment by rwidmark** [comment]
Don't understand? When ca you not auth with Mac?
You can use certificate or IDP?

**Comment by adamdriscoll** [comment]
Only windows auth. It just doesn't auth. They want single sign on.

**Comment by adamdriscoll** [comment]
I realize we have a KB for this: https://support.ironmansoftware.com/portal/en/kb/articles/kb0017-windows-auth-checklist

6 - 6) If you are using a Chromium-based browser, is it correctly identifying the PowerShell Universal website as intranet? 
Chromium will not pass Windows credentials if it does not detect the website as an intranet site. You can work around this by setting Chromium policies to force the system to send the credentials. 
You can read more about this setting here: https://chromeenterprise.google/policies/#AuthServerAllowlist
