### ISSUE TITLE
issues with VScode extension v4.2.3 on 5.0.0-beta4

### ISSUE THREAD

**Issue by alexrgreenwood** [ironmansoftware/powershell-universal#3339]
### Summary of the feedback

the config folders are blank 

![image](https://github.com/ironmansoftware/issues/assets/23561607/d70da89b-8de6-4f1f-8836-bdf4ff56ffba)

also on connecting the following error is generated

```
Install-UniversalModule -Version '5.0.0-beta4'
Import-Module: Cannot bind parameter 'RequiredVersion'. Cannot convert value "5.0.0-beta4" to type "System.Version". Error: "The input string '0-beta4' was not
in a correct format."
Install-Module: The '-AllowPrerelease' parameter must be specified when using the Prerelease string in MinimumVersion, MaximumVersion, or RequiredVersion.
Import-Module: Cannot bind parameter 'RequiredVersion'. Cannot convert value "5.0.0-beta4" to type "System.Version". Error: "The input string '0-beta4' was not
in a correct format."
```

**Comment by alexrgreenwood** [comment]
Hi Adam , I see you made this [commit ](https://github.com/ironmansoftware/universal-code/commit/ef44b8cf6b80927e05a7138db18726d67cf806cd)
any chance of incrementing the version and deploying to marketplace so i can try it out ?

**Comment by adamdriscoll** [comment]
Whoops. Didn't notice that the deployment failed. Done. In the pipeline now.
