### ISSUE TITLE
Update v5 doc with PostgreSQL

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3341]
### Version

5.0.0-beta4 (5/17/2024)

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

set beta4 to use postgres plugin

### Expected behavior

```console
success
```

### Actual behavior

```console
No database plugins found.
```

**Comment by adamdriscoll** [comment]
You need to use the plugin name: PostgreSQL 

That said, we do have an issue with Postgres in this release. We will have it fixed in v5-beta5

**Comment by Omzig** [comment]
Plugin doc is wrong then ;), the connection string is also an mssql connection not postgres ;)
https://docs.powershelluniversal.com/v/v5/config/persistence#postgresql

![image](https://github.com/ironmansoftware/issues/assets/1987296/61fbb640-8397-412e-8b4c-3f65e404fc3f)
