### ISSUE TITLE
Add license file path via env var for containers

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3343]
### Summary of the new feature / enhancement

i would like to add a layer for my license and allow us to point the environment path to the license or load the text of the license in the env var so that we can get those added to the container

**Comment by adamdriscoll** [comment]
You can use the PSULICENSE environment variable for this. The value should be the license text and not the path.

**Comment by Omzig** [comment]
> You can use the PSULICENSE environment variable for this. The value should be the license text and not the path.

i guess we are missing doc on it, cause i cannot find that in the doc :(

**Comment by adamdriscoll** [comment]
I added it to the docs here: https://docs.powershelluniversal.com/licensing#install-a-license
