### ISSUE TITLE
DefaultValue RadioGroup doesnt work with a variable value

### ISSUE THREAD

**Issue by ScheeleRxNL** [ironmansoftware/powershell-universal#3367]
### Version

4.2.21

### Severity

Low

### Environment

IIS

### Steps to Reproduce

I having issues with the defaultvalue of the radiogroup. When I use the defaultvalue parameter with a variable it doesnt work. If i use the parameter with singlequotes en the same value as the variable hardcoded it works.

WORKING = -DefaultValue 'example'
NOT WORKING = -DefaultValue $Example ($Example has the value "Example")

### Expected behavior

```console
because it is a string parameter, I expect that I can use a variable instead of single quotes.
```

### Actual behavior

```console
only works with single quotes
```

**Comment by ScheeleRxNL** [comment]
It works with variable but only when the variable is created outside the new-udradiogroup. when you create a variable inside his children then it is not usable. even if the variable scope is page.

**Comment by rwidmark** [comment]
If you create it inside you need to populate a session variable with it.
Then you have it

**Comment by adamdriscoll** [comment]
You have to create it outside the radio group. This is a scoping problem. The radio group is created fix and then the items in the group are created. This means the variable won't be set until after the default value has been defined. 

Changing the scope type won't matter.
