### ISSUE TITLE
show inherited schedule information for jobs

### ISSUE THREAD

**Issue by alexrgreenwood** [ironmansoftware/powershell-universal#3373]
### Summary of the new feature / enhancement

As a user that runs a lot of jobs , I share schedules by calling a master script for a particular frequency 
for example I might have scripts 100 scripts called by a script called "daily" , and 30 called by a script called "monthly"
as below
```
$script = 'FOLDER\script.ps1';Invoke-PSUScript -Script $script -Integrated | Wait-PSUJob -Integrated
$script = 'FOLDER\script2.ps1';Invoke-PSUScript -Script $script -Integrated | Wait-PSUJob -Integrated
...
$script = 'FOLDER\script100.ps1';Invoke-PSUScript -Script $script -Integrated | Wait-PSUJob -Integrated

```
however all the child scripts would appear to have no schedule attached to them

### Proposed technical implementation details (optional)

it would be nice if the job would figure out that it was called by a parent job and show the parents schedule in the schedule tab

also the current description says "run manually by admin" , showing the parents schedule name there would help

**Comment by adamdriscoll** [comment]
Related to #3796
