### ISSUE TITLE
Unable to delete the license when in One-Way git mode

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3375]
### Version

5.0.0-beta5 (9424572094)

### Severity

Low

### Environment

Nested IIS

##  with git settings set to One-Way, i am unable to delete the license

![image](https://github.com/ironmansoftware/issues/assets/1987296/90097d58-8f4c-4aef-b3a7-3a3fa4bdd8f2)

## Unable to toggle git to Two-Way:
![image](https://github.com/ironmansoftware/issues/assets/1987296/22a52fad-2c79-4ff3-a4f6-1c6e5391246a)

### Expected behavior

```console
clickable button
```

### Actual behavior

```console
disabled button
```

**Comment by Omzig** [comment]
# Build 9508507924
Still unable to delete while in One-Way git mode:
![image](https://github.com/ironmansoftware/issues/assets/1987296/a1e29306-b6b2-41f4-868f-225ab167dc59)

**Comment by adamdriscoll** [comment]
Ran into this earlier. This will be fixed in tonight's build.
