### ISSUE TITLE
Per-Branch Resources

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3379]
### Summary of the new feature / enhancement

We have implemented this in version 5 but are being asked to port back to version 4. The concept is that resources like scripts, schedules, APIs and apps can be restricted to a set of branches. For example, if a dashboard still in development, it could have restriction to only be shown in the development environment. In the prod environment, the code would still be present within the repository but the resource itself would not be accessible by the end users. 

This helps to simplify the development process by allowing for merges of incomplete resources to prod without the end users seeing them.

**Comment by RockoTheeHut** [comment]
If I’m reading this right this is just for new resources?

**Comment by adamdriscoll** [comment]
You could potentially do this for existing resources, but I think the intention is to apply branch restrictions to resources that are still in development so it likely would just be new resources. If no branch restriction is set, it will be available in all environments.,
