### ISSUE TITLE
SystemLogPath read from secondary appsettings.json

### ISSUE THREAD

**Issue by alexrgreenwood** [ironmansoftware/powershell-universal#3381]
### Summary of the feedback

If i start the exe with my own custom appsettings.json in my project directory 

`Start-Process .\Universal.Server.exe -ArgumentList @("--appsettings","appsettings.json")`

changing things under the "Data" node works fine , e.g. I can switch to another backend database 

changing either of   `SystemLogPath`  or  `SystemLogLevel` in the appsettings file im pointing to has no effect , only changing the value in C:\ProgramData\UniversalAutomation or the one in the application root folder makes it change

I notice that the exe logs these two lines as its first output

```
appsettings file exists: appsettings.json
appsettings file exists: appsettings.json
```

my expectation would be that if just reads one file and if it cant find the data it needs then it should not start , but it seems to be reading from multiple locations and not using the overrides that im setting , maybe i have misunderstood something about how these files interact ?

**Comment by adamdriscoll** [comment]
This should be working as you expect. The settings in the files are merged together but the command line one should take priority over the others. I tried this myself and didn't see this behavior. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/28122d1e-8603-4e2d-8c72-61918d82bd8b)


```
"--appsettings C:\src\universal\test-configs\systemlog.json"
```

```json
{
    "SystemLogPath": "%ProgramData%\\PSU\\systemLog.txt"
}
```

**Comment by alexrgreenwood** [comment]
Thanks Adam , 
I think i was trying to use relative paths and it wasn't using them and then falling back to the defaults

I had another go and got things working using environment variables (using the new -Enviroment parameter of Start-Process) - I think I prefer that way to override the defaults

https://gist.github.com/alexrgreenwood/afdb19382d0b7bf45db5ad20f646e97e

weirdly though using those settings I still get a small log file in %ProgramData%, this is not a show stopper but its unclear as to why there are 3 log files generated, maybe adjusting the naming could help with that...
![image](https://github.com/ironmansoftware/issues/assets/23561607/e6040c9c-8f49-48d8-b247-ca7210fc3949)




also get the following path error (think related to [this](https://github.com/ironmansoftware/issues/issues/3113))

```
[12:16:30 INF] Finished heartbeat job.
[12:16:30 INF] Starting module discovery using Process.
[12:16:30 ERR] Error discovering modules
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Users\alex\Documents\Projects\PSU_simple\UniversalApp\Agents\5.1\Universal.Agent' with working directory '.\Repository'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at UniversalAutomation.JobProcessManager.StartProcessAsCurrentUser(String powerShellPath, String commandLine, Variable credential, Action`1 onAgentOutput, Dictionary`2 environmentVariables) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\JobProcessManager.cs:line 468
   at UniversalAutomation.JobProcessManager.StartModuleDiscovery(ExecutionEnvironment environment) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\Automation\JobProcessManager.cs:line 344
   at Universal.Server.Services.ModuleService.Discover(ExecutionEnvironment environment) in C:\actions-runner\_work\universal\universal\src\Universal.Server\Services\ModuleService.cs:line 324
[12:16:30 INF] Starting module discovery using Process.
[12:16:30 INF] Startup complete.
[12:16:42 INF] PowerShell Universal performance counters do not exist.
```

also just noticed that the logpath thing behaves differently if the Repository folder exists , if it exists then you get logs and another repository folder under the existing repository folder. So you end up with this 

![image](https://github.com/ironmansoftware/issues/assets/23561607/d1f73214-f221-42e3-b39c-ea962c5ac255)

**Comment by adamdriscoll** [comment]
It doesn't seem to be creating the nested repo any more when I try your script. The issue with the Win32Exception will be fixed in tonight's build. The log.txt is the User scoped log. I've renamed it to UserLog.txt so you will have SystemLog.txt and UserLog.txt. 

You will need to update your test script to pull the release candidates:

```
Where-Object { $_.Name -like "*Universal.win-x64.5.0.0-rc*" -and $_.Name -like "*.zip" } |
```
