### ISSUE TITLE
No configuration found for event hub Agent

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3384]
### Version

4.2.21

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

trying to use the https://docs.powershelluniversal.com/api/event-hubs
- installed event hub agent on another machine
- configured %ProgramData%\PowerShellUniversal\eventHubClient.json

### Expected behavior

```console
connected
```

### Actual behavior

```console
2024-06-11 15:37:24.220 -05:00 [ERR] No configuration found.
```

**Comment by adamdriscoll** [comment]
I can't reproduce this. 

![image](https://github.com/ironmansoftware/issues/assets/1256531/10d4eb39-6c47-4948-b555-8623e4c9e72a)

I used configuration straight from the docs. 

```
2024-06-19 09:21:44.684 -05:00 [INF] Connected to server http://localhost:5000 at hub eventHub.
```

**Comment by Omzig** [comment]
/sigh, maybe i did something dumb.... setup a support call? maybe it will only be a 10min thing?

**Comment by adamdriscoll** [comment]
I could schedule something later. One thing I would check would be to look in event viewer. I noticed the error you are seeing in the log file because the service first started without the config file. Then I created it but didn't have the server running. The event hub client service crashed but didn't log to the log file. The event log had a clear error message.

**Comment by Omzig** [comment]
event viewer: Service started successfully.

**Comment by adamdriscoll** [comment]
Circling back on this one... 

I added a bunch more logging to v5 event hubs to make it easier to diagnosis this. I also had a hard time getting them configured. 😵‍💫 Can you also share the JSON file?

**Comment by adamdriscoll** [comment]
Let's finally get this scheduled because I want to look at: 

- #3384
- #3386
- #3574
- #3577

I can't reproduce any of these items and need to see what I'm missing.

**Comment by Omzig** [comment]
when do you want to work on it?

**Comment by Omzig** [comment]
remove the .txt from the file /facepalm
