### ISSUE TITLE
eventhubs do not work in iis

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3386]
### Version

4.2.21

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

- setup an eventhub
- connect from another computer
```
Connect-PSUEventHub -ComputerName 'https://dev.psu.domain.com/psuSandbox' -Hub 'StageEventhub' -ScriptBlock {
     Write-Host "Event Received 2"
}
```
- setup an automation script in psu
```
Send-PSUEvent -Hub 'StageEventHub' -Data "Hello!"
```

### Expected behavior

```console
should function the same way as port 5000 when running an msi
```

### Actual behavior

```console
event trigger doesn't happen
```

**Comment by adamdriscoll** [comment]
I believe we got this working. Please let me know, if not.
