### ISSUE TITLE
v5 Notifications

### ISSUE THREAD

**Issue by alexrgreenwood** [ironmansoftware/powershell-universal#3387]
### Summary of the feedback

Is currently creating an entry for **_every job run_** , this is different to how v4 worked (only system errors would generate an alert)

![image](https://github.com/ironmansoftware/issues/assets/23561607/136e24e7-538e-4265-9fcd-def65b8e21ac)

clicking "clear notifications" removes them from the view notifcations page but the **_big red spot remains_**

**Comment by alexrgreenwood** [comment]
sorry just to clarify , the red dot does go away but only after full (f5 or reload) page refresh

**Comment by adamdriscoll** [comment]
I've noticed this as well. Thanks for bringing it up. The notification for jobs starting was always there but we had 2 different colors for the notification in v4. I'll get that added back in as well.

**Comment by alexrgreenwood** [comment]
is it that this setting is missing ?

![image](https://github.com/ironmansoftware/issues/assets/23561607/2fae2c6f-2661-4240-8531-00284f4c5481)

**Comment by adamdriscoll** [comment]
Yeah that is probably the issue. I'll resolve that as well.
