### ISSUE TITLE
string[] parameters do not work with ValidateSets

### ISSUE THREAD

**Issue by jantari** [ironmansoftware/powershell-universal#34]
#### Description

When defining a script with a `string[]` parameter and a ValidateSet on that parameter,
I am only able to chose one of the items in the ValidateSet in the GUI. I cannot enter more than 1.

#### Additional Information

Example script:

```powershell
Param (
    [Parameter( Mandatory = $true )]
    [ValidateSet('server01', 'server02')]
    [string[]]$DCs
)

$DCs | % {
    Write-Host "$_"
}
```

#### Version Information

- Universal: 1.5.1
- Universal Hosting Method (IIS, Executable, docker etc): Executable from ZIP
- PowerShell: 5.1.17763.1490
- Operating System: Windows Server 2019 Core

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by rbleattler** [comment]
@adamdriscoll Let me know if you want this to be a separate bug, but... 
Likely closely related to this: When using String[] parameters, selecting _one_ in the GUI seems to result in the first parameter (regardless of whether it is the correct one) being used. When invoked from the cli, and the value enclosed in an array, the correct value is used. 
IE:
```powershell
Invoke-UAScript -Id 11 -Environment Core -EnvironmentType @('Development')
```
![image](https://user-images.githubusercontent.com/40604784/112036584-2ec36c80-8b17-11eb-8f0c-20541b2e0246.png)
