### ISSUE TITLE
"Page Not Found" When User Doesn't Have Role to Access Page

### ISSUE THREAD

**Issue by GeoffOrlebeck** [ironmansoftware/powershell-universal#340]
_If this is too similar to issue 286 (https://github.com/ironmansoftware/issues/issues/286), please close._

When a page has RBAC defined (via "**-Role _@('RoleName')_**") and an unauthorized user visits the URL they see "Page Not Found". That's incorrect or at least a bit misleading. Can it instead present the same "not authorized" message a user sees when visiting a dashboard to which they don't have access?

For a page that **does** exist, where the user has dashboard access, but not page access they see this for a page they are unauthorized to view:
![01_Current](https://user-images.githubusercontent.com/82668592/128226907-efd350f8-bd4c-4b8f-b84d-8f8c63afe2c5.png)

Instead can it be this message?
![02_Proposed](https://user-images.githubusercontent.com/82668592/128226987-b21f436c-2053-4b22-b1e7-28093604b05f.png)

**Comment by Viajaz** [comment]
Might be useful to have this as an option, it can sometimes be useful to obfuscate the existence of endpoints as part of a multi-layered security approach.

**Comment by rwidmark** [comment]
I second this

**Comment by adamdriscoll** [comment]
@Viajaz - This is currently why it behaves the way it does. I agree an option might be nice.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/new-udpage-onaccessdenial-parameter/6826/2

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/new-udpage-onaccessdenial-parameter/6826/3

**Comment by adamdriscoll** [comment]
We have added -PageNotFound and -NotAuthorized parameters to New-UDDashboard to allow for specifying custom pages. If you don't specify -NotAuthorized, it will continue to display the Page Not Found page.
