### ISSUE TITLE
WebSocket Health Check Fails in PowerShell Universal with IIS Integration

### ISSUE THREAD

**Issue by RubenT91** [ironmansoftware/powershell-universal#3404]
### Summary of the new feature / enhancement

When integrating PowerShell Universal with IIS, the health check for the WebSocket feature fails. This issue appears to be related to permissions or configuration settings, particularly when attempting to clear a specific WebSocket class. The failure does not impact the core functionality but affects notification-related features.

### Proposed technical implementation details (optional)

To ensure seamless integration and functionality of PowerShell Universal with IIS, we need to:
1. Identify and document the necessary configuration settings and permissions for enabling WebSocket Protocol in IIS.
2. Update the health check mechanism to handle scenarios where WebSocket configuration might not be straightforward.
3. Provide clear guidance in the documentation to prevent similar issues for other users.

Proposed Technical Implementation Details:

Investigation:

- Analyze the current health check mechanism for WebSocket Protocol in PowerShell Universal.
- Determine the exact cause of the health check failure when clearing the WebSocket class.

Configuration and Permissions:

- Ensure that the service account running PowerShell Universal has the necessary permissions to use the WebSocket Protocol.
- Validate that WebSocket Protocol is enabled and properly configured in IIS.

Documentation Update:

- Create a comprehensive guide detailing the steps to enable and configure WebSocket Protocol in IIS for PowerShell Universal.
- Include troubleshooting steps and common issues related to WebSocket configuration.

**Comment by adamdriscoll** [comment]
I've updated the docs: https://docs.powershelluniversal.com/platform/health-checks#iis-websocket

I've also updated the health check to give a clearer error message.
