### ISSUE TITLE
MSIs are not signed properly

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3411]
### Version

4.3.0

### Severity

Low

### Environment

msi

### Steps to Reproduce

This happened with the last release and then we got it working. But now it stopped working again. signtool is returning an internal error and failing to sign the MSI. Set-AuthenticodeSignature is working with the same certificate to sign the modules. 

### Expected behavior

```console
Signed MSIs
```

### Actual behavior

```console
Failure to sign MSIs.
```

**Comment by DataTraveler1** [comment]
Impacted versions:

4.3.0, 5.0.0-beta4, 5.0.0-beta5, 5.0.0-beta6

![image](https://github.com/ironmansoftware/issues/assets/537287/d5fb20d8-a069-4da4-b5d1-601be8d0edb8)
