### ISSUE TITLE
Page can conflict with Endpoint URL

### ISSUE THREAD

**Issue by mwatts-seg** [ironmansoftware/powershell-universal#342]
**Describe the bug**
I tried to create a HelloWorld page to just play around with it. System allowed me to do so, but when clicking 'view' to bring up the editor I got the "Hello World! This worked!" page. Deleting the page this still works, so I am guessing it is something built in.

**To Reproduce**
1. Go to 'Pages'
2. Click on 'Create New Page'
3. Name HelloWorld
4. Save
5. Click globe icon to visit

**Expected behavior**
HelloWorld should be available for end user or reserved to not allow use. 

**Screenshots**
None

**Version**

Version Number: 2.2.0
Dashboard Framework (if applicable): 
Operating System: Windows Server 2019

**Additional context**
None

**Logs** 
Let me know if you need a log.

**Comment by adamdriscoll** [comment]
@mwatts-segops - I tried to reproduce this but don't see this issue. Can you let me know if you have any dashboards or APIs defined with /helloworld?

**Comment by mwatts-seg** [comment]
> 
> 
> @mwatts-segops - I tried to reproduce this but don't see this issue. Can you let me know if you have any dashboards or APIs defined with /helloworld?

Hmmm At first I was going to beat myself if I actually had something setup for helloworld, but can confirm that I do not. 
"Hello World! This worked!" is what is produced when I visit http://myserver:5000/helloworld

Here is a list of dashboard URLs I have setup: 

- /dashboardST
- EEBrokerMessageFlowDashboard
- COVID19Dashboard
- /dashboard (This was a test)
- /PT7DCOPSdashboard
- /Bannerdashboard
- /ReplayFiles
- /ADInfodashboard
- /fte
- /SamsPortalPlusDashboard
- /NoOffersdashboard

The pages (just testing) 
- /Test2
- /PendingPOSFiles 
- There was a /helloWorld that I was trying to test.

**Comment by adamdriscoll** [comment]
So weird. I just searched the whole code base and the string "Hello World! This worked!" doesn't exist. There are gremlins somewhere 😱

Let me think of how to troubleshoot this...

**Comment by mwatts-seg** [comment]
@adamdriscoll - Man, I am so sorry, but I found the issue. Another admin (a gremlin) was playing with APIs and guess what, they created an API called, 'Hello World'. I did a search for the string with AgentRansack and found .endpoints.ps1 containing the string. I guess the real issue is that it let me create the name of a page when an endpoint had that same name? Thoughts? Thank you again!

**Comment by adamdriscoll** [comment]
Ah, ok! Yeah we should improve this. It shouldn't allow the creation of 2 things with the same URL. Let's leave this open. I'll rename this issue to adjust for what's happening.
