### ISSUE TITLE
Location of error log when the PSU MSI installer fails

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#3423]
### Version

5.0.0-betaX

### Severity

Low

### Environment

msi

### Steps to Reproduce

There appears to be an erroneous message in the MSI installer when a fatal error occurs. 

![image](https://github.com/ironmansoftware/issues/assets/537287/5f16c68f-4b3b-4e8a-bdc0-8f1bc6ea086d)

### Expected behavior

```console
The MSI installer should show the location of the corresponding log when it fails
```

### Actual behavior

```console
The MSI installer may not show the location of the corresponding log when it fails
```

### Additional Environment data

For extra context, the content of the MSI log file is below. I believe the root cause of the error is a health issue on the server and not related to PSU itself.

`Error 1923. Service 'PowerShell Universal' (PowerShellUniversal) could not be installed.  Verify that you have sufficient privileges to install system services.`

### Screenshots/Animations

![image](https://github.com/ironmansoftware/issues/assets/537287/446b4ea0-18d5-42c4-8e90-e0cb68e039b7)
###### figure shows the MSI fatal error message with the updated log location

**Comment by adamdriscoll** [comment]
This error is correct as that location may contain more information about why the install failed. That said, I can enhance this message to also reference the MSI log.
