### ISSUE TITLE
New-UDDatePicker - shows year when clicking a day

### ISSUE THREAD

**Issue by dbytes** [ironmansoftware/powershell-universal#3429]
### Version

4.3.0

### Severity

Low

### Environment

msi

### Steps to Reproduce

Click any day on the New-UDDatePicker component and observe the selection then displays the year selection.  This behavior was not observed in older versions and it is unknown when changed.  Forum discussion at https://forums.ironmansoftware.com/t/new-uddatepicker-shows-year-when-clicking-a-day/10886/3

### Expected behavior

```console
Click a day and doesn't go to the year selection.  See https://mui.com/x/react-date-pickers/date-picker/ for reference.
```

### Actual behavior

```console
See screen capture provided.
```

### Screenshots/Animations

![54601d7ee7266a6507d0a777ea28aa7bcae3a836](https://github.com/ironmansoftware/issues/assets/33239764/6e1ca32f-97ee-4722-acb5-10621cb194e7)

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/new-uddatepicker-shows-year-when-clicking-a-day/10886/7
