### ISSUE TITLE
Posh Pro Tools > Visual Studio Code > Variable Explorer Exclusions

### ISSUE THREAD

**Issue by rhochmayr** [ironmansoftware/powershell-universal#343]
**Is your feature request related to a problem? Please describe.**
Currently the variables explorer in the sidebar is also showing all automatic_variables, which is rarely usefull and clogging up the view quite a bit. This makes it quite hard to quickly locate the actual variable sought-after.

More infos on automatic variables can be found here:
[https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-5.1](url)

**Describe the solution you'd like**
The nicest solution would probably be a checkbox setting like the following

Posh Pro Tools › Side Bar: Variable (Automatic Variables Exclusion)
"Exclude automatic variables from beeing displayed in variable sidebar"

`"poshProTools.sideBar.excludeAutomaticVariables": true`

When enabled the setting automatically excludes all known automatic variables.

**Describe alternatives you've considered**
An alternative option would be to provide a setting similar to "Posh Pro Tools: Ignored Variables"
A delimited list of variables could be entered by the user into a text field to be excluded from beeing displayed in the variables side bar.

For Example:

`"poshProTools.sideBar.excludedVariables": "$;?;^;args;ConfirmPreference;ConsoleFileName;DebugPreference;Error;ErrorActionPreference;ErrorView;ExecutionContext;false;FormatEnumerationLimit;HOME;Host;InformationPreference;input;MaximumAliasCount;MaximumDriveCount;MaximumErrorCount;MaximumFunctionCount;MaximumHistoryCount;MaximumVariableCount;MyInvocation;NestedPromptLevel;null;OutputEncoding;PID;PROFILE;ProgressPreference;PSBoundParameters;PSCommandPath;PSCulture;PSDefaultParameterValues;PSEdition;PSEmailServer;PSHOME;PSScriptRoot;PSSessionApplicationName;PSSessionConfigurationName;PSSessionOption;PSUICulture;PSVersionTable;PWD;ShellId;StackTrace;true;VerbosePreference;WarningPreference;WhatIfPreference"`

**Comment by adamdriscoll** [comment]
I've added a new setting to hide automatic variables in 5.30.0. 

"poshProTools.excludeAutomaticVariables": true
