### ISSUE TITLE
Api documentation is missing the data set in a variable

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3430]
### Version

4.3.1

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

When I set the documentation to have set variables, they are lost when rendering in swagger.

Set the documentation class like this:
```
    [Documentation()]
    class GetCredentialsType {
        [string]$title
        [string]$userId
        [string]$password = "Encrypted Password or Secret"
   }
```

### Expected behavior

```console
{
  "userId": "string",
  "password": "Encrypted Password or Secret",
  "title": "string",
}
```

### Actual behavior

```console
{
  "userId": "string",
  "password": "string",
  "title": "string",
}
```

**Comment by rwidmark** [comment]
Ping on this one

**Comment by Omzig** [comment]
@adamdriscoll, funny, i was trying to use this again, and i almost created another issue. TY for adding it to the next release ;)
