### ISSUE TITLE
Page Variable "/edit-user/:samacountname" dot work after upgrade

### ISSUE THREAD

**Issue by urskog84** [ironmansoftware/powershell-universal#3434]
### Version

4.3.1

### Severity

Low

### Environment

msi

### Steps to Reproduce

Can not get the variable $samacountname to work after upgrade from 4.2.4 to 4.3.1

i have created a simple att to list and edit ursers:

```powershell
# ./Consult.ps1
New-UDApp -Title "Conslut Portal" -Pages @(
    Get-UDPage -Name "consulte"
    Get-UDPage -Name "edit-user"
)
)
```

```powershell
#./pages/edit-user.ps1
New-UDPage -Url "/edit-user/:samacountname" -Name "edit-user" -Content {

    $userObj = Get-ADUser $samacountname
    New-UDCard -Title  "

$samacountname" -Content { New-UDElement -Tag text -Content { $userObj } }
} -Title "edit-user" 
)
```

when i den go to url https://w-pwunivers-p-1.int.stadium.biz/app/consult/edit-user/user301710
it looks like the variable **$samacountname is null** 
i expected it to bee **user301710**
![error](https://github.com/ironmansoftware/issues/assets/18033678/ac39da57-c17c-47e3-bbfc-ff20a002b108)

### Expected behavior

```console
when i den go to url https://w-pwunivers-p-1.int.stadium.biz/app/consult/edit-user/user301710
it looks like the variable **$samacountname is null** 
i expected it to bee **user301710**
```

### Actual behavior

```console
i expected it to bee **user301710**
```

**Comment by Omzig** [comment]
@adamdriscoll, this killed 90% of our apps!  As soon as this is closed, can we release 4.3.2? 4.3.1 probly should be removed ;)

# Suggestion
Maybe we can add something to the documentation /apps/docs/Page so that we can add a playwright test?
- /apps/docs/Page/:id

# Workaround
We downgraded to 4.3.0 and not it is working again.

**Comment by adamdriscoll** [comment]
We'll get this released today. As for the playwright test, we'll get this added as well but likely after the release.

**Comment by urskog84** [comment]
Hi, Have now upgraded to version [4.3.2](https://imsreleases.blob.core.windows.net/universal/production/4.3.2/PowerShellUniversal.4.3.2.msi). it works.
big thanks for the quick response.

Regarding the Dnowngrade option. how is it possible downgrade the MSI installation.. if i run an lower relase. i get an error..

**Comment by Omzig** [comment]
> Hi, Have now upgraded to version [4.3.2](https://imsreleases.blob.core.windows.net/universal/production/4.3.2/PowerShellUniversal.4.3.2.msi). it works. big thanks for the quick response.
> 
> Regarding the Dnowngrade option. how is it possible downgrade the MSI installation.. if i run an lower release. i get an error..

idk about the msi, we use IIS so we just have a script that you put the version in and boom, its upgraded or downgraded.
