### ISSUE TITLE
Ability to restrict maximum AppToken age via Grant API

### ISSUE THREAD

**Issue by ad-85** [ironmansoftware/powershell-universal#3438]
### Summary of the new feature / enhancement

I'd like to be able to allow users to grant their own app tokens (currently I supply them manually) but I do not want them to be able to exceed a certain lifetime for security reasons. There does not currently appear to be a method available to do this.

### Proposed technical implementation details (optional)

Addition of a setting, either in appsettings.json or settings.ps1 to restrict the maximum value of the `lifespanDays` parameter in the AppToken grant endpoints - `/api/v1/apptoken/grant` and `/api/v1/apptoken/grant/{id}`.

**Comment by ad-85** [comment]
https://forums.ironmansoftware.com/t/maximum-lifespan-to-allow-in-apptoken-grant-endpoint/10920

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/maximum-lifespan-to-allow-in-apptoken-grant-endpoint/10920/2
