### ISSUE TITLE
/nestedSite/apps/docs not loading

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3440]
### Version

5.0.0-beta7 (9637475131)

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

load /docs for live doc

### Expected behavior

```console
200
```

### Actual behavior

```console
404
```

### Screenshots/Animations

![image](https://github.com/ironmansoftware/issues/assets/1987296/4443fd3f-7ee1-46d9-936f-8278c19f7780)

**Comment by adamdriscoll** [comment]
This seems to be working now. 

![image](https://github.com/user-attachments/assets/4b698fd3-1788-4f4d-84c5-0169b16648e8)

**Comment by Omzig** [comment]
# Build
Beta5-rc1 (9964496085)

IIS is nested

I cannot see any errors in dev tools

![image](https://github.com/user-attachments/assets/6b212f67-45ca-4b8c-b653-73874f219be6)

**Comment by adamdriscoll** [comment]
Hmm. Weird. Let me try on a clean machine to see if I can reproduce. It works on my dev machine...but you know...

**Comment by adamdriscoll** [comment]
😵‍💫

![image](https://github.com/user-attachments/assets/49a7edb1-647d-407f-ae28-f908c38ddf99)
