### ISSUE TITLE
Dashboards constantly restart

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/powershell-universal#3442]
### Version

4.3.2

### Severity

High

### Environment

msi

### Steps to Reproduce

Unknown, there is insufficient log data.

### Expected behavior

```console
Dashboards not to restart every few minutes.
```

### Actual behavior

```console
Dashboards constantly restart every three or so minutes. The only log information is:


Creating services. 
Dashboard configuration complete. 
Starting scheduler.
```
```


### Additional Environment data

Windows Server 2022

### Screenshots/Animations

_No response_

**Comment by adamdriscoll** [comment]
This could be due to something writing to the repository folder but we would need system logs to determine that. 

Debug system logs would be useful: https://support.ironmansoftware.com/portal/en/kb/articles/kb0061-enabling-debug-system-logs

**Comment by Viajaz** [comment]
That must have been it, turning off `Auto Deploy` solved the problem (and is also an acceptable solution for us too). Not sure what changed though, everything else remains the same.

Could a log entry be made to the dashboard log if it detects a redeploy due to file change? That would make it more transparent about what is going on.

**Comment by adamdriscoll** [comment]
Yep. We should be able to add that.
