### ISSUE TITLE
$Job.Children returning all job objects

### ISSUE THREAD

**Issue by mikedhanson** [ironmansoftware/powershell-universal#3445]
I think this introduced a new bug 

Job: 14743  
![image](https://github.com/ironmansoftware/powershell-universal/assets/15201245/f9dbe523-f72d-4aa5-9619-0ef00490ea7d)

as you can see this job has 4 child jobs. None of these child jobs have children.

$Job = Get-psujob -id 14743 -UseDefaultCredentials -ComputerName http://localhost:5000 

$Job.Children.id

![image](https://github.com/ironmansoftware/powershell-universal/assets/15201245/0bc9fa27-425e-4199-80c4-7ef0961a29bb)

![image](https://github.com/ironmansoftware/powershell-universal/assets/15201245/2385d1ed-f532-4c93-bedd-a2009e5bea9c)

_Originally posted by @mikedhanson in https://github.com/ironmansoftware/powershell-universal/issues/3433#issuecomment-2214315346_

**Comment by adamdriscoll** [comment]
I can reproduce this. This is happening in over HTTP but not in the integrated environment. We'll have a fix for this in 4.3.3.

**Comment by mikedhanson** [comment]
![MusicalCockroachesGIF](https://github.com/ironmansoftware/powershell-universal/assets/15201245/2d2441e2-7823-461c-a936-39f7cab10b68)

**Comment by mikedhanson** [comment]
Still seeing this issue on 4.3.3

![image](https://github.com/user-attachments/assets/61e0ecf3-2f5b-4fd6-a806-144b8329b634)

**Comment by adamdriscoll** [comment]
I can't reproduce this. 

![image](https://github.com/user-attachments/assets/a63914fb-798a-42d5-be68-16f57c6f850c)


```
PS C:\src\universal\src> (get-psujob -Id 5).Children | measure

Count             : 4
Average           :
Sum               :
Maximum           :
Minimum           :
StandardDeviation :
Property          :

PS C:\src\universal\src> Get-PSUInformation

Version BuildVersion
------- ------------
4.3.3   {"version":"2441366528"}

PS C:\src\universal\src> Get-Module Universal

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     4.3.3                 Universal                           {Clear-PSUCache, Connect-PSUEventHub, Connect-PSU…
```

Can you try to invoke the API directly? 

```powershell
Invoke-RestMethod 'http://localhost:5000/api/v1/job?trigger=true&child=true&take=100&parentId=15170' -UseDefaultCredentials
```

It should return a Page of jobs with a total property. 

```powershell
PS C:\src\universal\src> (Invoke-RestMethod 'http://localhost:5000/api/v1/job?trigger=true&child=true&take=100&parentId=5' -Headers @{ Authorization = "Bearer $AppToken" }).Total
4
```

What's interesting is that the cmdlet now limits it to 100 child jobs so it should never return more than 100.

**Comment by mikedhanson** [comment]
@adamdriscoll - It was my issue. I never restarted my terminal and the universal module was still showing 4.3.2. After restarting the powershell process it seems to be working with 4.3.3 cmdlets

**Comment by mikedhanson** [comment]
![image](https://github.com/user-attachments/assets/11546a2c-62b4-490f-b055-2dad39a49cfc)
