### ISSUE TITLE
The supplied URL is not local

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#3448]
### Version

5.0.0-betaX

### Severity

Medium

### Environment

msi

### Steps to Reproduce

The navigation can fail sometimes when repeatedly clicking around the notifications area as seen in the attached video. PSU log also attached.

[Issue3448.log](https://github.com/user-attachments/files/16132374/Issue3448.log)

The end-user will be presented with the below error message and unable to proceed with navigating.

`The supplied URL is not local. A URL with an absolute path is considered local if it does not have a host/authority part. URLs using virtual paths ('~/') are also local.`

The PSU log includes the below message

`[ERR] Navigation failed when changing the location to /login?returnUrl=admin/platform/notifications
System.Threading.Tasks.TaskCanceledException: A task was canceled.`

### Expected behavior

```console
Navigation requests should queue if the server is busy
```

### Actual behavior

```console
Navigation requests can be rejected if the server is busy
```

### Additional Environment data

Not sure if this is relevant, the PSU environment in the video uses Windows Authentication successfully, however the workstation shown in the video is not domain joined but successfully negotiates when challenged for domain logon.

### Screenshots/Animations

![Issue3448a](https://github.com/ironmansoftware/powershell-universal/assets/537287/26a764f0-4dc2-4e3c-9b9e-391fdb0636b3)

**Comment by DataTraveler1** [comment]
I have determined that this issue can occur whether the audience workstation is domain joined or not. The issue seems to be reproducible by having Windows Authentication enabled. If Windows Authentication is disabled, the problem goes away.

**Comment by DataTraveler1** [comment]
@adamdriscoll - The problem in this scenario is worse then I understood. Once this scenario occurs, the PSU server will fail to deliver navigation requests to all clients not just the one shown in the video but other fully domain-joined workstations will also fail when browsing the PSU node. Restarting the PSU service on the node restores service.

**Comment by adamdriscoll** [comment]
Thanks for all the details. I'll dig into it.

**Comment by adamdriscoll** [comment]
@DataTraveler1  - I can reproduce this.
