### ISSUE TITLE
Groups are not listed in Claims

### ISSUE THREAD

**Issue by RubenT91** [ironmansoftware/powershell-universal#3463]
### Version

4.2.21

### Severity

Low

### Environment

msi

### Steps to Reproduce

We set up PSU and tried the SAML2 authentication - unfortunately for some users (with many groups) the groups are not listed when looking into claim information. Instead of the groups directly there is only one claim type named http://schemas.microsoft.com/claims/groups.link	with nothing but an URL to graph.windows.net
 More information in the ticket.

### Expected behavior

```console
Be able to see all the groups claims listed from PSU Security settings.
```

### Actual behavior

```console
It does work as configured with my user having 108 groups; the others where it's not working are using 200+ groups.
```

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/9e18430a-047a-469a-9cac-3ec3f7c575c3)
![image](https://github.com/user-attachments/assets/53b6b1c9-5d0e-4f7c-bfa0-c4e3f6fdfe7f)

**Comment by adamdriscoll** [comment]
Related to #2121

**Comment by adamdriscoll** [comment]
@RubenT91 - I've determined this is a configuration issue. You can limit the number of groups that Azure provides through filtering in the Enterprise Application registration or by group assignment in the Application Registration. I've updated the documentation here: https://docs.powershelluniversal.com/config/security/saml2#group-overages
