### ISSUE TITLE
query does not work when using tabs #

### ISSUE THREAD

**Issue by timoline** [ironmansoftware/powershell-universal#3467]
### Version

4.3.2

### Severity

Low

### Environment

IIS

### Steps to Reproduce

In 4.3.3 you fixed linking to tabs. :-)
But I think I found a small bug when using # in an url and query (?page=abc&test=123)

### Expected behavior

```console
Use tabs and query
ad#servers?os=2016&enabled=false
```

### Actual behavior

```console
it doesnt work, lookslike query is not good
```

**Comment by timoline** [comment]
hmmm, it lookslike its working when you put "#tab" at the end of the url
ad?os=2016&enabled=false#servers

Is this correct

**Comment by adamdriscoll** [comment]
Yep. It looks like the valid syntax is to have the hash at the end. 

https://www.rfc-editor.org/rfc/rfc3986#page-16
