### ISSUE TITLE
datagrid filter from url/$query

### ISSUE THREAD

**Issue by timoline** [ironmansoftware/powershell-universal#3468]
### Summary of the new feature / enhancement

My idea was to filter datagrid from the url. so i can make pre-defined links to a filtered datagrid for my customers.
It's already possible but its not really dynamic and it is hardcoded on every datagrid page
I think it'easier to make it default in the base code.

### Proposed technical implementation details (optional)

So that we can use all the filters from the datagrid in an url. 
And ofcourse if possible sorting too ;-)

**Comment by TurnItOff-OnAgain** [comment]
Do you have some sample code as to what you are doing, and what you expect to work? I use the $query parameter with tables and it works correctly.

**Comment by timoline** [comment]
How do you pass the $query in the cmdlet Out-UDDataGridData?
https://docs.powershelluniversal.com/userinterfaces/components/data-display/data-grid#filtering

I assume you filter the data before it goes into Out-UDDataGridData

My request is to pass $query directly to Out-UDDataGridData and let it do it's job there, the logic is already in the cmdlet
Out-UDDataGridData does not have a query/filter input at the moment as far as I can see...

**Comment by timoline** [comment]
After using custom filters/queries ,I'm not sure this fr has any benefit.
It's a nice to have, but really necessary ....no, not for now
