### ISSUE TITLE
Endpoint testing returns 401 ClientError when testing from GUI with Authentication Enabled

### ISSUE THREAD

**Issue by RockoTheeHut** [ironmansoftware/powershell-universal#3483]
### Version

5.0.0-rc2

### Severity

Low

### Environment

msi

### Steps to Reproduce

Create a basic GET endpoint that returns a dummy object. If Authentication is disabled, it works. If you add Authentication, no matter if you add roles or leave blank, the Test tab Invoke returns '401 ClientError'.

I can not find logs with the error. 

### Expected behavior

```console
Authentication is inherited from the browser session and works
```

### Actual behavior

```console
401 error
```

### Additional Environment data

Windows Server 2019, MSI, SQL Server 2022 back end, MS Entra OIDC. I have tried with environments and without environments. 

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/a4a2f19a-d069-4b16-a088-8c374c26b16d)
![image](https://github.com/user-attachments/assets/9558f889-9157-4459-8533-57d181d84497)

**Comment by adamdriscoll** [comment]
I noticed this too. It's kinda by design but we should have an easy way to use the current user's authentication and authorization. 

One reason it's like this is so that you could use another user's authorization\authentication to do some tests to make sure it's been configured properly. Right now, you'd have to set the headers and app tokens and stuff and it's just not very straight forward.

**Comment by RockoTheeHut** [comment]
Completely understand. I think up front it would be ideal to default to the current users auth. 

Looking forward it would be nice to also have something like a dropdown to quickly choose what role/token to run under. Or a way to add testing configurations per user where a user could create auth tokens, or be assigned auth tokens,  with a unique name that you could quickly choose in a dropdown for testing. Something like that... The option for adding custom headers is pretty awesome, but we won't have need of that very often.

**Comment by adamdriscoll** [comment]
Totally agree. I'll at least get the default auth in for 5.0 GA. If it's easy enough to put in some additional controls I might sneak it in but might be a 5.1 thing.

**Comment by adamdriscoll** [comment]
![image](https://github.com/user-attachments/assets/a18b8633-caef-441b-bc47-3d2c1f426187)

This was pretty easy to get in. I just added an authentication tab that allows you to set a user name and set of roles.
