### ISSUE TITLE
Search for jobs by name on /admin/automation/jobs 

### ISSUE THREAD

**Issue by mikedhanson** [ironmansoftware/powershell-universal#3485]
### Summary of the new feature / enhancement

I would like to be able to search for jobs on the jobs page by either id, name, status, tags and maybe the user that started the job? 

The search box could be right above the id and script columns 

![image](https://github.com/user-attachments/assets/e7c0733e-782e-4dc4-8842-ffd71fb8d1f1)

**Comment by adamdriscoll** [comment]
This is implemented in v5. The filtering features on the jobs page are way better. You can customize the columns that are visible and filter by most of them. There is also a search bar that currently searches script, tags and user name but we could add status as well. 

![image](https://github.com/user-attachments/assets/6e2b565c-7a8b-446a-b6b6-4b5ff6361e4e)
