### ISSUE TITLE
Schedules NextExecution is not updated

### ISSUE THREAD

**Issue by timoline** [ironmansoftware/powershell-universal#3490]
### Version

4.3.2

### Severity

Low

### Environment

IIS

### Steps to Reproduce

The NextExecution is not updated 

### Expected behavior

```console
The NextExecution is updated
```

### Actual behavior

```console
The NextExecution is not updated
```

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/fd4f5b6c-0bb8-40b0-99f6-02c159e05fc6)
![image](https://github.com/user-attachments/assets/5765a46b-eaf1-45f1-9b5a-e5e7cc2e4712)

**Comment by timoline** [comment]
![image](https://github.com/user-attachments/assets/ff30219d-57ac-417b-9da2-aa3d227a2ddc)

**Comment by adamdriscoll** [comment]
Have you tried 4.3.4? We rolled back hangfire because of an issue with time zones so I wonder if they as had a bug with next execution time.

**Comment by timoline** [comment]
hmmm, it didn't work when updating to 4.3.4, but I removed all schedules and recreated them.
Now it works again
