### ISSUE TITLE
Using user function in Dashboards

### ISSUE THREAD

**Issue by oliwex** [ironmansoftware/powershell-universal#3497]
### Summary of the new feature / enhancement

As a user i want to create dashboard with grid.Every element of grid will be dynamic element changed every random time(example: 5 seconds). My code i soo long so i divide it into functions and i have problem with passing data to UI. Example:
               function Create-ComputerCard {
                    param (
                        [string]$ComputerName
                    )

                    $avatar = if (((Get-Random -Minimum 1 -Maximum 100) % 2) -eq 1) {
                        New-UDAvatar -Content { "T" } -Sx @{ backgroundColor = "#00FF00" }
                    } else {
                        New-UDAvatar -Content { "F" } -Sx @{ backgroundColor = "#FF0000" }
                    }

                    $header = New-UDCardHeader -Title $ComputerName -SubHeader "asdasd" -Avatar $avatar

                    $logonInfo = Check-LogonSessions -ComputerName $ComputerName

                    $body = New-UDCardBody -Content {
                        New-UDList -Children {
                            New-UDListItem -Label 'sdfsfdfds' -Icon (New-UDIcon -Icon user -Size 1x) -SubTitle $logonInfo.USERNAME
                            New-UDListItem -Label 'IP' -Icon (New-UDIcon -Icon laptop -Size 1x) -SubTitle "asdsa"
                            New-UDListItem -Label 'dfsfd' -Icon (New-UDIcon -Icon leaf -Size 1x) -SubTitle "asdsadsa"
                        }
                    }

                    New-UDCard -Header $header -Body $body -Sx @{ maxWidth = 200; border = '2px solid #f0f2f5' }
                }

Rendering UI

New-UDTypography -Text "asdasdas" -Variant "h1" -Align center

New-UDGrid -Container -Children {
    $computerList = Get-Content -Path "path" -TotalCount 10
    foreach ($computerName in $computerList) {
        New-UDGrid -Item -Children {
            New-UDDynamic -Content {

                Create-ComputerCard -ComputerName $computerName
            } -AutoRefresh -AutoRefreshInterval 5
        }
    }
}

### Proposed technical implementation details (optional)

Give me an entry in documentation where the info about passing data from function is. Show me multiple examples. Or maybe repair my own code to be working, because maybe I am a noobie with Dashboards

**Comment by adamdriscoll** [comment]
I've added information on the documentation on how to use functions within apps. 

https://docs.powershelluniversal.com/apps/building-dashboards#functions
