### ISSUE TITLE
editor theme does not work in dark mode

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3502]
### Version

5.0.0-rc4

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

- goto /apps/docs/Editor
- click the +

### Expected behavior

```console
easy to read
```

### Actual behavior

```console
hard to read
```

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/3c3a4a1d-8b34-4ffd-b1f1-2d444208d88b)

**Comment by adamdriscoll** [comment]
This has the same problem in 4.3.4. We need to merge this fix back.
