### ISSUE TITLE
transfer list not working when using OnChange

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3506]
### Version

5.0.0-rc4

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

- go to /apps/docs/Transfer-List
- scroll down to OnChange
- click [x] on something
- click [>]
- then click [<<]

### Expected behavior

```console
no error
```

### Actual behavior

```console
ud-dashboard.jsx:376 An error occurred: Cannot bind argument to parameter 'Message' because it is an empty string.
Endpoint: transferlist2onChange
Session: a235eebb-86cf-4f2b-9ef7-e40060bab004, User: admin

at transferlist2onChange: line 2
at transferlist2onChange: line 1
at index.ps1 : line 65

at transferlist2onChange: line 2
at transferlist2onChange: line 1
at index.ps1 : line 65
```

### Screenshots/Animations

![2024-07-30_10-34-03](https://github.com/user-attachments/assets/9f588186-4953-4518-ae1b-d64dea0ffe7c)

**Comment by adamdriscoll** [comment]
This works the same way in 4.3.4. I think it's doing this since nothing is selected so a $null value is being send back to the toast. We should fix the example.
