### ISSUE TITLE
Card with image url broken

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3509]
### Version

5.0.0-rc4

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

- go to /apps/docs/Card
- scroll down Card with image

### Expected behavior

```console
no error
```

### Actual behavior

```console
Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.
```

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/1f57b4b8-ab54-487b-ab6e-0cb57839ad5a)

**Comment by adamdriscoll** [comment]
This has the same problem in 4.3.4. We need to merge this fix back.
