### ISSUE TITLE
Script Runner component for Pages

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#351]
Users frequently want to run scripts from dashboards. It would be great to have a simple page component that could do this. 

# Features

- Script to run (including environment, parameters, user)
- Parameter editor 
- Wait for Script to return
- Display as table
- Display as chart
- Display output of script
- Display progress

**Comment by rwidmark** [comment]
But this already exist, if I do understand it correct.

I call the script with a button in my dashboard then I get the output in a code block (don't remember the correct name here I can check later)

I even have a drop down where the user can choose what script they want to run.
The drop down get the script names from the folder.

**Comment by adamdriscoll** [comment]
You can certainly do this with a dashboard. This particular issue is for implementing something super simple for pages. The idea is that it provides less configuration than a dashboard but should be easy to drag and drop onto a page.
