### ISSUE TITLE
Triggered scripts can build up the DB

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#3527]
### Version

4.3.4

### Severity

Medium

### Environment

msi

### Steps to Reproduce

If you have multiple scripts that will run when you start your server and you restart the server a couple of times you will build up a bunch of triggered scripts that are queued.

### Expected behavior

```console
It's kind of expected but it should have some kind of action to prevent it, like a variable that you can set to $true and then if this triggered action already are queued it will not start an other one.
```

### Actual behavior

```console
Building up a big queue
```

### Screenshots/Animations

![CleanShot 2024-08-01 at 14 03 17](https://github.com/user-attachments/assets/c4d41445-c0c0-49f0-b08d-08a1dcac1318)

**Comment by rwidmark** [comment]
@adamdriscoll can you reproduce this?
One of my PSU nodes DB ended up at 86GB toke down the server.
Removed and rebuilt the db solved it.
But as I can reproduce it i am a little worried that this can cause issues in the long run.

**Comment by adamdriscoll** [comment]
I haven't looked into this yet but I have seen this before.

**Comment by rwidmark** [comment]
FYI, I'm running sqllite

**Comment by adamdriscoll** [comment]
We've made some fixes to background jobs that should resolve this. I can't reproduce with 25 jobs running at startup after the change.
