### ISSUE TITLE
Update Cycle for PowerShell Universal

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#353]
Hi,
No big deal really but I would love if you did make some kind of update cycle for example MS has the second Tuesday every month.
It would bee great if you hade some similar as every enterprise are updating systems during that time.

The Pro's for this for you is that you have more time to try out every update in the nightly builds.

I do understand that not all people wants this but enterprises do want it :)

To tip of cycle is something like this;
Stable - Every second Tuesday monthly
Release Preview or maybe Golden release or similar - Every week or second week
Nightly build - every night

**Comment by Viajaz** [comment]
This is useful for enterprises that have testing, pre-prod and production rings for PSU as well as ISO Change Management processes.

**Comment by adamdriscoll** [comment]
I like this idea. Let me formalize a cycle and I'll post some official docs and schedule.

**Comment by adamdriscoll** [comment]
Here we go: https://blog.ironmansoftware.com/new-versioning/
