### ISSUE TITLE
[RC5] Simple Schedule Daily Reverts to every minute execution

### ISSUE THREAD

**Issue by mwatts-seg** [ironmansoftware/powershell-universal#3534]
### Summary of the feedback

**Summary of the feedback**
Simple Schedule Daily Reverts to every minute execution

**Version**
5.0.0-rc5 Nightly 08/02

**Severity**
Critical

**Environment**
Kestrel

**Steps to Reproduce**
Click Automation -> Schedules
Click [+ Create Simple Schedule] 
Fill out Data, select [Scheduled: Every Day] 
Set Time (i.e. 7:00)
Click [OK]

**Expected behavior**
```
Scheduled as user specified Daily @ specific time 
```

**Actual behavior**
```
Schedules every minute
```

**Additional Environment data**
No response

**Screenshots/Animations**
![image](https://github.com/user-attachments/assets/a112d62d-d7ad-4b6f-898b-35cadcfd559f)
![image](https://github.com/user-attachments/assets/f46e3664-51f3-4d1b-a44f-9a11fc6ac82e)
![image](https://github.com/user-attachments/assets/48132c82-a6cf-412b-b896-fe021e8fe903)

**Comment by adamdriscoll** [comment]
I actually think this is related to this: #3532 

The problem is that we have some lingering state in the property modals that is causing all kinds of weird problems when creating new items. Luckily, all the modals derive from the same base component. Unluckily, this may affect all property modals.

**Comment by mwatts-seg** [comment]
> I actually think this is related to this: #3532
> 
> The problem is that we have some lingering state in the property modals that is causing all kinds of weird problems when creating new items. Luckily, all the modals derive from the same base component. Unluckily, this may affect all property modals.

I was just going to add feedback that when creating another schedule, I am seeing the same behavior as #3532. :)

**Comment by adamdriscoll** [comment]
Actually, this one is unrelated 😵‍💫I did get the other one fixed.
