### ISSUE TITLE
Show-UDToast -ReplaceToast Switch not working

### ISSUE THREAD

**Issue by ganslm** [ironmansoftware/powershell-universal#3547]
### Version

4.3.4

### Severity

Low

### Environment

msi

### Steps to Reproduce
```
New-UDButton -Text 'Show Toast' -OnClick {
  
    Show-UDToast -Message 'Hello, World!' -ReplaceToast
  
} -Id 'toast15'
```

(Example from App Documentation)

### Expected behavior

```console
Replace previous toast.
```

### Actual behavior

```console
Displays multiple toasts.
```

### Additional Environment data

Windows Server 2022 Datacenter.

### Screenshots/Animations

![grafik](https://github.com/user-attachments/assets/c67a98d6-33bc-4421-8d5b-43dddb999556)

**Comment by adamdriscoll** [comment]
The doc is missing the -Id on the toast. It's required when using replacetoast.

```
    PS > New-UDButton -Text 'Show Toast' -OnClick {
    PS >    Show-UDToast -Message 'Hello, World!' -ReplaceToast -Id "toastId"
    PS > } -Id 'toast15'
```

**Comment by ganslm** [comment]
I tried using your example, but in my case it still doesn´t seem to work with the added -Id. I still see multiple toasts.
