### ISSUE TITLE
[RC5] - MSI Installer Issue - Error writing to file

### ISSUE THREAD

**Issue by mwatts-seg** [ironmansoftware/powershell-universal#3548]
### Summary of the feedback

Since moving to RC5 MSI from RC4 - I have noticed I keep getting this prompt: 

![image](https://github.com/user-attachments/assets/50e5edd3-6395-4b65-8b9b-3f8ac167d509)

I always ensure that I stop the service prior to upgrading. Clicking 'Retry' proceeds along and I do not get that message any further.

**Comment by adamdriscoll** [comment]
I haven't been able to reproduce this. If you do end up running into this again, it might be handy to try and discover what's locking the file: https://github.com/ironmansoftware/findopenfiles

The MSI logs may also contain more info.

**Comment by mwatts-seg** [comment]
> I haven't been able to reproduce this. If you do end up running into this again, it might be handy to try and discover what's locking the file: https://github.com/ironmansoftware/findopenfiles
> 
> The MSI logs may also contain more info.

@adamdriscoll  I will run the next install with logging, but it did appear 5.0.0 msi again:

![image](https://github.com/user-attachments/assets/079d0481-594c-4734-b80a-57779ba599d7)
