### ISSUE TITLE
Docs: Mapping Azure OIDC Group Claims to Roles through Role Policy

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/powershell-universal#355]
https://docs.powershelluniversal.com/config/security/openid-connect#configuring-azuread discusses how to configure OpenID Connect Authentication with Azure AD, it would be useful if a reference to a corresponding example Authorization configuration was made: https://docs.powershelluniversal.com/config/security#example-policy-based-on-active-directory-group-membership-windows-authentication

Language could be adjusted to also explain it's also relevant to OpenID Connect workflows.

**Additional context**
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-optional-claims#configuring-groups-optional-claims
https://docs.microsoft.com/en-us/azure/active-directory/hybrid/how-to-connect-fed-group-claims

**Comment by adamdriscoll** [comment]
Added an example here: https://docs.powershelluniversal.com/config/security#example-group-membership-based-on-azure-active-directory
