### ISSUE TITLE
New-UDIconButton Does not Use Correct EventData in UDTable

### ISSUE THREAD

**Issue by cmacnicholSA** [ironmansoftware/powershell-universal#3557]
### Version

4.3.4

### Severity

Medium

### Environment

msi

### Steps to Reproduce

I have a Standard UD Table Rendering multiple Actions in a column.  If you use New-UDButton, the EventData is rendered correctly and you can access the rows information.  However, if you use UDIconButton then the Eventdata is pulled from what appears to be the last row of the table and not the row it was rendered in.  As the below code shows, they should display the same computer name, they do not.

`                  New-UDIconButton -Icon (New-UDIcon -Icon 'clipboard') -Size small -OnClick { Set-UDClipboard -ToastOnSuccess -Data $EventData.ComputerName }
                New-UDButton -Id "info$($EventData.ComputerName)" -Text "$($EventData.ComputerName)" -OnClick {
                  Show-UDToast -Message "Computer is: $($Eventdata.ComputerName)"
                }`

### Expected behavior

```console
EventData should display the current row rendered, not the last row.
```

### Actual behavior

```console
New-UDIconButton is displaying incorrect EventData information.
```

### Additional Environment data

Windows Server 2016

**Comment by adamdriscoll** [comment]
Can you try putting the $EventData in another variable before defining the button? 

```
$MyData = $EventData
 New-UDIconButton -Icon (New-UDIcon -Icon 'clipboard') -Size small -OnClick { Set-UDClipboard -ToastOnSuccess -Data $MyData.ComputerName } 
New-UDButton -Id "info$($MyData.ComputerName)" -Text "$($MyData.ComputerName)" -OnClick { Show-UDToast -Message "Computer is: $($MyData.ComputerName)" }
```

**Comment by cmacnicholSA** [comment]
@adamdriscoll 

Well, I am a little confused at this point.  I have put my full column code below for show.  The first Toast notification with your workaround worked.  The second IconButton with the same workaround, just to a different variable did NOT.  Last, the third IconButton with EventData is showing the last table item and not the correct one.

                New-UDTableColumn -Property ComputerName -Title 'ComputerName' -Render {
                  $MyData = $EventData
                  New-UDIconButton -Icon (New-UDIcon -Icon 'clipboard') -Size small -OnClick { Set-UDClipboard -ToastOnSuccess -Data $MyData.ComputerName }
                 New-UDButton -Id "info$($MyData.ComputerName)" -Text "$($MyData.ComputerName)" -OnClick { Show-UDToast -Message "Computer is: $($MyData.ComputerName)" }

                  New-UDTooltip -Id 'wkspaceIDTT' -Placement top -TooltipContent { ('WorkspaceID: {0}' -f $EventData.WorkspaceID) } -Content {
                  New-UDButton -Id "lnk$($EventData.ComputerName)" -Text "$($EventData.ComputerName)" -OnClick { Get-ADComputer -Identity $($EventData.ComputerName) | Select-Object -ExpandProperty ObjectGUID | ForEach-Object { Invoke-UDRedirect "/ComputerDetails/$_" -OpenInNewWindow } }
                }

                  $buttonData1 = $EventData
                  New-UDIconButton -Id 'cpyClipComputerName' -Icon (New-UDIcon -Icon 'clipboard') -Size small -OnClick {
                    Show-UDToast -Message "Computer is: $($buttonData1.ComputerName)"
                  }
                  New-UDIconButton -Id 'infoWorkspace' -Size small -Icon (New-UDIcon -Icon 'info') -OnClick {
                    Show-UDToast -Message "Computer is: $($EventData.ComputerName)" -Duration 10000
                  }
                }

**Comment by cmacnicholSA** [comment]
@adamdriscoll  Any other thoughts on this?  This is currently directly impacting one of my production dashboards.  I cannot get the workaround to reliably work.

**Comment by adamdriscoll** [comment]
This is because you are specifying a static ID for the icon button in your second example. You need to make it unique or the event handlers will overwrite. You don't actually need the work around I provided. 

```
     New-UDTableColumn -Property ComputerName -Title 'ComputerName' -Render {
              $MyData = $EventData
              New-UDIconButton -Icon (New-UDIcon -Icon 'clipboard') -Size small -OnClick { Set-UDClipboard -ToastOnSuccess -Data $MyData.ComputerName }
             New-UDButton -Id "info$($MyData.ComputerName)" -Text "$($MyData.ComputerName)" -OnClick { Show-UDToast -Message "Computer is: $($MyData.ComputerName)" }

              New-UDTooltip -Id 'wkspaceIDTT' -Placement top -TooltipContent { ('WorkspaceID: {0}' -f $EventData.WorkspaceID) } -Content {
              New-UDButton -Id "lnk$($EventData.ComputerName)" -Text "$($EventData.ComputerName)" -OnClick { Get-ADComputer -Identity $($EventData.ComputerName) | Select-Object -ExpandProperty ObjectGUID | ForEach-Object { Invoke-UDRedirect "/ComputerDetails/$_" -OpenInNewWindow } }
            }

              $buttonData1 = $EventData
              New-UDIconButton -Id "cpyClipComputerName$($EventData.ComputerName)" -Icon (New-UDIcon -Icon 'clipboard') -Size small -OnClick {
                Show-UDToast -Message "Computer is: $($buttonData1.ComputerName)"
              }
              New-UDIconButton -Id "infoWorkspace$($EventData.ComputerName)" -Size small -Icon (New-UDIcon -Icon 'info') -OnClick {
                Show-UDToast -Message "Computer is: $($EventData.ComputerName)" -Duration 10000
              }
            }
```

Here's my example. 

```
New-UDApp -Content { 
  $data = 1..10 | %{ 
    @{ Key = "Item $_"; Value = $_}
  }

  New-UDTable -Data $Data -Columns @(
    New-UDTableColumn -Property Key 
    New-UDTableColumn -Property Value -OnRender {
      New-UDIconButton -Icon (New-UDIcon -Icon 'clipboard') -Size small -OnClick { Set-UDClipboard -ToastOnSuccess -Data $EventData.Key } 
      New-UDButton -Id "info$($EventData.Key)" -Text "$($EventData.Key)" -OnClick { Show-UDToast -Message "Computer is: $($Eventdata.Key)" }
    }
  )
}


```

**Comment by cmacnicholSA** [comment]
I did not actually realize that the ID's needed to be unique in a table like that.  Makes sense now that I think about it, but not something that would of occurred to me to check.

Thank you very much for the information, that resolved the issue immediately.
