### ISSUE TITLE
Exclude core.* files from Git

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#3560]
### Summary of the new feature / enhancement

We are using an external Git client, and recently had a crash on one our servers.
That generates an core.XYZ file under the Repository folder, that is then attempted to upload to our Git repository - but fails, because the memory dump is to big.

Please dont commit these files to the repository :)

**Comment by adamdriscoll** [comment]
We could add these to a .gitignore or something. I think documenting a default .gitignore for PSU and having a way to manage them in the product would be nice.

**Comment by JessePeden** [comment]
> We could add these to a .gitignore or something. I think documenting a default .gitignore for PSU and having a way to manage them in the product would be nice.

@adamdriscoll Does that mean that my custom .gitignore that's in the PSU repo overrides whatever built-in .gitignore PSU comes with (that users are, I'm guessing, unable to see)?  Or does PSU merge its default file with what a user may have created?  I wasn't aware that PSU even had a default .gitignore until you just mentioned it.

Also, if you're going to potentially add a way of managing the .gitignore file from within PSU, can I also request a way to manage .gitattributes and .gitmodules?

**Comment by adamdriscoll** [comment]
It doesn't. I was just suggesting we could add something. I think just having an editor for this and then having some documented suggestions would be as far as I would go.

**Comment by JessePeden** [comment]
> It doesn't. I was just suggesting we could add something. I think just having an editor for this and then having some documented suggestions would be as far as I would go.

So, what would the behavior be when someone, like myself, has a custom .gitignore on the root of the repository on the PSU server?  Does PSU use both that and its own .gitignore to ignore a combination of both files' entries?  I know the custom file I made is being used because entries matching one of the lines are not being synced.

**Comment by adamdriscoll** [comment]
We don’t do anything special with .gitignore. If you have it in the repo, we will honor it but not modify it. We just use standard git commands.

**Comment by rwidmark** [comment]
@adamdriscoll got an idea for this.

Create the possibility to merge this ignore with the ignore from the repo.

What I want to achieve with this is that if I have two branshes one production and one beta.

Production is for the production servers and beta are for the beta servers.

So for the beta bransche I have a folder named "beta-notes" I don't want that folder to be downloaded to my production servers but I want to merge my beta branche with the production.

So then I can add "beta-notes" to PSU ignore file for the production servers and now that folder will not be downloaded to the production servers.
