### ISSUE TITLE
Home Page Formatting is still bad

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3565]
### Summary of the feedback

Looks fine on my huge desktop monitor but not so great on the laptop...

![image](https://github.com/user-attachments/assets/31d531d0-a441-4cee-bcb6-5252432193d6)

**Comment by Omzig** [comment]
also, change uptime to a time (4 days 13min) instead of a datetime, or at least give the datetime on hover over.

**Comment by adamdriscoll** [comment]
Fixed the formatting. Added Humanizer to format the uptime better. 

![image](https://github.com/user-attachments/assets/ac0c59a4-86e1-42db-8699-f4ed300b60da)
