### ISSUE TITLE
Unable to login to admin account after db migration with psudb.exe

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3568]
### Version

5.0.0-rc5

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

- make sure the admin user has a password
- upgrade the db with psudb.exe
- start the app pool
- go to /login

### Expected behavior

```console
should allow login options
```

### Actual behavior

```console
it will go to /first-run
```

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/e29b63f6-9648-4673-a677-8621ed52d005)

### Workaround
create 'admin2' to get past /first-run

**Comment by adamdriscoll** [comment]
Does your admin account have the administrator role assigned in the db? If you use a different user name, does it work?

**Comment by Omzig** [comment]
my new admin has it:
![image](https://github.com/user-attachments/assets/8d1a0df3-9272-41c9-a69a-5ac621f97d50)
my old admin does not:
![image](https://github.com/user-attachments/assets/68d27b94-9135-4248-81cf-3f92cdb14eb1)

**Comment by adamdriscoll** [comment]
Thanks. I swear I saw this before. I'll see if I can reproduce it. The first run thing will show up if there are no administrators. Honestly, we should consider making that more intelligent.. like what if you want to use AD groups for admins but not a static local account?
