### ISSUE TITLE
Update logging documentation for v4 and v5

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#3572]
### Summary of the new feature / enhancement

In version 3 of PSU you can define the log level settings in the admin panel, and its also documented.
https://docs.powershelluniversal.com/v/v3/development/logging

For version 4 and 5 the setting is no longer available in the admin console, and the documentation does not state how to change it.
https://docs.powershelluniversal.com/development/logging#level

![image](https://github.com/user-attachments/assets/20685827-da50-4b69-bf12-af0df80caff8)
Under Platform\Logging you can view the logs, but not change any settings related to logging.

**Comment by adamdriscoll** [comment]
https://docs.powershelluniversal.com/development/logging#system-logging
