### ISSUE TITLE
refresh does not work in /admin/* sub pages

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3574]
### Version

5.0.0-rc5

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

- go to a sub page like /admin/apis/endpoints
- hit the refresh button or F5
- sometimes using the browser back button also causes this

### Expected behavior

```console
page refresh
```

### Actual behavior

```console
Page Not Found
```

**Comment by adamdriscoll** [comment]
I cannot reproduce this. My nested site is set to /psu1. BasePath is set to /psu1. F5 works every time. Using Chrome and Firefox. 

![image](https://github.com/user-attachments/assets/e444cb36-252e-45cf-b191-8158991d6270)

**Comment by Omzig** [comment]
funny, none of my nested sites will allow me to F5 when inside the admin site

**Comment by Omzig** [comment]
now the sites are working. i am confused

**Comment by Omzig** [comment]
i don't get it, not sure what is going on, only works when Adam looks at it.

**Comment by adamdriscoll** [comment]
Closing for now. Reopen once you try again when I'm not looking.
