### ISSUE TITLE
Docs: Updating PowerShell Universal

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/powershell-universal#358]
Please provide documentation on how to safely update PowerShell Universal in production, depending on which installation method was used.

**Comment by Viajaz** [comment]
If you install PowerShell Universal using MSI then upgrade the version by installing a newer MSI, it will delete any configuration under `C:\Program Files (x86)\Universal` such as `appsettings.json`

**Comment by adamdriscoll** [comment]
You will want to refer to the documentation here: https://docs.powershelluniversal.com/get-started/getting-started/upgrading#configuration-persistence

Specifically here for appsettings.json: https://docs.powershelluniversal.com/get-started/getting-started/upgrading#appsettings-json
