### ISSUE TITLE
[5.0.0] MSI - Seeing multiple entries in add/remove control panel. 

### ISSUE THREAD

**Issue by mwatts-seg** [ironmansoftware/powershell-universal#3591]
### Summary of the feedback

Went to go check something in windows control panel and see multiple entries for PowerShell Universal. 
I am pretty actively testing each nightly build, not sure if this is meant to be this way. I do remember seeing a post above having side-by-side installs. 

![image](https://github.com/user-attachments/assets/2f8636d3-94c5-46c1-bc0c-c741710d0470)

**Comment by adamdriscoll** [comment]
I just ran the 5.1 nightly installer over a 5.0 and it upgraded without this issue, so I figure this is just a problem running the same version multiple times. That said, it shouldn't allow this, so I'll still look into it.

**Comment by adamdriscoll** [comment]
After looking into this, the issue is that the product code is changing in the installer between versions of the pre-release version. This isn't the case with a final release version, so this won't be an issue. It won't install multiple versions of the same upgrade code, product code and version.
