### ISSUE TITLE
[5.0.0] New Scripts - Execution tab does not show

### ISSUE THREAD

**Issue by mwatts-seg** [ironmansoftware/powershell-universal#3592]
### Summary of the feedback

I am assuming there is supposed to be an 'execution' tab to adjust settings there, but it does not show or activate on MS Edge. 

Version: 5.0.0 - Build: Nightly (08/18/2024)

![image](https://github.com/user-attachments/assets/f03b387a-70ac-438f-b179-1b255706fac5)

***CONSOLE***
![image](https://github.com/user-attachments/assets/dd5017a5-3da3-4094-8f7d-99e576dc40a9)

**Comment by adamdriscoll** [comment]
Tried fixing this but only happens sometimes for me so rolling into v5.0.1 so we can have some more time with it.
