### ISSUE TITLE
[5.0.0] Cannot execute script in PowerShell 5 environment

### ISSUE THREAD

**Issue by mwatts-seg** [ironmansoftware/powershell-universal#3596]
### Summary of the feedback

When I try to execute a script in PS 5 environment, I get this error:

![image](https://github.com/user-attachments/assets/82872d4c-2348-4540-89db-f048749dd953)

I am able to successfully run in the integrated environment. However, this particular script does not work well with PowerShell 7. 
I did try to manually discover the environments and used the one discovered, but same results. 

I also found a forum post, where someone else had this in an earlier version:
https://forums.ironmansoftware.com/t/large-amount-of-job-errors-post-3-7-4-upgrade/8469/3

I tried what was suggested:
![image](https://github.com/user-attachments/assets/f87ce85b-568a-4e2e-a149-ee3e65302a1e)

![image](https://github.com/user-attachments/assets/3890addd-8106-445a-81ef-90c894bd5ce4)

**Comment by adamdriscoll** [comment]
This is actually expected. PSUv5 won't run in the standard Windows PowerShell executable. We have a .NET 4.8 executable that hosts the WinPS binaries to prevent this. More details will be in our release notes. We need a better error message. 

https://docs.powershelluniversal.com/v/v5/getting-started/upgrading#powershell.exe-is-no-longer-used

**Comment by mwatts-seg** [comment]
> This is actually expected. PSUv5 won't run in the standard Windows PowerShell executable. We have a .NET 4.8 executable that hosts the WinPS binaries to prevent this. More details will be in our release notes. We need a better error message.
> 
> https://docs.powershelluniversal.com/v/v5/getting-started/upgrading#powershell.exe-is-no-longer-used

@adamdriscoll Sorry! I didn't read and that's my fault.

Does that mean we will not be able to execute scripts that are heavily geared towards PowerShell 5? Our organization has tried using PowerShell 7 in the past, but there were issues with some cmdlets, tied with the time constraints of our team with trying to rewrite the scripts. 

Does the Integrated environment use the service account to execute the PowerShell process? I tried to run our Azure AD & O365 Photo Sync script, and it had issues access network resources, which makes me think it is trying to use the System account versus the service account.

**Comment by adamdriscoll** [comment]
You'll be able to execute PS5.1 scripts as expected. We still using the local PS5.1 assemblies to execute everything. It's just that we use a different host process so we can control the assembly loading. You shouldn't notice a difference except modules loading more consistently.

**Comment by mwatts-seg** [comment]
> You'll be able to execute PS5.1 scripts as expected. We still using the local PS5.1 assemblies to execute everything. It's just that we use a different host process so we can control the assembly loading. You shouldn't notice a difference except modules loading more consistently.

Ah, okay. That makes sense. I tried running 'PowerShell 5.0' without executable defined, as this is how it was when I set it up, It goes to failed right away. If I tried to run it via Integrated environment, it looks to run as SYSTEM context because it has no access outside the box. 
![image](https://github.com/user-attachments/assets/318e045b-040b-49ba-bd30-3b8180991ec5)

![image](https://github.com/user-attachments/assets/d020e1c4-bd0d-4ae8-90dd-4b918320b52e)

**Comment by adamdriscoll** [comment]
Integrated runs as whatever the service is configured. If you don't have a Windows PowerShell 5.1 environment, try adding that and executing it.

**Comment by mwatts-seg** [comment]
> Integrated runs as whatever the service is configured. If you don't have a Windows PowerShell 5.1 environment, try adding that and executing it.

Ah okay. I figured out why integrated would not work. Read the part where credentials would not work with integrated, which makes sense. The account does not have authority to do what I want. :) Still trying to work on getting PS5 working.

**Comment by adamdriscoll** [comment]
I've improved the Windows PowerShell 5.1 discovery and added better reporting to address this.
