### ISSUE TITLE
Add SSO Button to Login Form

### ISSUE THREAD

**Issue by mwatts-seg** [ironmansoftware/powershell-universal#3601]
### Summary of the new feature / enhancement

I like the idea of still having the login form but would be nice to have a button that redirects to SSO for users in case they land there. 

### Proposed technical implementation details (optional)

Button displayed below Login, 'Login with Single Sign-On' and redirects the users to automatically login via SSO if setup. 
![image](https://github.com/user-attachments/assets/4eb88871-a4df-47dd-ae77-fbced8b9c9e4)

If the application is not using SSO, then this should be hidden or greyed out.

**Comment by adamdriscoll** [comment]
We actually added a button for this for Windows SSO but we could certainly do it for the other auth types as well.

**Comment by mwatts-seg** [comment]
> We actually added a button for this for Windows SSO but we could certainly do it for the other auth types as well.

That would be awesome, we currently just pivoted to Azure AD SSO from ADFS.
