### ISSUE TITLE
clicking through /admin/settings/files does update

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3603]
### Version

5.0.0

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

- go to /admin/settings/files
- expand a folder
- click on a few ps1 files

### Expected behavior

```console
file viewer would show the contents of the file
```

### Actual behavior

```console
shows you only the first files contents
```

**Comment by adamdriscoll** [comment]
Bumping the priority on this. If you select a file and then another file, it saves to the wrong file...
