### ISSUE TITLE
Error when viewing script - http://:5000/admin/automation/scripts/folder/Admin/Get-AccessToken.ps1

### ISSUE THREAD

**Issue by mikedhanson** [ironmansoftware/powershell-universal#3606]
### Version

5.0.0

### Severity

High

### Environment

msi

### Steps to Reproduce

An error occured. Could not find 'blazorMonaco.languages.registerDocumentFormattingEditProvider' ('registerDocumentFormattingEditProvider' was undefined). Error: Could not find 'blazorMonaco.languages.registerDocumentFormattingEditProvider' ('registerDocumentFormattingEditProvider' was undefined). at http://:5000/_framework/blazor.server.js:1:537 at Array.forEach (<anonymous>) at l.findFunction (http://:5000/_framework/blazor.server.js:1:505) at _ (http://:5000/_framework/blazor.server.js:1:5248) at http://:5000/_framework/blazor.server.js:1:3041 at new Promise (<anonymous>) at y.beginInvokeJSFromDotNet (http://:5000/_framework/blazor.server.js:1:3004) at Xt._invokeClientMethod (http://:5000/_framework/blazor.server.js:1:60890) at Xt._processIncomingData (http://:5000/_framework/blazor.server.js:1:58279) at Xt.connection.onreceive (http://:5000/_framework/blazor.server.js:1:51920)

### Expected behavior

```console
No error
```

### Actual behavior

```console
Error
```

**Comment by adamdriscoll** [comment]
Did you install any pre-release versions of PSUv5? I can't reproduce this and wondering if we have a browser caching issue. We need to hash our JS binaries properly if that's the case.

**Comment by mikedhanson** [comment]
I did have a pre-release version installed. I think it was cache.. I cleared the cache, and it looks to be working now. Sorry about that :)
