### ISSUE TITLE
Agent Service Reconnect

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3614]
### Version

5.0.0

### Severity

Low

### Environment

msi

### Steps to Reproduce

When the agent service loses connection with the server it will retry a few times and then quit. You have to restart it after a while. We should just retry periodically incase servers are being patched etc. 

### Expected behavior

```console
Agent service reconnects if server goes down then comes back up.
```

### Actual behavior

```console
Agent service doesn't reconnect.
```

**Comment by JessePeden** [comment]
Thanks.  I was tempted to use 5.0.1 but seeing this bug will mean holding off for 5.0.2 since we use the agent for running almost all scripts.

**Comment by adamdriscoll** [comment]
We changed the naming of things a bit in v5 so this isn't the same agent environment as in v4. 

Event Hub Client is now PSU Agent (psuagent.exe) - Remote agent that connects back to the Universal.Server process. This bug is about that. 

Agent Environment is now PowerShell 7 Environment (Universal.Agent.exe) - Local agent that hosts PS 7 on the PSU server
(new) Windows PowerShell 5.1 Environment (Universal.Agent.exe) - Local agent that hosts WinPS on the PSU server

**Comment by JessePeden** [comment]
Oh.  I see.  Thanks for the clarification.  I'll probably still wait for 5.0.2 given some of the other posts on the forum that I've seen.
