### ISSUE TITLE
UDAutocomplete converts Option into datetime in OnChange

### ISSUE THREAD

**Issue by RubenT91** [ironmansoftware/powershell-universal#3644]
### Version

4.3.4

### Severity

Low

### Environment

msi

### Steps to Reproduce

New-UDApp -Title 'PowerShell Universal' -Content {
    New-UDCard -Title 'Autocomplete test' -Style @{Width = "50em" } -Content {
        New-UDAutocomplete -Label "First Autocomplete" -Options @('1.01', '1.02', '1.04', '1.05', '2.01', '2.02', 'ABCD-1.03') -Id 'Select1' -FullWidth -OnChange {
            $EventData
            $Session:SelectedValue = $EventData
            Sync-UDElement -Id 'DynSelect1'
        }
    }

    New-UDCard -Title 'Autocomplete Result' -Style @{Width = "50em" } -Content {
        New-UDDynamic -Id 'DynSelect1' -Content {
            if ($Session:SelectedValue) {
                Write-Output "$($Session:SelectedValue | Out-String)"
                Show-UDToast -Message "$($Session:SelectedValue | ConvertTo-Json)" -Duration 120000
            }
        }
    }
}

### Expected behavior

```console
The $EventData should contain the string from the UDAutoComplete instead of being converted to a datetime.
```

### Actual behavior

```console
The $EventData is being converted to a datetime, which is not expected, as the data should remain in string format. For example, '1.02' is converted to "Tuesday, January 2, 2024, 12:00:00 AM."
```

### Additional Environment data

Operating System: Windows Server 2019 Datacenter, Build 1809
Browser: Google Chrome (Various versions)

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/30e4c90a-ec74-4340-bdde-1649ee99d7cc)

**Comment by adamdriscoll** [comment]
This is a general problem with how we guess which type is passed. The user can use the $Body parameter instead. See example. 

```powershell
New-UDApp -Title 'PowerShell Universal' -Content {
New-UDCard -Title 'Autocomplete test' -Style @{Width = "50em" } -Content {
New-UDAutocomplete -Label "First Autocomplete" -Options @('1.01', '1.02', '1.04', '1.05', '2.01', '2.02', 'ABCD-1.03') -Id 'Select1' -FullWidth -OnChange {
$Session:SelectedValue = $Body.Trim('`"')
Sync-UDElement -Id 'DynSelect1'
}
}

New-UDCard -Title 'Autocomplete Result' -Style @{Width = "50em" } -Content {
    New-UDDynamic -Id 'DynSelect1' -Content {
        if ($Session:SelectedValue) {
            New-UDTypography $Session:SelectedValue
            Show-UDToast -Message "$($Session:SelectedValue | ConvertTo-Json)" -Duration 120000
        }
    }
}
}
```
