### ISSUE TITLE
Set-PSUCache Error when setting a value

### ISSUE THREAD

**Issue by jhadvan** [ironmansoftware/powershell-universal#3646]
### Version

5.0.1

### Severity

Low

### Environment

msi

### Steps to Reproduce

When I am trying to set a server level cache I am getting an error message.

### Expected behavior

```console
Set-PSUCache -Key "CurrentDate" -Value (Get-Date)
$date = Get-PSUCache -Key "CurrentDate"
Write-Host $date

to return current date
```

### Actual behavior

```console
Getting Invalid URI error;
```

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/f08d2cb1-5f0e-49ef-b2f8-987d9d9389cc)

**Comment by adamdriscoll** [comment]
This sounds a bit like PSU can't figure out the right URL to call. He's some more info about that: https://docs.powershelluniversal.com/config/module#reverse-proxies-iis

**Comment by adamdriscoll** [comment]
We are putting a fix in for the cmdlets against IIS in version 5.0.2. You will need to ensure that the API \ URL appsettings.json value is set.
