### ISSUE TITLE
Make it easier to go from 4 to 5

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#3650]
### Version

5.0.0

### Severity

Critical

### Environment

msi

### Steps to Reproduce

Today it's hard to get from version 4 latest version to version 5.
My dashboard are not working you can't just migrate your scripts or schedules it will throw errors etc.

I was just giving up and I do see my self as PSU "pro" as I have been using this for three years now or if it's four years.

### Expected behavior

```console
se above
```

### Actual behavior

```console
se above
```

**Comment by adamdriscoll** [comment]
I appreciate the feedback but need more information on what is happening. To be frank, we've had almost no breaking changes in the app framework. In terms of scripts and schedules, I will need to know what problems you are encountering to address them. A broad issue like this is a good placeholder but doesn't provide any actionable steps we can take to improve the situation you are in.

**Comment by rwidmark** [comment]
@adamdriscoll should have mentioned that I'll setup a issue for it with your support today.
Somehow I did forget to do so.

I know that you haven't made so much breaking changes and that's what's confusing me.

I'll try to censor the files today and explain it more for your support and add some more info here.

But in short my schedules file don't even show up in PSU admin and a notification stating that it's bad formatting.

loginPage.ps1 won't load, I have tried to convert it to the branding.ps1 file but the same issue there.
The logo is not correctly formatted and the login page is black color.
So the loginPage.ps1 is not 1:1 mapped.

I do get some error banners stating that I have not loaded my modules but I have.

FavIcon path are not saved in the settings.

Also I do get this error when I start my dashboard
![CleanShot 2024-08-24 at 07 52 24@2x](https://github.com/user-attachments/assets/03444808-d0d0-422d-82b3-2932926949e2)

**Comment by rwidmark** [comment]
@adamdriscoll I have sorted some things.
I was re-installing it with PSU 5.0.1, needed to through the UI add script manually for the triggers. It was showing in the UI in the column trigger script column but when I was clicking in to the trigger the script was not populated.

I have not sorted out the loginPage style and not the schedule, below you can find a example how my schedule looks like.
````
$Parameters = @{
    Cron               = "15 2 * * *"
    Script             = "folder1\folder2\script.ps1"
    TimeZone           = "Europe/Stockholm"
    Environment        = "Standard"
    Name               = "Test scripts"
    Timeout            = 15
    RandomDelay        = $true
    RandomDelayMaximum = 5
}
New-PSUSchedule @Parameters
````

The dashboard issue is gone after re-installing with psu 5.0.1 but replaced with this:
![CleanShot 2024-08-24 at 09 37 16@2x](https://github.com/user-attachments/assets/0c13fdcf-f273-4779-a163-7caadd015204)

Edit:
It do seem that the main issue is that I can't get my scripts to work with schedule or triggers.
I have read the documentation but I can't still figure the path thing out, It might be just me that are not understanding it.
Sorry for my frustration.

Edit2:
My folder structure are like this under C:\ProgramData\UniversalAutomation\Repository
RestAPI
Scripts -> different folders -> script files .ps1

In settings.ps1 I have the following
    ScriptBaseFolder            = "C:\ProgramData\UniversalAutomation\Repository\Scripts"

**Comment by rwidmark** [comment]
I think that I did find the root cause of my issue and I have opened a separate issue for it
https://github.com/ironmansoftware/powershell-universal/issues/3651

closing this one
