### ISSUE TITLE
Fault error when variable/object is null

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#366]
**Describe the bug**
When you are collecting something in the Dashboard and the variable is Null then you get a pop-up telling you that it's a issue.
![Screenshot 2021-08-16 at 11 46 09](https://user-images.githubusercontent.com/76907327/129544938-f2ba2fb4-290b-4490-a4ae-8d9da05556d4.png)

This is according to me false/positive as in my case when you collect information from the AD some variables are going to bee null as it don't contain any data in the object.

Running PSU 2.2.1

**Comment by adamdriscoll** [comment]
Can you let me know which component you are using that causes this? I'm assuming UDTable since I've seen this before.

**Comment by rwidmark** [comment]
> Can you let me know which component you are using that causes this? I'm assuming UDTable since I've seen this before.

That's correct it's when the UDTable are returning NULL from PSObject. In my case the table is totally empty when this are returned.

**Comment by rwidmark** [comment]
@adamdriscoll my suggestion is that you suppress this pop-up error from UDTable.
Don't even have it in the logs.

If the user wantS to try the table they should try the psobject in Pswh instead it's better to do so. :)
