### ISSUE TITLE
Role to claim mapping not working with Windows Auth

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3673]
### Version

5.0.3

### Severity

Low

### Environment

msi

### Steps to Reproduce

Setup windows auth
Setup a role that maps a group SID to a role
Login with a user in that role

### Expected behavior

```console
Role is applied
```

### Actual behavior

```console
Role is not applied
```

**Comment by adamdriscoll** [comment]
User reports they had a typo and now it works. I still can't get my environment to work.

**Comment by donlent** [comment]
@adamdriscoll
Not sure if that is 100% related to the same issue but I'm currently experiencing something similar:

Forms Auth and Role Mapping => works w/o problems
Windows Auth and Role Mapping => doesn't work. To be more precise the role actually shows up under the "identity" webpage of the user but when I try to access the App it just doesn't show any content! Just a blank page is shown... So not a "page not found" or so... it just doesn't load the App....

**Comment by adamdriscoll** [comment]
@donlent - Not sure. My issue ended up being caching and was able to resolve by restarting the service. I did end up adding the clear cached claims button back to the roles page to help with this issue. If you still have problems in 5.0.5, please open a new issue.
