### ISSUE TITLE
Nivo Charts: not all settings switches works

### ISSUE THREAD

**Issue by HansenRene** [ironmansoftware/powershell-universal#3682]
### Version

4.3.4

### Severity

Low

### Environment

msi

### Steps to Reproduce

$Data = $(
            [PSCustomObject]@{
                value = 30
                color = '#BF5290'
            }
            [PSCustomObject]@{
                value = 100
                color = '#52BE80'

            }
        )

        New-UDNivoChart -Pie -Data ($Data | Where-Object { $_.Value -ne 0 }) -OnClick { Show-UDToast -Message "test" } 
        
        Produces a pie chart with atrocious wild animations on mouse-over. i expected '-DisableAnimations' to disable animations.

### Expected behavior

```console
-DisableAnimations disables animations
```

### Actual behavior

```console
-DisableAnimations does not disable animations
```

**Comment by HansenRene** [comment]
Maybe I should have created a more "General" issue of all Nivo Charts.
for example, the sample provided for a bar chart in the docs does not work
`$Data = 1..10 | ForEach-Object { 
        $item = Get-Random -Max 1000 
        [PSCustomObject]@{
            Name = "Test$item"
            Value = $item
        }
    }
    New-UDNivoChart -Bar -Keys "Value" -IndexBy 'name' -Data $Data -Height 500 -Width 1000`
    
    
![image](https://github.com/user-attachments/assets/29e91087-0fd3-4b4e-b444-b6d7826b2b3a)

The example for Bubble kinda works, but like many of the types the labels are missong
`
$TreeData = @{
    Name     = "root"
    children = @(
        @{
            Name  = "first"
            children = @(
                @{
                    Name = "first-first"
                    Count = 7
                }
                @{
                    Name = "first-second"
                    Count = 8
                }
            )
        },
        @{
            Name  = "second"
            Count = 21
        }
    )
}

New-UDNivoChart -Bubble -Data $TreeData -Value "count" -Identity "name" -Height 500 -Width 800
`
![image](https://github.com/user-attachments/assets/a9f5afe8-cb8f-4a06-9a0d-8a8ac3bedaf5)

The sample for calendar kinda works, but the example picture shows some kind of mouse-over label which is missing IRL
and so on.

in general, it seems that Nivo charts in PSU could use a big box of love. bug fixing and maybe including more of the chart types available.

**Comment by adamdriscoll** [comment]
Spent some time fixing some of these issues. 

- Disabled Animations
- Case sensitivity (bar chart example you posted) 

And looked into some others: 

- Missing labels
- Missing tooltips 

I opened some issues to break out specific work. I also open a general "new nivo charts" issue and will take a look and see which would probably be the most useful.
