### ISSUE TITLE
ant theme lines are difficult to see on some resolutions

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3683]
### Summary of the new feature / enhancement

As a developer, I want the 1px lines a little bigger so that i can see them. 

### Proposed technical implementation details (optional)

![image](https://github.com/user-attachments/assets/54fbba77-9bf4-4f9b-a2d4-691cfa2ca46e)

**Comment by adamdriscoll** [comment]
This is a big lift actually because it would require a ton of CSS. If you have specific regions that would be helpful, it might be easier. Otherwise, I'm almost inclined to open something with AntD.

**Comment by Omzig** [comment]
> This is a big lift actually because it would require a ton of CSS. If you have specific regions that would be helpful, it might be easier. Otherwise, I'm almost inclined to open something with AntD.

mainly the dividers on the left, they are nice but the contrast doesn't allow for a primary and secondary region. Oh, maybe if there was some contrast there? like the way github dark mode gives contrast between sections? Maybe it is like elevation 10 or something on the bottom ones.
