### ISSUE TITLE
Get-PSUCache requiring ComputerName. 

### ISSUE THREAD

**Issue by RealDeclan** [ironmansoftware/powershell-universal#3687]
### Version

5.0.4

### Severity

Medium

### Environment

Container

### Steps to Reproduce

1. Create a scheduled script that populates a variable with an object. - Mine is hourly
2. Use Set-PSUCache -Key "MyVariable" -Value $MyValue
3. Create an API endpoint 
4. Call the Cache from the API logic - $ReturnVar = Get-PSUCache -Key "MyVariable"
5. Return the value to the api - return $ReturnVar

### Expected behavior

```console
it should return whatever is in the variable populated by the current cache value.
```

### Actual behavior

```console
Get-PSUCache is erroring as it requires a computer name. The Get-PSUCache docs declares that its not used and passing any computername value in requires authentication.
```

### Additional Environment data

Here is the exact error 
Specify a computer name or use the Connect-PSUServer command.
at <ScriptBlock>, <No file>: line 1
at <ScriptBlock>, <No file>: line 1

https://github.com/ironmansoftware/universal-docs/blob/master/cmdlets/Get-PSUCache.txt

**Comment by adamdriscoll** [comment]
This is due to new permissions enforcement in v5. You can work around by specifying an app token. That said, we're adding a setting in appsettings.json to revert the behavior to v4 for internal commands like this in 5.0.5. 

More info about new module permissions: https://docs.powershelluniversal.com/config/module

**Comment by RealDeclan** [comment]
Hi Adam,

What is the procedure with getting caching in play now with v5.06? Is it still using the app token?


Kind regards,​​​​

Declan E Dunne
Project Engineer
E: ***@***.******@***.***>
|
W: Ortus.ie<https://eu.content.exclaimer.net?url=http%3A%2F%2Fortus.ie%2F&tenantid=elFd28uoEeyZfgBQ8ofJ_Q&templateid=acea38c4b107ef1196f5000d3aaa3a50&excomponentid=mPjkvBPwUqtzBQF8jyfY3n04l-nJaD6-_O23Lmrj9_A&excomponenttype=Link&signature=y3Hw8S7itMhgljo368Qgf9ZQKzBeWGzebD4O3ll1zi2tur-MEwEKE4JgT27gRVLpxZFdWe28LY41OdBGfp4XoQkUl3fbmoDEPmRO0dT8yzAUx6rljE_K_jc_kMKK3DwuNf5SY8HJZikPG2UBoSRvKgHksKExlh5C-0bPjO4rN5Fqg30dASTm1QLzPjsXPopyQ96arEuxaDaPxF6FhEunXux7sgVr9DSNe5av9ppg1dInUTgY62_SYfUX7ZEFhSHHpWrexD0nZniW6cOzGYSQU_cXhi57tSpp_p3weCj6FKemgwe0XmCEMuB21eKj4as0RL4Tc8wi3a27CZuhv6VrAw&v=1>

***@***.***<https://eu.content.exclaimer.net/?url=https%3A%2F%2Fwww.ek.co%2F&tenantid=elFd28uoEeyZfgBQ8ofJ_Q&templateid=acea38c4b107ef1196f5000d3aaa3a50&excomponentid=BQYmbBBnNdIiV-JaSCqtBevUxWE9O9v_kLyz8Jm56WQ&excomponenttype=Image&signature=XJPk9oYXAuXv3Aqzhne4ptt_8Dg3-NXdzHzgjaaRMaX-RUY74pODdgyP-7AKkJ5xZTY3yLRHdrMIw8RWKD_CcuZduyS_0ImcqNDo_5Hah3L8sziNNWUEdKDdCHml_3Z02gbT7sHDmFJQBCpOnZHSqTcXhkrcSdseiMuTDq6SVxoftVj7RA0cxAWATwTsMAxvKfc7j_AnVU7iauAzi_L3yG-Bf75QJ6tW_QsbVCw87oXhKZFq64pgVmXOf77QBjxWGSSeboP7ay711_4LRYAr2elAS2pPgtU_kEvkHFyJfP2jV7Al5If0WOZ1caSDmzxfn5VsU7W4JajQaGnAi8t0nA&v=1>
***@***.***

The contents of this email message and any attachments are intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure.

From: Adam Driscoll ***@***.***>
Sent: Monday, September 2, 2024 3:12 PM
To: ironmansoftware/powershell-universal ***@***.***>
Cc: Declan E Dunne ***@***.***>; Author ***@***.***>
Subject: [DIFFERENT REPLY-TO] Re: [ironmansoftware/powershell-universal] Get-PSUCache requiring ComputerName. (Issue #3687)

This Message has a different reply to address and therefore may not be coming from who it appears to be. Reply-To-Address: ***@***.******@***.***>
________________________________
This is due to new permissions enforcement in v5. You can work around by specifying an app token. That said, we're adding a setting in appsettings.json to revert the behavior to v4 for internal commands like this in 5.0.5.

More info about new module permissions: https://docs.powershelluniversal.com/config/module<https://docs.powershelluniversal.com/config/module>

**Comment by adamdriscoll** [comment]
You only need the app token if you are using this in a scheduled task in strict permission mode. If you are using permissive, it will work without the app token. 

https://docs.powershelluniversal.com/config/module#authorization-security-model
