### ISSUE TITLE
Dashboard  - New-UDPage -Name cannot contain () 

### ISSUE THREAD

**Issue by mwatts-seg** [ironmansoftware/powershell-universal#369]
This may be valid just because the way PU handles URLs from -Name. I just figured I would post here for awareness. 

**Describe the bug**
New-UDPage -Name cannot contain '()' - No errors until you try to view the page, and you get a page cannot be found message. This may be due to how PU treats pages. Looks like  RFC 3986 for standards states the Parenthesis  is reserved. Maybe an error preventing this or allow the user to use it as a name, but change the page URL to something close without the Parenthesis. 

**To Reproduce**
1. Go to 'Dashboards'
2. Edit or create a new Dashboard
3. Add a new page $Pages += New-UDPage -Name 'My Test (Graphical)' -Content { ... }
4. Save & Redeploy
5. Visit Dashboard, this page when clicked will show Page Not Found

**Expected behavior**
I would expect to see an error message in the console and maybe instead of page not found, indicate that there is a error rendering the page. If possible, maybe New-UDPage could strip out the () in the URL, but still allow them on the menu bar. 

**Screenshots**
None

**Version**

Version Number: 2.2.0
Operating System:  Windows 2019

**Additional context**
None

**Logs** 
If needed, I can upload a log.

**Comment by adamdriscoll** [comment]
If you specify the -Url parameter of New-UDPage, you can adjust the actual URL vs the display name. 

```
    New-UDPage -Name 'Test (MyPage)' -Url '/test' -Content {}
    New-UDPage -Name 'Hello' -Content {}
```

That said, the navigation is messed up when I try this so we do have an issue to fix here.
