### ISSUE TITLE
is the documentation uptodate?

### ISSUE THREAD

**Issue by timoline** [ironmansoftware/powershell-universal#3698]
### Version

5.0.5

### Severity

Low

### Environment

msi

### Steps to Reproduce

Is the documentation uptodate ?
https://docs.powershelluniversal.com/apps/components/data-display/data-grid

Missing headerfilter and other new properties

Also Out-UDDataGridData is updated recently

### Expected behavior

```console
uptodate documentation
```

### Actual behavior

```console
not uptodate documentation
```

**Comment by adamdriscoll** [comment]
I updated the docs to point to the cmdlets in the doc repo rather than having to try and document them twice. These cmdlet docs come from the comment-based help.
