### ISSUE TITLE
Endpoint Body not Accepted

### ISSUE THREAD

**Issue by Weg-X** [ironmansoftware/powershell-universal#3707]
### Version

5.0.5

### Severity

Low

### Environment

msi

### Steps to Reproduce

Sending JSON data as a body to an endpoint results in an error. This was working in 4.X.

Create an endpoint at "/api/test" using the "Integrated" environment:
```
return $true
```

From a dashboard, send with some dummy JSON data:
```
$Body = @('TestItem1','TestItem2') | ConvertTo-Json -AsArray
Invoke-RestMethod "https://test.local/api/test" -Body $Body
```

Then, test using a dashboard or using Postman.

As an additional test, I tried passing a hashtable instead of an array like so:
```
$Body = @('TestItem1','TestItem2') | ConvertTo-Json -AsArray
Invoke-RestMethod "https://test.local/api/test" -Body $Body
```
This has the same result for the dashboard, but a different result for Postman.

### Expected behavior

```console
From the dashboard and Postman, I exepect the following to be returned:
"[ true ]"
```

### Actual behavior

```console
From a dashboard, the following error message is shown regardless of if an array or a hashtable converted into JSON is passed:
"The given key 'Content-Type' was not present in the dictionary."

When using Postman to test the endpoint when passed an array converted to JSON, the following error message is shown:
"Invalid JSON body specified. Cannot convert the "TestItem1" value of type "System.String" to type "System.Collections.Hashtable""

When using Postman to test the endpoint when passed a hashtable converted to JSON, no error message occurs and returns:
 "[ true ]"
```

### Additional Environment data

Operating System: Windows Server 2022 Standard

**Comment by adamdriscoll** [comment]
I can't reproduce this. Is it possible /api/test is defined somewhere else? I think a system log may be helpful in tracking down what the system is trying to do with that URL. 

Here are my tests from a PS console. 

```
PS C:\Users\adamr> $Body = @('TestItem1','TestItem2') | ConvertTo-Json -AsArray
PS C:\Users\adamr> Invoke-RestMethod -Uri 'http://localhost:5000/api/test' -Headers @{} -Method 'POST' -Body $Body
True
```

From an app:

```
New-UDDashboard -Title "App" -Content {
    $Body = @('TestItem1','TestItem2') | ConvertTo-Json -AsArray
    $Output = Invoke-RestMethod -Uri 'http://localhost:5000/api/test' -Headers @{} -Method 'POST' -Body $Body
    Show-UDToast ($Output[0].ToString()) -Position topLeft
}
```

![image](https://github.com/user-attachments/assets/a1268650-2a53-4550-800f-00682b83928a)

This is my endpoint. 

```
New-PSUEndpoint -Url "/api/test" -Method @('POST') -Endpoint {
    return $true
} 
```

**Comment by Weg-X** [comment]
Hi Adam,

Thanks for the quick response. I was using GET instead of POST here, so it was operator failure.
