### ISSUE TITLE
IIS with Anonymous Auth enabled prevents Windows auth from working

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3715]
### Version

5.0.5

### Severity

Low

### Environment

msi

### Steps to Reproduce

Create IIS site with anonymous and Windows auth enabled. 
Configure PSU for windows auth

https://forums.ironmansoftware.com/t/upgrade-to-5-05-now-getting-the-supplied-url-is-not-local/11314/5

### Expected behavior

```console
Can login
```

### Actual behavior

```console
Issues with strange redirects and failure to login.
```

**Comment by leihaung-ica** [comment]
having this problem with zip file as well, using IIS.
strangly, most stuff works if I disable anonymous auth, but then I lose functionality for API token.

**Comment by adamdriscoll** [comment]
I can reproduce this in my environment.
