### ISSUE TITLE
Floating Action Button is stuck on the page

### ISSUE THREAD

**Issue by HansenRene** [ironmansoftware/powershell-universal#3720]
### Version

4.3.4

### Severity

Low

### Environment

msi

### Steps to Reproduce

`
New-UDFloatingActionButton -Icon (New-UDIcon -Icon circle-exclamation -Size '2x') -OnClick {
            Show-UDToast -Message "Hello!"
        }  -Size medium -Color primary
`

### Expected behavior

```console
that the FAB stays in the lower right corner
```

### Actual behavior

```console
it scrolls with the rest of the page.
```

### Additional Environment data

in 4.4.0

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/57ad7f17-1300-4fc4-b60d-e0cf367ff919)
![image](https://github.com/user-attachments/assets/89fae9e1-8ed9-4768-8052-0d9c98547edc)

**Comment by donlent** [comment]
Funny, I mentioned that as well a couple of times, also on the forums over the last couple of years. But it seems that nobody really cares about this element. 😅
Anyway, let's hope that adam will check that out and fix it. Would be cool. 🤗
