### ISSUE TITLE
Cache size needs to be increased (PSU 5.0.6)

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#3722]
### Version

5.0.5

### Severity

Critical

### Environment

msi

### Steps to Reproduce

When I'm running scripts that will cache large amount of data in PSU 5.0.6 I do get errors, in PSU 4.4.0 it work's perfectly fine.

### Expected behavior

```console
That I can cache larger amount of data in PSUCache
```

### Actual behavior

```console
Picture:
![CleanShot 2024-09-09 at 14 22 33](https://github.com/user-attachments/assets/2187075f-a228-4138-8672-17b1f9bacfd0)
```

### Additional Environment data

PSU: 5.0.6
PowerShell: 7.4.5
OS: Windows Server 2022

### Screenshots/Animations

![CleanShot 2024-09-09 at 14 22 33](https://github.com/user-attachments/assets/2187075f-a228-4138-8672-17b1f9bacfd0)

**Comment by rwidmark** [comment]
Guessing this is the same issue as : #3700

**Comment by adamdriscoll** [comment]
You are seeing a different error than 3700. I just tried a 100MB file on the latest nightly and it works. 

![image](https://github.com/user-attachments/assets/22606698-3556-4ffb-8324-ec719dd72298)

```
Get-ChildItem C:\users\Administrator\Desktop\test2.txt
Set-PSUCache -Key 'Key123' -Value (Get-Content -Raw C:\users\Administrator\Desktop\test2.txt)
```

This error has something to do with recursion. 

https://learn.microsoft.com/en-us/answers/questions/230401/error-calldepthoverflow-when-running-powershell-st

I'm not saying there isn't a problem with PSU 5.0.6 but I cannot reproduce it.

**Comment by rwidmark** [comment]
@adamdriscoll when I'm rolling back to 4.4.0 everything works.
I'll be back at the computer later (within 2h) I'll check this out once again then.

**Comment by rwidmark** [comment]
Sorry for this @adamdriscoll did forget to mention that the environment that I'm using for this script are running at PS5

But I still have issue with one script that are running in PS7

**Comment by rwidmark** [comment]
Works perfect in psu 5.0.7 latest build
