### ISSUE TITLE
License PayWall Appears when refreshing specific pages (F5)

### ISSUE THREAD

**Issue by mwatts-seg** [ironmansoftware/powershell-universal#3725]
### Version

5.0.5

### Severity

Low

### Environment

msi

### Steps to Reproduce

- Navigate to one of the license required features:
   (Settings->Files, Settings->Branding, Security->Authentication)
- Refresh the page. 
(Note: I discovered this because the component on Settings->Files was not refreshing after I deleted a folder.)

### Expected behavior

```console
Reloads the current page
```

### Actual behavior

```console
Paywall is displayed
```

### Additional Environment data

5.0.6

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/41cb5969-33b4-4307-959a-081a65d0afec)
Refresh
![image](https://github.com/user-attachments/assets/0835d183-df23-4e5b-9e19-8c1a84ed2703)

**Comment by adamdriscoll** [comment]
Can no longer reproduce on 5.0.7.

**Comment by adamdriscoll** [comment]
Customer is reporting this on 5.0.7. 

Docker Container
MSSQL

**Comment by adamdriscoll** [comment]
I was able to reproduce this with the same configure.
