### ISSUE TITLE
Duplicate tab - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#3731]
### Version

5.0.6

### Severity

Low

### Environment

msi

### Steps to Reproduce

If you go the to script page of the PSU dashboard (https://serverFQDN/admin/automation/scripts), and then right click on the browser tab and click duplicate, this error message will show up:
![image](https://github.com/user-attachments/assets/df9f6e41-3462-4c79-8a56-9e9f0be5dec3)

If you then go back to the original tab, and press F5, then the same error message shows up.

To "fix" this, you have to access the /admin page of the server, then it works again.

### Expected behavior

```console
That the error message did not show up
```

### Actual behavior

```console
The error message appears
```

**Comment by adamdriscoll** [comment]
I can't reproduce this one. What authentication type do you use?

**Comment by ksl28** [comment]
OpenID Connect

**Comment by adamdriscoll** [comment]
Hmmm ok. Still can't reproduce. What browser?

**Comment by ksl28** [comment]
Brave (v1.69.162) - but can reproduce on Google Chrome as well, that have never been connected to the server.

**Comment by mwatts-seg** [comment]
I see this from time to time when editing then running the script. If I use the <- link, I will get the error message. 

Steps I did: 
- Find a script (in my case: Corporate -> IT -> OurTeam -> ActiveDirectory -> Test.ps1)
- Edit Script
- Run Script
- ![image](https://github.com/user-attachments/assets/435a9a2b-231c-4ade-8658-77413a4f8265)
- Click <- at the top 
- ![image](https://github.com/user-attachments/assets/02ba4dd8-7305-4e22-8113-27bd70a14e22)

**Comment by adamdriscoll** [comment]
That's good to know. I'm assuming there isn't anything in either of your logs with this error message?

**Comment by mwatts-seg** [comment]
It's not very chatty, and I don't see anything in the log related to it: 

![image](https://github.com/user-attachments/assets/62735c36-d7b3-4228-9875-684985f451e7)

If I need to enable debug or capture anything, let me know. :)
