### ISSUE TITLE
RestAPI (Endpoints) overwrite already existing files

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#3734]
### Version

5.0.6

### Severity

Critical

### Environment

msi

### Steps to Reproduce

Install PSU 5.0.6 make sure that your syncing with GitHub
the endpoint / restapi .ps1 files should be located in subfolders for example /RestAPI/Computer/Test/test.p1

Now when you start PSU it will overwrite the test.ps1 file and it will be blank

### Expected behavior

```console
That PSU will honor already existing / new added endpoint / restapi .ps1 files when they are added with content and not overwrite it
```

### Actual behavior

```console
Overwriting already existing content.
```

**Comment by rwidmark** [comment]
@adamdriscoll can you reproduce this?

**Comment by adamdriscoll** [comment]
No. I followed your steps but I haven't run into this yet.

**Comment by rwidmark** [comment]
> No. I followed your steps but I haven't run into this yet. 

I'll redo them and post them better with config files etc tomorrow it's night here in Sweden and got some no computer before bedtime rule. Else I'll never go to bed 😅

**Comment by rwidmark** [comment]
@adamdriscoll So here is how I have done it, and here is my configuration.

**endpoints.ps1**
```
$Parameters = @{
    Url            = "/rest/Computer/Status/Skrot/:ComputerName"
    Method         = @('PUT')
    Path           = "/ProgramData/UniversalAutomation/Repository/RestAPI/Computer/Status/Skrot.ps1"
    Authentication = $true
    Role           = @('Administrator', 'RestAPI-Dashboard')
    ErrorAction    = "SilentlyContinue"
    Environment    = "Standard"
    Tag            = @('Computer')
    Documentation  = "Test"
}
New-PSUEndpoint @Parameters
```

**Skrot.ps1**
This file are located under the following path `C:\ProgramData\UniversalAutomation\Repository\RestAPI\Computer\Status`

**settings.ps1**
```
ApiBaseFolder                 = "RestAPI"
ScriptBaseFolder            = "Scripts"
```

**Steps to take from clean install of PSU 5.0.7**
- Install PSU 5.0.7.
- Start PSU 5.0.7 and enter admin name and pw
- Stop PSU 5.0.7 services
- Add git information in `appsettings.json`
- Start PSU 5.0.7 process

Now it will overwrite the current API files

**Comment by adamdriscoll** [comment]
Are you populating an empty remote repository? 

Also, this path should not be a full path: 

    Path           = "/ProgramData/UniversalAutomation/Repository/RestAPI/Computer/Status/Skrot.ps1"

It should be: 

    Path           = "Computer/Status/Skrot.ps1"

With the correct path, I do not see this issue.

**Comment by rwidmark** [comment]
@adamdriscoll I'll give it a try when I'm home.
Strange that the c:\ are gone but I'll what you did write later.

**Comment by rwidmark** [comment]
@adamdriscoll works in latest build of 5.0.7.
Found out what was causing it.
Sometimes in environments.ps1 the path was "PowerShell 7" when I did replace that with the correct path it started to work.
It was psu that added "PowerShell 7" in the path during the install of PSU
