### ISSUE TITLE
5.0.6 - Running a schedule script with a parameter defined in the GUI does not pass the parameter to the script

### ISSUE THREAD

**Issue by OS-McNamaraC** [ironmansoftware/powershell-universal#3746]
### Version

5.0.6

### Severity

High

### Environment

msi

### Steps to Reproduce

Create a script with a param() block and then pass a parameter using the PSU GUI when creating a new schedule for that script. The passed parameter will not be taken in by the script, even though it appears in the GUI and in the schedules.ps1 configuration script. 

### Expected behavior

```console
Scripts should respect the parameters passed to them in the schedules GUI
```

### Actual behavior

```console
Scripts are ignoring the parameters passed to them in the schedules GUI
```

### Additional Environment data

To verify this issue, my coworker (author of the script) added the following line to his script - 
```
# Display the parameters that are in use
Write-Host "Parameters in use:"
foreach ($param in $PSBoundParameters.GetEnumerator()) {Write-Host "$($param.Key): $($param.Value)"}
```
And then ran the script manually, passing the parameter, and via a schedule where he set the parameter in the GUI. The manual job reported - 
```
[Information] [9/12/2024 11:40:21 AM] Parameters in use:
[Information] [9/12/2024 11:40:21 AM] Import: True
[Information] [9/12/2024 11:40:22 AM] Transcript started, output file is
```
While the scheduled job returned no parameters 
```
[Information] [9/12/2024 11:43:08 AM] Parameters in use:
[Information] [9/12/2024 11:43:08 AM] Transcript started, output file is .....
```
Parameters for this script are defined as - 

```
Param(
      [Parameter(Mandatory=$false)]
      [switch]$Import,

      [Parameter(Mandatory=$false)]
      [switch]$Export
      )
```

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/0fec8112-082b-4c30-9f8a-903668570867)

**Comment by adamdriscoll** [comment]
This has been resolved in v5.0.7.
