### ISSUE TITLE
Impersonation in PSU

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#375]
Everything currently run as the application user and not the user accessing the browser. It seems there is some functionality we can use with windows auth that may provide the ability to perform impersonation. 

https://docs.microsoft.com/en-us/aspnet/core/security/authentication/windowsauth?view=aspnetcore-5.0&tabs=visual-studio#impersonation

**Comment by Viajaz** [comment]
Might be relevant
https://forums.asp.net/t/2097886.aspx

**Comment by Viajaz** [comment]
Azure OAuth2
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-on-behalf-of-flow

**Comment by adamdriscoll** [comment]
See #309 for more information but the long story short is that the PS engine is not setup for impersonation and fails to even load when under an impersonation context.
