### ISSUE TITLE
Execution Time in Jobs list displayed in incorrect time zone

### ISSUE THREAD

**Issue by nickdollimount** [ironmansoftware/powershell-universal#3753]
### Version

5.0.6

### Severity

Low

### Environment

msi

### Steps to Reproduce

When viewing the Jobs list, the Execution Time is displayed off by a few hours.

### Expected behavior

```console
The Execution Time should be displayed in the local time zone for accuracy.
```

### Actual behavior

```console
The Execution Time is ahead by 3 hours.
```

### Additional Environment data

```
PS C:\Users\nickd> get-timezone

Id                         : Atlantic Standard Time
HasIanaId                  : False
DisplayName                : (UTC-04:00) Atlantic Time (Canada)
StandardName               : Atlantic Standard Time
DaylightName               : Atlantic Daylight Time
BaseUtcOffset              : -04:00:00
SupportsDaylightSavingTime : True
```

**Comment by bt-ndollimount** [comment]
@adamdriscoll With 5.0.9 nightly build, this issue is still present.

![image](https://github.com/user-attachments/assets/c8568fad-f1d9-4239-81fb-ce7d03f0d43c)
![image](https://github.com/user-attachments/assets/27d06db2-eb83-477f-914e-5dcb54901de7)

**Comment by Omzig** [comment]
The time zone is still off, i am in CST and it is 9:11 am, but the job says 2:11 pm. It would be nice to have the time in my timezone ;)

**Comment by adamdriscoll** [comment]
🤦‍♂️ ~I see the issue now. I was actually fixing the time on the schedules page being off and didn't notice the tooltip for execution time being off as well. I thought this was a larger problem where the time zones weren't working everywhere but I can reproduce this no problem.~

🤦‍♂️🤦‍♂️- I actually noticed this on v4 not v5. I still can't reproduce at the moment but will give it another look tomorrow.

**Comment by bt-ndollimount** [comment]
@adamdriscoll This appears to be off in the GIT Status page as well.

![image](https://github.com/user-attachments/assets/a29d4875-939e-403e-89ee-cd79f89377b6)
![image](https://github.com/user-attachments/assets/7540f091-4e49-47ef-92f3-a708084b28e9)

**Comment by Omzig** [comment]
> 🤦‍♂️ ~I see the issue now. I was actually fixing the time on the schedules page being off and didn't notice the tooltip for execution time being off as well. I thought this was a larger problem where the time zones weren't working everywhere but I can reproduce this no problem.~
> 
> 🤦‍♂️🤦‍♂️- I actually noticed this on v4 not v5. I still can't reproduce at the moment but will give it another look tomorrow.

I see it in v5, the GMT is gone, but the date is still GMT.

**Comment by adamdriscoll** [comment]
This is certainly an overall problem with the time conversion for the console. I'm adding a new detail to the My Identity page to help track this down. It will display the detected time zone. 

![image](https://github.com/user-attachments/assets/4be8ba38-18ca-469a-9ff5-72c8fabf3407)

I am not seeing this on either my local machine or my VM in PDT. Still futzing with it. 

EDIT: I've adjusted how this works to just use the client-side DayJS library to avoid converting the timezones at the server at all. This change will be in tonight's nightly build.

**Comment by bt-ndollimount** [comment]
@adamdriscoll This appears to still be off in public release of 5.0.10.
![image](https://github.com/user-attachments/assets/236cc5af-0e0e-4b83-9102-e0ee10df08a0)
![image](https://github.com/user-attachments/assets/911d9817-f48b-49a0-be7a-56f4edbdab94)

**Comment by Omzig** [comment]
![image](https://github.com/user-attachments/assets/f2038fe3-d46f-42d2-adf6-86e4c54fd519)

**Comment by adamdriscoll** [comment]
This is something fundamental I'm missing here. Here's 5.0.10 running a VM that is in PDT. Accessing it there gives the time in that time zone. Accessing the same server and viewing the same jobs from my machine in CDT returns the correct time in CDT. 

![image](https://github.com/user-attachments/assets/3d706642-b463-4910-81b6-6b4cbdc6cb69)

**Comment by adamdriscoll** [comment]
We determined this is a PostgreSQL problem.
