### ISSUE TITLE
5.0.6 - The Web Code Editor clears-out everything if you tab on the Intellisense suggestions

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#3758]
### Version

5.0.6

### Severity

Quality-of-life

### Environment

msi

### Steps to Reproduce

1. Login to PSU Admin
2. Create a Script, an App, whatever you want
3. Edit the Code using the Browser
4. Start typing any commandlet and don't use tab for now... Example:
`New-UDButton -Text "Save" -Icon (New-UDIcon -Icon "floppydisk" -Size 2x) -Variant outlined`
5. Now put the cursor between` "Save"` and `-Icon`. Start typing `-Show` and Tab in order to autocomplete the IntelliSense suggestion for `-ShowLoading`
6. You will notice that a good part that comes after ShowLoading has been overwritten. Not really practical. 😅

Ps. Sorry for having opened some many issues one after the other. I know it's annoying. 😏 I just collected them the last couple of weeks and was too lacy to report them right away, except for the critical one related to the Agents.

### Expected behavior

```console
Tabbing for the IntelliSense Suggestion should not overwrite what comes behind the cursor
```

### Actual behavior

```console
Tabbing for the IntelliSense suggestion overwrites what comes right after it
```

**Comment by adamdriscoll** [comment]
No worries. Keep em coming! I've also experienced this so I'm sure a lot of folks would like it fixed.
