### ISSUE TITLE
Repository Reorganization

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#376]
Hi,
Today we can't sync components with GIT and that's something that would be great if it was possible.
A new Repo is needed I guess as it syncs the folder right off.

So one Repo GIT sync for Dashboard and Scripts
One Repo for GIT with Components

**Comment by rwidmark** [comment]
@adamdriscoll Or is it possible for you to move the Components folder to the same folder as Dashboards and Scripts?
That folder structure should bee something like this:
-RootFolder-
- Dashboards
- Scripts
- Components
- - Different components
- -- version
- --- files

**Comment by adamdriscoll** [comment]
I like this approach. It should be pretty straightforward to implement in this regard.

**Comment by adamdriscoll** [comment]
Additional Requirements:

- Backwards compatibility
- Integration with folders

**Comment by rwidmark** [comment]
Don't forget to include .Universal folder also - It's perfect to sync with Git. Also exclude the licens.ps1 file as if you have multi servers you don't want that to sync with git.

**Comment by rwidmark** [comment]
Nvm, you don't need to exclude the licens file as you just can add it to gitignore I guess

**Comment by adamdriscoll** [comment]
I've added a new customization for setting the Script Base Folder. This means that it will continue to function the same but if you want your scripts in a sub folder, you just set that setting and it will move all scripts into that folder. Any new scripts will be created in that folder. The component functionality is also available but needs to be documented properly.

**Comment by rwidmark** [comment]
> I've added a new customization for setting the Script Base Folder. This means that it will continue to function the same but if you want your scripts in a sub folder, you just set that setting and it will move all scripts into that folder. Any new scripts will be created in that folder. The component functionality is also available but needs to be documented properly.

Perfect! Is it working in 2.3.1?

**Comment by rwidmark** [comment]
@adamdriscoll can't figure out how to do this with the script folder?
And components, any documentation over it?

**Comment by adamdriscoll** [comment]
This will be in 2.4. I will tag issues with milestone so you know which release it's in.

**Comment by rwidmark** [comment]
> This will be in 2.4. I will tag issues with milestone so you know which release it's in. 

Nice, sorry that I did miss that.
