### ISSUE TITLE
Sub Apps Href not working

### ISSUE THREAD

**Issue by Twenty94470** [ironmansoftware/powershell-universal#3760]
### Version

5.0.6

### Severity

Medium

### Environment

msi

### Steps to Reproduce

Hello,

I've created a main Apps named 'Home_Services', in this app I've created a sub page named 'test', with the navigation panel I want to go on this subpage 'Test'

> New-UDApp -Title "Web Service" -Content {
> 
> }
> } -Navigation (
>     New-UDList -Children {
>         New-UDListItem -Label "Home" -Href "/Home_Services" 
>         New-UDListItem -Label "Printers" -Children {
>             New-UDListItem -Label "Installation" -Href '/test' 
>         }
>     }
> ) -NavigationLayout permanent

The Home button work, the Installation button not, I got "Page Not Found"
I try many link without result :
-Href '/test' 
-Href './test' 
-Href '/Home_Services/test' 
....

![Capture d'écran 2024-09-14 013215](https://github.com/user-attachments/assets/c0508252-ee74-4db5-9b55-b47b8ea3b163)

![Capture d'écran 2024-09-14 012615](https://github.com/user-attachments/assets/c9c7cb18-1e6c-4267-bb0f-070f9241ab7f)

### Expected behavior

```console
Go to test subpage
```

### Actual behavior

```console
Page Not found
```

**Comment by adamdriscoll** [comment]
You need to include your page in your app for it to show. I verified this works in v5.0.6. 

```
New-UDApp -Title "Web Service" -Pages @(
   Get-UDPage -Name 'Test'
) -Navigation (
New-UDList -Children {
New-UDListItem -Label "Home" -Href "/Home_Services"
New-UDListItem -Label "Printers" -Children {
New-UDListItem -Label "Installation" -Href '/test'
}
}
) -NavigationLayout permanent

The Home button work, the Installation button
```

**Comment by Twenty94470** [comment]
Thanks for the reply, I should miss something but on my side, I dont have the expected behaviour,

When I use your code, and when I launch the main page "Web Service" I'm automatically redirected in an empty test page. but on the code of my real test page I have a button for example and the Home button doesn't work now " Page not found" 
![Capture d'écran 2024-09-15 230510](https://github.com/user-attachments/assets/d6ab6674-a565-42a7-aa67-3d7ffb7462c1)
![Capture d'écran 2024-09-15 230534](https://github.com/user-attachments/assets/8e0a5897-2a8a-45b9-86c7-7469a5f4ff49)
![Capture d'écran 2024-09-15 230722](https://github.com/user-attachments/assets/6c2d1984-9b23-4ae2-8fc5-bda5df3e75d5)
