### ISSUE TITLE
Invoke-PSUScript from inside of another script that is triggered on a sheduled task results in "Cannot retrieve the dynamic parameters for the cmdlet. Specify a computer name or use the Connect-PSUServer command."

### ISSUE THREAD

**Issue by JessePeden** [ironmansoftware/powershell-universal#3769]
### Version

5.0.7

### Severity

Low

### Environment

msi

### Steps to Reproduce

With the `"SecurityModel"` set to `"Strict"` and `"TrustCertificates"` set to `true` in appsettings.json under the "Api" category, if a scheduled task launches a script that calls `Invoke-PSUScript` to launch other scripts, the result is that the job fails and you receive the error `"Cannot retrieve the dynamic parameters for the cmdlet. Specify a computer name or use the Connect-PSUServer command."`

Changing the `"SecurityModel"` to `"Permissive"` allows the scripts called via the script referenced in the schedules task to run as normal.

`Invoke-PSUScript` runs without issue while `"SecurityModel"` is still in `"Strict"` mode, for reference, so this behavior seems to only affect certain aspects of PSU's internal communications.

### Expected behavior

```console
PSU should be able to talk to its own processes without error
```

### Actual behavior

```console
PSU cannot talk to its own processes without error
```

**Comment by adamdriscoll** [comment]
Did you specify an app token? The problem is that in the strict mode, schedules have no security context and it's actually failing to authenticate. The error message should be better. 

We have some plans to make this more seamless but it's the current status of the scheduler in strict mode. It's similar to the issue where if you have secret variables that define -Roles in a schedule, they aren't accessible via $Secret because there is no user context.

**Comment by JessePeden** [comment]
> Did you specify an app token? The problem is that in the strict mode, schedules have no security context and it's actually failing to authenticate. The error message should be better. 
> 
> 
> 
> We have some plans to make this more seamless but it's the current status of the scheduler in strict mode. It's similar to the issue where if you have secret variables that define -Roles in a schedule, they aren't accessible via $Secret because there is no user context. 

I see. You've mentioned this before but I guess I didn't really pay attention to it.

Rather than defining an app token to use with a `Connect-PSUserver` above the rest of the commands, is it possible to just set the scheduled task to use Run As, and use whatever account that's set to with the child jobs it creates?
