### ISSUE TITLE
5.0.7 - Received message exceeds the maximum configured message size.

### ISSUE THREAD

**Issue by emoeckel** [ironmansoftware/powershell-universal#3775]
### Version

5.0.6

### Severity

High

### Environment

msi

### Steps to Reproduce

Have an API Endpoint retrieving cache.
Hit the endpoint with PS from a client device

### Expected behavior

```console
Retrieve my data
```

### Actual behavior

```console
From Client Device:

PS C:\Users\v-emoeckel\OneDrive - Alaska Airlines, Inc\Documents\Scripts> $Test = Invoke-RestMethod http://igqprmgtpsu01:443/RVTools_vInfo -Method GET
Invoke-RestMethod: Status(StatusCode="ResourceExhausted", Detail="Received message exceeds the maximum configured message size.")
at , : line 2
at , : line 1

From Server Logs:

[9/16/2024 9:12:33 AM] [Information] [Api-1] Status: 400 Content-Type: application/json Length: 186 

[9/16/2024 9:12:33 AM] [Error] [Api-1] Status(StatusCode="ResourceExhausted", Detail="Received message exceeds the maximum configured message size.") 

[9/16/2024 9:12:33 AM] [Information] [Api-1] GET /RVTools_vInfo ::ffff:10.21.113.109
```

### Additional Environment data

AppSettings.json API Snippet:
   "Api": {
       "SecurityModel": "Permissive",
       "TrustCertificate": true
    }

5.0.7
API Endpoint using Integrated
Client using VS Code w/ PS 7.4.4

**Comment by adamdriscoll** [comment]
I have realized we set the max received size on the server but not the cmdlet client so while this error went away when sending large data to the server, receiving large data from the cmdlets still has the issue.

**Comment by emoeckel** [comment]
Awesome thank you so much!!!
