### ISSUE TITLE
App Tokens are seemingly randomly not displayed

### ISSUE THREAD

**Issue by JessePeden** [ironmansoftware/powershell-universal#3783]
### Version

5.0.7

### Severity

Low

### Environment

msi

### Steps to Reproduce

Creating a new App Token often results in no display of the token (in the green window) to allow the user to copy the token, resulting in a user not being able to use the token at all in cases where PSU is set to use enhanced app token security, thereby removing the user's ability to use the copy button next to a token.

### Expected behavior

```console
The token should be visible in the notification popup box upon creation each time, without fail.
```

### Actual behavior

```console
The token most often does NOT display after creation.
```

**Comment by JessePeden** [comment]
For the record, the current workaround I'm using is to generate the tokens via the Swagger API page.

**Comment by JessePeden** [comment]
@adamdriscoll Is https://github.com/ironmansoftware/powershell-universal/issues/3811 related to this bug, too, maybe?  I don't think it is, since I've had it happen in Firefox as well as Chromium-based browsers, but figured I'd ask anyway.

**Comment by adamdriscoll** [comment]
I don't think so. I think this is something else.
