### ISSUE TITLE
Intermittent Schedule Failures in High Availability (HA) Setup and API Returning 400 Errors with Debug Logging Enabled in PSU Version 4.4.0

### ISSUE THREAD

**Issue by RubenT91** [ironmansoftware/powershell-universal#3784]
### Version

4.3.4

### Severity

Medium

### Environment

msi

### Steps to Reproduce

- Configure PowerShell Universal (PSU) version 4.4.0 in a high-availability (HA) setup with two nodes.
- Set up schedules using the New-PSUSchedule cmdlet, ensuring that the schedules are visible and expected to run across all nodes.
- Monitor schedules for intermittent failures, particularly on one node, while the other node is placed in maintenance mode.
- Enable debug logging in appsettings.json with the following:
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug"
    }
  }
}

- After enabling debug logging, observe that API endpoints begin returning 400 errors when making API calls.

### Expected behavior

```console
All schedules should trigger reliably across nodes in an HA setup, regardless of which node creates the schedule.
Enabling debug logging should not interfere with API endpoint functionality, and all API requests should return valid responses without 400 errors.
```

### Actual behavior

```console
Schedules intermittently fail to trigger on certain nodes in the HA setup, even when one node is placed in maintenance mode. No discernible pattern or errors are present in the logs.
When debug logging is enabled via appsettings.json, API endpoints start returning 400 errors. Removing the debug logging configuration restores API functionality (returns 200).
```

### Additional Environment data

Operating System: Windows Server 2022 (HA setup)
Environment: MSI installation
Debug logs were requested but enabling them caused API errors, which could be part of the root cause.

**Comment by adamdriscoll** [comment]
@RubenT91 - Can you attach the logs?

**Comment by RubenT91** [comment]
> @RubenT91 - Can you attach the logs?

[logs.2024-09-18 (1).zip](https://github.com/user-attachments/files/17050223/logs.2024-09-18.1.zip)
