### ISSUE TITLE
API Key without identity

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#3794]
### Summary of the new feature / enhancement

We have several solutions with seperated frontend / backend PSU servers, and they communicate through PSU APIs.
Right now we have to create a dummy user (apiuser01), assign it to a role, just to be able to create an API token.

It would be nice if we could create an token, and assign it to a role - without having to create a user.

**Comment by JessePeden** [comment]
This has been requested previously.  https://github.com/ironmansoftware/powershell-universal/issues/3185#issue-2195385000

It's tagged to be in 5.1.

**Comment by adamdriscoll** [comment]
Closing as duplicate.
