### ISSUE TITLE
Parameter sets for API Methods

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#3798]
### Summary of the new feature / enhancement

We support multiple methods for endpoints, but we should be able to use them in parameter sets. This would allow for better validation logic using parameter validation attributes and avoid having to do a lot of if\else logic in the body of the endpoint. 

An example would be where a name parameter is required for PUT but not for GET. We could use switch parameters to define which parameter set is being called. These should be optional, and we won't set them if they do not exist in the param block for backwards compatibility. 

```powershell
[Parameter(ParameterSetName = "PUT", Mandatory)]
[Switch]$Put,
[Parameter(ParameterSetName = "PUT", Mandatory)]
[Parameter(ParameterSetName = "GET")]
[string]$Name,
[Parameter(ParameterSetName = "GET", Mandatory)]
[Switch]$Get,
```

**Comment by ksl28** [comment]
That would be amazing! Any chance, this could be ported back to 4.4.x ?

**Comment by adamdriscoll** [comment]
As long as the implementation isn't too complex we'll merge it back. I don't anticipate that will be the case so we should be able to get it into 4.4.1 or 4.4.2

**Comment by ksl28** [comment]
Awesome! We are looking forward to this feature then :)
