### ISSUE TITLE
5.0.7 - Making changes to a schedule wipes all existing configured parameters on all other schedules

### ISSUE THREAD

**Issue by bt-ndollimount** [ironmansoftware/powershell-universal#3799]
### Version

5.0.6

### Severity

Critical

### Environment

msi

### Steps to Reproduce

Making changes to any schedule wipes all configured parameters from all other existing schedules.

### Expected behavior

```console
Configured parameters should be retained on all other schedules not being modified.
```

### Actual behavior

```console
Modifying any schedule wipes the existing configured parameters for all other schedules.
```

### Additional Environment data

Version 5.0.7

**Comment by adamdriscoll** [comment]
Are you setting any specific property that causes this? Or is it anything you set? I can't reproduce on my end at the moment.

**Comment by bt-ndollimount** [comment]
> Are you setting any specific property that causes this? Or is it anything you set? I can't reproduce on my end at the moment.

I tested with just opening the properties of a random schedule and clicking 'Ok' without making any actual changes and this also wipes the parameters. Checking the schedules.ps1 file right after and they're gone.

If I have one that has parameters, then set parameters on a second one, the first one is wiped while the second one gets the parameters saved. So setting parameters does save the parameters for that script at the time, but it also wipes any others out.

**Comment by adamdriscoll** [comment]
Is there any way you can send me your schedules.ps1? I want to replicate your environment best I can.

**Comment by bt-ndollimount** [comment]
@adamdriscoll I just submitted a ticket with the same title as this issue. I pasted the schedules.ps1 file in the body.

**Comment by bt-ndollimount** [comment]
@adamdriscoll I tested this in a lab with only 3 schedules where 2 of them have parameters set. I saved changes to the schedule without parameters and the issue was not present. It may have to do with the amount of schedules we have in production.

**Comment by bt-ndollimount** [comment]
@adamdriscoll To make things even more interesting... I had manually updated the schedules.ps1 file yesterday and restarted the service on 1 of 3 hosts. Side-note, the other 2 hosts didn't actually pull in the changes from the updated schedules.ps1 file (separate issue). Today, when I realized all the 'Waiting for feedback' because it was still running on the other two hosts, I decided to pause those two schedules. Making the change to pause them did not remove the parameters in the schedules.ps1 file; it just added the -Paused to the end of both schedules.

**Comment by adamdriscoll** [comment]
Ok. I'll continue to try to reproduce. I do think having a larger number of schedules may have something to do with it so that's where I'm looking.

**Comment by adamdriscoll** [comment]
I put in a lot of time on schedule parameters this release. There were certainly scenarios where this could happen. I did not reproduce this directly but did reproduce a lot of other problems. Based on all my automated and manual testing, I think this should be resolved. Please feel free to comment again if you run into it.
