### ISSUE TITLE
OIDC login blank page

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#380]
PSU 2.2.1

Configure OIDC, login to Universal, blank page is shown. 

URL is /api/v1/auth/redirect?url=/admin

**Comment by Viajaz** [comment]
I have a similar issue, but it's only occurs when I try to go to a specific PSU component directly (eg: `/admin/automation/jobs/1234`) without an authenticated session, but logging it via `/admin` directly works fine.
