### ISSUE TITLE
5.0.8 - Can't Start Debugger "Wait-Debugger"

### ISSUE THREAD

**Issue by emoeckel** [ironmansoftware/powershell-universal#3803]
### Version

5.0.6

### Severity

Medium

### Environment

msi

### Steps to Reproduce

Put Wait-Debugger somewhere in the script.

### Expected behavior

```console
Click on job, and debug within PSU
```

### Actual behavior

```console
It pauses the script at the "Wait-Debugger" part of the script, but the job shows running. When I click to view the job, I don't get a debugger. 

On top of that, according to the documentation, I have to enable debugging within the Settings > Environment, I can't find that. Will upload screenshots.
```

### Additional Environment data

5.0.8

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/ab92701b-140a-4548-be25-b029c7648f93)
![image](https://github.com/user-attachments/assets/bdfef53b-3f8c-4af4-bfbd-b1981050749b)
![image](https://github.com/user-attachments/assets/8633bb7b-bd2f-4b71-ac5b-e481390cc4d2)
![image](https://github.com/user-attachments/assets/8df48e8f-c00a-4d6d-9932-b88fa4fd5dbd)
![image](https://github.com/user-attachments/assets/ed196fb5-f116-4c30-a2c6-65394b17d82f)
![image](https://github.com/user-attachments/assets/4ee9a6b1-d922-400f-bac3-e379abb61652)

**Comment by adamdriscoll** [comment]
I've updated the docs to remove the old v4 info. I can also reproduce this with the Integrated environment. In WinPS, it doesn't break at all. In PowerShell 7, it works.
