### ISSUE TITLE
5.0.8 - Missing 'busy' indicator

### ISSUE THREAD

**Issue by bt-ndollimount** [ironmansoftware/powershell-universal#3814]
### Version

5.0.8

### Severity

Quality-of-life

### Environment

msi

### Steps to Reproduce

When performing any action in the interface, there is no busy indicator to let you know that it's working in the background. This allows you to think you've mis-clicked on something and then you can click again or end up clicking somewhere else, which seems to get queued.

### Expected behavior

```console
There should be a busy indicator, preferably with a darkened overlay to stop you from clicking on other items while it's busy.
```

### Actual behavior

```console
You're able to click around while it's busy, seeming like the interface is not responding, until it's completed its current task then your queued clicks are actioned.
```

**Comment by adamdriscoll** [comment]
I finally found the reason for the weird delays in the admin console. I've hit many of the hot paths but there are likely actions\pages that might need some work done so I will open on specific issues for those as they pop up.
