### ISSUE TITLE
5.0.8 - Schedules configured to a computer group do not trigger

### ISSUE THREAD

**Issue by bt-ndollimount** [ironmansoftware/powershell-universal#3817]
### Version

5.0.8

### Severity

High

### Environment

msi

### Steps to Reproduce

Configuring a schedule to run on a computer group, the schedule will not trigger both on schedule and manually.

### Expected behavior

```console
Configuring a schedule to run on a computer group, the schedule will not trigger both on schedule and manually.
```

### Actual behavior

```console
A schedule configured to run on a computer group should trigger both on schedule and manually.
```

**Comment by adamdriscoll** [comment]
Duplicate of #3768

**Comment by bt-ndollimount** [comment]
@adamdriscoll I tested this in 5.0.9. Schedules configured to a computer group do trigger now, however manually triggering the schedule still doesn't create a job. This isn't a huge deal as you can still run it manually directly from the script, but still would be good for manually testing schedules instead of waiting for them to trigger on schedule.
