### ISSUE TITLE
Add memory usage to /admin home dashboard

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3828]
### Summary of the new feature / enhancement

not sure where to put this information, or if we can even get this information to put on the admin site.

if you could break it down by env/app/job/api?

We had a problem where psu ran over 40% cpu and we had to recycle the app pool 2 times to recover from using 16GB (all) of memory. We looked in the logs, and could not identify the bad actor. It is not intuitive, to what was using all of our resources. 

FYI: We almost didn't have enough resources to recycle the app pool.

**Comment by adamdriscoll** [comment]
We could only break it down if the resources are running in external environments but not the integrated environment. Certainly something we can add. We already check system memory with the health check and have process info already so we should be able to do that pretty easily and provide a nice little clickable chart.
