### ISSUE TITLE
Read Excel file fail

### ISSUE THREAD

**Issue by Twenty94470** [ironmansoftware/powershell-universal#3836]
### Version

5.0.8

### Severity

Quality-of-life

### Environment

msi

### Steps to Reproduce

Hello,

I've created a simple excel file, A1 = Test
When I run the script into the ise program I can see the cell content "Test" when I run the same script into Powershell Universal, I got an error  : 
**"Microsoft Excel cannot access the file ' C:\Sources\Classeur1.xlsx'
- The file name or path does not exist
- The file is being used by another program
- The workbook you are trying to same has the same name as a currently open workbook
You cannot call a method on a null-valued expression.
Unable to find type [Microsoft.Office.Interop.Excel.XlSearchOrder]."**

There is no excel process in background, I've checked the excel file is not already opened.

```
# Script contents
$excel = New-Object -ComObject Excel.Application
$excel.Visible = $false
$excel.DisplayAlerts = $false

$workbook = $excel.Workbooks.Open("C:\Sources\Classeur1.xlsx")
$sheet = $workbook.Sheets.Item(1)
$lastRow = $sheet.Cells.Find("*", [System.Reflection.Missing]::Value,
                                [System.Reflection.Missing]::Value,
                                [System.Reflection.Missing]::Value,
                                [Microsoft.Office.Interop.Excel.XlSearchOrder]::xlByRows,
                                [Microsoft.Office.Interop.Excel.XlSearchDirection]::xlPrevious,
                                $false, [System.Reflection.Missing]::Value,
                                [System.Reflection.Missing]::Value).Row


for ($row = 1; $row -le $lastRow; $row++) {
$sheet.Cells.Item($row, 1).Text
}
```

### Expected behavior

```console
Read excel file line by line
```

### Actual behavior

```console
error during openning excel file
```

### Additional Environment data

Office 2021 LTSC

### Screenshots/Animations

![Capture d'écran 2024-09-27 225943](https://github.com/user-attachments/assets/e35dab60-709d-4c30-8e45-f572f8cf8559)
![Capture d'écran 2024-09-27 230026](https://github.com/user-attachments/assets/4ed0a42a-6dc8-42c5-bed4-616f3552f6e9)
![Capture d'écran 2024-09-27 230138](https://github.com/user-attachments/assets/6ba32d97-d776-4cb6-ba5a-c78cd3d73f3c)

**Comment by rwidmark** [comment]
Have you made sure that PSU service account have permission to the file?
Also made sure to unblock it if it's blocked?

Unblock-File -Path "path to excel file"

I'm pretty sure it's unblock-file, im on my phone now. But it's a PowerShell function so just google it if it won't work.

**Comment by Twenty94470** [comment]
Hello thanks for your reply,

PSU is installed with system account, so yes, on the security tab, the system account as full access, 
The file was created on local, so there is not "Unsecure" like if I copy paste the file from network share, 

I try your command with verbose, but I still have the error on the excel file : 
![image](https://github.com/user-attachments/assets/1600a09d-627d-4e03-8eaa-8e40907f9695)

I check on google but all solution didn't works.

I don't know if on another environnement, you have the same result ?

Regards

**Comment by rwidmark** [comment]
> Hello thanks for your reply,
> 
> 
> 
> PSU is installed with system account, so yes, on the security tab, the system account as full access, 
> 
> The file was created on local, so there is not "Unsecure" like if I copy paste the file from network share, 
> 
> 
> 
> I try your command with verbose, but I still have the error on the excel file : 
> 
> ![image](https://github.com/user-attachments/assets/1600a09d-627d-4e03-8eaa-8e40907f9695)
> 
> 
> 
> I check on google but all solution didn't works.
> 
> 
> 
> I don't know if on another environnement, you have the same result ?
> 
> 
> 
> Regards
> 
> 

I have not tried it, the things I did write above was how I did solve it with word files.
Unblock-file did solve it for me.

Or wait, I needed to call on a script from the endpoint.
So I did never figure this out. But did a work a round.

Create a script file with your code then execute ps with that file from psu.

**Comment by Twenty94470** [comment]
Hello,

I got the same error, but I fix my error by using the import-excel module. https://github.com/dfinke/ImportExcel 
I let the issue opened if the COM object can be fixed. 

Regards

**Comment by adamdriscoll** [comment]
COM is going to be very problematic in a service like this. I would highly recommend just using the ImportExcel module to avoid it.
