### ISSUE TITLE
Unable to edit Widget

### ISSUE THREAD

**Issue by AniTexs** [ironmansoftware/powershell-universal#3839]
### Version

5.0.8

### Severity

Medium

### Environment

msi

### Steps to Reproduce

1. Create Portal Widget
2. Try to edit the widget

### Expected behavior

```console
Navigate to edit page
```

### Actual behavior

```console
Noting happens except it changes the URL Path but nothing UI is happening, reloading results in this error: `Object reference not set to an instance of an object.`
```

### Additional Environment data

Installed via Powershell Module.

### Screenshots/Animations

![Animation](https://github.com/user-attachments/assets/12bfa89f-096e-46c9-93fd-5d5312487e86)

**Comment by adamdriscoll** [comment]
~@AniTexs - Can you verify if you are using Windows authentication?~

Never mind. I can reproduce with forms as well.
