### ISSUE TITLE
5.0.9 - Issue with Invoke-PSUScript

### ISSUE THREAD

**Issue by bt-ndollimount** [ironmansoftware/powershell-universal#3845]
### Version

5.0.9

### Severity

Medium

### Environment

msi

### Steps to Reproduce

Scheduled scripts that use Invoke-PSUScript don't complete.

### Expected behavior

```console
A script that uses the Invoke-PSUScript command to execute a separate child script should complete.
```

### Actual behavior

```console
The parent script remains in 'Running' state.
```

### Additional Environment data

5.0.9 public release
I'm using the Invoke-PSUScript command as the very last part of the script so there's nothing holding the script up from completing.

### Screenshots/Animations

Script example:
![image](https://github.com/user-attachments/assets/e0f2c7b5-c55d-4383-95c6-f38c631a8fc2)

![image](https://github.com/user-attachments/assets/ec88127b-88aa-4973-a1df-9f48dc6c32a7)

**Comment by adamdriscoll** [comment]
Can you let me know what database you are using?

**Comment by bt-ndollimount** [comment]
> Can you let me know what database you are using?

PostgreSQL 16.4

**Comment by bt-ndollimount** [comment]
@adamdriscoll I noticed today that those two scripts that got stuck yesterday (I had to cancel them), they didn't run on their schedule this morning and show the next run to be tomorrow. I just kicked off their schedules manually and they're stuck running again after invoking the other script that completes.

Is there anything you'd like me to check?

**Comment by adamdriscoll** [comment]
I'm still looking into this. I can't reproduce it myself at the moment. 

If you add a short delay after the Invoke-PSUScript, do you see a different behavior? 

Invoke-PSUScript
Start-Sleep 1

**Comment by bt-ndollimount** [comment]
@adamdriscoll I can't test this at the moment but one thing that might be helpful is that I'm pretty sure it only occurs on scheduled scripts. I remember when I first tested the Invoke-PSUScript command, I was manually running it and that ran and completed fine. I'll give the delay a try in a little bit and report back.

**Comment by adamdriscoll** [comment]
Gotcha. Let me continue to test.

**Comment by bt-ndollimount** [comment]
With testing, it seems to be hit or miss. In the screenshot below, you'll see one that finished and it only ran for 12 seconds before finishing. The one currently going (no changes to scripts) is now going for over 4 minutes as I'm typing this.

![image](https://github.com/user-attachments/assets/50dcd185-5597-4af0-91a9-132eb07d7135)

**Comment by adamdriscoll** [comment]
I reproduced this but backwards.

![image](https://github.com/user-attachments/assets/c954b9a5-9c40-46b0-b06a-082f16921226)

**Comment by bt-ndollimount** [comment]
> I reproduced this but backwards.
> 
> ![image](https://private-user-images.githubusercontent.com/1256531/373347504-c954b9a5-9c40-46b0-b06a-082f16921226.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5ODIxOTQsIm5iZiI6MTcyNzk4MTg5NCwicGF0aCI6Ii8xMjU2NTMxLzM3MzM0NzUwNC1jOTU0YjlhNS05YzQwLTQ2YjAtYjA2YS0wODJmMTY5MjEyMjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDNUMTg1ODE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjgzZjU4MGI3MGJhMDlhYzFlN2E5YWMxMzBkYjc2NjcxMjgwODVjMjMwMDIyZjRlMGI4MmEyOWJjOTg0MDgxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.dNErsKgvyVsi8ByWYZHXhSoxo2OUXDoQpvxQMe1J70M)

Hopefully it's the same cause 🤞

**Comment by bt-ndollimount** [comment]
@adamdriscoll This issue seems to have either returned or wasn't fixed in the previous fix. I had previously changed from using Invoke-PSUScript to putting the script into a custom module as a workaround from the last time. Trying to use this again for a different set of scripts and we're running into the same issue. You can see from the screen shot that the children are completing but the top parent continues as 'Running'.

![image](https://github.com/user-attachments/assets/1dc97372-9c95-4419-957f-29c2f5392b3a)
