### ISSUE TITLE
Unable to edit endpoint from /admin/apis/endpoints

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3866]
### Version

5.0.9

### Severity

Medium

### Environment

Nested IIS

### Steps to Reproduce

i am unable to make consistent changes to the api using the cog

- goto /admin/apis/endpoints
- click cog
- add an api documentation
- click save

or
- click cog
- remove api doc
- click save

### Expected behavior

```console
changes are reflected when you edit again
```

### Actual behavior

```console
no changes are saved, sometimes they are sometimes they are not
```

**Comment by Omzig** [comment]
I can change other things, its just the doc and the tags that are janky

**Comment by adamdriscoll** [comment]
I think this is the same issue as #3868
