### ISSUE TITLE
Swagger doc is not being generated

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3867]
### Version

5.0.9

### Severity

Medium

### Environment

Nested IIS

### Steps to Reproduce

create an api

### Expected behavior

```console
swagger doc should have endpoints
```

### Actual behavior

```console
no endpoints in the doc
```

**Comment by adamdriscoll** [comment]
I can't reproduce this. I just add an endpoint, and it shows up. That said, it may be that I'm running 5.0.10 latest. 

![image](https://github.com/user-attachments/assets/790d88de-9caa-423c-afc4-9a59f963df61)

**Comment by Omzig** [comment]
i am in nested IIS, i think that is the problem

**Comment by adamdriscoll** [comment]
I just tried on a nested IIS site as well and it works there too. That said, I don't have anything complex so I wonder if it's something else. I probably need some logs. 

![image](https://github.com/user-attachments/assets/ee7de45e-7e8f-4aea-b466-4a52bd257e0a)

**Comment by Omzig** [comment]
@adamdriscoll, sent you an email with the logs.

**Comment by adamdriscoll** [comment]
Thanks. I don't see anything specific in the logs about errors with endpoint docs. That said, the doc generation service is kinda lacking in solid logging. I will add that to better capture what might be happening.

**Comment by Omzig** [comment]
@adamdriscoll, this is fixed now in 5.0.10

what did you do? hehehe

I think i figured it out, but it doesn't follow the same pattern as the main swagger doc

**Comment by adamdriscoll** [comment]
Not sure. Let me know what's different

**Comment by adamdriscoll** [comment]
Fixed the thing with the servers drop down.

**Comment by Omzig** [comment]
Funny thing, if you put security on and add it to a role like ServiceAccounts, you also need to add Administrators or you WILL NOT see the documentation because the role based security will hide the documentation from you.
