### ISSUE TITLE
Make a change in files, not reflected in GUI

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3868]
### Version

5.0.9

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

Make a change in files, you have to recycle the app pool to get the GUI to see the changes.

- open /admin/settings/files
- edit an endpoint and remove -documentation 'something'
- save
- go to /endpoints
- changes not displayed

### Expected behavior

```console
changes reflected in admin site
```

### Actual behavior

```console
no changes reflected
old settings are still displayed in admin site
```

**Comment by adamdriscoll** [comment]
I can reproduce this but only for removing the docs. If I change something like url or method it works.
