### ISSUE TITLE
Swagger crashes

### ISSUE THREAD

**Issue by JessePeden** [ironmansoftware/powershell-universal#3877]
### Version

5.0.9

### Severity

Medium

### Environment

msi

### Steps to Reproduce

Some of the APIs are causing Swagger to hang and eventually completely crash.  It seems to be spread out through multiple areas. 
 To see it in action, one of the most prevalent is with the Jobs category.  Simply expanding certain APIs to execute/test with causes the interface to hang and eventually crash. See the included screenshots for examples of working/not-working.  Being authenticated in Swagger makes no difference.

### Expected behavior

```console
Swagger should work without issues
```

### Actual behavior

```console
Swagger hangs and crashes.
```

### Screenshots/Animations

![2024-10-07_13-57-47](https://github.com/user-attachments/assets/b58fa937-a1ee-4b13-9167-adbcc8cb1eef)
![2024-10-07_13-57-58](https://github.com/user-attachments/assets/b93e4311-c28c-45ca-a36f-4c58db03cd7d)

**Comment by adamdriscoll** [comment]
Had to implement some work arounds due to this: https://github.com/swagger-api/swagger-ui/issues/6787

I still think we can improve the performance a bit, but it no longer crashes.
