### ISSUE TITLE
Global Datadog IIS Tracer kills PSU

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3881]
### Version

5.0.10

### Severity

Critical

### Environment

Nested IIS

### Steps to Reproduce

- install datadog
- install datadog trace
- Log in

![image](https://github.com/user-attachments/assets/60f20552-4a96-4e06-8c43-dd04381e84c4)

datadog Doc: https://docs.datadoghq.com/tracing/trace_collection/automatic_instrumentation/dd_libraries/dotnet-framework/?tab=windows

/WAS Environment settings
```
DD_LOGS_INJECTION=true
DD_RUNTIME_METRICS_ENABLED=true
DD_TRACE_DISABLED_ADONET_COMMAND_TYPES=CachingCommand
DD_TRACE_DEBUG=1
DD_TRACE_LOG_DIRECTORY=D:\DD_TRACER_LOGS
DD_TRACE_LOGFILE_RETENTION_DAYS=3
DD_PROFILING_ENABLED=true
COR_ENABLE_PROFILING=1
COR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
CORECLR_ENABLE_PROFILING=1
CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
```

/W3SVC Environment settings
```
DD_LOGS_INJECTION=true
DD_RUNTIME_METRICS_ENABLED=true
COR_ENABLE_PROFILING=1
COR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
CORECLR_ENABLE_PROFILING=1
CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
```

### Expected behavior

```console
200
```

### Actual behavior

```console
Could not load type 'Datadog.Trace.ClrProfiler.AutoInstrumentation.AspNetCore.UserEvents.AuthenticationHttpContextExtensionsIntegration' from assembly 'Datadog.Trace, Version=3.3.1.0, Culture=neutral, PublicKeyToken=def86d061d0d2eeb'.
```

**Comment by adamdriscoll** [comment]
I'm happy to take a quick peak at this but it seems like a Datadog problem. I found a similar issue in their repo: https://github.com/DataDog/dd-trace-dotnet/issues/429

**Comment by Omzig** [comment]
Created a bug here:
- https://github.com/DataDog/dd-trace-dotnet/issues/6135

**Comment by kevingosse** [comment]
The issue was caused by a custom AssemblyLoadContext injected by `System.Management.Automation`. We have a pending fix: https://github.com/DataDog/dd-trace-dotnet/pull/6148

**Comment by adamdriscoll** [comment]
@kevingosse Thanks you! I'll close this issue on our repo. @Omzig - Looks like a fix is coming and a workaround is mentioned on the DD repo.

**Comment by Omzig** [comment]
> Hello,
 
> Thank you for your patience! We have received an update from our engineering team:
 
> To exclude the exclude the problematic processes from being instrumented, you can detach a CLR Profiler as it can be scoped by process name:
> - Excluding processes: DD_PROFILER_EXCLUDE_PROCESSES=app1.exe;app2.exe
> - Including processes: DD_PROFILER_PROCESSES=w3wp.exe
 
> For example you could use:
> •	DD_PROFILER_EXCLUDE_PROCESSES=Universal.Server.exe
 
> Additionally our team has let us know that there is a pending fix for a similar issue reported on Github, and this fix will be shipped with the next release, although I do not have the exact timeline for this release it should be coming soon.
 
> If you still encounter any issues after setting the DD_PROFILER_EXCLUDE_PROCESSES variable, please let us know!
 
> Best,
> Jonathan G. | Technical Support Engineer | Datadog
- https://github.com/DataDog/dd-trace-dotnet/issues/6135#issuecomment-2407278162

We were able to bypass the datadog apm via a environment variable registry entry, i cannot find the datadog doc on it:

![image](https://github.com/user-attachments/assets/e612a2d1-d697-4c2a-8c42-074c468e76c1)
