### ISSUE TITLE
5.0.10 - In multi-node environment, schedules are being overwritten by nodes

### ISSUE THREAD

**Issue by bt-ndollimount** [ironmansoftware/powershell-universal#3885]
### Version

5.0.9

### Severity

High

### Environment

msi

### Steps to Reproduce

When I make a change to a schedule on one node, Git will sync and then there is another update after from one of the other nodes reverting the change. This eventually causes a loop of each node overwriting the schedules.ps1 file back and forth.

### Expected behavior

```console
The nodes should be importing updated schedules.ps1 into memory.
```

### Actual behavior

```console
The node is assuming its current schedule (old) is correct and overwriting the updated schedules.ps1 with its currently out of date schedules.
```

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/93adbd53-569a-40f9-9262-c1b1542f3443)
![image](https://github.com/user-attachments/assets/b47e2d43-18eb-45b0-aa76-9469a80f65a2)

**Comment by bt-ndollimount** [comment]
Related: [https://github.com/ironmansoftware/powershell-universal/issues/3847](https://github.com/ironmansoftware/powershell-universal/issues/3847)

**Comment by bt-ndollimount** [comment]
This time it's not parameters, it's the schedule values.

**Comment by bt-ndollimount** [comment]
I wanted to add a note to speak towards the severity of this bug. Any change I make to schedules causes this issue to engage where two nodes will update schedules.ps1 back and forth. In order to make any change, I have to shut down the services, make the change, then turn on the services so they pick up the new changes on startup.

**Comment by bt-ndollimount** [comment]
@adamdriscoll This might actually be an issue with the nodes not loading changes from any of the scripts. I made changes to a script in VS Code and pushed it via Git. After doing a sync in PSU, I can see the changes if I navigate to Settings > Files but if I open the script from the Scripts section, it still shows the original comment from when I created the empty script.

**Comment by adamdriscoll** [comment]
I wonder if this is the same problem as #3879. I'm looking into it. 

EDIT: I can reproduce this by creating one time schedules. It re-writes the schedules.ps1 file without changes. This causes git to mark it as changed. Then git sync will push the change to the remote. In a multi-node scenario, this causes the ping pong of changes back and forth. 

EDIT2: I've been able to reproduce this in a couple different ways as well. The good news is I see the root cause for this problem.
