### ISSUE TITLE
5.0.10 - Initial Git Setup does not work if the local Repository has already files in it

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#3889]
### Version

5.0.9

### Severity

Medium

### Environment

msi

### Steps to Reproduce

When you try to configure Git after you have already content in the Repository, the Init doesn't work.
Even if the Repo on Github is empty and you only have a README.md, the sync will fail with the following error:
![image](https://github.com/user-attachments/assets/24bf3245-3c1c-4008-90d9-d18f64d7b996)

This is an issue that I remember was already present in a past version... Somehow the issue is here again.
Probably if the local Repository is empty it will work. I haven't tried it though...

### Expected behavior

```console
The Initial Git Sync / Commit should work no matter if the local Repository has already Files in it or not.
```

### Actual behavior

```console
The Git sync process stops because it want's an empty local Repository.
```

**Comment by adamdriscoll** [comment]
This is expected because the remote is not bare. You need to ensure that when you create the remote it is a bare repository without a readme or any branches. 

The error message is different because we now check for this condition and output the above.

**Comment by donlent** [comment]
Thanks a lot @adamdriscoll for the quick response as always.
Indeed I tried this as well but it doesn't work either. I get this error message
![image](https://github.com/user-attachments/assets/dbe146d7-e602-4424-ab32-485ebf3dbb9a)
What am I doing wrong?

For your reference here's also a screenshot about the situation on github:
![image](https://github.com/user-attachments/assets/33f32e09-b744-4ceb-9de2-b8ff8085f0cc)
