### ISSUE TITLE
Logout goes no where

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3892]
### Version

5.0.10

### Severity

Low

### Environment

Nested IIS

### Steps to Reproduce

log in to psu
log out

### Expected behavior

```console
200
```

### Actual behavior

```console
This page isn’t working
If the problem continues, contact the site owner.
HTTP ERROR 401
```

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/027bc0f6-4148-4ddd-81e3-61dd9e2466c3)

**Comment by adamdriscoll** [comment]
Looks good in 5.2.0. I tried with both forms and windows auth in a nested IIS site.
