### ISSUE TITLE
MuiTooltip element styling issues in Theme hashtable / CSS

### ISSUE THREAD

**Issue by ad-85** [ironmansoftware/powershell-universal#3899]
### Version

4.2.21

### Severity

Visual

### Environment

msi

### Steps to Reproduce

There do not seem to be any theme overrides available for the MuiTooltip elements used since PSU 4.x which replaced the previous REACT elements. While `-Sx` is available, the different options (or none) used by the `-Type` parameter all appear to use the same Mui classes.

### Expected behavior

```console
Each tooltip type should be able to be overridden and set in the theme or via CSS, which does not appear to be possible currently outside of using New-UDStyle, which is not ideal for App-wide settings.
```

### Actual behavior

```console
MuiTooltip-tooltip is the CSS class used for all types, therefore overriding one overrides all of them.
```

### Additional Environment data

OS: Windows Server 2019 (VM)

**Comment by adamdriscoll** [comment]
I added a class name for the types. It will be MuiTooltip-tooltip-{type}
