### ISSUE TITLE
in the swagger api doc, please add contact

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3900]
### Summary of the new feature / enhancement

there are more fields in the swagger api doc, contact would be very helpful to us:

https://github.com/OAI/OpenAPI-Specification/blob/main/versions/2.0.md#info-object

### Proposed technical implementation details (optional)

Add more fields in the /admin/apis/docs edit properties icon in an endpoint documentation item.

**Comment by adamdriscoll** [comment]
I've added contact, license, terms of service and version
