### ISSUE TITLE
5.0.10 - Apps - 'Sync-UDElement -Broadcast' breaks existing sessions' dynamic updates

### ISSUE THREAD

**Issue by bt-ndollimount** [ironmansoftware/powershell-universal#3903]
### Version

5.0.10

### Severity

High

### Environment

msi

### Steps to Reproduce

We have a dashboard for reviewing community posts. We're using the Sync-UDElement with the -Broadcast switch to update the other sessions that are connected. This appears to break for existing sessions when someone new loads the dashboard or refreshes. The last loaded/refreshed dashboard will work but the local updates break on all the other sessions. You'll see the section blink when the item is updated but the update doesn't show. Oddly enough, existing sessions can make changes; those changes won't show locally but the last loaded/refreshed session will receive the changes and update.

### Expected behavior

```console
Broadcasted element sync should update both local and other sessions.
```

### Actual behavior

```console
When a new session is created, local updates on existing session breaks.
```

### Screenshots/Animations

@adamdriscoll I can send you a screen recording of the behavior but I can't post it here as it contains customer names.

**Comment by adamdriscoll** [comment]
I'm going to need an example of this. I tried with some basic apps but not noticing anything.

**Comment by bt-ndollimount** [comment]
@adamdriscoll  Do you want to set up a call to have a look at?

**Comment by adamdriscoll** [comment]
Sure thing. It will have to next week, but I can send over an invite.

**Comment by bt-ndollimount** [comment]
@adamdriscoll Checking in to see if you're still available this week to have a call to see this in action.

**Comment by adamdriscoll** [comment]
Updated via support case.
