### ISSUE TITLE
Variable for the page under an App

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#3906]
### Summary of the new feature / enhancement

There is a variable for DashboardName under Apps, but there isnt one for the PageName under the app.
https://docs.powershelluniversal.com/v4-beta/platform/variables#apps

It would be nice to have a similar hardcoded variable, so that we could query the PageName

**Comment by adamdriscoll** [comment]
You can use $UDPage to get this. I added it to the docs. 

https://docs.powershelluniversal.com/platform/variables#apps

You can also view all variables live in the live docs: http://localhost:5000/apps/docs/Variables
