### ISSUE TITLE
5.0.11 - Execution time wrong on running jobs

### ISSUE THREAD

**Issue by bt-ndollimount** [ironmansoftware/powershell-universal#3915]
### Version

5.0.11

### Severity

Low

### Environment

msi

### Steps to Reproduce

After updating to 5.0.11 that has the fix for the various sections having the incorrect time (those are fixed, thank!), now I see that currently running jobs are displaying the wrong date/time until they've completed. This is affect the returned value when retrieving the time details using Get-PSUJob as well.

### Expected behavior

```console
Currently running jobs should display the proper date/time.
```

### Actual behavior

```console
Currently running jobs have a date of January 01, 0001 with different times.
```

### Additional Environment data

Once the job has completed, the execution time is then set to the time the job completed.

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/7e9b6df1-dbcc-4959-9389-048c0cad0c50)
![image](https://github.com/user-attachments/assets/b765939f-229b-489d-b0cc-405e9b42227e)

**Comment by adamdriscoll** [comment]
I've got a fix for the displayed time. That said, for Get-PSUJob, there are actually 3 times to be aware of: 

- CreatedTime - When the job was created but is not yet running. Usually, same as start time. 
- StartTime - When the job started running
- EndTime - When the job finished running.

**Comment by bt-ndollimount** [comment]
@adamdriscoll This still appears to be an issue in 5.0.12.

**Comment by bt-ndollimount** [comment]
@adamdriscoll This is still an issue in 5.0.13.
![image](https://github.com/user-attachments/assets/a6ed07d7-1eac-408d-8308-0da2d7fef952)
