### ISSUE TITLE
PSU v5 Script Overwriting and Incorrect Script Loading After Service Restart

### ISSUE THREAD

**Issue by RubenT91** [ironmansoftware/powershell-universal#3919]
### Version

5.0.10

### Severity

High

### Environment

msi

### Steps to Reproduce

Organize scripts in folders with independent naming for scripts and paths (e.g., Technology/Function/Main.ps1).
Use New-PSUScript to create scripts, referencing different file names and paths:

New-PSUScript -Name "User-MailboxInfo" -Description "Retrieve user mailbox info" -Path "Exchange\User-MailboxInfo\Main.ps1" -Environment "Windows PowerShell 5.1"

Restart the PSU service.
Observe that PSU either:
Overwrites the script content of User-MailboxInfo.ps1 with the content of Main.ps1.
Fails to correctly load scripts, reverting to file names matching folder paths.

### Expected behavior

```console
Scripts should load correctly even when script names differ from folder structure (as in PSU v4.X). There should be no overwriting of scripts or changes to script behavior after PSU service restarts.
```

### Actual behavior

```console
Scripts are overwritten with content from other scripts (e.g., User-MailboxInfo.ps1 is overwritten by Main.ps1).
Scripts fail to load as expected after a PSU service restart, only loading scripts where file names match the folder structure.
Temporary fixes (e.g., renaming scripts) resolve the issue until PSU is restarted, after which the issue reoccurs.
```

### Additional Environment data

Operating System: Windows Server 2022
Dashboard Framework (if applicable): N/A
PowerShell Version: Windows PowerShell 5.1
PSU Setup: MSI, single node

**Comment by adamdriscoll** [comment]
Just a couple updates to this: 

- Customer has the same script name but different paths to scripts. This breaks scheduling. 
- Renaming the scripts to be unique causes other issues (listed above)

This all used to work on v4. It's likely it was by chance, but the file\path handling is not behaving correctly 

Support Case: 9551
