### ISSUE TITLE
Strangess with Secret Variables.

### ISSUE THREAD

**Issue by emoeckel** [ironmansoftware/powershell-universal#3920]
### Version

5.0.11

### Severity

High

### Environment

msi

### Steps to Reproduce

I am not exactly sure. Either editing the secret variable, or changing locations database etc.... Then trying to retrieve/use it in an endpoint script. Works in a script though.

### Expected behavior

```console
Just works
```

### Actual behavior

```console
Trying to retrieve a secret variable in an endpoint script will result in a Null value basically. But it works in a script.
```

### Additional Environment data

I am sorry I don't have more details for this one. I ended up having to recreate the variable to make it work. This is the second time I am having to recreate this secret variable. So there is just a general instability with it that I just can't explain.
If you need more details, due to the nature of this one, I will have to open a ticket within the customer support portal. That is fine, and I can do that. Just let me know. Thanks!

**Comment by adamdriscoll** [comment]
Likely, partially related to #3918. That said, I'll do some additional testing on this with the various resources using secrets.
