### ISSUE TITLE
5.0.12 - Setting a schedule to run on a computer group throws an error

### ISSUE THREAD

**Issue by nickdollimount** [ironmansoftware/powershell-universal#3927]
### Version

5.0.11

### Severity

High

### Environment

msi

### Steps to Reproduce

When configuring a schedule to run on a computer group, the following error is thrown:
`object reference not set to an instance of an object`

The schedules.ps1 file is not updated with the computer group, however opening the properties of the schedule again will show that it's set.

Setting it to a specific node or clearing it saves without issue.

### Expected behavior

```console
The schedule should be saved with the computer group selected.
```

### Actual behavior

```console
An error is thrown and the schedules.ps1 is not updated.
```

### Screenshots/Animations

https://github.com/user-attachments/assets/6f3d1251-5469-41fd-a75a-94fcef5a2638

**Comment by adamdriscoll** [comment]
The space in the computer group name is causing this. This will be resolved in 5.0.13.
