### ISSUE TITLE
5.0.12 - Apps - Show-UDModal throws 2 errors

### ISSUE THREAD

**Issue by bt-ndollimount** [ironmansoftware/powershell-universal#3930]
### Version

5.0.12

### Severity

Low

### Environment

msi

### Steps to Reproduce

When showing a modal with Show-UDModal, two separate errors are displayed. Functionality doesn't appear to break, but the errors are displayed anyway.

Error 1) `The property 'ScriptBlock' cannot be found on this object. Verify that the property exists and can be set.`
Error 2) `Exception calling "Register" with "2" argument(s): "Object reference not set to an instance of an object."`

### Expected behavior

```console
No errors should be displayed.
```

### Actual behavior

```console
2 separate errors are displayed.
```

### Additional Environment data

PSU 5.0.12
PostgreSQL 17
Windows Server 2022 Standard

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/32e87702-8b8d-46fe-8d62-0755eeffd154)

**Comment by adamdriscoll** [comment]
Same root cause as #3928
