### ISSUE TITLE
Get-PSUDashboard causes gRPC error

### ISSUE THREAD

**Issue by JCrabtree911** [ironmansoftware/powershell-universal#3932]
### Version

5.0.12

### Severity

Low

### Environment

msi

### Steps to Reproduce

A call to

Get-PSUDashboard

results in a gRPC error

An error occurred: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: The SSL connection could not be established, see inner exception. AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.", DebugException="System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.")

### Expected behavior

```console
Get-PSUDashboard

# Expected to return a list of Dashboards
```

### Actual behavior

```console
A red error pop will briefly appear with the following text:

An error occurred: Status(StatusCode="Internal", Detail="Error starting gRPC call. HttpRequestException: The SSL connection could not be established, see inner exception. AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.", DebugException="System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.")
```

### Additional Environment data

Windows Server 2019 Datacenter 1809.

**Comment by adamdriscoll** [comment]
This is due to the certificate not being trusted by the cmdlets. You can try this appsetting: https://docs.powershelluniversal.com/config/module#trust-https-certificate

You could also try -TrustCertificate on the cmdlet.

**Comment by JCrabtree911** [comment]
It's valid cert signed by a CA whose cert is in the local machine's trusted root certificate store.

**Comment by adamdriscoll** [comment]
Interesting. I added some more logging into the certificate validation. You should be able to use the -Verbose parameter on any cmdlets to see a bunch more information about the connection in 5.0.13.

**Comment by adamdriscoll** [comment]
I added -Integrated back to the PSU cmdlets. This will avoid the certificate all together and utilize the backchannel for cmdlets like this.
