### ISSUE TITLE
Fails to install as Server or Desktop

### ISSUE THREAD

**Issue by StevenTCramer** [ironmansoftware/powershell-universal#3935]
### Version

5.0.12

### Severity

Critical

### Environment

msi

### Steps to Reproduce

Run the installer.

### Expected behavior

```console
I would expect it to install.
```

### Actual behavior

```console
See screen shots
```

### Additional Environment data

Windows 11

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/d6839ddf-5e6a-463e-a0ce-8a633fe446c9)
![image](https://github.com/user-attachments/assets/00839388-da5c-4cb8-9f42-fb325d94abbd)
[systemLog20241020.txt](https://github.com/user-attachments/files/17448934/systemLog20241020.txt)

**Comment by adamdriscoll** [comment]
This seems like there may be a v4 LiteDB database still in place on this machine. Can you verify if you have installed previous versions of PSU on this machine?

**Comment by adamdriscoll** [comment]
Closing as I haven't heard back. I can reopen if you can provide some more detail.

**Comment by StevenTCramer** [comment]
Yes I have installed previous versions.

But I have attempted to uninstall PSU and reinstall a few times to no avail.  What do I need to do?

**Comment by StevenTCramer** [comment]
@adamdriscoll I updated comment above.

**Comment by adamdriscoll** [comment]
@StevenTCramer - Please delete or rename (if you want to back up any previous install's data) the %ProgramData%\PowerShellUniversal and %ProgramData%\UniversalAutomation folders. They contain old configuration data that is likely causing the new install to fail.

**Comment by StevenTCramer** [comment]
@adamdriscoll Thanks that worked  :)
