### ISSUE TITLE
Adding a Param() statement in an endpoint overrides route parameters

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#3938]
### Version

5.0.12

### Severity

Low

### Environment

msi

### Steps to Reproduce

Really just a documentation issue.

If you have a param() statement in an endpoint, you need to include the route parameters in the param() statement or they don't get passed.

There isn't an example that uses route parameters and a param() statement in the docs.

For instance:
Route: /api/:id
Endpoint: 
Param($data)
[pscustomobject]@{id=$id;data=$data}

In this case, you won't get the id parameter passed in (because it's not in the param() block).  Without the param() block, it does get passed in.

### Expected behavior

```console
Either pass ID in (as you would when there's no param statement, or update the docs to make it more clear.
```

### Actual behavior

```console
ID is not passed in.
```

**Comment by adamdriscoll** [comment]
I've updated the param block documentation with this info.
