### ISSUE TITLE
High CPU low memory for unknown reasons

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3963]
### Version

5.0.13

### Severity

High

### Environment

Nested IIS

### Steps to Reproduce

using psu with 3 api's and one empty app
no users hitting the server other than 1 person using the admin site

### Expected behavior

```console
1% cpu
```

### Actual behavior

```console
99% cpu
```

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/5920c979-b133-4d41-9362-8b0b68348340)

**Comment by Omzig** [comment]
@adamdriscoll, i have sent you the logs via email, got debug turned on and man, the logs just roll.

**Comment by adamdriscoll** [comment]
@Omzig - Can you grab a few memory dumps are well (10\15 seconds apart)? It will show exactly where the processing is happening.

**Comment by Omzig** [comment]
> Can you grab a few memory dumps are well (10\15 seconds apart)? It will show exactly where the processing is happening.

1gb each :(

**Comment by Omzig** [comment]
this is fun
![image](https://github.com/user-attachments/assets/777d25f7-411a-40c2-80de-22fd86ad5dc3)

**Comment by Omzig** [comment]
Current hypothesis:
- found a reference to an ActiveDirectory module

Possible Solution:
- remove ActiveDirectory from the internal environment
