### ISSUE TITLE
Internal API Access cmdlet

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3969]
### Summary of the new feature / enhancement

As a developer, I want to be able to call the api's from inside an app without explicit authentication so that i can quickly get to my resources on box. 

### Proposed technical implementation details (optional)

create new cmdlet like `Invoke-PsuRestMethod -route "/custom/api/v1/bob"`

Then i don't have to /login or /auth, and then i don't have sooooo much in order to get to internal data.

Think in the same way that i have access to the 'Automation' jobs and scripts.

**Comment by adamdriscoll** [comment]
This actually exists and this is a bug. Somewhere along the line it got renamed and it's exported properly. The cmdlet is Invoke-PSUEndpoint.

**Comment by Omzig** [comment]
i am soooooooooooooo testing this

**Comment by Omzig** [comment]
FTW: Invoke-PSUEndpoint
