### ISSUE TITLE
/login page only displays in dark theme

### ISSUE THREAD

**Issue by diegovdw** [ironmansoftware/powershell-universal#3978]
### Version

5.0.13

### Severity

Low

### Environment

msi

### Steps to Reproduce

I wanted to try to customize the login page the old way like New-PSULoginPage, but this has been moved to branding whith less options looks like (ex: https://forums.ironmansoftware.com/t/login-page-with-custom-background-image-and-custom-css/7493)

Currently, when using the login page for local login (/login), it will only show in dark theme.

The CSS that is currently being loaded: assets/_content/AntDesign/css/ant-design-blazor.dark.css

### Expected behavior

```console
Currently, it will only show the dark theme:
CSS file loaded currently:
assets/_content/AntDesign/css/ant-design-blazor.dark.css
```

### Actual behavior

```console
An option to choose which theme (through the branding page maybe)
Counterpart CSS file that should load (light theme)
assets/_content/AntDesign/css/ant-design-blazor.css
```

**Comment by eizedev** [comment]
thanks @diegovdw for opening the feature request. I have forgotten it when i posted the guide that you linked in the forum. i already had the problem.

@adamdriscoll How did you solve it in 5.2? Is this included in the documentation?
