### ISSUE TITLE
Assign claims to roles

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#398]
It should be possible to just assign a claim (like group membership) to a role. Right now, you need to write a script to check those claims. 

This should include some UI that displays available claims.

**Comment by Viajaz** [comment]
Like some sort of mapping Hashtable that forms part of the Role declaration or something? I'm wondering what such an implementation would look like.

**Comment by adamdriscoll** [comment]
I'm imaging a drop down list of claims available to the user. No need to write any script. Mostly just associate a certain claim with a role. Like if you have group xyz, then you have role x.

**Comment by adamdriscoll** [comment]
https://docs.powershelluniversal.com/config/security#role-to-claim-mapping
