### ISSUE TITLE
Get-PSUEventHubConnection  should have -Active

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3981]
### Summary of the new feature / enhancement

As a Developer, I want to say only the active connections should be given to me so that i can write clean code.

**Comment by parzog** [comment]
@adamdriscoll How do I use?
![image](https://github.com/user-attachments/assets/de6bf759-71de-49e7-825c-231cd8c4fcea)
![image](https://github.com/user-attachments/assets/797eb4be-da65-43c6-8b41-44e8b8bf03d4)
[Documentation](https://github.com/ironmansoftware/universal-docs/blob/v5/cmdlets/Get-PSUEventHubConnection.txt) hasn't been updated either.
