### ISSUE TITLE
Server-side table processing - no way to know what columns are included in search

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#3982]
### Summary of the new feature / enhancement

As a developer, I want to use the -IncludeInSearch parameter in a table and use server-side processing of rows.

The $EventData object doesn't include a list of columns included in search, so you have to provide them some other way

### Proposed technical implementation details (optional)

Add a list of "includeInSearch" columns as a property of $eventData for server-side processing

**Comment by MikeShepard** [comment]
I'm guessing that the selected rows aren't getting handled in this scenario either

**Comment by adamdriscoll** [comment]
I've added Columns and SelectedRowIds properties to the $EventData for -LoadData.
