### ISSUE TITLE
Event Hub Client Logs do not reflect write-*

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#3983]
### Version

4.4.1

### Severity

Low

### Environment

msi

### Steps to Reproduce

setup an event hub
- connect some event hub clients
- send write-host "something" and write-warning "something else" and write-error "Yo, i am an error"

### Expected behavior

```console
write-host, warning, error should show up in the eventLogClient20241028.txt logs
```

### Actual behavior

```console
write-host "Did not show up"
write-warning "did not show up at all"
only write-error "i am an error" -erroraction stop will be logged as a [WRN]
```

**Comment by adamdriscoll** [comment]
This has also been included in v5.
