### ISSUE TITLE
New-UDMarkdown inside New-UDPaper doesn't render correctly

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#3994]
### Version

5.0.13

### Severity

Low

### Environment

IIS

### Steps to Reproduce

If I have a Markdown inside a Paper, it messes it up.  Here's the same markdown inside and outside a paper:

New-UDApp -Title 'PowerShell Universal' -content {
 $m=@'
# Hello

## world
- a
- b
-c
'@
   New-UDPaper -Elevation 7 -Children {
       New-UDMarkdown -markdown $m
   }
   New-UDMarkdown -markdown $m
}

![image](https://github.com/user-attachments/assets/586520ee-494d-4a4b-aef9-5649546bf61c)

Apparently, you can fix this with adding  -style @{display='block'} to the New-UDPaper...

### Expected behavior

```console
Markdown is rendered correctly inside New-UDPaper
```

### Actual behavior

```console
Markdown is mangled inside New-UDPaper
```

### Additional Environment data

same behavior in msi

This was mentioned here: https://forums.ironmansoftware.com/t/new-udmarkdown-not-rendering-as-expected/9586

**Comment by adamdriscoll** [comment]
You can change this by adjusting the display type. I'll have to look into whether I should make this change directly in the control since I'm not entirely sure the effect it will have across peopel's dashboards. 

```
   New-UDPaper -Elevation 7 -Children {
       New-UDMarkdown -markdown $m
   } -Style @{
    display = 'block'
   }
```

**Comment by MikeShepard** [comment]
@Omzig gave me the workaround after I got the issue entered.  Might just be something to add to the doc on New-UDMarkdown?

**Comment by adamdriscoll** [comment]
Sure. I'll get that updated

**Comment by Omzig** [comment]
> Sure. I'll get that updated

can we add it to the live doc ? as a cmdlet example?
