### ISSUE TITLE
PowerShell Universal Logging Target Not Writing Logs for API Feature in PSU 4.4.1

### ISSUE THREAD

**Issue by RubenT91** [ironmansoftware/powershell-universal#3998]
### Version

4.4.1

### Severity

Medium

### Environment

msi

### Steps to Reproduce

Set up a logging target for PSU using logging.ps1 as follows:
New-PSULoggingTarget -Type 'File' -Scope 'User' -Feature 'API' -Properties @{
    Path = 'C:\Temp\Log.txt'
    RetentionPeriod = 5
}

Attempt to log API-related actions using Write-PSULog within an API endpoint script (e.g., a simple get-helloworld.ps1 API endpoint).

Observe that the log file specified in the target is not created when the Feature = 'API' parameter is used.

Note: If Feature is omitted, logging works as expected, and log files are created.

### Expected behavior

```console
Logs should be written to the specified file for API actions when the Feature = 'API' parameter is defined in New-PSULoggingTarget.
```

### Actual behavior

```console
When using Feature = 'API', the specified log file is not created, and no API-specific log entries are written. The logging target works for broader scopes (like System or User) without specifying a feature.
```

### Additional Environment data

Operating System: Windows Server 2019
Dashboard Framework: Not applicable
Logging Configuration: Defined in logging.ps1
Reproduced In: Multiple environments across different PSU installations

**Comment by adamdriscoll** [comment]
@RubenT91 - I can reproduce this. It looks like scope is case sensitive. Have the user try "Api" rather than "API". I'll get a fix in for it.

**Comment by floc011** [comment]
Hi @adamdriscoll. Ticket opener here.
Changing from "API" to "Api" does also work for me. The corresponding files are created now.
Just one additional thing, I still can't see my debug level calls.  
I already tried setting SystemLogLevel to Debug. Afterward, I see DBG entries at the beginning of the Systemlog, but my Write-PSULog -Level 'Debug' call still shows nowhere. Any idea on that?

```
$RequestLogMessage = 'API Log Test'  
$EndpointID = 1  
Write-PSULog -Message $RequestLogMessage -Level 'Debug' -Feature 'Api' -Resource $EndpointID  
Write-PSULog -Message $RequestLogMessage -Level 'Information' -Feature 'Api' -Resource $EndpointID  
Write-PSULog -Message $RequestLogMessage -Level 'Warning' -Feature 'Api' -Resource $EndpointID  
Write-PSULog -Message $RequestLogMessage -Level 'Error' -Feature 'Api' -Resource $EndpointID
```
  
System log:

> 2024-10-31 10:34:49.085 +01:00 [INF] GET /helloworld ::ffff:127.0.0.1
> 2024-10-31 10:34:49.537 +01:00 [INF] API Log Test
> 2024-10-31 10:34:49.542 +01:00 [WRN] API Log Test
> 2024-10-31 10:34:49.545 +01:00 [ERR] API Log Test
> 2024-10-31 10:34:49.569 +01:00 [INF] Status: 200 Content-Type: text/plain Length: 31

Api Logging Target:

> [10:34:49 INF][Api][1] GET /helloworld ::ffff:127.0.0.1
> [10:34:49 INF][Api][1] API Log Test
> [10:34:49 WRN][Api][1] API Log Test
> [10:34:49 ERR][Api][1] API Log Test
> [10:34:49 INF][Api][1] Status: 200 Content-Type: text/plain Length: 31

**Comment by adamdriscoll** [comment]
@floc011 Can you try setting the log level of the target? It defaults to Information, which won't show debug. 

```
New-PSULoggingTarget -Type 'File' -Scope 'User' -Feature 'API' -Properties @{
Path = 'C:\Temp\Log.txt'
RetentionPeriod = 5
} -Level 'Debug'
```

**Comment by floc011** [comment]
@adamdriscoll Unfortunately the same result.  
Gave it a Second try using an App instead of an Api to rule out it might be Feature related but same there.  
Also tried setting `$Env:SystemLogLevel = 'Debug'` but apart from a few unrelated DBG entries at the beginning of the system log no change.

System log:

> 2024-10-31 14:35:19.714 +01:00 [INF] GET /helloworld ::ffff:127.0.0.1
> 2024-10-31 14:35:20.145 +01:00 [INF] API Log Test
> 2024-10-31 14:35:20.148 +01:00 [WRN] API Log Test
> 2024-10-31 14:35:20.151 +01:00 [ERR] API Log Test
> 2024-10-31 14:35:20.174 +01:00 [INF] Status: 200 Content-Type: text/plain Length: 31

API Log:

> [14:35:19 INF][Api][1] GET /helloworld ::ffff:127.0.0.1
> [14:35:20 INF][Api][1] API Log Test
> [14:35:20 WRN][Api][1] API Log Test
> [14:35:20 ERR][Api][1] API Log Test
> [14:35:20 INF][Api][1] Status: 200 Content-Type: text/plain Length: 31

App Log:  

> [14:55:13 INF][App][mde] Creating services.
> [14:55:13 INF][App][mde] api_sdms
> [14:55:13 INF][App][mde] api_tanium
> [14:55:13 INF][App][mde] PsuCore
> [14:55:13 INF][App][mde] PsuSdmsHelper
> [14:55:18 INF][App][mde] App Log Test
> [14:55:18 WRN][App][mde] App Log Test
> [14:55:18 ERR][App][mde] App Log Test
> [14:55:19 INF][App][mde] Starting scheduler.
> [14:55:19 INF][App][mde] Dashboard configuration complete.
