### ISSUE TITLE
UDDataGrid - Select and Unselect are not working as expected when changing pages.

### ISSUE THREAD

**Issue by gshykhov** [ironmansoftware/powershell-universal#3999]
### Version

5.0.13

### Severity

Medium

### Environment

msi

### Steps to Reproduce

Selection and Unselection in the UDDataGrid do not work as expected when pages change.
Here is the code to reproduce:
```
New-UDApp -Content { 
    $Rows = 1..100 | % {
        @{ Name = 'Adam'; Number = Get-Random}
    } 
    New-UDDataGrid -id test123 -LoadRows {  
    $Rows| Out-UDDataGridData -Context $EventData -TotalRows $Rows.Length
} -Columns @(
    New-UDDataGridColumn -Field name
    New-UDDataGridColumn -Field number
) -AutoHeight $true -Pagination -CheckboxSelection -CheckboxSelectionVisibleOnly -DisableRowSelectionOnClick

New-udbutton -Text "test" -OnClick {
    $val = Get-UDElement -Id test123
    show-udtoast $($val.selectedRows | out-String)
}

}

```

### Expected behavior

```console
Select and deselect are acting correctly.
```

### Actual behavior

```console
Select and deselect are not working well.
```

### Screenshots/Animations

![ud_app_issue_grid](https://github.com/user-attachments/assets/717a326e-d4f2-4467-8dd5-a02241a9e020)

**Comment by adamdriscoll** [comment]
Selection requires an ID specified. This was completely missing from the documentation and examples.

https://docs.powershelluniversal.com/apps/components/data-display/data-grid#selection

There is some more work to do cleaning up the UDDataGrid docs, but this is a good start. Tracking that here: https://github.com/ironmansoftware/powershell-universal/issues/4087
