### ISSUE TITLE
API Endpoints Return Error 404

### ISSUE THREAD

**Issue by ml4den** [ironmansoftware/powershell-universal#4]
#### Description

When I create an API endpoint according to the documentation, I get Error 404 at its address.

#### Additional Information

I am just starting out with PowerShell Universal. The only config I've done is to add some config for HTTPS support (using the snippet from the docs), which works fine. I can create a dashboard and that works fine, I'm only experiencing problems with endpoints. 

I've tried restarting the PowerShell Universal service, but it didn't help.

On the Powershell Universal GUI endpoint info everything seems in order and I get the run command as expected:
`Invoke-RestMethod https://myserver.domain.local/hello`

Code in GUI:
```
#It's all start with a single line of PowerShell code
"hello"
```

Code in `endpoints.ps1`:
```
New-PSUEndpoint -Url "/hello" -Endpoint {
#It's all start with a single line of PowerShell code
"hello"
}
```

#### Version Information

- Universal: 1.5.14
- Universal Hosting Method (IIS, Executable, docker etc): Executable, I think - installed using the MSI without a separate web server in front.
- PowerShell: 5.1.14393.3866 but 6.2.4 is also installed
- Operating System: Windows Server 2016 Version 1607 (OS Build 14393.4225)

**Comment by adamdriscoll** [comment]
Cannot reproduce on 3.7.7.
