### ISSUE TITLE
PowerShell filter keyword is not recognized

### ISSUE THREAD

**Issue by kp-bit** [ironmansoftware/powershell-universal#4001]
### Description of Issue

The filter keyword is no longer recognized in PSU v5, it was working fine in the beta but after upgrading it no longer works. We can get around it for now by using function instead as we only have v5 on a test server currently.

More information: https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions?view=powershell-7.4#filters

### Version

5.0.13

### Severity

Medium

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQLite

### Features

- [X] Licensed
- [X] Git Sync
- [X] VS Code Extension

### Additional Environment data

Using integrated PowerShell

### Screenshots/Animations

n/a

**Comment by adamdriscoll** [comment]
Are you just getting an error that the keyword isn't recognized? I tried this on the latest and it's working. 

![image](https://github.com/user-attachments/assets/901884e3-9137-468a-bf23-c097d2b74cd6)

```
filter Get-ErrorLog ([switch]$Message)
{
  if ($Message) { Out-Host -InputObject $_.Message }
  else { $_ }
}

Get-WinEvent -LogName System -MaxEvents 100 | Get-ErrorLog -Message
```

**Comment by kp-bit** [comment]
The specific filter that fails is this one (works fine when changed to function):

```
filter GetPageUrl {
    $pageUrl = "$_".ToLower() -ireplace $script:rootPathPattern, '' -ireplace '\\', '/' -ireplace ' ', '-' -ireplace '\.ps1|\.udpage\.ps1', ''
    if ($pageUrl -eq '') {
        $pageUrl = '/'
    }
    $pageUrl
}
```

The error looks like this:
![image](https://github.com/user-attachments/assets/99a9c3ae-eeb2-4f49-ab55-18bb1df35b23)

**Comment by adamdriscoll** [comment]
Where are you defining your function? If I define it in the functions tab, it works. 

![image](https://github.com/user-attachments/assets/5f65a0da-3b2b-443c-94ce-c5c533e45852)

If I define it in the main app code, it doesn't. 

![image](https://github.com/user-attachments/assets/13302a95-37c3-45aa-8fb7-c54cb15aded6)

I can fix that, but you should be able to work around by putting it in the function tab. It effectively is a module that is loaded into the app.

**Comment by kp-bit** [comment]
Got it - we write everything in VSCode and sync it to the server via Git, so the functions tab is not really available to us. It would be nice to have it supported, but for now we're alright with using a function instead.

**Comment by adamdriscoll** [comment]
Gotcha. I've updated the VS Code extension to include the functions file so you can access it and set that update as a filter.

**Comment by kp-bit** [comment]
Sounds good, we won't be able to utilize that though, as we don't connect directly to PSU with VSCode, everything is synced via Git/DevOps...

**Comment by adamdriscoll** [comment]
Oh, in that case, you can just create the PSM1 file yourself. If you have an app names app1, it will have an app1.ps1 in the main folder for the app. Just create a app1.psm1 and it will be automatically imported.

**Comment by kp-bit** [comment]
Ok, thanks, will try that!
