### ISSUE TITLE
Add heartbeat for Event Hub Client/Agent

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#4005]
### Summary of the new feature / enhancement

We should probably do some sort of heartbeat call down the event hub client because, if the server doesn't see it disconnecting, then we will run into other issues. The heartbeat could check to see if we still have a connection and set it to disconnected if not. We can just add it to the heartbeat job in the server.

- from https://github.com/ironmansoftware/powershell-universal/issues/4003#issuecomment-2450706947

**Comment by adamdriscoll** [comment]
I narrowed this down. It will be fixed in both 4.5.1 and 5.1.1. Heartbeat isn't necessary and we will have much better logging in the next versions. 

https://github.com/ironmansoftware/powershell-universal/issues/4126
