### ISSUE TITLE
/Portal redirects to /login instead of SAML integration

### ISSUE THREAD

**Issue by bt-ndollimount** [ironmansoftware/powershell-universal#4010]
### Description of Issue

When not already logged in, or if a session has timed out, the /Portal redirects to the /login page instead of initiating the SAML login. The main console and custom apps seem to work fine where they will instantly kick off the SAML login.

### Version

5.0.14

### Severity

Medium

### Hosting Method

Other

### Operating System

Linux

### Database

PostgreSQL

### Licensed

Yes

### Features

Git sync, 3 Windows nodes running jobs, 1 Linux node running only the web interface and app/portal.

### Additional Environment data

Amazon Linux, Windows Server 2022 Standard.

**Comment by parzog** [comment]
We are experiencing this as well on Server 2022 / IIS10

**Comment by JessePeden** [comment]
This has been driving me nuts.  I'll get busy doing something and come back to PSU only to be sitting at the /login page (asking me for local credentials) instead of it renewing the SAML auth session/cookie and keeping me on the Admin dashboard.
