### ISSUE TITLE
Some jobs showing 'Execution Time' of January 0001

### ISSUE THREAD

**Issue by bt-ndollimount** [ironmansoftware/powershell-universal#4016]
### Description of Issue

When viewing the Jobs list, some jobs are showing 'Execution Time' of January 0001 while others are showing properly.

### Version

5.0.14

### Severity

Low

### Hosting Method

Other

### Operating System

Linux

### Database

PostgreSQL

### Licensed

Yes

### Features

Git Sync

### Additional Environment data

Amazon Linux
PowerShell 7.4.6
PostgreSQL 17

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/85c39de8-c5ce-4891-8df0-c8333ea36f24)

**Comment by adamdriscoll** [comment]
The bug that won't quit.
