### ISSUE TITLE
 Incorrect Weekday Display for New-UDDatePicker with German Locale (de) in PSU 

### ISSUE THREAD

**Issue by RubenT91** [ironmansoftware/powershell-universal#4017]
### Description of Issue

When using the New-UDDatePicker component in PowerShell Universal with the -Locale 'de' (German) and -Format 'DD.MM.YYYY' parameters, the weekday labels are incorrect. The component starts the week on Sunday instead of Monday, misaligning with German conventions. Additionally, the weekday labels do not correctly match the calendar days, causing usability issues for German users.

### Version

5.0.14

### Severity

Critical

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQLite

### Licensed

No

### Additional Environment data

Expected Behavior:
The New-UDDatePicker should display weekdays in German, starting with Monday (M D M D F S S), accurately labeling each day according to the German locale.

Actual Behavior:

The calendar week begins with Sunday (S M D M D F S) instead of Monday.
The day labels do not correspond correctly to the calendar days, leading to misalignment and confusion.

**Comment by RubenT91** [comment]
New-UDApp -Title $Titel -Content {
    New-UDDatePicker -Id 'datepicker1' -Locale 'de' -Format 'DD.MM.YYYY'
    New-UDDatePicker -Id 'datepicker2' -Locale 'de' -Format 'DD.MM.YYYY' -Value '11-21-2024'
    New-UDButton -Text 'Set Value for datepicker1' -OnClick {
    Show-UDToast "Seting a Value for datepicker1" -Duration 5000
    Show-UDToast "-> Weekday label changed MDMDFSS -> SMDMDFS" -Duration 5000
    Set-UDElement -Id 'datepicker1' -Properties @{
    'Value' = '11-21-2024'
    } -Broadcast
    }
    }
    
    Explanation:
    The Value for datepicker1 is set either manually or via button
    The Value for datepicker2 is set via code.
    The effect is always the same: Every time a value is set the weekday label changes from MDMDFSS -> SMDMDFS.

**Comment by adamdriscoll** [comment]
@RubenT91 There was a bug in the date and time library used by this component. Updating it to the latest version fixed the issue. It will be included in v5.1.0
