### ISSUE TITLE
5.0.14 | Set-PSUVariable triggers an Auto-Deploy

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#4022]
### Description of Issue

Not sure if this is related to the other Variable bugs reporteted in this milestone...
https://github.com/ironmansoftware/powershell-universal/issues/4002
https://github.com/ironmansoftware/powershell-universal/issues/4007

However I upgraded from 5.0.10 to 5.0.14 last friday and since then, whenever I update a variable (which is a secret), it reloads everything.

Here's an example code (very basic but it is sufficient to understand / reproduce):
`Set-PSUVariable -ComputerName "https://mypsuinstance.local" -Variable $varToChange -Name $CredentialsName -Description $CredentialsDescription -InputObject $PSCredential`

This is a major problem because when this gets triggered, obviusly all subsequent code won't be executed...

Has something changed on how variables get stored in the background? This issue remembers me of version 4.x... but sometimes it was fixed or enhanced so that this won't happen anymore but now it does again... :-(

Thanks a lot for your help!

### Version

5.0.14

### Severity

High

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQL

### Licensed

Yes

**Comment by adamdriscoll** [comment]
This is unrelated to the display issue but I can reproduce this. Will be fixed in .15.
