### ISSUE TITLE
PSU health check shows 100% CPU usage and never goes down

### ISSUE THREAD

**Issue by JessePeden** [ironmansoftware/powershell-universal#4024]
### Description of Issue

PSU shows 100% CPU usage according to its health checks, but the usage is not 100% when looking on the host itself, and the button to re-run health checks seems to be broken, as clearing health checks and clicking re-run does nothing and the health checks remain blank until you restart the PSU service.

### Version

5.0.13

### Severity

Low

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQLite

### Licensed

Yes

### Features

Health Checks

**Comment by adamdriscoll** [comment]
The CPU issue might just be that the last time the health check ran the CPU was higher. Health checks are only running once per hour. I can't reproduce that myself. The run checks button is not working.

**Comment by JessePeden** [comment]
So, the theory is that it was high at the moment it ran but that because the button doesn't work there's no way to get a current reading to see if it's still high.  Nice.

**Comment by adamdriscoll** [comment]
Yeah. Exactly. Once I fixed the button, I was able to see the CPU value changing.
