### ISSUE TITLE
Service not installing, even as admin

### ISSUE THREAD

**Issue by yaba** [ironmansoftware/powershell-universal#4029]
### Description of Issue

I'm getting the following message, no matter if I leave it blank (Local System), or use my admin account, or any other account with admin privileges:

> Error 1923. Service 'PowerShell Universal' (PowerShellUniversal) could not be installed.  Verify that you have sufficient privileges to install system services.

Which, I do. Tested with different accounts, same result. 

### Version

5.0.14

### Severity

Low

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQLite

### Licensed

No

### Additional Environment data

Windows Server 2022 Standard 21H2
Build: 20348.2700

**Comment by adamdriscoll** [comment]
@yaba - It could be a configuration issue and not a permission issue. Can you check for event log errors and in the %ProgramData%]\PowerShellUniversal folder for logs? It should have some more info.

**Comment by yaba** [comment]
@adamdriscoll thanks, I'll close the issue, I've manually uninstalled everything and seems to be working now.

I have used the ZIP version in the past, probably got some file corrupted or something, after deleting everything it installed flawlessly.

**Comment by yaba** [comment]
@adamdriscoll thanks, I'll close the issue, I've manually uninstalled everything and seems to be working now.

I have used the ZIP version in the past, probably got some file corrupted or something, after deleting everything it installed flawlessly.
