### ISSUE TITLE
5.0.15 | Code Editor: Format Document does not work anymore

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#4033]
### Description of Issue

The "Format Document" Feature which uses the PSScriptAnalyzer as dependency stopped to work with the last 5.0.15 release.
Also tried to install the latest module version of PSSA but it didn't help...

### Version

5.0.15

### Severity

Quality-of-life

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQL

### Licensed

Yes

**Comment by adamdriscoll** [comment]
I can't reproduce this. That said, can you check the logs? It looks like we log when it fails to format. System logs need to be on debug.

**Comment by donlent** [comment]
Strange...
I've set "SystemLogLevel": "Debug" in appsettings.json, restarted the service. Then I went into an App and performed a "Format Document"... nothing happened, and also in the logs I can't see any DBG entry or so that points to an issue with PSScriptAnalyzer.

Am I missing something or is that the way you wanted me to check for the logs?

Btw. I also rebooted the server... just to be sure...

Thanks!

**Comment by adamdriscoll** [comment]
That should have at least printed some DBG statements. That said, maybe I'll just surface errors for the formatting in the UI so it's easier to see what is going on. Then, we can just have a message box that complains if something isn't right. 

EDIT: I also changed the log level from dbg to warning so it doesn't require any config.

**Comment by Omzig** [comment]
so i ran into an issue where mine wouldn't work, i had to use ps7 to install the module instead of 5.1 and then it started working, making sure -scope was set to all users.

**Comment by donlent** [comment]
> so i ran into an issue where mine wouldn't work, i had to use ps7 to install the module instead of 5.1 and then it started working, making sure -scope was set to all users.

Hi @Omzig 
Thanks a lot for your comment. Normally I install the modules via the PSU internal Module function. This should do it the right way and instead of being part of the system itself it's just part of the PSU ecosystem since it's stored under the repository.
In can certainly try your suggestion but I'd like to try the 5.0.16 release first with the WRN messages that should help to understand a little bit better what's going on... Hope I can do this tomorrow. Will post my results here soon.

**Comment by donlent** [comment]
hahah... sorry, I was just upgrading another customer dev instance so I thought it might be a good idea to try the latest nightly build... and here's the result when trying to "Format Document" :-)
![image](https://github.com/user-attachments/assets/77422e22-665b-44a3-bda0-e70aa6bd42eb)

@adamdriscoll so you can see that it seems to be a new general issue starting from 5.0.15...  two different customers, two different environments, but same issue... ;-)
Hope this helps, if not let me know and I'll be happy to provide you more information.

**Comment by adamdriscoll** [comment]
Thanks! that's helpful. It's not sending the text into the formatter correctly for some reason and just sending an empty value. I'll keep trying to reproduce this myself.

**Comment by adamdriscoll** [comment]
I'm still having a hard time reproducing this. I can reproduce this if I format a blank file. Can you give me a little more info? 

- Any particular editor causing this? Apps, scripts, endpoints? Or just all of them? 
- What browser are you using? 
- It consistently happens every time?

**Comment by donlent** [comment]
Hey Adam
Sure! Really sorry that it takes so much time trying to reproduce...
Here are my answers
- All editors
- MS Edge
- Yes, it's constant and happens every time.

Ps. I'll try with Google Chrome and see if it makes any difference... Coming back to you shortly...

EDIT

- It's not related to all editors! Apparently it's only related to the main Page of an App, when you click "Edit Code".
- If you edit "Pages" of the App then it works
- It is also related to Modules! For some reason when you Format a Module it "expands" the Manifest file and you risk to break your script like that!

So even if it doesn't seem to be a general issue where it is everywhere, in each code editor, there are some parts that are somehow not working reliable anymore:
- Apps Main Editor
- Modules Editor (Expands / Opens the Manifest)

Hope this helps a little bit more...

EDIT 2
- Edge and Chrome = same behavior

**Comment by adamdriscoll** [comment]
Got it. I can reproduce this. It seems to happen when more than 1 monaco editor is on a page. For example, there are multiple tabs of editors on the apps page but not on the page editor.

**Comment by adamdriscoll** [comment]
After much messing around, I think I've solved it. This was actually causing all kinds of weird IntelliSense issues as well.
