### ISSUE TITLE
Modifying existing schedule results in error

### ISSUE THREAD

**Issue by bt-ndollimount** [ironmansoftware/powershell-universal#4034]
### Description of Issue

When attempting to modify an existing schedule, it results in the following error:
Object reference not set to an instance of an object.

The changes are not saved.

### Version

5.0.15

### Severity

High

### Hosting Method

Other

### Operating System

Linux

### Database

PostgreSQL

### Licensed

Yes

### Features

Git Sync

### Additional Environment data

Amazon Linux
PowerShell 7.4.6
PostgreSQL 17

**Comment by adamdriscoll** [comment]
Can you please gather a system log? Can you also let me know if it's a specific schedule type? I'm not reproducing this.

**Comment by bt-ndollimount** [comment]
@adamdriscoll I just narrowed it down; it appears to only be an issue when trying to change the name of the schedule. I'm able to edit the CRON value without issue.
