### ISSUE TITLE
Cache page in Admin console shows "Unkown" for Created and Updated, "Never" for Last Read

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#4044]
### Description of Issue

Obviously PSU should know when a cache entry was created.
Most of these entries have been read, but they all show "Never".

### Version

5.0.15

### Severity

Low

### Hosting Method

Nested IIS

### Operating System

Windows

### Database

SQLite

### Licensed

Yes

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/ed049d5d-9931-470f-99aa-d6192ba280f8)

**Comment by adamdriscoll** [comment]
I think this is an issue with persistent vs non persistent data.

**Comment by MikeShepard** [comment]
Is the persistent/non-persistent evident in any way in the adminn console?

**Comment by adamdriscoll** [comment]
Good question. I'll check when I'm back at my desk.

**Comment by adamdriscoll** [comment]
There isn't any indication of persistent state. Fixed in .16. .16 will also fix the issue with time stamps for non-persistent cache items.
