### ISSUE TITLE
5.0.15 - RemoteHub | Import-PfxCertificate not working

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#4050]
### Description of Issue

For a customer project we need to make sure that a particular pfx certificate is available in the CurrentUser Store.
The Remote Hub doesn't let us do that right now because it fails with the following error message:
![image](https://github.com/user-attachments/assets/a9d32d36-46fa-4498-8b3f-582a1ff74edd)

I also tried to import the module directly but with no success.
Is there any sort of limitation in place right now with some system modules like this one? If yes, can I somehow override this restriction?

Thanks a lot in advance as always for your much appreciated help and commitment!

### Version

5.0.15

### Severity

Medium

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQL

### Licensed

Yes

**Comment by adamdriscoll** [comment]
There isn't any restriction on which cmdlets that are used that I'm aware of. It could be an assembly loading issue since the agent uses an embedded PS7 runtime. Try running Import-Module PKI across the hub to see if it provides a better error message.

**Comment by donlent** [comment]
OK very strange... If I try to Import-Module PKI -verbose I can see that all modules are loaded fine. It's just the execution that fails. Haven't played around with the other modules of PKI though... 
Probably it could be related to the embedded PS7 runtime. On Wednesday I'll do some more testing and will let you know about the results.
Thanks!

**Comment by donlent** [comment]
I managed to find the issue.
Apparently for the PKI module to wirk with PS7 (embedded) it needs to be imported like this:
Import-Module PKI -SkipEditionCheck

If you don't specify the -SkipEditionCheck argument it won't work. So it must be something with compatibility. But I don't care, since now it's working perfectly! So I'm closing this now... :-)
