### ISSUE TITLE
Failed to start the transport 'WebSockets'

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#4064]
### Description of Issue

i have 2 servers in a round robin NLB, i get this error:

```console
[2024-11-18T15:39:00.852Z] Error: Failed to start the transport 'WebSockets': Error: WebSocket failed to connect. 
The connection could not be found on the server, either the endpoint may not be a SignalR endpoint, the 
connection ID is not present on the server, or there is a proxy blocking WebSockets. 
If you have multiple servers check that sticky sessions are enabled.
```

### Version

5.0.15

### Severity

High

### Hosting Method

Nested IIS

### Operating System

Windows

### Database

SQL

### Licensed

Yes

### Additional Environment data

2 app servers
1 sql db
1 git repo

### Screenshots/Animations

call stack of the error
![image](https://github.com/user-attachments/assets/a129597a-9db4-4155-9a4b-bc4d820bb38c)

**Comment by Omzig** [comment]
@adamdriscoll, let me know if you want me to create a support ticket on this one... :(

**Comment by adamdriscoll** [comment]
@Omzig - What kind of load balancer? Are sticky sessions on?

**Comment by Omzig** [comment]
> sticky sessions

It is round robin. Trying to find out what kind, i assume it is dns round robin.

Sticky Sessions, i would say no.... do you have a preferred way to set it up? I was looking at the doc's and the SQL option looked cleaner than most.

**Comment by adamdriscoll** [comment]
Sticky sessions are a requirement for web sockets for both the admin console and apps. It's usually set up via the load balancer configuration and not something done with PowerShell Universal. For example: 

https://learn.microsoft.com/en-us/community/content/azure-configure-load-balancer-for-sticky-sessions

Round robin strategy is fine but once the connection is made it needs to stay with the node selected. 

EDIT: It looks like some docs refer to it as session affinity.

**Comment by Omzig** [comment]
OK! i am on it, tracking it up to an Azure LB

**Comment by Omzig** [comment]
woohoo, i found it here: https://docs.powershelluniversal.com/config/hosting/high-availability#load-balancing

Side Note:
- also, i was reading a little more, is this still true? i think you have a new option to keep the cache in the db now ;)
- https://docs.powershelluniversal.com/config/hosting/high-availability#multi-node-caching

**Comment by adamdriscoll** [comment]
Nope. Good catch. That doc needs a refresh.

**Comment by Omzig** [comment]
going to close this for now, if i still have trouble with the sticky sessions, i will reopen it. ty @adamdriscoll

**Comment by Omzig** [comment]
@adamdriscoll, its FIXED! we finally got to the right LB and now sticky sessions is on and psu doesn't go nuts! ty so much adam.
