### ISSUE TITLE
Automation Triggers not validated

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#4069]
### Description of Issue

I had a trigger which was set on event type "PowerShell App Started", but I inadvertently forgot to select an app.  The trigger saved fine and faithfully didn't do anything ever.

Until I realized and selected the app.

It should have told me it was an invalid trigger (no resource selected).

### Version

5.0.16

### Severity

Low

### Hosting Method

Nested IIS

### Operating System

Windows

### Database

SQLite

### Licensed

Yes

**Comment by adamdriscoll** [comment]
It should have run whenever any app started, so a bug either way. ;)
