### ISSUE TITLE
OpenTelemetry Plugin Fails to Load in PowerShell Universal v5.0.13 Docker Container

### ISSUE THREAD

**Issue by RubenT91** [ironmansoftware/powershell-universal#4081]
### Description of Issue

When attempting to enable the OpenTelemetry plugin in PowerShell Universal (PSU) version 5.0.13 running within a Docker container, the plugin fails to load, resulting in the following error message:

Failed to load plugins. Method 'AddServices' in type 'PowerShellUniversal.Plugin.OpenTelemetry.ServiceConfigFeature' from assembly 'PowerShellUniversal.Plugin.OpenTelemetry, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

Observed Behavior:

The PSU container fails to load the OpenTelemetry plugin, displaying the error message mentioned above.

Expected Behavior:

The OpenTelemetry plugin should load successfully without errors, allowing PSU to integrate with the specified OpenTelemetry endpoint.

### Version

5.0.13

### Severity

High

### Hosting Method

Docker Container

### Operating System

Windows

### Database

SQLite

### Licensed

Yes

### Additional Environment data

This issue appears to be related to a missing implementation of the AddServices method in the PowerShellUniversal.Plugin.OpenTelemetry.ServiceConfigFeature class within the plugin assembly. Assistance in resolving this problem would be greatly appreciated.

**Comment by adamdriscoll** [comment]
I can reproduce this in a docker container but not in a Windows install.
