### ISSUE TITLE
Update Documentation - Datagrid

### ISSUE THREAD

**Issue by parzog** [ironmansoftware/powershell-universal#4087]
### Summary of the new feature / enhancement

https://docs.powershelluniversal.com/apps/components/data-display/data-grid#filtering
This object is not a `hashtable` and `$items` is not an `array`, it's an `ArrayList`. Its objects do not contain those properties either. This is the JSON output for `$EventData`, with additional output for `quickFilterValues` which are also not included in this documentation (despite being very relevant for use, as the default quick filtering does not automatically wildcard itself):
![image](https://github.com/user-attachments/assets/0f042d9c-86e5-4335-a2e1-04fad8ec9529)

**Comment by adamdriscoll** [comment]
Updated with fixes and some new examples.
