### ISSUE TITLE
Data Retention value not honored

### ISSUE THREAD

**Issue by bt-ndollimount** [ironmansoftware/powershell-universal#4089]
### Description of Issue

The default data retention value is set to 30 days. However, the user session information appears to only be kept for about 3 days. I'm building a dashboard for managers to view dashboard usage of their users but the user session information is being cleared older than 3 days.

### Version

5.0.16

### Severity

Medium

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

PostgreSQL

### Licensed

Yes

### Features

Git Sync

### Additional Environment data

Windows Server 2022 Standard / Amazon Linux
PowerShell 7.4.6
PostgreSQL 16

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/265fc819-b7b1-45b9-85dd-d0cdd4e832c5)

**Comment by adamdriscoll** [comment]
It was actually hard coded to 1 day so not sure why it would survive longer. That said, I updated it to honor the data retention setting.
