### ISSUE TITLE
Reopening issue #4084

### ISSUE THREAD

**Issue by NLABC** [ironmansoftware/powershell-universal#4094]
### Description of Issue

Tested nightly release 5.1.0 (11964051188)
Issue #4084 still not resolved even though it's closed and mentioned in the change logs of this build.  Cannot select multiple items in a string array with ValidateSet.  

You can test with below code block by trying to select option 1 AND option 2.  You can only select one OR the other. "
param(
[Parameter(Mandatory)]
[ValidateSet("Option1", "Option2", "Option3")]
[string[]]$ParameterName
)
"

### Version

5.1.0 (11964051188)

### Severity

Medium

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQL

### Licensed

Yes

### Additional Environment data

Microsoft Windows Server 2022 Datacenter
Powershell version 5.1

**Comment by adamdriscoll** [comment]
Ok. Double checked latest 5.1 and it's working. During our triage call this was mentioned that it was still not working but I don't see that being the case. 

![image](https://github.com/user-attachments/assets/45b20508-27b5-4f86-bb17-0e45659560e0)
