### ISSUE TITLE
Deployment Packages

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#4101]
### Summary of the new feature / enhancement

Git deployment can be complicated and problematic. The current suggested branch-based git configuration makes it difficult for teams to work efficiently. Instead, we should consider implementing a deployment package feature. Deployment package would be immutable artifacts that could be deployed to PSU instances without having to manage git at all. 

Git can be used to author and store code but when deployed to production or staging environments, deployment packages could be used that would effectively be self-contained, versioned configurations of PowerShell Universal. 

Some features of deployment packages:

- ZIP files with the entire configuration repository 
- The ability to be versioned 
- Information about git commit\tag\branch\repo, if used
- Include required modules directly in the ZIP or provide a mechanism to pull them from a repository on deployment 

Deployment packages could almost just be PowerShell modules since they could include all this information and content. 

We would also need some way to store deployment packages. If they were modules, we could publish them to a repository and indicate in the DB that the version was updated, and other nodes need to update. We could also store them directly in the database but, while simple, it could lead to bloat. 

Deployment should also be possible through the API. You should be able to upload a deployment package directly to PSU nodes.

**Comment by adamdriscoll** [comment]
5.1 nightly builds have a preview version of this feature. I decided to release this in preview in v5.1 because it was actually pretty easy to implement, and I think this will have a major impact on how PSU is run in production. It's just way simpler than trying to manage git. 

## Deployment Config

Deployments can be found under settings. 

![image](https://github.com/user-attachments/assets/816512bb-1918-436b-a53c-8217ef0ded09)

Creating a new deployment will effectively snapshot the current PSU configuration and store the contents of the repository in the database as a ZIP with a name and version. The reason for the name is that this will eventually integrate with PSResourceRepositories as a PS module. The ZIP will be a nupkg file that contains a module manifest that can be published to things like the PSGallery. 

![image](https://github.com/user-attachments/assets/4fae10d0-e676-4c6f-bd9e-deea59e8a809)

Once created, it will provide a list of the deployments so you can manage them. 

![image](https://github.com/user-attachments/assets/4f4695f2-610f-4774-afd1-ee8190908561)

Now, if for example, I were to make changes to PSU, like adding an endpoint. I have a state I can roll back to. As you can see, I added a new endpoint. 

![image](https://github.com/user-attachments/assets/1b145767-8542-4a57-aa37-5c3134906b2b)

Now, if I click the apply button on the deployment, I can go back to the previous state. 

![image](https://github.com/user-attachments/assets/e1466538-eb79-4c33-982f-cff152e6cd24)

After applying the deployment, you'll see only 2 endpoints are now available. 

![image](https://github.com/user-attachments/assets/80fb0e51-d946-4af3-8bc8-e04017c9c7a4)

What's nice is that this is, by default, multi-node compatible. Applying a deployment applies it to all nodes. It also means you could have a single node you are editing on, then create a new deployment and then apply it to send the configuration to all other nodes that are in the cluster, without git. 

## Pinning

In addition to simple deployments, you can also select to pin a deployment when applying it. 

![image](https://github.com/user-attachments/assets/741f80c4-a9be-4383-aca9-989acfbf4780)

When you pin a deployment, PSU will become read-only, similar to one-way git sync. You'll also get some info about the current deployment version in the header. 

![image](https://github.com/user-attachments/assets/ef8db0da-2761-43a8-842b-f35890466ba5)

## External Deployments

That said, you could also create deployments remotely with the Management API. This way, you can still manage your code in git but without having to integrate it into PSU. The preferred method would be to use a module repository. 

In your github actions or CI\CD pipeline, you could take your PSU code, package it as a module and the publish to an internal PS repository. For example, you could publish a PSUProduction module with version 1.0.0 to your internal gallery. 

From there, you can call PSU to reconfigure itself using that module and version. The following REST call would all you would need to do in PSU (aside from ensuring it has the proper repository configured) to update the cluster. 

```
Invoke-RestMethod http://localhost:5000/api/v1/deployments/PSUProduction/1.0.0 -Method PUT 
```

Internally, PSU will call Save-PSResource to grab the module and extract it to the repository directory. What's nice about this as well is that if you include dependencies in the module manifest, they will be included in the PSU repository Modules as well. 

## Downside

The only downside I see from deployments is that the PSU server effectively resets all the configuration whenever a deployment occurs. It doesn't do anything incrementally.  There could be some downtime, depending on how large the configuration, while the PSU server reconfigures itself. The server never actually stops but clears out its local config cache and loads everything from scratch. 

Git configures things incrementally by seeing what files changed and then reconfigures just those resources. That said, because of the complicated logic involved, it's way more error prone.

**Comment by MikeShepard** [comment]
If we're happy with the git workflow is the use of deployments optional?

**Comment by adamdriscoll** [comment]
Yes, of course. Git isn't going anywhere or changing at all. That said, I think users would just need to choose deployments or git and not both in the same environment.

**Comment by gaelcolas** [comment]
You should be wary of encouraging folks to do their release Management from your GUI 🤓. It's ok as a feature, but I don't think it's something to push forward or for users to get used to...
You know, "friends don't let friends right click publish"....

As for the feature, that's great!
I'm the deployment, I'd remind user to make sure to deploy other parts in sync (i.e. database changes or other), but that's the same thing (or worse) with git branches.

Now, when the configuration is reloaded, have you documented the order?
Roles should be firsts, Environments next, api, dashboards and the rest after... No?

**Comment by adamdriscoll** [comment]
Agreed about the UI. All the stuff you can do in the screenshots above have APIs already. 

As for the order, I don't think it's documented. This is the current order. 

```
await Read<LoggingTarget>(syncContext);
            await Read<Tag>(syncContext);
            await Read<Variable>(syncContext);
            await Read<Translation>(syncContext);
            await Read<Settings>(syncContext);
            await Read<PowerShellMiddleware>(syncContext);
            await Read<License>(syncContext);
            await Read<Role>(syncContext);
            await Read<ExecutionEnvironment>(syncContext);
            await Read<Folder>(syncContext);
            await Read<Script>(syncContext);
            await Read<AuthenticationMethod>(syncContext);
            await Read<EndpointDocumentation>(syncContext);
            await Read<ComputerGroup>(syncContext);
            await Read<Endpoint>(syncContext);
            await Read<Schedule>(syncContext);
            await Read<PublishedFolder>(syncContext);
            await Read<RateLimitRule>(syncContext);
            await Read<Trigger>(syncContext);
            await Read<Terminal>(syncContext);
            await Read<Branding>(syncContext);
            await Read<Module>(syncContext);
            await Read<Dashboard>(syncContext);
            await Read<EventHub>(syncContext);
            await Read<PortalComponent>(syncContext);
            await Read<PortalPage>(syncContext);
            await Read<CustomHealthCheck>(syncContext);
```

Afterwards, it syncs modules. If those modules have a .universal folder, it'll load those resources in the order. There currently isn't an order to modules, though I do think that would be useful for dependencies.

**Comment by adamdriscoll** [comment]
The initial implementation of this is complete. I'll open separate issues as they arise from the preview.
