### ISSUE TITLE
New-UDRedirect -OpenInNewWindow doesn't open in new window

### ISSUE THREAD

**Issue by MikeShepard** [ironmansoftware/powershell-universal#4104]
### Description of Issue

`	Invoke-UDRedirect -Url "/ArchiveDetails?Campaign=$campaign" -OpenInNewWindow`

Opens in the same tab, not a new tab.

### Version

5.0.16

### Severity

Low

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQLite

### Licensed

No

**Comment by adamdriscoll** [comment]
You can work around this by using -Native. That said, I can reproduce this.
