### ISSUE TITLE
Issues with App logging.

### ISSUE THREAD

**Issue by chauberg** [ironmansoftware/powershell-universal#4105]
### Description of Issue

- DebugPreference seems to be ignored.
- Exceptions triggered in the App aren't logged.
- Write-Host -NoNewLine doesn't work.

I have made the following Test App

```
New-UDApp -Content {
    $DebugPreference = "Continue"

    Write-Information "ErrorActionPreference: $ErrorActionPreference"
    Write-Information "DebugPreference: $DebugPreference"

    Write-Debug "Debug from App"

    Write-Host "This should be " -NoNewLine
    Write-Host "the same line"

    throw "Exception inside App"
}
```

This is what I see in the App log

> [11/27/2024 12:53:09 PM] [Information] [App-Test] the same line 
> [11/27/2024 12:53:09 PM] [Information] [App-Test] This should be  
> [11/27/2024 12:53:09 PM] [Information] [App-Test] DebugPreference: Continue 
> [11/27/2024 12:53:09 PM] [Information] [App-Test] ErrorActionPreference: Continue 

Adding a trap to UDApp content seems to activate exception logging.

### Version

5.0.16

### Severity

Low

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQL

### Licensed

Yes

### Features

Git Sync, SAML

**Comment by adamdriscoll** [comment]
This is fixed in the nightly 5.1
