### ISSUE TITLE
Quickly switch my local development PSU to a different github repo and back

### ISSUE THREAD

**Issue by Omzig** [ironmansoftware/powershell-universal#4111]
### Summary of the new feature / enhancement

As a developer, I want a way to quickly flip to a different repo/branch so that i can work on an specific instance of PSU. 
- I find it tedious to go in and clean my repo folder and change my github settings just right and work through setting up each instance on my local machine. 

### Proposed technical implementation details (optional)

- add more than one github repo setting.
- add a way to flip/change to that other repo/branch.

**Comment by adamdriscoll** [comment]
Related #2842 

The deployment stuff I just did will actually make this pretty easy to do. Currently, the git settings are considered a single value but there is a table where we could easily have multiple configurations.

**Comment by Omzig** [comment]
cannot wait to find out how all that works :)
