### ISSUE TITLE
Portal Branding

### ISSUE THREAD

**Issue by bt-ndollimount** [ironmansoftware/powershell-universal#4119]
### Summary of the new feature / enhancement

Currently if you have custom branding configured in PSU, this branding doesn't port over to the Portal page. It would be good to have settings for custom branding for the Portal page as well.

**Comment by pyramidofgreatness** [comment]
Is there any way to manually edit the portal branding in the meantime?

**Comment by adamdriscoll** [comment]
@pyramidofgreatness Not at the moment. That said, this will be the in January release, so you won't have to wait too long :)
