### ISSUE TITLE
Associate a textbox and button with enter key

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#413]
Goal;
When a textbox are active and you push enter a specific button are pressed. That will get a better workflow when your working inside PSU dashboard.
For example if you are writing a search string in a textbox you just want to push enter key and not push a button on the side.

For example;
New-UDTextbox -Button "Button1"
New-UDButton -id "Button1" -OnKey "Enter"

**Comment by donlent** [comment]
Just "voting up" this request! 👍 :-D
Thanks a lot in advance!

**Comment by rwidmark** [comment]
@adamdriscoll can you solve this? :) I know many people are looking after this.

**Comment by donlent** [comment]
Yes please @adamdriscoll 
This would improve the usability of dashboards a lot, especially when you're using them from a non touch device, which is mostly the case probably... ;-)

**Comment by donlent** [comment]
Dear @adamdriscoll 
Sorry if I revive this topic again... But would it be possible to add this issue also to one of your next milestones? Doesn't need to be an immediate thing... but maybe for release 3.0?
It would really be a huge benefit for the users if that would work.
...I'm sure you're a keyboard guy as well and do understand what it means to avoid to use the mouse. ;-)
Thanks for taking this into consideration! Your efforts are really much appreciated! 😀👍
Don

**Comment by donlent** [comment]
Thanks alot! @adamdriscoll 🙏🏻😀
Really much appreciated!

**Comment by rwidmark** [comment]
Thanks @adamdriscoll
