### ISSUE TITLE
Add Search Bar in Scripts Page

### ISSUE THREAD

**Issue by alwaysforward14** [ironmansoftware/powershell-universal#4160]
### Summary of the new feature / enhancement

Would like to see a way to be able to search the scripts on the Automation -> Scripts section. I think this could be useful in other areas as well, but once you get a few pages of scripts, even after organizing into folders, it becomes difficult to find what you are looking for.

**Comment by adamdriscoll** [comment]
This was added in 5.1.

**Comment by alwaysforward14** [comment]
Thanks, sorry about that, had not seen it in the changelog, so my apologies if I missed it.
