### ISSUE TITLE
Updating custom modules via vscode plugin creates new files under .universal folder

### ISSUE THREAD

**Issue by MS-Marox** [ironmansoftware/powershell-universal#4161]
### Description of Issue

Creating custom modules via portal and editing them via vscode plugin ends in creating a new file under .universal/_FileNameHere_ and the module itself stays untouched.

### Version

5.0.16

### Severity

Low

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

SQLite

### Licensed

Yes

### Features

Git Sync
VSCode Plugin Version 4.2.4

### Additional Environment data

OS: Windows Server 2022 21H2
PSVersion: 5.1.20348.2849

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/c469849e-80f1-46c2-a832-e6c8237b0b97)

![image](https://github.com/user-attachments/assets/efd61d3b-0d8b-41ce-bdd0-00ad41eab559)

![image](https://github.com/user-attachments/assets/6a0f9b94-3d88-48cf-9cfd-4b40517d5668)

**Comment by MS-Marox** [comment]
The Problem is still present in version 5.2.2

**Comment by JessePeden** [comment]
This seems nearly identical to the bug I just filed at #4475
