### ISSUE TITLE
There seems to be a 'PowerShell Universal is starting...' loop occurring

### ISSUE THREAD

**Issue by bt-ndollimount** [ironmansoftware/powershell-universal#4167]
### Description of Issue

I noticed when checking Platform > Computers that random nodes were showing offline. I checked one of them and it was running, however when I tried to access the local site, it showed the 'PowerShell Universal is starting...' screen for a short bit and then ended on the login screen.

When I went to refresh the Platform > Computers page, that interface did the same thing. Once it loaded again, a different set of nodes were showing offline.

It seems all the nodes are in some sort of starting loop that's also affecting their heartbeat. This doesn't seem to affect the dashboards though as they continue to run, which is why I hadn't noticed until I happened to check Platform > Computers.

### Version

5.1.12

### Severity

Medium

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

PostgreSQL

### Licensed

Yes

### Features

Git Sync

### Additional Environment data

Amazon Linux
PowerShell 7.4.6
PostgreSQL 16

**Comment by bt-ndollimount** [comment]
As an aside that may or may not be related... I had just added a new Linux node, which is why I went to check the Platform > Computers section to begin with. Interestingly enough, that node doesn't seem to want to show online at all, however, I've targeted it to run a test script and it ran successfully. 🤷

**Comment by adamdriscoll** [comment]
I spotted the issue here. Let me know if this causes bigger problems than reporting. It's a small change and we could release a 5.1.3 if necessary.

**Comment by bt-ndollimount** [comment]
@adamdriscoll Seems to not be getting in the way of running jobs so we're good with it for now.

**Comment by bt-ndollimount** [comment]
@adamdriscoll We were having issues with an new Ubuntu node server and it turns out it was the time zone was set incorrectly. That has fixed a few things, including this issue. None of the hosts are doing the restart loop anymore. All the hosts are now showing as Online in the computers list. And the web interface, which runs on a different host entirely, is now noticeably snappier. Figured I'd let you know in case it was something you'd want to investigate to see if there are any other weird behaviors that specific scenario could cause.
