### ISSUE TITLE
Odd behavior with job status updates on long-running scripts

### ISSUE THREAD

**Issue by bt-ndollimount** [ironmansoftware/powershell-universal#4177]
### Description of Issue

We have a few scripts that take an hour or more to complete. These scripts are written to use parallel jobs and progress is written back while running. We've noticed since a while now that sometimes (more often in later versions) the job output will hit a point where it looks like the script has restarted. We will get the output written as if it restarted and we then start to get 2 progress amounts and it will flip-flop back and forth between the two. Sometimes if it goes long enough, there will be a third. Also, the job start time restarts to reflect the time the issue occurs and counts from there.

Checking in the Hangfire diagnostics, the current job will show that it started recently as opposed to the original job start time. When looking at the details, it displays at the top, "Looks like the job was aborted...".

My suspicion is that Hangfire is losing connection to the original process and assumes that it was aborted so it kicks off a new instance as a retry, but then you have processes running the same script, updating the output and progress to the same job, resulting in the job output showing the output of both scripts and the progress bouncing back and forth between the two.

We can see the two processes in Task Manager as well. The PID reported remains that of the first one; checking the start times of the processes, 15544 was exactly a half hour prior to 29260.

I never had enough details previously to confidently report it but it seems pretty obvious now what is happening.

**UPDATE**
We now have a third one spawned and it's also exactly a half hour after the second one spawned so that seems to be more than a coincidence. Added screenshots of the process properties showing the start times.

### Version

5.1.12

### Severity

Medium

### Hosting Method

MSI (Windows Service)

### Operating System

Windows

### Database

PostgreSQL

### Licensed

Yes

### Features

Git Sync

### Additional Environment data

Amazon Linux
PowerShell 7.4.6
PostgreSQL 16

### Screenshots/Animations

![image](https://github.com/user-attachments/assets/adf1e026-7783-42f6-9d2e-37933428f80c)
![image](https://github.com/user-attachments/assets/954c3d52-e3be-4168-a0fc-0e215b6f17f8)
![image](https://github.com/user-attachments/assets/24561ef0-632f-4bc1-9072-fb4675c693db)
![image](https://github.com/user-attachments/assets/222a0c7a-204b-463f-afe6-0cd2105643d3)

![image](https://github.com/user-attachments/assets/961dcaaf-8baa-4426-b3ed-d99e7f4d3e1a)
![image](https://github.com/user-attachments/assets/dea214df-8f14-4fec-9126-5c215afee499)
![image](https://github.com/user-attachments/assets/c314064f-c03b-4e61-a317-7ec10e59c4b6)

https://github.com/user-attachments/assets/6dc93c38-2361-4640-aa1d-d111479ea4c0

**Comment by bt-ndollimount** [comment]
Some additional things I noticed is that the scheduled runs of this recent one ran fine (2 hour run) so it might be contained to manually executed jobs. I'll execute it manually today to see if it experiences the issue again.

EDIT: Update; the manual execution is experiencing the issue again so it seems it may be isolated to manual runs.

**Comment by adamdriscoll** [comment]
I was able to nail this down. Hangfire has a default timeout (called Invisibility Timeout) of 30 minutes for jobs (but not scheduled ones?) when using PostgreSQL. They actually fixed this issue in the SQL backend to avoid having to set this setting but not PG. I've increased the timeout to 1 day. We may want to make this configurable in the future, but this seems fine in the meantime.
