### ISSUE TITLE
Simple Schedule seems to run multiple times before the next schedule

### ISSUE THREAD

**Issue by mwatts-seg** [ironmansoftware/powershell-universal#441]
**Describe the bug**
Simple Schedule - Run every 2 minutes seems to run more frequently

**To Reproduce**
1. Create script
2. Create schedule -> Simple Schedule (every 2 minutes)
3. Check Job Status page

**Expected behavior**
Should only run according to schedule (every 2 minutes)

**Screenshots**
![image](https://user-images.githubusercontent.com/60755343/132537809-0cd94d4b-c044-4fad-a01f-38c96a79460f.png)
![image](https://user-images.githubusercontent.com/60755343/132537927-8ff959fd-54f2-4d12-a8ae-595b2acddee0.png)

**Version**

Version Number: 2.2.1

**Comment by adamdriscoll** [comment]
@mwatts-segops Can you do me a favor and let me know what's listed under the hangfire dashboard? 

https://localhost:5001/hangfire/recurring

**Comment by adamdriscoll** [comment]
Never mind. I created the wrong kind of schedule. Trying to reproduce...

**Comment by adamdriscoll** [comment]
What I'm actually after is located under scheduled: https://localhost:5001/hangfire/jobs/scheduled

In my environment, it schedules it properly. What I'm thinking is that there must be some sort of misfire here and we might have multiples in this list for the same schedule. 

![image](https://user-images.githubusercontent.com/1256531/132612179-a59d53d9-7ffc-424f-a3fe-cf17edbb6a20.png)

**Comment by mwatts-seg** [comment]
@adamdriscoll  - I am not sure if I am not doing something right, but accessing the URL on the server produces cannot establish a connection to the server when using port 5001. Port 5000 produces a blank page.

**Comment by mwatts-seg** [comment]
I did as a work around, because this was causing multiple emails to be sent put a work around in by using a trigger on job completion with another job that is paired with.

**Comment by adamdriscoll** [comment]
OK. Strange. Glad you have a work around. 

As for the hangfire dashboard, sorry, I wasn't clear on that. 

On your PSU instance, go to: http://<servername>:<port>/hangfire/jobs/scheduled

**Comment by mwatts-seg** [comment]
> OK. Strange. Glad you have a work around.
> 
> As for the hangfire dashboard, sorry, I wasn't clear on that.
> 
> On your PSU instance, go to: http://:/hangfire/jobs/scheduled


@adamdriscoll  - Morning!
Maybe I have not had enough coffee this morning lol.
The URL above is missing the domainname, which I am assuming I would populate with the server name that I am running PSU on and the port. I have tried both http://myserver:5000/hangfire/jobs/scheduled & http://myserver:5001/hangfire/jobs/scheduled and am not able to see anything? 

I can implement the script again to test it and just comment out the email portion. This was in our production environment, so didn't want to continue flooding people with emails. :)

**Comment by adamdriscoll** [comment]
Ah, that's really weird. I don't know why you wouldn't have access to that dashboard. Don't worry about the job for now in prod. Let's schedule something next week to take a gander at this together.

**Comment by mwatts-seg** [comment]
> Ah, that's really weird. I don't know why you wouldn't have access to that dashboard. Don't worry about the job for now in prod. Let's schedule something next week to take a gander at this together.

Sounds good! :)

**Comment by adamdriscoll** [comment]
Just going through stale issues and wondering if you are still seeing something like this.
