### ISSUE TITLE
Modules Support

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#448]
It might be nice to include a section for defining modules in PSU. You could then include those with environments and then reuse functionality throughout the platform.

**Comment by adamdriscoll** [comment]
It could be kind of cool to provide a NuGet feed directly in PSU: https://www.nuget.org/packages/NuGet.Server/

**Comment by Viajaz** [comment]
This would be a fantastic feature, I've been disappointed with the current available NuGet.Server solutions and this would tie in perfectly with the use-cases I want to use PSU for, I was actually about to investigate how practical using https://github.com/emgarten/sleet with PSU would be.

https://github.com/emgarten/Sleet/blob/main/doc/feed-type-local.md

**Comment by adamdriscoll** [comment]
@Viajaz - I think you could use sleet with published folders. We might need to introduce an additional mine mapping for nupkgs.

**Comment by Viajaz** [comment]
> @Viajaz - I think you could use sleet with published folders. We might need to introduce an additional mine mapping for nupkgs.

That was the plan but, if this was a native feature in PSU, I'd use that instead.

**Comment by adamdriscoll** [comment]
I've branched the NuGet feed into it's own issue. In 2.4, you'll be able to include modules directly in the repository as well as view available modules in all environments. 

![image](https://user-images.githubusercontent.com/1256531/133831813-f0fe133e-0398-4fa5-a999-22fa376d18c7.png)
