### ISSUE TITLE
[Security issue!!!]User with no access can still access /admin page

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#450]
Hi,
I have the Windows Windows Authentication activated and the user can't access any of my dashboards as it's intended.
But if the user writes FQDN/admin the can see the Automation (Scripts and jobs) and Platform (Published folders, Rate Limits)
Under Rate Limits they can "Create New RateLimit" and Rate Limit settings.
Under the Published folders they can edit the folders and even create a NEW published folder!

If a user don't have access it should not get access to this page either.

**Comment by rwidmark** [comment]
@adamdriscoll This is according to me a critical issue!

**Comment by adamdriscoll** [comment]
I can reproduce part of this. Users do have access to view certain things in the console. I do not see that users have the ability to change anything in the console. I'll ensure that the issue with viewing published folders, rate limits, etc is resolved but I'll need some more information on how you were able to create items. 

Maybe a call would be best to identify this quickly.

**Comment by rwidmark** [comment]
> I can reproduce part of this. Users do have access to view certain things in the console. I do not see that users have the ability to change anything in the console. I'll ensure that the issue with viewing published folders, rate limits, etc is resolved but I'll need some more information on how you were able to create items.
> 
> Maybe a call would be best to identify this quickly.

I'll do some more checking and replay - I'll be operated (surgery) within two days so I'll be a bitt off.

**Comment by adamdriscoll** [comment]
Ok. Good luck with the surgery. Please let me know what you find and we can schedule a call whenever it's appropriate for you. Feel free to email adam[at]ironmansoftware.com

**Comment by adamdriscoll** [comment]
Have you experienced this issue since last year?

**Comment by rwidmark** [comment]
> Have you experienced this issue since last year? 

I did not go with that auth solution as it was not approved from the security board so I don't know.
