### ISSUE TITLE
Windows Authentication, removed user can still access dashboard

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#451]
Hi.
If I activate Windows Authentication everything works perfect and if the users are members of the AD group PSU.Users they can access my PowerShell Universal Dashboard etc.

But if I remove a user from the PSU.Users group in the AD they still can access my PowerShell Universal Dashboard. I did wait for 1h and they could still access it.

To resolve it I was forced to restart the PowerShell Universal service at the host.

I guess it's some kind of cache at the powershell universal host that not refresh against the AD and that's why the user are not blocked until you have restarted the service?

**Comment by adamdriscoll** [comment]
Yes. There is a cache that prevents the role operations from running over and over again for Windows Auth. That said, any change to the appsettings.json file requires a restart of the service.

**Comment by rwidmark** [comment]
> Yes. There is a cache that prevents the role operations from running over and over again for Windows Auth. That said, any change to the appsettings.json file requires a restart of the service.

I understand, how long is the cache? A Cache is good but maybe some manual trigger? So you can trigger it with a script or similar I don't want to restart the dashboard to force PSU to update the cache. It would be simpler if I could force trigger it instead when your doing big changes.

**Comment by adamdriscoll** [comment]
The cache timeout is set to the session timeout of the user. We could certainly introduce something to clear that cache.

**Comment by rwidmark** [comment]
Did a req for this function instead:

https://github.com/ironmansoftware/issues/issues/536
