### ISSUE TITLE
"Package Script as Exe" Code Signing (Authenticode)

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/powershell-universal#454]
The ability to have PowerShell code, and the resulting binary, be signed (Authenticode) as part of the process would be useful.

This can currently be achieved using [Set-AuthenticodeSignature](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-authenticodesignature?view=powershell-5.1) but having it as part of the packaging would be more efficient.

A Certificate Thumbprint for the code signing certificate could be defined in Package.psd1

**Comment by adamdriscoll** [comment]
We've added a certificate property to the package configuration. You'll be able to specify the path to the certificate store for the cert and it will sign after build.
