### ISSUE TITLE
Website: PowerShell Universal - Windows MSI Link 404

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/powershell-universal#455]
The "Windows MSI" download button for PowerShell Universal on https://ironmansoftware.com/downloads leads to a HTTP 404:
`https://imsreleases.blob.core.windows.net/universal/production//PowerShellUniversal..msi`

```xml
<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:REDACTED Time:2021-09-14T00:50:07.4627468Z</Message>
</Error>
```

@adamdriscoll

**Comment by Viajaz** [comment]
This seems to have resolved itself although I notice that it's offering 2.2.1 whilst changelog implies 2.3.0 has been released today?
https://docs.powershelluniversal.com/changelog

**Comment by adamdriscoll** [comment]
Release incoming...

**Comment by adamdriscoll** [comment]
Release has been released. I think we can close this issue. I don't see the issue with the blob.
