### ISSUE TITLE
Show-UDToast -Icon not working

### ISSUE THREAD

**Issue by alexsmid** [ironmansoftware/powershell-universal#456]
**Describe the bug**
When using Show-UDToast it is not possible to add an icon using the -Icon parameter

**To Reproduce**
Show-UDToast -Icon "ad" -Message "Test"
Or
Show-UDToast -Icon (New-UDIcon -Icon "ad") -Message "Test"

**Expected behavior**
An UDToast should show, with an icon.

**Version**
Version Number: 2.2.1 (running on Kestrel)
Dashboard Framework (if applicable): 3.5.2 
Operating System: Windows Server 2016 

**Additional context**
https://forums.ironmansoftware.com/t/show-udtoast-icon/5019

**Comment by adamdriscoll** [comment]
I think the problem is that they are case sensitive: Show-UDToast -Icon "Ad" -Message "Test"

**Comment by adamdriscoll** [comment]
Please let me know if you are still experiencing this issue with PSU 2.9 or later.
