### ISSUE TITLE
Everyone is Admin by default when configuring OIDC / WS-Fed

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/powershell-universal#46]
#### Description

I tried both with WS-Fed and OIDC but all the accounts connecting are Administrator.
I imagine it is possible to play around with security to restrict users but I think that By default, users should have no access. 
(That might require a special consideration for the first user that connect once OIDC / WS-Fed is setup) 

I would imagine, if anything, users connecting should not have access by default until configured and / or have a predefined default access (Since you can restrict the users that can connect through the SSO provider, you might want instead any new users that is granted access to have a default configurable role).

It might be already possible through configuration but the restrictive behavior to Admin. role should be the default and not "once configured". 

#### Additional Information

I'll do a new install to see if it fix the issue.
I deleted initial identities and added other so this might have caused the issue, although I was under the impression there was no restrictions in the first place, which pushed me to do that initially.

Also, this might or might nor be related but username stopped appearing.
I know  I'm logged in though as trying to access the page from a private window will bring me to the login page rather than this page.

![image](https://user-images.githubusercontent.com/1980296/95697251-17995e00-0c0c-11eb-825c-4f6ee5fc1ddf.png)

#### Version Information

- Universal: 1.4.3
- Universal Hosting- As Service
- PowerShell: Any
- Operating System: Any

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by Viajaz** [comment]
Is this because the Policy Scriptblock for the Admin role always returns true by default?

**Comment by adamdriscoll** [comment]
Yes

**Comment by adamdriscoll** [comment]
I'm going to maintain this behavior but warn with #354 that this should be updated.
