### ISSUE TITLE
Developer license

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#468]
It should be possible to run PSU local-only using a developer license. You should be able to generate a developer license from your Ironman Software account if you have an active PSU subscription.

**Comment by rwidmark** [comment]
For us that has licenses but no account. How can we get this license in the future?

My employer do have a partner that buys licenses etc as we are "big" so we don't handle it by our self.

Can we then generate dev licenses somehow from the original license?

Edit;
Also it would be great if you can spinn it inside a vm on the developer computer. I know many people working like that.
You maybe can limit two access at the time to the dashboard or similar to prevent people using the dev licenses in prod.

**Comment by adamdriscoll** [comment]
Developer licenses will be able to be generated from the parent license. 

![image](https://user-images.githubusercontent.com/1256531/136584896-47ed477c-e20c-4c60-88e1-f42adcd9c700.png)

You can install them and won't be able to access the machine remotely. 

![image](https://user-images.githubusercontent.com/1256531/136584757-61443d23-9445-44b4-8d35-215a17e58a85.png)

We might limit the concurrent connections in the future but it's more complicated and I didn't want to rush that in.
