### ISSUE TITLE
Support for IValidateSetValuesGenerator 

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#472]
https://forums.ironmansoftware.com/t/powershell-classes/5586/7

**Comment by memphisraynz** [comment]
Has there been any progress on this or another method to allow for a custom class to be available to ValidateSet?

**Comment by memphisraynz** [comment]
I was talking with Darren from ImmyBot, and he is implementing much the same code. To reading from params and dynamically change the web form.
Might be able to reach out to him, he seems very happy to assist.
