### ISSUE TITLE
NuGet Feed for local Module repository

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#476]
Branched from: https://github.com/ironmansoftware/issues/issues/448

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/cant-search-the-gallery-for-modules/6002/28

**Comment by adamdriscoll** [comment]
After talking with the Chocolatey team, I've decided against providing a dedicated NuGet server in PSU. The team over there said it's been painful to maintain their own custom feed and recommend Nexus OSS. It's what they actually use in C4B. 

https://www.sonatype.com/products/repository-oss-download

**Comment by Viajaz** [comment]
> The team over there said it's been painful to maintain their own custom feed

Yup, that's exactly why it would be useful to have such a feature, that's a shame. I was looking into whipping up something myself using https://github.com/emgarten/Sleet I might revisit that.
@adamdriscoll
