### ISSUE TITLE
$dte is null

### ISSUE THREAD

**Issue by ericmschmidt** [ironmansoftware/powershell-universal#479]
We have a script that we use to open any files changed between two changesets which utilizes the $dte object within the PowerShell Interactive Window which worked fine up until recently. Suddently I started receiving an error 'You cannot call a method on a null-valued expression.'. After some troubleshooting, I've identified that the problem is related to the $dte object being null now for some reason.

**To Reproduce**
1. Go to Visual Studio 2017 (v15.9.39) or Visual Studio 2019 (16.11.3)
2. Go to PowerShell Interactive Window
3. Type in $DTE and click enter
4. See that result is null/blank

**Expected behavior**
From the documentation, this should return a handle to the Visual Studio instance, which should allow you to execute commands such as File.OpenFile.

**Screenshots**
![image](https://user-images.githubusercontent.com/8714769/133854261-32cc6306-cdab-4dc7-8993-dfbb10daf66d.png)

**Version**

Tool: Visual Studio 2017 and Visual Studio 2019
Version Number: v15.9.39 and 16.11.3
Operating System: Windows 10 20H2 OS Build 19042.1237

**Additional context**
I was able to confirm with a co-worker that they were still able to access the $dte in Visual Studio 2017 v15.9.36. I've 

**Logs** 

Please upload a log. Logs are found in $Env:AppData\PowerShellProTools\ by default.
[log.devenv.exe.txt](https://github.com/ironmansoftware/issues/files/7188473/log.devenv.exe.txt)

**Comment by adamdriscoll** [comment]
Thanks for the report. This has been fixed and will be released in next month's release.

**Comment by ericmschmidt** [comment]
Awesome to hear. Thanks for checking in and fixing this. I'll be looking forward to the next update.
