### ISSUE TITLE
Swagger - show my endpoints

### ISSUE THREAD

**Issue by itfranck** [ironmansoftware/powershell-universal#48]
#### Description

Swagger is super nice but do not display my API endpoint.

It would be nice to be able to use the combo box to switch to endpoints available to the authenticated user
(For instance, if I am an Operator, then I should see endpoints available to my role and not all of them) 

Default swagger endpoint could also be hidden unless available to my role.
For instance, if I was to grant access to the helpdesk, I wouldn't want them to look at the PSU endpoints at all as they don't have the rights to use them.

![image](https://user-images.githubusercontent.com/1980296/95695055-45c67000-0c03-11eb-847d-50d21bdcaf9b.png)

**Comment by adamdriscoll** [comment]
I've implemented the first pass at this. Currently, it will show all the endpoints. I'll open a separate issue for tracking filtering by roles.
