### ISSUE TITLE
Windows Authentication don't show logged in user

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#480]
This one was closed so I open a new one as it's not resolved in 2.3.1.
https://github.com/ironmansoftware/issues/issues/449

When you have activated the Windows Auth and the user loggin, the user can't see there own username in the left or similar in the bar as they can do when they login trough other Auth solutions in to PSU.

I did update from 2.2.0 to 2.3.1 and the issue are still there.

**Comment by adamdriscoll** [comment]
I just tried this myself and don't have this issue. 

![image](https://user-images.githubusercontent.com/1256531/134066284-61a10e8d-b572-42db-8b83-ce6b611aeee5.png)

I tried both dark and light theme. Can you try clearing your web browser cache to see if that helps.

**Comment by rwidmark** [comment]
> I just tried this myself and don't have this issue. 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/1256531/134066284-61a10e8d-b572-42db-8b83-ce6b611aeee5.png)
> 
> 
> 
> I tried both dark and light theme. Can you try clearing your web browser cache to see if that helps. 

It's outside of the admin page.
Your inside the admin page now.

If you access your dashboard with the navbar without windows Auth you do see your name as you have showed in the pic above but if you access jt with windows auth the username is gone.

So the issue are inside the dashboard and not inside the admin page.
