### ISSUE TITLE
Windows ARM support for Dev?

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#481]
Hi,
I'm running macOS as my developer machine and I'm using Parallelse to spinn up VM's to try stuff on.
And as you know I can only run Windows 11 (arm) and Linux/macOS.

So I'm wondering if it's possible to make the MSI package universal or similar?
I'll try to install it later today and return here and see if it works which I guess as Windows 11 have good emulation (far better then Windows 10 ARM)

Edit;
Reason I have writing it for devs is as windows 11 arm etc are not made for prod environment as far as I know.

**Comment by adamdriscoll** [comment]
Yeah. We can produce a build for that. We only need to rebuild the .NET binaries so it doesn't add too much time to our build process.

**Comment by rwidmark** [comment]
> Yeah. We can produce a build for that. We only need to rebuild the .NET binaries so it doesn't add too much time to our build process. 

That would bee perfect :)

**Comment by rwidmark** [comment]
And also if possible ARM for docker :) I think many people are going over to ARM for dev machines etc.

**Comment by rwidmark** [comment]
@adamdriscoll any news on windows arm?

**Comment by rwidmark** [comment]
@adamdriscoll  any news on this?

**Comment by adamdriscoll** [comment]
Will be in tonight's nightly build.
