### ISSUE TITLE
Linux PSModulePath for environment adds semi colon

### ISSUE THREAD

**Issue by Entech-Ramon** [ironmansoftware/powershell-universal#5]
#### Description

When setting up an environment (either through the GUI or environments.ps1 path) using Linux and pwsh 7, setting the PSModulePath add a semi colon to the path you are adding.

#### Additional Information

Example Code:
`New-PSUEnvironment -Name "pwsh" -Path "/usr/bin/pwsh" -PSModulePath @('/home/.PowerShellUniversal/Repository/Modules') `
Output in Universal Automation
![image](https://user-images.githubusercontent.com/47992004/110171299-8482df80-7dc9-11eb-9517-d98d93005d1f.png)

Work around
Add a colon to the beginning of your path in the GUI or ps1 file.
`New-PSUEnvironment -Name "pwsh" -Path "/usr/bin/pwsh" -PSModulePath @(':/home/.PowerShellUniversal/Repository/Modules')`

![image](https://user-images.githubusercontent.com/47992004/110171563-e6434980-7dc9-11eb-9259-5b1e3d382cf2.png)

#### Version Information

- Universal: 1.5.X
- Docker
- PowerShell: 7
- Operating System: Any Linux

**Comment by adamdriscoll** [comment]
Fixed in 1.5.15
