### ISSUE TITLE
Frameworks get's copied in to C:\ProgramData\UniversalAutomation\Repository

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#507]
Got 2.3.1 of PSU with Git TwoWay activated and I have also moved Components folder like this in appsettings.json.
  "UniversalDashboard": {
    "AssetsFolder": "%ProgramData%\\UniversalAutomation\\Repository"
  },

I do see issue with this as if I update one server I might not want to update an other and then Frameworks folder get synced with Git.
I have three servers and the same thing happened to every singel on of them.

Side Q; why does it get copied in there? Can't it bee on its rightful place?

**Comment by adamdriscoll** [comment]
This is by design. I can add an option to turn this off but the idea was that you could pin to a framework version and upgrade PSU without upgrading the framework.

**Comment by rwidmark** [comment]
> This is by design. I can add an option to turn this off but the idea was that you could pin to a framework version and upgrade PSU without upgrading the framework. 

I see, so every version you use for your dashboards are automatic copied to that folder?

**Comment by adamdriscoll** [comment]
Yep

**Comment by rwidmark** [comment]
> Yep 

I see then no need to change anything I'll just exclude it in gitignore.
Document it in the documentation under git also would bee a good ide :)
