### ISSUE TITLE
OneWay git sync blocks logg in for admin user.

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#509]
PSU 2.3.1

When I do activate OneWay sync my user that are member of Administration grp can no longer access any dashboard and not even the administration dashboard.
I do understand that the admin dashboard are readonly if it's oneway but should you not see anything?

I isolated the issue as when I activate OneWay I can no longer access any dashboard or the administration page. This take a while around 1h then this happens.
Then if I change it back to TwoWay I can access everything again.

**Comment by adamdriscoll** [comment]
I'm unable to reproduce this one. I left it run all night to see if the git sync would mess with the roles but it never happened. Can you let me know a little bit about your roles.ps1 and what auth you are using? I was just using basic forms auth with default roles.

**Comment by rwidmark** [comment]
> I'm unable to reproduce this one. I left it run all night to see if the git sync would mess with the roles but it never happened. Can you let me know a little bit about your roles.ps1 and what auth you are using? I was just using basic forms auth with default roles. 

I can send you a mail with it later as it containes confidential  information I don't want to upload it here.

I'm using roles connected to ad account and every dashboard has multiple roles auth to it.

**Comment by rwidmark** [comment]
> I'm unable to reproduce this one. I left it run all night to see if the git sync would mess with the roles but it never happened. Can you let me know a little bit about your roles.ps1 and what auth you are using? I was just using basic forms auth with default roles.

You have mail now with the files.

**Comment by rwidmark** [comment]
Is it fixed in 2.4.0? @adamdriscoll

**Comment by adamdriscoll** [comment]
Yep. Nightly build failed yesterday but will be available tonight.
