### ISSUE TITLE
Progress demo not working as intented, bug in code?

### ISSUE THREAD

**Issue by McAndersDK** [ironmansoftware/powershell-universal#51]
#### Description
The following Demo: https://demo.ironmansoftware.com/progress
should show some colors and different sized, but it dont?

https://demo.ironmansoftware.com/avatar is having the same issue with the size, it's not reflected in the demo

https://demo.ironmansoftware.com/sparklines is having unknown cmdlet :)

#### Additional Information

I guess this is enought? :)

#### Version Information

What ever the Demo is running on ;)

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
This demo site no longer exists so closing this issue. You can find demos here: https://demo.powershelluniversal.com
