### ISSUE TITLE
Modules with 'Secret' in the module name cant be imported via environments

### ISSUE THREAD

**Issue by gitbute** [ironmansoftware/powershell-universal#529]
Hi there

Just like in the title, PS-Modules with 'Secret' in the name cant be imported via the environments.
I tried changing it to 'Seret' or even 'Sec' and this works just fine, all the same functions, cmdlets, variables etc.

Best Regards

**Comment by adamdriscoll** [comment]
I'm trying to reproduce this and haven't succeeded. What I'm doing is that I created a module called Secret.psm1 and include it in my environments.ps1 like this.

```
New-PSUEnvironment -Name "7.1.0" -Version "7.1.0" -Path "C:\Program Files\PowerShell\7\pwsh.exe" -Modules @('C:\Users\adamr\Desktop\Secret\Secret.psm1') -Variables @('*') 
New-PSUEnvironment -Name "Windows PowerShell 5.1" -Version "5.1.22000.65" -Path "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" -Variables @('*') 
New-PSUEnvironment -Name "Integrated" -Version "7.1.4" -Path "Universal.Server" -Variables @('*') 
New-PSUEnvironment -Name "6.2.7" -Version "6.2.7" -Path "C:\pwsh\6.2.7\pwsh.exe"
```

Then I'm call a function my my module in an API and that is working as expected. Am I doing this differently than you are?

**Comment by gitbute** [comment]
This is the environment that works:
```powershell
New-PSUEnvironment -Name "ServerManagementDashboard" -Version "5.1.14393.3866" -Path "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -Modules @('\\DOMAIN\PATH\PATH\PATH\git_PSSecretServer\PSSecretServer\PSSecServer.psm1') -Variables @('*')
```
This does not load the module correctly: (It shows how its trying to load the psm1, but then doesnt load the corresponding psd1, like in the example that works)
```powershell
New-PSUEnvironment -Name "ServerManagementDashboard" -Version "5.1.14393.3866" -Path "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -Modules @('\\DOMAIN\PATH\PATH\PATH\git_PSSecretServer\PSSecretServer\PSSecretServer.psm1') -Variables @('*')
```

I tried everything, and as soon as i renamed the psm1 and psd1 files it worked. I tried 'Seret' and 'Sec' wich works, only 'Secret' wont work. I expected maybe a strange interaction with the SecretManagement Module that Universal loads.
