### ISSUE TITLE
Universal Console Behaviour

### ISSUE THREAD

**Issue by insomniacc** [ironmansoftware/powershell-universal#53]
#### Description

The Universal console has the following issues compared to UD admin console:

- Unable to paste into the console
- Behaviour is different - for example, get-variable works in a UD console but does not in Universal console (this also applies to things like the $Pages and $cache variables)

#### Version Information

- Universal: 1.3.1
- UD Framework: 2.9.3
- Universal Hosting Method (IIS, Executable, docker etc): IIS
- PowerShell: 5.1
- Operating System: Windows

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by Entech-Ramon** [comment]
Would like to mention other issues we have with the console. 

- The text being displayed is wonky. Example with Get-Runspace and (Get-Runspace).id

![image](https://user-images.githubusercontent.com/47992004/124810673-9c14d500-df2f-11eb-8502-f6a4e3e05acd.png)
![image](https://user-images.githubusercontent.com/47992004/124810844-ce263700-df2f-11eb-9566-f9ecc8b8ee74.png)

Happens in 1.5.20 and 2.1.1

- In 2.1.1 can't use backspace when typing a command.
