### ISSUE TITLE
New-UDGrind -spacing don't seem to work?

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#535]
PSU 2.3.1

New-UDGrid -Spacing don't seem to work anymore here is a example code that for me don't work. I can change the -spacing to whatever I won't but it won't work. The spacing between the rows are still them same. I needed to put New-UDHtml -Markup "</br>" to get some spacing and I'm guessing that's not right?

New-UDGrid -Spacing '20' -Container -Content {
New-UDGrid -Item -Size 6 -Content {
        New-UDCard -Title 'Användar Grupp' -Content {
            New-UDDynamic -Id 'MTUserGroup' -content {
                New-UDGrid -Spacing '20' -Container -Content {
                    New-UDGrid -Item -Size 4 -Content {
                        New-UDHtml -Markup "<b>Fråga</b>"
                    }
                    New-UDGrid -Item -Size 6 -Content {
                        New-UDHtml -Markup "<b>Svar</b>"
                    }
                    New-UDGrid -Item -Size 2 -Content {
                    }
                    New-UDGrid -Item -Size 4 -Content {
                        New-UDHtml -Markup "<b>Fråga</b>"
                    }
                    New-UDGrid -Item -Size 6 -Content {
                        New-UDHtml -Markup "<b>Svar</b>"
                    }
                    New-UDGrid -Item -Size 2 -Content {
                    }
                    New-UDGrid -Item -Size 4 -Content {
                        New-UDHtml -Markup "<b>Fråga</b>"
                    }
                    New-UDGrid -Item -Size 6 -Content {
                        New-UDHtml -Markup "<b>Svar</b>"
                    }
                    New-UDGrid -Item -Size 2 -Content {
                    }
                    New-UDGrid -Item -Size 4 -Content {
                        New-UDHtml -Markup "<b>Fråga</b>"
                    }
                    New-UDGrid -Item -Size 6 -Content {
                        New-UDHtml -Markup "<b>Svar</b>"
                    }
                    New-UDGrid -Item -Size 2 -Content {
                    }
                }
            }
        }
    }
}

**Comment by adamdriscoll** [comment]
It looks like it needs to be a value between 0 and 10. 

This is 10. 

![image](https://user-images.githubusercontent.com/1256531/142230389-3a042c93-e0b7-48dc-b65d-b7b7c81d9eda.png)

This is 0.

![image](https://user-images.githubusercontent.com/1256531/142230433-5c239381-f9dd-4fff-b038-c2e70038a738.png)

I've updated the parameter and introduced a ValidateRange to ensure that the proper values are set.
