### ISSUE TITLE
Clear AD cache from dashboard

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#536]
It would be very good if this feature was implemented.

As you know the AD cache is connected to the users session so it's only renewed when the user session expires.

So my thought is that you can call a reset function from inside the dashboard when or after you have done / executed something.

Something like this;
New-PSUADCache -reset

And it's important that the dashboard don't need to bee reloaded as if it's reloaded all the users are going to bee affected and in the end irritated.

I also want this to refresh/reset the cache for the AD-Groups that are connected to a role.

**Comment by adamdriscoll** [comment]
We've added an endpoint to v2.9 that allows for removing entries from the memory cache. It's more generic than the cache we use for AD but should achieve the same result. I'll make sure that gets in the docs and leave this open until we come up with a more specific solution to this.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/update-rate-of-ad-group-membership-for-windows-authentication/6894/2

**Comment by adamdriscoll** [comment]
We've add a button and endpoint to accomplish this in 2.10. 

DELETE /api/v1/cache/claims
On the Roles page, you can also click the Clear Cached Claims button.
