### ISSUE TITLE
Export as .log or .PDF code editor

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#537]
It would bee great if the same export function that UDTable has was added to the code editor.
Only one thing that are different and that it would bee nice to have the option to export it as .log file

**Comment by adamdriscoll** [comment]
We've added Start-UDDownload in 2.6. You'll be able to add a button that performs a download. 

```
New-UDButton -Text 'Download Log' -OnClick {
   $code = (Get-UDElement -Id 'myEditor').code
   Start-UDDownload -StringData $code -FileName 'code.log'
}
New-UDCodeEditor -Id myEditor
```
