### ISSUE TITLE
Schedule disappeared - Getting error in notificaiton bar

### ISSUE THREAD

**Issue by mwatts-seg** [ironmansoftware/powershell-universal#538]
**Describe the bug**
A script stopped scheduling out. I noticed in the notification drop down this appeared: 
Invalid configuration: schedules.ps1
Sequence contains no elements
10/04/2021 10:00 AM

I checked schedules.ps1 and the schedule exists for both entries, but not sure why it did not schedule out? 
Looking at the schedule tab, I do not see it when viewing the script or the schedules page. I can see the entry in schedules.ps1

New-PSUSchedule -Cron "1 2,4 * * *" -Script "ContainerGetINCount.ps1" -TimeZone "America/New_York" -Credential "Default" -skipRedefine 'N' 
New-PSUSchedule -Cron "30 8 * * *" -Script "ContainerGetINCount.ps1" -TimeZone "America/New_York" -Credential "Default" -skipRedefine 'N'

**To Reproduce**
1. Click script details
2. Click 'Schedules' 
3. Nothing appears

**Expected behavior**
Should schedule out?

**Screenshots**
![image](https://user-images.githubusercontent.com/60755343/135890340-ed225389-3c82-449f-88a3-f871c360a981.png)

**Version**
2.3.2

I tried attaching log, but github is not allowing me, reporting 'is not included in the list.'

**Comment by adamdriscoll** [comment]
Being a very old issue, I'm going to assume this is resolved. If you are still experiencing this, please let me know and we can re-open and investigate on the newest version.
