### ISSUE TITLE
Docs: Create a doc to outline how to move app tokens between systems

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#541]
Multiple customers have asked for how to move app tokens between PSU instances for redundancy.

**Comment by Viajaz** [comment]
What happens right now when you use the same JWT signing key between multiple instances when the token was signed and recorded in one instance but not the other?

**Comment by adamdriscoll** [comment]
The token won't work in the system where it doesn't exist in the database. We validate that the token isn't revoked so if it doesn't exist, it won't be valid even though the signing keys match.

**Comment by rwidmark** [comment]
Here is my solution:

https://github.com/rstolpe/PSU-Random/tree/main/AppToken

**Comment by Viajaz** [comment]
@rstolpe That makes me think of how you could make a high availability setup for PSU.
Assuming most of what you wanted was stateless/minimial-state API endpoints, could use reverse proxy for load balancing or a DNS round-robin setup, maybe create API endpoints on each PSU to sync API token manually with each other?
Discussion for the forums I think.

**Comment by rwidmark** [comment]
> @rstolpe That makes me think of how you could make a high availability setup for PSU.
> 
> Assuming most of what you wanted was stateless/minimial-state API endpoints, could use reverse proxy for load balancing or a DNS round-robin setup, maybe create API endpoints on each PSU to sync API token manually with each other?
> 
> Discussion for the forums I think.

I actually has HA on my PSU. Using NetScaler to load balancing from VIP address to one of my two servers that running the excatly same PSU and code.

Code are syncing with git.

**Comment by adamdriscoll** [comment]
Here are the docs to migrate an app token. 

https://docs.powershelluniversal.com/config/security/app-tokens#migrating-app-tokens
