### ISSUE TITLE
New-UDPage loading issue when -id and -endpoint are supplied together

### ISSUE THREAD

**Issue by insomniacc** [ironmansoftware/powershell-universal#55]
#### Description
Endpoint pages do not load (blank) when new-udpage has both -id and -endpoint parameters specified together.
(Tested on UD 2.9.3 Only)

#### Version Information

- Universal: 1.3.1
- UD Framework: 2.9.3
- Universal Hosting Method (IIS, Executable, docker etc): IIS
- PowerShell: 5.1
- Operating System: Windows

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
This is not reproducible on v3.7.7.
