### ISSUE TITLE
Reduce Complexity of Universal Dashboard

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#554]
I'm considering making some changes to how Universal Dashboard works. This is a breaking change and thus in PowerShell Universal v3. The current configuration of Universal Dashboard is a hold over from the when it was a PowerShell module. I think we should reduce the complexity. 

## Merge the Universal Dashboard Module with the Universal module

Include the Universal Dashboard cmdlets directly in the Universal module. This would make installation of the modules easier. 

## Merge built in components into the main react app

There really isn't much benefit in having the components external. We should just merge those directly into the main UD react app. There would be no need to add components for charts, UDStyle, the code editor etc. 

## Merge the Universal Dashboard React app with the admin console React app 

Having separate react apps makes it difficult to manage and develop. Merging the react app would remove a lot of overhead and complexity. 

## Remove the ability to select previous versions of the Universal Dashboard framework

Merging the react apps would remove the ability to run previous versions of the UD framework in a PSU instance. Most people just run the latest anyways so this should be an issue. 

## Drop Support for Universal Dashboard v2 

The v2 framework sees little use and is updated infrequently. 

## Feedback

Please feel free to comment below about this plan. PSU v3 does not have an ETA but will likely happen in 2022.

**Comment by dkkazak** [comment]
I like these ideas.  I admin that, while I have some v2 dashboards, I have never tried running them under the new framework and am instead migrating them (slowly) to the new dashboards.  What you say above would simplify things, for sure.
