### ISSUE TITLE
SQL Support

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#555]
We currently use LiteDB for persistence. This doesn't work well for several scenarios; including HA. 

- Hangfire SQL Support
- Job, app token and identity storage

**Comment by rwidmark** [comment]
What's the play here?
Separated SQL DB on its own server and then the PSU on the other

**Comment by adamdriscoll** [comment]
That's would be the recommended setup. It would allow for redundancy of the PSU instance as well as clustering of the SQL server as well.

**Comment by rwidmark** [comment]
> That's would be the recommended setup. It would allow for redundancy of the PSU instance as well as clustering of the SQL server as well. 

Perfect :) then cache are not needed as much anymore.
I'm currently setting up SQL to minimize the cache use.

**Comment by Entech-Ramon** [comment]
Would it be possible to make sure there is support for Azure SQL? I know there are some small limitations between on prem and Azure SQL.

**Comment by Entech-Ramon** [comment]
This might be more trouble than it's worth, I'm wondering if certain things that are currently managed in ps1 files can be moved over to SQL. I'm specifically thinking of Script schedules. With our current workflow in order to adjust any schedules we'll have to update code and make pull requests etc.

**Comment by adamdriscoll** [comment]
RE schedules in the database: It's possible but something I'm not targeting for this first iteration. I understand the appeal of that though. The idea with the code-base configuration is the ability to validate and verify changes so that's why PSU is setup like this so I would say that it is by design that you would need to update code and make PRs to change schedules. 

In terms of Azure SQL support, this should also work with that. We are implementing an EF 6 database layer that can will talk to SQL server on-premises and within cloud services. Once we have that base, we should be able to add additional SQL providers pretty easily.

**Comment by Entech-Ramon** [comment]
Thanks for the insights @adamdriscoll, much appreciated.
