### ISSUE TITLE
Python\Other Language Support

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#558]
We've had an increasing number of people asking for python support. Obviously, we'd have to do some rebranding if this was something that we decided to embrace. 

I would rather not implement python support for Universal Dashboard as it would be an insane amount of work. What we could implement is API and Script support. Python users could use Pages with those features to have some sort of UI abilities. 

I like the idea of supporting another powerful DevOps language but I worry about the feature creep of something like this.

**Comment by rwidmark** [comment]
I for one think it's stupid to support python.
I love it, but powershell universal should aim to bee perfect with powershell hence the name of it.
Don't let this steal time from other important fixes, updates etc.

**Comment by adamdriscoll** [comment]
Thanks for the feedback. We have started 0 work on this and this was merely an issue open for discussion so I'm happy to hear that this isn't something that you are looking for.

**Comment by timd19** [comment]
I think the ability to run python scripts would be great. We have a mix of people with PS and Python experience, and allowing any of them to write a script to run in PU I think would be a big benefit.

I agree not having a full python support for UD, but the ability to even run scheduled python scripts I think would be a huge improvement.

**Comment by Entech-Ramon** [comment]
I currently use python with PowerShell universal for things that are just easier in python or there no is module for in PowerShell. For my linux container, I just install python and my needed pip packages in the dockerfile. For windows machines, I would imagine you just install it normally and can wrap the py file in a function/API. 

![image](https://user-images.githubusercontent.com/47992004/151863965-754bf3bd-e543-45d4-942f-add8bef37ddf.png)

![image](https://user-images.githubusercontent.com/47992004/151864038-cb9dafb4-eee5-40f6-8b24-fdc2175a709f.png)

**Comment by sgaglione** [comment]
@Entech-Ramon's is the way I would solve the problem including a different language runtime.  I think of how my plans to execute ansible playbooks via PSU and it would simply be a powershell wrapper making calls to a linux host to run `ansible-playbook` .  In theory you could create an powershell function and/or endpoint to wrap the logic, repeated code that simplifies the use case whereby you pass the path to the python executable, path to file and parameters.
