### ISSUE TITLE
HA SQL script run

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#562]
This is a function for when the SQL feature are released.

If you have more then one PSU server and are updating them with GIT then you will have the same schedule etc for the scripts as it's from the same branch.

I guess that no one wants the same script runt multi-times but from different servers and as it's HA you need to have the same config on every server.

The solution is that when a script runs it do fill it out in the SQL DB, time stamp.
And then before a script runs it checks the SQL DB if the script with the same name has been started within the latest 5 minutes if it has then the script will not run.
And if it has not been registered in the SQL then the script runs anyway.

Failover should bee if PSU don't have access to the SQL DB or can't connect then the script should run.

Flow;
- Script starts; check if it has been registrar in SQL if it has then check if it's older the 5 min if it's older or not register then the script runs else it don't run.

I'm writing this now as this is important to have at the same time when you release the SQL function.

**Comment by adamdriscoll** [comment]
This is going to be a function of the SQL integration for Hangfire (our scheduling library). It supports multiple servers so it manages the execution across multiple job runners. Once we turn that on, we should be able to scale out job agents and they won't run the same jobs.

**Comment by rwidmark** [comment]
> This is going to be a function of the SQL integration for Hangfire (our scheduling library). It supports multiple servers so it manages the execution across multiple job runners. Once we turn that on, we should be able to scale out job agents and they won't run the same jobs. 

Perfect the solution above my current work-a-round for our HA solution for PSU
