### ISSUE TITLE
Connect-PnPOnline TelemetryConfiguration exception

### ISSUE THREAD

**Issue by IdahoVandal** [ironmansoftware/powershell-universal#568]
**Describe the bug**
Connect-PnPOnline in an Automation Script returns this error:
> The type initializer for 'Microsoft.ApplicationInsights.Extensibility.TelemetryConfiguration' threw an exception. 

**To Reproduce**
Example script:
`$env:PNPPOWERSHELL_DISABLETELEMETRY = $true`
`$env:PNPPOWERSHELL_UPDATECHECK = $false`
`Connect-PnPOnline -Url "https://tenant-admin.sharepoint.com" -Credentials $Secret`

**Expected behavior**
Successful connection to SharePoint Online

**Version**
Version Number: 2.4.0
Environment: Windows PowerShell 5.1
Operating System: Windows Server 2019
PnP.PowerShell Version Number: 1.8.0

**Comment by adamdriscoll** [comment]
This module is very problematic for PSU. Was this working in the previous version?

**Comment by IdahoVandal** [comment]
Unfortunately I don't know if it worked in a previous version as I have only tried integrating it since 2.3.0 and have been getting the assembly conflict issues mentioned in issue #394 until the 2.4.0 fix you added. There was some discussion about similar problems with the module in Azure Functions so I will see if I can find some information there in how the module is loaded and possible workarounds.

**Comment by IdahoVandal** [comment]
@adamdriscoll, I tried Disable-PnPPowerShellTelemetry, -NoTelemetry and variations of the PNPPOWERSHELL_DISABLETELEMETRY=true environment variable and it will continue to throw the same exception. I can make the connection in a Start-Job background process and wait for it to finish but that is basically just wrapping the entire script in a background job.

**Comment by adamdriscoll** [comment]
I've stood up a SharePoint online environment and can reproduce this. Trying to get it fixed today.

**Comment by adamdriscoll** [comment]
Success! This will be included in the 2.5 release due out Oct 9th. This fix will also be in tonight's nightly build. 

![image](https://user-images.githubusercontent.com/1256531/139454290-eb151c3c-1610-493d-99ba-418d0d76974a.png)
