### ISSUE TITLE
PowerShell Universal MSI: "Start Service after Install" Toggle Option

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/powershell-universal#572]
Can you please include an option (both in the interactive wizard and as a MSI option parameter) to disable the starting of the PowerShell Universal service after install?

When upgrading a PowerShell Universal MSI install, it replaces the `appsettings.json` with a default one, the default functionality starts the service after installation completes, causing PSU to start with the incorrect configuration.

**Comment by adamdriscoll** [comment]
Sure. That said, I would totally recommend putting custom appsettings.json in ProgramData. It won't replace that one and will use that by default. 

https://docs.powershelluniversal.com/config/settings#programdata-appsettings.json

**Comment by Viajaz** [comment]
No idea how I missed that, will do that.
That said, I still think this feature does have utility, if `appsettings.json` needs to be modified to include new configurations options for changed/new features from the new version then you don't want the PSU service starting automatically.
