### ISSUE TITLE
2.4.0 OneWay sync blocks access to Admin page.

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#574]
The issue are still there, it was present in 2.3.2 and it's still there in 2.4.0.
This happens to the account that are member of the Role Administrators.

When you have activated OneWay sync and trying to access /admin you get Unauthorized Access.

The thing that are working is that now you can access the "ordinary" page with 2.3.2 you also did get Unauthorised Access there also.

This starting to get a little irritating as git conflict are getting popup up many times due to someone change something etc.

@adamdriscoll begging you for a 2.4.1 for a fix of this.

**Comment by adamdriscoll** [comment]
I can't reproduce this. I turned off all roles except admin. 

```
New-PSURole -Name "Administrator" -Description "Administrators can manage settings of UA, create and edit any entity within UA and view all the entities within UA." -Policy {
param(
$User
)
        
#
# Policies should return $true or $false to determine whether the user has the particular 
# claim that require them for that role.
#

$true
} 
New-PSURole -Name "Operator" -Description "Operators have access to manage and execute scripts, create other entities within UA but cannot manage UA itself." -Policy {
param(
$User
)
        
#
# Policies should return $true or $false to determine whether the user has the particular 
# claim that require them for that role.
#

$false
} 
New-PSURole -Name "Reader" -Description "Readers have read-only access to UA. They cannot make changes to any entity within the system." -Policy {
param(
$User
)
        
#
# Policies should return $true or $false to determine whether the user has the particular 
# claim that require them for that role.
#

$false
} 
New-PSURole -Name "Execute" -Description "Execute scripts within Universal Automation." -Policy {
param(
$User
)
        
#
# Policies should return $true or $false to determine whether the user has the particular 
# claim that require them for that role.
#

$false
}
```

I can login. 

![image](https://user-images.githubusercontent.com/1256531/137121659-b11cc144-a3c7-4ace-b744-1ec21e51ef3e.png)

My appsettings look like this. 

```
  "Data": {
    "RepositoryPath": "%ProgramData%\\UniversalAutomation\\Repository",
    "ConnectionString": "filename=%ProgramData%\\UniversalAutomation\\database.db;upgrade=true",
    "GitRemote": "https://github.com/ironmansoftware/shiny-octo-waffle.git",
    "GitUserName": "adam",
    "GitPassword": "PAT",
    "GitBranch": "main",
    "GitSyncBehavior": "OneWay",
    "ConfigurationScript": ""
  },
```

When you say ordinary page, what do you mean?

**Comment by adamdriscoll** [comment]
I've tried with several authentication types as well (Forms, Windows, OIDC) and it still works for me.

**Comment by rwidmark** [comment]
> I've tried with several authentication types as well (Forms, Windows, OIDC) and it still works for me.

Hi @adamdriscoll 
I'm logging with form and AD auth every role with a group.
If my Admin are member of the Administrator group/role and an other I get access denied for the /Admin page.
If I then remove this member from the other group so it just are member of Administrator group then I can't even login on any page/dashboard.
When I try to login the page are loading and then it just get back to the login page with the username and password field blanked.

This only happens when I do activate OneWay sync and not if I active TwoWay. And if I reverse it back from OneWay to TwoWay everything starts to work again.

I'll email you my configuration as it's classified information in it.

**Comment by rwidmark** [comment]
This seem to bee fixed now thanks :)
