### ISSUE TITLE
Schedules - Active Hours

### ISSUE THREAD

**Issue by ksl28** [ironmansoftware/powershell-universal#582]
**Describe the solution you'd like**
We often use the Simple schedule types, to execute scripts every hour.
But we are missing an feature like "Active Hours", to specify an time range, when the scripts must be executed.

**Describe alternatives you've considered**
Right now we have several scripts that run every hour, starting at 08:00AM, and stops at 10:00PM.
But we have to create an schedule for each script, for each hour that it has to execute.

**Comment by Viajaz** [comment]
There is support for Cron expressions which allows for this.

Every Hour, On the Hour, between 08:00 and 22:00
`0 8-22 * * *`

**Comment by ksl28** [comment]
Thanks - i must have missed that part.
