### ISSUE TITLE
TimeZone for PS Universal docker container

### ISSUE THREAD

**Issue by qlikq** [ironmansoftware/powershell-universal#594]
**Is your feature request related to a problem? Please describe.**
I noticed that when i run a script from my local pc, the date/time when script is executing is correct, when i run the same script via Powershell Universal that runs in a docker, it its UTC+0 time , entries in DB have bad timestamps when i use get-date inside of the script.

**Describe the solution you'd like**
I am open for any solution. I am no specialist with docker, but maybe it is possible to add a timezone ENV variable like Europe/Amsterdam , America/Chicago ? so anybody can change it for one's needs. I noticed that there was no tzdata pkg inside the container. I suppose one also has to issue 'apt-get install tzdata'

**Describe alternatives you've considered**
I have manually added package tzdata into container and configured it. Afterwards powershell get-date shows the time in correct manner according to my timezone.

Thank you

**Comment by Entech-Ramon** [comment]
If you are using a linux docker container, try adding this to your dockerfile.
`RUN apt-get install -y tzdata`
Then Add the following environment variable.
TZ = America/Chicago
or if starting the container from command line.
`-e TZ='America/Chicago'`

**Comment by qlikq** [comment]
> If you are using a linux docker container, try adding this to your dockerfile. `RUN apt-get install -y tzdata` Then Add the following environment variable. TZ = America/Chicago or if starting the container from command line. `-e TZ='America/Chicago'`

Hello, thank you for comment.  I will give it a try tomorrow at work, to build it again with your remarks.
Just pasting 1 remark from severfault:
ENV TZ=America/Los_Angeles
RUN apt-get install -y tzdata && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

via
https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes

I will report back tomorrow if all worked.

**Comment by qlikq** [comment]
@Entech-Ramon Hello, i have tested it today, everything works like you mentioned. It is not required to set the symbolink links etc.
my dockerfile looks like this now:

> FROM ironmansoftware/universal:latest
> LABEL description="Universal - The ultimate platform for building web-based IT Tools"
> EXPOSE 5000
> VOLUME ["/data"]
> ENV Data__RepositoryPath ./data/Repository
> ENV Data__ConnectionString ./data/database.db
> ENV UniversalDashboard__AssetsFolder ./data/UniversalDashboard
> ENV Logging__Path ./data/logs/log.txt
> ENV TZ Europe/Amsterdam
> RUN apt-get install -y tzdata
> ENTRYPOINT ["./home/Universal/Universal.Server"]

And one can run instance with -e TZ=Europe/Amsterdam  for example, and once in pwsh, it reports the correct timezone

PS C:\PSUBuild> docker run -e "TZ=Europe/Warsaw" --rm -d -p 5009:5000 qlikq/gregprivaterepo:newpsu
9b887c48f54482d78e9896119b6f8f779fb8045b0e7c05af7fd0dcaae8368c83
PS C:\PSUBuild> docker exec -it 9b887  pwsh
get-PowerShell 7.1.4
...
PS /> Get-TimeZone

Id                         : Europe/Warsaw
DisplayName                : (UTC+01:00) Central European Standard Time
StandardName               : Central European Standard Time
DaylightName               : Central European Summer Time
BaseUtcOffset              : 01:00:00
SupportsDaylightSavingTime : True

@adamdriscoll i suppose this is the desired effect.

**Comment by adamdriscoll** [comment]
I'll add the tzdata package to our docker file for the next release. I'll add the tidbit about setting the ENV TZ to our docs.
