### ISSUE TITLE
Windows Performance Counters

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/powershell-universal#598]
For those of us utilising PowerShell Universal on Windows Server instances that are monitored by a traditional monitoring solution, it would be useful if PSU performance metrics were exposed as Windows Performance Counters so it can be picked up by numerous monitoring suites that can utilise these counters.

Some examples of things to track:
- Requests Per Second against API Endpoint (Counter Instance Per Endpoint plus a `_Total`)
- Average Request Fulfilment Time Per Minute against API Endpoint (Counter Instance Per Endpoint plus a `_Total`)
- Concurrent Dashboard Connections (Counter Instance Per Dashboard plus a `_Total`)
- Thread Counts
- Errors Per Minute/Time-Period (Could be broken down numerous ways)
- Any Available PowerShell SDK Runspace Performance Metrics

https://stackoverflow.com/questions/38124196/what-is-the-story-of-performance-counters-for-net-core
https://www.nuget.org/packages/System.Diagnostics.PerformanceCounter/

**Comment by adamdriscoll** [comment]
We've implemented some of these: 

- API Requests per second
- API Execution Time (Fulfilment time)
- API Active Endpoints
- Dashboard Active Connections

For process specific items, you can use the dotnet-counters global tool: https://learn.microsoft.com/en-us/dotnet/core/diagnostics/dotnet-counters

I'm not aware of performance counters directly in PowerShell but I'd be a bit surprised if those don't exist.

**Comment by potatoqualitee** [comment]
dbatools has a bunch of commands that support Performance Counters, can't say i love the design of the commands but I did add them along with Microsoft PAL which can be imported using `Import-DbaPfDataCollectorSetTemplate`.


```
Name                                
----                                
Add-DbaPfDataCollectorCounter       
Export-DbaPfDataCollectorSetTemplate
Get-DbaPfAvailableCounter           
Get-DbaPfDataCollector              
Get-DbaPfDataCollectorCounter       
Get-DbaPfDataCollectorCounterSample 
Get-DbaPfDataCollectorSet           
Get-DbaPfDataCollectorSetTemplate   
Import-DbaPfDataCollectorSetTemplate
Invoke-DbaPfRelog                   
Remove-DbaPfDataCollectorCounter    
Remove-DbaPfDataCollectorSet        
Start-DbaPfDataCollectorSet         
Stop-DbaPfDataCollectorSet          
```
