### ISSUE TITLE
Ability to Parse Param() from external functions in endpoints.ps1

### ISSUE THREAD

**Issue by jdkang** [ironmansoftware/powershell-universal#606]
**Is your feature request related to a problem? Please describe.**
We keep our primary functions in scripts/modules which get dot-sourced into `endpoints.ps1`. This is in order to make testing of the these functions easier without having to try to mock PSU's endpoint cmdlets. 

It also reduces the size of the current monolith `endpoints.ps1`.

Unfortunately, PSU seem to parse (perhaps with AST?) the `param()` blocks in `endpoints.ps1` to provide feedback.

**Describe the solution you'd like**
Support some kind of way to hint that PSU should pull the param() block from an external function

**Describe alternatives you've considered**
If PSU supported alternative to the monolith `endpoints.ps1` (e.g. `endpoints.d/*.ps1`) this would at least alleviate the huge file issue though would still require redundant `param()` blocks.

**Additional context**

**Comment by Viajaz** [comment]
https://github.com/ironmansoftware/issues/issues/599
https://forums.ironmansoftware.com/t/new-psuendpoint-path/5810
https://github.com/ironmansoftware/issues/issues/600

https://github.com/ironmansoftware/universal-docs/issues/35
