### ISSUE TITLE
UDDatePicker not clearing out value

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#614]
https://forums.ironmansoftware.com/t/uddatepicker-and-clearing-out-value/5832

**Comment by dkkazak** [comment]
I'll mention that I find I can backspace over the date to clear it out, but the date will reappear.  Doing this will send a blank field when doing a submit, which works, it's just hard to know that it was cleared out or not.

**Comment by psott** [comment]
Upvote for this
