### ISSUE TITLE
Refactoring "extract function" does not work in Microsoft Visual Studio Community 2019

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/powershell-universal#617]
**Describe the bug**
Following the video on:
https://docs.poshtools.com/powershell-pro-tools-documentation/visual-studio-code/refactoring
It seems to me that when having selected some code and choosing (by mouse) "Extract function" in the bulb, an input windows should show. Giving me a chance to name the function.
But, nothing happens - no window , no message, no error - just nothing.

Same happens for "Extract to file".  
So apparently my VS does not/cannot open the input window.

Can see you are using "CTRL+ALT+R" - what is that bound to ?
It may very well be due to some missing setup of my VS - but what?

**To Reproduce**

**Expected behavior**

**Screenshots**

Version
2021.10.0

Tool (Visual Studio, VS Code, PSScriptPad, PS Module):
Microsoft Visual Studio Community 2019
Version 16.11.5
Version Number:
Operating System: Microsoft Windows [Version 10.0.19043.1288]

**Additional context**

**Logs** 

Please upload a log. Logs are found in $Env:AppData\PowerShellProTools\ by default.

**Comment by adamdriscoll** [comment]
I can reproduce this. We'll get it fixed in the next version.

**Comment by adamdriscoll** [comment]
This is partially fixed in 2021.11.0 but not totally. It will produce new files and copy the highlighted text over but not remove it from the original file. Still trying to work out why that is happening.

**Comment by pju55** [comment]
Okie - thanks for the info :-)
Good step forward.

**Comment by pju55** [comment]
Still have the problem in Visual Studio that I' not presented with a window to name the file/function. Don't know if that's what you're still looking into.
A small video attached so you can see if I'm doing something wrong.

https://user-images.githubusercontent.com/32414636/142054896-fcffba01-996a-47eb-beab-94289ddaf926.mp4
