### ISSUE TITLE
'Run As' for API Endpoints

### ISSUE THREAD

**Issue by Viajaz** [ironmansoftware/powershell-universal#620]
The ability to run API Endpoints as a different security principal would be useful to compartmentalise endpoints in the same way one does with Automation Scripts and Dashboards.

I think this would tie in well with https://github.com/ironmansoftware/issues/issues/599

@adamdriscoll

**Comment by Viajaz** [comment]
@adamdriscoll Is this on the PSU 3.0.0 Roadmap like #599?

**Comment by adamdriscoll** [comment]
This has been completed in v4.
