### ISSUE TITLE
Isolated API Endpoints

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#632]
### Summary of the new feature / enhancement

Some modules don't work well when all running within a single process (looking at you PowerCLI). There should be a way to create an isolated API endpoint. When the endpoint is called, it should start a PowerShell process and execute that endpoint. 

It will be much slower but will resolve some of the issues people are having with these types of modules.

**Comment by Viajaz** [comment]
Possibly related if you're adding to that feature:
https://github.com/ironmansoftware/issues/issues/620
https://github.com/ironmansoftware/issues/issues/599

**Comment by adamdriscoll** [comment]
You can now put endpoints in their own environments.
