### ISSUE TITLE
Pages with custom URLs can't be viewed directly

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#652]
### Steps to Reproduce

Create a page with a custom URL. Name the page "test" and the url "test-page". Clicking view page or navigating to /test-page doesnt work. Navigating within a nav bar within pages will work. 

### Expected behavior

```console
Navigation to test-page should work.
```

### Actual behavior

```console
404 is shown
```

### Environment data

PSU 2.4.1

**Comment by Viajaz** [comment]
Other problematic values:

- `page/test` results in 404
- `/page/test` results also breaks the 'View' button on `/admin/pages` as it's treated as `https://pages/test`

**Comment by adamdriscoll** [comment]
All these permutations have been fixed in 2.5.
