### ISSUE TITLE
Anonymous Script Execution

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#656]
### Summary of the new feature / enhancement

When creating pages, it's possible to create a page that doesn't require auth but includes a form that calls a script. Executing the form won't work because it requires authentication. 

It should be possible to execute a script without authentication if the user decides to configure it that way.

**Comment by joshooaj** [comment]
I was just playing with PowerShell universal and ran into the same roadblock. I'm really new to the platform though so it's entirely possible I'm not thinking about using it the way it's intended.

My goal was to have an unauthenticated page where users could see a report in a table, populated by a script that is running in the background on a schedule.

**Comment by adamdriscoll** [comment]
This is one of the "duh" moments for me in terms of product design. Kinda missed an obvious use-case people would want to use.  This is certainly something we'll implement in 2.6. It only makes sense this should be possible and I'm a bit unhappy that it's not super straight forward in the product when you use a script in an unauthenticated page.

**Comment by joshooaj** [comment]
No worries, you've been busy building this out and doing a fantastic job. I'm looking forward to building some samples out on this platform and seeing what our customers/partners think of it :)
