### ISSUE TITLE
New-PSUEndpoint with `-Method 'POST'` fails to serialize/deserialize variables depending on input

### ISSUE THREAD

**Issue by djpbessems** [ironmansoftware/powershell-universal#660]
### Steps to Reproduce

Assuming the following endpoint:
```
New-PSUEndpoint -Url '/foo/:bar' -Method POST -Endpoint {
    Param(
        [Parameter(Mandatory)]
        $varA,
        $varB
    )

    $Bar
    $varA
    $varB
}
```

This works when it is called with the following command:
```
(Invoke-WebRequest -Uri http://localhost:5000/foo/woot -Method Post -Body @{VarA = 'valueA'; VarB = 'valueB'} -UseBasicParsing).RawContent
```
Output:
```
["woot","valueA","valueB"]
```

However, when calling it with serialized content (which works correctly when not using a `Param` block, btw):
```
(Invoke-WebRequest -Uri http://localhost:5000/foo/woot -Method Post -Body (@{VarA = 'valueA'; VarB = 'valueB'}|ConvertTo-Json) -UseBasicParsing).RawContent
```
Output:
```
[]
```

### Expected behavior

```console
I'm not sure, but I would expect to at the very least get the value for `:bar` to still be populated
```

### Actual behavior

```console
See earlier description.
```

### Environment data

Version Number: 2.4.1

**Comment by djpbessems** [comment]
Actually, thinking about it a bit more; I'd expect a `400 Invalid Data` response instead; since the required parameter `VarA` could not be interpreted from the provided Data/Body
(Unless the Data/Body *should* be allowed to be JSON)

**Comment by adamdriscoll** [comment]
If you enable -ErrorAction Stop on the endpoint in endpoints.ps1, you'll see errors. We suppress them by default. As for the serialized data, we are looking to enhance this in the future. The idea would be that if the endpoint receives JSON, it will take the top-level key\value pairs and assign them to the parameters automatically. Param blocks only work with form data at the moment. 

For using JSON, you'll have to get rid of the param block and use the $Body variable instead. 

$Body | ConvertFrom-Json

**Comment by adamdriscoll** [comment]
Didn't mean to close...

**Comment by djpbessems** [comment]
Not using the Param block is probably undesirable; since it allows all kinds of nasty tampering by the calling party.

For now I know to avoid submitting JSON and I can instruct my endusers; but it would make sense to have PSU do magic to accept both forms of input :)
