### ISSUE TITLE
Possibly unexpected behaviour New-PSUEndpoint when using `Param` block

### ISSUE THREAD

**Issue by djpbessems** [ironmansoftware/powershell-universal#661]
### Steps to Reproduce

Assuming the following endpoint:
```
New-PSUEndpoint -Url '/foo/:bar' -Method POST -Endpoint {
    Param(
        [Parameter(Mandatory)]
        $varA,
        $varB
    )

    $Bar
    $varA
    $varB
}
```

When trying to call this endpoint with non-declared variables (in the `Param` block):
```
(Invoke-WebRequest -Uri http://localhost:5000/foo/woot -Method Post -Body @{BogusVar = 'ignoreme'; VarA = 'valueA'} -UseBasicParsing).RawContent
```

### Expected behavior

Either the bogus variable should be ignored and the output should be:
```
["woot","valueA"]
```
Or the request should be denied entirely with a `400 Invalid Data` response

### Actual behavior

The output is
```
[]
```

### Environment data

Version: 2.4.1

**Comment by adamdriscoll** [comment]
This is unexpected. Try turn on -ErrorAction Stop in the Endpoint.ps1 to see what error is being returned. I would have expected this to work.

**Comment by djpbessems** [comment]
Just tested with `-ErrorAction Stop`; then it behaves in a better predictable way (Response `400`) :)

Feel free to close; but I can imagine that you would want to make these kind of errors stopping errors by default; in which case this is technically an actual bug :)
