### ISSUE TITLE
`New-PSUEndpoint` returns unexpected output when using a `ValidateSet` with invalid data (that could not be validated)

### ISSUE THREAD

**Issue by djpbessems** [ironmansoftware/powershell-universal#663]
### Steps to Reproduce

Assuming the following endpoint:
```
New-PSUEndpoint -Url '/foo' -Method POST -Endpoint {
    Param(
        [Parameter(Mandatory)]
        [ValidateSet('foo','bar')]
        $varA
    )

    $varA
}
```
When trying to call this endpoint with an invalid value for the declared (in the Param block) parameter:
```
(Invoke-WebRequest -Uri http://localhost:5000/foo -Method Post -Body @{VarA = 'invalid'} -UseBasicParsing).RawContent
```

### Expected behavior

```console
This should result in a `400 Invalid Data` response.
```

### Actual behavior

```console
It returns a `200` response with Content: `[]`
```

### Environment data

Version: 2.4.1

**Comment by adamdriscoll** [comment]
Similar to the other issues, this is because we suppress errors by default. We suppress errors by default mostly because of historical reasons as APIs have always done this. They actually used to return a 200 with an error message in there 😭I think there is a case for changing this in 3.0 as lot's of people run into this.

**Comment by djpbessems** [comment]
Ah, good to know. 

I'll add `-ErrorAction Stop` to all my endpoints; just tested that and it behaves in a better predictable way :)

Feel free to close; but I can imagine that you would want to make these kind of errors stopping errors by default; in which case this is technically an actual bug :)

**Comment by adamdriscoll** [comment]
I moved it into the v3 milestone because I agree with that. It's just a breaking change so we need to wait for a major version.
