### ISSUE TITLE
new-PSUScript -scriptblock generate a 500 code exception

### ISSUE THREAD

**Issue by rjvrijn** [ironmansoftware/powershell-universal#668]
### Steps to Reproduce

When trying to add a script using new-PSUScript with a scriptblock an *internal server error - 500* is thrown. 

After connect-PSUServer with a valid token the following I fired the following command:

```new-PSUScript -computername localhost -name testscript.ps1 -scriptblock {write-output "hello"}```
After that, The line 'New-PSUScript -Name "testscript.ps1" -InformationAction "Continue"' is added to settings/configuration/script.ps1, but the script is not visible in the automation/script section

**The expected behavior is:**
No exception is generated and script is added to the automation/scripts section

### Expected behavior

```console
new-PSUScript -computername localhost -name testscript.ps1 -scriptblock {write-output "hello"} doesn't generate an exception and script is added to the automation/scripts section.
```

### Actual behavior

```console
Exception New-PSUScript: Call failed with status code 500 (Internal Server Error): POST http://localhost:5000/api/v1/script is thrown and the script is not added to the automation/scripts section.
```

### Environment data

Universal: 2.4.1 (and 2.5.0)

Windows/Powershell core:
PSVersion                      7.1.5
PSEdition                      Core
GitCommitId                    7.1.5
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Windows/Powershell 5.1
PSVersion                      5.1.19041.1151
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1151
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by adamdriscoll** [comment]
This was actually resolved in 2.5.1.

**Comment by rjvrijn** [comment]
Hi Adam,

Are you sure this issue is solved? I’m still getting the error in version 2.5.3 and even in 2.6.0 nightly. I’m using the Powershell module version 2.5.3.

The log shows an entry beginning with:

[10:28:09 WRN] No exception handler was found, rethrowing original exception.
[10:28:09 ERR] Connection id "0HMD5NQ96QQ5S", Request id "0HMD5NQ96QQ5S:00000003": An unhandled exception was thrown by
the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at UniversalAutomation.Services.ConfigurationScript`1.GetItemPath(String path, String basePath) in D:\a\universal\uni
versal\src\UniversalAutomation\Services\Configuration\ConfigurationScript.cs:line 271
   at UniversalAutomation.Services.ScriptsConfigurationScript.OnWriteAfterAsync(Script script) in D:\a\universal\univers
al\src\UniversalAutomation\Services\Configuration\Scripts.cs:line 62
…

Greetings,

René van Rijn

**Comment by adamdriscoll** [comment]
I just tried this in 2.5.3 and it is working for me. 

New-PSUScript -Name 'ApiScript.ps1' -AppToken 'token' -ScriptBlock { "Hello" }

This results in the script being created successfully. I'm calling this from an API to test.

**Comment by rjvrijn** [comment]
Hi Adam,

Found it! The exception is generated only when called from Powershell version: 5.1.19041.1237. When new-psuscript is called from PS Core (in my case 7.1.5), the script is indeed created succesfully.

Hope you can reproduce this in your environment too, or else this issue gona cost me some sleepinghours. ;)

Greetings,

René van Rijn

**Comment by rjvrijn** [comment]
Did a little further testing and I’m not able to generate this error anymore. Had restarted my environment though, so I guess my Powershell session was someway corrupt. A situation that I’m should be aware off. Sorry for the confusion. :flushed:

Keep up the good work. :+1: :smiley:

René van Rijn
