### ISSUE TITLE
Consider pushing PSU & ProTools to the Microsoft Community Repository being part of your release pipeline 

### ISSUE THREAD

**Issue by apetitjean** [ironmansoftware/powershell-universal#68]
It would be nice if you could consider pushing your binaries to the Microsoft Community Repository anytime you release a new version of your awesome tools ;-).

Doing so would ease your product's installation using **Winget** which is becoming the new Microsoft way to install software.

I noticed there is PSU version 1.4. So please consider an update.

**Comment by adamdriscoll** [comment]
Good idea. I will make sure to update this. I haven't been keeping up with the WinGet repo.

**Comment by adamdriscoll** [comment]
https://techcommunity.microsoft.com/t5/educator-developer-blog/wingetcreate-keeping-winget-packages-up-to-date/ba-p/4037598

**Comment by adamdriscoll** [comment]
https://github.com/microsoft/winget-pkgs/pull/148690
