### ISSUE TITLE
After set-psusetting "Starting groom job" is triggered every minute.

### ISSUE THREAD

**Issue by rjvrijn** [ironmansoftware/powershell-universal#682]
### Steps to Reproduce

After using Set-PSUSetting (any setting), the the groom process runs every minute

```powershell
Set-PSUSetting -LogLevel Information
```

### Expected behavior

```console
Perhaps the groom job is as designed, but I expected a possibility to change or stop this behavior. At least there is a difference in a plain (working) installation and a installation you'd tried to change with set-PSUSetting. ;)
```

### Actual behavior

```console
A plain install of Universal does not run or log a groom process. After using...


Set-PSUSetting -LogLevel Information


the groom process runs and create groom log entries every minute.
```

### Environment data

Universal: 2.4.1

Powershell 5.1 and PS Core:

PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Micro
Platform                       Win32
PSCompatibleVersions           {1.0,
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0
WSManStackVersion              3.0

PSVersion                      5.1.14393.4583
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.4583
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by rjvrijn** [comment]
Oh, and the date of the log entries are logged 1 month and 1 hour in the past. Although the 1 hour difference is possible caused due regional settings. ;)

**Comment by adamdriscoll** [comment]
The fact that the groom job is running every minute is by design. The log message is logging the date beyond which we start to groom jobs so it makes sense it's a month in the past. 

What isn't really by design is changing the settings causing the log messages to start showing up.

**Comment by rjvrijn** [comment]
> On 9 Nov 2021, at 19:04, Adam Driscoll ***@***.***> wrote:
> 
> 
> The fact that the groom job is running every minute is by design. The log message is logging the date beyond which we start to groom jobs so it makes sense it's a month in the past.
> 
> What isn't really by design is changing the settings causing the log messages to start showing up.

Ah, Thank you Adam! 

I thought this was not totally unexpected, but still there is a little strange behavior. I hoop II could help a little on this one. ;)

Greetings,

René van Rijn

**Comment by adamdriscoll** [comment]
We've changed this behavior and you can set the groom interval in settings. 

![image](https://user-images.githubusercontent.com/1256531/213377517-70ae8053-e9d5-4ac2-969b-9672a126f19a.png)
