### ISSUE TITLE
OIDC SaveTokens - UI Errors in 2.5.1 Nightly

### ISSUE THREAD

**Issue by insomniacc** [ironmansoftware/powershell-universal#684]
### Steps to Reproduce

When using OIDC with savetoken enabled in the new 2.5.1 nightly, the generated code in authentication.ps1 for the UI controls causes errors to be thrown. Seems that -SaveTokens is being added as a switch rather than a boolean. Adding $true manually clears the issue.

### Expected behavior

```console
N/A
```

### Actual behavior

```console
N/A
```

### Environment data

PSU 2.5.1 Nightly
IIS
OCID Auth with savetokens enabled

### Visuals

![image](https://user-images.githubusercontent.com/10046621/141020374-e0d03a5c-a95c-422d-9c2c-6ed24afe913d.png)

**Comment by insomniacc** [comment]
Just logged in this morning and spotted the same for parameter UseTokenLifetime:
![image](https://user-images.githubusercontent.com/10046621/141063478-f4bde8f2-3448-4d66-8b11-8c1a00c77378.png)

**Comment by adamdriscoll** [comment]
Fixed in the 2.5.2 nightly.
