### ISSUE TITLE
Transitions not working properly anymore

### ISSUE THREAD

**Issue by donlent** [ironmansoftware/powershell-universal#694]
### Steps to Reproduce

Take the docs sample
https://docs.powershelluniversal.com/userinterfaces/dashboards/components/utilities/transitions

### Expected behavior

```console
Normally when using an UDSwitch in combo with transitions you should be able to transition components in and out.
```

### Actual behavior

```console
Components only transition in. not out anymore.
```

### Environment data

PSU 2.5.0

### Visuals

![transition](https://user-images.githubusercontent.com/11975745/141287485-0180ad6d-c438-4544-9d91-3bc5275aa66d.gif)

**Comment by adamdriscoll** [comment]
Definitely a bug but it looks like you can work around it by using $Body. 

```
New-UDTransition -Id 'test' -Content {
    New-UDCard -Text "Hey"
} -In -Fade -Timeout 1000

New-UDSwitch -OnChange {
    Set-UDElement -Id 'test' -Properties @{
        in = $Body -eq 'True'
    }
} -Checked $true
```

**Comment by donlent** [comment]
Thanks a lot mate! As always your help is really much appreciated! :-D

Best regards,
Don
