### ISSUE TITLE
New-UDCardMedia control parameters

### ISSUE THREAD

**Issue by insomniacc** [ironmansoftware/powershell-universal#695]
### Summary of the new feature / enhancement

It would be good to have the following parameters on New-UDCardMedia:
```
[switch]$autoplay (note that muted is also required for autoplay to work)
[switch]$muted
[switch]$loop 
[Boolean]ShowControls (Defaulted to $true)
```

I'm currently working around this using the following instead of the New-UDCardMedia function:
`New-UdHtml -Markup '<video width="500" autoplay muted loop><source src="./video/shot.mp4" type="video/mp4"></video>'`
This hides the controls, starts the video, and loops.

**Comment by adamdriscoll** [comment]
The MUI component doesn't support these parameters so I think we won't be implementing them.
