### ISSUE TITLE
Docker container switches between relative and absolute paths

### ISSUE THREAD

**Issue by Atreidae** [ironmansoftware/powershell-universal#7]
#### Description

Universal docker container switches between relative and absolute paths when configured as per the example.

Using the example docker file enviroment variables like "UniversalDashboard__AssetsFolder" are set to a relative path "./data/UniversalDashboard"
Source: https://docs.ironmansoftware.com/get-started/getting-started/docker

This causes the docker image to randomly switch between absolute and relative paths 

![image](https://user-images.githubusercontent.com/8736291/109227856-182a3e00-7815-11eb-9497-ef226edaabc3.png)

#### Additional Information

Hi all,
I tried chatting about this on Discord but got crickets.
I'm trying to chase down an issue with modules loading and found this during my troubleshooting.

![image](https://user-images.githubusercontent.com/8736291/109227856-182a3e00-7815-11eb-9497-ef226edaabc3.png)

This also appears to cause PSU to try and import a folder as a module
![image](https://user-images.githubusercontent.com/8736291/109227935-34c67600-7815-11eb-80d9-773fcbf784bd.png)

if I remove the preceeding dot from the components path, all the paths are now the same format 
![image](https://user-images.githubusercontent.com/8736291/109228031-5fb0ca00-7815-11eb-89d4-5d23a2c32010.png)

I'm still investigating why the modules wont autoload, they work fine if I specify the full path. Thats something I'll raise in another issue.

More info over on Discord.
https://discord.com/channels/785398709239545856/785406543025537024/812852387235627068

#### Version Information

- Universal: 1.5.13
- Universal Hosting Method (IIS, Executable, docker etc): Docker on Synology NAS
- PowerShell: Any
- Operating System: DSM

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
This is just a display issue and shouldn't be the original problem. If you experience issues on the latest version, please let me know.
