### ISSUE TITLE
Endpoint stats

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#705]
### Summary of the new feature / enhancement

Some basic endpoint stats would be nice. 

Average execution time
Number of executions
Number of endpoints currently running
Etc

**Comment by Viajaz** [comment]
@adamdriscoll Some additional ideas are also in #598

**Comment by adamdriscoll** [comment]
This has been implemented as performance counters

**Comment by adamdriscoll** [comment]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/1256531/192356487-af3ec949-3883-4d2b-9624-acef523974ba.png">
