### ISSUE TITLE
new-psuvariable -type PSCredential generate a var with status "Missing Secret" 

### ISSUE THREAD

**Issue by rjvrijn** [ironmansoftware/powershell-universal#712]
### Steps to Reproduce

**issue**
Adding a secret variable using new-PSUVariable does create the variable but its value is empty. A message "The secret *variablename* was not found." is logged in the logfile.

```powershell
$cred = [pscredential]::new('MyUsr',((“MyPWD" | ConvertTo-SecureString -AsPlainText -Force | ConvertFrom-SecureString) | ConvertTo-SecureString))  # or $cred = get-credential

New-PSUVariable -name newvar -Type PSCredential -Vault BuiltInLocalVault -Value $cred
```
>This behavior can be repeated on the same variable (after removing it :wink: ) until the following workaround is used

**workarround**
- Create the secret variable from within the GUI manually or
- edit the secret variable in the GUI by clicking on "set secret value"

>After this manual action you can again repeating the steps above but with that difference the secret variable is created succesfully. This workaround does work even after restarting the universal process

I looks like this problem is introduced in version 2.5.4, but I didn't test this very well in older versions.

I discovered this behavior when trying to get info for another secret variable issue when creating a secret pointing to an invalid vault. Perhaps I'll create a separate issue for that later. 

### Expected behavior

```console
The secret variable is created in all scenario's without a problem, e.g. same behavior as in the GUI.
```

### Actual behavior

```console
An empty secret variable is created, or the value could not be resolved.
```

### Environment data

Powershell Universal 2.5.4

Powershell 5.1 and Powershell Core 7.1.0

**Comment by adamdriscoll** [comment]
We have fixed this by including a -Credential parameter to New-PSUVariable. The problem is that the -Value parameter is a String and will not work with PSCredential. 

```
            $Password = "password" | ConvertTo-SecureString -AsPlainText -Force
            $PSCredential = [PSCredential]::new("user", $Password)
            $Variable = New-PSUVariable -Name "Credential" -Credential $PSCredential -Vault 'BuiltInVault'
```

**Comment by rjvrijn** [comment]
Thanks Adam,

I understand this approach. What i don't get is that after adding the
secret in the GUI the secret can be created without any problem with the
-value parameter from new-psuvariable. I think it would be a nice
enhancement to support multiple object types, or at least the pscredential
object, for the value parameter. But that is for another day. Or not. Love
your work. Thanks!

René

Op do 18 nov. 2021 16:18 schreef Adam Driscoll ***@***.***>:

**Comment by adamdriscoll** [comment]
The issue is that in the admin console, we are calling the API in a way that creates the credential as part of the API call. 

That said, I think you're right that maybe we just update the -value parameter to support multiple types. I think I'll do that. Remove what I just added with -Credential and then have -Value accept object and check Object type.

**Comment by rjvrijn** [comment]
Wow cool! Sounds as a plan. :)

René

Op do 18 nov. 2021 17:47 schreef Adam Driscoll ***@***.***>:
