### ISSUE TITLE
Script user role

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#72]
Hi,
I think many other are missing this also, I want a Script user role that can handle everything with the scripts, change, schedule etc. and nothing else.

Today the Execute has to low permissions as it can't schedule a job and the Operator has to high permissions instead as they can enable or disable auth for the Dashboards etc.

**Comment by adamdriscoll** [comment]
Replaced by: https://github.com/ironmansoftware/issues/issues/98
