### ISSUE TITLE
Secret marked as does not exist when it exists

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#727]
### Steps to Reproduce

https://forums.ironmansoftware.com/t/this-secret-does-not-exist-in-the-vault/6022/2

### Expected behavior

```console
Secret should correctly show if it exists
```

### Actual behavior

```console
Secret shows that it does not exist but does work for starting jobs
```

### Environment data

PSU 2.5.4

**Comment by mabster** [comment]
Turns out the warning was correct - the secrets are not persisting across restarts in an Azure Web App. :(

**Comment by adamdriscoll** [comment]
We are adding support for the new secret management module in 2.6 so you should be able to use AZ Key Vault.
