### ISSUE TITLE
Notification when PSU has updates?

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#740]
Hi,
Sometimes you do .x updates and that's great but as it's outside the update cycle I'm wondering if it's possible for you to create RSS feed or similar so we can get notification when you release them?

**Comment by adamdriscoll** [comment]
Sure. I can get that implemented. You should be seeing update notifications within the application admin console as well.

**Comment by rwidmark** [comment]
> Sure. I can get that implemented. You should be seeing update notifications within the application admin console as well. 

Yes I do, but my thought was that your release site should have rss support.

**Comment by Viajaz** [comment]
@adamdriscoll Was RSS/Atom support for software updates ever added to the website?

**Comment by adamdriscoll** [comment]
@Viajaz - You can subscribe to this RSS feed: https://forums.ironmansoftware.com/c/powershell-universal/releases-of-powershell-universal/23.rss

We now post all updates to the Forums.
