### ISSUE TITLE
Variables in parameter default values aren't interpreted

### ISSUE THREAD

**Issue by jantari** [ironmansoftware/powershell-universal#746]
### Steps to Reproduce

Create a script with a param block such as:

```powershell
[CmdletBinding()]
Param (
    [string]$OutputPath = "${env:USERPROFILE}"
)
```

and add it to the Autmation scripts.

### Expected behavior

```console
When running such a script in the normal PowerShell console, a runspace or other automation solutions the variable is properly interpolated and substituted for its value when the script is run.

`$OutputPath` should contain a valid filesystem path when the script is running.
```

### Actual behavior

```console
In PowerShell Universal 2.5.5 the value '${env:USERPROFILE}' is passed verbatim, the variable is not recognized and not substituted.

Subsequently the PowerShell script fails because of invalid paths.
```

### Environment data

Version Number: 2.5.5
Framework: Kestrel, running Universal.Server.exe from the downloaded ZIP
OS: Windows Server 2019 Core 10.0.17763.2300

### Visuals

The parameter value shows up in the UI like this: 
![image](https://user-images.githubusercontent.com/25607767/143897453-03c748a0-24f8-457b-af6e-82c2b8d8849a.png)

which is correct IMO, the content of the variable is not known until the script is run. But it should be interpreted instead of passed verbatim.

**Comment by adamdriscoll** [comment]
This has been implemented in more recent versions.
