### ISSUE TITLE
Transitions don't work

### ISSUE THREAD

**Issue by kireener** [ironmansoftware/powershell-universal#752]
### Steps to Reproduce

Problem with in and out in transitions. Ex. the code from the docs:

`New-UDTransition -Id 'test' -Content {
    New-UDCard -Text "Hey"
} -In -Fade -Timeout 1000
New-UDSwitch -OnChange {
    Set-UDElement -Id 'test' -Properties @{
        in = $EventData -eq 'True'
    }
} -Checked $true`

### Expected behavior

```console
Transion element would do a transition, ie. fade, collapse etc.
```

### Actual behavior

```console
No transition
```

### Environment data

Version: 2.5.4 and 2.5.5. Operating system: Windows

**Comment by adamdriscoll** [comment]
I can reproduce this. Looks like something changed in the $EVentData variable where it is actually an array. 

Work around: 

```powershell
New-UDTransition -Id 'test' -Content { New-UDCard -Text "Hey" } -In -Fade -Timeout 1000 
New-UDSwitch -OnChange { Set-UDElement -Id 'test' -Properties @{ in = $EventData[0] } } -Checked $true
```
