### ISSUE TITLE
Enable table pagination options for top/bottom/both -not just bottom - on New-UDTable

### ISSUE THREAD

**Issue by IanEMartin** [ironmansoftware/powershell-universal#754]
### Summary of the new feature / enhancement

As a user - I would like to be able to have the option on New-UDTable command for the -ShowPagination parameter to have an option to show on either the top or the bottom or both.

Currently it only shows on the bottom.

**Comment by adamdriscoll** [comment]
We've added -PaginationLocation to New-UDTable that accepts top, bottom and both. It defaults to bottom
