### ISSUE TITLE
frontail integration

### ISSUE THREAD

**Issue by kamilkosek** [ironmansoftware/powershell-universal#766]
### Summary of the new feature / enhancement

Currently there are two (or even more) ways to review PSU logs

1. Download logs directly from PSU, unzip them and review them
2. Log on to the machine where PSU is running and open the desired log file with whatever tool you like.

In the customers environment where we are implementing PSU, only option `1` is possible, because of policies. 

It would be a real time saver if some kind of "live log stream to the browser" could be implemented. 

### Proposed technical implementation details (optional)

Technically what I´m talking about is  [Frontail](https://github.com/mthenw/frontail). 
Im not a dev and mostly don´t know what I´m talking about :D but I think the hardest part would be to integrate the authentication/authorization so only the Administartors or "LogReview"-Role-Holders are able to open it. 

Then once it´s implemented, there would be just a link from the admin console i.e. under
`Settings -> Live-Log`

**Comment by adamdriscoll** [comment]
We've added a live log view to the Settings \ General \ Diagnostics page.
