### ISSUE TITLE
Unauthorized page is not working from dashboard

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#767]
### Steps to Reproduce

https://forums.ironmansoftware.com/t/i-dont-get-the-unauthorized-page/6268/2

### Expected behavior

```console
Unauthorized page is shown
```

### Actual behavior

```console
404 error is shown
```

### Environment data

PSU 2.5.5

**Comment by mwatts-seg** [comment]
@adamdriscoll  - Hello! I know you are very busy, will the fix be in 3.1?

**Comment by adamdriscoll** [comment]
@mwatts-segops  - This will be fixed!
