### ISSUE TITLE
Multi-lingual support for dashboards

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#776]
### Summary of the new feature / enhancement

We should detect the user's language and allow users to customize text for it. We should also provide a drop down to select a language.

**Comment by donlent** [comment]
Dear @adamdriscoll 
Any plans for a future implementation for that?
Currently (as probably most of us) I'm coding everyting in English. Most of the time this is fine but as soon as you want to go with a Dashboard or a Page out to the user which maybe only speaks another language (in our case German and/or French) then it becomes a problem. :-)

So it would be really cool if we had a simple solution to create language files / xmls or whatever to store the language strings that are dynamically retrieved based on the user's choice and/or browser locale.

Thanks a lot!

**Comment by adamdriscoll** [comment]
I'm trying to best figure out how to implement. At the moment, it seems like something that would be pretty easy to handle with a function yourself so I want to make sure that whatever is provided is of some benefit. 

For example, I've been messing with a Get-LanguageDictionary function. I just defined a couple hashtables with strings and then check the language provided by the client. In my dashboard, I can just call Get-LangaugeDictionary and it will automatically load the proper dictionary based on the user's browser headers. 

```


function Get-LanguageDictionary {
    $en = @{
        "Hello" = "Hello, World!"
    }

    $de = @{
        "Hello" = "Hallo Welt"
    }

    if ($Headers["Accept-Language"] -match 'en')
    {
        $en 
    }
    elseif ($Headers["Accept-Language"] -match 'de')
    {
        $de
    }
}


New-UDDashboard -Title "Hello, World!?" -Content {
    $Dictionary = Get-LanguageDictionary
    New-UDTypography $Dictionary.Hello
}
```

Is there anything else you think would be necessary from something like this? What should PSU provide in this regard? I'm just trying to think of the best possible API that we can provide. I think you could provide the hashtables for strings and we could do the language selection based on the headers.

**Comment by augiaugi** [comment]
Hi, I am just posting some notes that came in my mind after reading this:

- there should be a "default" in your function (e.g. undefined language)
- an more automated way could be very helpful and cleaner in code (e.g. replace all <<welcome>> text in code (for hardcoded stuff) or even in variables) - this can be dangerous, or result in unexpected behaviours, but would be very easy to use and understand. For example define the language translation list in New-UdDashboard scope
- handling the dictionary in code or as a file (e.g. json). I am not familiar with translation or multilingual frameworks, but there should be an existing format

**Comment by donlent** [comment]
Hi Adam
First of all thanks for taking care of this!

Here are also my thoughts:

- Like mentioned above I also agree that the LanguageDictionary should be filebased (JSON sound good to me as well) and stored somewhere on the PSU Server Repo
- NICE TO HAVE: It would be very neat to have a UI Integration in the PSU Admin Interface for the Dictionary definitions. Something like a mapping table for each Language. Then in-code you can just refer to the PSU internal variables that contain the language values.
- Even if reading the $Header is great to make it more seamless for the user, I think that the user should have as well the possibility to change the language. You should then save its choice inside a cookie.
- Like mentioned above there should be a default language definition... sort of a fallback mechanism...

If I'll have some more ideas I'll post them.

Thanks again,
Don

**Comment by adamdriscoll** [comment]
In the UI, you will be able to define languages files and set keys to strings. In code, (APIs and Dashbaords), you will be able to use the `$t` provider (similar to react-localization) to access the strings. The localized string will automatically be returned. 

For example, the localization interface looks like this .

![image](https://user-images.githubusercontent.com/1256531/177060625-a90e6d06-5d06-4217-8e4a-234677273d2a.png)

It produces files like this. 

```
$Parameters = @{
	LanguageId = "en"
	Strings = @{
		String1 = 'asfsdafafa'
		String3 = 'asdfasdfas'
	}
}
New-PSUTranslation @Parameters
```

Within APIs or Dashboards, you can use the translation provider. 

```
New-UDDashboard -Content {
   New-UDTypograhpy $T:String1
}
```

We look at the `Accept-Language` header to select the proper string. You can set the fallback language in the settings.

**Comment by donlent** [comment]
Thanks a lot Adam! Your support and commitment is just outstanding!
THANKS! 😃👍

**Comment by ad-85** [comment]
So happy this feature is being added! Already writing the strings hashtable for French support ⚜️

Thanks Adam
