### ISSUE TITLE
UDTable sort is case sensitive

### ISSUE THREAD

**Issue by molson98** [ironmansoftware/powershell-universal#8]
#### Description

When sorting in UDTable if it is ascending upper case is first and if Descending it is lower case first. I am not sure if this is by design, but I cannot find a way to make it case insensitive.

#### Version Information

- Universal: 1.5.13
- Hosted by executable
- PowerShell: 7.1.1
- Operating System: Windows Server 2016

#### Internal Issue

We'll fill this out when we create an internal issue in our repository.

**Comment by adamdriscoll** [comment]
Fixed in 1.5.15
