### ISSUE TITLE
ANSI Escape Sequences do not work in the PowerShell Interactive window

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#800]
PowerShell interactive window does not display ANSI escape sequences as colors but literally. It makes the console difficult to read. 

2021.12.2

https://forums.ironmansoftware.com/t/powershell-interactive-window-not-working-as-expected/6349/2

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/powershell-interactive-window-not-working-as-expected/6349/3

**Comment by KyleKolander** [comment]
![Ansi Escape Sequences](https://user-images.githubusercontent.com/22461822/147294072-cf91fc3d-fc6e-4287-b304-cee9f1f70b7e.gif)

**Comment by KyleKolander** [comment]
As you can see in the gif, it is displayed incorrectly in the Output window as well.
