### ISSUE TITLE
Visual Studio Hangs when switching to Windows PowerShell

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#802]
When switching from PowerShell 7 to Windows PowerShell in Visual Studio, the IDE will hang. 

VS 2021.12.2

https://forums.ironmansoftware.com/t/powershell-interactive-window-not-working-as-expected/6349/2

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/powershell-interactive-window-not-working-as-expected/6349/3

**Comment by KyleKolander** [comment]
![Switch to PowerShell 7](https://user-images.githubusercontent.com/22461822/147302714-30710096-41e0-41d7-a537-40259f6332ae.gif)

As you can see in the gif, switching to PowerShell 7 (x64) locks up VS 2022 for over 2 minutes, twice resulting in toast notifications that "Visual Studio is busy".  For reference, my machine has an AMD Ryzen 9 3900X 12-Core Processor (24 logical cores) and 64 GBs of RAM.

**Comment by KyleKolander** [comment]
![Switch to Windows PowerShell](https://user-images.githubusercontent.com/22461822/147303323-9cd751db-ef0f-4d17-8d30-d235f6ccf890.gif)

As you can see in the gif, switching to Windows PowerShell (x64) also locked up VS 2022...this time for over 3 minutes, thrice resulting in toast notifications that "Visual Studio is busy".
