### ISSUE TITLE
Table PageSizeOptions (Disable show all)

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#81]
Hi,
In the PageSizeOptions I can choose what the user can choose. example 10 or 20 per page.
But even do I do it like @(10, 20) it also show the "All" option.

It should bee great if that option don't show if you are activating the PageSizeOptions

**Comment by adamdriscoll** [comment]
This will be included in the 1.5.15 release. It will also be available in tonight's 1.6 nightly build.

**Comment by adamdriscoll** [comment]
Added in 1.5.15
