### ISSUE TITLE
Icon support for PS7 executables. 

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#813]
Forking from the original issue because file properties were easy and this is much harder. looking for a solution.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/merge-script-2022-1-0-does-not-insert-icon/6457/2

**Comment by mikeroy2k** [comment]
I'm still having issues with Icons not appearing after packaging exe. using ps 7.2.0
the unpackaged .exe in the temp folder appears fine but not after it's copied to the packaged .exe in the final version. 
I've upgraded to version 3.0 of pro tools. uninstalled and reinstalled trying to resolve another issue. 

C:\Users\USERNAME\AppData\Local\Temp\56e4f0a9f26645438019066121d4fdbc\out <-- icon appears in unpackaged .exe fine


VERBOSE: Setting file information: "S:\SHARED\USERNAME\Scripts_S_Shared\Appname\Out\appname.exe" "1.02" /va /pv "1.02" /s product "AppName" /s description "application descriptionl" /s copyright "@CompanyName"
VERBOSE:
