### ISSUE TITLE
Access Controls for Dashboards

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#816]
### Summary of the new feature / enhancement

We should implement access controls for dashboard. Allowing a user to restart a dashboard but not change the code. 

https://forums.ironmansoftware.com/t/access-controls-allow-specific-role-to-restart-dashboard/6416

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/dashboards-do-not-appear-for-permissioned-users/7252/9

**Comment by SolidOceanTrust** [comment]
Thanks @adamdriscoll !
I would vote that each top-level resource 
1. APIs
2. Automation
3. User Interfaces
4. Platform

be able to control:
* Read
* Read/Write
* Admin (Read/Write/Delete?)

Under the existing or soon-to-be extended RBAC model.

Thank you very much! I really enjoy using PSUniversal! Thank you for your hard work!!

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/kiosk-mode-for-universal/9138/2
