### ISSUE TITLE
VS Code: Upgrade publisher status to verified

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#822]
## Summary of the new feature / enhancement
It would be great if the VS Code extension publisher was upgraded to verified status

![image](https://user-images.githubusercontent.com/537287/148641637-7a70edb0-040b-43c2-a268-0a025c0ee3ab.png)
## Benefit of implementing the change
Increased trust

 
## Proposed technical implementation details (optional)
Microsoft has the below guidance ([source](https://code.visualstudio.com/api/working-with-extensions/publishing-extension))

 
```
To verify a publisher

1. Visit the Visual Studio Marketplace publisher management page.
2. Select or create a publisher you wish to verify.
3. Input an eligible domain in the Verified domain field, save, and select Verify.
4. Follow the instructions in the dialog to add a TXT record to your domain's DNS configuration.
5. Select Verify to validate that the TXT record has been successfully added.
6. Once your TXT record has been validated, the Marketplace team will review your request and grant verification within 5 business days.

Eligible domains meet the following criteria:

- Cannot be a subdomain ({subdomain}.github.io, {subdomain}.contoso.com, or similar).
- You must be able to manage the DNS configuration settings and add a TXT record.
- Your domain must use HTTPS protocol.
```

**Comment by adamdriscoll** [comment]
Waiting to hear back from Microsoft on this. Their verification process is not working.

**Comment by adamdriscoll** [comment]
It's in Microsoft's court. Not going to worry about it.
