### ISSUE TITLE
Parameter Sets for Scripts

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#831]
### Summary of the new feature / enhancement

https://forums.ironmansoftware.com/t/script-parameter-sets/6003/4

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/script-parameter-sets/6003/8

**Comment by penser-jata** [comment]
Please be aware that when importing existing scripts, you experience this as a (surprising,blocking) bug
Say you have parameters like
```
param(
    [Parameter(Position = 0, Mandatory=$True, ParameterSetName = 'FirstSet')][String]$First,
    [Parameter(ParameterSetName ='SecondSet', Mandatory = $True)] [String]$Second )

```
The intention is that you you have to specify one of the paramters, _but not both_.
However, the generated input panel _requires_ you to fill in a value for both, exactly what the script doesn't want.
