### ISSUE TITLE
Universal Automation - Per Script RBAC?

### ISSUE THREAD

**Issue by dcherry88** [ironmansoftware/powershell-universal#84]
**Is your feature request related to a problem? Please describe.**
I would like to be able to specify individual permissions per Universal Automation script.

**Describe the solution you'd like**
Would like to have the ability to grant permissions based of roles to UA scripts. We are looking to house scripts to perform different functions and jobs, and would like to be able to say one role based off AD group is allowed to execute a specific script, but maybe another AD group based role can only look at the code.

**Comment by adamdriscoll** [comment]
Replaced by: https://github.com/ironmansoftware/issues/issues/98
