### ISSUE TITLE
Improve UDSelect type searching

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#840]
### Summary of the new feature / enhancement

When using a UDSelect, the user can type to move between the list. The search stops at the first character. It should continue so you can search for multiple characters.

**Comment by rwidmark** [comment]
This is awesome! Was thinking about this the other day.
Perfect!

**Comment by adamdriscoll** [comment]
I would argue to just use an autocomplete in this circumstance.
