### ISSUE TITLE
Dashboard controls don't appear when GitSync is set to 1-Way

### ISSUE THREAD

**Issue by SimonBurrowsBD** [ironmansoftware/powershell-universal#846]
With git sync set to one way in my appsettings.json file the Admin console doesn't display dashboard controls (start/stop, details etc)

![image](https://user-images.githubusercontent.com/84912706/149342080-31ac0908-791c-4899-8aa2-6f72bff7eb12.png)

Removing the line:

` "GitSyncBehavior": "OneWay",`

from appsettings.json fixes the issue and the controls re-appear.

The Admin role is definitely applying as the logged in user can see the Security and Settings options listed on the left hand menu when in the Admin console and can browse to a dashboards details page by manually browsing to eg. /dashboards/4 but this page doesn't display controls either.

Tested on v2.6.2 and v2.7.0

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/dashboard-controls-disappeared-from-admin-console/6456/7
