### ISSUE TITLE
PS to EXE: A space in the script file name causes EXE crash

### ISSUE THREAD

**Issue by ZurekCorp** [ironmansoftware/powershell-universal#847]
**Describe the bug**
A space in the PS script file name causes EXE crashes with the error coppied down below.
The packaging/merging process passes without any error or warning.
A space in a path has no effect.

**To Reproduce**
1. Create any script and save it as test1.ps1
2. Verify if it works
3. Create EXE file - still works
4. Remove package.psd1
5. Change the name of the file test1.ps to test 1.ps
6. Create EXE file and run it

**Expected behavior**
to make it work

**Screenshots**
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: stream
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream)
   at PowerShellToolsPro.Packager.ConsoleHost.Program.Main(String[] args)

**Version**

Tools: VS Code 1.63.2, PowerShellProTools 2022.1.0, PSVersion 5.1.17763.2268
Operating System: Windows Server 2019

**Comment by adamdriscoll** [comment]
I can't reproduce this one. Here's my package.psd1

```
@{
    Root = 'c:\Users\adamr\Desktop\test 1.ps1'
    OutputPath = 'c:\Users\adamr\Desktop\out'
    Package = @{
        Enabled = $true
        Obfuscate = $false
        HideConsoleWindow = $false
        DotNetVersion = 'v4.6.2'
        FileVersion = '1.0.0'
        FileDescription = ''
        ProductName = ''
        ProductVersion = ''
        Copyright = ''
        RequireElevation = $false
        ApplicationIconPath = ''
        PackageType = 'Console'
    }
    Bundle = @{
        Enabled = $true
        Modules = $true
        # IgnoredModules = @()
    }
}
        
```

`test 1.ps1` is this. 

```
Write-Host 'hi'
```

Running the compiled executable does this. 

![image](https://user-images.githubusercontent.com/1256531/151828196-603989a6-ada0-4307-bf62-359fc01c172d.png)

I am running the same version of PS Pro Tools. Curious if you notice a difference in my script or package.psd1 versus yours.

**Comment by adamdriscoll** [comment]
I'll close this for now and if you can let me know if you are still experiencing it on the 2022.2.0 version, we can reopen and continue to investigate.
