### ISSUE TITLE
Add shortcut for the Clear Screen button

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#850]
### Summary of the new feature / enhancement

Consider adding a keyboard shortcut for the Clear Screen button of the PowerShell Interactive Window. This is in reference to bug [#25](https://github.com/ironmansoftware/issues/issues/25) 

![image](https://user-images.githubusercontent.com/537287/149639602-3132a332-f67d-41f2-a8a4-97f0a309d92a.png)

**Comment by adamdriscoll** [comment]
I've added the default Ctrl+C to clear the prompt. I also fixed #25 so you can now use cls or Clear-Screen.
