### ISSUE TITLE
Script Analyzer can be enabled when the needed module is not present

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#852]
## To Reproduce

1. Do not have the module PSScriptAnalyzer installed
2. Enable _Script Analyzer_ under Options -> PowerShell Pro Tools -> Analysis (see Screenshot 1)

## Expected behavior
```
If the module is not available, the user should be informed
```

## Actual behavior
```
The user is not informed that the ability to Analyze is not available (possibly leading to confusion)
```

## Suggestion 1
```
Prompt as Screenshot 2 if the PSScriptAnalyzer module is not available
```

## Suggestion 2
```
If it can't be detected in the menu, add a permanent static textual warning to install the module
```

## Screenshot 1
![image](https://user-images.githubusercontent.com/537287/149669143-3e77e652-c3e7-4410-b01f-5d478866578e.png)
## Screenshot 2
![image](https://user-images.githubusercontent.com/537287/149669317-898284ca-b452-4003-932b-e0d3f8c3c959.png)
## Environment Data

PowerShell Pro Tools v2022.1.0
Visual Studio 2022 Community Edition 17.0.4
Windows 10 21H2

**Comment by adamdriscoll** [comment]
I'm removing this page from the options menu and will update the documentation. These settings are now available in Tools -> PowerShell -> Settings.
