### ISSUE TITLE
Form is reset on Page after submitted

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#861]
### Steps to Reproduce

Create a page and add a form
Set output to text
Run the script
The form is reset and the user cannot see the output

### Expected behavior

```console
Form stays after it has completed running
```

### Actual behavior

```console
Form resets and output cannot be viewed
```

### Environment data

PSU 2.7.2

**Comment by adamdriscoll** [comment]
Cannot reproduce.

**Comment by adamdriscoll** [comment]
Customer is still experiencing this.

**Comment by adamdriscoll** [comment]
Reproduced this with an unauthenticated page.

**Comment by Marvin-Becker** [comment]
I just got the same issue with an authenticated page. Is there another trick or hint to fix this?
