### ISSUE TITLE
Consolidate tabs for Powershell Form projects

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#863]
### Summary of the new feature / enhancement

Consolidate the separate tabs that each form script can potentially generate into side-tabs. Each script would have only a single tab with accompanying side tabs where needed.

![image](https://user-images.githubusercontent.com/537287/150640725-cb734742-a1ad-4a0a-9ab0-da3e348a8872.png)

### Benefits of feature

Easier navigation between forms developing multi-form projects. Valuable real estate on the project task bar will have been freed up.

**Comment by DataTraveler1** [comment]
Just to clarify on the picture. It is from VS2022 with the PowerShell Pro Tools extension installed. The vertical tabs on the left side were added by me in Photoshop. The red arrows indicate where the respective tabs would be moved to.

**Comment by adamdriscoll** [comment]
This one is a bit tricky to implement because we integrate with the default VS form designer experience. It would be similar if you were using C#. I like the idea though so let's leave this open to investigate.

**Comment by adamdriscoll** [comment]
This is how the designer in VS works and we wont be implementing.
