### ISSUE TITLE
Add Working Directory property (wkdir) to New-InstallerShortcut

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#865]
### Summary of the new feature / enhancement

Add parameter to New-InstallerShortcut for specifying the [WkDir](https://docs.microsoft.com/en-us/windows/win32/msi/shortcut-table) or 'Start in' property of the shortcut.

![image](https://user-images.githubusercontent.com/537287/150695295-92fd6233-8d7e-4e3c-a91b-e66637133f58.png)

This was originally mentioned in the forums [here](https://forums.ironmansoftware.com/t/new-installershortcut-error-executing-shortcuts/1997).

### Benefits of feature

The starting context of the application can be forced.

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/new-installershortcut-error-executing-shortcuts/1997/2

**Comment by DataTraveler1** [comment]
> This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:
> 
> https://forums.ironmansoftware.com/t/new-installershortcut-error-executing-shortcuts/1997/2

Yes. That was a post from 2 years ago 🪦 which I looked into and discovered that OP was correct. The feature is indeed missing. I also bumped that forum post to acknowledge it. 

Edited: Fixed a typo

**Comment by adamdriscoll** [comment]
This works in the current version and has been documented here: https://docs.poshtools.com/powershell-pro-tools-documentation/installers#working-directory

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/new-installershortcut-error-executing-shortcuts/1997/3
