### ISSUE TITLE
PSCommander - Run script on startup 

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#87]
**Is your feature request related to a problem? Please describe.**

Want to run stuff when it's starting up. 

**Describe the solution you'd like**

Some sort of way to configure a startup script block. 

**Describe alternatives you've considered**

None. 

**Additional context**

**Comment by Windos** [comment]
This could be (from the user facing end) added to the config file as something like:

```powershell
New-CommanderStartup -Action {
    # Custom code here
}
```

Alternative names could include:

+ -CommanderOnLaunch
+ Other options that I thought of but lost before writing down

If adding this I could also see a use case for -CommanderOnExit for environment cleanup, etc.

**Comment by adamdriscoll** [comment]
I'm also kind of considering something like

```
Register-CommanderEvent -OnStartup {

} -OnExit {

} -OnError {

}
```

**Comment by adamdriscoll** [comment]
Events have been added in 1.1.0
