### ISSUE TITLE
The designer.ps1 is saved in ANSI instead of UTF-8 BOM

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#878]
### 1. Create a new PowerShell Form Project
![image](https://user-images.githubusercontent.com/537287/151045405-733a1f8c-ef06-4ac8-a4d3-b3618dbfd089.png)

### 2. Add a [menustrip](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.menustrip) to the form that has an item with a text property that contains characters not present in ANSI (e.g. Français)

![image](https://user-images.githubusercontent.com/537287/151112489-f5313779-f9ea-4335-936a-a6e37d5af9e2.png)

### 3. Run the project and observe the change in the menuitem resulting from the encoding to ANSI

![image](https://user-images.githubusercontent.com/537287/151112979-18bf37df-7967-45fb-bc7e-4edb085bfb8e.png)

## Expected behavior
```
The .ps1 designer file should be saved in UTF-8 BOM as the parent .ps1 file is
```

## Actual behavior
```
The .ps1 designer file is saved in ANSI encoding
```

## Extra
This might be appropriate to implement for the resources .ps1 file as well.

## Version

Visual Studio 2022.02
Windows 10 21H2

**Comment by adamdriscoll** [comment]
Nice catch!
