### ISSUE TITLE
GIT for components

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#88]
Hi,
It would be me great if it was possible for git sync for the component folder also.

Thanks.

**Comment by rwidmark** [comment]
> @rstolpe - Would you want that to be in a separate repository or would you like it to be somehow in the same repository and we copy it over after a git sync? 

In the same repo should bee fine.

**Comment by adamdriscoll** [comment]
You will be able to add a components folder within your git repository and these components will automatically be added during a git sync.
