### ISSUE TITLE
Create bool variable

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#887]
### Summary of the new feature / enhancement

Don't know if it's a bug that it says string in admin GUI or not but I can't create a bool variable just string even when I change the value to $true in the .ps1 file.

It would be great if it was possible to create bool variables there also.

**Comment by rwidmark** [comment]
@adamdriscoll

**Comment by adamdriscoll** [comment]
We currently only support string and secrets. We can get this added in 2.9.

**Comment by rwidmark** [comment]
> We currently only support string and secrets. We can get this added in 2.9.

Sound good, thanks.

**Comment by rwidmark** [comment]
@adamdriscoll will this be added to 2.9.0 release?

**Comment by adamdriscoll** [comment]
Yep :)
