### ISSUE TITLE
Default view for a ListView should be 'Details'

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#893]
## Background

When a ListView control is dragged onto the VS canvas, the default property of the 'View' is 'Large Icon' instead of 'Details'. This renders the column headers as invisible by default and will lead to confusion for the new user.

## Benefits of implementing this change

Less confusion for new users. With this change, the ListView becomes immediately usable which should improve the user experience.

![image](https://user-images.githubusercontent.com/537287/151732422-1a7b958d-dc0a-4b8d-bf5f-0a3733caf0b6.png)

## Version

Visual Studio 2022.02
Windows 10 21H2

**Comment by adamdriscoll** [comment]
We don't actually control this. It's provided by the VS form designer.
