### ISSUE TITLE
PowerShell Universal and DBATools Memory Leak

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#894]
### Steps to Reproduce

More information here: https://github.com/dataplat/dbatools/issues/8035

### Expected behavior

```console
No memory leak
```

### Actual behavior

```console
Memory leak when using dbatools
```

### Environment data

PSU v2.7.3

**Comment by potatoqualitee** [comment]
Thanks, bud. Following.

**Comment by adamdriscoll** [comment]
@janszedc - I have identified one issue with memory usage in PSU that was causing a big spike for me. The PowerShell engine was caching script blocks which results in high levels of memory usage for script blocks we will never reference again. I've disabled that feature in the PS engine for the integrated environment. I've also implemented a feature called runspace recycling that will dispose of runspaces after they have been used for some time. This has shown a small impact on memory as well. 

I'm still researching the issue with memory usage in dashboards. I've actually tried without dbatools at all and am seeing a higher level of memory usage than expected. I'm wondering if we were seeing high memory usage from dbatools just because it was being used but in reality, any module being used may exhibit high memory usage. 

I'm going to continue to research.

**Comment by adamdriscoll** [comment]
Also, note that these PS instances can come from implicit remoting performed by PS7. If a cmdlet exists in Windows PowerShell but not PS7, PS7 will automatically start a PS process and use it to remotely execute the command. This can cause a bunch of PS processes to open like this. I noticed this in my Azure container when attempting to execute a command that was not installed in PS7 but was installed in Windows PowerShell. 

https://github.com/dataplat/dbatools/issues/8035#issuecomment-1009981306

**Comment by DatabaseDylan** [comment]
Not sure if it helps, but memory usage spikes in dashboards appears to occur when the page loads/reloads several times. If I spam F5 or auto-deploy from the VSCode extension I can see memory go up very fast and not be released. Sync-PSUComponent doesn't seem to have this issue as much, but I guess that would make sense since an entire page reload would run ALL the code versus simply re-rendering the data in the component.

**Comment by adamdriscoll** [comment]
@janszedc - Thanks! I've made some tweaks to the way we handle event handlers in PSU that will be in tonight's 2.8 nightly build that hopefully will help reduce memory usage. If you have the ability to upgrade and test that would be great. Still continuing to research additional ways to imrpove this.

**Comment by DatabaseDylan** [comment]
Sounds good to me! I should be able to upgrade no problem (currently on
version 2.6.1 via MSI).  Are you also looking into endpoints as it seems
those also have an issue releasing memory when called repeatedly.

**Comment by adamdriscoll** [comment]
Yep. Looking into that as well. I haven't addressed that in this build.

**Comment by adamdriscoll** [comment]
I've done some additional work on the memory issue today. It's much more consistent in my lab. Tonight's nightly build will include these changes.

**Comment by DatabaseDylan** [comment]
When can I expect the nightly/daily build to be released? Sorry, not
familiar with the process. I should be able to update this week (maybe
next) once it is publicly available.

**Comment by adamdriscoll** [comment]
Nightly builds run around 5 PM UTC-7. You can download them here: https://ironmansoftware.com/release/powershell-universal-nightly

The current builds are from yesterday.

**Comment by DatabaseDylan** [comment]
@adamdriscoll  I have had some time to test on 2.8 and while memory management seems better, I am still running into the same issue. Currently a single script that makes ~100 API calls every 60 seconds is still causing memory to rise uncomfortably fast. I am using Integrated environment for my script with -RunspaceRecycling enabled. I am also taking advantage of the new Discard Pipeline option, but nothing seems to work. Thank you for continuing to make performance improvements to PSU btw.. really like the software, but performance is my biggest bottleneck. When I was running via task scheduler it worked great, but obviously that kind of defeats the purpose.

**Comment by adamdriscoll** [comment]
@janszedc Is it possible to try using a non-integrated environment for this script? If you have discard pipeline on and a non-integrated environment, it will be starting and stopping processes so all memory should be reclaimed once the process is terminated. 

That would be similar to what Task Scheduler is doing.

**Comment by DatabaseDylan** [comment]
Here is what my memory looks like when I start up PSU with one dashboard (no scripts/user defined endpoints called yet):
![image](https://user-images.githubusercontent.com/49908138/153643504-a3a8761a-6c03-4736-8678-7bda35792e9a.png)

The moment I run a script (either in PS 7.2 or Integrated) with both -RunspaceRecycling and Discard Pipeline set.. here is what my memory shoots up to and continually rises on each execution:

![image](https://user-images.githubusercontent.com/49908138/153643752-a4d391a6-67f7-4ef0-a702-648aaa1ba777.png)

The script executes in about 10 seconds (doesn't stop until all jobs are complete) and spins up about 30 api calls that are invoked within start-rsjob. I've tried other methods as well where I kept all the logic in functions/scripts themselves, but to no avail. I've also tried invoking endpoints from Task Scheduler, but that didn't work either. Everything seems to make memory climb and rather fast.

**Comment by DatabaseDylan** [comment]
In PS 5.1 I see this message each execution:
![image](https://user-images.githubusercontent.com/49908138/153644651-7e8e8a5e-0df6-49d6-8670-c9536d5ee5df.png)

Maybe the discard pipeline option doesn't work in 7.2? I am going to let this run on 5.1 each minute and watch memory closely. I think it is still rising, but it doesn't seem to be jumping at least. Will report back shortly with an edit to this message.

**Comment by adamdriscoll** [comment]
Discard pipeline output is supported for all platforms. We disable it in a common service that is shared between the environments.

I'm really surprised the memory is growing so much even with external environments like PS7.2. Feel free to upload a memory dump here: https://www.dropbox.com/request/zPau9idxQ8rtMdJSyTT8

You're not doing any caching in your script using Set-PSUCache are you?

**Comment by DatabaseDylan** [comment]
Uploading a memory dump now... Memory was only at 63% (out of 16gb), but this was taken immediately after restarting the service and then letting the script run on the schedule. Immediately goes from 33% - >60%+.

I am indeed using Set-PSUCache, although this was a recent addition in the last 2ish weeks..

```
Set-PSUCache -Key "CollectionStatus" -Value "Gathering data..."
Sync-PSUComponent -Id 'CollectionStatus'

...

Set-PSUCache -Key "CollectionStatus" -Value "The previous collection took $($CollectionRunTime_s.CollectionRunTime_s) seconds. ($($CollectionErrorCount.ErrorCount) errors)"
Sync-PSUComponent -Id 'CollectionStatus'
```

Is it worth upgrading to 2.8.1 as I see there are some performance improvements? I could also remove the Set-PSUCache component if needed.

**Comment by DatabaseDylan** [comment]
Hey @adamdriscoll, any updates here? I keep finding more and more use cases for PSU at my company, but the performance concerns are a major drawback (both CPU and memory). For the time being, I am going to go back to scheduled tasks (yuck) and continue utilizing the dashboard component of PSU because it is awesome!

**Comment by adamdriscoll** [comment]
@janszedc - Can you please try using the new high performance runspace pools? 

https://docs.powershelluniversal.com/config/environments#high-performance-runspace-pools

It should greatly increase throughput and reduce CPU usage. It seems to have a minimal amount of impact on memory but may help there as well.

**Comment by DatabaseDylan** [comment]
Absolutely! Thank you for continually looking into this! However, I've
noticed that a good chunk of CPU is consumed by simply executing a script
since it has to launch a pwsh session, which is necessary to invoke my API
on a schedule.

The only other way I know of to call an API with PSU is to schedule it in
my dashboard, but then the script will only run when the dashboard itself
is open (although now that I'm writing this out I'm wondering if a
scheduled endpoint within a dashboard will still run if activated despite
no clients having it open?).

**Comment by adamdriscoll** [comment]
Yes. The scheduled endpoint will run even if you don't have clients connected. You can also run scripts in the Integrated environment and it will not start a new pwsh process.

**Comment by adamdriscoll** [comment]
We located the source of memory of this memory leak. It actually had to do with our us of the debugger. We've disabled it by default. It was causing dbatools to pin our runspaces so even after they were removed from our pool they would still be allocated in memory. I would recommend trying the latest to see if this is resolved.

**Comment by DatabaseDylan** [comment]
Hey Adam,

This is FANTASTIC news!! Unfortunately, I had to stop developing on PSU a
couple months ago as I had other work items take priority, but now that you
say this is resolved I will definitely try and find some time to test on
the latest version. I sincerely appreciate your persistence on this issue.

Best Regards,
Dylan

**Comment by DatabaseDylan** [comment]
Hey Adam,

Unfortunately the issue appears to be significantly worse. Before updating,
I was letting the service run fine (albeit no scheduled jobs or anything
were running.. just a few dashboards) for several weeks. After updating, I
started the service up and did not touch it and yet it is now consuming
100% memory and forcing me to stop the service. Any ideas?

[image: image.png]

**Comment by adamdriscoll** [comment]
Not what I was expecting. A couple things that I'd like to try: 

## Reduce the max runspace count for your environments. 

Settings \ Environments 

![image](https://user-images.githubusercontent.com/1256531/165798177-411621dc-89e4-4641-b309-b6b888c5b08f.png)

## Manually disable dbatools logging

```
[Sqlcollaborative.Dbatools.Message.LogHost]::MessageLogEnabled = $false
```

**Comment by DatabaseDylan** [comment]
I lowered all 3 environments down to 5 max runspaces. I currently have a
single dashboard running that is extremely simple and only runs a SQL query
when a user loads it up, which is 1x per day. That does use DBATools, but I
went ahead and disabled logging within the dashboard code. Upon restarting
I can see PSUniversal is slowly rising, but I will continue to monitor.

**Comment by adamdriscoll** [comment]
Great. Thanks for trying those items. If you're still having this issue, I think I want to schedule a zoom call to take a look at the environment together. 

One other thing I was thinking about was attempting to use -PersistentRunspace on the environments to completely disable runspace cleanup.

**Comment by DatabaseDylan** [comment]
Just checking back in at end of day and sure enough it has shot back up in
a few hours despite hardly even being used by any users if at all today:

[image: image.png]

I'm happy to jump on a call! =]

**Comment by adamdriscoll** [comment]
Cool. I am traveling tomorrow but can do anytime next week. 

I was able to reproduce a memory issue with dbatools in PSU. I'm not sure if it's the same thing you are seeing but I did a write up about it here: https://forums.ironmansoftware.com/t/dbatools-memory-usage-diagnostics/7031

**Comment by potatoqualitee** [comment]
Hey Adam, anything i can do on this side? I'm sure 1024 messages was a random number. I can knock that down to like 128 or 256 ;) Or whatever you suggest. Performance & internals like this are not my forte :/

**Comment by DatabaseDylan** [comment]
Hey Adam, at one point I think I littered all of my
scripts/dashboards/APIs/etc with the disabling of DBATools logging to
ensure that wasn't the issue. As it currently stands, I did my best to try
and disable everything except a single dashboard that is hardly used while
also adding the disable logging script to the top of the code so we will
see if that has any effect.

I am free to chat 5/2 on a Zoom call if you think that would help.

**Comment by adamdriscoll** [comment]
@potatoqualitee - I think the larger problem is that the dbatools logging uses Get-PSCallstack which pins a bunch of ScriptBlocks which effectively stores all the scripts that were executed in memory. I think adding some option to disable that part of the feature would really reduce the default memory profile. I'd be happy to help work that out with you over on the dbatools repo. Maybe I can come up with a PR. 

@datadill - Sounds good. I'm in UTC-600 so just let me know what time zone you're in and we can get it scheduled. Email me at support@ironmansoftware.com

**Comment by DatabaseDylan** [comment]
I'm free 11AM-1PM Eastern Standard Time.

**Comment by potatoqualitee** [comment]
@adamdriscoll - gosh, yes please. i'm out of my depth when it comes to this and would love an assist.

**Comment by adamdriscoll** [comment]
I think this is resolved. Please open a new issue if you are still having this problem.
