### ISSUE TITLE
SAML Login Not Redirecting in Firefox

### ISSUE THREAD

**Issue by onehit** [ironmansoftware/powershell-universal#899]
https://forums.ironmansoftware.com/t/saml2-authentication-working-in-chrome-edge-but-not-firefox/6536

Logging in through Firefox never redirects to the admin portal post-SAML login

Chromium-based browsers function as expected, fully logging in the user and presenting the admin dashboard

SAML Responses have been validated to be identical in both browsers

I added logging to the roles.ps1 file and discovered the correct username is passed and the user is being assigned an Admin role successfully, so the required data appears to come in from the IDP.

### Expected behavior

```console
PSUniversal redirects to the admin portal after role assignment is successful
```

### Actual behavior

```console
PSUniversal never redirects after role assignment is successful
```

### Environment data

PSUniversal 2.7.3

**Comment by adamdriscoll** [comment]
I can't reproduce this issue in my environment. 

Running Firefox 97.0.2
Shibboleth IDP 4.1.5
Active Directory on Serve 2022

What's the experience in Firefox? Blank screen or sits at the login screen?

**Comment by adamdriscoll** [comment]
I can't reproduce this in 2.9. If you are still experiencing this issue, feel free to reopen.
