### ISSUE TITLE
Script editor to support Ctrl+A (Select All)

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#908]
### Summary of the new feature / enhancement

Consider adding support into the Script Editor for the Ctrl+A keyboard shortcut (Select All) functionality. Also to the right-click context menu.

![image](https://user-images.githubusercontent.com/537287/152299658-182e245b-cf3a-42e7-86e3-6a233ef86788.png)

**Comment by DataTraveler1** [comment]
I would also suggest adding the keyboard shortcut descriptions of Cut, Copy and Paste to the context menu.

**Comment by adamdriscoll** [comment]
Ctrl+A works. Cut copy and paste shortcuts work as well but aren't listed. Not going to worry about this one.
