### ISSUE TITLE
[Script Editor] Add Ctrl+S functionality

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#910]
### Summary of the new feature / enhancement

Consider implementing the Ctrl+S (Save) functionality to the keyboard shortcuts in the Script Editor. Currently, using this shortcut opens the browser's save dialog.

![image](https://user-images.githubusercontent.com/537287/152305899-850ef177-ceae-430f-be5e-e53bd4b4d685.png)

### Proposed technical implementation details (optional)

Associate this keystroke with the application's Save function

![image](https://user-images.githubusercontent.com/537287/152306144-f71c97c6-1e01-406a-a428-a34ecea7da52.png)

**Comment by adamdriscoll** [comment]
This was actually implemented in 2.7.x somewhere so this is a bug. Which editor was this for?

**Comment by DataTraveler1** [comment]
> This was actually implemented in 2.7.x somewhere so this is a bug. Which editor was this for?

Sorry that this wasn't clear. The script editor with the issue is under _Automation_ -> _Scripts_

![image](https://user-images.githubusercontent.com/537287/152642723-4522d7ee-264e-426c-a1df-88a3f63303a9.png)

None of the other script editors (e.g. _API_ -> _Endpoints_) seem to be affected.

Edit: forgot to mention that the version of PowerShell Universal is 2.7.3

**Comment by DataTraveler1** [comment]
@adamdriscoll actually, this seems to be fixed in the current 2.8.0 nightly build
