### ISSUE TITLE
There is no create just a file option for powershell in the VS 2022 

### ISSUE THREAD

**Issue by Woody033** [ironmansoftware/powershell-universal#915]
**Describe the bug**
There is no option to create just a new PS file in the menu, only create projects

**To Reproduce**
Steps to reproduce the behaviour:
1. Start VS 2022
2. Click on File -->New-->File
**Expected behavior**
I would expect that i can open a new file

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/20205685/152554696-4921e8d1-ea6a-424a-a33f-2483f439dd2c.png)

**Version**
[Microsoft Visual Studio Community 2022 - Version 17.0.5.txt](https://github.com/ironmansoftware/issues/files/8004184/Microsoft.Visual.Studio.Community.2022.-.Version.17.0.5.txt)
PowerShell Tools For VS 2022 Version Number: 2022.1.0
Operating System:  Windows 10 Pro Version 21H2 Installed on 2022-‎01-‎27 

**Additional context**
During the install process there is an error message that pop up. But I will include the log files. Sorry, but I was not able to get a screenshot at the time.  After the install, it did say there was an update available, but there was nothing to update.  

**Logs** 
[- DxDiag](https://github.com/ironmansoftware/issues/files/8004285/DxDiag.txt)
[- Event log critical errors - during initial install](https://github.com/ironmansoftware/issues/files/8004260/PS.Pro.errors.csv) 
[- Event log critical errors - during uninstall and reinstall
](https://github.com/ironmansoftware/issues/files/8004278/PS.Pro.errors.during.uninstall.and.reinstall.csv)
 
[- Install log - dd_VSIXInstaller_20220204090540_4040.log](https://github.com/ironmansoftware/issues/files/8004297/dd_VSIXInstaller_20220204090540_4040.log)
[- Install log - dd_VSIXInstaller_20220203120919_3ee8.log](https://github.com/ironmansoftware/issues/files/8004298/dd_VSIXInstaller_20220203120919_3ee8.log)

**Comment by adamdriscoll** [comment]
I checked with Microsoft and adding to the New File dialog is not possible through an extension. 

If you want this functionality, you can create a PS1 file here: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\NewFileItems

Once that's done, you'll be able to select it from the New File dialog. 

![image](https://user-images.githubusercontent.com/1256531/178323625-2cdcebfa-9a03-4a3e-848a-cc816315648f.png)

**Comment by Woody033** [comment]
Thank you Adam 👍
