### ISSUE TITLE
Security: Roles are not properly enforced for Windows Authentication outside of IIS

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#916]
### Steps to Reproduce

Run PowerShell Universal as a service or just as a kestrel process
Configure authentication using Windows Authentication 
Create an API endpoint that requires authentication and a role 
Access the endpoint without the role 
Authentication is still required

### Expected behavior

```console
Roles should be properly enforced.
```

### Actual behavior

```console
Roles are not properly enforced.
```

### Environment data

2.7.3

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/invoke-restmethod-with-usedefaultcredentials-will-execute-api-and-ignore-roles-security/6568/2

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/psu-caching-ad-cred/6570/2

**Comment by Viajaz** [comment]
@adamdriscoll Was this the issue brought up in "Security Notice: PowerShell Universal Authorization Bypass" email on 2022-02-04 (UTC)?
