### ISSUE TITLE
UniversalDashboard module install error: 'Start-UDDashboard already available'

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#919]
## Synopsis
Attempting to install the UniversalDashboard PowerShell module may fail under certain circumstances.

### Step 1
Ensure that neither modules Universal or UniversalDashboard are installed. The below command should return empty results.

```
Get-Module -Name Universal, UniversalDashboard -ListAvailable
```

### Step 2
Install Universal

```
Install-Module -Name Universal -Scope CurrentUser
```
### Step 3
Install UniversalDashboard

```
Install-Module -Name UniversalDashboard -Scope CurrentUser
```

See Visuals for screenshot

### Expected behavior

```console
The UniversalDashboard module should install without error following the installation of Universal.
```

### Actual behavior

```console
The below error message will result and the UniversalDashboard module will not be installed.

> Install-Package: The following commands are already available on this system:'Start-UDDashboard'. This module 'UniversalDashboard' may override the existing commands. If you still want to install this module 'UniversalDashboard', use -AllowClobber parameter.
```

### Environment data

Windows 10 21H2
PowerShell 7.2.1
Module scopes are CurrentUser

### Visuals

![image](https://user-images.githubusercontent.com/537287/152628103-9fc0f5ae-8033-47af-91bb-5706b68947d7.png)

The workaround per @adamdriscoll is to include the -AllowClobber parameter (see related forum post [here](https://forums.ironmansoftware.com/t/new-uddashboard/4484)).

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/new-uddashboard/4484/9
