### ISSUE TITLE
VS code extenstion should have empty token by default

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#922]
### Summary of the new feature / enhancement

On the first attempt to use the VS Code extension for PowerShell Universal there will be an error 401

![image](https://user-images.githubusercontent.com/537287/152674018-73a1ebc9-91a0-45c6-9f63-3cca43a24abb.png)

After clicking through to go to the settings, the user will be presented with the app token dialog but it is already populated with an example token(?). This example token (which does not authenticate successfully) has the potential to cause confusion as it may not be clear to the user if it's OK to remove it.

![image](https://user-images.githubusercontent.com/537287/152674040-0ccd987e-5539-4e17-b7e6-bba4d8a1eed5.png)

### Proposed technical implementation details (optional)

Replace the example token with a warning text that directs the user on how to generate their token.

Ideally, also include the first few characters of an example token in the direction (e.g. '_eyJhbG_') so that the user will know they are on the right track once they do generate their token.

**Comment by adamdriscoll** [comment]
I've changed how this works and this will no longer happen.
