### ISSUE TITLE
Add ability to export token details

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#923]
## Request 1
Add a button in the token menu to export the full details of the token (e.g. expiration date) to some format such as a .csv file, a JSON string to the clipboard, etc. (pictured below with Request 2)

## Request 2

In the token menu, extend the tool-tip description for the Copy button

'_Copy_' --> '_Copy Token_'

![image](https://user-images.githubusercontent.com/537287/152674446-5a272003-a7da-4f03-8c2c-855f901baaf6.png)

**Comment by adamdriscoll** [comment]
This can be determined with external tools like jwt.io.
