### ISSUE TITLE
VS Code: Failed to query configuration files (code 403)

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#924]
### Steps to Reproduce

1. Create an identity with less than admin role (e.g. Execute role)
2. Create a token for that identity with the same role (e.g. Execute role)
3. Configure the VS Code extension to use that token
4. Receive error 403 regarding unable to read configuration files

![image](https://user-images.githubusercontent.com/537287/152676045-90294e7f-541d-40dc-8b82-173a21b04946.png)

## Workaround

1. Use a token with the Admin role instead (or just disregard the error message since it only pertains to the Configuration box)

Thanks to [this](https://forums.ironmansoftware.com/t/vs-code-extension-failed-to-query-configurations/4644/5?u=datatraveler) forum post for the hints.

### Expected behavior

```console
There should not be any errors thrown in this scenario. Instead, the Configuration box should state that it is unavailable due to lack of Admin privilege.
```

### Actual behavior

```console
The user is still able to otherwise use the extension but is confusing for someone who is new and not already familiar with the application.
```

### Environment data

Windows 10
PowerShell Universal 2.7.4 (MSI install)
PowerShell Universal - VS Code extension 2.5.0
(all fresh installs)

**Comment by adamdriscoll** [comment]
I've changed how the extension works by simplifying it a bit. It used to attempt to issue an app token automatically which could cause this issue. This caused lots of problems similar to this one. Now it will just prompt and provide a link to the app tokens page.
