### ISSUE TITLE
Let’s encrypt integration

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#925]
### Summary of the new feature / enhancement

I don’t know if it’s possible but it would be perfect with let’s encrypt integration so you can get free ssl certs.

As they are looking for the text file to verify trough port 80. I guess that it should be possible.

**Comment by adamdriscoll** [comment]
This is likely something we wouldn't integrate directly into PSU. It might be possible to achieve this with PoshAcme and published folders.
