### ISSUE TITLE
vscode extension can't connect if SSL cert are self signed

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#926]
### Steps to Reproduce

If your PSU server has a self signed SSL cert you can't connect to it with the vscode extension.
For more info see;
https://forums.ironmansoftware.com/t/vscode-module-psu-how-trust-self-signed-cert/6582

### Expected behavior

```console
Somehow allow connection to psu servers with self signed certs.
```

### Actual behavior

```console
Can't connect it complaining about the cert
```

### Environment data

PSU 2.7.4 and latest vscode extension

**Comment by adamdriscoll** [comment]
This issue has been mentioned on **Ironman Software Forums**. There might be relevant details there:

https://forums.ironmansoftware.com/t/vscode-module-psu-how-trust-self-signed-cert/6582/4

**Comment by rwidmark** [comment]
Issue are still here, I was just trying it out.
<img width="449" alt="Screenshot 2022-03-13 at 15 44 35" src="https://user-images.githubusercontent.com/76907327/158065068-f81e4d86-254e-491e-879c-a2a2da6c8e88.png">

@adamdriscoll
