### ISSUE TITLE
TypeError when creating a new script

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#929]
### 1. Create a new script like below

![image](https://user-images.githubusercontent.com/537287/152780968-760d7b68-076e-4904-a857-3bc08915a387.png)

### 2. After the "Creating new script" completes the page will turn to below error

![image](https://user-images.githubusercontent.com/537287/152781257-2b7dc398-ca45-44dc-8417-dd062c34a2fa.png)

### Expected behavior

```console
The script should be created without any errors
```

### Actual behavior

```console
The user is brought to an error message. However, there is no other impact and the script is still created.
```

**Comment by adamdriscoll** [comment]
Nice catch! Thanks.
