### ISSUE TITLE
Connect-PSUServer should return back an object if it successfully connects

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#931]
### Summary of the new feature / enhancement

A status object returns from the [Connect-PSUServer](https://github.com/ironmansoftware/universal-docs/blob/master/cmdlets/Connect-PSUServer.txt) cmdlet when successfully invoked.

### Proposed technical implementation details (optional)

Ideally, the status object would have some basic information including a boolean for whether or not a token was used to establish the session.

**Comment by adamdriscoll** [comment]
I agree. This is a breaking change since it affects the pipeline. I'll move it into our 3.0 release.

**Comment by adamdriscoll** [comment]
We'll be returning info like: Username, roles, one-way git sync status, server-mode and access controls.

**Comment by DataTraveler1** [comment]
![image](https://user-images.githubusercontent.com/537287/174205743-2ac6108d-aae2-40bc-8238-a42b300aee9c.png)

@adamdriscoll - Looks great! 👍
