### ISSUE TITLE
$Roles Dashboard variable returns no value in PSU 2.8.0 (Windows auth)

### ISSUE THREAD

**Issue by ad-85** [ironmansoftware/powershell-universal#941]
### Steps to Reproduce

Updating to PowerShell Universal caused my dashboard pages to reject all incoming users, as the $Roles variable was not returning any values with Windows authentication.

### Expected behavior

```console
$Roles should return all SIDs the user has claim to as well as the Roles PSU has already assigned, e.g. 
S-1-5-21-112361945-1364589140-839522115-513
S-1-1-0
S-1-5-32-544
S-1-5-32-545
S-1-5-2
S-1-5-11
S-1-5-15
[...]
VALID_AD
Administrator
```

### Actual behavior

```console
$Roles returns null or empty value.
```

### Environment data

PSU version 2.8.0, Windows Server 2016, Windows authentication.

**Comment by ad-85** [comment]
Oddly enough, when reverting to 2.7.4 I noticed that $Roles in that version returns its values in triplicate. Unsure if this is related to same cause as the issue in 2.8.0.

**Comment by adamdriscoll** [comment]
I see the triplicate issue but not the loss of roles. Are you hosting in IIS or Kestrel?

**Comment by ad-85** [comment]
Kestrel.

**Comment by adamdriscoll** [comment]
Ok. I will continue to investigate. Thanks

**Comment by adamdriscoll** [comment]
Issue was with a standard license that did not activate properly. Adding an offline license fixed this issue. 

This issue would help identify this faster: #921
