### ISSUE TITLE
Failed to load Swagger API definition.

### ISSUE THREAD

**Issue by passcodex** [ironmansoftware/powershell-universal#950]
### Steps to Reproduce

**Steps to Reproduce**
Open http://localhost:5000/swagger/index.html, 
then Failed to load API definition. 
Internal Server Error /swagger/v1/swagger.json

### Expected behavior

```console
No 500 ERROR
```

### Actual behavior

```console
/swagger/v1/swagger.json 500 ERROR
```

### Environment data

2.8.0

### Visuals

![image](https://user-images.githubusercontent.com/11014056/153567761-093d6ccb-8d56-4f74-b6ed-836e8576723f.png)

**Comment by adamdriscoll** [comment]
This has been fixed and an integration test added so this won't happen again.
