### ISSUE TITLE
Disallow creation of a script with ".ps1" at the end of the name in the PSU UI

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#960]
### Summary of the new feature / enhancement

When creating a new script in the _PowerShell Universal_ console (UI) it is possible to create a redundantly named script by including '.ps1' as the end of the 'Name' property. This is seemingly contrary to how **New-PSUScript** operates.

![image](https://user-images.githubusercontent.com/537287/153727199-4d2cbb39-9b0d-4d77-9095-663aa1eddce5.png)

Currently, the UI interface allows this (pictured below)

![image](https://user-images.githubusercontent.com/537287/153727228-7845d436-d623-4323-9b13-c734b46264c7.png)

### Proposed technical implementation details (optional)

Add a filter to disallow '.ps1' as the final 4 characters of the Name property of the script. Imagined 💭 with composite image below.

![image](https://user-images.githubusercontent.com/537287/153727294-59a202e5-e7fb-4f59-9c6c-dac41fd3282e.png)

**Comment by penser-jata** [comment]
This seems like a rather unfriendly and complicated way of handling the issue.
Why not do the obvious instead: If the user has already provided a .ps1 suffix, don't add it once more.

This is what users expect and how even the most primitive apps in Windows behave.
Try it in Notepad: If you write foo in the save as file name box you will get a file named "foo.txt".
If you write foo.txt in the box you will _also_ get a "foo.txt" (and not "foo.txt.txt" )

**Comment by adamdriscoll** [comment]
@penser-jata That's how I'll fix this.
