### ISSUE TITLE
[PowerShellUniversal.Endpoint] should have a CreatedTime property

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#962]
### Summary of the new feature / enhancement

When a new script is created with **New-PSUScript**, a _CreatedTime_ property is included with the `[PowerShellUniversal.Script]` object type.

Consider adding the same property to `[PowerShellUniversal.Endpoint]`.

![image](https://user-images.githubusercontent.com/537287/153765030-b9a862ee-e3a7-4632-9ad9-f3a59e5a94a0.png)

### Proposed technical implementation details (optional)

There may be other properties which are included in the script object that would be helpful to have ported over to the endpoint object as well.

**Comment by adamdriscoll** [comment]
We should probably just remove the Script.CreatedTime because it doesn't really make sense. When you restart the server, the value will be reset so it's not really valid anyways. We should probably provide some way associate with git history.
