### ISSUE TITLE
Measure-PSUBlock hangs if the Name parameter is not specified

### ISSUE THREAD

**Issue by DataTraveler1** [ironmansoftware/powershell-universal#964]
### Steps to Reproduce

1. Create a script for profiling within the _PowerShell Universal_ console which includes **Measure-PSUBlock** per the example in the documentation [here](https://docs.powershelluniversal.com/development/profiling)

2. Include a scriptblock for the -ScriptBlock parameter but accidentally forget to include a string for the -Name parameter

### Expected behavior

```console
The Name parameter should be mandatory for Measure-PSUBlock
```

### Actual behavior

```console
If the Name parameter is omitted, Measure-PSUBlock will hang forever in 'waiting for feedback' status
```

### Environment data

PowerShell Universal 2.8.2 (nightly build 2022-02-12)

### Visuals

![image](https://user-images.githubusercontent.com/537287/153773269-9256fd12-ac27-462c-bfc1-22e504b7ca9d.png)
###### (figure illustrates a job stuck in '_waiting for feedback_' status)

**Comment by adamdriscoll** [comment]
The -Name parameter is mandatory so I wonder if we have a different problem where it's waiting for feedback since a mandatory parameter is missing.

**Comment by adamdriscoll** [comment]
I'm closing this because it behaves as expected. You'll see that you can enter the name by clicking the Respond to Feedback button. 

![image](https://user-images.githubusercontent.com/1256531/158473701-6e7c09e8-1da3-483c-b2fb-2fc81629e197.png)

**Comment by DataTraveler1** [comment]
@adamdriscoll - Thank you for explanations
