### ISSUE TITLE
Restart of service required when externally installing a module

### ISSUE THREAD

**Issue by adamdriscoll** [ironmansoftware/powershell-universal#978]
### Steps to Reproduce

Install a module from the gallery into the AllUsers scope requires a restart of the PSU service before they can be used within the platform. 

### Expected behavior

```console
Installing a module with Install-Module -Scope AllUSers should be available to PSU
```

### Actual behavior

```console
Requires a restart before it is available.
```

### Environment data

2.8.1

**Comment by sgaglione** [comment]
i would include the concept of newer versions of existing modules as well.  i know some of my personal module revisions can be excessive at times 😄

**Comment by adamdriscoll** [comment]
We will be providing guidance on external modules but any module in the Repository\Modules folder will now automatically cause a refresh in runspace state in PSU when changed. #1920

Our next step will be to monitor for external module changes but it will only be looking at versions and not the content of those modules and comparing them with the previous run.
