### ISSUE TITLE
VS Breakpoint removed at Save / CTL-S

### ISSUE THREAD

**Issue by pju55** [ironmansoftware/powershell-universal#985]
**Describe the bug**
I'm testing VS 2022 Community version 17.0.5 with Pro Tools 2022.2.1.
I experience random deletion of breakpoints for instance at save of file.
I also - worse - see it sometimes when starting the debugger ie pressing F5. 

My up front question is - is that on your table or is it a VS issue?

I have attached a smal screen dump video to show the deletion on save.

No evidence on delete on debug start. 
But - it seems that when VS goes in "delete breaktpoint on debug start", breakpoint setting "Condition"  somehow has been checked. And it seems that if I uncheck "Condition", breakpoints works for a while again.
I'll try to catch it if needed.

**To Reproduce**
Steps to reproduce the behavior (random):
1. Set a breakpoint
2. Start debug a run to breakpoint.
3. Stop debugging
4. Make any change
5. Press CTL-S or as shown (outside recording ;-) ) use manu "File->Save"
Breakpoint disappears.

**Expected behavior**

**Screenshots**

**Version**

Tool (Visual Studio, VS Code, PSScriptPad, PS Module):  VS 2022 Community
Version Number: version 17.0.5
Operating System:  Win10 21H2 Build 19044.1526

**Additional context**

**Logs** 

Please upload a log. Logs are found in $Env:AppData\PowerShellProTools\ by default.

https://user-images.githubusercontent.com/32414636/154288874-576dd9e9-6ceb-48b5-ace9-bfae3e0bffb9.mp4

Best regards and thanks for a great product.
Poul

BTW: have not seen the problem in VS2019 - makes sense if somehow connected to the new breakpoint design.

**Comment by pju55** [comment]
Problem also occur when changing code while debugging and subsequent restart. 
Makes sense - an implicit save

https://user-images.githubusercontent.com/32414636/154297070-cdbaf408-097f-43a7-9204-a0619688ff1a.mp4

.

**Comment by adamdriscoll** [comment]
I'll look into this. It seems like it may be a problem with PowerShell Tools and not Visual Studio.

**Comment by pju55** [comment]
Thanks :-)

Sorry having mislead you -  the problem also exist in VS2019.
I had missed the latest Powershell Tool update.
Went back to PowerShellTools.2022.1.0.vsix and I'm good.

**Comment by adamdriscoll** [comment]
Do you have this extension installed? 

https://marketplace.visualstudio.com/items?itemName=mynkow.FormatdocumentonSave

I can reproduce this issue when I use the Format Document command (Ctrl+K, Ctrl+D) but haven't reproduced it yet on save. But if you have Format On Save installed, it would be running the formatter when saving and causing the breakpoints to be removed.

**Comment by pju55** [comment]
Spot on.
I have this one which also removes trailing whitespace on save:

https://marketplace.visualstudio.com/items?itemName=MadsKristensen.TrailingWhitespaceVisualizer

**Comment by adamdriscoll** [comment]
Cool. I will see what I can do to fix the issue with the formatter.
