### ISSUE TITLE
Option to hide "run as" throughout PSU

### ISSUE THREAD

**Issue by HansenRene** [ironmansoftware/powershell-universal#987]
### Summary of the new feature / enhancement

It would be nice to be able to hide the run as options basically everywhere, in situations where your IIS apppool identity is a serviceaccount, where the feature isn't supported.

### Proposed technical implementation details (optional)

![image](https://user-images.githubusercontent.com/20628942/154344262-3de4969a-e9f5-415a-bc71-6b94c9e19b5f.png)

hit me up if you need a front end guy man.

**Comment by adamdriscoll** [comment]
https://media.giphy.com/media/p8GJOXwSNzQPu/giphy.gif
