### ISSUE TITLE
Array in variables.ps1

### ISSUE THREAD

**Issue by rwidmark** [ironmansoftware/powershell-universal#989]
### Summary of the new feature / enhancement

Make it possible to store arrays in variables.ps1

**Comment by rwidmark** [comment]
@adamdriscoll can this be in 2.9.1? Or is it going to be 3.0? :)

**Comment by adamdriscoll** [comment]
I'll get it in a 2.x release. We will still be doing small features for 2.x going forward. It'll probably go in 2.10
