### ISSUE TITLE
New-PSUSchedule -OneTime not working

### ISSUE THREAD

**Issue by rachaelsingleton** [ironmansoftware/powershell-universal#998]
### About 

New-PSUSchedule -OneTime does not work and throws an error in PowerShell. 

```
$date = [datetime]"2/14/2022 4:00PM"

New-PSUSchedule -Description "Scheduled server restart" -Script "Servers\Restart-Servers.ps1" -Servers "Test" -OneTime $date

```
#### Description

```New-PSUSchedule : Sequence contains no matching element
At line:1 char:1
+ New-PSUSchedule -Description "Scheduled server restart" -Script "Serv ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-UASchedule], InvalidOperationException
    + FullyQualifiedErrorId : System.InvalidOperationException,UniversalAutomation.Cmdlets.NewScheduleCommand
```

In the logs I see the following: 
```2022-02-04 15:02:24.106 -05:00 [ERR] Failed to schedule job. CRON expression is invalid. Please see the inner exception for details. (Parameter 'cronExpression') Wrong number of parts in the `0 0 9 ? 1/1 1L *` cron expression, you can only use 5 or 6 (with seconds) part-based expressions.```

#### Version Information

- Universal: 2.7.4
- Universal Hosting Method (IIS, Executable, docker etc): Exe
- PowerShell: 5.1
- Operating System: 2022

**Comment by adamdriscoll** [comment]
The reason -Description had to be used is because the parameter is actually -Name. The problem is in the UI, it says description rather than name. I'll get that fixed. We assume UTC for all schedules. You can set the time zone with time -TimeZone parameter. 

```
New-PSUSchedule -Script "Test.ps1" -TimeZone "America/Denver" -Credential "Default" -OneTime '2022-03-08T18:18:00Z' -Name "My Description"
```
